### PR TITLE
My Site Dashboard: update the dashboard after a new site is created

### PR DESCRIPTION
**Pull request by leandroalonso**
Part of #17873 

This PR fixes the state of the dashboard after creating a new site and if the user triggers the Quick Start, it is shown.

Basically, there are two states:

1. If the flag is **disabled**, all should behave as it is right now
1. If the flag is **enabled**, the dashboard is the default after a site creation

#### With the flag DISABLED

1. Do a fresh install of the app
2. Create a new site
3. Accept Quick Start
4. ✅ You should see the site menu and the quick start steps

##### New account and new site

1. Open the app and enable the My Site Dashboard feature flag
3. Log out
4. Create a new account
6. Create a new site
5. Accept the help
7. ✅ Check that the dashboard is shown with the Quick Start
9. Close the app and reopen
10. ✅ The dashboard is shown

##### Creating a new site

1. Delete the app
2. Run and log in with an account with sites
3. Close and reopen the app
4. ✅ Check that "Site Menu" is the default
5. Create a new site and accept the help
7. ✅ Check that the dashboard is shown with the Quick Start
9. Close the app and reopen
10. ✅ The dashboard is shown
11. Switch between sites, the selected tab should stay the same

## Regression Notes
1. Potential unintended areas of impact
n/a

3. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a

4. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by leandroalonso** [comment]
@pachlava as [per this comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/17943#issuecomment-1036439504) it would be awesome to have your review in this.

**Comment by pachlava** [comment]
Just leaving a note that I've posted #18099 which is not related to this PR, but maybe(?) has something to do with the recent FAB related changes.

**Review by momo-ozawa — COMMENTED** [review]
@leandroalonso I found two issues while testing this PR

#### Dashboard post cell empty on first load

I'm not sure if this is 100% reproducible but I saw the empty post cell issue that we've seen a couple of times in the past.

1. Open the app and enable the My Site Dashboard feature flag
2. Log out
3. Create a new account
4. Create a new site
5. Accept Quick Start prompt
6. Tap "Home"
7. 👀 Notice that the post cell is empty
8. Pull to refresh
9. 👀 Notice that the post cell display "Create your first post"

#### Creating a new site from the dashboard displays site menu under dashboard

If you trigger the site creation flow from the dashboard, then the site menu vc gets embedded underneath the dashboard vc. 


https://user-images.githubusercontent.com/6711616/157215651-5670fc30-5e44-4dbb-bd23-537fde758b60.MP4

**Comment by leandroalonso** [comment]
@pachlava I haven't fixed the iPad issue you mentioned [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/18101#issuecomment-1062730335) yet.

But besides that this is PR is ready for review if you have some time, thank you so much!

**Review by pachlava — APPROVED** [review]
I explored a bit more on iPhone/iPad, and while it looks some issues still exist, I think they aren't directly related to the PR. I'm giving the :shipit: from my side, but still list the issues for the record:

1. The issue mentioned by @momo-ozawa [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/18096#pullrequestreview-902811537) (first issue) still exists:

Screenshot 2022-03-10 at 11 09 20

2. It looks like on iPad (with `Home` selected), the newly added scheduled/draft posts are not added to the cards unless user switches to other cell and back to `Home` again.

Please let me know if I should create a separate issues for any/both of these.

**Comment by leandroalonso** [comment]
@pachlava could you please create those issues? This way we don't lose track of them and I can create smaller and easier to test PRs. :)

**Comment by leandroalonso** [comment]
@pachlava 

> It looks like on iPad (with Home selected), the newly added scheduled/draft posts are not added to the cards unless user switches to other cell and back to Home again.

Could you please share a video of that?

**Comment by leandroalonso** [comment]
> The issue mentioned by @momo-ozawa https://github.com/wordpress-mobile/WordPress-iOS/pull/18096#pullrequestreview-902811537 (first issue) still exists:

@pachlava @momo-ozawa I believe #18114 fixed that. :)

**Comment by pachlava** [comment]
Tried to reproduce the first issue from [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/18096#pullrequestreview-905579491), while being on #18114, and it looks fixed. However, there are such differences as still old segments order and `Home` not being default, which makes me not 100% sure about starting preconditions for the fix check.

For the second issue, here's the bug: #18122

**Pull request merged**
