### PR TITLE
Sanitize Email for Gravatar Hash Creation

### LINKED ISSUE #6270: Me: App doesn't load Gravatar when account email includes capital letters
### Expected behavior

I expect to always be able to upload and see my account's Gravatar on the Me tab when logged in.

### Actual behavior

If my account email includes capital letters, I can upload a new Gravatar (and it appears on Gravatar.com) but if I close the app and reopen it, the Gravatar is gone.

### Steps to reproduce the behavior

1. While logged out of the WordPress app, select "Create a site"
2. Create a new account and site, using an email address with capital letters
3. On the Me tab, add a new Gravatar
4. Confirm the Gravatar is added and appears on the Me tab
5. Swipe to close the app
6. Reopen the app. Result: The Gravatar is no longer there
7. Update the account's email address to replace the capital letters with all lowercase letters
8. Reopen the app. Result: The Gravatar you uploaded previously appears

##### Tested on iPhone 6, iOS 10.1.1, WPiOS 6.8.0.20161129

### PR DESCRIPTION
**Pull request by astralbodies**
Fixes #6270 

Gravatar URLs should be constructed with a hash based off of the e-mail address (or URL for Blavatar) with the following sanitization ([per Gravatar documentation](https://en.gravatar.com/site/implement/hash/)):
1. Trim leading and trailing whitespace from an email address
2. Force all characters to lower-case
3. md5 hash the final string

To test (based on @rachelmcr's steps):

1. While logged out of the WordPress app, select "Create a site".
2. Create a new account and site, using an email address with capital letters.
3. On the Me tab, add a new Gravatar.
4. Confirm the Gravatar is added and appears on the Me tab.
5. Swipe to close the app.
6. Reopen the app. Verify the Gravatar is still there.

Needs review: @jleandroperez

### CODE REVIEW

**Comment by jleandroperez** [comment]
Having issues with this one. The Gravatar seems not to be downloaded afterwards.

Using a testing account that looks like: ```xxxxx+test@gmail.com```

**Comment by astralbodies** [comment]
@jleandroperez I discovered the cause of the issue. Here's what's happening:

1. Create a new account, e-mail address is sanitized properly.
2. My Profile screen loads, AFNetworking UIImageView extension attempts to load Gravatar for the e-mail address. 404 is returned per the URL parameters. This response is BEING CACHED.
3. New Gravatar uploaded. UI updates.
4. Force-quit and re-launch the app - the 404 cached response is returned. Mystery man is shown.

I have to figure out a way to empty the AFNetworking private cache for the UIView extension after uploading a new Gravatar...

**Comment by astralbodies** [comment]
It looks like I don't have direct access to the NSURLCache that AFImageDownloader is using and have no way to clear it out. After five minutes, however, that cache expires and the request would go out over the Internet again (after a force quit).

**Comment by jleandroperez** [comment]
@astralbodies I'm late for the party... just in case it's still useful... [this is the hack](https://github.com/wordpress-mobile/WordPress-iOS/pull/5058/files#diff-09dfb3be101c89e6b35fc9be65e4e288R65) we use to override NSURLCache's entry.

Maybe... we can do something similar to nuke just that request?

**Comment by jleandroperez** [comment]
@astralbodies ahhh ... right... please... [see these notes](https://github.com/wordpress-mobile/WordPress-iOS/pull/5058/files#diff-09dfb3be101c89e6b35fc9be65e4e288R65)... i think many of the NSURLCache methods were broken. Awesome...

**Comment by astralbodies** [comment]
@jleandroperez Yup that's what I ended up updating. I removed the call to the global shared NSURLCache as the AFNetworking image downloader does not use that one at all. I end up wiping all the url request caches out to prevent the five minute cached 404 or old image. 

Ready for you to review again.

**Comment by jleandroperez** [comment]
### Update:
I've followed the following steps (on the device):

1. Created new account
2. Uploaded a new Gravatar
3. Killed + relaunched
4. **The gravatar was missing**
5. Killed + relaunched again
6. Uploaded a *new* gravatar
7. Killed + relaunched yet again
8. The new new gravatar was onscreen (Step 6)

Given the facts that:
- This happens whenever the user signs up and enters an email in caps
- Uploads a gravatar and
- Effectively kills and relaunches the app in less than 5 minutes

Even though this PR adds a "Purge Cache" call, the SDK's API seems to be broken. Since (IMHO) this is a very low occurrence bug, i'd vote we :shipit:, and maybe file a radar, so that someday NSURLSession's purge helpers get fixed.

**Comment by astralbodies** [comment]
@jleandroperez 
> This happens whenever the user signs up and enters an email in caps
Actually the missing Gravatar will happen with everyone signing up through the app for the first five minutes because of the pre-cached 404 (unless they already have a Gravatar with that e-mail address).

**Comment by astralbodies** [comment]
Thanks for reviewing!! @rachelmcr there's a small caveat with your testing that'll need to know about the cached missing Gravatar. Let me know if the issue is clear enough otherwise ping me and I'll walk through it so its noted in your test plans.

**Comment by rachelmcr** [comment]
Thanks, that's clear! If I run into any confusion while testing I'll ping you.

**Pull request merged**
