### PR TITLE
Site Pages: replace No Results view

### LINKED ISSUE #9982: Site Pages: replace No Results view
For Site Pages, replace `WPNoResultsView` with `NoResultsViewController`.

The No Results view is displayed when:
- Fetching sites.
- No published.
- No drafts.
- No scheduled.
- No trashed.
- No connection.

Current View Examples:
nrv

connection

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #9982 

The No Results view is displayed when:
- Fetching pages.
- No published.
- No drafts.
- No scheduled.
- No trashed.
- No connection.

NOTE: There are constraint warnings in the logs. These are pre-existing and are not related to the NRV.

To test:

---
**Fetching sites:**
- On a slow network, go to Site Pages.
- Verify the view is:
fetching

---
**No published/drafts/scheduled:**
- Go to Site Pages.
- Select a page type other than trashed.
- The message will change according to each type.
- Verify the view is:
drafts

---
**No trashed:**
- Go to Site Pages.
- Select trashed.
- Verify the view is:
trashed

--- 
**No connection:**
- With no internet connection, go to Site Pages.
- Verify the view is:
connection

### CODE REVIEW

**Comment by aerych** [comment]
Howdy @ScoutHarris 

I took the branch for a spin.  

❌ Fetching sites
✅ No published/drafts/scheduled
✅ No trashed
✅ No connection

To test fetching, I set Network Link Conditioner to Edge. I always saw the no results view vs the fetching message, then the pages would just appear.

**Comment by ScoutHarris** [comment]
Hey @aerych . Thanks for finding the issue with fetching! It's been fixed. There is a little oddity in that `syncHelper.isSyncing` is initially `false`, which means the no results is displayed first, then the fetching is displayed as `syncHelper.isSyncing` goes to `true`, then the final view is displayed when syncing is done. But the NRV is showing correctly according to the sync state.

fetching

**Comment by aerych** [comment]
When the controller first appears the NRV is visible, then it switches to say Fetching.  It goes by pretty quick.  I can see it in the gif you posted and maybe even a bit more clearly in this one. 
nrvgif

It'd be a nice bit of polish to have the nrv be completely hidden initially so there's not a switch from it to fetching.

**Comment by ScoutHarris** [comment]
> It'd be a nice bit of polish to have the nrv be completely hidden initially so there's not a switch from it to fetching.

Yep, it would be nice. I'll open a separate issue since it's not directly related to NRV replacement and was pre-existing.

**Comment by aerych** [comment]
Sounds good!

**Comment by ScoutHarris** [comment]
New issue for NRV/loading display order: https://github.com/wordpress-mobile/WordPress-iOS/issues/9993

**Pull request merged**
