### PR TITLE
Fix #22283: child pages are not moved under parent pages

### LINKED ISSUE #22283: Pages are not displayed in a hierarchy
Reported by user [here](https://a8c.slack.com/archives/C04HB8JU78A/p1703315190170519), and I confirmed it on my site that I used for testing pages hierarchy.

Screenshot 2023-12-23 at 9 35 14 AM 

Screenshot 2023-12-23 at 9 35 27 AM

### PR DESCRIPTION
**Pull request by crazytonyli**
## Issue

See #22283 for the issue. The issue is pretty easy to reproduce and it's my mistake that I didn't double check the app after a refactor. For context, the issue happens when a child page presents before a parent page in a pages array, which should be pretty common.

## Details

When building a page tree, the elements in a pages array are processed one by one. When a child page is processed before its parent page, it is treated as an "orphan node" util it's parent page is later added to the tree. When adding the parent page to the tree, we should look up the existing orphan nodes and moving child pages under the parent page node. This logic is implemented in the `relocateOrphanNodes(to:)` function. However, during a refactor, I placed this function call in an incorrect place, which led to the bug in the app.

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Verified the issue is fixed using a test site.

3. What automated tests I added (or what prevented me from doing so)
A couple of unit tests that can reproduce the issue.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist: N/A

### CODE REVIEW

**Comment by mokagio** [comment]
Hey @crazytonyli  👋 You might notice a merge `trunk` commit here from me. That is to bring this branch up to date with the latest CI changes on `trunk` and ensure everything works on the new Xcode 15.1 CI stack.

Don't hesitate to ping me if there's any trouble. I hope to get to review this before the end of the day as it would be ideal to include it in 24.0

**Review by mokagio — COMMENTED** [review]
@crazytonyli I run this branch locally but didn't get the pages sorted hierarchically in the UI 🤔 

iOS | Web
--- | ---
image | image

Semi-related, not all pages appear in the "Set parent" menu in the app, while they do on the web.

https://github.com/wordpress-mobile/WordPress-iOS/assets/1218433/732b94a2-86b3-4dd7-80b8-15f992e9519e

**Comment by crazytonyli** [comment]
@mokagio 🤦‍♂️ My brain obviously wasn't working on my first day back.

**Comment by mokagio** [comment]
> @mokagio 🤦‍♂️ My brain obviously wasn't working on my first day back.

LOL. I know the feeling 😄 🤝

**Pull request closed without merging**
