### PR TITLE
Address NoticePresenter iPad rotation workaround

### LINKED ISSUE #11900: Initialize NoticePresenter in didFinishLaunchingWithOptions
In #11345, we fixed a `UIWindow` rotation issue by keeping the `UIWindow` visible and hiding it on the next run loop (`DispatchQueue.main.async`). After talking to Apple engineers at WWDC, it looks like we can avoid doing the hack by moving the `NoticePresenter` initialization to `didFinishLaunchingWithOptions` instead of `willFinishLaunchingOptions`. 

Here is a sample code showing that this works. You will have to create an empty application with a single view and replace the `AppDelegate` contents. 

```swift
import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    private var secondWindowPresenter: SecondWindowPresenter?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Move this to willFinishLaunchingWithOptions to reproduce the rotation bug
        secondWindowPresenter = SecondWindowPresenter()
        return true
    }

    func application(_ application: UIApplication, willFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        window = UIWindow(frame: UIScreen.main.bounds)
        window?.backgroundColor = UIColor.white
        window?.rootViewController = ViewController()

        window?.makeKeyAndVisible()

        // If this is in -didFinishLaunchingWithOptions, the rotation works fine
//        secondWindowPresenter = SecondWindowPresenter()

        return true
    }
}

private class SecondWindowPresenter {
    private let window: UIWindow

    init() {
        let windowFrame: CGRect
        if let mainWindow = UIApplication.shared.keyWindow {
            windowFrame = mainWindow.offsetToAvoidStatusBar()
        } else {
            windowFrame = .zero
        }
        window = UntouchableWindow(frame: windowFrame)
        window.windowLevel = .alert
        window.backgroundColor = UIColor.blue.withAlphaComponent(0.4)

        // Emulate showing the Notice (inside a UIWindow)
        DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(1)) { [weak self] in
            self?.window.isHidden = false
        }
    }
}

private extension UIWindow {
    func offsetToAvoidStatusBar() -> CGRect {
        return self.frame.insetBy(dx: Offsets.minimalEdgeOffset, dy: Offsets.minimalEdgeOffset)
    }

    private enum Offsets {
        static let minimalEdgeOffset: CGFloat = 1.0
    }
}

@objc class UntouchableWindow: UIWindow {
    override init(frame: CGRect) {
        super.init(frame: frame)
        rootViewController = UIViewController()
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```

## Proposed Tasks

- [ ] Verify that the fix works and there are are no regressions. 
- [ ] Verify rotation still works on devices. 
- [ ] Revert unnecessary changes #11345. 

@nheagy

### PR DESCRIPTION
**Pull request by megmil**
Fixes #11900 

To test: Reproduce steps in #11345

| iPad Air Simulator | iPhone 15 Simulator |
| :---: | :---: |
| ezgif com-video-to-gif-converter | iphonetest-ezgif com-video-to-gif-converter (1) |

## Description

New solution for bug in #11345 (Fix Notices showing anywhere but the bottom on iPad devices)

## Regression Notes
1. Potential unintended areas of impact
Notices on iPhone
Split view

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested on iPhone 15 simulator

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [x] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by megmil** [comment]
@justtwago @dvdchr @guarani @wargcm Could someone review this or let me know if there's any other steps to complete before this can be looked at?

**Comment by guarani** [comment]
Hi @megmil, thanks for your contribution! 

I couldn't reproduce the issue with the notices disappearing on the iPad. The notices appear if I go to Posts or Pages and turn off the internet. As I rotate the device's orientation, the notices work as expected (they move so they're always at the bottom of the screen, no matter the orientation). I'm testing on a physical iPad 8th generation (iPadOS 16.3). 

Could you please verify the issue is present on the latest `trunk` commit? If so, please file an issue with steps to reproduce. 

> Fixes #11900

Just a note: this should point to an open issue, not a PR.

**Comment by megmil** [comment]
Hi @guarani! The issue isn't the notices disappearing on iPad (anymore)--that was fixed in #11345. However, the fix in #11345 was a workaround "hack", and Apple engineers recommended a different way to fix it, according to #11900. That's what I implemented here.

My bad with the PR/bug thing. I just saw that it was marked as "Good First Issue."

**Comment by kean** [comment]
It works great. Thank you for addressing it, @megmil! 🙇

**Review by kean — APPROVED** [review]

**Pull request merged**
