### PR TITLE
Enhance rotation for collapsable header screen

### PR DESCRIPTION
**Pull request by chipsnyder**
## Description
Resolves an issue where the scroll position and header doesn't properly resize when rotated after initial load.

## To test:
1. Open either: 
    - Site Creation: Choose your design
    - Site Creation: Choose your domain
    - Page Creation: Starter Page Template Picker
2. _Without scrolling first_ - Rotate the device
3. **Expect** the header to resize to the proper collapsed position. 

## PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mkevins — APPROVED** [review]
Code looks good, and it works as described. I tested all flows on an iPhone 11 (physical device). LGTM!

**Review by antonis — CHANGES_REQUESTED** [review]
Hey @chipsnyder 👋 
Nice work. The code changes are consistent and the original issue is fixed.

Testing on an iPhone SE 2020 with iOS 14.2 I noticed that the collapsed header disappears when scrolling in portrait mode.

https://user-images.githubusercontent.com/304044/106246588-05711900-6217-11eb-87ae-45378b6a5195.mov

**Comment by mkevins** [comment]
> the collapsed header disappears when scrolling in portrait mode

Good catch! I confirmed this as well.

**Comment by chipsnyder** [comment]
> Testing on an iPhone SE 2020 with iOS 14.2 I noticed that the collapsed header disappears when scrolling in portrait mode.

Oops that's not supposed to happen😄 Good catch I must have failed to go back and check there. I'll update this today.

**Comment by chipsnyder** [comment]
@mkevins @antonis This is ready for review again 🙇

**Comment by mkevins** [comment]
Tested, and it's mostly working. I was still able to reproduce the missing title issue in the case when I rotated _while_ the scroll animation was still taking place. Steps:

* Open modal layout picker (new page) in landscape
* Begin scrolling down with a swipe gesture
* Rotate the phone back to portrait while the "momentum" is still scrolling
* Observe that the title in the header is missing

I tried to record a video, but the recording kept stopping on rotation.

**Comment by chipsnyder** [comment]
> I was still able to reproduce the missing title issue in the case when I rotated while the scroll animation was still taking place.

Great catch @mkevins This is now solved in https://github.com/wordpress-mobile/WordPress-iOS/pull/15731/commits/2ab2a2759e4f2d8b2c8fe1b94ba4a5ebd6590d07.

**Comment by mkevins** [comment]
Nice, tested again with the latest changes, and the issue is resolved. :shipit:

**Comment by chipsnyder** [comment]
Thanks @mkevins! 

@antonis when you get a chance can you re-review to remove the `Changes requested` flag.

**Review by antonis — APPROVED** [review]
LGTM Chip!

**Pull request merged**
