### PR TITLE
Media Library: No Results View

### PR DESCRIPTION
**Pull request by frosty**
This PR adds a No Results view to the media library when the user's media library is empty. 

noresults

Note that the Upload button in the no results view is currently nonfunctional.

To test:

* Ensure the no results view shows correctly when there are no items, and no search results.
* Check it appears correctly if you delete the last item from the web, or add a new item to the web.
* Check the collection view scroll insets still work correctly with the keyboard, as I switched things to use a stack view.

Needs review: @kurzee

### CODE REVIEW

**Comment by kurzee** [comment]
Probably not a big deal:

1. Search for known search text that returns 1 item.
2. Remove the matching text in wp-admin for that item.
3. Pull down to refresh.
4. Notice the item disappears, but the noresults view isn't shown.

**Comment by kurzee** [comment]
Found an issue, spoke too soon:

1. This finicky, but open the Media Library on an iPhone Plus.
2. Search something without results so the no results view is visible.
3. Rotate to landscape.
4. Rotate to portrait.
5. Cancel search, the no results view is visible over the collection.
6. Try to cancel more, it just blinks.

**Comment by kurzee** [comment]
1. On iPad, open Media, search something without results.
2. Background app.
3. Open up a multitasking split with WP.
4. Notice the area with the search bar above is now gray.

simulator screen shot mar 23 2017 5 35 09 pm

**Comment by kurzee** [comment]
1. On iPad, open, stay on Blog Details.
2. Background app.
3. Open up a multitasking split with WP.
4. Open Media, search something with results.
5. Slide WP into full screen.
6. Delete all the characters in the search bar.
7. Notice the search and results don't reset.
8. Hitting cancel brings the collection back, but with the no results visible.

**Comment by elibud** [comment]
@frosty To be consistent with https://github.com/wordpress-mobile/WordPress-iOS/pull/6931 the title of the Upload Media button should be uppercased, what do you think?

**Comment by frosty** [comment]
@elibud It probably should be – perhaps we should have `WPNoResultsView` automatically uppercase whatever button title it's passed?

**Comment by elibud** [comment]
> perhaps we should have WPNoResultsView automatically uppercase whatever button title it's passed?

Sounds right, I'll make the changes and will assign the PR to you @frosty

**Comment by frosty** [comment]
@kurzee I've pushed up a couple of fixes that will address some of your issues, namely:

* No results should no longer appear over the collection when cancelling search
* No results should be shown if you delete the last search result remotely

The issues with the search bar disappearing or becoming unresponsive after rotation (updating your search query not updating the collection view, or the cancel not working) are present on `develop`, and seem like they could be related to the split view. As they're pre-existing, I'll investigate and fix in a separate PR if that's okay?

**Comment by kurzee** [comment]
Maybe related to `UISearchController`?:

1. Search for known search text that returns 1 item.
2. Open the item detail view.
3. Open the editor.
4. Remove the matching text in wp-admin for that item.
5. In the editor picker, refresh the media library.
6. Close the picker and editor.
7. Go back to the library from the detail item view.
8. Notice the search bar has disappeared.

**Comment by kurzee** [comment]
@frosty everything looks good as far as the no-results view. Just the one comment and previous issues with the search bar, for the next PR. :shipit:

**Comment by frosty** [comment]
Thanks @kurzee! I've just put together a fix for your last issue in my search bar branch, so I'll merge this.

**Pull request merged**
