### PR TITLE
Add support for WordPress REST API on WordPress.com (required for Activity Log endpoints)

### PR DESCRIPTION
**Pull request by elibud**
First part to tackle #7832 
In this PR we are adding support for [WordPress REST API on WordPress.com](https://developer.wordpress.com/2016/11/11/wordpress-rest-api-on-wordpress-com/) 

**To test:**
Since the mechanism to create all the URLs has slightly changed please do a full pass of the app, testing different features.

Needs review: @bummytime

### CODE REVIEW

**Comment by bummytime** [comment]
Nice work @elibud 🎉! I took a first pass on this PR — the code looks square and the unit tests are all ✅. I am going to test this build on a few devices to make sure everything still works as expected. Stay tuned....

**Comment by bummytime** [comment]
@elibud I am seeing errors when running this branch. Looks like the URL's might be off a little bit and we are getting 404's in `WordPressComRestApi`. For example:

`https://public-api.wordpress.com/rest/rest/v1.1/users/matt.bumgardner@gmail.com/auth-options?locale=en`

**Comment by elibud** [comment]
@bummytime this is ready for another look. Thanks a million for the thorough testing.

**Comment by elibud** [comment]
Thanks a lot @bummytime I'm going to wait until `8.7` is branched to merge this one since it touches so many places in the app.

**Pull request merged**
