### PR TITLE
Issue/9083 fix async publish when offline or fails uploads

### LINKED ISSUE #9083: Fix async flow when revisions are active and app is offline.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #9083 

This PR changes the async flow to apply revision every time we save instead of waiting for the server to return. 

The rational behind this is: if the user press to save/publish he considers that revision is good and ready to go, and he want to save that version, so we don't need the server to return to confirm the application of the revision.

This simplifies the revision flow, and fixes error regarding discard of changes when working with post that are only have a local copy on the device.

To test:
 - Start the app
 - Switch the device to offline mode
 - Start a new post
 - Write things to it and even add images
 - Press Publish
 - The post will fail publish
 - Open it again
 - Close it without changes
 - Open it again, do some change, tap save again
 - Disable airplane mode
 - Push save again.

Note: there is a non-related change to avoid overload of alerts about no connectivity  when using offline mode. This is being reviewed on a separate PR so ignore those changes at the moment.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
We need it for scenarios we are still using the old sync code.

**Comment by diegoreymendez** [comment]
The whole idea of the revision is to be able to maintain the local version of the post when there are connectivity issues... what happens if the post fails to upload, and you refresh your list of posts?

Won't you lose all local content for that post?

Let's hold back a bit until we can answer that question.

Additionaly this shouldn't be targetted at 9.8 if it's not a bugfix.  I couldn't tell by the description, but it sounds like a logic change.

**Comment by SergioEstevao** [comment]
@diegoreymendez the main issue is that we have a bug now when we try to save async a post and the upload fails. If we come back to the past and try to close it without saving and press discard all the post content is deleted.

We probably can fix this, by saving/applying the revision if the post is local only and still doesn't have a remote version? What do you think?

**Comment by frosty** [comment]
@diegoreymendez I feel like whatever the solution for this, it is a bug fix that we should probably pull into 9.8 because it's fixing an easy to replicate data loss issue:

* Write a post
* Publish with no connectivity / network error
* Re-open the draft, don't make any changes, tap 'discard' in the unsaved changes alert
* Post disappears

**Comment by diegoreymendez** [comment]
@frosty - The problem I'm seeing is that this topic is not as simple as it seems, and a "bugfix" may end up introducing other issues.

As an example: how do you discard the local changes once a post fails to upload?  There's no "discard local post" button.

I also have some doubts about whether the changes you're "saving" by deleting the revision won't be lost silently if the post is refreshed.

Let's discuss a bit more... I think this needs some extra thought.

**Pull request merged**
