### PR TITLE
Issue/8213 site creation theme

### LINKED ISSUE #8213: Site Creation: Theme Selection view
Add a view for selecting a theme based on the site type selected in the previous step.

From the design:
theme_selection

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #8213 

Needs Review: @nheagy

**To test:**
- Start Site Creation process.
- Select a Site Category.
- Verify the Themes displayed match those for the Site Category (listed here https://hogwartsp2.wordpress.com/2017/10/12/social-auth-signup-with-google-design-i3/#comment-6657)
- Verify the layout matches the design.

**Notes:**
- The step description is different than in the design, as discussed here https://hogwartsp2.wordpress.com/2017/11/27/social-auth-signup-with-google-design-i5/#comment-6951.
- The Themes for each category are hard-coded.
- For some reason, the Portfolio > Lodestar theme isn't being returned anymore in the fetch. Leaving that as-is as it should be addressed with the new endpoint.
- When a Theme is selected, this temporary alert appears:
alert

**Implemented:**

implemented

**Designed:**

design

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@nheagy - I fixed the theme fetching by using ThemeService & SyncHelper. Also, I fixed the header sizing (the step description text) - it was truncating on small devices (i.e. iPhone 5). Should be ready for review. Thanks!

**Comment by ScoutHarris** [comment]
@nheagy - should be ready for review now.

**Comment by ScoutHarris** [comment]
Hey @nheagy - could you give it another review please? Thanks!

**Comment by ScoutHarris** [comment]
OK @nheagy - give it one more go please kind sir!

**Comment by nheagy** [comment]
Looks good! Time to :shipit:

**Pull request merged**
