### PR TITLE
Updating to cocoapods 1.0.1

### PR DESCRIPTION
**Pull request by kwonye**
Nothing's broken

Needs review: @koke

### CODE REVIEW

**Comment by koke** [comment]
You should also update the cocoapods version in the `Gemfile` and run `rake dependencies:bundle:install`

**Comment by kwonye** [comment]
@koke that command isn't working for me. Looks like it's failing at installing one of the dependencies. Any ideas on how to fix this?

```
rake dependencies:bundle:install --trace
** Invoke dependencies:bundle:install (first_time)
** Execute dependencies:bundle:install
bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
sh: bundle: command not found
rake aborted!
Command failed with status (127): [bundle install --jobs=3 --retry=3 --path=$...]
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/file_utils.rb:57:in `call'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/file_utils.rb:57:in `sh'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/Will/Git/wordpress-mobile/WordPress-iOS/Rakefile:47:in `block (4 levels) in <top (required)>'
/Users/Will/Git/wordpress-mobile/WordPress-iOS/Rakefile:143:in `fold'
/Users/Will/Git/wordpress-mobile/WordPress-iOS/Rakefile:46:in `block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `call'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `block in execute'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `each'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block in top_level'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:78:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/Library/Ruby/Gems/2.0.0/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => dependencies:bundle:install
```

**Comment by koke** [comment]
I think I'll need to tweak the Rakefile a bit to make sure that step installs `bundler`. For now, try `sudo gem install bundler` and run that command again.

**Comment by kwonye** [comment]
Unable to install bundler and from what I'm reading I have to disable Apple's System Integrity Protection on my machine to do so. Since I'm not comfortable doing that, can you make the changes to the Gemfile/Gemfile.lock and commit. I'll review it and make sure Travis builds and then we can merge.

**Comment by koke** [comment]
OK, pushed the change.

**Comment by kwonye** [comment]
Travis works fine... so :shipit:? I don't know how this works now that I'm reviewing your change...

I'll have you do the merge if you think this is good 👍

**Pull request merged**
