### PR TITLE
Update WordPressAuth pod for password autofill

### LINKED ISSUE #7615: Login: Support iOS 11's password autofill for login fields
In iOS 11, there's a new password autofill feature for login text fields. It _should_ be as simple as setting the correct `UITextContentType` value on the text fields, as we already have associated domains set up for wordpress.com.

screen shot 2017-07-27 at 12 23 04

More information available here: https://developer.apple.com/videos/play/wwdc2017/206/

### PR DESCRIPTION
**Pull request by nheagy**
Fixes #7615

To test:
- Build and run on device
- Attempt to login using password autofill, from keychain storage
- Ensure it succeeds
- The same, but this time with an incorrect password stored
- Ensure it fails and presents the option to enter a different password

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by frosty** [comment]
Just a note that I posted some comments to the related authenticator PR.

**Comment by nheagy** [comment]
This is ready for re-review as well, @frosty ;)

**Comment by nheagy** [comment]
@frosty third time's the charm?

🤨

**Comment by nheagy** [comment]
Thanks @frosty!

**Pull request merged**
