### PR TITLE
Update Charts to fix module name conflicts with Apple Charts

### PR DESCRIPTION
**Pull request by kean**
This PR updates Charts to version 5.x where the module was renamed to `DGCharts` to eliminate the conflicts with the new Apple's [`Charts`](https://developer.apple.com/documentation/charts) framework. This will allow us to use Apple's `Charts` and integrate third-party packages the use Apple's `Charts`.

To test: 

- Regression testing of the Stats screen
- Regression of the prepublishing social accounts list 

## Regression Notes
1. Potential unintended areas of impact: Stats
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual
3. What automated tests I added (or what prevented me from doing so): n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x]  I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by kean** [comment]
Hey, @dvdchr, can you please help verify the change in `PrepublishingSocialAccountsViewController`? I replaced `indexed()` that was part of `swift-algorithm`, a transient dependency in `Charts` 4.x, with simple `indices`. I think it should be functionally equivalent.

**Comment by crazytonyli** [comment]
@kean The project doesn't compile. Maybe you forgot to check in some code? Like the one in `PrepublishingSocialAccountsViewController`?

**Comment by kean** [comment]
My bad – I didn't notice that push failed. Fixed.

**Comment by dvdchr** [comment]
> can you please help verify the change in `PrepublishingSocialAccountsViewController`?

Hi @kean 👋🏼, I've tested the flow and it worked as expected. LGTM and thanks for updating this.

**Review by crazytonyli — APPROVED** [review]
:shipit:

**Review by staskus — APPROVED** [review]
Thanks for updating, looks good!

**Comment by kean** [comment]
Thanks everyone. Rebased; merging.

**Pull request merged**
