### PR TITLE
Issues/3355 helpshift freeze

### LINKED ISSUE #3355: App freezes when accessing HelpShift Conversation
The app freezes when accessing a HelpShift support chat under certain situations. [Forum thread](https://ios.forums.wordpress.org/topic/ipad-app-freezes).

To reproduce:
1. Go to Me > Help & Support > Contact Us and start a conversation. 
2. Dismiss the chat screen and move to a different part of the app. 
3. After you receive a reply, return to the Me tab and tap Help & Support
The app is now frozen. 

Hat tip @sandymcfadden for the nudge and steps to reproduce.

### PR DESCRIPTION
**Pull request by aerych**
Closes #3355

### CODE REVIEW

**Comment by aerych** [comment]
cc @oguzkocer for a review :)

**Comment by oguzkocer** [comment]
Looks good @aerych, thanks for fixing this and sorry about a couple of the original issues that I missed! :shipit:

**Comment by aerych** [comment]
Thanks @Oguz!  Hey @sendhil, would you be up for a practical test of the patch?  HelpShift does not want to connect for Oguz. Everything works for me but my paranoia demands another practical test for confirmation.

**Comment by sendhil** [comment]
@aerych works for me.

**Comment by aerych** [comment]
Thanks @sendhil

**Pull request merged**
