### PR TITLE
Integrate gutenberg-mobile release 1.100.1

### PR DESCRIPTION
**Pull request by derekblank**
## Description
This PR incorporates the 1.100.1 release of gutenberg-mobile.
For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/5985

Release Submission Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by fluiddot — COMMENTED** [review]
In this version we introduced important UI changes in the editor, hence it would be great to reflect them in the release notes of the app.

**Comment by geriux** [comment]
> In this version we introduced important UI changes in the editor, hence it would be great to reflect them in the release notes of the app.

I agree! I'll update them here and on WP Android.

**Comment by geriux** [comment]
Release notes updated ✅

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

**Pull request merged**
