### PR TITLE
Issue/implement mentions in gutenberg

### PR DESCRIPTION
**Pull request by SergioEstevao**
This PR adds support for adding user mentions in the Block Editor (Gutenberg)

Gutenberg Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2163

To test:
 - Start the app
 - Create a new post using GB (preferably on a site with multiple users)
 - Add a text block (paragraph, list, heading)
 - Tap on the @ icon on the toolbar
 - Check that the mention interface shows up
 - Tap characters and see if the list is filtered according
 - Select an option
 - Check if mention is added to the content
 - Repeat but this time, clean the suggestion completely or press the X button on the text field
 - Check if no mention is inserted.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mchowning** [comment]
Such a good gif! 😄

**Comment by atwdeali** [comment]
org:35177729-Abosnd02-users-nore

**Comment by ceyhun** [comment]
I also realised an issue with the SuggestionsTableView not updating thumbnails in cells correctly. If you scroll very quickly and stop, the thumbnails still keep updating. But that's probably not related to the changes here.

**Comment by SergioEstevao** [comment]
> I also realised an issue with the SuggestionsTableView not updating thumbnails in cells correctly. If you scroll very quickly and stop, the thumbnails still keep updating. But that's probably not related to the changes here.

This looks an existing bug, we can open a separate ticket for this and sort it in another PR

**Comment by SergioEstevao** [comment]
@ceyhun thanks for the great review. I updated the code and it's ready for another round of review.

**Comment by loremattei** [comment]
Hey! I'm moving this to 14.9 since 14.8 has been cut. Please, feel free to ping me if you want this to make it to 14.8.

**Comment by loremattei** [comment]
Hey! I'm moving this to 15.0 because 14.9 has been cut. If you want this to make it to 14.9, please feel free to ping me.

**Pull request merged**
