### PR TITLE
localize.py: Surround arguments with quotes.

### LINKED ISSUE #10051: Localize "Stock Photos" feature.
Stock Photos is not translated properly on the supported languages.

As an example, in Spanish it shows 100% translated on [translate.wordpress.org](https://translate.wordpress.org/projects/apps/ios/dev/es/default), but the feature is still in English.

simulator screen shot - iphone 8 - 2018-08-27 at 15 04 04

The interesting bits are:
- The strings seem to be [correctly localized](https://github.com/wordpress-mobile/WordPress-iOS/blob/d892f88350f6509f33078dbb702d6581ed1ad811/WordPress/Classes/ViewRelated/Media/Stock%20Photos/StockPhotosStrings.swift) on code.
- None of the strings of this sections has been uploaded to `translate.wordpress.org`.
- The code is old enough to have been uploaded already.

### PR DESCRIPTION
**Pull request by etoledom**
Fixes #10051 

This PR solves the issue where none of the strings in the Stock Photos sections was localized, even when all the strings were properly handled in code.

After performing some tests, I noticed that the problem was the space in the name of the folder `Stock Photos`.

The `localize.py` script sends the filename arguments separated by spaces, so a file that is inside a folder with a space in its name will be mistakenly recognized as two different and **nonexistent** files.

i.e.: `Classes/ViewRelated/Media/Stock Photos/StockPhotosStrings.swift`

To avoid this issue in the future, the solution was to wrap up all file names with quotes.

To test:
- Run the script locally `python Scripts/localize.py`
- Open `WordPress/Resources/en.lproj/Localizable.strings`
- Check that the key `"Search to find free photos to add to your Media Library!"` exists.

### CODE REVIEW

**Comment by etoledom** [comment]
Hey @loremattei - Do you think it's better to merge this to the release branch?

**Comment by loremattei** [comment]
@etoledom yes, please. I'll update the strings on release/10.8 branch so that the translators will get the new ones too.

**Comment by etoledom** [comment]
Thank you!

**Comment by loremattei** [comment]
Thank you @etoledom! This is a great catch!

**Pull request merged**
