### PR TITLE
Removes verticals and site info steps from site creation

### LINKED ISSUE #13666: Site creation: Remove verticals and site info steps
Please remove the following site creation steps:

### What will your blog/site be about? (Verticals):
<a href="https://user-images.githubusercontent.com/154014/76801693-261db500-67a4-11ea-9f6c-8d9e0a10b54f.png"></a>

### Title and tagline. (Site Info):
<a href="https://user-images.githubusercontent.com/154014/76801769-451c4700-67a4-11ea-8ff8-ccc8e5005e98.png"></a>

These steps were felt unnecessary when testing new user flow on WordPress apps.

Android ref: https://github.com/wordpress-mobile/WordPress-Android/issues/11420
Internal ref: pbArwn-an-p2

/cc @frosty

### PR DESCRIPTION
**Pull request by Gio2018**
Fixes #13666

##### Change log:
 - Update `SiteCreationWizardLauncher.swift`, remove `verticalStep` and `siteStep` from steps
- Update `SiteCreationWizardLauncher.swift`, remove `verticalStep` and `siteInfoStep` properties
 - Update `SiteCreator.swift`, assign default values for `title` and `tagline` in `SiteCreationRequest`
 - Update `SiteCreator.swift`, remove `invalidSiteInformation` error
- Update `InlineErrorTableViewProvider.swift`, add `typealias CellSelectionHandler = ((IndexPath) -> ())`, moved from `VerticalsTableViewProvider.swift`
- Delete `SiteVerticalsPromptService.swift`, not used anymore
- Delete files in `ViewRelated/Site Creation/SiteInfo`: 
  - `SiteInformationStep.swift`, `SiteInformationWizardContent.swift`, `SiteInformationWizardContent.xib`
- Delete files in `ViewRelated/Site Creation/Verticals`: 
  - `NewVerticalCell.swif`t, `NewVerticalCell.xib`, `SiteVerticalPresenter.swift`, `VerticalsCell.swift`, `VerticalsCell.xib`, `VerticalsStep.swift`, `VerticalsTableViewProvider.swift`, `VerticalsWizardContent.swift`, `VerticalsWizardContent.xib`.
- Update Release Notes.

To test:
- build/run
- Go to `My Sites`
- tap add site to launch the site creation wizard
- Verify that after choosing the type of site, the wizard skips to the `choose domain name` page
- Choose a domain name and verify that the site is created.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by Gio2018** [comment]
> * Is it possible for us to hide the 'suggestions' heading on the domains screen until there are suggestions to show?
> 

Can you please clarify? The screenshot shows the page title, but maybe you are referring to the 'SUGGESTIONS' placeholder, that appears when no suggestions are still available?

**Comment by bummytime** [comment]
Looking good @Gio2018!

> the screenshot shows the page title, but maybe you are referring to the 'SUGGESTIONS' placeholder, that appears when no suggestions are still available?

Yes, that is it:

**Comment by frosty** [comment]
Apologies, the screenshot was showing the '3 of 3' header. The SUGGESTIONS item was as @bummytime showed in his video.

**Comment by Gio2018** [comment]
I updated the logic to show the 'suggestions' title header only when there are results. I also found an issue on iPhones where, sometimes, the title disappears. This is also happening on 14.5, and I haven't been able to observe it on iPads.

**Pull request merged**
