### PR TITLE
Add guard around self-hosted site generation to help limit the risk o…

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes** https://github.com/wordpress-mobile/WordPress-iOS/issues/14354

The exception reported in the ticket was a result of the xmlrpc path not being populated yet. The code attempts to [catch](https://github.com/wordpress-mobile/WordPress-iOS/blob/ea2bf8d5d942f6c735a9ee66c374c31f773823b8/WordPress/Classes/Networking/WordPressOrgRestApi%2BWordPress.swift#L34) possible errors however there seems to be an interesting difference between how errors are thrown from Objective-C and how swift manages them.

> Although Swift error handling resembles exception handling in Objective-C, it is entirely separate functionality. If an Objective-C method throws an exception during runtime, Swift triggers a runtime error. There is no way to recover from Objective-C exceptions directly in Swift. Any exception handling behavior must be implemented in Objective-C code used by Swift.
Excerpt From: Apple Inc. “Using Swift with Cocoa and Objective-C (Swift 2.1).” iBooks.
https://stackoverflow.com/a/35141887/1350218

As a result, I added a guard around this point to return nil which would have followed the logic if this catch was working as expected.

## To test:

- Open Gutenberg on a blog (tested on a Premium wpcom site)
- Logout from the app
- Log back in right away
- The app should show the same blog as before
- Go to Posts
- Open a post
## PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by chipsnyder** [comment]
> My test site is a wpcom site, so the execution shouldn't have gone to the .org side to begin with.

Yeah I think the fallthrough happens here: https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Gutenberg/GutenbergNetworking.swift#L15-L21

We might be better off adding a second check that includes a new boolean along the lines of `blog.isAccessibleThroughXMLRPC()` then call the failure completion if neither API is available.

> I also noticed that every time we close and re-open the editor, the amount of requests we make to /wp/v2/themes?status=active increases. This regardless of the logout/login step.

Good catch on that. Sounds like we have a retain cycle somewhere. I'll take a look at that and make the adjustment.

> What it seems it's happening is those accumulated requests are storing a reference to a blog object that becomes faulty after login out, and re-triggering those requests things will go wrong.
>
> Could you please take another look at this? 

If it is holding on to bad blog instance that might reduce the need to add the `blog.isAccessibleThroughXMLRPC` suggested above. I wonder if that might still be useful though just in case. I'll try it without first then assess from there.

**Comment by chipsnyder** [comment]
@etoledom 

> Sounds like we have a retain cycle somewhere.

This ended up being the case. Looks like this was introduced as part of [15.0](https://github.com/wordpress-mobile/WordPress-iOS/blob/3c00578ee73b352d4416e28ffa9c43c1e2178100/WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift#L304-L317) I reverted the change I originally made so that way we could focus in on the root cause. 

FYI: @pinarol @hypest not sure if we're seeing many out of memory crashes in the app but this is causing a retain cycle every time we open the editor.

**Comment by hypest** [comment]
> FYI: @pinarol @hypest not sure if we're seeing many out of memory crashes in the app but this is causing a retain cycle every time we open the editor.

How bad can this be, and is it a different issue than the ticket this PR is trying to address? We should extract it as its own hotfix if bad enough.

**Comment by chipsnyder** [comment]
> is it a different issue than the ticket this PR is trying to address?

This retain-cycle is the root cause of the issue in the ticket. 

> How bad can this be

There is one other component to the retain cycle that I'm narrowing in on now. But it basically will translate to crashes from out of memory and slowness in the app for users who frequently use the editor. 

My gut says this will be fine until 15.2 but I wanted to drop the FYI  in case we see complaints that the app is slowing down or crashing when launching the editor.

**Comment by chipsnyder** [comment]
> I have one more tweak to make then this should be ready

@etoledom This is actually good to go now. My "one last tweak" was me forgetting I had Zombies enabled so I was tracking down allocations that didn't actually exist.

**Before**
Screen Shot 2020-06-24 at 11 08 45 AM

**After** (With the GB editor open)
Screen Shot 2020-06-24 at 1 52 00 PM


> How bad can this be

I double-checked Sentry and I don't see any out memory exceptions/crashes so this doesn't seem like a big concern. So you can probably ignore the FYI before.

**Comment by pinarol** [comment]
Nice catch @chipsnyder !

**Pull request merged**
