### PR TITLE
Updates Unapproved Comment Styles

### LINKED ISSUE #4149: Comments: Update Styles
Let's update CommentViewController, and NotificationDetailsViewController, so that *unapproved* comments look like this (the new Calypso style!):

s-8cojust3-3000x3000

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Description:
In this PR we're updating the Style for Unapproved Comments to match the latest Calypso UX.

#### Scenario A: Notifications Comments
1. Receive an unapproved comment with no gravatar. An anonymous comment should do the trick, and it can also be 'unaprovved' via web
2. Launch WPiOS
3. Open the Notifications tab and locate the comment received in step (1)
4. Verify that the Gravatar Icon is an orange placeholder.
5. Open the Notification Details

As a result, the comment should be onscreen, with an orange placeholder, and an updated color palette.

--

#### Scenario B: Comments List
1. Receive an unapproved comment with no gravatar. An anonymous comment should do the trick, and it can also be 'unaprovved' via web
2. Launch WPiOS
3. Open `Mi Sites` > `Site` > `Comments`
4. Verify that the Gravatar is an orange placeholder, and the background is yellow-ish
5. Open the comment details

As a result, the Comment Details screen should be consistent with the one rendered in Notifications.

Needs Review: @SergioEstevao (Thanks in advance sir!)

As usual, thanks a lot @drw158, you're **da** man!

Closes #4149

### CODE REVIEW

**Comment by jleandroperez** [comment]
#### Comment Details Sample Screenshot:

ios simulator screen shot aug 14 2015 3 20 00 pm

**Comment by SergioEstevao** [comment]
It's a bit strange @jleandroperez , I see the yellow place holders but after a while I see them change to:

- On the Comment list to the random gravatar images.
- On notifications to the grey placeholder image.

If this is expected.. then I say :shipit:

**Comment by jleandroperez** [comment]
@SergioEstevao nice catch!. First scenario (Yellow Placeholder > Gravatar) is expected.

Hooowever, the second one is _not_ expected. I've been playing and couldn't reproduce it.
Would it be possible to print the [Gravatar URL](https://github.com/wordpress-mobile/WordPress-iOS/pull/4160/files#diff-728aa10a7f8b7bfdb0c9d403c237a38fR92) for the offending row? (the one that flickers from Orange > Gray)

Thanks a lot!!

**Comment by jleandroperez** [comment]
@SergioEstevao thanks *a lot* for catching the gravatars glitch!. 

Should be fixed now, mind taking a quick look sir?. Thank you!

**Comment by SergioEstevao** [comment]
@jleandroperez It looks it's ok now on the notification list, but when you select it the comment there, on the next screen it switches from yellow to gray.

**Comment by jleandroperez** [comment]
@SergioEstevao **thank you** for catching that!!. Should be good now, ready for another round sir!

**Comment by sendhil** [comment]
Changing this milestone to 5.7 as I cut the 5.6 branch.

**Comment by SergioEstevao** [comment]
@jleandroperez after you approve a comment shouldn't the gravatar switch to grey when you go back to previous screen?

**Comment by jleandroperez** [comment]
@SergioEstevao **THANKS** for catching that!!. Different flow, should be fixed now.

Mind taking a (hopefully) last peek? Thanks sir!

**Comment by SergioEstevao** [comment]
@jleandroperez :shipit:

**Comment by jleandroperez** [comment]
Thank you sir!

**Pull request merged**
