### PR TITLE
Editor session tracking

### PR DESCRIPTION
**Pull request by koke**
Adds the editor session tracking described in https://github.com/wordpress-mobile/gutenberg-mobile/issues/556

One change from the original spec is that I renamed the `reason` property to `outcome` in the `editor_session_end` event. The reason for this is that I noticed some undesired behavior when testing the first implementation: you could save a draft without leaving the editor, then closing it and it would register as a `cancel` (because it quit without pending changes).

After seeing that, I changed the logic so the editor session records save/publish events and forces those instead when sending `editor_session_end`. But sometimes those aren't the "reason" why the session ended anymore, "outcome" seems like a better description.

To test:

The best way to test the events is to look at the logs, but it gets too noisy with React Native. You can edit the Xcode scheme, and in Run > Arguments enable the `OS_ACTIVITY_MODE=disable` environment variable. You can also search for `🔵` in the log but that would filter out the event properties 😞 

Some things to test:

- Opening an editor should trigger the `editor_session_start` event
- Switching to classic/gutenberg/html should trigger the `editor_session_switch_editor` event, no `editor_session_start` when the other editor is created
- Saving/publishing shouldn't trigger the `editor_session_end` event. Nothing that doesn't close the editor should
- Closing the editor should trigger the `editor_session_end` event. The `outcome` should match whether the post has been published/saved, even if that was done before closing

cc @hypest

### CODE REVIEW

**Comment by koke** [comment]
Dependencies have been merged, so this should be good to go when reviewed

**Comment by pinarol** [comment]
Hey @koke thanks for wrangling with analytics! 🎉 

I could just found 2 issues:

1. We don't log `editor_session_switch_editor` when switching from classic to aztec

2. the editor property seems a bit invalid in `editor_session_switch_editor` when we go from gutenberg->classic->html>classic It is displayed as 'gutenberg' at the end.

also it could be more clear to name it either as source_editor/destination_editor(or from_editor, to_editor ?) since this is a switch event, just using "editor" might be a bit vague I think.

logs

**Comment by koke** [comment]
> editor property seems a bit invalid in `editor_session_switch_editor`

Copy/paste fail 🤦‍♂️, I pushed a fix for it

> We don't log `editor_session_switch_editor` when switching from classic to aztec

I'm not sure what you mean by that, can you explain?

**Comment by pinarol** [comment]
> I'm not sure what you mean by that, can you explain?
@koke  Sorry I wrote that wrong the first time, it was supposed to be "1. We don't log `editor_session_switch_editor` when switching from classic to **gutenberg**"

**Comment by koke** [comment]
Ah yes, good catch, I missed that one. Pushed a fix in eaf485f64d

About the editor property naming, I agree it's a bit ambiguous, but it's consistent in all the events. I'd be fine renaming in Swift, but I'd leave it as is for what we send to Tracks. What do you think about renaming `switch(editor:)` to `switchTo(editor:)`?

**Comment by pinarol** [comment]
> About the editor property naming, I agree it's a bit ambiguous, but it's consistent in all the events

That's not a big deal for me but just wanted to make sure we are on the same line, I might be wrong about this, but as far as I see other events are using below one:

NSString * const WPAppAnalyticsKeyEditorSource                      = @"editor_source";

And this one is defined first time within this PR so I assumed we can choose what we want but feel free to choose what you think it is convenient. 

https://github.com/wordpress-mobile/WordPress-iOS/blob/eaf485f64dfad334e2636dad04ec697449d46795/WordPress/Classes/ViewRelated/Post/PostEditorAnalyticsSession.swift#L59


> What do you think about renaming `switch(editor:)` to `switchTo(editor:)`?

I don't usually have strong opinions on such things but just so you asked I am more of a 
`switch(to editor: PostEditor) ` person :) it feels more Swifty to me, especially after Swift 4 this kind of usage became more popular.

**Comment by koke** [comment]
🙇 Thanks for the review!

**Pull request merged**
