### PR TITLE
[Gutenberg] Contact Support from inside editor

### PR DESCRIPTION
**Pull request by twstokes**
This feature adds the ability to:
1. Create a support ticket from the editor's Help & Support view
2. Access all support options from the editor's Help & Support view

Internal Ref: pbArwn-2IA-p2#comment-3977

### Related PRs

- https://github.com/wordpress-mobile/gutenberg-mobile/pull/3975
- https://github.com/WordPress/gutenberg/pull/34890

### Test 1

1. Inside the editor, tap the 3-dot menu button.
2. Tap on the "Help & Support" option.
3. In the full-screen editor help center view, tap the "Contact Support" button.
4. Observe the "Contact Support" chat window.
5. Start a support session from this view and confirm it generates a Zendesk ticket.
6. Confirm that `origin:editor-help` tag is passed to Zendesk in the ticket.
7. Confirm that the event `wpios_support_new_request_viewed` appears in the internal tracking tool.

Zendesk support view

### Test 2

1. Inside the editor, tap the 3-dot menu button.
2. Tap on the "Help & Support" option.
3. In the full-screen editor help center view, tap the "All Support Options" button.
4. Observe the app's support view.
5. Ensure each option in the view functions as designed.

Support view for the app

## Regression Notes
1. Potential unintended areas of impact
The "new Zendesk ticket" flow could be impacted.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tried out the "My Site > Avatar at the top-right > Help & Support > Contact Support" flow both from inside and outside the editor and confirmed it works OK.

3. What automated tests I added (or what prevented me from doing so)
No automated tests added. This is not a critical flow so not considered adding a UI test.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by twstokes** [comment]
@guarani, would you mind providing the code review for this? Thank you!

**Comment by twstokes** [comment]
@guarani I'm going to need to troubleshoot why this binary isn't pulling in the Gutenberg Mobile changes first. I'll comment on this PR once that's ready.

**Comment by twstokes** [comment]
@guarani and @kyleaparker - I need to complete [the steps here](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/WPiOS%20Integration.md#how-to-test-a-gutenberg-mobile-pr-in-wpios) to get the installable build working. Doing that now!

**Comment by twstokes** [comment]
The iOS build should be good now. Thanks!

**Review by guarani — APPROVED** [review]
Looks good to me! Thanks for adding this!

I noticed a quirk with the notch where upon rotation, the help screen modal slides under the notch, so I'll create a separate issue for that.

I verified the two scenarios and all good :shipit:

**Comment by guarani** [comment]
> I noticed a quirk with the notch where upon rotation, the help screen modal slides under the notch, so I'll create a separate issue for that.

https://github.com/wordpress-mobile/gutenberg-mobile/issues/4030 was created to track this, thanks @twstokes!

**Comment by twstokes** [comment]
Smoke tests for the latest build passed. 👍

**Comment by startuptester** [comment]
@twstokes should this change be in the release notes?

**Comment by twstokes** [comment]
Hey @startuptester - it should, and I waffled on adding it to this PR or adding it as part of the Mobile Gutenberg release. 

@Guarani and I are release wranglers so I'll be sure to add it to #17249. Thanks!

**Pull request merged**
