### PR TITLE
Updated Podfile to absorb changes to WordPressKit

### PR DESCRIPTION
**Pull request by stevebaranski**
Supports the resolution of [this issue](https://github.com/wordpress-mobile/WordPressKit-iOS/issues/86
https://github.com/wordpress-mobile/WordPressKit-iOS/issues/79) in `WordPressKit`.

I've designated this a Draft PR, unless or until the associated update to [`WordPressKit`](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/103) has been properly versioned.

To test:

- Branch should build.
- Tests should pass.
- "Smoke test" of network connectivity in the app should work.

Update release notes:

- [X] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by stevebaranski** [comment]
@jklausa would you be willing to take a look at this?

**Comment by stevebaranski** [comment]
@jklausa please hold on this. I absorbed the change to `WordPressKit` that you just approved, and am now faced with a merge conflict. 

In attempting to resolve said conflict, I encountered the following error:

**Comment by stevebaranski** [comment]
OK @jklausa - no version increment was required here. Ready when you are!

**Comment by jklausa** [comment]
@stevebaranski I ended up needing to roll those changes among others as part of #11129 — would you mind if we closed this and just merged #11129 instead?

**Comment by stevebaranski** [comment]
Sounds good @jklausa - thank you!

**Comment by stevebaranski** [comment]
Closing this issue in deference to #11129.

**Pull request closed without merging**
