### PR TITLE
Media: Remove new media exports feature flag and legacy support

### PR DESCRIPTION
**Pull request by frosty**
This PR removes the feature flag for the 'new' media export code, and any legacy support we had in place while we were transitioning over to it.

The new code has been in testing in internal builds for many months now, and other than a couple of small issues we've fixed there have been no major problems arising. We've decided we're ready to enable it for everybody.

To test:

* Ensure viewing and adding media to the app still works as expected, both for dotcom and self-hosted sites.

Needs review: @SergioEstevao

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@frosty it looks you missed the removal of some code on our unit tests.

**Comment by SergioEstevao** [comment]
Check buddy build.

**Comment by frosty** [comment]
Thanks @SergioEstevao! I totally missed that.

**Comment by frosty** [comment]
It looks like the failing tests are due to a timeout, and unrelated to this PR. We'll merge now, and fix those separately.

**Pull request merged**
