### PR TITLE
Remove the Gutenberg dialog on new sites

### PR DESCRIPTION
**Pull request by etoledom**
Remove the Gutenberg dialog that was showning after creating a new site by setting gutenberg as default.

Since Aztec was set as default, the logic run the migration to gutenberg and set the dialog to be shown.

Just setting gutenberg as default should have been enough, but there was an issue where the URL string on the site creation flow appends a trailing `/`. This URL is used as the key for gutenberg `enabledOnce` setting. After refreshing the URL from remote, the trailing `/` was removed, creating a different key, so `enabledOnce` was returning false (and showing the dialog when it shouldn't).

This PR solves that issue ensuring that there are no trailing `/`s when saving the `enabledOnce` setting.

**To test:**

Test 1:
- Create a new site.
- Create a new post, make sure the block editor is showing and there is no dialog about it.

Test 2:
- Create a new user.
- Create a new site.
- Create a new post, make sure the block editor is showing and there is no dialog about it.

Test 3:
- Add a self hosted site.
- Create a new post, make sure the block editor is showing and there is no dialog about it.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

cc @maxme

### CODE REVIEW

**Comment by guarani** [comment]
@etoledom, I'm holding off testing the build because of CircleCI failing.

**Comment by guarani** [comment]
## Test Results

Tested on iPhone 7, iOS 13.3.1.

Test | Result
-|-
Test 1: | ✅
Test 2: | ✅
Test 3: | ⚠️ I'm seeing a popup about the block editor upon post creation. This is using a Pressable (.org site) site at https://pschrottky.mystagingwebsite.com/ <br><br>

**Comment by etoledom** [comment]
@Guarani - Thank you for your tests!
The issue on SelfHosted should be fixed now. Would you mind giving it another look?

**Comment by guarani** [comment]
@etoledom, I just installed the new version and the app unfortunately crashed after logging into the new site https://pschrottky1.mystagingwebsite.com/ (this is a brand new site I just created today).

1. Log into self-hosted Pressable site
2. On the site confirmation page, tap Continue
3. Observe the crash
4. On a side note, the app then crashes when attempting to open it afterwards

Let me know if you need any other details to reproduce this. Here's a screen recording:

**Comment by guarani** [comment]
@etoledom - This looks good to me, I tested the self-hosted option and couldn't reproduce the crash I reported in the comment above.

**Comment by loremattei** [comment]
Hey there! I'm moving this to 14.5 because 14.4 has just been cut. If you want this to make it to 14.4, please feel free to ping me!

**Comment by etoledom** [comment]
Targeting release 14.4 as discussed with @loremattei

**Comment by etoledom** [comment]
Thank you @guarani for your tests! 🙏

**Pull request merged**
