### PR TITLE
Stats Traffic: Update UI Tests

### LINKED ISSUE #22447: Update UI tests for Traffic tab
We have some minimal tests in `StatsTests` that need to be updated [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/UITests/Tests/StatsTests.swift) when the Traffic tab is enabled.

### PR DESCRIPTION
**Pull request by staskus**
Fixes #22447
Depends on https://github.com/wordpress-mobile/WordPress-iOS/pull/22400

## Regression Notes
1. Potential unintended areas of impact

None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

None

3. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by tiagomar** [comment]
👋  Hi @staskus, the build is failing for me on this branch, but I see it went well on CI. Am I missing something? I'm on Xcode 15.1.

<details><summary>Screenshot</summary>

</details>

**Comment by guarani** [comment]
It looks like the UI tests also run on the WordPress app and show Stats. I haven't run UI Tests for a while, so I'm not sure if this is part of the setup, but it's odd seeing Stats in the WordPress app again:

Simulator Screenshot - iPhone 15 Pro Max - 2024-02-27 at 22 06 57

Otherwise, the tests appear to run successfully.

If I run JetpackUITests, it fails with an "unable to find type StatsPeriodUnit in scope" error. I didn't dig into this more, but I'd be happy to loop back tomorrow.

**Comment by derekblank** [comment]
@tiagomar In regards to your [local build failures](https://github.com/wordpress-mobile/WordPress-iOS/pull/22703#issuecomment-1967307858): I think this may be related to the merge of initial support for VideoPress v5 in https://github.com/wordpress-mobile/WordPress-iOS/pull/22602 which also included updated submodule references for Gutenberg and Jetpack. Based on your screenshot, there may be an issue with your other connected repositories or local Pods install that would need to be updated on your local machine.

You could try the following:

- Ensure you have checked out the latest trunk from Gutenberg Mobile and run `git submodule update --init --recursive` to update the submodule references
- Remove and reinstall all Pods to ensure you've got the latest Gutenberg Pod version: `rm -rf Pods && bundle exec pod install`

Let me know if either of those don't help resolve the issue.

**Comment by staskus** [comment]
> It looks like the UI tests also run on the WordPress app and show Stats. 

@guarani, yes, technically they can run on the WordPress app as well. However, UI tests are only run on the Jetpack app. https://github.com/wordpress-mobile/WordPress-iOS/blob/aab11aca759350ad8bb6022abc3d52cf8243cf64/.buildkite/pipeline.yml#L77

> but it's odd seeing Stats in the WordPress app again

It all depends on the feature flag configuration (https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/feature_flags.json). In the end, both apps are mostly the same. 

> If I run JetpackUITests, it fails with an "unable to find type StatsPeriodUnit in scope" error. I didn't dig into this more, but I'd be happy to loop back tomorrow.

You're most likely having the same issue as Tiago. p1709057601865439-slack-C04U3GCAVK2 . It shouldn't be related to this PR.

**Review by tiagomar — APPROVED** [review]
I confirm that the build failures I'was facing were caused by issues in my local environment (thanks @derekblank !), nothing to do with this PR.

The changes look good, tests run smoothly on iPhone and iPad, and CI is 🟢. This is good to go! :shipit:

**Review by guarani — APPROVED** [review]
Tests passed now on the JP app (ran `StatsTest` in isolation). I'm not sure what caused the "unable to find type StatsPeriodUnit in scope" error yesterday. I'd already re-installed Pods after running into the same error @tiagomar mentions in https://github.com/wordpress-mobile/WordPress-iOS/pull/22703#issuecomment-1967307858.
Thanks @staskus and @tiagomar! 🙇

**Pull request merged**
