### PR TITLE
Zendesk Mobile: add support for users not logged in

### LINKED ISSUE #9374: Zendesk Mobile: add support for users not logged in.
Zendesk requires user credentials to be able to create tickets via the SDK.

When users are not logged in (signup and login), we need to prompt the user for email and name.

Implementation and design discussed [here](https://wp.me/p9xubY-aS), with the final design being:

user_information_prompt

For the name field, the desire is to (from the P2 linked above): "start with pre-populating it from the email, like we do on signups: take the email, extract the name part, spaces-for-dots, capitalize."

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #9374 

This allows users to contact Support while logged out.
- When 'Contact Us' or 'My Tickets' is selected, Zendesk will prompt for email and name.
- Zendesk saves this information to User Defaults.
- Zendesk will use this information as long as the user is logged out.
- Once the user is logged it, Zendesk will then use the account information.

---
**To test:**

**Access Help Center while logged out:**
- Start with a fresh app install (to clear User Defaults).
- Go to either Login or Signup.
- Select 'Help'.
- Select 'WordPress Help Center'
- Verify it appears.

---

**Accessing Support for the first time while logged out:**
- Go to either Login or Signup.
- Select 'Help'.
- Select either 'Contact Us' or 'My Tickets'.
  - Verify you get the information prompt.
- Enter an email address.
  - Verify the 'Done' button is active once a valid email is entered.
  - Verify the 'Name' is updated as you type the email address.
- Select 'Done'.
  - Verify you are directed to the view you selected.

---

**Accessing Support again while logged out:**  
- Relaunch the app.
- Go to either Login or Signup.
- Select 'Help'.
- Select either 'Contact Us' or 'My Tickets'.
  - Verify you do not get the information prompt, and the selected view appears.
  
---

**Accessing 'Contact Us' from the Help Center:**
- Start with a fresh app install (to clear User Defaults).
- Go to either Login or Signup.
- Select 'Help'.
- Select 'WordPress Help Center'
  - Verify 'Contact Us' _does not_ appear.
- Select an Article.
  - Verify 'Contact Us' _does not_ appear.
- Go back and select either 'Contact Us' or 'My Tickets' and enter your information in the prompt.
- Cancel the view and select 'WordPress Help Center'.
  - Verify 'Contact Us' _does_ appear.
- Select an Article.
  - Verify 'Contact Us' _does_ appear.

---

init_alert

with_info

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@SylvesterWilmott  - could you verify the UI is OK?

**Comment by ScoutHarris** [comment]
syl

**Comment by ScoutHarris** [comment]
Thanks @etoledom !

> A name seems to not be required, right? I can just enter my email, remove the name and continue.

That is correct. The customer can just submit an email. It is a bit sneaky though - if the user doesn't provide one, the app actually creates one anyway before contacting Zendesk.

> The help center shows, but there seems to be an error. 

As we figured out via DM, this is because ZD doesn't allow agent accounts to act like customers. Using another email address works.

**Comment by SylvesterWilmott** [comment]
Looks good @ScoutHarris , but one thing. The `Cancel` label is bolded instead of `Done`.

**Comment by SylvesterWilmott** [comment]
And actually let's change that `Done` label to `OK`

**Comment by ScoutHarris** [comment]
@SylvesterWilmott - both changed, screenshots updated in description. Thanks!

**Pull request merged**
