### PR TITLE
Blogging Prompts Dashboard Card: hide prompt card when prompt skipped

### PR DESCRIPTION
**Pull request by ScoutHarris**
Ref: #18429, #18250

When `Skip this prompt` is selected from the prompt dashboard:
- The prompt information is stored in User Defaults.
- The card is removed from the Dashboard.

Bonus: the card will now use the cached prompt if there is one.

To test:
- Enable `bloggingPrompts` feature flag.
- Select the My Site `Home` tab.
- On the prompt card menu, select `Skip this prompt`.
- Verify the card is removed from the Dashboard.
- Select a different site.
- Verify the prompt card appears.

| prompt | no_prompt |
|--------|-------|

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by wargcm — CHANGES_REQUESTED** [review]
Hey @ScoutHarris 👋, I ran into a few issues while testing different scenarios:

<table>
  <tr>
    <th>Prompt for other sites being skipped</th>
    <th>Unable to skip prompt on other sites</th>
    <th>Skipped prompt reappears</th>
  </tr>
  <tr>
    <td>
<ul>
<li>Launch app</li>
<li>Site 1 appears, change to a different site</li>
<li>Skip site 2's prompt</li>
<li>Site 2's prompt remains on the dashboard</li>
<li>Switch to site 1</li>
<li>Site 1's prompt is now gone</li>
</ul>
    </td>
<td>
<ul>
<li>Launch app</li>
<li>Skip site 1's prompt</li>
<li>Switch to site 2</li>
<li>Site 2's prompt can't be skipped</li>
</ul>
</td>
<td>
<ul>
<li>Launch app</li>
<li>Skip site 1's prompt</li>
<li>Switch to site 2</li>
<li>Kill and relaunch the app</li>
<li>Skip site 2's prompt</li>
<li>Switch to site 1</li>
<li>Prompt is shown again</li>
</ul>
</td>
  </tr>
</table>

**Comment by ScoutHarris** [comment]
Hey @wargcm .

Thanks for the testing! Much appreciated. 

The problem was twofold:
1. I failed to correctly manage skipped prompts by siteID in `UserDefaults`. 🤦 
2. I was using `prompt.siteID` in UD. However, the prompt doesn't update when the site changes, so it didn't always match the displayed blog's siteID. UD is now using `blog.dotcomID` instead of `prompt.siteID`.

Ready for another go if you please. You'll want to reinstall the app to purge the defective user defaults. Thank you!

**Review by wargcm — APPROVED** [review]
@ScoutHarris Each of those have been fixed and I don't see any other issues. Looks good! :shipit:

**Comment by ScoutHarris** [comment]
Thanks @wargcm !

**Pull request merged**
