### PR TITLE
Improves tag capitalization.

### LINKED ISSUE #2995: Reader: topic names are sometimes the wrong case.
Topics appear to have the first character upper cased.  This can lead to the title being incorrectly cased, e.g. "Wordpress" instead of "WordPress".

### PR DESCRIPTION
**Pull request by aerych**
Closes #2995

### CODE REVIEW

**Comment by aerych** [comment]
cc @astralbodies for a code review por favor :)

**Comment by astralbodies** [comment]
This would be beautiful with a unit test :smirk: 

:shipit:

**Comment by aerych** [comment]
> This would be beautiful with a unit test

Right you are!  I shall craft one directly.

**Comment by aerych** [comment]
@astralbodies Test added. Take two?

**Comment by astralbodies** [comment]
Awesome job :smiley: :shipit:

**Pull request merged**
