### PR TITLE
Jetpack App: Filter Jetpack sites

### PR DESCRIPTION
**Pull request by momo-ozawa**
## Description 

This PR adds a Jetpack filter for "My Sites" on the Jetpack App 

WPKit: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/375

## Merge directions
- Merge after https://github.com/wordpress-mobile/WordPress-iOS/pull/16124 and https://github.com/wordpress-mobile/WordPressKit-iOS/pull/375

### Jetpack Scheme
1. Build and run the Jetpack scheme
2. Go to My Site > Switch Site
3. Login to the same account on https://cloud.jetpack.com
4. ✅ The sites displayed in the app match the sites displayed in https://cloud.jetpack.com

### Regression: WordPress Scheme
1. Build and run the WordPress scheme
2. Go to My Site > Switch Site
3. Login to the same account on https://wordpress.com
4. ✅ The sites displayed in the app match the sites displayed in https://wordpress.com

Jetpack app | WordPress app
--- | ---
 |

 
PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by emilylaguna — APPROVED** [review]
LGTM! 🚀

**Comment by leandroalonso** [comment]
@momo-ozawa I was discussing with @emilylaguna a possible approach to remove the preprocessor #ifs from the code.

We can rely on: protocol + a file in WordPress scheme and another in Jetpack scheme.

An example, the protocol (for both targets):

```
protocol AppConfiguration {
  static var onlyJetpackSites: Bool { get }
}
```

Then, in WordPress we'll have a `WordPressConfiguration.swift`:

```
class Configuration: AppConfiguration {
  static let onlyJetpackSites = false
}
```

And in Jetpack:

```
class Configuration: AppConfiguration {
  static let onlyJetpackSites = true
}
```

Then, in your code you can just do:

```swift
filterJetpackSites = [Configuration onlyJetpackSites];
```

Of course, the naming needs a lot more love but I think this can helps us to drastically reduce the amount of `#if` we're going to use.

We can work on that on an upcoming PR, it's not necessary to change this right now.

Let me know what do you both think (@emilylaguna // @momo-ozawa)

**Comment by emilylaguna** [comment]
I like that approach! The Less #ifs the better!

**Comment by momo-ozawa** [comment]
@leandroalonso @emilylaguna 
Sounds like a solid plan to me. Will open a new PR to get rid of the #ifs 👍

**Pull request merged**
