### PR TITLE
Zendesk Mobile: Me tab: update icon for new notifications

### PR DESCRIPTION
**Pull request by ScoutHarris**
Ref #9325 

To test:
- Start the app.
- Go to Support and create a ticket.
- Be on a tab other than Me.
- Reply to your ticket in Zendesk.
- When the PN is received:
  - Verify the Me icon changes to unread.
  - Select the Me tab. Verify the Me icon is now blue (still unread).
- Select My Tickets to clear the notification.
  - Verify the Me icon is now the original.
  - Select another tab. Verify the Me icon is still the original.

Unread notifications icon:
unselected_unread
selected_unread

No notifications icon: (no change, just verification)
unselected_read
selected_read

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
What's the reasoning behind using the blue with dot icon?

I think once you tap on the 'Me' tab we should remove the dot, same as notifications. You don't need to consume the message to remove the dot, you only need to visit the tab.

Once you're on the 'Me' tab then we use the orange dot in the "Help and support" table row

**Comment by ScoutHarris** [comment]
> You don't need to consume the message to remove the dot

I thought otherwise. 😄 

The idea was to leave all the new notification indicators on until the user viewed 'My Tickets' (thus looking at the notifications). If they have not, the Me tab will still show the indicator letting them know they still have notifications. 

It is blue because when you select a tab, the icon's color changes.

If we don't like this, I can change it to clear the indicator (the dot) on the icon when they select the Me tab.

**Comment by aerych** [comment]
> I think once you tap on the 'Me' tab we should remove the dot, same as notifications. You don't need to consume the message to remove the dot, you only need to visit the tab.

But then on the notifications tab you're also seeing the newly received notifications.  Is it different on the me tab with the newly received replies hidden behind the help & support option? 
No strong opinion about it just, noting the variation.

**Comment by ScoutHarris** [comment]
@aerych @SylvesterWilmott - I've updated the Me icon for the unread selected (it's now blue with an orange dot). Good for final checks!

**Comment by ScoutHarris** [comment]
From @SylvesterWilmott :
"I've been looking around iOS to understand their indicator dots. And It looks like they are also using two types in the tab bar - Those that clear when you press the tab (eg. recent calls) and those that stick around until the action is taken (eg. app store updates). With this in mind, let's go ahead and use your current system of showing the dot until the ticket/ticket list is seen."

**Pull request merged**
