### PR TITLE
[Stats Refresh] Stat Row: add percentage data bar

### LINKED ISSUE #10708: [Stats Refresh] Stat Row: add percentage data bar
Add an optional data bar to the stats row that represents the percentage based on the highest row total. 

Design
bar_design

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #10708 , #10707

- Primarily, this adds a data percentage bar to the `StatsTotalRow`, currently only used by Insights Comments. 
- It also fixes the issue where hidden UI elements became visible on rotation.

---
To test:

Data bar:
- On a site with Comments, go to Stats > Insights > Comments.
  - Tip: en.blog has lots.
- Both tabs, `Authors` and `Posts and Pages`, show the bar.
- The first row is always 100%.
- The remaining rows are a percent of the first row.

UI elements:
- On rotation, verify hidden elements don't appear. (i.e. cell header ellipsis, row disclosure icon, data bar.)

---
iphone_authors

---
iphone_pandp

---
ipad_authors

---
ipad_pandp

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@jklausa - gawd I'm blind. I just noticed the icons and totals aren't centered vertically in the rows. Please don't review just yet!

**Comment by ScoutHarris** [comment]
OK @jklausa . It's ready when you are!

**Comment by ScoutHarris** [comment]
@SylvesterWilmott - I've made two changes:
1) Increased the max bar width.
2) You were right - the row was 2pt too high. It is now 56pt.

I've updated the screenshots in the description.

@jklausa - OK, ready for a review!

**Comment by ScoutHarris** [comment]
@frosty @jklausa -

I know @frosty already reviewed this, but I've refactored the Stat Row to be more flexible/dynamic. Previously, the end of the data bar couldn't be constrained to the data label due to the way the xib was layed out.  (Plus, the xib was just overly complex.)

Now, the end of the data bar is constrained to the data label, so the max data bar will shrink/grow according to how wide the data label is. I've updated the screenshots in the description.

@SylvesterWilmott - if you wouldn't mind, please take another look to ensure I got the layout correct. Thank you!

**Comment by SylvesterWilmott** [comment]
Hey @ScoutHarris , It looks good.

Are we now allowing the bar to be it's max width with a margin to the right hand value?

**Comment by ScoutHarris** [comment]
@SylvesterWilmott -

> Are we now allowing the bar to be it's max width with a margin to the right hand value?

Yep! That's exactly what the latest changes did.

**Pull request merged**
