### PR TITLE
Fix UI Tests for iOS 13/Xcode 11

### PR DESCRIPTION
**Pull request by rachelmcr**
This PR has updates to ensure stability for local UI test runs:

* Fixes the selector for the Safari URL field (used in the magic link login and signup tests).
* Adds a build phase that disables hardware keyboards, so any tests using keyboard presses on the software keyboard will work as expected. (This also closes any open simulators to apply that change.)

It also relies on WordPressMocks updates in this PR:

* https://github.com/wordpress-mobile/WordPressMocks/pull/10

To test:

* Confirm the UI tests pass on CircleCI.
* Run the UI tests locally and confirm they pass (even if you previously disabled the software keyboard/connected a hardware keyboard in the simulator).

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by rachelmcr** [comment]
@aerych These changes _should_ resolve the issues you ran into in your local test runs, so if you have a chance to give this a whirl I'd be curious to know how it goes.

**Comment by aerych** [comment]
Hi Rachel :wave: 
```
Test Suite 'All tests' passed at 2019-09-27 09:37:33.125.
	 Executed 12 tests, with 0 failures (0 unexpected) in 332.050 (332.071) seconds
```
Looking good!  I'll say :shipit: once the Podfile.lock is sorted :)

**Comment by jtreanor** [comment]
I have confirmed the tests pass on both iOS 12 and 13 🎉

**Comment by rachelmcr** [comment]
Thanks for the reviews! The `Podfile.lock` conflict is resolved, so I'll wait for tests to pass to confirm it's all good and then merge.

**Comment by rachelmcr** [comment]
I've been looking into the CircleCI test failures, which look like potentially new flakiness.

At least one (the `kAXErrorServerNotFound` error) looks to be some new flakiness that I can occasionally reproduce in either the magic link login or the signup test — the test gets stuck trying to interact with Safari to consume a magic link. I haven't find a solution for it yet but I'll keep looking.

The other failures occur when the app tries to close the block editor in the `MainNavigationTests` and it doesn't close. This _could_ be a timing issue with the overlay that appears when loading the block editor in development. That shouldn't be new but it's probably worth addressing now that it's showing up.

**Comment by rachelmcr** [comment]
I addressed the `MainNavigationTests` failure but have yet to find a solution for the flaky failure in magic link tests. I've opened https://github.com/wordpress-mobile/WordPress-iOS/issues/12608 for further investigation and will go ahead and merge this PR as-is since I'm not sure this issue is avoidable at this point.

**Pull request merged**
