### PR TITLE
Fix Core Data warnings

### PR DESCRIPTION
**Pull request by etoledom**
This PR updates `Automattic-Tracks-iOS` to implement and test https://github.com/Automattic/Automattic-Tracks-iOS/pull/118

Screenshot 2020-02-18 at 15 33 17

>[error] fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.

> CoreData: fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
2020-02-18 09:51:07.296112+0100 WordPress[9358:4346765] [error] CoreData: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.

> CoreData: warning: Property 'customProperties' on Entity 'TracksEvent' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

> CoreData: warning: Property 'deviceInfo' on Entity 'TracksEvent' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

> CoreData: warning: Property 'userProperties' on Entity 'TracksEvent' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

To test:

- General smoke test of Tracks should be enough.
  - Check that tracks events arrive to the tracks backend appropriately.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pinarol** [comment]
Hey there! I've moved this to 14.4 since 14.3 has been cut. If you want this to make it to 14.4, please feel free to ping me.

**Comment by etoledom** [comment]
@jkmassel - could you please give it a fast look at this one please?
https://github.com/Automattic/Automattic-Tracks-iOS/pull/118 has already been approved and merged 🎉 

Thank you!

**Comment by loremattei** [comment]
Hey there! I'm moving this to 14.5 because 14.4 has just been cut. If you want this to make it to 14.4, please feel free to ping me!

**Comment by etoledom** [comment]
Closing since this update has been already included via https://github.com/wordpress-mobile/WordPress-iOS/pull/13608

**Pull request closed without merging**
