### PR TITLE
Update Post Cell Statuses + Add Progress View

### PR DESCRIPTION
**Pull request by frosty**
This PR extracts the logic for the status label in post list cells into a view model, which will make it easier to add uploading statuses for async. I've also updated the icons and colours for the statuses, to match our latest designs:

4b15f725-7bb1-4452-bd2b-483814d295d7

Here are how these look in the cells:

statuses

Some of the states aren't in there yet as they're currently not supported. They'll be added as we add async support later.

I've also taken this opportunity to add a progress view to the bottom of the cell, which will be used when uploading posts / media, but it's currently hidden by default. 

**To test:**

* Check I've converted the logic correctly!
* If you want, you can either create posts of these different types (create a local post with no internet connection, schedule a post, mark a post as pending, trash a post), or edit the `postStatus` var in `PostCardStatusViewModel` to return different statuses.
* You can show the progress view by modifying `shouldHideProgressView` to return `false`

### CODE REVIEW

**Comment by frosty** [comment]
@jleandroperez Thanks for the review!

Is that snippet from the `else if (!self.statusView.hidden)` when populating the status views?

This case should now be taken care off by the `default` case in the two switch statements – and I'm now using the device icon (phone / tablet) and grey for the text color. Perhaps @folletto could confirm for us whether that's okay.

**Comment by folletto** [comment]
I might be missing some of the context of where the previous one and current ones are triggered, but reading the code seems correct to me.

**Comment by jleandroperez** [comment]
Yup, that was the one!. I've noticed you've merged them both, and picked one of the two styles.

Looks great on my end, squirrel still stands, sir!

**Comment by frosty** [comment]
Thanks both!

**Pull request merged**
