### PR TITLE
Comments: fix moderation options on Atomic sites

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes: #16859
Ref: #16783

This fixes two issues with Comment moderation on Atomic sites:
- Author/Contributor no longer have moderation options. They can now only Like and Reply to Approved comments. (This matches the intended behavior on #16783 )
- If replying to a comment on a closed post, the API's error message is displayed, which in this case is `Comments on this post are closed`.

To test:

---
On an Atomic site where you cannot moderate comments (your role is Author or Contributor):
- Go to My Site > Comments.
- Verify you cannot Approve, Spam, or Trash any comment type.
- Verify you can Like and Reply to Approved comments.
- Verify you cannot Like or Reply to any other comment type (Pending, Spam, Trashed).
  - Since no actions are available, the action bar is hidden.
  - Since you cannot Reply, the Reply bar at the bottom is hidden.

| Approved | Pending |
|--------|-------|
| approved | pending |

---
On an Atomic site where you cannot moderate comments (your role is Author or Contributor):
- Go to My Site > Comments.
- Select an Approved comment on a post where commenting is closed.
- Reply to the comment.
- Verify the `Comments on this post are closed` message is displayed.

<kbd>fail</kbd>

---
On an Atomic site where you can moderate comments (your role is Editor or Administrator):
- Verify you can moderate, like, and reply to all comments.

<kbd>god_mode</kbd>

---
## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@mokagio this will need to go in the next 17.8 release when merged. Thank you!!

**Review by aerych — APPROVED** [review]
LGTM!  I did some extra testing out of paranoia and learned not to test this while proxied.  Confirming that the behavior is now expected on atomic sites.   
I also tested authors on self-hosted sites and it looks like we might need to make a similar change as the moderation options are available for authors and always fail (at least as far as I tested).  Unrelated, I had some trouble refreshing individual comment filters for a self-hosted site. I'll look into this a bit more later.
:shipit: from me!

**Comment by ScoutHarris** [comment]
> I also tested authors on self-hosted sites and it looks like we might need to make a similar change as the moderation options are available for authors and always fail (at least as far as I tested).

🤦 I'll take a look. Thank you!!

**Comment by mokagio** [comment]
@ScoutHarris   this has been bundled as part of [17.8 beta 2 (17.8.0.2)](https://github.com/wordpress-mobile/WordPress-iOS/pull/16878).

Thanks for your work 🙌

**Pull request merged**
