### PR TITLE
Jetpack App (Emphasis): Update Jetpack screenshots

### PR DESCRIPTION
**Pull request by momo-ozawa**
Part of #16395
Follow-on to https://github.com/wordpress-mobile/WordPress-iOS/pull/16396

## Description

This PR updates the JetpackScreenshotGeneration target.
- Added new stubs to WordPressMocks (https://github.com/wordpress-mobile/WordPressMocks/pull/25)
- Updated the My Site screenshot flow to switch to a site with Jetpack Scan / Backup capabilites turned on

Design ref: pcdRpT-n0-p2

## How to test
1. Switch to the `JetpackScreenshotGeneration` target
2. Run `rake mocks` to start a local mock server for UI tests
3. ✅ Make sure that `testGenerateScreenshots()` succeeds

My Site | Activity Log | Jetpack Scan | Jetpack Backup | Stats
-- | -- | -- | -- | --
Simulator Screen Shot - iPhone 12 Pro - 2021-05-10 at 15 05 21 | Simulator Screen Shot - iPhone 12 Pro - 2021-05-10 at 15 05 42 | Simulator Screen Shot - iPhone 12 Pro - 2021-05-10 at 15 05 52 | Simulator Screen Shot - iPhone 12 Pro - 2021-05-10 at 15 06 04 | Simulator Screen Shot - iPhone 12 Pro - 2021-05-10 at 15 06 21

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by momo-ozawa** [comment]
@osullivanchris 👋 
Let me know if the screenshots look okay! 🙇‍♀️

**Review by osullivanchris — APPROVED** [review]
> Let me know if the screenshots look okay! 🙇‍♀️

@momo-ozawa 👋  hey this is looking great! I only have one suggestion:

Could we have a better name than "Jetpack - complete" and the URL similarly? It almost sounds like a product name. I see we have 'Four Paws Dog Grooming' and 'Tri-County Real Estate' on WordPress. Maybe we could come up with similar here?

Not sure if we have anything existing or if I can come up with something. I'll see if Jetpack design have any they use.

**Review by leandroalonso — APPROVED** [review]
@momo-ozawa all green!

You might want to make the changes Chris suggested. Let me know if you'd like for me to review this again.

But given it's a small change, I'm comfortable with you merging the PR after making this change. :)

**Comment by momo-ozawa** [comment]
@osullivanchris New My Site screenshot 😄

**Comment by osullivanchris** [comment]
@momo-ozawa nice! Thanks for looking into it!

**Comment by momo-ozawa** [comment]
Closing this PR in favor of https://github.com/wordpress-mobile/WordPress-iOS/pull/16488.

**Pull request closed without merging**
