### PR TITLE
Renames PostSettingsSelectionViewController

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Description:
The class `PostSettingsSelectionViewController` is being used in few different spots, plus, is also consumed by the upcoming PR #4397.

In this PR, we're renaming `PostSettingsSelectionViewController` > `SettingsSelectionViewController` (because it's usage is not only limited to post settings). Plus, few other classes are getting moved to a new folder called *Tools*.

I'm sending this change in this PR, in order to minimize #4397's footprint.

--

#### Scenario 1: Privacy Picker
1. Tap over `My Sites` > *Any site* > `Settings` > `Privacy`
2. Verify that the picker shows up onscreen, and behaves correctly

#### Scenario 2: Post Format
1. Tap over `My Sites` > *Any site* > `Settings` > `Post Format`
2. Verify that the picker shows up onscreen, and behaves correctly

#### Scenario 3: Image Alignment
1. Edit a new post
2. Upload an image
3. Once the upload is compelte, tap over the image, and tap over the *Edit* button
4. Tap over *Alignment*
5. Verify that the picker shows up onscreen, and behaves correctly

#### Scenario 4: Image Size
1. Edit a new post
2. Upload an image
3. Once the upload is compelte, tap over the image, and tap over the *Edit* button
4. Tap over *Size*
5. Verify that the picker shows up onscreen, and behaves correctly

#### Scenario 5: Post Status
1. Edit a new post
2. Tap over the Settings button (top right)
3. Tap over the Status row
4. Verify that the picker shows up onscreen, and behaves correctly

#### Scenario 6: Post Visibility
1. Edit a new post
2. Tap over the Settings button (top right)
3. Tap over the Visibility row
4. Verify that the picker shows up onscreen, and behaves correctly

#### Scenario 7: Post Format
1. Edit a new post
2. Tap over the Settings button (top right)
3. Tap over the Format row
4. Verify that the picker shows up onscreen, and behaves correctly

Needs Review: @diegoreymendez 
Thanks in advance Diego!

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Test 1: :white_check_mark:

**Comment by diegoreymendez** [comment]
Test 2: :white_check_mark: 
Test 3: :x:  - but from my debugging it's a bug in the editor and not in your PR.  I'll open a ticket after reviewing this PR.

**Comment by diegoreymendez** [comment]
Test 4: :white_check_mark: 
Test 5: :white_check_mark: 
Test 6: :white_check_mark: 
Test 7: :white_check_mark: 

:shipit:

**Comment by jleandroperez** [comment]
Thanks @diegoreymendez !!

**Pull request merged**
