### PR TITLE
Remove last `if let strongSelf = self` usages

### LINKED ISSUE #19549: Replace `if let strongSelf = self` and `if let self = self` checks in closures with modern `if let self`
There's nothing _wrong_ with using `if let strongSelf = self` or `guard let strongSelf = self`. However, `strongSelf` makes the code a bit more cumbersome to read. 

`strongSelf` or any other name different from `self` used to be required when we couldn't use that keyword in an assignment within a closure, but we now can and do so in various places, e.g.

https://github.com/wordpress-mobile/WordPress-iOS/blob/939521f2af12485d1ba2932bccf473b59311fcd1/WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift#L512-L514

We should remove the leftover instances of this old pattern and keep the codebase homogeneous.

**Update**, we can actually use [an even better syntax](https://github.com/wordpress-mobile/WordPress-iOS/issues/19549#issuecomment-1302690610):

```swift
if let self {
  ...
}
```

I renamed the issue accordingly to include acting on both `strongSelf = self` and `self = self`.

### PR DESCRIPTION
**Pull request by mokagio**
Fixes #19549 — I'm working through the [iOS Core project](https://github.com/orgs/wordpress-mobile/projects/134/views/1?pane=issue&itemId=13478946&issue=wordpress-mobile%7CWordPress-iOS%7C19549), to consolidate into a project in the Automattic org. This task was simpler to address than to migrate. _Not really a [2-minute task](https://gettingthingsdone.com/2020/05/the-two-minute-rule-2/), but close enough._

To test: Green CI will suffice. Also notice there should be no SwiftLint warnings.

I intentionally opened the PR with the new rule but no fix to verify the linter. Before applying the fixes:

image

Now, the linter is green. See the checks below.

_P.S._ Sorry for the _huuuge_ diff. I started this out with `strongSelf` in mind. But since opening the task, SwiftLint upgraded the rule to include _all_ optional binding. There were two `strongSelf` instances left which made me think it be a small little PR. But there were hundreds more `if let x = x` around the codebase. 😓 

## Regression Notes
1. Potential unintended areas of impact
_N.A._

2. What I did to test those areas of impact (or what existing automated tests I relied on)
_N.A._

3. What automated tests I added (or what prevented me from doing so)
_N.A._

PR submission checklist:

_N.A._

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- N.A.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by crazytonyli — APPROVED** [review]
Thanks for the changes!

**Review by kean — APPROVED** [review]
Nice

**Pull request merged**
