### PR TITLE
Reader: Code Removal

### PR DESCRIPTION
**Pull request by kean**
- Remove the `.readerReset` FF and the deprecated code. 
- Remove duplicated actions from `ReaderPostMenu` (they are accessible from the cell itself)
- Update UI tests

The only commits worth reviewing are the last two.

To test: n/a

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/297">25.5</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by crazytonyli** [comment]
Is this PR supposed to target the trunk branch?

**Comment by kean** [comment]
> Is this PR supposed to target the trunk branch?

I haven't merged the new Reader PRs in `trunk` yet, but ultimately, yes. I think it's shippable with a couple of minor exceptions that I plan to cover tomorrow: cross-posts and some minor layout tweaks on iPad.

**Comment by crazytonyli** [comment]
@kean Can you have a look at these two PRs to clear ways for this PR to be merged?

* https://github.com/wordpress-mobile/WordPress-iOS/pull/23676
* https://github.com/wordpress-mobile/WordPress-iOS/pull/23700

**Comment by kean** [comment]
This PR is ready to be merged.

**Comment by kean** [comment]
This PR is ready to be merged now, @crazytonyli .

**Review by crazytonyli — APPROVED** [review]

**Pull request merged**
