### PR TITLE
Update release notes with gutenberg-mobile release 1.66.0 changes

### PR DESCRIPTION
**Pull request by fluiddot**
This PR only updates the release notes to include the changes introduced in gutenberg-mobile release 1.66.0, which should have been updated in https://github.com/wordpress-mobile/WordPress-iOS/pull/17450.

PR submission checklist:

- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by fluiddot** [comment]
@mokagio we would need to include this change in the current release branch `release/18.7`, could we do a cherry-pick or would you rather have a new PR with the change? Thanks for the help and sorry for the inconvenience 🙇 .

**Review by hypest — APPROVED** [review]
Update looks good to me! Let's wait for @mokagio to chip in on how best to update the release notes/in what branch, before merging to develop.

**Review by mokagio — APPROVED** [review]
Thank you @fluiddot 👍 

I changed this PR's base to `release/18.7` which is the source of truth branch when it comes to release notes.

The change will propagate to `develop` as soon as we'll merge the release branch back into it, which we'll do at some point soon for the editorialized release notes.

**Comment by fluiddot** [comment]
> Thank you @fluiddot 👍
> 
> I changed this PR's base to `release/18.7` which is the source of truth branch when it comes to release notes.
> 
> The change will propagate to `develop` as soon as we'll merge the release branch back into it, which we'll do at some point soon for the editorialized release notes.

Awesome, thank you @mokagio for the help on this 🙇 .

**Pull request merged**
