### PR TITLE
Show post title in "Customize the message" screen if no publicized message.

### LINKED ISSUE #10665: Publicize: Show default publicize message on "Customize the message" screen
Currently in the editor, under Post Settings > Sharing you can see a preview of the default publicize message. However, when you select "Message" you are taken to a "Customize the message" screen that is empty:

image from ios 5

@m noted that he expected the default publicize text to appear on that screen. That would mirror the Calypso behavior, which fills the "Customize the message" field with the default text:

screenshot 2018-12-14 18 56 25

### PR DESCRIPTION
**Pull request by yaelirub**
Fixes #10665 

To test:
1. Go to blog posts
2. Go to Drafts
3. Tap on a draft post
4. tap on the 3 dots icon in the top right corner
5. Go to Post Settings
6. Under Sharing section tap on the message
7. notice that the message appears in the next screen and is editable
8. edit message and go back.
9. Notice that the message was updated.
10. Tap on message again, clear text and go back
11. Notice that the message is now back to the ortiginal post title. 

publicizedmessage

simulator screen shot - iphone 8 - 2019-01-15 at 12 50 23

Update release notes:
* Fixed an issue where the message field in "Customize the message" screen was empty.
* Added clarification text to footer about empty messages.
- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
Thanks for wrangling this, @yaelirub! One question: is that a single-line input, or is it able to expand to multi-line? If single-line, can we possibly make it multi-line capable?

**Comment by yaelirub** [comment]
Hey @iamthomasbishop ! It is multi line :)

**Comment by ScoutHarris** [comment]
Hey @yaelirub . 

I'm not sure if this is correct behavior or not, but with this change I cannot remove the sharing message. If I edit the message and clear the text, when I return to Post Settings it is re-populated with the default text. This doesn't seem right...

cc @iamthomasbishop

**Comment by yaelirub** [comment]
@ScoutHarris , not sure what's the right behavior here either but in code:
 if (value.length) {
            self.post.publicizeMessage = value;
        } else {
            self.post.publicizeMessage = nil;
        }
[tableView reloadData];
and then the table will reload to the post title in case the publicizedMessage is nil.
Should this behavior be updated?

**Comment by ScoutHarris** [comment]
Hey @yaelirub . 

> Should this behavior be updated?

Unless @iamthomasbishop has other thoughts,  that makes sense to me.

**Comment by yaelirub** [comment]
Hey @iamthomasbishop , I agree and except it to go back to the default to. 
I like the second option better and will go a head with implementing it if that's ok with both of you.

**Comment by iamthomasbishop** [comment]
If it's not too much of a hassle, I would add the note to the footer as well – just helps to clarify a little bit. If it's a pain, this is at least an improvement :)

**Comment by yaelirub** [comment]
Not too much of a hassle at all.
Now that Im trying it, it looks like adding the dim grey default text when the user deletes the text can be somewhat confusing. Seems like they can't really delete the text. 

Im gonna implement adding the instructions to the footer

**Comment by yaelirub** [comment]
Updated and ready for review

**Comment by ScoutHarris** [comment]
Thanks for the clarifications @iamthomasbishop !

@yaelirub - two things:

1. I've added the 'Needs Copy Review' label for this:
> Add descriptive text to the footer – something along the lines of "If empty, the Post Title will be used as the default message." (Note: this copy will need review from editorial)

2. Everything works and looks fine. We just need to add an entry to `RELEASE-NOTES.txt` for this change.

**Comment by michelleweber** [comment]
Can we make it a little more conversational? "If you don't add your own text here, we'll use the post's title as the message."

**Comment by yaelirub** [comment]
Updated

**Comment by ScoutHarris** [comment]
@yaelirub - nicely done! All looks good to me! :shipit:

**Pull request merged**
