### PR TITLE
Aztec/36 feature flag and setting for aztec editor

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/36

To test:
 - Start the app using the standard scheme: WordPress-iOS on Debug mode
 - Go to app settings and activate the Native editor option
 - Tap on the following places to check if the new editor placeholder view is used:
  - Post List
  - Page List
  - New Post on the Tab Bar
- Disable the setting on  app settings
- Go to the same places and check if the regular visual editor shows up.

Needs review: @diegoreymendez

### CODE REVIEW

**Comment by diegoreymendez** [comment]
My only concern is that this combination of options is not very intuitive.

screen shot 2016-08-18 at 9 46 30 am

Can we visibly disable or hide the native editor option when "Visual Editor" is off?

PS: we can treat this in a separate ticket since the feature isn't public yet.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Please read my notes above, let me know if you want a new ticket for that, and :shipit:.

**Comment by SergioEstevao** [comment]
@diegoreymendez update the code to fix the issue in your note. Do you mind check it again?

**Comment by diegoreymendez** [comment]
For history - I gave the :shipit: through DM.

**Pull request merged**
