### PR TITLE
Accessibility: Adjust collapsable header text sizes

### LINKED ISSUE #15925: Accessibility: can't create a new site/choose a domain if iOS is set to a larger text size
When you create a new site from the app, we give the option to start with WordPress.com. You first choose a layout and then you move to the next screen, called "Choose a Domain". Users with larger text sizes will be stuck there.

Similar to #15655 but this one is apparently fixed.

### Expected behavior

Users should be able to:

- See the field **Search Domains** in order to type it
- See the results of the domain they search for

### Actual behavior

Depending on the text size, you'll see the **Search Domains** field and can type a domain. However, you can't see the results | On even larger text sizes, you can't even see the **Search Domains** text field.
------------ | -------------
 | 

In both cases, it's impossible to scroll down.

### Steps to reproduce the behavior
1. On your phone, go to System Settings > Accessibility > Display & Text Size
2. Make sure that **Larger Accessibility Sizes** is checked
3. Increase the font size 
4. Try to scroll down to either see the search results or to simply find the **Search Domains** field

##### Tested on iPhone 7, iOS 14.4, WPiOS 16.6.1

Report: 3746854-zen

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes** https://github.com/wordpress-mobile/WordPress-iOS/issues/15925

## To test:
1. Set your device to a larger text size (The screenshots max out the size by enabling "Larger text sizes" in Accessibility Settings)
2. Navigate to Choose a Design and Choose A Domain
3. Notice that the header now accepts taps to scroll the page. The search box is above the keyboard

| Before | After |
| --- | --- |
|  |  |
|  |  |

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
None

## PR submission checklist:

- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by chipsnyder** [comment]
cc @iamthomasbishop I made some changes to the layout to constrict its growth a bit when it comes to the larger text sizes. It does make the font styles look a bit different at those sizes but it is still the same overall. Just wanted to give you a heads up.

**Comment by iamthomasbishop** [comment]
@chipsnyder Looks much better, thank you! 

I can't recall what our margins are in this presentation, but it looks a bit cramped. Is there any way we can add some margin on the sides so that it's something between 12-20pts? I'm guessing we'd have to sacrifice a bit more on the font size, but even just slightly more margin would be worth the trade off imo.

image

**Comment by chipsnyder** [comment]
> Is there any way we can add some margin on the sides so that it's something between 12-20pts? 

Yeah right now it's set to a minimal 5pts but I agree a bit of an extra margin here would look better and still be a readable size.

I'll start with the 12pts and get something up soon.

**Review by antonis — APPROVED** [review]
Great work @chipsnyder 👍 
I tested this on an iPhone SE 2020 (iOS 14.4.1) and it works as expected both on the "Choose a design" and the "Choose a domain" screen. The code changes also look good 🎉 

> I'll start with the 12pts and get something up soon.

I'll be happy to recheck if needed after this change.

**Comment by chipsnyder** [comment]
@iamthomasbishop I went with a 20pt margin because the text size was essentially the same and IMO the added space looked better. Here's a new screenshot after that update.

20-margin

There are other items on this page that could probably use some tweaks to make them look better but we can tackle that in other tasks as this one was really trying to make the domains functional on larger text sizes.

**Comment by iamthomasbishop** [comment]
@chipsnyder Agreed, that definitely looks better and it makes sense to tackle the other things separately. Nice work!

**Pull request merged**
