### PR TITLE
Plans: Fix truncated feature description labels.

### LINKED ISSUE #10310: Plans: Feature details are truncated.
Earlier, while chatting with @iamthomasbishop, we noticed on the plans cards that the feature descriptions are truncated.  Let's fix that. 

simulator screen shot - iphone 8 - 2018-10-23 at 17 07 11

### PR DESCRIPTION
**Pull request by aerych**
Fixes #10310 

The issue was due to cell heights fixed to 80 px.  Any wrapping text was hidden because the cells were too small.  This PR tweaks constraints and row sizing in the plans storyboard and specifies `.automaticDimension` for row height.

To test:
On a wpcom blog:
- Go to My Sites > Site > Plans and tap to view a plan detail screen
- Confirm that the feature descriptions wrap their text and are not truncated by a cell that is not high enough.
- Check the console and confirm there are no breaking constraints due to the change.

simulator screen shot - iphone 8 - 2018-10-23 at 16 57 41

@ScoutHarris could I trouble you with this one?

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Or I could notice there is already an issue for that (https://github.com/wordpress-mobile/WordPress-iOS/issues/10164).

**Comment by aerych** [comment]
Thanks @ScoutHarris !

**Comment by aerych** [comment]
Ugh.  I was a little fast on that merge and didn't wait for the 👍 from a designer.  Mea Culpa.  @iamthomasbishop or @SylvesterWilmott if there's any changes needed lemme know and I'll sort it.

**Comment by iamthomasbishop** [comment]
Lgtm! 🚢 It!

**Pull request merged**
