### PR TITLE
Add Domains Tracks events

### PR DESCRIPTION
**Pull request by frosty**
This PR adds Tracks events to Domains. It adds the following events:

* `domainsDashboardViewed` – visiting the Domains section from My Site
* `domainsDashboardAddDomainTapped` – tapping the button in the Domains section to choose a new domain, including whether it's using a credit or not
* `domainsSearchSelectDomainTapped` – tapping the button in Domains search to proceed with a selected domain
* `domainsRegistrationFormViewed` – when the native registration details form is displayed
* `domainsRegistrationFormSubmitted` – when the native registration details form is submitted
* `domainsPurchaseWebviewViewed` – when the webview checkout is displayed

It also restores the tracking of `.automatedTransferCustomDomainPurchased`, which was previously accidentally removed.

**To test**

* Build and run
* Navigate through the various events listed above and ensure they're logged in your console
* Here are two example runs:

```
🔵 Tracked: domains_dashboard_viewed <blog_id: 123456789, site_type: blog, tap_source: row>
🔵 Tracked: domains_dashboard_add_domain_tapped <blog_id: 123456789, site_type: blog, using_credit: false>
🔵 Tracked: automated_transfer_custom_domain_suggestion_queried <>
🔵 Tracked: automated_transfer_custom_domain_suggestion_selected <>
🔵 Tracked: domains_dashboard_add_domain_tapped <blog_id: 123456789, site_type: blog, using_credit: false>
🔵 Tracked: domains_purchase_webview_viewed <blog_id: 123456789, site_type: blog, using_credit: false>
```

```
🔵 Tracked: domain_credit_redemption_tapped <>
🔵 Tracked: automated_transfer_custom_domain_suggestion_queried <>
🔵 Tracked: automated_transfer_custom_domain_suggestion_selected <>
🔵 Tracked: domains_dashboard_add_domain_tapped <blog_id: 123456789, site_type: blog, using_credit: true>
🔵 Tracked: domains_registration_form_viewed <using_credit: true>
🔵 Tracked: domains_registration_form_submitted <using_credit: true>
🔵 Tracked: automated_transfer_custom_domain_contact_information_validated <>
🔵 Tracked: automated_transfer_custom_domain_purchased <>
🔵 Tracked: domain_credit_redemption_success <>
```

## Regression Notes

1. Potential unintended areas of impact

None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
3. What automated tests I added (or what prevented me from doing so)

N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Gio2018 — CHANGES_REQUESTED** [review]
Hey @frosty , I tested in on a real device and it seems that the event `domains_dashboard_add_domain_tapped` is triggered multiple times without actually tapping the add domain button. As an example, here is a console log (filtered by `Tracked`) of a successful domain registration through the web view. This registration was performed on the sandbox store, on a premium site that already had the free domain claimed:

```
2021-10-22 15:35:29:823 WordPress[4980:4007005] 🔵 Tracked: domains_dashboard_viewed <blog_id: 192480876, site_type: blog, tap_source: row>
2021-10-22 15:35:33:113 WordPress[4980:4007005] 🔵 Tracked: domains_dashboard_add_domain_tapped <blog_id: 192480876, site_type: blog, using_credit: false>
2021-10-22 15:35:36:557 WordPress[4980:4007005] 🔵 Tracked: automated_transfer_custom_domain_suggestion_selected <>
2021-10-22 15:35:38:918 WordPress[4980:4007005] 🔵 Tracked: domains_dashboard_add_domain_tapped <blog_id: 192480876, site_type: blog, using_credit: false>
2021-10-22 15:35:40:524 WordPress[4980:4007005] 🔵 Tracked: domains_purchase_webview_viewed <blog_id: 192480876, site_type: blog, using_credit: false>
2021-10-22 15:36:00:633 WordPress[4980:4007005] 🔵 Tracked: domains_dashboard_add_domain_tapped <blog_id: 192480876, site_type: blog, using_credit: false>
2021-10-22 15:36:01:293 WordPress[4980:4007005] 🔵 Tracked: domain_credit_redemption_success <>
2021-10-22 15:36:01:430 WordPress[4980:4007005] 🔵 Tracked: domains_dashboard_add_domain_tapped <blog_id: 192480876, site_type: blog, using_credit: false>
2021-10-22 15:36:01:530 WordPress[4980:4007005] 🔵 Tracked: domains_dashboard_add_domain_tapped <blog_id: 192480876, site_type: blog, using_credit: false>
2021-10-22 15:36:01:592 WordPress[4980:4007005] 🔵 Tracked: domains_dashboard_add_domain_tapped <blog_id: 192480876, site_type: blog, using_credit: false>
2021-10-22 15:36:01:770 WordPress[4980:4007005] 🔵 Tracked: domains_dashboard_add_domain_tapped <blog_id: 192480876, site_type: blog, using_credit: false>
```

**Comment by frosty** [comment]
Thanks @Gio2018, I'll take a look! I'm guessing this is going to be something to do with SwiftUI regenerating parts of the view.

**Comment by frosty** [comment]
@Gio2018 I've tried a different approach – ready for another look!

**Review by Gio2018 — APPROVED** [review]
:shipit:

**Pull request merged**
