### PR TITLE
Debouncer improvements

### PR DESCRIPTION
**Pull request by diegoreymendez**
## Description:

This PR improves the `Debouncer` class in three ways:

1. It no longer waits to trigger if it's being released.  This ensures that if the owner of the `Debouncer` is being released, it will be able to trigger the last call before it's actually released.
2. [The callback is no longer optional](https://github.com/wordpress-mobile/WordPress-iOS/pull/11015/files#diff-d025383eb1161f651ad2ec8c7b154b2cR6), as the debouncer would make no sense without a callback.
3. [Adds automated tests](https://github.com/wordpress-mobile/WordPress-iOS/pull/11015/files#diff-87b0abffcbd8e06248ecc2d337dff76fR4) covering both the regular scenario, and the scenario in which we want the `Debouncer` to be released immediately.

## Original issue:

To test the original issue, check out `develop` and change this line:

https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Utility/Debouncer.swift#L11

To:

```swift
self.delay = 10
```

Then run the app, go to the editor, make a change, publish it and exit.
You'll get an assertion failure after a bit.

### Test 1:

Follow the steps mentioned in the section above, to see the original issue is no longer a problem.

### Test 2:

Analyze the logic of the automated tests and run them.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Thanks @yaelirub - I'll check that out.

**Comment by rachelmcr** [comment]
Thanks for working on this! I tested this against the UI tests I'm working on and I'm still getting the assertion failure — it matches what @yaelirub mentioned above. Happy to test again when you're ready.

**Comment by diegoreymendez** [comment]
@yaelirub, @rachelmcr - Made a few extra changed.  The debouncer is still scheduling calls while typing, but when the user explicitly updates / saves / publishes a post, the save call is now triggered immediately.

On top of that I removed the assertion that was causing trouble, since there's no way to avoid that being `nil` if the debouncer call is executed during `deinit`.  This should not be a problem though since if the user really wanted to save, the changes mentioned above will make sure nothing is lost.

Ready for another round.

**Comment by rachelmcr** [comment]
Tried this out against our UI tests and it works perfectly there, resolving the crash I was seeing. 👍 Thank you!

**Comment by diegoreymendez** [comment]
Thanks @yaelirub & @rachelmcr!

**Pull request merged**
