### PR TITLE
Notification Details: Autosizing Cells

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:
In this PR we're enabling Autosizing Cells in NotificationDetails. Benefits are:

- Perceived speed gain when pushing a notification's details (on the iPhone 6s). Haven't measured, but can tell the difference to the naked eye
- Less code
- All of the above make me happy!!

Ref #5613 

#### To test:
1. Log into a dotcom account
2. Test pushing Notification Details. Specially comment-Y notifications, since those would be the most troublesome
3. Try rotations

Needs review: @aerych 
cc @kurzee 

Thanks in advance!!

### CODE REVIEW

**Comment by kurzee** [comment]
@jleandroperez quick note, tapping through a few comments, I could _sometimes_ get constraints to break, as seen in the console. Can't peg any specific steps, or comments, as it seems to happen randomly.

**Comment by jleandroperez** [comment]
thanks @kurzee !! will try to break it (on my end this PR actually solved the CircularImageView warnings i was getting).

P.s.: Aren't you supposed to be AFK!?

**Comment by jleandroperez** [comment]
Tested with nearly all of my notifications (~200) on the 6s (Device) and 4s (Simulator), couldn't trigger any warnings (upon push / rotation).

Is it possible this was caused by a stale nib? (please, try  performing a clean build / fresh install).

Thanks!!

**Comment by aerych** [comment]
Hola @jleandroperez !
I got crashes right away just tapping on row to view a detail. This turned out to be a stale xib (I'm pretty sure) cos I can't repro after doing a clean install. 

Code changes look good!  All that read is very pretty. ;) 
I've tested on the iPhone and iPad.  No breaking constraints as far as I've seen and cell sizing looks good. 
:shipit: :)

**Comment by jleandroperez** [comment]
Thank you @aerych !!!

@kurzee if you _ever_ see any kind of glitch again, please, let me know. It was hopefully caused by a stale nib.

**Pull request merged**
