### PR TITLE
Acknowledgments

### PR DESCRIPTION
**Pull request by garrett-eclipse**
Base en_US localization for acknowledgments.

> Both acknowledgment and acknowledgement appear throughout the English-speaking world, but acknowledgment, without the middle e, is preferred in U.S. and Canadian English, while acknowledgement is preferred outside North America. These preferences extend to the plural forms, acknowledgements and acknowledgments.
Reference - https://grammarist.com/spelling/acknowledgment-acknowledgement/

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by elibud** [comment]
@jkmassel can you please take a look at this one?

**Comment by garrett-eclipse** [comment]
Thanks @jkmassel appreciate the heads up, didn't realize the release notes were short lived there. I've rebased the branch so this should only include the `Podfile` changes. Please review and let me know if I botched anything.

**Comment by jkmassel** [comment]
@garrett-eclipse – looks better, just one more thing – tests are failing because the `Podfile` and `Podfile.lock` are out of sync. 

To resolve this, you can run `pod install` in project root directory which will bring them back in sync.

Then I think we'll be ready to merge!

**Comment by garrett-eclipse** [comment]
Thanks for the guidance @jkmassel I've updated the Podfile.lock, let me know if there's any other issues. Cheers

**Comment by garrett-eclipse** [comment]
Thanks @jkmassel I appreciate the help

**Pull request merged**
