### PR TITLE
Update `a8c-ci-toolkit` to latest version, 2.15.1

### PR DESCRIPTION
**Pull request by mokagio**
This was done to fetch and improved CI annotation for flaky tests, see https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/pull/46.

Change automated via

```
find . -type f -name "*.yml" -exec sed -i '' 's/automattic\/a8c-ci-toolkit#[0-9.]\{1,\}/automattic\/a8c-ci-toolkit#2.15.0/g' {} +
```

## Testing

If Ci is green, we're good
## Regression Notes

1. Potential unintended areas of impact – N.A.
2. What I did to test those areas of impact (or what existing automated tests I relied on) – N.A.
3. What automated tests I added (or what prevented me from doing so) – N.A.

---

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes. **N.A.**
- [x] I have considered adding accessibility improvements for my changes. **N.A.**
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary. **N.A.**

### CODE REVIEW

**Comment by AliSoftware** [comment]
Seems that any [potential error in the case of removing old annotations](https://buildkite.com/automattic/wordpress-ios/builds/13278#01870751-7660-4c67-a740-3cad66e3cc2c/2798-2802) prints a big red message when calling [this line](https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/blob/trunk/bin/annotate_test_failures#L89) in the command.

At first when I saw the failure on [that other step](https://buildkite.com/automattic/wordpress-ios/builds/13278#01870751-7665-49a2-a7f2-b46dea62bb68/3980-3996) and saw the red message about failing to remove annotation, I thought that red message was the cause for the step having gone red, and thus thought that there was an issue in the `annotate_test_failures`. Turns out the red message is unrelated to the failure, and the "Jetpack UI Tests (iPhone)" step really failed due to a real test failure, not due to that error about non-existent annotation removal.

So overall, in theory this should be all good. In practice though, I still think, now that I see those in a real use case, that those big red `FATAL  Failed to remove annotation` errors are quite confusing, especially when they appear just before the rest of the `.buildkite/commands/*sh` turns out to `exit $TEST_EXIT_STATUS` immediately after that, making it easy to think that the "Error: The command exited with status 1" that appears in the log is due to those `FATAL` red error just before it.

image

Given that, I think it would be nice if we could avoid the red `FATAL  Failed to remove annotation` error to appear in the logs in the first place when there's no annotation to remove (which will require fixing this in `a8c-ci-toolkit` then release a `2.15.1`)

**Comment by mokagio** [comment]
@AliSoftware 

> Given that, I think it would be nice if we could avoid the red FATAL  Failed to remove annotation error to appear in the logs in the first place when there's no annotation to remove (which will require fixing this in a8c-ci-toolkit then release a 2.15.1)

I've been sitting on this for a while because I was hoping to address the issue in the plugin.

Even though the logs in Buildkite might be confusing, I think we could benefit from merging this as is in light of a currently ongoing problem where CI shows `AccountSettingsServiceTests.testUpdateFailure()` as a failure even though the logs show it passed. I think the improve flakiness reporting could help remove some noise there, although I that is clearly not the reason why the tests are failing.

I'm going to post this PR in the internal thread where that CI issue is being discussed and let other folks weigh in on whether to merge this as is or wait for better logs.

**Comment by AliSoftware** [comment]
I'm ok with merging this if it causes issues with folks. We'll need a new release of `a8c-ci-toolkit` to fix the misleading red log issue anyway, which we can update on client repos later with a subsequent PR.

[EDIT] Wait, let me [try a quick fix while first while I'm at it though](https://github.com/wordpress-mobile/WordPress-iOS/pull/20378/commits/2fe6e3fce397c372cc066c923dc08d912ba363a1) 😅

**Comment by AliSoftware** [comment]
@mokagio I've fixed the issue on `annotate_test_failures` in [this `a8c-ci-toolkit` PR](https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/pull/50), and tested the change on this PR via 77dc717ea5b3dff6b47d21bc83ccb7260c285712. The [corresponding CI build seems to confirm that the misleading red log is now gone when trying to remove non-existing annotation](https://buildkite.com/automattic/wordpress-ios/builds/13716#0187807a-e8e5-4e64-96cd-2d1dfc288743/2870-2871) 🎉 

Once the `a8c-ci-toolkit` PR lands, feel free to release a new `2.15.1` version then update your PR here to point to it in all pipelines.

**Comment by mokagio** [comment]
🎉 🎉 🎉 

Thank you @AliSoftware 🙇‍♂️

**Review by AliSoftware — APPROVED** [review]

**Pull request merged**
