### PR TITLE
Update travis config file.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Needs Review: @sendhil

### CODE REVIEW

**Comment by sendhil** [comment]
@SergioEstevao  looks like the build is breaking b/c of InfoPlist.h stuff from your fabric changes.

**Comment by SergioEstevao** [comment]
This was fixed on develop meanwhile let me merge the latest develop here.

**Comment by sendhil** [comment]
@SergioEstevao updated the branch for you as we needed to pull in the latest changes from `release/5.3` into `develop` and then re-merge.

**Comment by sendhil** [comment]
:shipit:

**Pull request merged**
