### PR TITLE
Adding tracking for when a user replies to Helpshift

### PR DESCRIPTION
**Pull request by sendhil**
Integrated the latest Helpshift (4.10.0) which added a delegate method for when a user replies to us.

@oguzkocer mind taking a peek since you did the re-do for `HelpshiftUtils`?

### CODE REVIEW

**Comment by oguzkocer** [comment]
@sendhil The code looks good to me. I wonder if it makes sense to add some extra properties for which type of message they're sending though: https://developers.helpshift.com/ios/delegates/. I don't really know how we handle these types, but just wanted to bring it up. What do you think?
```
static NSString *HSUserAcceptedTheSolution = @"User accepted the solution";
static NSString *HSUserRejectedTheSolution = @"User rejected the solution";
static NSString *HSUserSentScreenShot = @"User sent a screenshot";
static NSString *HSUserReviewedTheApp = @"User reviewed the app";
```

**Comment by sendhil** [comment]
@oguzkocer I think it could, but we could always do it in a separate pull request.

**Comment by sendhil** [comment]
Created issue here - https://github.com/wordpress-mobile/WordPress-iOS/issues/3470

**Comment by oguzkocer** [comment]
:+1:

**Pull request merged**
