### PR TITLE
Fix cached notifications appear when logout

### LINKED ISSUE #19075: [Self-hosted] Cached notifications are retained after logging out of Jetpack
### Expected behavior
Locally cached notifications to be flushed when logging out of Jetpack

### Actual behavior
Cached notifications aren't flushed and break the notifications view

### Steps to reproduce the behavior
1. Connect the app to a self-hosted site with Jetpack installed and activated
2. Tap the Notifications tab and observe existing notifications
3. Log out of WordPress.com from the app
4. The notifications screen should now show a message "Looks like you have Jetpack set up on your site. Congrats!..." with a "Log in" button. There may be a large gap above it.
5. Scrolling down in the notifications screen shows notifications previously received when logged in, and some may be visually cut off

| Large gap | Old notifications |
| - | - |
| Screen Shot 2022-07-19 at 15 26 49 |  |

### PR DESCRIPTION
**Pull request by ipalm0423**
Fixes #19075

| -- | Before | After |
| -- | -- | -- |
| iPhone | Simulator Screen Shot - iPhone 14 - 2022-09-27 at 21 13 09 | Simulator Screen Shot - iPhone 14 - 2022-09-28 at 04 25 57 |
| iPad | Simulator Screen Shot - iPad (9th generation) - 2022-09-28 at 03 12 23 | Simulator Screen Shot - iPad (9th generation) - 2022-09-28 at 03 49 36 |

## How To Test:
1. Lanch the app and log in with a WordPress.com account
2. Tap `My Site` tab, open the site-switch page 
3. Tap `+` and tap `Add self-hosted site`
4. Typing address and userName/password and login
5. Tap the `Notifications` tab and observe existing notifications
6. Tap `My Site` tab
7. Tap `user` icon button at top-right navigation bar, and tap `Log Out` to logout
8. Tap the Notifications tab and observe only the jetpack view without notification.

## Root Cause:
The notification cache didn't delete if the  `NotificationsViewController` is not [presented](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift#L689).

## Fix:
0d8cb1a7dc95fd6ba82f5c90459e629034843b5e  :
- delete the notification cache and other cache params no matter view is presented or not
- set `needsReloadResults = true` if the view is not presented. (it will lazy reload at the [viewWillAppear](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift#L196))
- use `reloadResultsController` instead of `tableView.reloadData` because the [sections](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift#L1170) also need reload.

d28c64aadaefa0e3eea3e8cfeed79754790a603c  :
- fix the `JetpackLoginViewController` to align the center of tableView.

| before | after |
| -- | -- |
| Simulator Screen Shot - iPhone 14 - 2022-09-28 at 01 58 28 | Simulator Screen Shot - iPhone 14 - 2022-09-28 at 02 33 37 |

- The `JetpackLoginViewController` will have labels overlapping in large `Dynamic Type`. It should open another issue/PR to handle it.

dd7bff1cdd1a0c5ba2345a7cdaa0f0970a682e82  :
- On iPad, the `detailViewController` should be clean at [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift#L1320).  But it doesn't clean correctly because the `splitViewController.wpPrimaryColumnWidth` is set to `.full` at [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift#L1561). 
- We should not use the `.full` mode because it does nothing change by the [reason](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/ViewRelated/System/WPSplitViewController.swift#L74). You will stay `default` view style even when you select `.full`.
- So this commit adds a comment and remove the `.full` mode temporarily.
- the [BlogListViewController](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/ViewRelated/Blog/Blog%20List/BlogListViewController.m#L348) also has similar `.full` logic, it should open a new issue to check if other views work fine on `.full` mode.

| before | after |
| -- | -- |
| Simulator Screen Shot - iPad (9th generation) - 2022-09-28 at 03 12 23 | Simulator Screen Shot - iPad (9th generation) - 2022-09-28 at 02 45 51 |

4d997564752e1aa1351add708b3af0e0dafb2c1f 
799c547c31968bfc73488a3c6f6b35d7f7ef9246 :
- Tweak the logic of `shouldDisplayJetpackPrompt`, it should check `blog != nil` before presenting it. Otherwise, the jetpackView will not show and will get an empty page.

a92f36d5f4461e91a7ff5bb869f6182c6d7a9e7e 
776edf09d07afcb7e2b907db406a7f2ccf23ce99 :
- Modified the `NotificationsViewController` interface and made it testable.
- Added unit tests for testing the parameter reset behavior when the account changed. 

## Regression Notes
1. Potential unintended areas of impact
`Notifications` tab on iPad/iPhone

3. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing on the `Notification` tab when login/logout WP.com account. (both iPad/iPhone)

4. What automated tests I added (or what prevented me from doing so)
614f37450c837af60625c5089173d4612f0b9c3a Added unit tests for testing the parameter reset behavior when the account changed. 

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by twstokes** [comment]
CI branch: https://github.com/wordpress-mobile/WordPress-iOS/pull/19382

**Comment by mokagio** [comment]
@ipalm0423 @twstokes I noticed you added the 20.9 recently. However, this PR hasn't been reviewed yet—_It also has merge conflicts, but I could have addressed those myself it this had been ready to merge._

I'm going to bump this to the next release because we'll be code freezing 20.9 today.

If this cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.

**Comment by ipalm0423** [comment]
> @ipalm0423 @twstokes I noticed you added the 20.9 recently. However, this PR hasn't been reviewed yet—_It also has merge conflicts, but I could have addressed those myself it this had been ready to merge._
> 
> I'm going to bump this to the next release because we'll be code freezing 20.9 today.
> 
> If this cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.

@mokagio , Ok,  no problem. This PR could deliver in the next release.
Thanks for your reminder.🙂

**Comment by twstokes** [comment]
> @ipalm0423 @twstokes I noticed you added the 20.9 recently. However, this PR hasn't been reviewed yet—_It also has merge conflicts, but I could have addressed those myself it this had been ready to merge._
> 
> I'm going to bump this to the next release because we'll be code freezing 20.9 today.
> 
> If this cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.

Thanks @mokagio! This was my mistake - I added a milestone to appease Peril and should've gone for 21.0. 🙇

**Comment by ipalm0423** [comment]
@twstokes
I rebased the commit to `trunk` and solved the conflict on `project.pbxproj`, `RELEASE-NOTES.txt`.

**Review by twstokes — COMMENTED** [review]
This is looking really good @ipalm0423! Your testing steps succeeded for me, and I'm finishing up the code review. In the mean time:

1. It looks like there's another conflict with `trunk` related to the release notes 😅 
2. I noticed that the view breaks a bit when rotating to landscape on the phone and the artwork doesn't reappear when rotating back to portrait. However, this was also broken for me on `trunk`. Do you think we should address it in this PR or move it to another one?

| Landscape after portrait | Back to portrait |
| - | - |
| Simulator Screen Shot - iPhone 14 - 2022-10-03 at 22 24 32 | Simulator Screen Shot - iPhone 14 - 2022-10-03 at 22 24 38 |

**Comment by ipalm0423** [comment]
> This is looking really good @ipalm0423! Your testing steps succeeded for me, and I'm finishing up the code review. In the mean time:
> 

Thanks for the review @twstokes 😀

> 1. It looks like there's another conflict with `trunk` related to the release notes 😅

I fixed the conflict again🥲. 

> 2. I noticed that the view breaks a bit when rotating to landscape on the phone and the artwork doesn't reappear when rotating back to portrait. However, this was also broken for me on `trunk`. Do you think we should address it in this PR or move it to another one?

I reproduced it on the `trunk`, It seems there is something wrong in the `JetpackLoginViewController` layout, not the `NotificationsViewController`. 

Because the bug comes from a different viewController and it could fix separately from this PR.  I also don't want to make the current PR too big. 
So I open a new [issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/19396) to fix it.

ps: We could also fix the `DynamicType` mode together in the new [issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/19396).
| -- | default | DynamicType |
| -- | -- | -- |
| -- | Simulator Screen Shot - iPhone 14 - 2022-10-04 at 18 32 36 | simulator_screenshot_EE404A98-0AB6-459E-8E96-A5E02AD77A83 |

**Review by twstokes — APPROVED** [review]
LGTM @ipalm0423! Unit tests and manual tests all passed for me on iPhone and iPad. 🎉

**Pull request merged**
