### PR TITLE
Update sign up strings

### PR DESCRIPTION
**Pull request by elibud**
**Fixes** #8747 

**To test:**

Go through the sign up flow and check that all the strings mentioned on #8747 are correctly updated.

### CODE REVIEW

**Comment by elibud** [comment]
@rachelmcr what do you think, do you want to keep the `"` around the user names or drop them?

**Comment by rachelmcr** [comment]
Let's drop them — they aren't being used on Android so it's more consistent.

**Comment by elibud** [comment]
Done! @etoledom would you mind taking another look? Thank you

**Comment by elibud** [comment]
Thanks for the review and speed @etoledom ⚡️

**Pull request merged**
