### PR TITLE
Only show blogs hosted at WordPress.com when reblogging.

### LINKED ISSUE #3724: Reblog shows non-wp.com blogs in the selector
When reblogging a post, the selector should only show wp.com blogs. Right now it allows reblogging to a Jetpack site. It apparently succeeds, although the reblog isn't posted anywhere

ios simulator screen shot 27 may 2015 10 43 02
ios simulator screen shot 27 may 2015 10 43 04
ios simulator screen shot 27 may 2015 10 43 09

### PR DESCRIPTION
**Pull request by aerych**
Closes #3724 

To test:
1) Be signed in with a WordPress.com account and have a Jetpack connected blog.
2) Open the Reader and view Freshly Pressed
3) Tap the reblog button on a cell. 
4) Tap the blog selector to choose the target for the reblog. 
The Jetpack connected blog should not appear in the list. 

Needs Review: @koke

### CODE REVIEW

**Comment by koke** [comment]
This might be my previous PRs fault, but the Jetpack site is the preselected site, even though it's not available in the list.

ios simulator screen shot 02 jun 2015 23 49 00
ios simulator screen shot 02 jun 2015 23 49 02

**Comment by koke** [comment]
Yep, my fault: https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/BlogService.m#L75

```
- (Blog *)lastUsedOrFirstBlogThatSupports:(BlogFeature)feature
{
    Blog *blog = [self lastUsedOrPrimaryBlog];

    if (!blog) {
        blog = [self firstBlogThatSupports:feature];
    }

    return blog;
}
```

If there's a `lastUsed` blog, it won't check if it supports `feature`.

Do you want to sneak in a fix, or leave that for another PR?

Code looks good and it seems to work fine otherwise :shipit:

**Comment by aerych** [comment]
Let's fix it. We can override that method to make it specific for wpcom hosted blogs.  Thanks Koke!

**Comment by aerych** [comment]
I'll submit a fix and retarget to release/5.3

**Comment by aerych** [comment]
> override that method to make it specific for wpcom hosted blogs

Er... I misread where that was happening.  I think the right fix is to just tweak the conditional to check if the last used blog (if there was one) actually supports the specified feature.

**Comment by aerych** [comment]
Closing this one in favor of #3782

**Pull request closed without merging**
