### PR TITLE
Media Library: Add support for video preview

### PR DESCRIPTION
**Pull request by frosty**
This PR adds playback of video assets to the media library. When you view details for a video, you'll see a play icon over the video thumbnail:

img_6675

This is a custom view, which I've tried to match as close as I could to the system icon that's shown over videos in Safari. When you tap the video, we play it back through `AVPlayerViewController`.

To test:

* Try playing back video assets on different types of site (self-hosted, .com etc)
* Check that the video icon only shows on videos, not images
* Check that the icon is centered correctly and looks right

Needs review: @kurzee 
cc @SergioEstevao

### CODE REVIEW

**Comment by SergioEstevao** [comment]
Working well for me and the code looks great!

**Comment by kurzee** [comment]
This may be an issue with the underlying media code, but when tapping the video preview of a Media item which you haven't watched before shows a broken play symbol on the `AVPlayerViewController`, until you close the `AVPlayerViewController` and tap again to watch it.

**Comment by kurzee** [comment]
>Check that the icon is centered correctly and looks right

Feels like it's a bit on the larger side.

**Comment by frosty** [comment]
Thanks for the reviews! I just pushed a change to make the icon a little smaller, in line with the play icon in Safari.

**Pull request merged**
