### PR TITLE
Update My Site menu wording

### LINKED ISSUE #16418: Enhancement: change "Blog Posts" menu label to simply "Posts"
Now with the Nav Unification in WordPress.com, the dashboard is closely aligned to self-hosted sites. On both dashboards, we have **Posts** as the menu item.

On the mobile devices, however, we still show them as **Blog Posts**. The suggestion is to change it **Posts** so they all match.

### Steps to reproduce the behavior

1. Open the app
2. Tap on My Site
3. Find **Blog Posts**

Context: 3949093-zen

### PR DESCRIPTION
**Pull request by AliSoftware**
Fixes #16418

## What this does

This PR is part of HACK week item p7cLQ7-1H5-p2#comment-3181.

 - Updates the "Blog Posts" to "Posts" in the "My Site" screen – as well as in the related screens pushed on tap of those items, for consistency
 - Updates the "Site Pages" to "Pages" in that same screen, for consistency – even if that wasn't part of the original issue and request; I took the liberty to update that too as I felt it made sense, but **we might want @eduardozulian's confirmation about this one** first (see p7cLQ7-1H5-p2#comment-3248)
 - Updates the Quick Tour copies accordingly

## Screenshots

<details><summary>🖼 "My Site" Screen</summary>
<table><tr><th>Before</th><th>After</th></tr><tr>
<td>16418-MySite-Before</td>
<td>16418-MySite-After</td>
</tr></table></details>

<details><summary>🖼 "Posts" Screen</summary>
<table><tr><th>Before</th><th>After</th></tr><tr>
<td>16418-Posts-Before</td>
<td>16418-Posts-After</td>
</tr></table></details>

<details><summary>🖼 "Pages" Screen</summary>
<table><tr><th>Before</th><th>After</th></tr><tr>
<td>16418-Pages-Before</td>
<td>16418-Pages-After</td>
</tr></table></details>

<details><summary>🖼 Quick Tour</summary>
<table><tr><th>Before</th><th>After</th></tr><tr>
<td>16418-QuickTour-Before</td>
<td>16418-QuickTour-After</td>
</tr></table></details>

## To Test

1. Open the app
2. Tap on My Site
3. Check the titles in the menu are "Posts" and "Pages" (not "Blog Posts" nor "Site Pages")
4. Tap on "Posts" and check the title of the screen matches.
5. Go back to "My Sites", then Tap on "Pages" and check the title of the screen matches.
6. Restart the Quick Tour for your site (Me > App Settings > Debug > Enable Quick Start for site)
7. In the "Next Steps" section of "My Site" screen, tap "Customize Your Site" then "Review site pages"
8. Check the name of the section mentioned in the tooltip also matches the new name: "Select **Pages** to see your page list"

#### 1. Potential unintended areas of impact

This is not the only `NSLocalizedString` in the app using just "Posts" as the localization key anymore, which means that if for some locales, the translation of the term "Posts" should be different in the different contexts where this term is used, this might cause context to be lost in translation (since translation of the text "Posts" will be the same everywhere it's used in the app). This is not a new issue (there were already multiple places/screens/contexts where "Posts" string were used), but just wanted to pointing it out given this change.

#### 2. What I did to test those areas of impact (or what existing automated tests I relied on)

Couldn't do much for testing this, as this will highly depend on the translators feedback for any locale

####  3. What automated tests I added (or what prevented me from doing so)

I've run the UI tests and ensured that change in wording didn't break them.

## PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by antonis — APPROVED** [review]
Great work @AliSoftware 👍 
The code changes look good and the app works as expected 🎉 
Let's wait for a confirmation of the `Site Pages` change before merging by @eduardozulian (cc @osullivanchris)

**Comment by kristastevens** [comment]
Hi @AliSoftware, thanks for the copy ping! This looks fine — nice consistency throughout.

**Comment by AliSoftware** [comment]
> Hi @AliSoftware, thanks for the copy ping! This looks fine — nice consistency throughout. 

Oh, I didn't realize that `[Status] Needs Copy Review` would auto-ping you, sorry @kristastevens !

tbh I used that GitHub label mostly to indicate that we were waiting from Eduardo on [this question](https://github.com/wordpress-mobile/WordPress-iOS/issues/16418#issuecomment-919566395) before merging, as he was the one who opened the issue/request 😅  … But I guess I can also take your word as approval for it 🙃

**Comment by kristastevens** [comment]
No worries! When you apply that label, we get a notification for review in our main Slack channel.

**Comment by eduardozulian** [comment]
Thank you all, folks!

**Pull request merged**
