### PR TITLE
Update terminology to Subscribers from Followers 

### LINKED ISSUE #21878: Update terminology to Subscribers from Followers
Context: pcdRpT-4iq-p2, p9Jlb4-6Lu-p2

Web stats have followers changed to subscribers. The same should be done on the app.

PRs that include renaming:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/23084
- https://github.com/wordpress-mobile/WordPress-iOS/pull/23113
- https://github.com/wordpress-mobile/WordPress-iOS/pull/23126

### PR DESCRIPTION
**Pull request by staskus**
Fixes #21878

Update terminology to Subscribers from Followers  in the app.

Other PRs that include renaming:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/23084
- https://github.com/wordpress-mobile/WordPress-iOS/pull/23113

## Solution

I used regex `"follow\w*\b.*?"` to find candidate strings for renaming:
regular expression

There are follow/follower references left in other contexts. For example, Jetpack Social Connections, or Topics. I concentrated on Blog's Followers/Follows/Following/Followed cases.

Affected places:
- Reader (although most popular buttons and prompts already have subscribers used instead of followers, there were still some unchanged strings left)
- Notifications, NotificationSettings (similar to Stats it still used follower terminology)
- Insights -> Grow Audience cell
- Onboarding
- Jetpack overlay

Notifications rename

Notifications rename

## To test:

1. Check localized string changes on the PR.
2. Check most prominent places:
- Notifications
- Notification Settings
- Reader
- Stats

Note: Not all the changes I made appear on the project since `.strings` file still contain old strings and require them to be regenerated and retranslated.

3. Review the project with this or similar regex `"follow\w*\b.*?"` to check if any strings are missed

## Regression Notes
1. Potential unintended areas of impact

Make sure the strings are translated correctly at all the required places

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by staskus** [comment]
cc @aditi-bhatia since you work on this task on Android. There're quite a few references of followers in the app that I found besides Stats. Most notably Notifications and Reader.

**Review by guarani — APPROVED** [review]
Looks good! This keeps "follow" for things like following a topic in Reader or following a post's comment.

**Comment by aditi-bhatia** [comment]
> cc @aditi-bhatia since you work on this task on Android. There're quite a few references of followers in the app that I found besides Stats. Most notably Notifications and Reader.

Thanks for the heads up @staskus! I'm noticing and addressing those on Android too 👍

**Pull request merged**
