### PR TITLE
Post Settings: Removed Drop shadow on tags input field

### LINKED ISSUE #8282: Post Settings: Drop shadow on tags input field
### Expected behavior

In the editor post settings, the Tags input field should have the same design as other settings inputs (e.g. Slug and Excerpt).

### Actual behavior

The Tags input field has a drop shadow, likely coming from the suggestions list. (The drop shadow disappears when you enter a tag that doesn't exist yet on the site.)

### Steps to reproduce the behavior

1. Start a new post in the app.
2. Open the post settings.
3. Open the Tags section.
4. Note that the input field has a drop shadow.
5. Start typing a tag that doesn't exist yet on the site.
6. Note that the drop shadow disappears.

img_0034

##### Tested on iPhone 6, iOS 11.1.1, WPiOS 9.0.0.20171205

Internal ref: p4a5px-25L-p2

### PR DESCRIPTION
**Pull request by Rhetorical**
Fixes #8282 

To test:
- Create a new post
- Go to Post Settings
- Tap on Tag Setting

### CODE REVIEW

**Comment by koke** [comment]
Thanks for the PR, code looks good, but I want to double check with @mattmiklic that we actually want to remove that shadow.

**Comment by Rhetorical** [comment]
I'm not sure if this makes any difference but it only looks weird when switching between the list being empty or not. I checked around in the settings where there were other lists and searches and it's the only one that I could see that had a shadow on it.

**Comment by mattmiklic** [comment]
Hmm, yes this is very strange; shadows around text inputs are not a pattern we typically use on iOS, and it's weird that the shadow disappears when you enter a new, unique tag. I'm not sure how it got here but let's get rid of it.

**Comment by koke** [comment]
Triggered a build manually, I'll merge when green 👍

**Pull request merged**
