### PR TITLE
Media: Use jpg instead of jpeg for uploaded image extension

### LINKED ISSUE #4663: Media: Images saved as JPEG are conflicting with some plugins
Reported [in the forums](https://ios.forums.wordpress.org/topic/the-change-of-jpg-to-jpeg-causing-plugins-to-fail?replies=1).   

To summarize, changes released in version 5.8 cause some images uploaded by the app to be saved as a JPEG (unclear if its just the extension or something besides).  Images saved as a JPEG are apparently incompatible with a number of third party plugins.  

Let's take a closer look at how we're saving/uploading images and try to reproduce the behavior. We can test with the plugin(s) mentioned in the forum thread. This might be a rare case where the app needs to change its behavior to correct a plugin issue. 

Added the bug label even tho this wouldn't be a bug with the app per se.

### PR DESCRIPTION
**Pull request by aerych**
Closes #4663.

This is a replacement for #4681.  Props @koke for the suggestion

Needs review: @koke

### CODE REVIEW

**Comment by koke** [comment]
As mentioned in Slack, I'd move the replacement code to `-[MediaService remoteMediaFromMedia:]` instead of duplicating it in two places. 

Other than that, it seems to work fine.

**Comment by aerych** [comment]
I moved the replacement code to `[MediaService uploadMedia:progress:success:failure:]` which is in keeping with the specific use case. `remoteMediaFromMedia` seemed more general purpose and not the best fit.

**Comment by koke** [comment]
:shipit:

**Comment by aerych** [comment]
Thanks @koke!

**Pull request merged**
