### PR TITLE
Updated username text color on Me tab

### PR DESCRIPTION
**Pull request by lewiguez**
**Details**
Updated username label text color from WordPress blue to dark grey color that is used on the display name label under the Me tab. Reference: #4380

### CODE REVIEW

**Comment by lewiguez** [comment]
Also, cc @astralbodies since he filed the bug. :)

**Comment by astralbodies** [comment]
@mattmiklic Can you take a look at the original issue and confirm my design thoughts jive with expectations before I merge this?  :smile:

**Comment by mattmiklic** [comment]
Good catch; I'd make one small adjustment though, to use `grey` instead of `darkGrey`. That's what I used in the mockup.

screen shot 2015-11-03 at 10 00 02 am

**Comment by astralbodies** [comment]
@lewiguez Can you make the adjustment to `grey` in your PR? Thanks! :smile:

**Comment by lewiguez** [comment]
Updated to `grey` instead of `darkGrey`

**Comment by astralbodies** [comment]
Thanks for the contribution :smile: 
:shipit:

**Pull request merged**
