### PR TITLE
Improve post sharing in Reader

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/23685.

- Remove "title" and "summary" from the shared content
- Update Safari icon to use the modern one from SF symbols
- Remove the "Copy Link" action as "Copy" now does the same
- Make post title selectable (long-press to "Copy")

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/304">25.4.1</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by dcalhoun — APPROVED** [review]
Changes look sound to me. The functionality performed as expected when I tested them on an iPhone SE running iOS 18.0. 🚀 

A few notes for future improvements in a separate PR: 

* We might use the post title to populate fields in other apps—e.g., title in Reminders, subject in Mail. 
* There is an odd animation that occurs in the menu located in the top-right corner when opening/closing the share sheet (video below). 

<details><summary>Unexpected menu animation</summary>
<p>

https://github.com/user-attachments/assets/cfaedc26-9800-4589-90bd-4d56288ece7e

</p>
</details>

**Comment by dcalhoun** [comment]
Noting there are failing CI checks currently. Also, feel free to await further feedback from more experienced iOS developers, if you'd like.

**Comment by kean** [comment]
Thanks for the quick review!

> We might use the post title to populate fields in other apps—e.g., title in Reminders, subject in Mail.

We are still using the title for this purpose:

```
        if let str = title {
            controller.setValue(str, forKey: "subject")
        }
```

When I test sharing to the Mail app, it does populate the subject.

> Unexpected menu animation

I opened an issue https://github.com/wordpress-mobile/WordPress-iOS/issues/23694

> Noting there are failing CI checks currently.

Got some flaky tests.

**Comment by dcalhoun** [comment]
> When I test sharing to the Mail app, it does populate the subject.

Ah, good to hear. 

I do not have Mail set up on my testing device, so I only tested Reminders and presumed Mail would also not function. When sharing to Reminders from the Jetpack app, the new entity name is "Reader." In contrast, Safari sets the new entity title to the post title. It could be that most other apps "just work" like your experience with Mail. 

| Jetpack | Safari |
| - | - |
| share-jetpack | share-safari |

**Comment by kean** [comment]
I opened another ticket to track it https://github.com/wordpress-mobile/WordPress-iOS/issues/23695, thanks for the clarification

**Pull request merged**
