### PR TITLE
Fixing Unit Tests Crash

### PR DESCRIPTION
**Pull request by jleandroperez**
I'm reproducing, quite reliably, a crash while running our unit tests suite.

The source of this glitch is the `TestContextManager` helper utility, which overrides our main `ContextManager` stack. However, this override isn't being reset in any spot.

Stack attached below.

Needs review: @astralbodies 

```
2015-11-13 14:19:18.064 WordPress[31791:395480] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSFetchRequest could not locate an NSEntityDescription for entity name 'ReaderDefaultTopic''
*** First throw call stack:
(
    0   CoreFoundation                      0x000000011481df45 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000114297deb objc_exception_throw + 48
    2   CoreData                            0x00000001100d603a -[NSFetchRequest(_NSInternalMethods) _resolveEntityWithContext:] + 426
    3   CoreData                            0x00000001100d4c26 -[NSManagedObjectContext executeFetchRequest:error:] + 150
    4   WordPress                           0x000000010dc03671 -[ReaderTopicService currentTopicFromDefaultTopic] + 401
    5   WordPress                           0x000000010dc030dc -[ReaderTopicService currentTopic] + 108
    6   WordPress                           0x000000010dcbd904 -[ReaderViewController currentTopic] + 116
    7   WordPress                           0x000000010dcbe2bc __34-[ReaderViewController syncTopics]_block_invoke + 76
    8   WordPress                           0x000000010dc0cba8 __50-[ReaderTopicService mergeMenuTopics:withSuccess:]_block_invoke_2 + 56
    9   libdispatch.dylib                   0x0000000115586d59 _dispatch_call_block_and_release + 12
    10  libdispatch.dylib                   0x00000001155a24a7 _dispatch_client_callout + 8
    11  libdispatch.dylib                   0x000000011558cf2d _dispatch_main_queue_callback_4CF + 714
    12  CoreFoundation                      0x000000011477e2e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    13  CoreFoundation                      0x000000011473f8a9 __CFRunLoopRun + 2073
    14  CoreFoundation                      0x000000011473ee08 CFRunLoopRunSpecific + 488
    15  Foundation                          0x0000000110b413a1 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 267
    16  XCTest                              0x000000011fe12c79 -[XCTestCase(AsynchronousTesting) waitForExpectationsWithTimeout:handler:] + 921
    17  WordPressTest                       0x000000012629d530 -[WPAvatarSourceTest testGravatarCaches] + 848
    18  CoreFoundation                      0x000000011470c7ac __invoking___ + 140
    19  CoreFoundation                      0x000000011470c5fe -[NSInvocation invoke] + 286
    20  XCTest                              0x000000011fdcd820 __24-[XCTestCase invokeTest]_block_invoke_2 + 159
    21  XCTest                              0x000000011fe007c2 -[XCTestContext performInScope:] + 184
    22  XCTest                              0x000000011fdcd770 -[XCTestCase invokeTest] + 169
    23  XCTest                              0x000000011fdcdc0b -[XCTestCase performTest:] + 443
    24  XCTest                              0x000000011fdcb8d1 -[XCTestSuite performTest:] + 377
    25  XCTest                              0x000000011fdcb8d1 -[XCTestSuite performTest:] + 377
    26  XCTest                              0x000000011fdb8adc __25-[XCTestDriver _runSuite]_block_invoke + 51
    27  XCTest                              0x000000011fdd92e3 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 615
    28  XCTest                              0x000000011fdb8a28 -[XCTestDriver _runSuite] + 408
    29  XCTest                              0x000000011fdb9787 -[XCTestDriver _checkForTestManager] + 263
    30  XCTest                              0x000000011fe01b23 _XCTestMain + 628
    31  CoreFoundation                      0x0000000114749ffc __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
    32  CoreFoundation                      0x000000011473fc85 __CFRunLoopDoBlocks + 341
    33  CoreFoundation                      0x000000011473f3e2 __CFRunLoopRun + 850
    34  CoreFoundation                      0x000000011473ee08 CFRunLoopRunSpecific + 488
    35  GraphicsServices                    0x000000011625aad2 GSEventRunModal + 161
    36  UIKit                               0x0000000111ccc30d UIApplicationMain + 171
    37  WordPress                           0x000000010da0c89e main + 62
    38  libdyld.dylib                       0x00000001155d192d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

### CODE REVIEW

**Comment by astralbodies** [comment]
I'm seeing a bunch of failing tests now - are you seeing that on your end?

**Comment by jleandroperez** [comment]
@astralbodies nope, it's passing everything (but one Reader test). I'll poke via Slack, thanks!

**Comment by jleandroperez** [comment]
@astralbodies + @aerych: Thanks *a whole lot* to the both of you, for helping me troubleshoot this one!!.

Ready for another look, everything should be green now.

Thanks!!

**Comment by aerych** [comment]
Props to @astralbodies's eagle eye on the allocation issue :)
:shipit:  from me.

**Comment by jleandroperez** [comment]
Definitely, Aaron is *da man*!!!

**Comment by astralbodies** [comment]
Awesome fix @jleandroperez - :shipit:!

**Comment by jleandroperez** [comment]
Thanks gentleman!

**Pull request merged**
