### PR TITLE
AztecPostViewController: Stripping Media on site switch

### LINKED ISSUE #6827: Aztec: Remove media when switching sites
When switching sites remove all media from a post/page when recreating the revision.

Currently there is a TODO.

```swift
    func recreatePostRevision(in blog: Blog) {
        let shouldCreatePage = post is Page
        let postService = PostService(managedObjectContext: mainContext)
        let newPost = shouldCreatePage ? postService.createDraftPage(for: blog) : postService.createDraftPost(for: blog)

        //  TODO: Strip Media!
        //  NSString *content = oldPost.content;
        //  for (Media *media in oldPost.media) {
        //      content = [self removeMedia:media fromString:content];
        //  }
```

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes #6827

### To test:
1. Open Aztec in "Rich Text Mode"
2. Add a couple images
3. Switch to another site
4. Verify that the images have been removed
5. Repeat in "HTML Mode"

Needs review: @SergioEstevao 
Thanks in advance!

### CODE REVIEW

**Comment by SergioEstevao** [comment]
I found the following bug:

- Start a new post
- Tap on the media picker
- Add 5 images
- While the uploading is going tap on the media picker/switch
- The editor allows switching to a different blog
- It clean the content correctly but: It doesn't stop ongoing uploads and then get's stuck thinking the uploads are not finished and you cannot save the post.

**Comment by jleandroperez** [comment]
Nice catch @SergioEstevao!. Pushed a patch: now, upon `discardChanges`, we're also cleaning up the pending media upload OP's.

Ready for another look!

**Comment by SergioEstevao** [comment]
@jleandroperez I added some extra fixes for the media uploading detection and cancelation.

It's all ok now for my part so :shipit:

**Comment by jleandroperez** [comment]
Thanks for the fixes @SergioEstevao!!

**Pull request merged**
