### PR TITLE
Integrates Editor v1.1.3 into WPiOS.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Integrates several enhancements and bug fixes from WPiOS Editor v1.1.3.

/cc @SergioEstevao for review.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
I'm seeing this error message in the console: ```WebEditor error:
  In file: file:///Users/sergioestevao/Library/Developer/Xcode/DerivedData/WordPress-bhovcvphqqnupmdcmkqpgpepszeo/Build/Products/Debug-iphonesimulator/WordPressEditor.framework/ZSSRichTextEditor.js
  In line: 2220
  TypeError: undefined is not an object (evaluating 'currentNode.nodeName.toLowerCase')```

**Comment by SergioEstevao** [comment]
On the iPhone 6S Plus simulator if I insert two images and then rotate the device while uploading is happening one of the images is removed from the page.

**Comment by diegoreymendez** [comment]
I've seen this too.  It seems like a race condition of some sort.

I can check it when back, but in the meanwhile I'd suggest evaluating if we can treat it in a separate ticket since v1.1.3 additions have several important bg fixes for the editor.

**Comment by SergioEstevao** [comment]
@diegoreymendez I tested develop and the issue of dissapearing was already there so I :shipit: on this one.

If you don't mind I will solve the conflicts and merge it in ok?

**Comment by diegoreymendez** [comment]
Ty @SergioEstevao

**Pull request merged**
