### PR TITLE
Workaround proposal to fix crash building with Xcode 10.1

### LINKED ISSUE #10389: Crash building with Xcode 10.1
Building the App with the new Xcode 10.1 creates a crash when the user tries to open a post/page from their blog's post/page list.

The crash happens [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/505c23ae10663c6e0fc3ad52dc8e915f342b18df/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L1644)

The stack trace is:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000107cb24bc libswiftCore.dylib`swift_objc_classCopyFixupHandler(objc_class*, objc_class*) + 48
    frame #1: 0x00000001d7cd1894 libobjc.A.dylib`alloc_class_for_subclass(objc_class*, unsigned long) + 120
    frame #2: 0x00000001d7cd1ee0 libobjc.A.dylib`objc_allocateClassPair + 156
    frame #3: 0x00000001d95497b4 Foundation`_NSKVONotifyingCreateInfoWithOriginalClass + 136
    frame #4: 0x00000001d95426d0 Foundation`_NSKeyValueContainerClassGetNotifyingInfo + 84
    frame #5: 0x00000001d9458084 Foundation`-[NSKeyValueUnnestedProperty _isaForAutonotifying] + 88
    frame #6: 0x00000001d9457f24 Foundation`-[NSKeyValueUnnestedProperty isaForAutonotifying] + 108
    frame #7: 0x00000001d9456050 Foundation`-[NSObject(NSKeyValueObserverRegistration) _addObserver:forProperty:options:context:] + 420
    frame #8: 0x00000001d945522c Foundation`-[NSObject(NSKeyValueObserverRegistration) addObserver:forKeyPath:options:context:] + 128
  * frame #9: 0x0000000102672a5c WordPress`AztecPostViewController.addObservers(toPost=0x0000000283f37c60, self=0x0000000109a8d400) at AztecPostViewController.swift:1633
```
(Thanks @jklausa !)

For this reason, until this is solved, is recommended to build with Xcode 10, since the crash just happens when building with 10.1.

cc @wordpress-mobile/platform-9 

Thank you @jtreanor and @jklausa for helping figure out the source of the crash!.

### PR DESCRIPTION
**Pull request by etoledom**
Fixes #10389 .

Since this have been working from 2017, and now after the Xcode update it started crashing, we could assume that there's a bug introduced on this new Xcode version.

### Search:

The crash happens at `swift_objc_classCopyFixupHandler`. It seems to be a private API and I couldn't find anything about it, or crashes related to it. (Even though it says it comes from `libswiftCore.dylib` 🤔 )

Searching about Xcode 10.1 KVO related issues didn't help either.
Xcode 10.1 [release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_1_release_notes/) didn't show relevant information.

Bottom line, I couldn't find information that could help.

### Experimenting:

Since this seems to be related to `swift_objc` interoperability, one of my first tests was to see if it crashes when there's no swift code related. `AbstractPost` is already Objc, so I created a small Objc class to be the observer. It also crashed in the same way. 🤔 🤔 

What about `AbstractPost.dateCreated`?

It's a computed var (objc getter-setter):
```objc
- (NSDate *)dateCreated
{
    return self.date_created_gmt;
}

- (void)setDateCreated:(NSDate *)localDate
{
    self.date_created_gmt = localDate;
    /// ...
}
```

Clearly `dateCreated` depends on `date_created_gmt`, but I'm not sure how KVO is working here. 
🤔 🤔 🤔 

I saw that `keyPathsForValuesAffectingDateCreated` wasn't implemented so I made a simple implementation returning `date_created_gmt` but it also does nothing. I haven't used KVO in some years already so I might be missing important things.

### Workaround

Finally I decided to try observing `date_created_gmt` directly. It doesn't crash anymore and preliminary tests show that it performs in the same way.

If there are more things we could try or if there are resources that I didn't find, I'll be happy to try/check out and modify this PR accordingly.

Thank you!

### To test:
**Reproduce the crash:**
1. Checkout `release/11.2` (or develop) 
2. Build and run with Xcode 10.1 on a iPhone XS or XS max running iOS 12.1. This configuration is proven to experiment this issue.
3. Open one of your posts from the site's post list.
4. Check that it crash.

**Test fix:**
1. Check out this branch.
2. repeat 2 and 3 from **Reproduce the crash:**.
3. Check that the crash is fixed.
4. Edit your post changing the creation date.
5. Check that [this line](https://github.com/wordpress-mobile/WordPress-iOS/blob/9954975fc06ed6d5e7da8293b7240a5346de9790/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L1609) is called.

### CODE REVIEW

**Comment by jklausa** [comment]
I'm flabbergasted at what's going on here. 

I can get it to crash even in circumstances where it makes _absolutely no sense_. I renamed the property on `AbstractPost` to a gibberish, like `testOfDateOFCreation` and remove the implementation from `BasePost` (and `@synthesize` it instead), _it still crashes_.  I have no idea how that's even possible. Changing the order of items in ` addObservers(toPost: AbstractPost)` also has no effect.

This is absurdely bizarre.

**Comment by etoledom** [comment]
Both `toPost` and `#keyPath(AbstractPost.dateCreated)` are valid values. So everything in our side is working properly (or as it was before).

I've been trying to reproduce this crash on a clean project to properly fill a Radar but I haven't had success so far.

Everybody is welcome to join the party. 🎉

**Comment by etoledom** [comment]
This is the setup I made to try to reproduce this crash (unsuccessfully so far):
https://github.com/etoledom/test-crash-xcode-10-1

Independent of that, @jklausa what do you think about this workaround?

**Comment by diegoreymendez** [comment]
@etoledom - I'm not sure if the following is required for calculated properties or not, as the documentation is quite slime, but have you tried / can you try this in the setter?

```objc
- (void)setDateCreated:(NSDate *)localDate
{
    [self willChangeValueForKey:@"localDate"];
    self.date_created_gmt = localDate;
    [self didChangeValueForKey:@"localDate"];
}
```

**Comment by etoledom** [comment]
@diegoreymendez - Thanks for the idea!
I didn't tested it before, I did test it now, and it didn't work. 😩

Maybe @aerych could have an insight? 
Since you have worked on that area of the code (the `AbstractPost` side at least). 🙏

**Comment by aerych** [comment]
> Maybe @aerych could have an insight?

Not really, I'm afraid.  Observing `date_created_gmt` seems like it would do the trick (its what I'd have tried) and Diego's [comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/10400#issuecomment-436363121) covers what I had mentioned in Slack the other day.   Other than there being some bizarre caching going on with @jklausa's device I'm not sure what else it could be.  

For a very hacky work around I suppose rather than KVO we could rely on Notification center and have `dateCreate` dispatch events that could be observed. 😬

**Comment by jklausa** [comment]
Let's get this in. I have absolutely no idea what's going on here, but this fixes the crash, so ¯\_(ツ)_/¯

**Comment by jtreanor** [comment]
Thanks for the quick fix on this @etoledom!

**Pull request merged**
