### PR TITLE
Notifications: Autosizing Nightmare

### LINKED ISSUE #6085: Notification Details: Comments might get cut off
We've received reports indicating that Comments Details might get cut off.

This might be a bug introduced when we toggled Autosizing Cells on (Ref. #5924). Let's review, and fix ASAP.

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:
Implements a (temporary) workaround, to be removed once we enable Readability.

Please, DM me regarding details on how to test!

Fixes #6085

Needs review: @kurzee 

Brent, may i bug you with a super fun review?
Thanks in advance sir!

cc @kwonye

### CODE REVIEW

**Comment by kurzee** [comment]
Not sure if this is related, but the paragraph breaks didn't make it into the cell for this comment:

simulator screen shot oct 18 2016 5 43 46 pm

screen shot 2016-10-18 at 5 44 46 pm

**Comment by kurzee** [comment]
Also the Notifications cell itself didn't quite display as I would expect, maybe OK though: 
screen shot 2016-10-18 at 5 45 53 pm

**Comment by kurzee** [comment]
@jleandroperez other than the comments above, which are probably not new issues, this is good to go: :shipit:

**Comment by jleandroperez** [comment]
@kurzee thanks **A LOT** for the review!!.

Paragraph breaks, apparently, get filtered somewhere, backend side, as well. I'll poke the backend team to get that checked.

RE: Weird Notification Listing, caused by `Word Wrap` preference. Since `corned` can't be displayed, eeeeverything goes to the next line, so that'd be expected.

Again, thanks for helping me out!!

**Pull request merged**
