### PR TITLE
Integrate gutenberg-mobile release 1.62.2

### PR DESCRIPTION
**Pull request by enejb**
## Description
This PR incorporates the 1.62.2 release of gutenberg-mobile.
For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/4051

Release Submission Checklist

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by jd-alexander — APPROVED** [review]
Smoke tested via https://github.com/wordpress-mobile/gutenberg-mobile/pull/4051#pullrequestreview-767205917 LGTM 🚢

**Comment by mokagio** [comment]
Thanks folks! ~~I've enabled auto-merge so this will go in~~ (Update: only the author can enable auto-merge, apparently) I'll merge as soon a Buildkite is done. Then I'll ship a new beta 🚀

**Comment by jd-alexander** [comment]
Thanks @mokagio the tests had failed initially. I doubt it's related to these changes though.

**Comment by jd-alexander** [comment]
The WP Android side of things have been integrated https://github.com/wordpress-mobile/WordPress-Android/pull/15391

**Comment by enejb** [comment]
Thanks for all your help @mokagio  and @jd-alexander!

**Comment by mokagio** [comment]
> the tests had failed initially. I doubt it's related to these changes though.

Correct, it was an hiccup in downloading the cache

```
📦 Restoring cache for wordpress-mobile/wordpress-ios/ from a8c-repo-mirrors | 0s
-- | --
  | Using Git Mirror Server at http://10.254.3.15:41362
  | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  | Dload  Upload   Total   Spent    Left  Speed
  | 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  | 🚨 Error: The plugin git-s3-cache pre-checkout hook exited with status 1
```

**Comment by AliSoftware** [comment]
> Update: only the author can enable auto-merge, apparently

@mokagio I think it's more related to the fact that the PR targets `release/18.3` not `develop`. I have noticed that apparently auto-merge only seems to works for PRs targeting the default branch (`develop`)? 🤔

**Pull request merged**
