### PR TITLE
Replacing the BlogDetails icons with tinted gridicons.

### PR DESCRIPTION
**Pull request by kurzee**
Small step towards reusing gridicons throughout the app, and in this round within `BlogDetailsViewController`.

To test:

1. Build and run the branch `feature/blog-details-gridicons` on either the device or simulator.
2. Ensure each icon is the correct icon for the corresponding row.

Needs review: @frosty would you take a peak at the code/file changes?
Needs review: @mattmiklic would you do a quick design review?

simulator screen shot mar 31 2016 3 23 36 pm

### CODE REVIEW

**Comment by mattmiklic** [comment]
Nice! 🙌 I see no visual differences from the current icons, therefore, they look perfect.

**Comment by frosty** [comment]
This looks good to me, @kurzee! 

I'm thinking we may want to create our own Gridicons framework that spits out Gridicons at various sizes – either with a class method for each icon (think `Gridicons.pagesIcon()`) or a single class method that takes an enum value (`Gridicon(type: .Pages)`. The latter's perhaps nicer. It'd be good to avoid having to hardcode strings for the icons across the app. We might also have an issue when we need gridicons in different sizes, because PDFs in Xcode aren't truly vectors – they're saved out as PNGs at the 1x, 2x, 3x sizes at compile time.

Anyway, I have some thoughts about that that I might experiment with later today. But for now:

:shipit:!

**Comment by mattmiklic** [comment]
If it helps in figuring out some of the logic -- Gridicons generally should only be used at their original size of 24x24 or at a few other specific multiples: 18x18, 36x36, and 48x48. Some explanation can be found here: https://github.com/automattic/wp-calypso/blob/master/docs/icons.md

**Comment by kurzee** [comment]
@frosty @mattmiklic I'd love a gridicons framework and was thinking about that a bit yesterday. There's still quite a few icons in the app that are duplicates of gridicons and ultimately a larger PR is needed to migrate all the other icons and views using those icons.

**Comment by kurzee** [comment]
@frosty @mattmiklic thanks for the review guys!

**Pull request merged**
