### PR TITLE
Don't autosync if uploading a post.

### LINKED ISSUE #2804: Sometimes new posts are duplicated in app
When you create a new post, it might appear on the posts list twice temporarily. What happens:

- New posts don't have an ID until the upload request finishes
- When you save a new post, the editor will dismiss and go back to the posts list
- When the posts list appear, it will sync posts. The result might include the new post if the request finishes before the upload request does

### PR DESCRIPTION
**Pull request by aerych**
Closes #2804

### CODE REVIEW

**Comment by aerych** [comment]
cc @bummytime

**Comment by bummytime** [comment]
@aerych This PR helps — I'm no longer seeing the extra post after a save. However, as I am sure you know, if I pull to refresh the post list while uploading I will get the dup:

https://cloudup.com/cLK7a5-dmlb

I think this fix will cover 98.67% of the use cases. The question I have is if we should close #2804. Maybe a new issue specifically mentioning the manual refresh use case?

Thoughts?

**Comment by aerych** [comment]
> if I pull to refresh the post list while uploading I will get the dup

Honestly I don't think I considered pull to refresh :facepalm: 
Let's address that in this PR too.  Patch coming.

**Comment by aerych** [comment]
@bummytime take two :)

**Comment by bummytime** [comment]
This looks and works great @aerych! So much win here. :shipit:

**Comment by aerych** [comment]
Thanks @bummytime !

**Pull request merged**
