### PR TITLE
Feature/4105 share settings

### PR DESCRIPTION
**Pull request by aerych**
This patch implements sharing button management and other sharing settings. The feature is accessed from the sharing option on the blog details screen, then clicking on the manage button.

To test:
Edit the various none sharing button settings. Confirm they are updated in the blog.

Enable and disable the Twitter sharing button. Ensure the Twitter section is present when the button is enabled and absent when it is disabled.

Add buttons to the sharing and more sections. Ensure that buttons enabled in one are not enabled in the other. 

Add buttons to the sharing and more sections. Ensure they are enabled on the blog. 

Drag to reorder buttons in the sharing and more sections. Ensure they changed are reflected on the blog. 

Needs review: @alexcurylo

### CODE REVIEW

**Comment by alexcurylo** [comment]
If you have author-level access on a site, on web Calypso you have access to the Publicize settings but not the sharing button management. So SharingViewController should exclude that section. What happens right now is an "You do not have the capability to manage sharing buttons for this site" error in the console when `syncSharingButtonsForBlog` fails.

**Comment by alexcurylo** [comment]
Hmmm ... but when I actually try to connect up an author-level blog on the web, it consistently returns an error. Perhaps you're not actually supposed to see any sharing settings unless you're an admin? That would fit with another error I'm seeing, "Publicize is disabled on this blog." from `syncPublicizeConnectionsForBlog`.

**Comment by alexcurylo** [comment]
There's a failure path when accessing a blog that last had its settings synchronized before `sharingButtonStyle` was added: since it's empty, in `SharingButtonsViewController.setupButtonStyleSection()`

                cell.detailTextLabel?.text = self.buttonStyles[self.blog.settings.sharingButtonStyle]!

will crash with a nil optional. Probably there should be a guard to synchronize settings if the new sharing fields are empty?

**Comment by alexcurylo** [comment]
Settings synchronization is also problematic with fields like 'Show reblog button' and 'Show like button'; when changed on the web, they will not update in the app until the Settings controller is shown and a sync is triggered there.

**Comment by alexcurylo** [comment]
> Drag to reorder buttons in the sharing and more sections. Ensure they changed are reflected on the blog.

You know what would be REALLY cool? If you could drag a service from one section to the other.

**Comment by alexcurylo** [comment]
Currently you can't select the label/button style/twitter name rows. Was that supposed to be set after`SharingButtonsViewController.configureTableView()` starts editing?

        tableView.setEditing(true, animated: false)
        tableView.allowsSelectionDuringEditing = true

**Comment by alexcurylo** [comment]
It would be elegant if the Twitter username edit field could supply a leading '@', same as the web edit field. Presently it's added silently server side when synced, apparently.

**Comment by alexcurylo** [comment]
Currently the Button Style selector shows the internal values and crashes on selection. Looks like in `SharingButtonsViewController.setupButtonStyleSection()` the value should be appended to titles and the key appended to values in

        _ = buttonStyles.map({ (k: String, v: String) in
            titles.append(k)
            values.append(v)
        })

**Comment by alexcurylo** [comment]
The buttons in the 'Reblog & Like' section aren't visible on my Jetpack blog's web dashboard, and manipulating their settings in the app doesn't seem to have any affect. Am I missing a setting someplace, or should that section only be available for wp.com blogs?

**Comment by alexcurylo** [comment]
That's all I have for now -- aside from that last 'Reblog & Like' note, everything appears to work as expected on the blog and display as expected in the web dashboard on both wpcom and Jetpack blogs. Nice work!

**Comment by aerych** [comment]
Thanks for the excellent review Alex!  I'm busy with the meetup project for the next few days but I'll address comments as I'm able. :)

**Comment by aerych** [comment]
> Settings synchronization is also problematic

Ugh. I completely over looked this.  Updated.

> You know what would be REALLY cool? If you could drag a service from one section to the other.

@hugobaeta and I looked at a few different approaches to sorting the list and dragging between sections was one.  We ended up going a different way because it might not be clear to the user that a button could be dragged into a section that was empty.

> Currently you can't select the label/button style/twitter name rows

Bah! Yes. I neglected to make them selectable when the tableView was in edit mode. Updated.

> Currently the Button Style selector shows the internal values and crashes on selection

Nice catch. Yah, the keys and values were reversed in `handleEditButtonStyle`.  Fixed.

> The buttons in the 'Reblog & Like' section aren't visible on my Jetpack blog's web dashboard

These need to be excluded from Jetpack sites.  Updated.

**Comment by aerych** [comment]
Ready for another round @alexcurylo  :)

**Comment by alexcurylo** [comment]
Here's an interesting case:

**Comment by alexcurylo** [comment]
The trick there seems to be that `switchRowForMoreSectionButton()` applies changes to a `SharingButton` in the main context that are not synced to the web. Thus they will persist local-only until the next sync. I'd suggest syncing on every change, as is done with moving rows.

**Comment by aerych** [comment]
Just realized I missed the comment about the twitter @ symbol. I'll take care of that directly.

**Comment by alexcurylo** [comment]
One more sharing access problem: When you're an admin on a private site. On the web, what happens is that attempting to add share/more buttons results in a "Sharing options are limited on private sites." message; and although Publicize options are displayed, they always fail connection. In the app, you get a  "Publicize connection synchronization failed" overlay message on entering, because of `syncConnections` result "Publicize is disabled on this blog." (publicize_disabled).

**Comment by alexcurylo** [comment]
That's all for this round -- all functionality appears working as expected on WPcom and Jetpack blogs.

**Comment by aerych** [comment]
> Presently it's added silently server side when synced, apparently.

Its actually omitted in the REST API results. The web form adds it as decoration. I've updated the button settings screen to display the @ symbol but I'm going to leave the edit vc alone as its supposed to be generic. 

>  I'd suggest syncing on every change, as is done with moving rows.

This gets a bit tricky as it impacts button order. Rather than syncing on every change, let's keep the save behavior as it is but have the sharing button vc use a child context instead of the main context.  This way any unsaved changes will be properly discarded. 

> When you're an admin on a private site

Another good catch. :)  For simplicity (and since the web experience seems pretty poor) let's hide the feature if the site is private. We can revisit later if the web experience changes. 

One other change in this round... I remembered that publicize and sharing are separate Jetpack modules and either can be enabled or disabled separate from the other.  I've added some new logic so we avoid showing a disabled sharing feature and just show the enable done in these situations. 

Ready for round three! :)

**Comment by alexcurylo** [comment]
Agree with comments and all functionality appears to be in order. Nice work! :shipit:

**Comment by aerych** [comment]
Thanks @alexcurylo !

**Pull request merged**
