### PR TITLE
Support editing media metadata via XML-RPC #809

### LINKED ISSUE #20726: Ability to Edit Title, Caption, Description, and Alt Text of Images in WordPress App Media Library Without Jetpack
### Expected behavior
If you're connecting to a site without the Jetpack plugin, you should be able to update the Title, Caption, Description, and Alt Text for media within the media library.

### Actual behavior
If you're connected to a site without the Jetpack plugin, you can view the Title, Caption, Description, and Alt Text, but there is no way to update it.

### Steps to reproduce the behavior
1. Connect to a site in the WordPress app using your WP Admin credentials (without Jetpack).
2. Navigate to the media library and tap on an image.
3. Note that the Title, Caption, Description, and Alt Text cannot be changed.

##### Tested on iPhone 13 Pro, iOS 16.4.1, WordPress iOS 22.4

### PR DESCRIPTION
**Pull request by staskus**
Fixes #20726

- [x] Make sure WPKit Podspec version is updated correctly

## Description

There's a long-standing issue created https://github.com/wordpress-mobile/WordPress-iOS/issues/20726 correctly pointing out that there's no ability to edit a title, caption, description, and alt text of images for a site without Jetpack.

It happens because it wasn't supported in `MediaServiceRemoteXMLRPC` since XML-RPC doesn't have specific methods for updating media metadata. However, media is just a type for the post, so using `wp.editPost` method is sufficient to make updates.

The only field that is not supported is alt text which is kept on post metadata and cannot be **fetched** and **updated** via XML-RPC:
- Ticket: https://core.trac.wordpress.org/ticket/58582 
- Previous investigation: https://github.com/wordpress-mobile/WordPress-Android/issues/18514#issuecomment-1589752274

## Solution

Media is a type of post therefore "wp.editPost" can be used to edit media metadata via XML-RPC. 

Note that alternative text cannot be edited due to lack of XML-RPC support https://core.trac.wordpress.org/ticket/58582. Explanation: https://github.com/wordpress-mobile/WordPress-Android/issues/18514#issuecomment-15897522

Android solution: https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/98d43f5f4ed25dbacac85fc42889a6ac529c03e4/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/media/MediaXMLRPCClient.java#L99 

### Self-hosted site

1. Create a self-hosted site with jurassic ninja
2. Log into Jetpack app
3. Media
4. Upload media
5. Click on the item
6. Confirm alt text not shown
7. Confirm title, caption, and description are editable
8. Enter title, caption, and description values
9. Go to WP-Admin and confirm the values are set

### Jetpack-powered site

1. Log into Jetpack-powered (WP.com) site
2. Media
3. Upload media
4. Click on the item
6. Confirm title, caption, alt text, and description are editable
7. Enter title, caption, description, and alt text values
8. Go to Site Dashboard and confirm the values are set

## Regression Notes
1. Potential unintended areas of impact

Jetpack-powered use cases continue to work

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by staskus** [comment]
Update after https://github.com/wordpress-mobile/WordPress-iOS/pull/23366 is merged

**Review by kean — APPROVED** [review]
Great addition! Tested & reviewed.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/292">25.2</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
