### PR TITLE
Specify in PRs whether work is behind feature flag

### PR DESCRIPTION
**Pull request by guarani**
We'd like to easily identify whether a PR is going to be available to users or will be kept behind a feature flag until further notice.

This PR adds a sentence to the top of PRs to help authors make this information clear and visible to other contributors. Suggestions on alternatives welcome.

If we move forward with this, we should do a similar PR for Android.

### CODE REVIEW

**Review by staskus — APPROVED** [review]
I think if we want to have an instant visibility for a PR if it was made under the feature flag, this is a good option 👍

**Comment by guarani** [comment]
Thanks for reviewing 🙇 I'll hold-off merging for now since there are ongoing discussions (pc8eDl-so-p2#comment-342) and changes to the PR template might warrant wider input and communication.

**Comment by mokagio** [comment]
@guarani I'm going to close this given there hasn't been any activity in a long time. Feel free to reopen if needed.

**Comment by guarani** [comment]
Good call @mokagio! I don't think we need this anymore. I haven't seen any more instances where it would be useful.

**Pull request closed without merging**
