### PR TITLE
Switch to saved posts when tapping "view all" on the saved post notice

### LINKED ISSUE #15514: Reader: View All for saved posts displaying posts from wrong stream
### Expected behavior
If a user saves a post then taps on the `View All` button on the toast message, the Reader should:
- switch to the `Saved` tab
- display saved posts

### Actual behavior
If a user saves a post then taps on the `View All` button on the toast message, the Reader:
- switches to the `Saved` tab
- displays posts from the previous stream

### Steps to reproduce the behavior

1. Go to the Reader tab > `Following`
2. Save a post > tap on `View All` in the toast message

view_all

##### Tested on [device], iOS [version], WPiOS [version]

- iPad Air 4, iOS 14.2, WPiOS 16.3
- iPhone SE, iOS 14.2, WPiOS 16.3

### PR DESCRIPTION
**Pull request by Gio2018**
Fixes #15514

To test:
- Go to the Reader
- Save a post for later
- tap on "view all" in the notice that appears at the bottom after saving, and make sure you are redirected to the "Saved" tab and the content matches your saved posts

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by emilylaguna — CHANGES_REQUESTED** [review]
This works but it looks like it's causing a weird issue where the Discover view is display the site stream header when it shouldn't. 

Disabling `setContent?(tabItems[index].content)` seems to fix this.

**Comment by Gio2018** [comment]
@emilylaguna @leandroalonso would any of you have some time to review the latest changes on this PR? If not I can assign it to someone else, thank you!!

**Comment by emilylaguna** [comment]
Heya! I'm planning on looking at this a little later today.

**Review by emilylaguna — APPROVED** [review]
Working now! LGTM! 🚢

**Comment by Gio2018** [comment]
> Working now! LGTM! 🚢

Thanks so much @emilylaguna !!

**Pull request merged**
