### PR TITLE
Integrate gutenberg-mobile release 1.96.1

### PR DESCRIPTION
**Pull request by geriux**
## Description
This PR incorporates the 1.96.1 release of gutenberg-mobile.
For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/5821

Release Submission Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

**NOTE:** Before merging, the Gutenberg Mobile reference should point to a version tag.

**Comment by geriux** [comment]
Hey @mokagio 👋 I was wondering if we could merge this even though the UI tests are failing 😅 I see they're failing in this other PR https://github.com/wordpress-mobile/WordPress-iOS/pull/20785 We smoke-tested the app and it works fine, they only changes are in the editor.

**Comment by mokagio** [comment]
> I was wondering if we could merge this even though the UI tests are failing 😅 I see they're failing in this other PR https://github.com/wordpress-mobile/WordPress-iOS/pull/20785 We smoke-tested the app and it works fine, they only changes are in the editor.

Yes. 

One argument would be that these changes could have added _new_ failures, but with the current state of UI tests the cost of verifying it is higher than the assurance we'd get from it.

I'll merge and ship a new beta.

**Comment by geriux** [comment]
> I'll merge and ship a new beta.

Thank you!

**Pull request merged**
