### PR TITLE
WebViews Auth issue: Recover from disabled auth token

### LINKED ISSUE #15611: Invalid key error shown when viewing a post in the app
It was reported in 3617798-zen that the user wasn't able to view a post in the app through My Site > Blog Posts > View on a WordPress.com Simple site with a custom domain (Public). They saw the `Invalid key [1]` error on the screen with the URL `r-login.wordpress.com`. The same behavior was observed if the user previewed the post in the editor.

When they tried viewing the posts in the app on two other WordPress.com Simple sites (without custom domain) in private mode, they were asked to log in.

I wasn't able to replicate this in SSP.

### Expected behavior

The user expects to be able to view their posts in the app through My Site > Blog Posts > View.

### Actual behavior

The user wasn't able to view the post with either the error `Invalid key` error on their public site or they were asked to log in for the private sites.

### Steps to reproduce the behavior

1. Go to My Site > Blog Posts
2. Tap View on one of the posts
3. The screen prompted the error `Invalid key`
4. Tap the post to go to the editor
5. Tap three dots > Preview
6. The same issue in Step 3 is observed

px93uvWz

##### Reported WPiOS 16.3.

I'm asking for the device and iOS version and will report back.

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes** https://github.com/wordpress-mobile/WordPress-iOS/issues/15611

## Description:
The error logged in #15611 was the result of `r-login` being loaded with a stale auth cookie which the app provides to prevent having to fetch a fresh cookie each time. However, there are actions that can be taken that invalidate those cookies on the server but the app mechanisms to clean them up weren't in place. This changeset allows the request to go then tries again if it runs into some errors. 

### Setup
You'll want a simple site with a custom-mapped domain name and the ability to invalidate the web token in the web view.

You can invalidate the token either by enabling 2FA or using some of the internal tools.

### Test
1. Log in to the app and open a Web view to make sure your Auth tokens are populated.
2. Invalidate your token.
3. Navigate to My Site > View Site
    - You can also check by Navigating to My Site > Posts > View (on one of the posts) 
4. Expect your Web View to load.

## Regression Notes
1. Potential unintended areas of impact
The app has limited indications that could signal that the cookie is bad so we could be cleaning it up too regularly or for issues not related to authentication. 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I checked the other web views from this scenario and wasn't able to produce any oddities.

3. What automated tests I added (or what prevented me from doing so)
Added tests around the flows for when we want to clear the cookies.

## PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by chipsnyder** [comment]
@diegoreymendez I see you've worked in this area the most. Would you be able to take a look at this one for me?

**Comment by diegoreymendez** [comment]
I'm getting the login screen with 100% reproduction rate when following these steps:

1. Use an account that has 2FA disabled to run WPiOS
2. Select an atomic site under "My Site" and tap on View Site
3. While the web view is still open, go to your web browser, and enable 2FA for the account.
4. Go back to WPiOS
5. Close the web view
6. Go to Posts, and tap on "View Post" for any published post.

Closing and reopening that web view loads the post just fine - it's only on the first attempt that I'm seeing that screen.

**Review by diegoreymendez — COMMENTED** [review]
I'm getting the login screen with 100% reproduction rate when following these steps:

1. Use an account that has 2FA disabled to run WPiOS
2. Select an atomic site under "My Site" and tap on View Site
3. While the web view is still open, go to your web browser, and enable 2FA for the account.
4. Go back to WPiOS
5. Close the web view
6. Go to Posts, and tap on "View Post" for any published post.

Closing and reopening that web view loads the post just fine - it's only on the first attempt that I'm seeing that screen.

**Comment by chipsnyder** [comment]
@diegoreymendez this is ready to go again whenever you have the time.

**Comment by diegoreymendez** [comment]
@chipsnyder - Sorry for the delay.  I'll be checking this PR tomorrow first time in the morning!

**Review by diegoreymendez — APPROVED** [review]
Really nice work @chipsnyder !

**Pull request merged**
