### PR TITLE
Update tabbar icons & remove labels

### LINKED ISSUE #4546: Update Tab Bar Icons to Match Latest on Web
Reference - https://github.com/Automattic/wp-calypso/pull/631

### PR DESCRIPTION
**Pull request by oguzkocer**
Closes #4546. This PR updates the tabbar icons to the latest version and removes the tabbar item labels. The icons are moved around a bit to have the correct spacing and look centered. It also sets all the accessibility labels and removes the previous hack since we don't need to backwards compatibility anymore. This is the first time I am using Xcode pdfs for the images, so please make sure I did it correctly. I've moved around the app to make sure no other VC changes the title of the tabbars, please make sure to test this as well. Here are before and after screenshots: 

simulator screen shot dec 22 2015 18 58 48
simulator screen shot dec 22 2015 18 15 43

Needs review: @koke 
Design review: @mattmiklic

### CODE REVIEW

**Comment by koke** [comment]
> This is the first time I am using Xcode pdfs for the images, so please make sure I did it correctly

PDFs look set up correctly and icons look sharp.

As I mentioned on Slack, I'm not too happy about restricting the view controllers to not set `self.title` for this to work. I think if we don't want any labels, we should make sure the tab bar doesn't display labels regardless of it's VCs titles.

**Comment by mattmiklic** [comment]
After making an adjustment to the Reader icon for better optical alignment, this is good to go from a design point of view. :shipit: 

New screenshot:

screen shot 2015-12-22 at 1 38 34 pm

**Comment by koke** [comment]
I don't have any better solutions, so let's go with the navigationItem titles. :+1:  once the new icons are in

**Comment by oguzkocer** [comment]
Thanks for the review @koke & @mattmiklic!

**Pull request merged**
