### PR TITLE
[RNMobile] Parent PR: Add Setting to Set/Remove a Featured Image Directly from Image Block

### PR DESCRIPTION
**Pull request by SiobhyB**
Fixes the iOS side of the following issue: wordpress-mobile/gutenberg-mobile#1011

`gutenberg`: https://github.com/WordPress/gutenberg/pull/31345
`gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3449

## Description

Introduces an option to set/remove an image as featured from the image block's settings, with a "featured" banner to denote when an image is already featured. The end goal is to make it easier for users to both identify and set/remove featured images directly from the post editor.

This PR builds on the work done in https://github.com/WordPress/gutenberg/pull/30806 and https://github.com/WordPress/gutenberg/pull/28854 to introduce this functionality to Android. For iOS, the work has been split up into the following PRs:

Gutenberg PR | Gutenberg Mobile PR | iOS PR | Merged
-- | -- | -- | --
[Display a `Featured` banner over any image block containing a post's featured image](https://github.com/WordPress/gutenberg/pull/31347) |  https://github.com/wordpress-mobile/gutenberg-mobile/pull/3390 |  https://github.com/wordpress-mobile/WordPress-iOS/pull/16332 | ✅
[Include a `Set/Remove as Featured` option in the image block's settings](https://github.com/WordPress/gutenberg/pull/31415) | https://github.com/wordpress-mobile/gutenberg-mobile/pull/3450 | https://github.com/wordpress-mobile/WordPress-iOS/pull/16426 | ✅

_- Once the PR has been merged it will be updated with a_ ✅  

## How has this been tested? Screenshots? Types of changes?

Please refer to the first PR in each row (the Gutenberg PR) for test cases, screenshots, and further details of the types of changes involved.

## Regression Notes

1. Potential unintended areas of impact

As this PR adds a banner over the image block, there is some potential for it to unintentionally have a negative impact on the existing UI and/or animations that take place when an image is replaced within the block (depending on whether it's featured or not).

It also adds another flow for users to set/remove featured images, so there is some potential for it to unintentionally have a negative impact on the existing flow (found via Post Settings).

A third unintended area of impact is the `wpios_editor_post_featured_image_changed` Track event. This event currently only fires when a featured image is changed via Post Settings. With this PR, it should also be fired when a featured image is changed via the image block, with a `gutenberg` property to differentiate it.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

The steps taken to test whether the intended flow works as expected can be found in the Gutenberg PRs [here](https://github.com/WordPress/gutenberg/pull/31415) and [here](https://github.com/WordPress/gutenberg/pull/31347), with additional steps for verifying the Tracks event fires as expected listed in [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/16426).

3. What automated tests I added (or what prevented me from doing so)

No automated tests.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by SiobhyB** [comment]
👋 @illusaen, do you perhaps have any availability to review this PR either this week or next? This is the main feature branch for the `Set/Remove Featured Image` project that you've already helped me with, so all the code here has already been reviewed through other PRs and it's in need of a final overall review/test.

There are two known issues that will be worked on separately and I don't believe to be blockers to this one being merged:

* There are some occasions where the notice that's displayed after clicking the button flickers. I'll be creating a separate issue for this, but it can't be reproduced consistently and I've seen it in other places where the notice is called, so I don't believe it to be specific to this PR.
* The undo/redo functionality doesn't work correctly when used immediately after setting a featured image, which I'm working on in https://github.com/WordPress/gutenberg/pull/33057. 

Let me know how that sounds to you and thanks in advance!

**Comment by SiobhyB** [comment]
@illusaen, just pinging again on this. :) Do you have any availability to review this PR?

**Review by illusaen — APPROVED** [review]
Looks good to me!

**Comment by SiobhyB** [comment]
@illusaen, thank you! Would you also be able to approve the Gutenberg and Gutenberg Mobile PRs? I can then go ahead to merge these. :)

**Pull request merged**
