### PR TITLE
Network mocking for all UI and screenshot tests

### PR DESCRIPTION
**Pull request by jtreanor**
This PR updates all of our UI and screenshot tests to use mocked networking using WireMock. The mocking functionality is shared with WPAndroid from the [WordPressMocks repo](https://github.com/wordpress-mobile/WordPressMocks).

It relies on the following open PRs:

- https://github.com/wordpress-mobile/WordPressMocks/pull/3

Other related PRs:

- https://github.com/wordpress-mobile/WordPress-iOS/pull/11655
- https://github.com/wordpress-mobile/WordPress-iOS/pull/11717
- https://github.com/wordpress-mobile/WordPress-iOS/pull/11762
- https://github.com/wordpress-mobile/WordPress-iOS/pull/11807
- https://github.com/wordpress-mobile/WordPress-Android/pull/9422
- https://github.com/wordpress-mobile/WordPressKit-iOS/pull/141
- https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/93
- https://github.com/wordpress-mobile/WordPressMocks/pull/1

To test:

- Check out this branch. Run `rake dependencies` as usual.
- Run `rake mocks` to start the mock server.
- Run the UI tests in the `WordPressUITests` target with Xcode.
- All tests should pass and there should be no errors/warnings in the terminal when you ran the mock server.

**Note:** The screenshot tests are broken in `develop` due to the recent stats changes. I think we should fix that in a separate change.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by jtreanor** [comment]
Thanks @rachelmcr!

> However, I did get this warning in the terminal when I started the mock server:

This is expected and fine. It doesn't affect us.

> And while running the UI tests on an iPad simulator (iPad Pro, 12.9-inch, 3rd Generation), I saw a number of "Request was not matched" errors (although the tests still pass).

Oh great, thank you! These should all be quick to fix.

**Comment by jtreanor** [comment]
Okay, I've updated https://github.com/wordpress-mobile/WordPressMocks/pull/3 with the missing requests.

@rachelmcr It should all be working now. Once you pull, you will need to run `rake dependencies` and then `rake mocks` again.

**Comment by rachelmcr** [comment]
Looks great now! :shipit:

**Comment by jtreanor** [comment]
Thanks, @rachelmcr! Could you also take a quick look at https://github.com/wordpress-mobile/WordPressMocks/pull/3? That's where the mocks live and you have already effectively tested them by reviewing this 😄 

Once that is merged, we can merge this PR and get these tests running on CI.

**Comment by jtreanor** [comment]
Okay, I have updated to the release version of `WordPressMocks`. There are no changes, so I will merge when green.

**Pull request merged**
