### PR TITLE
Uppercase strings with the locale to take into account language rules

### LINKED ISSUE #7449: Use localized uppercase(with:) function in login/epilogue.
See comments on #7127 to address localization issue:

https://github.com/wordpress-mobile/WordPress-iOS/pull/7127#discussion_r124372984

```swift
sectionTitle = NSLocalizedString("My Sites", comment: "Header for list of multiple sites, shown after loggin in").uppercased(with: NSLocale.current)
```

Assigning to @nheagy 😄

### PR DESCRIPTION
**Pull request by astralbodies**
Fixes #7449 

This fixes a couple instances of using uppercased() without passing in the current locale. Some languages have different rules for what's considered uppercasing based upon the character set. I also eliminated the default string from being in uppercase to simplify translations (prevents a duplicate string).

To test:
1. Build and run.
2. Make sure values are uppercased in each of the view controllers. Testing uppercase logic might be hard so just making sure default behavior isn't changed is good.

Needs review: @nheagy

### CODE REVIEW

**Comment by astralbodies** [comment]
Good point @nheagy - I'll make those changes!

**Comment by astralbodies** [comment]
@nheagy Ready for another look - I picked up on some other instances of uppercased(with:) to replace.

**Comment by nheagy** [comment]
Great! It's so nice and clean 😍

:shipit:

**Comment by astralbodies** [comment]
Thanks @nheagy!!

**Pull request merged**
