### PR TITLE
Issue/3546 standardize offline alert messages

### PR DESCRIPTION
**Pull request by elibud**
**Fixes** #3546 

This PR adds alert messages to user initiated actions when the user is offline:

- Pull to Refresh on Notifications, Reader and Blog Comments
- Replying to a message while offline was displaying a non appropriate error and clearing the text, now the error is displayed before invoking the handler and the entered text is not cleared.
- Actions on comments (like, trash, etc) and user cells (follow).

**To test:**

Put the phone on Airplane mode and:
1. Pull to refresh on Notifications
2. Pull to refresh on Blog Comments
3. Pull to refresh on Reader
4. Reply to a Comment
5. Follow a User
6. Like, Approve, Trash, Spam and Edit a Comment 

Needs review: @kurzee

### CODE REVIEW

**Comment by kurzee** [comment]
Found another case where we should add this:

1. Airplane mode, on Notifications.
2. Swipe left on one of the cells.
3. Hit delete or unapprove, no error presented.
4. Also seems to change state as if it succeeded.

The same can be repeated for Blog Details -> Comments, Blog Posts, Pages (maybe another PR)

**Comment by elibud** [comment]
Great catch @kurzee thanks, I'll ping you later to clarify all the missing cases.

**Comment by elibud** [comment]
@kurzee updated :)

**Comment by kurzee** [comment]
@elibud good to go! Nice work!

**Comment by elibud** [comment]
@kurzee thanks for the help, suggestions and testing!

**Pull request merged**
