### PR TITLE
Constraint Quick Actions Max Width

### PR DESCRIPTION
**Pull request by bjtitus**
Sets the Quick Actions maximum width to 500 points based on feedback to reduce spacing from @osullivanchris and to avoid running into the FAB.

### Before

Screen Shot 2020-04-10 at 1 04 32 PM

### After
Screen Shot 2020-04-10 at 12 42 36 PM

## To Test

- Visit the Blog Details Page
- Check the Quick Actions Buttons in Portrait and Landscape

## Screenshots

<details>
  <summary><strong>iPhone 11 Pro</strong></summary>

Screen Shot 2020-04-10 at 12 42 46 PM

Screen Shot 2020-04-10 at 12 42 36 PM
</details>

<details>
  <summary><strong>iPhone 11 Pro Max</strong></summary>

Screen Shot 2020-04-10 at 12 48 06 PM

Screen Shot 2020-04-10 at 12 48 25 PM
</details>

<details>
  <summary><strong>iPad Pro 11"</strong></summary>

Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-04-10 at 12 44

Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2020-04-10 at 12 45
</details>

## PR submission checklist

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
@bjtitus @osullivanchris Would it make sense to keep the margins between items and sizing the same, and only adjust to condense on very narrow viewports (iPhone SE or like in the iPad example above)? Widening out the margins looks a little unbalanced to my eye, although this is just a _tiny_ detail 🙂

**Comment by bjtitus** [comment]
@iamthomasbishop Is this more of what you're talking about?

Screen Shot 2020-04-10 at 2 13 34 PM

Screen Shot 2020-04-10 at 2 13 30 PM


Screen Shot 2020-04-10 at 2 18 01 PM

**Comment by iamthomasbishop** [comment]
Precisely! I guess I should've phrased that better — "make the max-width whatever the current width is for the 'normal' size iPhone" 😄 @osullivanchris feel free to overrule me here, but I thought this would look a little more balanced.

**Comment by bjtitus** [comment]
@ScoutHarris Thanks for catching this! Should be fixed now. I keep having trouble identifying the new ones from existing ones in detail view controllers.

**Pull request merged**
