### PR TITLE
Fixes several static analyzer warnings in WordPressKit & Stats Framework

### LINKED ISSUE #7417: WordPressKit: Fix the numerous static analyzer issues
Title has it.

### PR DESCRIPTION
**Pull request by astralbodies**
Fixes #7417 

To test:
1. Run static analyzer.
2. Verify no warnings appear for WordPressKit or WordPressComStatsiOS
3. Run unit tests and verify they pass (technically Buddybuild will do this).

Needs review: @koke

### CODE REVIEW

**Comment by astralbodies** [comment]
@bummytime Any chance you could take a peek?

**Comment by bummytime** [comment]
@astralbodies Yep!

**Comment by bummytime** [comment]
Looks good @astralbodies:

b-a

Unit tests are all green too. :shipit:

**Comment by astralbodies** [comment]
Thanks @bummytime!

**Pull request merged**
