### PR TITLE
Approve 2fa challenges via notification action.

### PR DESCRIPTION
**Pull request by aerych**
This PR modifies how the app handles 2FA auth notifications so an auth challenge may be approved while the app remains in the background. This builds on previous work in #14868 (h/t @jkmassel) and #12216. 

To test:
Apply D52487-code to your wpcom sandbox, and sandbox `wordpress.com` and `public-api.wordpress.com` so you can test with dev/sandboxed push notifications.

Scenario 1:
- Switch to this branch and test the app on a device. 
- Login, view the Notifications tab and allow push notifications.
- Background the app.
- In a browser, attempt to log in to a 2fa enabled account. 
- Confirm you receive a push auth notification.
- Long press on the notification to reveal the approve and deny actions.  Confirm the UI looks good.
- Tap approve.  Confirm the app does not launch.
- Confirm you are logged in. 

Scenario 2:
Launch the app and keep it in the foreground.
- In a browser, attempt to log in to a 2fa enabled account. 
- Confirm that in the app you see a prompt to approve the log in.
- Tap approve.
- Confirm you are logged in. 

@emilylaguna and @jkmassel could I trouble y'all sandbox capable folks for a peek at this one? 
cc @jleandroperez as this might be relevant to your interests

Example:
push-notification-actions

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by emilylaguna** [comment]
👋 Hey @aerych, I've been trying to test this PR but I can not get Xcode to connect to my device (it keeps saying it's not connected) no matter what I do (restart Xcode, Computer, iPhone, Disconnect/Reconnect, etc). I'll review later if I can get it working. 😢

**Comment by aerych** [comment]
No worries @emilylaguna!  Thanks for trying!

**Review by jleandroperez — APPROVED** [review]
I've been trying to verify WPCOM's behavior (with the ARC patch mentioned in my sandbox), **but** I've hit two issues:

1. Dotcom sandbox doesn't render the Login UI properly: fixed by disabling IP spoofing **just** to load the authentication UI

2. Dotcom sandbox appears not to be processing the **Push Authentication™** app approval

Since:

1. The changes look definitely great!!
2. WPiOS's behavior has been verified in Charles, and the 2FA endpoint is effectively invoked
3. Dotcom's sandbox appears to be misbehaving when it comes to auth


Let's :shipit:, and we'll quintuple verify this with the next TestFlight build!!

Nice work @aerych!!

**Comment by aerych** [comment]
Thanks @jleandroperez !   I'll wait a bit longer for @emilylaguna and @jkmassel to share any feedback they might have. Otherwise I'm game to 🤞 and ship it and then revert quickly if there are serious issues.

**Comment by bummytime** [comment]
Love this @aerych — I've been wanting this for some time now. 🙇‍♂️ 🙌

**Comment by aerych** [comment]
Gonna go ahead and merge.  @emilylaguna, @jkmassel please feel free to still share any feedback/comments/etc you might have!

**Comment by jkmassel** [comment]
Don't have much to add – just took a look through the code and it LGTM – nice and clean :)

**Pull request merged**
