### PR TITLE
PostsList - Disable the menu button/action bar when a post is being uploaded

### PR DESCRIPTION
**Pull request by geriux**
This PR fixes part of https://github.com/wordpress-mobile/WordPress-iOS/issues/20868 by introducing new UI changes to the Posts list. The issue won't be fully fixed until we apply similar changes to the Pages list, but currently, there are open issues: https://github.com/wordpress-mobile/WordPress-iOS/issues/16370 & https://github.com/wordpress-mobile/WordPress-iOS/issues/15535 that need to be fixed before adding this.

Until now it was possible to encounter a situation where you could edit/duplicate a post when it was being uploaded, this was causing an issue where the editor would crash.

The proposed changes aim to have the same behavior as we currently have on Android. When a post is being uploaded, yo you can't interact with that post until it finishes uploading, by disabling the action bar/menu button.

To test:

## Regression Notes
1. Potential unintended areas of impact
Posts list

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing and unit tests (kudos to @dvdchr for the help with those 🎉 )

3. What automated tests I added (or what prevented me from doing so)
- Updated the `testMenuButtonOpacityAfterConfigure` test
- Added the `testMenuButtonOpacityAfterConfigureWithPushingStatus`

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### Action bar changes

https://github.com/wordpress-mobile/WordPress-iOS/assets/4885740/0cf19e4d-bad3-4a1f-a545-74da02049fa0

### Menu button changes

https://github.com/wordpress-mobile/WordPress-iOS/assets/4885740/a4ac5581-9774-42e6-876b-87a5bb54afe7

### CODE REVIEW

**Comment by geriux** [comment]
Hey there @dvdchr 👋 I was wondering if you could help me out with this PR, I'm introducing a change to disable the action bar/menu button in the Posts list, when a post is being uploaded. This is to avoid opening the editor and encountering a crash, this will make the behavior to be the same as it is on Android.

I've tested this and it works correctly but the unit tests are failing and I'm trying to understand why (my knowledge of native iOS development is very limited still).

For example, for the `testActionBarOpacityAfterConfigure` [test](https://github.com/wordpress-mobile/WordPress-iOS/blob/7fcb4620a204557ac1e250f9c3108bd2284bcebf/WordPress/WordPressTest/PostCardCellGhostableTests.swift#L76), it fails to assert the opacity of the `actionBarView` due to having a value of `0.3` instead of `1`, do you know why with this test, it would go through the logic of the [new added code](https://github.com/wordpress-mobile/WordPress-iOS/pull/20885/files#diff-9ee96eb2778e44a5c8296af9ed6e9c960225bacc274198988cbd68fd20496837R371-R373)? Any help would be appreciated! Thank you!

**Comment by dvdchr** [comment]
@geriux 👋🏼 

> do you know why with this test, it would go through the logic of the [new added code](https://github.com/wordpress-mobile/WordPress-iOS/pull/20885/files#diff-9ee96eb2778e44a5c8296af9ed6e9c960225bacc274198988cbd68fd20496837R371-R373)?

After checking out the code, it looks like the `shouldHideProgressView` depends on the post's `remoteStatus` value:

https://github.com/wordpress-mobile/WordPress-iOS/blob/7fcb4620a204557ac1e250f9c3108bd2284bcebf/WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift#L135-L137

And, since the value of `remoteStatus` is not set in the test case, it defaults to `.pushing`:

https://github.com/wordpress-mobile/WordPress-iOS/blob/7fcb4620a204557ac1e250f9c3108bd2284bcebf/WordPress/Classes/Models/AbstractPost.swift#L17-L25

This explains why the opacity is set to `0.3`.

---

To resolve this, in https://github.com/wordpress-mobile/WordPress-iOS/pull/20885/commits/41ba9f338dfc7160bbf2ec16cac52a1e755376d1 and https://github.com/wordpress-mobile/WordPress-iOS/pull/20885/commits/27ba786cc596689afef4bb597e5b125c34dbf706 I've added the proper `remoteStatus` for the post under test, and also added a test case for when the post is being uploaded. Hope this helps!

**Comment by geriux** [comment]
Hey @dvdchr 👋 thank you so much for the help and for updating the tests! 🙇 It also helped me to understand how they work for future changes so thanks a lot!

This PR is now ready for review so I was wondering if you could take a look, thanks!

**Review by dvdchr — APPROVED** [review]
The changes are looking good, and it works as described. LGTM!

**Pull request merged**
