### PR TITLE
Improved My Site header: Update release notes

### PR DESCRIPTION
**Pull request by momo-ozawa**
Adds release notes for changes made in #22151

### CODE REVIEW

**Comment by momo-ozawa** [comment]
Hi @mokagio 👋 
I'd like to add release notes for a change I made in 23.9. Thanks!

**Comment by mokagio** [comment]
@momo-ozawa 👋 unfortunately, the editorialization request already went in and got merged into `trunk`, see #22218.

If this is super important, we can ask for a new editorialization.

My two cents, and without detracting from the value of the work you and others put into improving the My Site Header, is that it's not worth it. Those release notes will stay in the store for around 14 days and only a fraction of the users will read them.

Let me know.

**Comment by mokagio** [comment]
Regardless of whether we'll send this change for editorialization, we can merge this in now 👍

**Review by mokagio — APPROVED** [review]

**Comment by momo-ozawa** [comment]
Thanks for merging! I agree this is not worth editorializing.

**Pull request merged**
