### PR TITLE
[Notifications] Debounce like inline action

### LINKED ISSUE #22779: Comment likes count becomes inaccurate when the notification like action is tapped in quick succession
### Expected behavior

Tapping the like inline action in quick succession or not should not result in inaccurate likes count.

### Actual behavior

See this message p1709661314601119/1709655110.809149-slack-C06BWNSR02K

### Steps to reproduce the behavior

1. Navigate to Notifications screen
2. Switch to "Comments" tab
3. Navigate to the Comment Details screen by tapping the row. Note down the initial likes count.
4. Go back to Notifications screen
5. Tap the like action twice in quick succession
6. Tap the notification row again
7. Verify if the likes count is accurate or not

##### Tested on iPhone 14 Pro Max, iOS 17 Jetpack iOS / WordPress iOS dd01aca6e0b7729bb792e557fdfa817ef20b7e5f

### PR DESCRIPTION
**Pull request by alpavanoglu**
Fixes #22779

## Description
Debounces the request to avoid sending a new request for multiple back to back like actions.

## Testing Steps
1. Navigate to Notifications screen
2. Tap on a notification that has like inline action. Take note of the like count.
3. Go back to Notifications screen
4. Tap the like action twice in quick succession
5. Tap the notification row again
6. ✅ Verify if the likes count is accurate or not

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by justtwago** [comment]
Thanks for the fix, Alp! 
I'm considering if it's possible to debounce only an API request but not the UI. I assume it would look more natural if we changed the like's state on each tap, but sent an API request and tracked an event after debouncing. What do you think about that?

**Comment by alpavanoglu** [comment]
> I'm considering if it's possible to debounce only an API request but not the UI.

I don't really mind. I think the important thing is that things don't break with user behavior. One cannot tap much faster than the set period anyway. It is easier on simulator since we can click much faster. 

My thought process for the UI bit was to discourage tapping multiple times in succession by discarding the taps UI effect as well as the request. However I don't think in either way, more than a handful of users would notice it. Up to you.

**Review by salimbraksa — APPROVED** [review]
Issue is resolved, and I don't mind debouncing the UI. 👍

**Review by justtwago — APPROVED** [review]
We can leave it as it works now 👍 Eventually, we can improve it if there are such requests from the users.

**Comment by hassaanelgarem** [comment]
@alpavanoglu Why did we target `trunk` and not the release branch, even though this issue was introduced in the current beta?

**Pull request merged**
