### PR TITLE
Update Gutenberg reference to release branch 1.32.0

### PR DESCRIPTION
**Pull request by SergioEstevao**
Update Gutenberg to release 1.32.0

To test:
 - Smoke test the block editor writing flow.
 - Test Copy, Cut, Paste, and Duplicate functionality to blocks
 - Test mentions insertion ( this will be under a feature flag and it's only for internal testing)

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ceyhun** [comment]
**Writing Flow** checklist:

- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
- [x] Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [x] Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
- [x] Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

Tested with build number: 31152 from App Center on a device with iOS 13.5.1
Everything works great 🎉

**Comment by guarani** [comment]
@mchowning @SergioEstevao  There's a bug with Unsupported Blocks. It's not working on Atomic sites and an issue has been filed [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2470) and a PR to fix [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/14446).

**Comment by antonis** [comment]
**Sanity Testing Results**

Tested with build number: 31152 from App Center on a iPhone SE 2020 with iOS 13.5.1

1 issue found
1 test pending

Gallery-2

- [x] Gallery block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

Gallery-4

- [ ] **Gallery block - Settings: Link to - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc012) -> issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2473**
- [x] Gallery block - Settings: Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc013)
- [x] Gallery block - Settings: Crop images - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc014)

Columns - 2
- [x] Columns - Max limit of Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc005)
- [x] Columns - Min limit of Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc006)
- [x] Columns - Removing Column with remove button - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc007)
- [x] Columns - Removing the only one left Column with remove button - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc008)
- [x] Columns - Changing alignment on Columns - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc009)
- [x] Columns - Changing alignment on individual Columnn - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc010)
- [x] Columns - Alignment attribute is properly passed when adding Column - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc011)
- [x] Columns - Deep nesting is possible (iOS only)- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc012)

Columns - 4

- [x] Columns - Check if in DarkMode all components gets proper colors - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc018)

MediaText-3

- [x] Media Text block - Insert video from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-v)
- [x] Media Text block - Close/Re-open post with an ongoing video upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-v)

MediaText-4

- [x] Media Text block - Media & Text alignment - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc006)
- [x] Media Text block - Vertical alignment - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc007)

Shortcode-1

- [x] Shortcode block - Add a youtube link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/shortcode.md#tc001)

Cover-2

- [ ] Cover - Add Video Background from WordPress Media library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc005)
- [x] Cover - Replace media - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc006)
- [x] Cover - Gradient background is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc007)
- [x] Cover - Gradient overlay is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc008)

**Comment by SergioEstevao** [comment]
Testing build using iPhone 11 Pro, iOS 13.5.1

### Unsupported blocks

- [ ] [TC001: New edits are persisted](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/unsupported-block-editing.md#tc001) — note, use [updated](https://github.com/wordpress-mobile/test-cases/pull/42/files) sample content
- [ ] [TC002: Discarded edits are not persisted](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/unsupported-block-editing.md#tc002)
- [ ] [TC003: WP.com Business (Atomic) sites are supported](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/unsupported-block-editing.md#tc003) 
- [] [TC004: Self-hosted sites are supported](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/unsupported-block-editing.md#self-hosted-sites-are-supported)

**Comment by hypest** [comment]
<blockquote>
I tested on:

    WP.com regular site
    WP.com private site
    WP.com Atomic site
    Self-hosted site
    Jetpack connected site
</blockquote>

@SergioEstevao , can you please also test on a selfhosted site with Jetpack installed and connected, but added to the app via username/password? The result should be that the feature is disabled for that too. Thanks!

**Comment by SergioEstevao** [comment]
> @SergioEstevao , can you please also test on a selfhosted site with Jetpack installed and connected, but added to the app via username/password? The result should be that the feature is disabled for that too. Thanks!

Tested and it's working correctly too.

**Comment by guarani** [comment]
Tested build 31353 on an iPhone 7 with iOS 14 beta 1.

### Unsupported blocks

- [x] [TC001: User can edit unsupported blocks on regular WP.com sites](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/unsupported-block-editing.md#tc001)
- [x] [TC002: Ensure discarded edits are not persisted](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/unsupported-block-editing.md#tc002)
- [x] [TC003: User can edit unsupported blocks on regular WP.com Business (Atomic) sites](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/unsupported-block-editing.md#tc003)

**Pull request merged**
