### PR TITLE
Allow changing site in Post editor when current site is hidden

### LINKED ISSUE #5296: Can't change site in Editor if current site is hidden
### Expected behavior
When selecting a different site in the drop down menu, the site you are writing the post for should change.

### Actual behavior
The site does not change.

### Steps to reproduce the behavior
1. Create a new post by tapping "New Post" in the tab bar for a hidden site
2. Tap the drop-down to select another site
3. Notice the site does not change

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #5296 

If the current posting site is hidden, previousIndexPath will be `nil` causing `[self cancelButtonTapped:nil]` to be called. Now we check to make sure preiviousIndexPath is not nil.

To test:
1. Start a post from a hidden site
2. Change site using the site picker on the top left
3. Verify site is changed

Needs review: @diegoreymendez

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@kwonye - I'm not being able to reproduce the case in which `previousIndexPath` is `nil`.  Could you provide me with more details about the testing steps?

For instance: is this what you mean by hidden site?

hiddensite

**Comment by diegoreymendez** [comment]
Just to add more info - I tried to get the error with the old code but couldn't really reproduce the original problem.  I never got `nil` in `previousIndexPath`.

The change is not disruptive, so we could go ahead with it anyways if you're confident this fixes the issue you saw.

**Comment by kwonye** [comment]
> For instance: is this what you mean by hidden site? If so: how are you starting a post from a hidden site? (once hidden I can't go into it... can only start a new post from the tab bar button)

@diegoreymendez yes, that's it. Try hiding a site, opening it from search, and creating a new blog post using the tab bar that way. Sorry for the unclear repro steps.

**Comment by diegoreymendez** [comment]
I couldn't reproduce the original issue, but since the code change is non-diruptive and seems to be working fine... :shipit:

**Comment by kwonye** [comment]
Ok, just so there's proof: https://cloudup.com/ctbg_pTpj54

**Comment by diegoreymendez** [comment]
@kwonye - Still can't reproduce at all.  I've recorded a video so you can see if I'm missing anything.

This was recorded in using the code form `develop`.

Video: https://cloudup.com/cEDWPw471Dk

**Comment by diegoreymendez** [comment]
@kwonye - I could finally reproduce this issue.

However it seems to me like a more appropriate fix would be to show the current blog in the picker, even if it's hidden (simply because it's the blog in which the current post is being written).

A more appropriate fix could be along the lines of:

```
- (NSPredicate *)fetchRequestPredicate
{
    NSManagedObjectContext* context = [[ContextManager sharedInstance] mainContext];
    NSManagedObject* currentBlog = [context objectWithID:self.selectedObjectID];
    
    NSString *predicate = @"(visible = YES OR SELF = %@)";
    if (!self.displaysOnlyDefaultAccountSites) {
        return [NSPredicate predicateWithFormat:predicate, currentBlog];
    }
    
    AccountService *accountService = [[AccountService alloc] initWithManagedObjectContext:context];
    WPAccount *defaultAccount = [accountService defaultWordPressComAccount];
    
    predicate = [predicate stringByAppendingString:@" AND (account == %@ OR jetpackAccount == %@)"];
    return [NSPredicate predicateWithFormat:predicate, currentBlog, defaultAccount, defaultAccount];
}
```

**Comment by kwonye** [comment]
@diegoreymendez good call, I'll change it

**Comment by kwonye** [comment]
@diegoreymendez after investigating, I believe the current change is actually best.

`BlogSelectorViewController` is used multiple places and seems to have a decent amount of state-related properties:

```
@property (nonatomic, assign) BOOL displaysPrimaryBlogOnTop;
@property (nonatomic, assign) BOOL displaysOnlyDefaultAccountSites;
@property (nonatomic, assign) BOOL displaysCancelButton;
@property (nonatomic, assign) BOOL dismissOnCancellation;
@property (nonatomic, assign) BOOL dismissOnCompletion;
```

`displaysOnlyDefaultAccountSites` is especially interesting because I can't still quite figure out why we need that. Changing what blogs are shown may have unintended consequences, especially in other places that are expecting a certain set.

**Comment by kwonye** [comment]
Also, I accidentally merged `develop` into this branch. I was able to revert that commit, but it seems to have caused a mess of commits. If you'd like me to re-create this branch/PR, let me know and I'll be happy to. If not, I'm ready to ship when you are.

**Comment by diegoreymendez** [comment]
If we avoid this fix only because the VC is used elsewhere where it may break, we'd be kind of defeating the purpose of using the same code for both cases - we might as well just have two VCs.

From the user's POV, the moment he's editing the post in a hidden blog, I think it should be shown then the picker is opened.

That said, if we only want a temporary workaround, then this fix is going to work and I'll be glad to approve the PR.  But I'd rather aim for a better fix, and help you test this wherever the VC is used.

Your call... let me know!

**Comment by diegoreymendez** [comment]
Btw... to speed things up since this PR has been open for a while.  If you want to apply a quick fix for the crash, then :shipit:.  I tested the code and its working perfectly.

**Comment by kwonye** [comment]
@diegoreymendez you're right. Updated `fetchRequestPredicate` to search for currentBlog. I've tested and it all seems to work great 👍

**Comment by diegoreymendez** [comment]
Working nicely in all the places where this is used.  Nice work @kwonye! :shipit:

**Pull request merged**
