### PR TITLE
Rich Text: Adds support for horizontal rules.

### LINKED ISSUE #6278: Reader: Add support for horizontal rules in rich text.
Title has it. Currently horizontal rules are removed as they are not well translated into an NSAttributedString, but it might be possible to present a horizontal rule via a custom text attachment.

### PR DESCRIPTION
**Pull request by aerych**
Fixes #6278

To test:
Check a post containing horizontal rules. For example: https://wordpress.com/read/blogs/53424024/posts/20733
Ensure the horizontal rules are displayed.

Needs review: @kurzee would you mind?

### CODE REVIEW

**Comment by aerych** [comment]
> I would say let's use one of the WPStyleGuide light gray colors for the bar, to match the web.
Also, I think a 0.5 pt line height would be preferred for the thinness. Which would also require a check for non-retina screens where we would use a full 1.0 pt instead.

If we want to match we'd want to use greyLighten30, but a 0.5 height rule in that color is nearly invisible.  Maybe keep it at 1.0?

**Comment by kurzee** [comment]
@aerych not sure on which one, maybe a bit darker with the `0.5` to be visible? I'd imagine whichever combination matches the web the closest. Or roll with the matching color at `1.0` and a designer can review later?

**Comment by aerych** [comment]
> I'd imagine whichever combination matches the web the closest

1.0pt and greyLighten30 is the closest match, so let's do that.  A 0.5 and darker grey also looks nice, but the darker colors make the line look too heavy to me.

**Comment by kurzee** [comment]
:shipit: !

**Comment by aerych** [comment]
Thanks @kurzee, but since I made a change for the color would you take one last look for paranoia?

Since we can set the hr color in css, I've opted instead to add a property with the desired default value. I went with this approach so the color would still be configurable should we have another use case for the formatter outside the Reader.

**Comment by kurzee** [comment]
@aerych this looks great! Definitely better with the `1.0`.

:shipit: :shipit: :shipit:

**Comment by aerych** [comment]
Thanks @kurzee !!!

**Pull request merged**
