### PR TITLE
Issue/7371 crash on media picker

### LINKED ISSUE #7371: Crash: MediaPicker 0.16 causes a crash when changing sites, loading Media.
I've finally nailed this down, and likely the primary cause of the crashes in Fabric matching `[WPMediaPickerViewController updateDataWithRemoved:inserted:changed:moved:]` and seen in https://github.com/wordpress-mobile/WordPress-iOS/issues/7278 (thanks @theck13).

1. Uninstall the app from the device (just to ensure the data is cleared)
2. Install, log in to a .com with multiple sites.
3. Open the editor, open media picker, select the Media Library group.
4. Media loads just fine.
5. Close picker, close editor.
6. Change sites to a site known to have Media (and particularly one which you haven't already synced Media items for)
7. Open editor, open media picker, select the Media Library group.
8. Notice there's a strange transition with the loading indicator.
9. Shortly after, crash.

I've pinned this down to something that changed in the MediaPicker pod, version `0.16`, which I base off of not being able to reproduce the crash with `0.15`.

Right now I'm thinking it was this MediaPicker PR: https://github.com/wordpress-mobile/MediaPicker-iOS/pull/172 and later brought into `develop`as `0.16` for our`7.6` release here: https://github.com/wordpress-mobile/WordPress-iOS/pull/7112.

I gave it my best shot to try and bring out a fix, but I'm just not familiar enough with what's going on here. @frosty, @SergioEstevao can you take a look at this? I'd consider this high priority as it would be a breaker for anyone with multiple sites trying to pick media.

@elibud we'd probably need to prepare a hot-fix for `7.8` ^

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #7371 

This PR sorts the crashing issue by two main things:
 - reduce the amount of reload of the data that was being done ( there was some bugs on the navigation picker code that made the data to be reloaded two or three times on load)
 -  and when a group is changed (ex:switch to media library) don't load the data was a set of change but instead do a full reload

To test:
 - Install the app fresh
 - Select a blog
 - Open the media picker by trying to change the site icon or creating a new post
 - Switch to the WordPress Media Library
 - Check that no crash happen
 - Switch to another blog do the same and see if no crash happen
 - Check if picker is still working well when selecting things.

If all goes well I will need to release a new version of the MediaPicker pod and then update the Podfile to a proper version. DO NOT MERGE until I change that.

Needs review: @kurzee and @elibud

### CODE REVIEW

**Comment by kurzee** [comment]
Thanks for looking at this @SergioEstevao.

The good news: the app doesn't crash any more.

The bad news: using the same steps as in the issue creates a very lengthy UI freeze while media is being loaded for the newly changed site, even as long as 30 seconds+ on big sites with lots of media, but it doesn't crash at least.

Is there anything else that recently changed in the picker that is bogging down the loading process in the picker? cc @frosty

**Comment by elibud** [comment]
I could not replicate the crash on develop, which makes me not confident of my testing of this branch. @kurzee can you give me step-by-step for not the brightest to replicate it? Thx

**Comment by kurzee** [comment]
>I could not replicate the crash on develop, which makes me not confident of my testing of this branch. @kurzee can you give me step-by-step for not the brightest to replicate it? Thx

@elibud it should just be the exact steps in the issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/7371, did those not replicate for you on develop?

**Comment by SergioEstevao** [comment]
I think the freeze was always there, when loading a big library for he first time you need to do multiple requests to get all the media this can take some time. The app isn't frozen you can cancel or switch to other collection right?

Enviado do meu iPhone

No dia 15 de jun de 2017, às 00:54, Brent Coursey <notifications@github.com> escreveu:

**Comment by kurzee** [comment]
>I think the freeze was always there, when loading a big library for he first time you need to do multiple requests to get all the media this can take some time. The app isn't frozen you can cancel or switch to other collection right?

For a decent bit, depending on the library, the cancel button cannot be selected, but it will carry on the touch event once it unblocks the thread. That could indeed have been there before though, so perhaps unrelated here. 🤔

**Comment by elibud** [comment]
@kurzee nope, I couldn't get it to crash on develop or on 7.8. Which is odd since I've seen the crash working with the site icon. Ping me when you are available and we can screen share or sth.

**Pull request merged**
