### PR TITLE
Merges release/15.7 into develop

### PR DESCRIPTION
**Pull request by diegoreymendez**
Merges back the `release/15.7` changes into `develop`.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Please ignore this PR momentarily.  I'm fixing some issues in it.

**Comment by diegoreymendez** [comment]
@frosty , @leandroalonso , @emilylaguna - Can I ask you to validate your changes are fine with a review approval?  Thanks

**Review by emilylaguna — APPROVED** [review]
Verified my changes are working after the merge.

**Review by leandroalonso — APPROVED** [review]

**Review by frosty — APPROVED** [review]
I can confirm my changes look fine!

**Comment by diegoreymendez** [comment]
Thanks folks!

**Pull request merged**
