### PR TITLE
Update synced media references when saving a post with ongoing uploads

### LINKED ISSUE #33593: Gallery block: Some images point to local URLs when closing the post with ongoing uploads
## Description

Some images point to local URLs (example: `//private/var/mobile/Containers/Data/Application/...`) when closing the post with ongoing uploads and re-opening when they're finished.

## Step-by-step reproduction instructions

This can be reproduced by following the ["Close post with an ongoing image upload" test case](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc002):

- Add a gallery block and tap "Add Media"
- Select "Choose from device" option
- Select multiple images from the device and confirm the selection
- While image are uploading, leave the editor
- Wait for uploads to complete while in the post list
- Re-open the post with the gallery block

## Expected behaviour

The images' URL scheme should be `https://`.

## Actual behaviour

The images' URL scheme is `///`.

## Screenshots or screen recording (optional)

Uploading images|Last frame before closing the post|Re-open post|HTML mode
--|--|--|--
uploading|last-frame|enter-post|html-mode

**NOTE:** This issue might be related to closing the post when the image is already uploaded but not loaded in the editor, as you can see in the screenshots, the first four items are showing a placeholder image right before the post is closed, and coincidentally these items are the ones that point to local URLs.

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 11
- Operating system: iOS 14.2
- WordPress app version: `develop`

### PR DESCRIPTION
**Pull request by fluiddot**
Fixes https://github.com/WordPress/gutenberg/issues/33593

**To test:**
1. Create a post.
1. Add a gallery block and tap "Add Media".
1. Select "Choose from device" option.
1. Select multiple images from the device and confirm the selection.
1. While images are uploading, leave the editor.
1. Wait for uploads to complete while in the post list.
1. Re-open the post with the gallery block.
1. Tap on the post settings button (three dots button located at the top).
1. Tap on "Switch to HTML mode"
1. Observe that the `src` attributes of all `img` tags reference a remote URL and not a local version.
    - Remote URLs start with `https://`
    - Local URLs start with `///`

## Regression Notes
1. Potential unintended areas of impact
The fix is specific to the post save process when there are uploads in progress, so apart from this area, I don't expect other unintended areas of impact.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I tested in the following scenarios for this area:
- Save a post with completed and pending media uploads
- Save a post with only pending media uploads
- Save a post with no media uploads

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing 18.4 today and this hasn't been approved yet.

If this cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.

**Comment by fluiddot** [comment]
> I'm going to bump this to the next release because we'll be code freezing 18.4 today and this hasn't been approved yet.
> 
> If this cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.

Thanks @mokagio for bumping it to the next release 🙇 , this fix is not critical so it can wait to the next version.

**Review by ceyhun — APPROVED** [review]
I was able to reproduce the issue consistently following the instructions in https://github.com/WordPress/gutenberg/issues/33593#issuecomment-921666593 and verified the fix and it LGTM 👍 We only need to update the release notes to be in the correct version.

**Comment by fluiddot** [comment]
> I was able to reproduce the issue consistently following the instructions in [WordPress/gutenberg#33593 (comment)](https://github.com/WordPress/gutenberg/issues/33593#issuecomment-921666593) and verified the fix and it LGTM 👍 We only need to update the release notes to be in the correct version.

Thanks @ceyhun for the review ❤️! I've just updated the release notes in [this commit](https://github.com/wordpress-mobile/WordPress-iOS/pull/17157/commits/6c506c82fd2c0fdd018c8481e58da89f4fa80577), once the CI checks pass I'll merge it.

**Pull request merged**
