### PR TITLE
Enabling Unsupported Block Editor for Jetpack sites with SSO enabled.

### PR DESCRIPTION
**Pull request by etoledom**
Fixes part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/2471

Gutenberg Mobile PR: http://github.com/wordpress-mobile/gutenberg-mobile/pull/2542
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/24476

This PR enables Unsupported Block Editor for self-hosted sites connected via Jetpack to WordPress.com.

SSO can also be disabled for Atomic sites, but in this case it is opt-out option, so with this PR we are also disabling Unsupported Block Editor for Atomic sites with SSO disabled.

This is an intermediate step to finally enable Unsupported Block Editor to all Jetpack and Atomic site, via letting the user activate SSO before editing the unsupported block.

### To test:

**Jetpack-connected self-hosted sites:**
- Create a [JN](https://jurassic.ninja) instance of WordPress.
- In that self-hosted site, create a post with a block not yet supported on mobile.
- Connect the self-hosted site to your WP.com account via Jetpack.
- Login to your WP.com account on the WPiOS mobile app.
- Select the newly created Jetpack site on the site list.
- Go to Posts and open the newly created post.
- On the unsupported block, press `(?)` button (top right).
  - Check that there's no option to open Unsupported Block Editor.
- Go back to Site Settings -> [Jetpack] Security -> Allow WordPress.com Login 
  - Enable said option ✅ 
- Go back to the post with the unsupported block.
- On the unsupported block, press `(?)` button (top right).
  - Check that the option `Edit block in web browser` is there.
- Press said option.
- The web view will load with an option to login with WordPress.com (Image bellow).
- Press on `Login with WordPress.com`.
  - Check that Gutenberg loads as expected on the Web View displaying the block to edit.
- 🎉 

**Atomic sites:**
- Have a testing Atomic site on a WordPress.com account.
- On web, create a post with a block not yet supported on mobile.
- Login to your WP.com account on the WPiOS mobile app.
- Select the Atomic site on the site list.
- Go to Posts and open the newly created post.
- On the unsupported block, press `(?)` button (top right).
  - Check that the option `Edit block in web browser` is there.
- Press said option.
  - Check that Gutenberg loads as expected on the Web View displaying the block to edit.
- Go back to Site Settings -> [Jetpack] Security -> Allow WordPress.com Login.
  - Disable said option ❎
- Go back to the post with the unsupported block.
- On the unsupported block, press `(?)` button (top right).
  - Check that there's no option to open Unsupported Block Editor.
- 🎉 

### Login with WordPress.com screen:

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by etoledom** [comment]
cc @marecar3 @hypest

**Review by guarani — COMMENTED** [review]
@etoledom I was not able to get this to work unfortunately. 

### Self-hosted, Jetpack-connected site with SSO enabled

On a self-hosted site with Jetpack enabled, I turned SSO on:

<details>
<summary>See screenshot</summary>
Screen Shot 2020-08-04 at 12 12 32

</details>

but the option to edit an unsupported block was missing. Debugging this shows that `blog.settings?.jetpackSSOEnabled` is `false` when it should be `true`. I'm not sure if I'm missing something obvious here.

### Atomic site with SSO enabled

I had similar results here — despite the same SSO setting I mentioned earlier being enabled, I don't see the option to edit an unsupported block. Again `blog.settings?.jetpackSSOEnabled` when I expected it to be `true`.

**Comment by etoledom** [comment]
Thanks for testing @Guarani !

My tests were enabling SSO in the same Mobile app. Thanks for also testing the flow enabling it from web!
I'll be checking this out to see what the problem is.

**Comment by guarani** [comment]
> My tests were enabling SSO in the same Mobile app. Thanks for also testing the flow enabling it from web!
I'll be checking this out to see what the problem is.

I wasn't aware of that option in the mobile app. It's great how each one of us tests slightly differently which allows us to cover more ground 🙌.

**Comment by jkmassel** [comment]
Today is the `15.5` code freeze, so I've bumped this to `15.6`. If it needs to be shipped as part of `15.5`, please merge it to the `release/15.5` branch, then DM me – I'll be happy to cut a new beta release.

**Comment by loremattei** [comment]
Hey there! I'm moving this to 15.8 because 15.7 has been cut. If you want this to make it to 15.7, please, feel free to ping me.

**Comment by etoledom** [comment]
> @etoledom I was not able to get this to work unfortunately.
> 
> ### Self-hosted, Jetpack-connected site with SSO enabled
> On a self-hosted site with Jetpack enabled, I turned SSO on:
>
> but the option to edit an unsupported block was missing. Debugging this shows that `blog.settings?.jetpackSSOEnabled` is `false` when it should be `true`. I'm not sure if I'm missing something obvious here.
> 
> ### Atomic site with SSO enabled
> I had similar results here — despite the same SSO setting I mentioned earlier being enabled, I don't see the option to edit an unsupported block. Again `blog.settings?.jetpackSSOEnabled` when I expected it to be `true`.

@guarani - this issue with refreshing the local sso status after opening the editor has been fixed 🎉 

Now you should be able to change the setting on web, open the editor, and see the correct behaviour on the unsupported block.

Would you mind taking another look at this PR? Thank you! 🙏

**Review by guarani — APPROVED** [review]
Hey @etoledom I tested both the self-hosted and the Atomic and things are working for me 👍

**Pull request merged**
