### PR TITLE
[Site Picker] Add tracks and update icons

### PR DESCRIPTION
**Pull request by alpavanoglu**
Refs: https://github.com/wordpress-mobile/WordPress-iOS/pull/22833/

## Description
Updates tracks and icons used in the redesigned site picker.

## Video Reference

https://github.com/wordpress-mobile/WordPress-iOS/assets/15968946/1f0b824a-ddf6-44f6-844f-8712a4c2ded4

### Placeholder icon
1. Open Site Picker
2. Find a site with no image (if none exists, add one from the CTA below)
3. ✅ Verify that the placeholder is the newly added vector image (also seen in the video)
4. Regression: Go to Notifications and find an avatar without image. ✅ verify that an avatar (person shape) placeholder appears instead.

### Track `site_switcher_toggled_pin_tapped`
1. Interact with the Edit/Done button
2. ✅ Verify `Tracked: site_switcher_toggled_pin_tapped <state: edit>` with the correct state fires.

### Track `site_switcher_pin_updated`
1. Tap on Edit, pin and unpin sites
2. ✅ Verify `Tracked: site_switcher_pin_updated <blog_id: 231823006, pinned: 0>` with the correct boolean fires.

### Track `site_switcher_site_tapped`
1. Select a site
2. ✅ Verify `Tracked: site_switcher_site_tapped <section: pinned>` with the correct section name fires.

### Regression for Legacy Screen
1. Go to "Me"
2. Tap on "All Domains"
3. Tap on ➕ 
4. Search for any domain
5. Select one and press "Select domain"
6. Tap on "Choose Site"
7. ✅ Verify the old site picker appears. (We can replace this with the new class, once we are confident with the redesign along with removing the legacy code)

## Regression Notes
1. Potential unintended areas of impact
N/A

8. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

9. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by momo-ozawa** [comment]
👋 I'm bumping this PR to 24.8 since it's code freeze day. If this PR needs to target 24.7, please target the release branch once it's been cut. Thanks!

**Comment by justtwago** [comment]
Tested it on my iPhone 15 Pro Max (iOS 17.4.1) and I see no custom placeholders for my sites with no icons:



___________

Apart from that, all the analytics events work as described, and the legacy site picker looks as usual.

**Comment by alpavanoglu** [comment]
@justtwago 
> Tested it on my iPhone 15 Pro Max (iOS 17.4.1) and I see no custom placeholders for my sites with no icons:

For some reason git ignores the changes on DesignSystem color asset catalog. I removed and re-added it to fix the name. I assume that's why it worked locally but not on remote. Not it should be fine.

**Comment by alpavanoglu** [comment]
I am merging this to the parent PR to get the tests running there. Please test for the icon fix on the main PR @justtwago

**Pull request merged**
