### PR TITLE
Fix unit tests in Xcode 9

### PR DESCRIPTION
**Pull request by koke**
Replace OCMock on managed objects with the TestContextManager. Refactored some remotes so they take site IDs instead of Blog objects. Added ModelTestHelper to ensure test Blog/WPAccount objects have all the required properties filled.

See #7343 

To test:

- Make sure tests pass in Xcode 8
- Make sure tests pass in Xcode 9

Needs review: @astralbodies

### CODE REVIEW

**Comment by astralbodies** [comment]
I think your PR is going to get whacked in the head by @bummytime's #7406.

**Comment by koke** [comment]
Yep, there will be conflicts but they'll be easy to solve by overriding my changes with @bummytime's (we kind of both fixed the same problem with different solutions)

**Comment by bummytime** [comment]
I went ahead and merged my changes into `develop` @koke. Let me know if you want help resolving anything.

**Comment by koke** [comment]
@astralbodies conflicts solved

**Comment by astralbodies** [comment]
For some reason I'm having problems compiling 😢

**Pull request merged**
