### PR TITLE
Update internal and external app launcher icons.

### PR DESCRIPTION
**Pull request by jasmussen**
These new icons are based on design group discussions to standardize on branding, colors and icon design. It uses the "Medium Blue" brand color. The internal icon has also been changed, to just show a little "beta" glyph.

Don't merge this in right away. Although the design group has approved mockups, I'd love for them to have a final say while visually comparing the github before and after view!

### CODE REVIEW

**Comment by folletto** [comment]
Looks great to me. :+1: 

The only note is probably about the internal icon, which currently it's overlaid with the version number, so probably we should move the ß symbol top-right?

Reference:

screen shot 2015-02-12 at 11 03 35

**Comment by jasmussen** [comment]
> The only note is probably about the internal icon, which currently it's overlaid with the version number, so probably we should move the ß symbol top-right?

That's a good point. In fact, maybe we shouldn't even have a beta symbol at all, since the overlay makes it quite obvious you're running a beta version. No reason to maintain two iconsets :)

**Comment by folletto** [comment]
I guess might still be useful if we discontinue the versioning at some point, but regardless, you're right. Not needed right now. :)

**Comment by diegoreymendez** [comment]
Just adding a note here about our chat with @jasmussen in Slack, for historic ref.

Filenames for images in iOS have a standard they follow, where @2x, and @3x are suffixed to resolution-specific images (which offer some cool features on the programming side of things).

Thanks for the good work @jasmussen!

**Comment by jasmussen** [comment]
Updated filenames to use @-syntax per @diegoreymendez advice. 

Additionally, I retired the "internal" icon entirely, per @folletto's idea. This will allow us to actually test how the new icon looks in the beta release, before actually submitting it to the app store.

**Comment by diegoreymendez** [comment]
Looks great! Feel free to :shipit:

**Comment by drw158** [comment]
Looks great Joen. I like the idea of not using a different icon for the beta builds.

**Comment by jasmussen** [comment]
Alright, I'm taking that as a signoff. Merging in!

**Pull request merged**
