### PR TITLE
Fixes issues for multiple blog user who is creating a new post

### PR DESCRIPTION
**Pull request by bummytime**
Fixes https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/164

This PR does two things. First it creates a "read-only" mode for the ```WPBlogSelectorButton```. Secondly the blog picker should now always be visible on the editor no matter how you navigate to it. It will be in read-only mode for the following situations:

* Editor screen is in preview mode
* The user only has a single blog
* The user is editing an existing post

In all other situations, the picker will allow the user to change the current blog they are posting to (which really is just new posts/pages).

/cc @diegoreymendez

### CODE REVIEW

**Comment by aerych** [comment]
Yay :)

**Comment by bummytime** [comment]
@aerych Could you do me a HUGE favor? Since Diego is on vacation could you review this PR for me?

**Comment by aerych** [comment]
Looking :)

**Comment by aerych** [comment]
@bummytime Code looks good and the button looks good.  I did encounter something that seemed strange.   Try this:

- Be signed in to an account with multiple sites.
- Pick a site (any site) and tap to view its details. 
- Tap the New Post button on the tab bar.  
- Note that the editor is pointing to the same site you chose. 
- Dismiss the editor.
- Tap Blog Posts. 
- Tap the New Post button on the tab bar and note its still pointing at your blog. 
- Dismiss the editor. 
- Tap the + button in the top corner. 
- The editor opens targeted at your chosen site. 

All of this is as expected. Now for the strange:

- In the open editor, change the target site. 
- Dismiss the editor. 
- Tap the + button in the top corner.  Note the editor opens pointing at the site to which you've navigated.
- Dismiss the editor. 
- Tap the New Post button in the tab bar. 
- This editor is targeting the blog you selected from the drop down. (Wait what?)

It was strange that being navigated into a site I could open an editor that was targeting a different site.  This maybe makes sense when I'm viewing a different tab, but when I'm on the my sites tab my expectation was the editor would always default to the site I'm interacting with.  

Getting different results depending on how the editor is launched is probably going to confuse others.

I'm not sure if its an issue to address in this PR since the changes don't seem to be related to it. I think its more likely something that crept up in the masterbar changes (current app store version doesn't have this behavior as far as I can tell) and the changes in this PR have shown a spotlight on a previously invisible bug.

If you agree the behavior is undesired I'm fine opening an issue for it vs patching here.   

On all other fronts things look good so I say :shipit:

**Comment by bummytime** [comment]
Very nice catch @aerych. I am logging the issue you mentioned here: https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/513

**Pull request merged**
