### PR TITLE
Update fastlane and release-toolkit

### PR DESCRIPTION
**Pull request by loremattei**
GitHub claims a `potential security vulnerability` warning on the repository due to `nokogiri`.
This PR updates `release-toolkit` to the latest version in order to use a newer version of `nokogiri`. The PR also updates `fastlane` to the latest.

# To test:

- Check that CI is green.
- Check that bundle install succeeds locally.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
👋 We're freezing WPiOS `16.5` today, so this PR is being bumped to `16.6`. 

If you need it to be part of the `16.5` release, please DM me – I'll be happy to cut a new beta release once this lands!

**Review by mokagio — APPROVED** [review]

**Comment by fluiddot** [comment]
👋 I've just pulled these changes from `develop` branch and I spotted that running `rake dependencies` modifies the `Podfile.lock` file, specifically it changes:
`COCOAPODS: 1.10.0` => `COCOAPODS: 1.10.1`

I think that as the `cocoapods` gem has been [updated](https://github.com/wordpress-mobile/WordPress-iOS/pull/15621/files#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fL55) we'll also need to update that file.

**Comment by fluiddot** [comment]
> 👋 I've just pulled these changes from `develop` branch and I spotted that running `rake dependencies` modifies the `Podfile.lock` file, specifically it changes:
> `COCOAPODS: 1.10.0` => `COCOAPODS: 1.10.1`
> 
> I think that as the `cocoapods` gem has been [updated](https://github.com/wordpress-mobile/WordPress-iOS/pull/15621/files#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fL55) we'll also need to update that file.

Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/15635.

**Comment by loremattei** [comment]
Good catch @fluiddot! Thanks for the fix!

**Comment by mokagio** [comment]
Thanks @fluiddot 🙏 👏

**Pull request merged**
