### PR TITLE
[Site Creation] Add "Create Site" button to Domain screen

### LINKED ISSUE #10922: [Site creation] Missing "Create Site" button in Domains Screen
There should be a "Create site" button shown in Domains similar to the Basic Information screen.

Actual:
simulator screen shot - iphone xr - 2019-01-30 at 16 55 17

Expected:
screenshot 2019-01-30 at 4 54 06 pm

### PR DESCRIPTION
**Pull request by ctarda**
Fixes #10922 

iPhone X:
screen recording 2019-01-31 at 11 47 10 pm mov

iPhone SE: 
screen recording 2019-01-31 at 11 44 17 pm mov

iPad Pro 11:
simulator screen shot - ipad pro 11-inch - 2019-01-31 at 23 58 03

To test:
- Checkout the branch, run the tests
- Launch the Enhanced Site Creation flow, navigate to the Domains step, and select a domain. The Create Site button should then be visible, and wizard should not progress until the "Create Site" button is tapped.

### CODE REVIEW

**Comment by stevebaranski** [comment]
I took the branch for a spin - it builds & tests pass. All of the scenarios you highlighted in screenshots work okay. 

I wanted to call out a couple of issues I'm seeing with this behavior on the iPad in Landscape orientation. 

When the keyboard is hidden, life is good.
10933_ipad-landscape_nokeyboard

When the keyboard is not hidden, the manner in with the _Create Site_ button was created occludes the content of the table view, resulting in an experience like the following:

10933_ipad-landscape_keyboard-a
10933_ipad-landscape_keyboard-b

This resembles what's shown in the iPhone SE GIF above. It seems like this might be avoided if the button was added to the footer of the table view instead of a footer view as shown.

The approach used in this PR is the same as the one used for Verticals in #10917. Unfortunately, however, the experience on those screens is different. For Verticals, the appearance of the _Skip_ button is mutually exclusive from the table view content. In this case, they both need to appear.

I think this is worth fixing prior to shipping, but will if @kwonye disagrees, perhaps he can approve and create a new issue to resolve this separately.

**Comment by stevebaranski** [comment]
Another option that might be warrant consideration - what if we just replaced the button at the bottom of the table with a bar button item on the right side of the navigation bar? We could enable / disable it based on whether or not a domain had been selected.

**Comment by ctarda** [comment]
Thanks @stevebaranski I have just pushed a commit that, as discussed, hides the keyboard and presents the "Create Site" button when users select a domain from the list of results.

**Comment by SylvesterWilmott** [comment]
@ctarda Did we keep everything else the same. So if for example I press the field again to show the keyboard does the button still appear above the keyboard?

**Comment by SylvesterWilmott** [comment]
Thanks @ctarda this looks great!

**Comment by stevebaranski** [comment]
The _Create Site_ button is behaving well for me!

I see a couple of issues that are best explained with a couple of screenshots of the iPad experience:

_iPad : Row Selected_
10933a

_iPad : Row Unselected_
10933b

There are three items worth noting:

1. It is not currently possible to tap a row to deselect it (i.e., hide the checkmark). A user must clear the search criterion or select another row. If that's the desired UX, then I think we're good to proceed.
1. In the selected state, the spacing between the magnifying glass and the input text decreases from the unselected state. I don't think it's new in this PR, but probably warrants a separate ticket to resolve that visual defect in `TitleSubtitleTextfieldHeader`.
1. It appears that the input text is now bold. I'm afraid this was introduced via #10934. We should probably tidy that up.

**Comment by kwonye** [comment]
> 1. It is not currently possible to tap a row to deselect it (i.e., hide the checkmark). A user must clear the search criterion or select another row. If that's the desired UX, then I think we're good to proceed.

I believe that's ok. Android also cannot deselect. Let's proceed with this functionality and if we get complaints or a drop off in signups we can tweak it.

> 2. In the selected state, the spacing between the magnifying glass and the input text decreases from the unselected state. I don't think it's new in this PR, but probably warrants a separate ticket to resolve that visual defect in TitleSubtitleTextfieldHeader.

https://github.com/wordpress-mobile/WordPress-iOS/issues/10943

> 3. It appears that the input text is now bold. I'm afraid this was introduced via #10934. We should probably tidy that up.

https://github.com/wordpress-mobile/WordPress-iOS/issues/10942

Thanks, @stevebaranski! I'll tackle 2 and 3 in separate issues like you suggested. Barring anything else I believe this is good to go!

**Pull request merged**
