### PR TITLE
Additional tracking for Google Sign In.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/14592
WPAuth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/367

Additional tracking for Google Sign In, and some enhancements to make the new analytics tracker easier to use in client Apps.

## Changes:

1. Tracks `createAccount` and `addSelfHostedSite`.
2. Trackes `editUsername`.
2. Tracks `continue` at the epilogue.

**Not** included in this PR:

1. Tracking the prologue has been shown.
2. Tracking `dismiss` (when pressing back in VCs).
3. Tracking `select_avatar`.
4. Tracking `submit`

#### Preconditions:

- Disable `unifiedGoogle`.

#### Steps:

Go around Signup / Login.  Execute any flow.

#### Expectations:

Make sure you don't see any of these events tracked:

- `unified_login_step`
- `unified_login_interaction`
- `unified_login_failure`

#### Preconditions:

- Enable `unifiedGoogle`.
- User a Google account that's already connected.

#### Steps & Partial Expectations:

1. Tap Log In.
2. Tap Login with Google

🔵 Tracked: unified_login_interaction <click: login_with_google, flow: wordpress_com, source: default, step: prologue>
🔵 Tracked: unified_login_step <flow: google_login, source: default, step: start>

3. Complete login with the google account

🔵 Tracked: unified_login_step <flow: google_login, source: default, step: success>

### Test 3: Login with Connected Google Account with 2FA

For all upcoming tests we'll only verify new expectations, and not the ones that are already covered.

#### Preconditions:

- Enable `unifiedGoogle`
- User a Google account that's already connected 
- Make sure the WP account has 2FA enabled
- Make sure your WP app is NOT a fresh install.

#### Steps & Partial Expectations:

1. Log in with Google, select your account and complete the Google part of logging in.
2. Once the two factor code is requested check the console for the following:

🔵 Tracked: unified_login_step <flow: google_login, source: default, step: 2fa>

3. Tap "Text me a code instead"

🔵 Tracked: unified_login_interaction <click: send_code_with_text, flow: google_login, source: default, step: 2fa>

4. Enter a bad code and tap continue

🔵 Tracked: unified_login_interaction <click: submit_2fa_code, flow: google_login, source: default, step: 2fa>
🔵 Tracked: login_failed_to_login <error_code: 7, error_description: Error Domain=WordPressComOAuthError Code=7 "Hmm, that's not a valid verification code. Please double-check your app and try again."

5. Enter the correct SMS code and tap continue

🔵 Tracked: unified_login_interaction <click: submit_2fa_code, flow: google_login, source: default, step: 2fa>
🔵 Tracked: unified_login_step <flow: google_login, source: default, step: success>

6. In the epilogue screen tap "Done".

🔵 Tracked: unified_login_interaction <click: continue, flow: google_login, source: default, step: success>

#### Preconditions:

- Enable `unifiedGoogle`.
- Use a Google account that's NOT connected to your WP account but has the same email
- Make sure the WP account has a password set and 2FA disabled

#### Steps & Partial Expectations:

1. Log in with Google, select your account and complete the Google part of logging in.
2. Once the password is requested make sure you can see this in the tracking:

🔵 Tracked: unified_login_step <flow: google_login, source: default, step: username_password>

3. Fill in a bad password and tap Continue

There's some extra old error tracking here which I'll have to work on separately (`login_failed_to_login`).

🔵 Tracked: unified_login_failure <failure: It seems like you've entered an incorrect password. Want to give it another try?, flow: google_login, source: default, step: username_password>

4. Tap Help.

🔵 Tracked: unified_login_interaction <click: show_help, flow: google_login, source: default, step: username_password>

5. Close help.
6. Tap reset your password.

🔵 Tracked: unified_login_interaction <click: forgotten_password, flow: google_login, source: default, step: username_password>

7. Go back to the app without reseting the password.
8. Enter the correct password and press continue.

🔵 Tracked: unified_login_step <flow: google_login, source: default, step: success>

#### Preconditions:

- Enable `unifiedGoogle`.
- Use a Google account that's NOT connected to your WP account but has the same email
- Make sure the WP account has a password set and 2FA enabled

#### Steps & Partial Expectations:

1. Tap "Signup for WordPress.com"
2. Tap "Continue with Google"

🔵 Tracked: unified_login_interaction <click: signup_with_google, flow: google_signup, source: default, step: prologue>
🔵 Tracked: unified_login_step <flow: google_login, source: default, step: start>

3. Login to your Google account.
4. When the password screen is visible check:

🔵 Tracked: unified_login_step <flow: google_login, source: default, step: username_password>

5. Enter the WP password when requested and tap continue.
6. The 2FA screen should come up.

🔵 Tracked: unified_login_step <flow: google_login, source: default, step: 2fa>

7. Enter a correct code and tap "Continue"

🔵 Tracked: unified_login_interaction <click: submit_2fa_code, flow: google_login, source: default, step: 2fa>
🔵 Tracked: unified_login_step <flow: google_login, source: default, step: success>

#### Preconditions:

- Enable `unifiedGoogle`.
- Use a Google account that's NOT connected to any WP account
- Make sure there's no existing WP account with the same email address

#### Steps & Partial Expectations:

1. Tap "Signup for WordPress.com"
2. Tap "Continue with Google"
3. Log into your Google account.
4. A screen should come up telling you that your email will be used for creating your new WordPress.com account.

🔵 Tracked: unified_login_failure <failure: The Google account "youremail@host.com" doesn't match any account on WordPress.com, flow: google_login, source: default, step: start>

5. Tap "Next"

🔵 Tracked: unified_login_interaction <click: submit, flow: google_login, source: default, step: start>
🔵 Tracked: unified_login_interaction <click: create_account, flow: google_login, source: default, step: start>
🔵 Tracked: unified_login_step <flow: google_signup, source: default, step: start>
🔵 Tracked: unified_login_step <flow: google_signup, source: default, step: success>

6. Tap on the username field

🔵 Tracked: unified_login_interaction <click: edit_username, flow: google_signup, source: default, step: success>

7. Tap "Back"
8. Tap "Done"

🔵 Tracked: unified_login_interaction <click: continue, flow: google_signup, source: default, step: success>

## PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Hey @mindgraffiti , @ScoutHarris.  I'm temporarily removing this from review to add more successful test cases for the remaining Sign In flows.

**Comment by diegoreymendez** [comment]
Signup tracking should be working now.  This is ready for review again.

**Comment by diegoreymendez** [comment]
Just for context on the discussion, those events coming up are ok, but I've rewritten the expectations for the first step to be clearer.

**Comment by diegoreymendez** [comment]
> The instructions assume that I knew I needed at least 1 active site to complete the steps

They don't.  You shouldn't need an active site in this test, as we discussed privately.

That last event is failing for me too though, so I'll review the test.

**Comment by diegoreymendez** [comment]
I removed the last check from test 2.  I'll be adding support for that event once I deal with the dismissal of all login VCs.

**Comment by mindgraffiti** [comment]
Thanks for the clarification on Test 2 @diegoreymendez! I think I found a bug involving the Post-Site Interstitial, which explains why I couldn't get the epilogue to appear for testing.

**Comment by mindgraffiti** [comment]
Going to add comments for each test.

✖️ Test 3. I didn't receive the last event after tapping the "Done" button. 
(🔵 Tracked: unified_login_interaction <click: continue, flow: google_login, source: default, step: success>)

These are the last events that show up in the console:

🔵 Tracked: unified_login_interaction <click: submit_2fa_code, flow: google_login, source: default, step: 2fa>
🔵 Tracked: unified_login_step <flow: google_login, source: default, step: success>
🔵 Tracked: widget_active_site_changed <>
🔵 Tracked: signed_in <dotcom_user: true, multifactor: true>
🔵 Tracked: login_epilogue_viewed <>

**Comment by diegoreymendez** [comment]
> I didn't receive the last event after tapping the "Done" button.

Strangely enough I'm getting it - I imagine this may be the same difference we saw in test 2.

Is there a chance you're getting the other epilogue in this test too?

**Pull request merged**
