### PR TITLE
Resolved Alpha & Internal signing issues for notification extensions

### PR DESCRIPTION
**Pull request by stevebaranski**
## Description
Corrected a couple of issues identified with builds of the app with the notification content & service extensions.

## To test
- Branch should build and existing tests should pass.
- It should also now be possible to build the `WordPress`, `WordPress Alpha` & `WordPress Internal` targets without issue. Notably, Building the `WordPress Alpha` scheme now uses the `Debug` _Build Configuration_ rather than the `Release-Alpha` configuration.

### CODE REVIEW

**Comment by loremattei** [comment]
Thank you very much for taking care of this @stevebaranski!

I tested it and I can build `WordPress`, `WordPress Alpha` & `WordPress Internal` with no issue! 👍
Tough `Archive` only works for `WordPress` and `WordPress Internal`. It seems that the `Release-Alpha` configuration is broken, could you please look into it?

Also, it looks like the fix is all about changing the provisioning profile id. Can I ask why we're adding the other changes?

**Comment by stevebaranski** [comment]
> It seems that the `Release-Alpha` configuration is broken, could you please look into it?

I'm happy to investigate this. Out of curiosity, what error are you encountering?

> Also, it looks like the fix is all about changing the provisioning profile id. Can I ask why we're adding the other changes?

There are three files changed. I'll discuss each in turn:

1. `Podfile.lock` : Nothing explicit changed here; it was updated when running `pod install`.
1. As I investigated the issue, I noticed some redundant Build Settings. When viewed in Xcode for a particular target, these typically appear in bold. I deleted some of these that were muddling the picture a bit, and verified that the non-bold value that remained was the same as before. Please let me know if you like to review screenshots of these.
1. I noted that the `WordPress Alpha` scheme was configured to Run (via Cmd-R) with the `Release-Alpha` Build Configuration, rather than `Debug`. This differs from the other WP schemes in the target and from Xcode default. I simply took the liberty to tidy up this default value.

**Comment by loremattei** [comment]
Thank you @stevebaranski !

> Out of curiosity, what error are you encountering?

I get this error with `Archive`:

`couldn't parse contents of '/Users/lore/Sources/wordpress-mobile/WordPress-iOS/WordPress/WordPressDraftActionExtension/Info-Alpha.plist': The data couldn’t be read because it isn’t in the correct format.`

>2. As I investigated the issue, I noticed some redundant Build Settings. When viewed in Xcode for a particular target, these typically appear in bold. I deleted some of these that were muddling the picture a bit, and verified that the non-bold value that remained was the same as before. Please let me know if you like to review screenshots of these.

Ah! I got it now! Sorry for the very stupid question! 
Looking at the changes here in GH, I was wondering why some configurations that looked good were delete 😬 I didn't think about the easiest answer!

**Comment by stevebaranski** [comment]
@loremattei thanks for the additional detail. I haven't made any changes to `WordPressDraftActionExtension`, but I'll have a look and get back to you.

**Pull request merged**
