### PR TITLE
Stats Period Details: Optimize table view updates by integrating diffable data source

### LINKED ISSUE #22720: Stats Details: Optimize table view updates by integrating diffable data source
Optimize table view updates by integrating a diffable data source into Stats Details views:
- Insights -> Details
- Traffic -> Details

Use the example and mechanisms of past implementations:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/22542
- https://github.com/wordpress-mobile/WordPress-iOS/pull/22592

### PR DESCRIPTION
**Pull request by staskus**
Fixes #22720
Related PRs:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/22542
- https://github.com/wordpress-mobile/WordPress-iOS/pull/22592

### Description

Introduce diffable data source into Stats Details (Traffic -> Details, Days/../Years -> Details) views. I only found 2 ViewControllers used for Stats Details:
- `PostStatsTableViewController` to show Stats for a Post
- `SiteStatsDetailTableViewController` for all the other Details views

### Solution

1. Change `ImmuTableViewHandler` to `ImmuTableDiffableViewHandler`
2. Call `diffableDataSource.apply` instead of setting `tableViewModel`
3. Build `tableViewSnapshot` instead of `tableViewModel`
4. Make required models `Hashable`
5. Added helper methods to handle a common case of building a single-section table view snapshot

### To test

Test with both `Stats Traffic` feature flag enabled and disabled:

1. Select a high traffic site
6. Open `Traffic` or `Days/../Years` tab
7. Go through each of the cards and tap "View More"
8. For Post & Pages cards click on a specific post
9. Confirm that views open and scroll without any crashes or glitches

## Regression Notes
1. Potential unintended areas of impact

Breaking Stats Details views

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing

3. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by staskus** [comment]
TODO: Requires the same fix https://github.com/wordpress-mobile/WordPress-iOS/pull/22857

Edit: Done ✅

**Comment by guarani** [comment]
When I run this on my phone, Stats feels sluggish. I haven't checked `trunk` yet, but this is what I see when testing this branch:
- App freezes for 4-5 seconds when tapping back on the details screens (e.g. Posts and Pages
- Slow scrolling on the main Day screen as well as on the detail screens

It's hard to tell if it's due to the debug build or an actual issue with the app. I'm leaving this as a partial review to come back to.

**Comment by staskus** [comment]
> When I run this on my phone, Stats feels sluggish.

Thanks for testing!

Yes, we should be careful with performance, especially given that the goal if this task was to optimize Stats. I'll check later myself to see which operations could be making Stats sluggish and maybe there're some flaws in this implementation.

**Comment by staskus** [comment]
@guarani 

> When I run this on my phone, Stats feels sluggish. I haven't checked trunk yet, but this is what I see when testing this branch:
> App freezes for 4-5 seconds when tapping back on the details screens (e.g. Posts and Pages
> Slow scrolling on the main Day screen as well as on the detail screens

I can reproduce the same thing when the iPhone is connected to a debugger. Both on the `trunk` and on `task/22720-stats-details-optimize-table-view-updates-by-integrating-diffable-data-source` branch. So it doesn't look to be related to these changes.

- Back action is delayed by `WordPressComLanguageDatabase.init()` method. Specifically, the call implemented in WordPressKit (https://github.com/wordpress-mobile/WordPressKit-iOS/commit/b942929e49e0636ddd033525cadbc82e57da9963) to get device language slug. It's called once for each of the Stats endpoint:
image

Without a connected debugger, `WordPressComLanguageDatabase.init()` calls have a smaller footprint which doesn't cause a hang although it still takes a visible footprint of resources:

image

- Scroll lag is caused by the methods described in this comment (https://github.com/wordpress-mobile/WordPress-iOS/issues/22721#issuecomment-1997901640). It just looks to be slower and more apparent when connected to the debugger.

**Review by guarani — APPROVED** [review]
Thanks for checking @staskus! 

I re-tested with the feature flag on and off by going through all the Traffic detail screens and found no issues. It's not very easy to see the difference this PR makes because of the other performance issues that are unrelated to this PR. Even after disconnecting the debugger, the back button is very slow at times (~5 seconds to respond), but it might also have to do with it being a debug build. 

I think this is good to merge because the diffable data source is the way forward 👍

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/278">24.7</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
