### PR TITLE
Disable automatic breadcrumb tracking

### PR DESCRIPTION
**Pull request by jkmassel**
**To test:** 
- Set a breakpoint at https://github.com/Automattic/Automattic-Tracks-iOS/blob/40c80b2966b2bf9d47b2c629d44cd63dc500bdf6/Automattic-Tracks-iOS/CrashLogging.swift#L47 and launch the app.
- Ensure the breakpoint isn't hit at startup.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by frosty — APPROVED** [review]
Changes work for me!

But did we decide to definitely remove the breadcrumbs? Is there some value in keeping them if the stack traces are symbolicated and the crash descriptions are improved?

**Comment by loremattei** [comment]
Hey there! I've moved this to 13.8 since 13.7 has been cut. If you want this to make it to 13.7, please feel free to ping me.

**Comment by pinarol** [comment]
Hey there! I've moved this to 14.0 since 13.9 has been cut. If you want this to make it to 13.9, please feel free to ping me.

**Comment by jkmassel** [comment]
This is waiting on encrypted logging – I'm going to close it for now to avoid cluttering up the list.

Will reopen when ready.

Thanks!

**Pull request closed without merging**
