### PR TITLE
Issues/update reader analytics

### PR DESCRIPTION
**Pull request by aerych**
Updates an adds new analytics for the reader. 
Sorts some existing code for readability. 

cc @astralbodies for naming convention sanity check.

Needs review: @sendhil

### CODE REVIEW

**Comment by sendhil** [comment]
The naming looks good to me.

**Comment by sendhil** [comment]
:shipit:

**Comment by astralbodies** [comment]
I know the PR has already been merged but the event names specifically sent to Tracks look good.

@daniloercoli can you make sure to keep an eye out for a similar PR on Android? @nbradbury have you made these changes yet?

**Comment by nbradbury** [comment]
@astralbodies No, these changes haven't made their way to Android yet. I'll create a PR for this.

**Comment by aerych** [comment]
@nbradbury I was planning on adding the same changes to Android if you don't mind me stumbling about in your sandbox for a bit :)

**Comment by nbradbury** [comment]
> I was planning on adding the same changes to Android if you don't mind me stumbling about in your sandbox for a bit :)

Go for it :)

**Comment by astralbodies** [comment]
Awesome @aerych! If there are similar events being fired off in Calypso for Tracks, make sure to coordinate the names with them too. I'm finding more and more people wanting to create cross-product funnels!

**Comment by aerych** [comment]
> make sure to coordinate the names with them too

I shall match all the things!

**Pull request merged**
