### PR TITLE
Fixes animation glitch displaying restore cell.

### PR DESCRIPTION
**Pull request by aerych**
Refs #3673 
Avoids unnecessarily refreshing the table view when transitioning a post card to a restore cell.  Keeps the animation very smooth.

Needs Review: @koke

### CODE REVIEW

**Comment by koke** [comment]
I got a crash when I trash a post:

```
(lldb) po $rax
Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (41) must be equal to the number of rows contained in that section before the update (40), plus or minus the number of rows inserted or deleted from that section (1 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).

(lldb) bt
* thread #1: tid = 0xb9cc68, 0x00000001162fbb8a libobjc.A.dylib`objc_exception_throw, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x00000001162fbb8a libobjc.A.dylib`objc_exception_throw
    frame #1: 0x0000000116662aca CoreFoundation`+[NSException raise:format:arguments:] + 106
    frame #2: 0x0000000112ef598f Foundation`-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
    frame #3: 0x00000001140e4c53 UIKit`-[UITableView _endCellAnimationsWithContext:] + 12678
    frame #4: 0x000000010fded6eb WordPress`-[AbstractPostListViewController deletePost:](self=0x00007f996bc4ea70, _cmd=0x000000011060ad61, apost=0x00007f996bca4df0) + 523 at AbstractPostListViewController.m:600
    frame #5: 0x000000010ffb0c17 WordPress`-[PostListViewController cell:receivedTrashActionForProvider:](self=0x00007f996bc4ea70, _cmd=0x000000011060c9cd, cell=0x00007f99698b1200, contentProvider=0x00007f996bca4df0) + 103 at PostListViewController.m:606
    frame #6: 0x000000010fe0fac6 WordPress`-[PostCardTableViewCell trashPostAction](self=0x00007f99698b1200, _cmd=0x000000011060c92a) + 198 at PostCardTableViewCell.m:544
    frame #7: 0x000000010fe0e1cf WordPress`__52-[PostCardTableViewCell configurePublishedActionBar]_block_invoke354(.block_descriptor=<unavailable>) + 47 at PostCardTableViewCell.m:448
    frame #8: 0x000000010fdca6ea WordPress`-[PostCardActionBar handleButtonTap:](self=0x00007f996bcc0da0, _cmd=0x0000000110607c07, sender=0x00007f996be624e0) + 362 at PostCardActionBar.m:360
    frame #9: 0x0000000114008da2 UIKit`-[UIApplication sendAction:to:from:forEvent:] + 75
    frame #10: 0x000000011411a54a UIKit`-[UIControl _sendActionsForEvents:withEvent:] + 467
    frame #11: 0x0000000114119919 UIKit`-[UIControl touchesEnded:withEvent:] + 522
    frame #12: 0x00000001143b3a10 UIKit`_UIGestureRecognizerUpdate + 9487
    frame #13: 0x0000000114055686 UIKit`-[UIWindow _sendGesturesForEvent:] + 1041
    frame #14: 0x00000001140562b2 UIKit`-[UIWindow sendEvent:] + 666
    frame #15: 0x000000011401c581 UIKit`-[UIApplication sendEvent:] + 246
    frame #16: 0x0000000114029d1c UIKit`_UIApplicationHandleEventFromQueueEvent + 18265
    frame #17: 0x00000001140045dc UIKit`_UIApplicationHandleEventQueue + 2066
    frame #18: 0x0000000116596431 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #19: 0x000000011658c2fd CoreFoundation`__CFRunLoopDoSources0 + 269
    frame #20: 0x000000011658b934 CoreFoundation`__CFRunLoopRun + 868
    frame #21: 0x000000011658b366 CoreFoundation`CFRunLoopRunSpecific + 470
    frame #22: 0x0000000117eeca3e GraphicsServices`GSEventRunModal + 161
    frame #23: 0x0000000114007900 UIKit`UIApplicationMain + 1282
    frame #24: 0x000000010fd0ea3e WordPress`main(argc=1, argv=0x00007fff4fef8368) + 62 at main.m:5
    frame #25: 0x0000000117205145 libdyld.dylib`start + 1
    frame #26: 0x0000000117205145 libdyld.dylib`start + 1
```

**Comment by koke** [comment]
It looks like it's crashing only when you trash the first post on the list

**Comment by aerych** [comment]
> It looks like it's crashing only when you trash the first post on the list

Weird. That was my test scenario but I saw no crash.  Any other details?

**Comment by koke** [comment]
Wow, that was a tricky one.

So, `-[PostListViewController predicateForFetchRequest]`:

```
    if ([searchText length] == 0 && [self.recentlyTrashedPostIDs count] > 0) {
        NSPredicate *trashedPredicate = [NSPredicate predicateWithFormat:@"postID IN %@", self.recentlyTrashedPostIDs];
        predicate = [NSCompoundPredicate orPredicateWithSubpredicates:@[predicate, trashedPredicate]];
    }
```

If there's a trashed post the resulting predicate will be (in pseudo-code):

```
((blog == $blog) AND original == nil) AND status IN {"publish", "private"}) OR postID IN {$trashedID}
````

In other words: (whatever) **OR** postID IN {$trashedID}

postID is only unique per-blog, and you might see where this is going, there was a post from a different blog with that ID (being first was irrelevant) which is now matched by the fetch request. The table will have one row more than it's expecting, and it crashes because it's inconsistent

**Comment by aerych** [comment]
Ooph.  Good catch

**Comment by aerych** [comment]
Closing in favor of #3784

**Pull request closed without merging**
