### PR TITLE
Account Settings, part 1

### PR DESCRIPTION
**Pull request by koke**
To review after #4732, [relative diff](https://github.com/wordpress-mobile/WordPress-iOS/compare/feature/my-profile-error-handling...feature/account-settings-take-2)

I just ported the code that I already had in the [feature/account-settings](https://github.com/wordpress-mobile/WordPress-iOS/tree/feature/account-settings) branch to the latest design from #4732. I started writing the account settings feature, then I decided to first implement all the RxSwift stuff on My Profile first, then extract the common logic.

This isn't the full feature, but the easy parts :wink: 
- Web address doesn't have any validation, it's just a plain text field.
- Email is read only, since it needs validation, and a whole flow for email change confirmation.
- Primary site selector is missing
- The mockups also had Interface Language and Instant Post Feedback, which I argued don't make much sense on the app, since they feel more like client settings for calypso.

Needs Review: @astralbodies

### CODE REVIEW

**Comment by koke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;YKbv64tN&#x2F;2-account-settings"> Account Settings</a>

**Comment by astralbodies** [comment]
Now that I got the My Profile network PR reviewed, I'll review this one shortly.

**Comment by astralbodies** [comment]
Reviewing now, @koke. Sorry for the delay. Can you bring the branch current with develop in the meantime?

**Comment by astralbodies** [comment]
`SettingsViewControllerTest.m` needs to get removed - the file wasn't being compiled because it wasn't part of the test target 😕

**Comment by koke** [comment]
Merged and removed test

**Comment by astralbodies** [comment]
I'm still wary of how the failed updates are handled with the data flopping back to the original value. In the end its not destructive and at least the UI does reflect the reverted data. Maybe we can put an issue (if there isn't one already) for coming up with a way to signal a failed update if the user is still in the screen where the notification is relevant.

One side note I didn't see the activity indicator in the status bar when changing the web address and tapping done with a bad network link conditioner turned on. I went back to `Me` and then saw the spinner.

Otherwise @koke this looks solid :facepunch: 

:shipit:

**Pull request merged**
