### PR TITLE
Update Nimble and Starscream to latest version

### PR DESCRIPTION
**Pull request by elibud**
**Fixes** #7926 

**To test:**

Build and ran the app, send yourself a notification from the web, test that everything works as expected.
Run the tests locally, check that all is all green.

Needs review: @koke

### CODE REVIEW

**Comment by jleandroperez** [comment]
I'm seeing this in console:

```
2017-10-10 10:41:11:799 WordPress[4165:1866958] PingHub connecting
2017-10-10 10:41:22:301 WordPress[4165:1866958] PingHub disconnected: Error Domain=WebSocket Code=403 "Invalid HTTP upgrade" UserInfo={NSLocalizedDescription=Invalid HTTP upgrade}
2017-10-10 10:41:24:471 WordPress[4165:1866958] PingHub connecting
2017-10-10 10:41:28:689 WordPress[4165:1866958] PingHub disconnected: Error Domain=WebSocket Code=403 "Invalid HTTP upgrade" UserInfo={NSLocalizedDescription=Invalid HTTP upgrade}
```

@koke any thoughs on what might be causing this?

**Comment by koke** [comment]
@elibud @jleandroperez I figured out the error. We need to change the `endpoint` URL from `wss` to `https`.

Starscream will use that to add a `Origin` header, and WordPress.com doesn't recognize the `wss` and closes the connection with a HTTP 403

**Comment by elibud** [comment]
@koke thanks a million for that, updated and:

1. There's no error on the simulator
2. Receiving a notification on the device via PingHub worked correctly for me.

@jleandroperez @koke another look?

**Comment by jleandroperez** [comment]
Fix confirmed, nice work!

:shipit:

**Pull request merged**
