### PR TITLE
Share Extension: Attachments

### LINKED ISSUE #4910: Share Extension: Attach items like images, PDFs
Dig through the extensionContext and make sure to attach anything like images, PDFs, etc. to the posts.

### PR DESCRIPTION
**Pull request by jleandroperez**
Closes #4910

#### Scenario: Upload Pictures
1. Launch the Photos.app and pick any picture
2. Tap over the extensions button and launch the WordPress Share Extension
3. Pick a blog and make a post

Verify that the image gets effectively posted at the top.  

#### Known Issues / Limitations:
- Retry / Recovery mechanism is still pending.
- The user may upload just a single picture. Multiple pictures are (still) not supported.

Needs review: @astralbodies 
Aaron, may i bother you with a review?. Any UX / suggestions will be *very* welcome.

cc @SergioEstevao

### CODE REVIEW

**Comment by astralbodies** [comment]
@jleandroperez I'm still seeing that squashed UI on the iPad Pro with and without the external keyboard.

img_0013

**Comment by jleandroperez** [comment]
@astralbodies should be good to go now!

**Comment by astralbodies** [comment]
Looks like I can't share an image from Safari - not going to block this PR with that issue with our activation logic. #5642

**Comment by astralbodies** [comment]
It appears that `public.image` isn't limited to an item provider of type NSURL - it's possible for a UIImage to be passed back. We have to patch WordPressComKit to expand the methods available before continuing forward with a fix.

**Comment by astralbodies** [comment]
We've resolved a number of issues with the sharing of media. There remains a bug with the calls possibly not going through when on an actual device. We're erring on the side of opening a bug fix against `release/6.4` instead of waiting until 6.5 and holding this PR up any longer.

**Comment by astralbodies** [comment]
:shipit:

**Comment by jleandroperez** [comment]
Thank you @astralbodies!! Session Bug will be addressed via #5653.

**Pull request merged**
