### PR TITLE
Implement a type to track Privacy Settings analytic events

### LINKED ISSUE #20798: iOS - Track user actions
Implement the following new analytic events.

Event | Trigger
---- | ----
`privacy_choices_banner_presented` | When the banner is presented
`privacy_choices_banner_settings_button_tapped` | When the settings button is tapped
`privacy_choices_banner_save_button_tapped` | When the save button is tapped

### PR DESCRIPTION
**Pull request by salimbraksa**
Fixes #20798

## Description

This PR implements a class responsible for tracking the following events:

**New Events**:
These are new events but they're not tracked yet.
- privacy_choices_banner_presented
- privacy_choices_banner_settings_button_tapped
- privacy_choices_banner_save_button_tapped

**Old Events**:
These are old events that were part of the massive `WPAnalyticsEvent` enum. I moved them from this enum into `PrivacySettingsAnalytics` enum:
- privacy_settings_opened
- privacy_settings_report_crashes_toggled

## Test Instructions

Since the **New Events** are not being tracked, there is nothing to test there. But the old events were refactored so they should be tested for regression.

1. Build and run Jetpack
2. Head to "Me > App Settings > Privacy Settings"
3. Toggle "Crash Reports"
4. Expect these logs in the console
```
🔵 Tracked: privacy_settings_opened <>
🔵 Tracked: privacy_choices_banner_save_button_tapped <enabled: true>
```

## Regression Notes
1. Potential unintended areas of impact
Existing privacy settings analytics could be impacted. See "Test Instructions".

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing.

3. What automated tests I added (or what prevented me from doing so)
None.

## PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mokagio** [comment]
I'm going to start the 22.7 code freeze soon and this PR: 1) hasn't been reviewed yet, 2) has conflicts. I'm going to bump it to 22.8.

Feel free to revert and update base branch to `release/22.7` if this can't wait two more weeks.

**Review by mokagio — DISMISSED** [review]
The current diff doesn't build:

image

Aside from that, there are no unit tests for these changes.

Adding tests for this kind of code might not be straightforward but is necessary. I took a stab at it in https://github.com/wordpress-mobile/WordPress-iOS/pull/20961. That PR fails in CI for the same reason this one does. To verify the tests work, I commented out the line that doesn't build and pushed a test PR, https://github.com/wordpress-mobile/WordPress-iOS/pull/20962

**Comment by salimbraksa** [comment]
@mokagio Thank you for your review and for pointing out the build issue with the current diff ( resolved in 01778799fae747ae4470dc517dfae436e372793c ). I also appreciate your initiative in working on the unit tests, you'll find my feedback in https://github.com/wordpress-mobile/WordPress-iOS/pull/20961.

> Adding tests for this kind of code might not be straightforward but is necessary

Agreed. Since you already added tests for the `PrivacySettingsAnalyticsTracker` type, I'll build on that and add a unit test for the `navigateToPrivacySettings` method.  The test should check whether the `tracker` is called.

**Review by antonis — APPROVED** [review]
LGTM 🎉 
Thank you for your work on this @salimbraksa 🙇

**Comment by mokagio** [comment]
@salimbraksa 

> The requested changes were addressed.

I'm happy that this was merge as is so it can be used in the beta, _but_ my requested changes were not addressed. There are still no tests in this PR.

I think that if tracking privacy settings events is so important that we are adding it to the beta, then having unit tests that give us more confidence in the tracking behavior being correct should be part of the work, too.

**Comment by salimbraksa** [comment]
@mokagio 

> I'm happy that this was merge as is so it can be used in the beta, but my requested changes were not addressed. There are still no tests in this PR.

I think I misunderstood your changes request. I thought for this PR, you were referring to fixing the build error, that's why I dismissed the review so I can merge the PR. I think you were away at that time due to time zone differences.

My understanding was to fix the build error, merge this PR into `release/22.7`, then merge [the unit tests PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/20961) into `release/22.7`. But I guess what you had in mind was to merge the unit tests PR into this PR, then merge this PR into `release/22.7`. Is that correct?

Sorry for the confusion, I just approved the [unit tests PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/20961), so we can merge it into `release/22.7`.

**Comment by mokagio** [comment]
@salimbraksa That's okay. I could have been clearer. 

> But I guess what you had in mind was to merge the unit tests PR into this PR, then merge this PR into release/22.7. Is that correct?

What I had in mind was to add unit tests. The build error _had to_ be addressed regardless, or GitHub wouldn't have enabled the merge button.

Thank you for taking a look at #20961. I has now landed in this branch.

However, that PR only setup the testing scaffold and added a couple of tests to ensure the components were wired up. Most of the event logging added here is still not unit tested.

_I think it would be appropriate to cover all the other code paths_. Let me know if I can help

**Pull request merged**
