### PR TITLE
Tracks some additional Helpshift events.

### LINKED ISSUE #3470: Add in more tracking for various Helpshift Interactions
@oguzkocer pointed out that Helpshift added a few more methods to their delegate that will allow us to track a few more things. Let's add in the following to our tracking:

```
static NSString *HSUserAcceptedTheSolution = @"User accepted the solution";
static NSString *HSUserRejectedTheSolution = @"User rejected the solution";
static NSString *HSUserSentScreenShot = @"User sent a screenshot";
static NSString *HSUserReviewedTheApp = @"User reviewed the app";
```

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes #3470.

Also removes events `WPAnalyticsStatSupportSentMessage` and `WPAnalyticsStatSupportSentReplyToSupportMessage` since:

1. There was no way to track those, and
2. They kind of overlap with `WPAnalyticsStatSupportReceivedResponseFromSupport` which is already tracked.

/cc @sendhil - Ready for review

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@sendhil - Do we want these events to be mutually exclusive with the original `WPAnalyticsStatSupportSentReplyToSupportMessage` event, or in addition to it?

**Comment by diegoreymendez** [comment]
Doubt: even if the enum name changed for `WPAnalyticsStatSupportSentMessage` we may want to keep the original [property flag](https://github.com/wordpress-mobile/WordPress-iOS/pull/6173/files#diff-0e4bdf148c930a0e03519d13ddaea3b0R855).

Thoughts?

**Comment by diegoreymendez** [comment]
@frosty - Can I bother you with a review?

**Comment by frosty** [comment]
@diegoreymendez Other than the conflict with `Podfile.lock`, the changes look good to me! Regarding changing the flag, I don't feel I know enough about our analytics setup to really make a recommendation. I like the fact that if we change it, it's consistent with the other new flags. Also, it looks like it's been changed on Android, so perhaps we should follow their lead.

:shipit:

**Comment by diegoreymendez** [comment]
Ty @frosty !

**Pull request merged**
