### PR TITLE
Issue/update screenshot generation

### PR DESCRIPTION
**Pull request by sendhil**
The Fastlane tool we've been using for a while deprecated use of UI Automation for screenshot generation a few versions back. We were fine and dandy using the old versions of the tool but unfortunately the old versions stopped working with the recent version of Xcode. This PR converts the script from UIAutomation to Xcode UI tests.

In order to run the script you'll need to install snapshot(`gem install snapshot`) and adjust the credentials in `WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift`. From the `Scripts/fastlane` directory run `snapshot` and you'll be good to go. Given how long a full run takes, I recommend you adjust `Snapfile` to only do one or two languages and a smaller set of devices.

A few notes

* I created a new Scheme to contain the screenshot generation as this is required by Snapshot.
* Lots of the code you see out there uses text to refer to elements but in some places it breaks down due to localization particularly on controls or elements where the accessibility identifier is set to localized text. As such you'll see a lot of the code in particular accessing items by an index. This is somewhat brittle but the screenshot script always has been and any future changes shouldn't be too hard to fix.

cc @astralbodies

### CODE REVIEW

**Comment by astralbodies** [comment]
@sendhil I'm getting this failure:

```▸ Touching WordPressScreenshotGeneration.xctest
** TEST FAILED **

All tests
Test Suite WordPressScreenshotGeneration.xctest started
WordPressScreenshotGeneration
✗ testGenerateScreenshots, UI Testing Failure - No matches found for TabBar


WordPress.WordPressScreenshotGeneration
testGenerateScreenshots, UI Testing Failure - No matches found for TabBar
/Users/aaron/src/WordPress-iOS/WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift:49
```
        // Get Reader Screenshot
        app.tabBars["Main Navigation"].buttons["Reader"].tap()
        app.navigationBars["Blogs I Follow"].buttons["Menu"].tap()
  ```


	 Executed 1 test, with 1 failure (0 unexpected) in 18.051 (18.058) seconds

[15:48:34]: Exit status: 65
[15:48:34]: Tests failed - check out the log above
[15:48:34]: Backtrace:
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/error_handler.rb:14:in `handle_test_error'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:125:in `block in launch'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/fastlane_core-0.36.1/lib/fastlane_core/command_executor.rb:82:in `call'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/fastlane_core-0.36.1/lib/fastlane_core/command_executor.rb:82:in `execute'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:119:in `launch'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:35:in `block (3 levels) in work'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:31:in `each'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:31:in `block (2 levels) in work'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:30:in `each'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:30:in `block in work'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:29:in `each'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/lib/snapshot/runner.rb:29:in `work'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/bin/snapshot:37:in `block (2 levels) in run'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/bin/snapshot:78:in `run'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/snapshot-1.6.0/bin/snapshot:84:in `<top (required)>'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/bin/snapshot:23:in `load'
	/Users/aaron/.rvm/rubies/ruby-2.0.0-p598/bin/snapshot:23:in `<main>'
	/Users/aaron/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
	/Users/aaron/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'
[15:48:34]: Patching '/Users/aaron/Library/Preferences/com.apple.iphonesimulator.plist' to scale simulator to 100%
```

**Comment by astralbodies** [comment]
Oh wait I think I missed the credentials...

**Comment by astralbodies** [comment]
@sendhil I'm getting a failure in Xcode because the screenshot unit test is part of the Test configuration of the scheme. Can we remove that test suite from that scheme?

**Comment by astralbodies** [comment]
Everything looks good @sendhil except for the one comment about the scheme configuration. :shipit: after that's addressed! :smile:

**Comment by sendhil** [comment]
@astralbodies pushed a commit up.

**Comment by astralbodies** [comment]
@sendhil I pushed a commit that fixes the Travis build. It applies a fix I already have in develop (setting the root project deployment target to 9.0 instead of nil) and I also removed the override on base SDK in the WordPressTest target. This fixes the issue with `@testable` in that one unit test failing.

:shipit:

**Comment by astralbodies** [comment]
Okay I am at a loss as to why this is STILL failing. I got it to fail similarly locally and my fixes have fixed it locally. Damn you, Travis!

**Comment by astralbodies** [comment]
Found it - pushed a fix. This should let Travis get on with its life.

**Comment by astralbodies** [comment]
@sendhil Okay I fixed the build issue but it looks like Travis is executing the test configs for all of the schemes in the project. Maybe we should update the config so only WordPressTest is executed?

**Comment by sendhil** [comment]
@astralbodies - yea we probably should update that.

**Comment by astralbodies** [comment]
@sendhil Done :+1: 

Can you just verify the changes I made make sense and then :shipit:

**Pull request merged**
