### PR TITLE
Notifications + Swift Mk 1: Subviews Initialization

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:
This PR adds no new functionality. We'll gradually migrate all of the Notifications-Y code over to Swift.
Once it's ready, we'll address code improvements / technical debt.

Reference #5613

--

#### Scenario: Ratings
1. Perform a fresh install
2. Log into a Dotcom account
3. Open (5) notifications (can be the same!)

After hitting back for the last time, please, verify that the Ratings View shows up.

#### Scenario: Empty Notifications
1. Log into a Dotcom account that has no notifications
2. Tap over the Notifications tabBar button

Verify that the `No notifications yet` label shows up.
P.s.: I’ve got a million testing accounts, if needed, please, just let me know!

#### Scenario: Bucket Delegate
1. Log into a Dotcom account
2. Tap over the Notifications tabBar button
3. Receive a new notification (click `Like` over any comment of yours)

As a result, the Application’s Badge should get immediately cleared out.

#### Scenario: Pull to Refresh
1. Perform the Pull to Refresh gesture

Verify that the spinner briefly shows up, and gets dismissed.
Note: The PTR is just a ‘Dummy’ visual OP, since data is actually pulled from the backend.
Note II: YES this was implemented because we began getting tons of requests from confused users.

#### Scenario: Segmented Control
1. Log into a Dotcom account
2. Tap over the Notifications tabBar button

Verify that the Segmented Control filters work as expected (All / Unread /…).

Needs review: @kurzee 
Brent, may i bother you with a *violent* review?

Thanks in advance!!

### CODE REVIEW

**Comment by kurzee** [comment]
Found this, it may not be an issue.

notifications

**Comment by kurzee** [comment]
>Scenario: Bucket Delegate

For this one, I can't ever get the unread indicator to show when building for dev. However, I did successfully test this by downloading the App Store version, pulling in a notification without reading, leaving the indicator on. Then, build and run on the device, over the App Store build, tap the notifications tab, indicator disappears as expected.

**Comment by kurzee** [comment]
@jleandroperez this looks good to go! Nice job including the recent header/footer normalization changes as well.

*Note:* The milestone tagged here is 6.5, but 6.4 will be cut Monday, if you want to hold off on the merge.

ship-it

**Comment by jleandroperez** [comment]
Thanks for the review @kurzee!!

- Re: Actions over Like Notifications, that'd be expected, since that kind of notification shouldn't present any action. I've got an issue to add `Mark as Read / Unread` everywhere.
- Re: Notifications, already dm'ed you about that one.

Again, thanks!!!

**Pull request merged**
