### PR TITLE
Headers are no longer precompiled for WPiOS.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Precompiles headers are making some fake-errors pop up when building WPiOS, that makes spotting real errors more difficult.  I'm disabling precompiled headers for now.

**How to test:**
- Just make sure the build times are reasonable with this setting off.

/cc @sendhil, @astralbodies

### CODE REVIEW

**Comment by sendhil** [comment]
I ran a couple of builds using the `time` command and the results are kind of varying ;). That being said the times don't seem too bad to me, I think we could just merge it in and if people complain we can always revisit reverting it.

**Comment by astralbodies** [comment]
Lets give it a try and see how it goes :shipit:

**Comment by diegoreymendez** [comment]
@sendhil - Are the time differences significant, though?  A few notes:

- If the different in time isn't really significant, I'd rather have accurate results every single time, and avoid the fake errors.  Seeing fake errors often can make us adapt to ignore them, which can be risky.
- New Xcode projects don't turn on precompiled headers by default anymore, afaik.
- For system libraries we now have the possibility to use modules, which I think also affects compile times in a possitive way (in case we feel the need to recover some of that time back).

**Comment by diegoreymendez** [comment]
All right, merged and we can keep an eye on this as suggested.

**Pull request merged**
