### PR TITLE
Fix project to allow Cocoapods 0.36 to work properly

### PR DESCRIPTION
**Pull request by sendhil**

### CODE REVIEW

**Comment by sendhil** [comment]
cc @diegoreymendez

**Comment by sendhil** [comment]
Actually - closing this as we're still having issues.

**Comment by jleandroperez** [comment]
Working fine for me!. Side note, i'm getting few warnings (SiteStats.storyboard + DDLegacyMacros.h), but none of them is related to this PR.

:shipit:

**Comment by sendhil** [comment]
I'm not seeing any of the warnings. Lets merge this in and if we can reproduce we'll let's tackle them as they come up.

**Pull request merged**
