### PR TITLE
Integrated Editor v1.6.2.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Integrated the latest editor version (1.7), fixing an important bug when pasting links.

While this fix allows links to be pasted, they're currently pasted as simple text.  I've created [a new issue](https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/829) to implement this.

More information [here](https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/825).

To test:
Paste an URL copies from Safari.

Needs review: @SergioEstevao 

/cc @astralbodies

### CODE REVIEW

**Comment by SergioEstevao** [comment]
:shipit:

**Comment by astralbodies** [comment]
@diegoreymendez Conflicts 😢

**Comment by sendhil** [comment]
@diegoreymendez don't merge this. This includes more than just the copy/paste fix and including them this late in the cycle is risky. See link [here](https://github.com/wordpress-mobile/WordPress-Editor-iOS/compare/1.6.1...1.7).

**Comment by sendhil** [comment]
Fixed the merge conflict and pushed up an updated Podfile that points to the cherry picked version of the editor(1.6.2)

**Comment by diegoreymendez** [comment]
Thank you for taking care of this @sendhil!

**Comment by sendhil** [comment]
Updated title real quick. Going to merge this in now.

**Pull request merged**
