### PR TITLE
Fixed two unintentional changes in my previous commit.

### PR DESCRIPTION
**Pull request by susered**
Removes unneeded constraint breaking on iOS7

### CODE REVIEW

**Comment by aerych** [comment]
This pr contained one one commit @diegoreymendez from a branch we've deprecated (for now), and the description references a PR I'd made.  Closed as this makes no sense.

**Comment by aerych** [comment]
@susered This was a strange PR that you submitted.  Would you mind telling us about it?  What was the goal here? Maybe if we understand what you're trying to accomplish we can offer some advice.

**Comment by susered** [comment]
Pure accident in that at the time I did not know where to report an issue with the app. ..

**Comment by aerych** [comment]
We saw that you opened #3210 previously and that was the right way to open an issue. :)  

Pull requests should only be made when you some code you created on your own fork of the repo that you would like to have merged in.  Typically this should be fixing a bug or creating a new feature, and be addressing an open issue. 

If there is something new you'd like to bring up, have a look through the list of open issues and if there is not already a ticket for the issue you have in mind then feel free to make a new one.

**Pull request closed without merging**
