### PR TITLE
Integrates the latest changes from WordPressShared.

### LINKED ISSUE #11874: Quick Start Guide highlights no longer bold.
As a result of [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/11857) there was a regression that [is causing the highlights in the Quick Start Tour notices to no longer be bold](https://github.com/wordpress-mobile/WordPress-iOS/pull/11857#issuecomment-499250463).

We need to fix them to be bold again.

58919160-f2c0dc80-86e1-11e9-9b2f-b967450d67a9

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes #11874 

Certain styles cause method `fontForTextStyle(_:fontWeight)` to return a font that works well with the initial setup of Dynamic Type, but that fails to update properly when the Dynamic Type size is updated in real time.

We're updating to a version of WordPressShared that fixes this issue.

## Associated PRs:

WordPressAuthenticator: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/100
WordPressShared: https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/208
WordPressKit: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/161

## Testing:

1. Launch the App
2. Create a new Site
3. Once you're offered the Quick Start Guide accept the help.
4. Tap on "Upload a Site Icon"
5. Make sure the notice that reads "Tap Your Site Icon to upload a new one" has the right font size.
6. Go to you device's settings > Large Text > Pick a very different size.
7. Go back to the App and make sure the notice has updated its size to match the settings.

## Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by jkmassel** [comment]
I tested this as described, but rather than creating a new site, I overrode `shouldShowChecklist(for blog: Blog)` in `QuickStartTourGuide` to force the quick start to show for an existing site.

Here are the screenshots documenting what I saw when following this process:

Simulator Screen Shot - iPhone Xʀ - 2019-06-07 at 10 10 36
Simulator Screen Shot - iPhone Xʀ - 2019-06-07 at 10 10 17

If those look right to you, :shipit:!

**Comment by pinarol** [comment]
Hey @diegoreymendez I gave it a quick try but I am afraid "Your Site Icon" text doesn't get adjusted due to System font size:

Screen Shot 2019-06-10 at 10 19 04

**Comment by diegoreymendez** [comment]
@pinarol - We'll need to compare to figure out why we're seeing a difference, as it's working fine for me.

I've just re-tested using:

- Simulator: iPhone Xr (iOS 12.2)
- Physical device: iPhone XS with iOS 12.3.1

I got it to work fine in all cases.

This is a recording of the simulator test:

textResize

This is a screen from the simulator running iOS 11:

Screen Shot 2019-06-11 at 5 33 04 PM

**Comment by jkmassel** [comment]
I was able to repro the issue @pinarol is seeing. If the app never stops running during the font size change, you should see the issue.

**Comment by diegoreymendez** [comment]
> I was able to repro the issue @pinarol is seeing. If the app never stops running during the font size change, you should see the issue.

There's something weird cos this is exactly what I'm seeing (and the App is never killed).

textResize

Can I ask you to check that this a breakpoint in [this line](https://github.com/wordpress-mobile/WordPress-iOS/blob/4024b7a59fea650335803ac8fd44b7d48ffc728a/WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift#L227) gets all the way to [this line](https://github.com/wordpress-mobile/WordPress-iOS-Shared/blob/f33b40ada66c9eca5d834e655e8050701ac9ea71/WordPressShared/Core/Views/WPStyleGuide%2BDynamicType.swift#L125) during startup?

**Comment by diegoreymendez** [comment]
Thanks @pinarol and @jkmassel !

**Pull request merged**
