### PR TITLE
MediaPicker: WPMediaCollectionViewCell placeholder design update

### PR DESCRIPTION
**Pull request by bummytime**
**NOTE:** This PR has a dependency on https://github.com/wordpress-mobile/MediaPicker-iOS/pull/247. (Right now we are pointing to a specific git commit in the pod file.)

This PR updates some UIAppearance API values for `WPMediaCollectionViewCell`  in `WordPressAppDelegate`. We also are bringing in new updates from the `WPMediaPicker` pod. The end result yields a new default placeholder design:

screen shot 2017-09-29 at 12 28 57 pm

Fixes https://github.com/wordpress-mobile/MediaPicker-iOS/issues/245

To test:

Run WPiOS on a variety of devices and sims. Verify everything looks ok in both the media picker(s) as well as the media library.

Needs review: @SergioEstevao 

/cc @iamthomasbishop

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@bummytime @iamthomasbishop it's all looking good code wise.

Just a question do we want the cells to look like this while they are loading (WP Media Library)

screen shot 2017-09-29 at 21 51 32

**Comment by iamthomasbishop** [comment]
@SergioEstevao I would probably leave the background of the loading cells as the lighter gray that we have currently.

**Comment by SergioEstevao** [comment]
@bummytime we may then need to change the way the appearance selector to only change the background of the stack view that holds the file size info.

**Comment by bummytime** [comment]
@SergioEstevao @iamthomasbishop The loading cell backgroundColor issue has been fixed with the [latest commit to the media picker feature branch](https://github.com/wordpress-mobile/MediaPicker-iOS/pull/247/commits/8a6f2e05ad622cd5cbad4eefd3e47c005695a18c) this PR uses.

media_colors

Have another look when y'all are able to.

**Pull request merged**
