### PR TITLE
Updates Aztec to beta 16. Integration needs fixing.

### PR DESCRIPTION
**Pull request by diegoreymendez**
### Description:

This PR integrates Aztec 1.0.0 Beta 16 into WPiOS.

### Pending fixes:

There are some problems with the integration due to [this change](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/846/files#diff-d8a133f794ed76fc0e76e3f633a1cf51L11) in Beta 16.

Ideally, this should be merged before the 9.1 code freeze on Monday.

Can you let me know when the fix is up @SergioEstevao.  Thanks!

/ccing @elibud since she'll be freezing 9.1.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@diegoreymendez ready for another look.

**Comment by diegoreymendez** [comment]
Seems like there's a hound violation reported above, @SergioEstevao.

**Comment by elibud** [comment]
Thanks @jleandroperez for taking on this one.

**Comment by diegoreymendez** [comment]
Thanks @elibud and @jleandroperez for taking care!

**Pull request merged**
