### PR TITLE
Update to stats pod 0.6.2 - bug fixes mostly

### PR DESCRIPTION
**Pull request by astralbodies**
What's included:

* Prevents modal stats window from being dismissed when accessed through Today Widget in WPiOS
* Reorders Insights sections to current requirements
* Sanitizes post titles to eliminate special characters looking like HTML entities
* Ensures labels are resized properly when the text in them is too large

Needs Review: @sendhil 
cc: @daniloercoli

### CODE REVIEW

**Comment by astralbodies** [comment]
Revoking this PR - will re-apply at develop.

**Comment by astralbodies** [comment]
Wait, this was aimed at develop, lol.

**Comment by astralbodies** [comment]
Assigned to @koke since this isn't aimed at a release branch atm

**Comment by koke** [comment]
:shipit:

**Comment by astralbodies** [comment]
Thanks @koke!

**Pull request merged**
