### PR TITLE
[UI Tests] - Refactor login flows

### PR DESCRIPTION
**Pull request by jostnes**
### Description
Follow up PR to [this conversation](https://github.com/wordpress-mobile/WordPress-iOS/pull/21187#pullrequestreview-1550218517) in https://github.com/wordpress-mobile/WordPress-iOS/pull/21187. (note: this branch was created based of https://github.com/wordpress-mobile/WordPress-iOS/pull/21187, and will display changes from https://github.com/wordpress-mobile/WordPress-iOS/pull/21187 until that's merged)

Changes include: 
1. Removed unnecessary parameters used in the `login` methods
2. Renamed `siteUrl` and `selectedSiteTitle` to `siteAddress` to be more generic as we're now using one value since the values are the same

### Testing
CI should be 🟢

### CODE REVIEW

**Review by pachlava — CHANGES_REQUESTED** [review]
Hey @jostnes!

The changes are 👍. I'm requesting changes only because the screenshot generation tests are not building any longer. Even though they don't really work, once they're running, they at least should build.

**Comment by jostnes** [comment]
> Hey @jostnes!
> 
> The changes are 👍. I'm requesting changes only because the screenshot generation tests are not building any longer. Even though they don't really work, once they're running, they at least should build.

@pachlava nice catch! this won't fix the tests, but those tests should build with this change https://github.com/wordpress-mobile/WordPress-iOS/pull/21198/commits/d7463c8bcabc2fbc99fbcccad7592475ea9390d6 (also included one change we missed from an earlier change so it was probably not working before this PR 😬)

**Review by pachlava — APPROVED** [review]
With the latest changes, screenshots build as well 👍 I've enabled auto-merge, so 🤞 the CI passes on the first go. Thank you, @jostnes :shipit:

**Comment by pachlava** [comment]
(oh, I did not realize the 🟢 UI tests are not necessary for the merge, so the PR got merged as soon as I approved 😬)

**Comment by jostnes** [comment]
> (oh, I did not realize the 🟢 UI tests are not necessary for the merge, so the PR got merged as soon as I approved 😬)

😬 but i can now confirm the tests are 🟢!

**Pull request merged**
