### PR TITLE
Tenor Picker support for Aztec editor

### PR DESCRIPTION
**Pull request by ngoctr**
This added Tenor Picker support for Aztec Editor as part of #13803 

# Testing
**First steps**
1. Register your Tenor developer API here: https://tenor.com/gifapi
2. Check out this branch
3. Put your API Key into `.configure-files/wpcom_app_credentials` (TENOR_API_KEY line)
4. Run `rake dependencies`
5. Build and run

**Verify Tenor support in Aztec Post Editor**

1. Go to Site -> Posts
2. Open the Post and switch to Classic Editor if needed
3. Tap the Editor to activate edit mode
4. Tap the ellipsis button at the media toolbar, then select **Free GIF Library**
tenor-picker-aztec

5. Search and select your images, then tap Add button at the bottom right, verify that the selected image(s) have been added into the Post while being uploaded to Media library 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes. -> **This will be addressed in a separate PR**
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary. -> **This will be addressed in a separate PR**

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @ngoctr .

I'm seeing some odd behavior. 
- Start a new post with classic editor.
- Add a GIF.
- Preview the post.
- Notice the GIF doesn't appear in the preview.
- Close the preview.
- Notice the GIF has been replaced with the placeholder.

gif_post

**Comment by ngoctr** [comment]
Thanks @ScoutHarris. Let me check it, perhaps, there are some recent changes with the Aztec Editor.

**Comment by ScoutHarris** [comment]
FWIW, it works fine with the [Gutenburg editor](https://github.com/wordpress-mobile/WordPress-iOS/pull/13910).

**Comment by ngoctr** [comment]
Thanks @ScoutHarris. It worked perfectly with Aztec for me before, I am investigating why.

**Comment by ngoctr** [comment]
> Hey @ngoctr .
> 
> I'm seeing some odd behavior.
> 
> * Start a new post with classic editor.
> * Add a GIF.
> * Preview the post.
> * Notice the GIF doesn't appear in the preview.
> * Close the preview.
> * Notice the GIF has been replaced with the placeholder.
> 
> gif_post

This is an issue with both Aztec/Post Editors if we don't update the Post before previewing, then images will be invalid. If we do update first, then previewing, then it's all working fine. @ScoutHarris

**Pull request merged**
