### PR TITLE
Plans on JP: Update UI test to reach purchase result screen 

### LINKED ISSUE #20790: Plans on JP: Update UI test to reach purchase result screen
The UI test in `DashboardTests` need to be updated to cover the entire plan purchase flow including the final result screen.

### PR DESCRIPTION
**Pull request by staskus**
Fixes #20790

**Implementation**

1. Use `WireMock` to mock web view pages instead of API endpoints
2. Create fake checkout and plans pages to be used in UI tests
3. Redirect to expected pages once the links are tapped
4. Use `Environment` to inject `WireMock` URL and use it instead of WP.com URL 
5. Covered the whole flow with tests

**To test:**

- Confirm UI tests succeeding in CI

## Regression Notes
1. Potential unintended areas of impact

Affecting free to paid plans flow

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manually retesting the whole purchase flow

3. What automated tests I added (or what prevented me from doing so)

Covered the whole free to paid plans flow with automated UI Tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Video

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/afc7bb99-bb27-4e5f-83ac-b54559467ab7

### CODE REVIEW

**Comment by staskus** [comment]
@guarani if you're interested, it looks like `WireMock` can also be used to mock `web view` content. Check the video from [00:17-] to see how it would look. We would essentially verify that our native code responds to the redirections as expected. This way we can simulate the whole flow. WDYT?

**Comment by guarani** [comment]
> @guarani if you're interested, it looks like `WireMock` can also be used to mock `web view` content. Check the video from [00:17-] to see how it would look. We would essentially verify that our native code responds to the redirections as expected. This way we can simulate the whole flow. WDYT?

This seems like an interesting approach. I watched the screen recording and agree this test can ensure that the app can handle the redirects.

On Calypso a test for https://github.com/Automattic/wp-calypso/pull/77029 could verify the sequence of screens and redirect URLs don't get changed.

**Comment by staskus** [comment]
> This seems like an interesting approach. I watched the screen recording and agree this test can ensure that the app can handle the redirects.

Yes. These are not E2E tests, only native UI tests. Just like with mocked APIs, we expect our app to behave in a certain way given the input. 

> On Calypso a test for [Automattic/wp-calypso#77029](https://github.com/Automattic/wp-calypso/pull/77029) could verify the sequence of screens and redirect URLs don't get changed.

👍 Good idea

**Comment by staskus** [comment]
@guarani 

Ready for review. The whole free to paid plans flow on the native side is now covered with UI tests

**Review by guarani — COMMENTED** [review]
👋 While the changes look good, I keep running into the issue where the dashboard card doesn't appear and the UI test keeps trying to scroll the screen up to find it (similar to https://github.com/wordpress-mobile/WordPress-iOS/pull/20728#pullrequestreview-1440601868). It also works the second time I run the app.

I re-read your comment, https://github.com/wordpress-mobile/WordPress-iOS/pull/20728#issuecomment-1560863895, and the fix you added (reloading local cards after the app fetches the site domains), but don't see anything wrong.

Stopping at breakpoints seems to affect whether the card shows up or not, so I printed `hasLoadedDomains` in both the failing scenario (1st run after fresh install) and the passing scenario (2nd run) and there's a difference:

| Not working | Working |
| - | - |
| Screenshot 2023-06-06 at 20 43 23 | Screenshot 2023-06-06 at 20 45 14 | 

I thought to check if this is reproducible on `trunk` and it isn't. I did two fresh installs and both worked the first time. Have you tried a fresh install on this branch? I'm curious if you can reproduce.

**Comment by staskus** [comment]
> I thought to check if this is reproducible on trunk and it isn't. I did two fresh installs and both worked the first time. Have you tried a fresh install on this branch? I'm curious if you can reproduce.

It is reproducible but only sometimes. In a morning investigation, I couldn't point out exactly why it would happen. Even in your "not working" scenario, the third reload of the free to-paid plan card indicates that domains are loaded so the card should appear. I continue investigating.

**Comment by staskus** [comment]
I found the issue that `hasMappedDomain` unexpectedly returns `true` with these internal values, causing `shouldShowCard` to return `false`. 

image

- `API-Mocks` have `rest_v11_sites_106707880.json` that matches `urlPath": "/rest/v1.1/sites/106707880` and sets different values for "URL" and "unmapped_url" fields.
- `rest_v11_sites_106707880.json` matches `urlPathPattern": "/rest/v1.(1|2)/me/sites` that shares the same siteID but sets the same "URL" and "unmapped_url" fields.
- `rest_v11_sites_106707880_settings.json` that shares the same siteID but has a different "URL" field from the previous one

I haven't identified how these API mocks are matched and how it differs between the first or second launches. However, after making the mocks consistent, I could no longer reproduce the issue in multiple attempts. 

Could you try it out again, @guarani, thanks!

**Comment by guarani** [comment]
👋 Hey @staskus, I gave this a try today and weirdly still getting the same issue. I'd love to investigate more today, but I want to prioritise manually testing the flows since the project is close to finishing.

Do you agree with de-prioritizing this until we're confident we've done enough manual testing? I appreciate you investigating this and I think once it's working, having the UI test here for the happy path will be very valuable to catch regressions going forward.

**Comment by staskus** [comment]
> Do you agree with de-prioritizing this until we're confident we've done enough manual testing? 

Yes, we can wait given the issues we're facing in producing these tests.

**Pull request closed without merging**
