### PR TITLE
WPWebViewController: Fixing WordPress CDN auth

### LINKED ISSUE #4983: WPWebViewController not following 301 redirects properly
### Expected behavior
When visiting a url like https://astralbodiesnet.files.wordpress.com/2014/02/2014-02-10_12-44-50.png it should just load.

### Actual behavior
The web view is being redirected to wordpress.com/wp-login.php with a 403 error.

### Steps to reproduce the behavior
1. Log into the app and view stats for a frequently viewed site.
2. Find the clicks section and look for `WordPress.com Media`.
3. Expand that section and try tapping on any file URL.
4. User is presented with a 403 Forbidden Screen.

##### Tested on iPhone 6s Plus & Simulator, iOS 9.2.1

cc: @jleandroperez

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:
WordPress CDN (`.files.wordpress.com`) doesn't deal with authentication. In this (small) PR we're patching (hacking) the Auth URL.

**Note:** (Just for the record) I've got a working branch to switch over to `WKWebView`, which would have *vastly* improved the code quality in WPWebViewController. However... `WKWebView` appears to ignore the `NSURLRequest` **HTTPBody**. Isn't that so great?

#### Scenario:
1. I've hacked [this spot](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Stats/StatsViewController.m#L159), and added the following snippet, for the sake of ease of testing.
  ```
    url = [NSURL URLWithString:@"https://astralbodiesnet.files.wordpress.com/2014/02/2014-02-10_12-44-50.png"];
  ```
2. Launch WPiOS and log into your account
3. Open any blog's Stats, and tap over any links in the clicks section

As a result, the asset should show up onscreen.

Needs review: @astralbodies 
Fixes #4983

Thanks in advance Aaron!

### CODE REVIEW

**Comment by astralbodies** [comment]
@jleandroperez: Can you also cherry pick this for WPiOS 6.1 once its merged?

**Comment by jleandroperez** [comment]
@astralbodies yes sir!

**Comment by astralbodies** [comment]
:shipit: 

Discovered a small auth weirdness with this when 2FA is enabled. It won't hold up this PR and I'll file another issue.

**Comment by jleandroperez** [comment]
Thanks Aaron! Doing some research (RE: 2FA bug).

**Pull request merged**
