### PR TITLE
Jetpack Focus: Emphasize uninstalling the app in the migration success card

### LINKED ISSUE #20513: Jetpack Focus: Update migration success UI
## Description

Update the wording on the migration success card to make clear to users they should uninstall the app instead of deleting their site.

Slack ref: p1681290711175429-slack-C0180B5PRJ4
Design ref: qk5s4q4mZsXknwhMWo2vIY-fi-10230_21914

## Todo

- [x] Update strings on the final step of the migration
- [x] Update strings and appearance on the dashboard card
- [x] Update strings on the migration popover

### PR DESCRIPTION
**Pull request by momo-ozawa**
Fixes #20513 

## Description
Updates the migration success card design to make clear to users they should **uninstall the WordPress app** (not delete their site)

Design ref: qk5s4q4mZsXknwhMWo2vIY-fi-10230_21914

## How to test

Note that we're updating the value of existing localized strings. For testing purposes, change the keys by appending an extra letter to see the new value.
- `MigrationCenterViewConfiguration.swift`: L24, L27 
- `MigrationDeleteWordPressViewModel.swift`: L33, L38

1. Delete the Jetpack app
2. Install the WordPress app if not installed already
3. Build and run the Jetpack app
4. Follow the migration flow
5. ✅ The migration success card should match the new designs - please test light vs dark mode, landscape vs portrait, min / max font sizes
6. Tap on the migration success card
7. ✅ The overlay should match the new designs  - please test light vs dark mode, landscape vs portrait, min / max font sizes (note: we've decided to use ["on your device" instead of "on your iPhone"](p1681296746617889/1681290711.175429-slack-C0180B5PRJ4)) 

Before | After (light mode) | After (dark mode)
-- | -- | --
 |  | 
 |  | 

## Regression Notes
1. Potential unintended areas of impact
n/a

8. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a

9. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by staskus — APPROVED** [review]
👍

Tested by temporarily commenting out Localizable.strings file:

✅ Strings updated on the final step of the migration
✅ Strings and appearance updated on the dashboard card
✅ Strings updated on the migration popover

**Review by osullivanchris — APPROVED** [review]
Screenshots look good to me. Nice work! 🙌

**Review by hassaanelgarem — APPROVED** [review]
🚀

**Comment by momo-ozawa** [comment]
@tiagomar I added the RtL assets!

LtR | RtL
-- | --
 |

**Pull request merged**
