### PR TITLE
Reader: Check siteID to determine if topic is external.

### LINKED ISSUE #5730: Reader: Crash when you follow/unfollow from the site detail
### Expected behavior

I should be able to follow or unfollow a site using the link in the top right of the site detail screen in the reader.

### Actual behavior

When I tap to follow/unfollow a site on the site detail screen, the app crashes.

### Steps to reproduce the behavior

1. Open the Reader in the app
2. Tap the header area on a post to open the site detail
3. Tap Follow or Following in the top right to follow or unfollow the site

Result: the app crashes

### PR DESCRIPTION
**Pull request by aerych**
Fixes #5730 

To test:
#### Scenario 1
Browse posts for a tag. 
Tap the header of one of the posts in the list to preview that site. 
Tap the following button in the site header to follow and unfollow the site. Confirm there are no crashes. 
#### Scenario 2
In the new reader Menu, ap the Manage button next to Followed Sites.
Tap on one of the sites in the list to preview it. 
Unfollow and refollow the site. Confirm their are no crashes. 
#### Scenario 3
Back on the Manage Sites list, follow a wpcom site and a remote feed via the search bar. 
Confirm they are followed correctly and there are no crashes. 
#### Scenario 4
Swipe to delete the two sites you just added. 
Confirm they are removed correctly and there are no crashes. 

Needs review: @nheagy would you mind taking this one?

### CODE REVIEW

**Comment by aerych** [comment]
Whoops! I forgot @nheagy was afk for a bit.  @frosty could I trouble you instead?

**Comment by aerych** [comment]
Annnnnnd back to @nheagy since he's around after all.  Gotta love some github ping pong :)

**Comment by nheagy** [comment]
As I see it, the :shipit: have it.

**Comment by aerych** [comment]
Thanks @nheagy !!

**Pull request merged**
