### PR TITLE
Remove custom activities

### LINKED ISSUE #4600: Remove all the custom sharing activities
Remove this custom activities and rely on share extensions:

 - SafariActivity
 - InstapaperActivity
 - PocketActivity
 - GooglePlusActivity
 - WordPressActivity

### PR DESCRIPTION
**Pull request by SergioEstevao**
Closes #4600 

How to test:

Go to the reader, open an article and click on the share extension:

- The following custom activities should be gone:

- GooglePlus
- Instapaper
- Pocket

However if you have any of those applications installed in your device you should be to use their standard share activity that should be available on the top row, if you have enable it.

@astralbodies: I noticed that we where tracking the use of these custom activities, so I kept the tracking on using the extension class identifier. Is this something we want to keep? Or we just want to track the general use of share activities and those are not that relevant?

Needs Review: @aerych

### CODE REVIEW

**Comment by aerych** [comment]
Awesome :)  :shipit:

**Comment by aerych** [comment]
> Or we just want to track the general use of share activities and those are not that relevant?

Might be nice to have analytics for the share activity type regardless of what it is.  Maybe for a later PR? cc @astralbodies

**Comment by astralbodies** [comment]
> Might be nice to have analytics for the share activity type regardless of what it is. Maybe for a later PR?
Yeah I think that's the right approach. I'm still working on the share extension which might involve this. 

@daniloercoli what are we tracking for sharing on Android?

**Comment by SergioEstevao** [comment]
Just to clarify: at the moment we track all sharing activities events (with a generic event), but we only identify the type (with a specific event type) for the ones support by the system (Facebook, Twitter) and for our custom ones.

**Comment by daniloercoli** [comment]
> @daniloercoli what are we tracking for sharing on Android?

Share to WordPress opens the post editor in Android. 
We're tracking the event `editor_post_created` with the following property:
`created_post_source::= "post-list" | "shared-from-external-app" | "media-library" | "quick-press" | "quick-media"`

**Comment by astralbodies** [comment]
Thanks @daniloercoli - At some point we'll update how we're tracking sharing with the iOS app to match each other. For now we're going to keep the enums the same and just add some fall-throughs to the generic share enum.

**Pull request merged**
