### PR TITLE
[Tooling] Draft: Upload app metrics

### PR DESCRIPTION
**Pull request by AliSoftware**
🚧  This is WIP to test the new App Size Metrics API and fastlane action implemented in https://github.com/wordpress-mobile/release-toolkit/pull/364

Internal Reference: paaHJt-3od-p2

### CODE REVIEW

**Comment by AliSoftware** [comment]
You should now be able to see the generated payloads (`wordpress-app-size-metrics.json`) in the Artifacts tabs of [the Buildkite jobs for Installable Builds](https://buildkite.com/automattic/wordpress-ios/builds/7642#ba16a306-063a-4b78-8987-d0e14390bede)

**Comment by mokagio** [comment]
Switched to use the "Someday" milestone because this hasn't seen activity in a while.

image

**Comment by AliSoftware** [comment]
For reference, I asked for an update on when the server might be deployed (and thus when we could hope circle back on this PR) internally in paaHJt-2Wx-p2#comment-6376

**Comment by twstokes** [comment]
👋 I'm going to close this PR due to lack of activity, but please reopen if this was an error. Thank you.

**Pull request closed without merging**
