### PR TITLE
#13440: Adjusts mobile preview on tablets

### LINKED ISSUE #13440: [GlobalStep] On some tablet devices the lower right preview option lists default and mobile which appear the same.
### Description
When the user loads the app on a larger tablet device, while previewing a post the lower right icon to switch between desktop and mobile views lists ‘Default’ and ‘Mobile’ , when selected there is no visual appearance in the app, it could be that the mobile view on these tablets is also the default but due to the larger native screen it is being treated as desktop by the app.

### Reproduction Rate
4/4 100%

### Expected behavior
Selecting ‘desktop’, ‘mobile’ or ‘default’ switched the appearance of the preview.

### Actual behavior
Selecting any of the available options causes no change the appearance of the app.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Select ‘My sites’.
4. Select ‘View’ on any post.
5. In the lower right select the change view style button.
6. Select ‘Mobile’ then back to ‘Default’.

##### Tested on the following
iPad 6th Gen (11.3.1)
iPad Air 3 (13.2.3)

#### Please see the attached video for more information.
[Tablet_Change_View.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4193480/Tablet_Change_View.zip)

### Submitted by:
Oliver Howe

### PR DESCRIPTION
**Pull request by bjtitus**
Adjusts the web view's actual width to provide Mobile Preview on tablets.

This is different than the Android version (which was already just keeping the same Default + Desktop previews). I originally added the Mobile preview on tablet because iOS 13 is intended to use a more "desktop like" web experience. This is less obvious because the theme designs are responsive and the preview is presented in a popover, taking up a smaller portion of the screen.

The preview in the Calypso editor on the web appears to adjust the iframe width. I think it makes sense to copy that behavior on the mobile clients so it is consistent.

 | Default | Mobile |
|--|--|
| <a href="https://user-images.githubusercontent.com/3250/74798414-efc74580-528a-11ea-9902-6f4b1bfd25d2.png"></a> | <a href="https://user-images.githubusercontent.com/3250/74798425-f5249000-528a-11ea-9804-c1530432470d.png"></a> |

 | Default | Mobile |
|--|--|
| <a href="https://user-images.githubusercontent.com/3250/74798476-14bbb880-528b-11ea-9fda-2364e074f0a0.png"></a> | <a href="https://user-images.githubusercontent.com/3250/74798487-1dac8a00-528b-11ea-83c9-5a81e6b64e19.png"></a> |

Fixes #13440 

To test:

- Open the list of blog posts
- Tap on the View button to open a web preview
- Change the preview style to "Mobile" by tapping the button in the lower right.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by bjtitus** [comment]
@osullivanchris This has some new functionality that may need a look from a design perspective. The typical iPad view is somewhere between Desktop and Mobile and we will need to shrink the actual `webView` to properly show the "mobile" version of most responsive layouts.

Only that center part (i.e. non-black in the dark mode) would be interactive, the side space is non-interactive. This pretty much matches what the web editor's preview does.

**Comment by osullivanchris** [comment]
@bjtitus this looks great! I also pinged @SylvesterWilmott who worked on designs for preview a little while ago and he's happy with it too.

Only thing I can think of is that when I see the dark version the black around the preview actually helps to clarify where the mobile screen ends. I wonder if we could add a light grey background on the light version to add the same clarity? The alternative would be to narrow this whole modal when you switch to a mobile preview. But I know that probably wouldn't work without a different design - as all the actions and everything would be moving when you switch between desktop and mobile which would be weird.

**Comment by bjtitus** [comment]
@osullivanchris Thanks for taking a look! I adjusted the color to a light grey.

#### iOS 13
Simulator Screen Shot - iPad Pro (11-inch) - 2020-02-20 at 10 03 54

#### iOS 13 Dark
Simulator Screen Shot - iPad Pro (11-inch) - 2020-02-20 at 10 04 08

#### iOS 12 Portrait
Simulator Screen Shot - iPad Pro (10 5-inch) - 2020-02-20 at 10 11 22

#### iOS 12 Landscape
Simulator Screen Shot - iPad Pro (10 5-inch) - 2020-02-20 at 10 11 25

**Comment by osullivanchris** [comment]
Looks good @bjtitus ! Thanks for the tweak. Just to make sure its a system grey we're using. Agree to use the lightest one. It only needs a subtle indication

**Pull request merged**
