### PR TITLE
Forcing Notifications refresh

### LINKED ISSUE #6744: Likes are no longer working.
### Expected behavior

Liking a post from the list of notifications should work.

### Actual behavior

It looks like it works, but if you go to that post using your browser you'll find it didnt' really work.  Another way to see it fail is by closing the app and reopening it.  You'll notice the like is gone.

### Steps to reproduce the behavior

Launch the app.  Go to your list of notifications.  Like a post.

/cc @jleandroperez since you're the notifications VC expert.
/cc @rachelmcr to keep you posted.

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
Several Notification Actions are not forcing, backend side, a Notification Document Regeneration. As a result of this, retrieving the remote `[NoteID, Hash]` collection will not correctly indicate us if the notification has been updated.

Bottom line is: performing actions, such as Liking a Comment, **do work**, but upon relaunch, the Notification does not reflect it's actual remote state.

As a workaround, we'll force a Notification Refresh whenever the user perform an action such as `[Like, Unlike, Follow, Unfollow, Update Comment, Reply Comment, Approve Comment, Unapprove Comment]`

Fixes #6744

### To test:
1. Open a Comment-Y Notification
2. Try the following actions:
    `[Like, Unlike, Follow, Unfollow, Update Comment, Reply Comment, Approve Comment, Unapprove Comment]`
3. Kill the app
4. Relaunch
5. Verify that after the Notifications List gets reloaded, the updated notification looks as expected

Needs Review: @koke 
Thanks for reporting this @diegoreymendez!!

### CODE REVIEW

**Comment by jleandroperez** [comment]
@koke let's do this right! Cache Invalidation mechanism in place. Mind taking a second look?

@diegoreymendez thanks for the suggestion! link to the original issue added. Thanks!

:bowtie:

**Comment by koke** [comment]
I also tested #6885 as part of this, and when you reply to a comment, the "You replied to this comment" doesn't appear until you go back to the list and the note refreshes. For the reply case, perhaps we should force sync the note, or at least modify it manually?

**Comment by jleandroperez** [comment]
@koke Invalidating **AND** Force Sync'ing now. Ready for another look, nice catch!

**Comment by koke** [comment]
Perfect, and confirmed that it fixes #6885

**Comment by jleandroperez** [comment]
Thank you sir!

**Pull request merged**
