### PR TITLE
Update tag sanitization to match core

### LINKED ISSUE #2964: Update tag sanitization logic to match core.
When a user enters a tag to subscribe, make sure that we sanitize the text to match core WordPress. 
See https://github.com/WordPress/WordPress/blob/master/wp-includes/formatting.php#L1258

### PR DESCRIPTION
**Pull request by aerych**
Closes #2964

### CODE REVIEW

**Comment by aerych** [comment]
cc @sendhil for review, s'il te plait.

**Comment by sendhil** [comment]
Hey @aerych  - this is kind of a dumb edge case, but I found one when comparing the WordPress function you referenced in #2964 and the code in the iOS app.

Here's the input/output for the WordPress function:
wordpress function

Here's the input/output for the iOS method:
ios method

TL;DR maybe adjust https://github.com/wordpress-mobile/WordPress-iOS/pull/3036/files#diff-973f681ed5f4154fbc9a23b3b7cfa6e3R172 to take any successive dashes greater than one and replace them with just one dash?

**Comment by sendhil** [comment]
Oh.. for reference I stripped out this blurb from the PHP code when running in Coderunner as it didn't have the function easily referenced and I didn't think it really would adjust the output:
```php
	if (seems_utf8($title)) {
		if (function_exists('mb_strtolower')) {
			$title = mb_strtolower($title, 'UTF-8');
		}
		$title = utf8_uri_encode($title, 200);
	}
```

**Comment by aerych** [comment]
Good catch about the dashes! Will update.

**Comment by aerych** [comment]
@sendhil ready for take two

**Comment by sendhil** [comment]
Looks good.

**Comment by sendhil** [comment]
@aerych can you update this so it can be merged properly?

**Pull request merged**
