### PR TITLE
My Site Dashboard: Hide Quick Actions cell for Jetpack App

### PR DESCRIPTION
**Pull request by momo-ozawa**
## Description

- Fixed an issue where the Quick Actions cell (introduced in [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/17812)) was being shown for the Jetpack app, even though the cell shouldn't be displayed
- Deleted some obsolete files and code in BlogDetailsVC related to the headerView

Before | After
-- | --
 | 

## Notes
- FYI @pachlava -- pinging you since this is a MSD related bug

## How to test
1. Build and run the Jetpack app
2. Log in
3. Go to My Site
4. ✅ The Quick Actions cell should not be displayed

## Regression Notes
1. Potential unintended areas of impact
Quick Actions cell

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested the above steps manually (both Jetpack and WordPress)

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by leandroalonso — APPROVED** [review]

**Comment by momo-ozawa** [comment]
Hi @mokagio 👋 
JFYI we're targeting 19.2 for this fix -- thanks!

**Comment by mokagio** [comment]
@momo-ozawa thank you for the ping!

I am waiting on some additional work to land on the release branch before releasing a new beta.

Is that okay with you? Cc @tiagomar 

If you want to send this out ASAP instead, I can do it no problems. No stress.

**Comment by momo-ozawa** [comment]
> If you want to send this out ASAP instead, I can do it no problems. No stress.

@mokagio I'd actually prefer a new beta with this fix ASAP 🙇‍♀️

**Comment by mokagio** [comment]
@momo-ozawa  this has been bundled as part of [19.2 beta 1 (19.2.0.1)](https://github.com/wordpress-mobile/WordPress-iOS/pull/17918).

Thanks for your work 🙌

**Pull request merged**
