### PR TITLE
Issue/9856 make active plan optional

### LINKED ISSUE #9856: Plans Page Sometimes Doesn't Load
I have seen a handful of questions over the last month or two where users are going to the Plans section of the app, and they are coming across an error message instead.  This has been happening infrequently enough that I have not been able to figure out what links the issues, but I have seen it a handful of times. 
What I have noticed so far is that this problem seems to be only iOS, and happens to WPCOM users.  When the WPCOM users go to My Site > Plans they see this page 

The most recent issue I came across with this problem was 1300122-zd-woothemes
The user was using WordPress 10.4.1
iOS 11.4.1
and had a premium plan on their site.

I first brought this up here p4a5px-2eR-p2 and @ScoutHarris found in the logs that noActivePlan is coming up in the logs when the user visits that page, which is causing the error, but we couldn't figure out why the user was showing up as having no plan.

I don't have a to replicate, cause I can't replicate it...  With previous issues I have had users reinstall the app, and reconnect, but that did not fix the problem.

### PR DESCRIPTION
**Pull request by aerych**
Fixes #9856 

This PR makes it optional for the user's currently active plan to be one of the plans returned from the `v1.2/sites/site/plans` endpoint.  This allows the plans feature to continue showing the four default plans instead of an error message prompting the user to contact support.  This matches the behavior in the wpandroid.

To test:
You want a site with a Jetpack or two year plan.  DM me and I help get you set up.
View MySites > Site > Plans and confirm that you see the four default plans.

Waiting for an update to the WordPressKit pod.  @ctarda and I both have PRs to bump to 1.4.1-beta.2 so once his lands I'll update this branch and update/remove the status labels.

After the patch:
simulator screen shot - iphone 8 - 2018-10-04 at 11 46 19

### CODE REVIEW

**Comment by aerych** [comment]
Looks like we'll need to wait til we're done migrating to Swift 4.2 and Xcode 10 for this one to be ready.

**Comment by aerych** [comment]
@ctarda could I trouble you with a review of this one?

**Comment by ctarda** [comment]
The code diff is 💯  and it works as expected (to the left, the app in production, to the right, this branch)

comparison

:shipit:

**Comment by aerych** [comment]
Thank you sir!!

**Pull request merged**
