### PR TITLE
Quick Start v2: Update completion logic

### PR DESCRIPTION
**Pull request by nheagy**
Refs #10860

For QS v2 the completion logic must consider both lists. Furthermore, both lists should still be displayed even when both lists are complete.

screen shot 2019-02-07 at 10 25 47 pm

Note: until the `ellipsis` menu is implemented, quick start checklists will always be visible in v2.

To test:
- create a new site (otherwise the 'create a site' item won't appear) **OR** open a site that previously started (or completed) quick start
- ensure that the checklists appear correctly when completed
- ensure both lists remain when all tours have been completed

### CODE REVIEW

**Comment by sirisak1985** [comment]
good

**Comment by loremattei** [comment]
I'm moving this to 11.9 since 11.8 has been cut. If you want it in 11.8, please feel free to target the release branch and to ping me to build a new beta.

**Comment by sirisak1985** [comment]
support me

**Comment by SylvesterWilmott** [comment]
Hey! This is looking good

I've noticed a couple of issues here:

- The space between the site title block and the quick start table heading should be 0

screenshot 2019-02-13 at 16 09 14

- The title `Quick Start` should be `Next Steps`


Regarding the ellipsis icon inside the table heading, we can recycle the table heading that is used in Stats Refresh which is essentially the same component (without an icon).

**Comment by nheagy** [comment]
@SylvesterWilmott I've created #11041 to address the gap, and changed the title in #11028

**Comment by nheagy** [comment]
Thanks, @danielebogo (and @loremattei)!

**Pull request merged**
