### PR TITLE
Transitioned Period Chart to use live data

### LINKED ISSUE #11069: [Stats Refresh] Adapt DWMY Charts to leverage persisted data
In general, we will be transitioning the [DWMY charts](https://github.com/wordpress-mobile/WordPress-iOS/issues/11063) from using stubbed data to use real data, vended by the persistence layer @jklausa is working on.

### PR DESCRIPTION
**Pull request by stevebaranski**
### Description
Fixes #11069.

To test:

- Checkout the branch & confirm that existing tests pass.
- Navigate to Stats for a given site and select a period in the filter bar (e.g., Days, Weeks, Months, Years).
- Observe that the chart now reflects live data, and updates when you select (by tapping) a dimension like Views, Visitors, Likes, or Comments.
- Rinse & repeat for a couple of different device types & orientations.
- Please keep in mind the caveats below. I've included some screenshots as well, but there should be no real aesthetic difference from #11210.

Update release notes:

- [X] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### Notes

- The charts in the screenshots below include 10 bars; I think this can be attributed to [this default value](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/develop/WordPressKit/StatsServiceRemoteV2.swift#L198). I intend to fix this as part of #11671. We might find that a change to `WordPressKit` is in order, but I'm hoping we can just specify a non-default value [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Stores/StatsPeriodStore.swift#L307).
- The chart does not currently update or really interact in any way with the Date bar. This will also be accounted for via #11671.
- You might wonder why we pass arrays of `BarChartDataConvertible` to the `PeriodChart` in `SiteStatsPeriodViewModel`. This accommodates the filter bar instance for Views, Visitors, Likes & Comments that resides in our `OverviewCell`. That is to say, a `FilterTabBar` selection essentially changes our data source index.
- On the bright side, no changes were made in this PR (or #11605 or #11616)  to `StatsBarChartView`. That suggests that we probably got the abstractions right.
- Peril has expressed a concern about the LOC changed, but a fair bit of the changes in this PR are deletions.

_iPhone XS Max (Portrait):_
11069a

_iPhone XS Max (Landscape):_
11069b

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @stevebaranski . 

The chart is looking great! 🎉 

The only thing I noticed is the numbers on the y-axis are duplicated. This is from en.blog, which has a lot of data:

ios_chart

Comparing that with Android:

android_chart

**Comment by stevebaranski** [comment]
Thanks @ScoutHarris - thanks for the review, and for surfacing that issue. I guess you could say the PR review process works! 😂  

That's certainly not what our users deserve to see. I think this _might_ be a regression introduced via #11143, but I will investigate more thoroughly & report back once a fix is worth your time. 😄

**Comment by stevebaranski** [comment]
@ScoutHarris as discussed in `p1557761654009100-slack-nde-stats-refresh`, Zeplin comps depicted axes without decimals, and accounts for the as-built discrepancy.

That said, you rightly noted a case where the lack of a decimal falls down a bit. This is also evident on sites with little traffic (i.e., single-digit counts).

I examined the [Android implementation](https://github.com/wordpress-mobile/WordPress-Android/blob/fa4f422c863a521675782a7f5ef053e8a202b395/WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt#L95), and observed that it uses a formatter that is included with the [`MPAndroidChart`](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/formatter/LargeValueFormatter.java) framework.

The iOS framework (i.e., `Charts`) includes a [similar](https://github.com/danielgindi/Charts/blob/0d33db4da87a549abb8d517d71ac2c36ecd731a5/ChartsDemo-iOS/Swift/Formatters/LargeValueFormatter.swift) formatter, but it does not appear to be part of the pod, nor is it as well-documented.

I pushed an additional commit that uses that formatter, and applies a few minor chart configuration changes to account for different data sets. Hopefully you'll agree that this an improvement. 😄 

11672b-3

cc: @SylvesterWilmott

**Comment by ScoutHarris** [comment]
Hey @stevebaranski . It is indeed better! Thank you.

Unfortunately, there is now one minor visual glitch. There is now basically no spacing between the `Visitors` label and the top of the chart.

yaxis_spacing

**Comment by stevebaranski** [comment]
Good catch @ScoutHarris. I double-checked the dimension in Zeplin, and I think it looks better now with the additional commit.

11672b-4

Hopefully you agree. 😄

**Comment by stevebaranski** [comment]
Thanks again @ScoutHarris!

**Comment by SylvesterWilmott** [comment]
Hey @stevebaranski 

Do we need to show decimals on full numbers too? 

I can see numbers like `993.3` or `860.6`. The decimals should only be applied to shortened numbers like `4.2k`

Can we also limit the number of values on the Y axis to 5 (including the 0)?

**Comment by stevebaranski** [comment]
👋 @SylvesterWilmott

> Do we need to show decimals on full numbers too?

This is a consequence of transitioning to use the value formatter that comes with the Charts framework for all values. Making this change has the following benefits:

- It is more consistent with the Android implementation.
- In my testing, having a decimal was more consistent across a broad range of actual data. For example, in the comment [above](https://github.com/wordpress-mobile/WordPress-iOS/pull/11672#issuecomment-491901057), I noted that the presence of the decimal was useful for sites with low traffic (i.e., smaller counts). That is to say, _not_ having the decimal resulted in multiple axis entries where single digits were repeated.

Once all of the Chart functionality is in place, I'd like to revisit this to see if we can do better - honoring the intent you stated. Is that okay?

> Can we also limit the number of values on the Y axis to 5 (including the 0)?

Absolutely. The current behavior is based on what I saw in Zeplin, but it is a [one line](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift#L249) change.

**Pull request merged**
