### PR TITLE
Fix mime type sent to server when uploading video media.

### LINKED ISSUE #5326: Wrong file type being sent to xmlrpc.php when uploading videos
When uploading a video, XML sent to the xmlrpc.php file includes a wrong type.
The video was recorded on the device.

### Expected behavior

File type should be set appropriately upon upload ("video/quicktime" for .mov videos).

When the uploaded file is viewed in the admin page on the web, in the Media Library, its File type should be "video/quicktime".

### Actual behavior
File type is set to image/jpeg in the XML.

Also, this file type is visible in the Media Library when viewed in the admin page of the blog.

### Steps to reproduce the behavior

Record a video on the device.
Create new post (empty or otherwise).
Upload the video.

### Additional info

This is happening on a self-hosted Wordpress, 4.5.2.

I logged the raw XML by hacking my xmlrpc.php, adding this snippet ...
```php
$ts = time();
$raw_post = file_get_contents("php://input");
file_put_contents("/tmp/php/".$ts.".log", $raw_post);
```

This is the XML the app sent...
```xml
<?xml version="1.0"?>
<methodCall>
    <methodName>wp.uploadFile</methodName>
    <params>
        <param>
            <value>
                <i4>0</i4>
            </value>
        </param>
        <param>
            <value>
                <string>MY_EMAIL_HERE</string>
            </value>
        </param>
        <param>
            <value>
                <string>MY_PASSWORD_HERE</string>
            </value>
        </param>
        <param>
            <value>
                <struct>
                    <member>
                        <name>name</name>
                        <value>
                            <string>img_0887-3.mov</string>
                        </value>
                    </member>
                    <member>
                        <name>type</name>
                        <value>
                            <string>image/jpeg</string>
                        </value>
                    </member>
                    <member>
                        <name>bits</name>
                        <value>
                            <base64>BASE64_STUFF_HERE</base64>
                        </value>
                    </member>
                </struct>
            </value>
        </param>
    </params>
</methodCall>
```
This is a especially an issue when using a plugin which depends on the file type being set correctly, namely something like this...
https://wordpress.org/plugins/video-embed-thumbnail-generator/screenshots/

##### Tested on an iPhone 5s, iOS 9.3.1 (13E238), WPiOS 6.1

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #5326 

To test:
 - On a self hosted site
 - Create a new post and add a device video to the post.
 - Save the post
 - Check the media type on the web server and see if it's the correct one.

Needs review: @aerych

### CODE REVIEW

**Comment by peachkovit** [comment]
For what it's worth, I'm available to test if I get the TestFlight access. I already signed up, but haven't received anything yet.

**Comment by aerych** [comment]
Worked great when tested.  :shipit: !!!

**Comment by SergioEstevao** [comment]
@peachkovit thanks for the report, we added the latest users that registered to the TestFlight account. So when you receive a 6.3 release for test this fix should be there.

**Comment by peachkovit** [comment]
Got the TestFlight mail and am eagerly awaiting 6.3 landing for test. Thanks for the quick fix.

**Pull request merged**
