### PR TITLE
Notifications: Badge Scrolling

### LINKED ISSUE #5781: NotificationDetails: iPhone 4s + Badges
As pointed out in #5737 by @kurzee, we've got a spacing / layout problem with Badge Notifications, on 3.5 screens.

Thanks for catching this one Brent!

ef001044-4da9-11e6-84d8-6c19aaa2cca7

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes #5781

### To test:
1. Launch the app in a 4s device
2. Open a Badge notification
3. Rotate the device into Landscape mode
4. Verify that vertical scrolling is enabled (if there's actual overflow!)

Please: also verify that regular notifications (non badge ones!) always have vertical scrolling enabled.

Needs review: @kurzee 

Brent, you game for a hopefully fun review?
Thanks a lot in advance!!

### CODE REVIEW

**Comment by kurzee** [comment]
@jleandroperez I wonder if we might add just a bit more padding to the bottom? Kind of dances on that bottom edge. No big deal though.

simulator screen shot dec 1 2016 1 29 05 pm

**Comment by jleandroperez** [comment]
@kurzee since the content is 100% dynamic, and scrolling is enabled only if it doesn't fit the screen, i'd really rather avoiding paddings. (The only scenario in which this happens is always 4s, landscape, other devices should never, not ever get this UX).

Thanks Brent!!!

**Comment by kurzee** [comment]
>since the content is 100% dynamic, and scrolling is enabled only if it doesn't fit the screen, i'd really rather avoiding paddings.

Makes sense!

The only other thing I might suggest changing is trying to avoiding activating and deactivating constraints. Seems a bit redundant to have to two different top and bottom constraints and _seems_ like it would be cleaner to just modify the same top and bottom constraints. No biggie though, your call!

:shipit:

**Comment by kurzee** [comment]
Also, if you want `6.8`, you'll need to retarget.

**Comment by jleandroperez** [comment]
Reason why we've got two Top / Bottom constraints is: you can't change the relationship, dynamically (`>= 0` vs `= 0`). Tried going that way... but... hit that brickwall along the way.

Thought develop was 6.8, updating that (since it's low prio, no need to retarget).

Thanks a lot for the review @kurzee, as ever!!

**Pull request merged**
