### PR TITLE
Aztec : Append line separators when linking to attachments

### LINKED ISSUE #9293: Aztec: inserting multiple documents with doc picker results in an awkward layout with no spaces between links
### Expected behavior

After inserting multiple documents at once, I expected links to documents to be on separate lines or have spaces between each one.

### Actual behavior

Links to documents are in one line with no spaces if you insert multiple documents at a time.

### Steps to reproduce the behavior

1. Go to My Sites > Blog Posts > +.
1. Go to "Add Media" > {ellipsis menu} > Other Apps in the editor toolbar.
1. Select Locations > iCloud Drive and tap "Select."
1. Select multiple documents and then tap "Open."
1. Check to see if the formatting of the links that were inserted appear as expected.

Result: the links have no spaces or line breaks between them.

### PR DESCRIPTION
**Pull request by a8c-sab-trial**
Fixes #9293, which noted an improvement opportunity where adding multiple documents could benefit from adding line separators.

To test:

- Manually test by adding multiple attachments and confirming that the formatting is preserved when toggling between editing modes.
- Review code and evaluate attached screenshots.

9293_rich-before-and-after
9293_html

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@a8c-sab-trial - Since this PR touches code inside `CalypsoProcessorIn.swift` and `CalypsoProcessorOut.swift` (both of which are classes that contain very important and hard to maintain code) I'll need us to pause a bit before moving forward.

Could you provide information as to what made those changes necessary?

Or alternatively, can you provide me steps to see the issue if I roll back those changes locally?

**Comment by a8c-sab-trial** [comment]
@diegoreymendez I recognize the importance of the code that's being changed, and appreciate the extra scrutiny.

When I first implemented [this](https://github.com/wordpress-mobile/WordPress-iOS/pull/9307/files#diff-705f087506da53949ae67cbac0ed8d98R2918), I was using `.lineSeparator` rather than `.carriageReturn`. When testing with this change, I observed that the `br` tags were inserted, but were stripped out by these Calypso processors when toggling between _Visual_ & _HTML_ mode, then back again.

I have tested locally with `.carriageReturn` but without the changes to `CalypsoProcessorIn` & `CalypsoProcessorOut`, respectively. I can corroborate your findings.

I will amend the PR to revert the changes to those two files. I appreciate the extra scrutiny here.

**Comment by a8c-sab-trial** [comment]
@diegoreymendez I have pushed an additional commit that reverts the Calypso changes. 

@frosty now that the changes are limited to `DocumentUploadProcessor` & `AztecPostViewController`, would you or @SergioEstevao be able to take a look?

**Comment by SergioEstevao** [comment]
Just wanted to confirm the expected behaviour and yes I agree with you not
easy to implement with our current solution. Let's just :shipit: for now
and then we can see the feedback from it.
On Wed, 9 May 2018 at 09:23, James Frost <notifications@github.com> wrote:

> @SergioEstevao I think that would be the ideal behaviour. I'm not sure of
an easy way to accomplish this in the DocumentProcessor though?

**Pull request merged**
