### PR TITLE
SharingServiceRemote: Crash Failsafe

### LINKED ISSUE #7102: Crash: SharingServiceRemote.swift line 374
```
Crashed: com.apple.main-thread
0  WordPress                      0x1002e3d28 specialized SharingServiceRemote.remotePublicizeConnectionFromDictionary(NSDictionary) -> RemotePublicizeConnection? (SharingServiceRemote.swift:374)
1  WordPress                      0x1002e4370 specialized SharingServiceRemote.(getPublicizeConnections(NSNumber, success : ([RemotePublicizeConnection]) -> ()?, failure : (NSError?) -> ()?) -> ()).(closure #1) (SharingServiceRemote.swift)
2  WordPress                      0x1002dbaf4 SharingServiceRemote.(getKeyringConnections(([KeyringConnection]) -> ()?, failure : (NSError?) -> ()?) -> ()).(closure #1) + 4298275572
3  WordPress                      0x1002e8b38 partial apply for SharingServiceRemote.(getPublicizeConnections(NSNumber, success : ([RemotePublicizeConnection]) -> ()?, failure : (NSError?) -> ()?) -> ()).(closure #1) + 4298328888
4  WordPress                      0x1005037b0 specialized WordPressComRestApi.(GET(String, parameters : [String : AnyObject]?, success : (AnyObject, HTTPURLResponse?) -> (), failure : (NSError, HTTPURLResponse?) -> ()) -> Progress?).(closure #2) (WordPressComRestApi.swift:121)
5  WordPress                      0x100504d8c partial apply for WordPressComRestApi.(GET(String, parameters : [String : AnyObject]?, success : (AnyObject, HTTPURLResponse?) -> (), failure : (NSError, HTTPURLResponse?) -> ()) -> Progress?).(closure #2) (WordPressComRestApi.swift)
6  WordPress                      0x1004fd138 thunk (WordPressComRestApi.swift)
7  AFNetworking                   0x100a4e88c __116-[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:]_block_invoke.80 (AFHTTPSessionManager.m:290)
8  AFNetworking                   0x100a61788 __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.150 (AFURLSessionManager.m:308)
9  libdispatch.dylib              0x1862069e0 _dispatch_call_block_and_release + 24
10 libdispatch.dylib              0x1862069a0 _dispatch_client_callout + 16
11 libdispatch.dylib              0x18620b3c0 _dispatch_main_queue_callback_4CF + 444
12 CoreFoundation                 0x1872fd0c0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
13 CoreFoundation                 0x1872facdc __CFRunLoopRun + 1572
14 CoreFoundation                 0x18722ad94 CFRunLoopRunSpecific + 424
15 GraphicsServices               0x188c94074 GSEventRunModal + 100
16 UIKit                          0x18d4e3130 UIApplicationMain + 208
17 WordPress                      0x100046804 main (main.m:5)
18 libdyld.dylib                  0x18623959c start + 4
```

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
Although i've been unable to reproduce this crash, i'm adding a couple `guard let` in the spot that, according to the crashlog, the app was crashing.

Closes #7102

### Testing:
Please, run a smoke test over Publicize, and make sure nothing breaks.

Needs review: @aerych 
Eric, may i bug you with this one?

### CODE REVIEW

**Comment by jleandroperez** [comment]
As discussed with @elibud, i've updated this PR so that the `connectionID` is the only "mandatory" field in the parser.

Thanks Elisa!

**Comment by jleandroperez** [comment]
Hey there @aerych!!

**RemotePublicizeConnection** already has a default **dateIssued** value [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Networking/Remote%20Objects/RemotePublicizeConnection.swift#L5), so i _think_ we should be good.

**Comment by aerych** [comment]
Whoops!  I overlooked that. 
In that case :shipit: when ready :)

**Comment by jleandroperez** [comment]
Thanks a lot for the review sir!!

**Pull request merged**
