### PR TITLE
AB testing: update how experiments are assigned

### PR DESCRIPTION
**Pull request by leandroalonso**
This PR updates how experiments are assigned.

### To test

First, add a breakpoint in `ExPlatService.swift:76`.

#### No experiments

1. Run the app
2. Put the app in the background
3. Put the app in the foreground
4. Make sure the breakpoint is never hit

#### Adding experiments

Add these experiments into `ABTest.swift`:

```swift
    case mock = "explat_test_ios_mock_experiment_1"
    case mock2 = "explat_test_ios_mock_experiment_2"
```

1. Run the app
2. The breakpoint should be hit
3. Put the app into the background and wait 1 minute (the `tll` time)
4. Put the app in the foreground
5. The breakpoint should be hit
6. Put into the background and then foreground
7. The breakpoint should not be hit

## Regression Notes
1. Potential unintended areas of impact
N/a.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/a.

3. What automated tests I added (or what prevented me from doing so)
They were added to the library's PR (https://github.com/Automattic/Automattic-Tracks-iOS/pull/178)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by momo-ozawa — COMMENTED** [review]
I tried testing the Adding Experiments section several times, but I wasn't able to verify step 5... I never hit the breakpoint.

**Comment by leandroalonso** [comment]
@momo-ozawa Are you logged in?

**Comment by leandroalonso** [comment]
@momo-ozawa Are you logged in?

**Review by momo-ozawa — APPROVED** [review]
Yep, logged in! Tried again and waited well past the ttl for good measure ... and it works as described! 

Sorry about the confusion, LGTM!

**Pull request merged**
