### PR TITLE
Declare WordPressClient as class instead of actor

### PR DESCRIPTION
**Pull request by crazytonyli**
WordPressClient has immutable stored properties, and does not have to be an actor.

This change gets rid of a few warnings.

> Non-sendable type 'WordPressAPI' in implicitly asynchronous access to
> actor-isolated property 'api' cannot cross actor boundary; this is an error
> in the Swift 6 language mode

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/303">25.6</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jkmassel** [comment]
I had originally made this an actor type because there should be one for each site, and it should be passed down the view hierarchy. If there's an issue that requires reauthentication, if helps if we can guarantee that no other requests are being attempted while we deal with that.

WDYT?

**Comment by crazytonyli** [comment]
@jkmassel That all make total sense to me. After the re-authentication thing is implemented, `api` will become a mutable property, and we have to declare the type as an actor.

What do you think about making it a plain class for now, and changing to an actor after re-authentication (or anything that requires `WordPressClient` to be an actor) is implemented? That'll save us from using `await client.api.xxx`  unnecessarily, which is the syntax the compiler thinks we should use.

**Comment by jkmassel** [comment]
> That'll save us from using await client.api.xxx unnecessarily, which is the syntax the compiler thinks we should use

IMHO that's a feature, just because we'll likely need it in the future anyway – keeping it an actor for now avoids needing to propagate a bunch of `async` stuff throughout the app later if it changes?

**Comment by crazytonyli** [comment]
@jkmassel Sounds good. I'll keep it as it is then.

**Pull request closed without merging**
