### PR TITLE
Update Posts to Gridicons

### PR DESCRIPTION
**Pull request by mattmiklic**
Updates all icons in the Posts section to Gridicons.

The following icons have been updated to Gridicons. Each is provided as a single vector PDF.

- icon-clock
- icon-nav-chevron-highlight
- icon-nav-chevron
- icon-post-actionbar-back
- icon-post-actionbar-edit
- icon-post-actionbar-more
- icon-post-actionbar-publish
- icon-post-actionbar-restore
- icon-post-actionbar-stats
- icon-post-actionbar-trash
- icon-post-actionbar-view
- icon-post-add-highlight
- icon-post-add
- icon-post-list-footer
- icon-post-list-search
- icon-post-search-highlight
- icon-post-search
- icon-post-undo
- icon-postmeta-comment
- icon-postmeta-like
- post-blavatar-placeholder

The following icon was added. The searchfield previously used the standard gray textfield clear icon, which clashed with the search field's blue background.

- icon-clear-searchfield

The following icons were unused and have been removed:

- icon-navbar-dropdown
- icon-postmeta-comment-selected
- icon-postmeta-like-selected
- icon-posts-add

Insets have been added to all postmeta icons (except More and Back). Because gridicons are on a consistent grid, we don't need separate insets for every image. If there is a better/more concise way to apply the same insets to all icons in PostCardTableViewCell.m, please let me know.

Post status icons have not been changed, as they are <a href="https://github.com/Automattic/wp-calypso/pull/2338">still in flux</a> in Calypso.

Before:
before

After:
after

### CODE REVIEW

**Comment by mattmiklic** [comment]
Updated the PR with cleaner screenshots.

**Comment by kwonye** [comment]
```
The following icons were unused and have been removed:

* icon-navbar-dropdown
```

I see `icon-navbar-dropdown` being used in https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m

**Comment by mattmiklic** [comment]
> I see icon-navbar-dropdown being used in https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m

Whoops, not sure how I missed that one. Thanks for catching; I've restored the original icon (will update it as I'm working on the Editor section).

**Comment by kwonye** [comment]
:shipit:

**Pull request merged**
