### PR TITLE
Notifications: Nukes Follow Action

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:
As discussed, let's nuke the User's row *Follow* action.

#### To test:
1. Log into a dotcom account 
2. Open a Like / Follow notification

Please, verify that each of the user's cells don't display a **Follow** button anymore.

Needs review: @kwonye 
Will, can i bug you with yet another review?

Thanks in advance!!

cc @roundhill

### CODE REVIEW

**Comment by roundhill** [comment]
> there are about 900 unique clicks of "follow" every day

I wish we could tell how many of those were accidental. I brought up the idea to remove it to @jleandroperez because I keep accidentally tapping on it.

Can we get a count of how many times the follow button in the reader detail view is tapped? If we think we should keep this button, I'd vote to make it way bigger and more obvious, like with a blue background or something.

**Comment by jleandroperez** [comment]
Invoking the master of it all... @drw158 

What do you think Dave? should we, perhaps, change the asset to look more prominently like a button?

(Dan: I owe you the Reader stats, gotta step away for a little bit!)

**Comment by drw158** [comment]
Button aligned on the right would be better. Remove the disclosure icon, but keep the same tap functionality on the table cell (it goes to the user's site, I think?).

Mockup incoming...

**Comment by drw158** [comment]
Here we go:

artboard

Notice the new text spacing and gray color instead of blue.

Those changes will align it more with this Reader screen:

artboard

Although we have new icons for Follow and Following, so those should be updated:

screen shot 2016-09-28 at 3 01 36 pm

**Comment by aerych** [comment]
What @drw158 said.  We have new follow icons courtesy of @jancavan for the reader too, so those will also get updated (eventually).

**Comment by jleandroperez** [comment]
@drw158 hooow about... if the user wants to tap over the row, to access the user's site (instead of following him?)

**Comment by drw158** [comment]
Not sure how it would work it code... but taping on the whole row (minus the follow button) should go to the user's site.

**Comment by jleandroperez** [comment]
@drw158 code is super easy, just checking the behavior. I'll get back to this in a couple weeks, got assigned 100% to the new Native Editor project, for a full sprint.

Thanks for the input Dave!!

**Comment by jleandroperez** [comment]
Closing this PR, since it's no longer relevant. UI changes promoted to Issue #6025.

Thanks everyone!

**Pull request closed without merging**
