### PR TITLE
[Stats Refresh] Add Period > Overview card

### LINKED ISSUE #11192: [Stats Refresh] Add Period > Overview card
Add Period Overview card with just the data, with a temporary view for the chart to be added in the future.

Design:
dwmy_overview

dwmy

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #11192 

This adds the Period Overview card. The data is fake for now, but the functionality can still be seen. Also, there is a temporary view for the chart area.

To test:

- Go to Stats > Period. 
- The hero value and label matches the tab selected.
- Selecting different tabs will update the hero value and label, and the difference value.
- The hero value is abbreviated after 99,999.
- The difference value and difference percent are abbreviated after 9,999.
- If the difference is negative, the text is red. If positive, green.

one

two

three

four

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@SylvesterWilmott  - 

---
one

---
two

---
three

---
four

**Comment by stevebaranski** [comment]
Hi @ScoutHarris - this is looking pretty good to me. I noticed a little bit of wrapping on an iPhone SE (please see below).
11204_pr

I think it might be better to resolve this kind of issue once we incorporate real data via #11205. What do you think?

**Comment by SylvesterWilmott** [comment]
This looks good @ScoutHarris 

I don't want to comment to much on the design until we have the chart in there.

Regarding the tabs along the bottom though, is it possible to have a layout where each tab only occupies as much space as it needs and having them evenly spaced within the bar, this should help with the issue on iPHone SE that @stevebaranski pointed out. For example:

screenshot 2019-03-07 at 08 50 11

**Comment by ScoutHarris** [comment]
@SylvesterWilmott  - Thank you for that diagram. I clearly was confused as to how the tab bar was meant to be sized. Sadly, I had it that way at one point and thought it was wrong. 🤦‍♂️ But alas, it shall be corrected!

**Comment by ScoutHarris** [comment]
@stevebaranski , @SylvesterWilmott - I updated the tab bar so the sizing is now as designed. However, it now looks worse on smaller devices. @SylvesterWilmott suggested some modifications that Android used to resolve this issue. I'll create another PR for that.

**Pull request merged**
