### PR TITLE
Stats Revamp: Updated cell appearance for Insights

### PR DESCRIPTION
**Pull request by frosty**
Implements #18236. This PR implements a new appearance for all cells within the Insights view in Stats. The key components are:

- A new in-cell title, removing the existing section header rows
- An 'inset grouped' table style with inset edges and rounded corners on cells

**Known issues / areas still to complete**

- The animation when switching tabs in tabbed cells like Comments and Followers isn't ideal
- This PR doesn't handle loading or error states for cells
- The 'no data yet' appearance for cells isn't updated 

These will be addressed in a future PR.
There also appear to be a few small issues with text not fitting in cells now we have a smaller width. We'll have to investigate decreasing font sizes in some places.

Here are some examples of before and afters of this cell style:

| Before | After |
| --- | --- |
| Simulator Screen Shot - iPhone 13 Pro - 2022-04-06 at 17 13 10 | Simulator Screen Shot - iPhone 13 Pro - 2022-04-06 at 16 01 21 |
| Simulator Screen Shot - iPhone 13 Pro - 2022-04-06 at 17 13 13 | Simulator Screen Shot - iPhone 13 Pro - 2022-04-06 at 16 02 32 |
| Simulator Screen Shot - iPhone 13 Pro - 2022-04-06 at 17 13 16 | Simulator Screen Shot - iPhone 13 Pro - 2022-04-06 at 16 02 56 |
| Simulator Screen Shot - iPhone 13 Pro - 2022-04-06 at 17 13 19 | Simulator Screen Shot - iPhone 13 Pro - 2022-04-06 at 16 32 47 |

#### Existing appearance

By default the feature flag for these changes is off, so we'll verify that the Insights cards and sunscreens look as they currently do.

- Build and run. 
- Navigate to Stats > Insights for a site and enable all Stats cards.
- When stats have loaded verify that the cells look as they currently do in the shipping app. Also navigate into subscreens from any cards that have a 'view more' option at the bottom and check these look as expected.

#### New appearance

- Enable the `statsNewAppearance` feature flag and build and run again.
- Perform the same steps as above, but ensure that all cards have the new appearance, including a title and inset rounded edges.
- Also navigate into subscreens and ensure those look as they did in the previous version.macos

#### Period stats

- Finally, with the feature flag both enabled and disabled, verify that the Period views in the app still use the old appearance.

## Regression Notes
1. Potential unintended areas of impact

Insights with the feature flag disabled, and cards within 

2. What I did to test those areas of impact (or what existing automated tests I relied on)

I manually verified the appearance of stats cards in Insights and Period stats both with these changes active and without.

3. What automated tests I added (or what prevented me from doing so)4. 

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by frosty** [comment]
Converting to draft as something seems to have gone wrong with the merge with trunk. Will resolve and re-ping for a review!

**Comment by frosty** [comment]
Okay, should be fixed now!

**Comment by mokagio** [comment]
@frosty  I'm going to bump this to the next release because we'll be code freezing 19.7 in a few hours and this hasn't been reviewed yet and it has the "[Status] Not Ready for Review" label.

If this cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.

**Comment by sla8c** [comment]
Hey @frosty so far this is looking good!  Just one issue I ran into with a title with "No data yet".  I used site = wpmobile2.wordpress.com to test and Publicize had a title on current app store / production but not with FeatureFlag enabled.  2x screenshots to help
1. PR code / FeatureFlag enabled without Publicize title
image

2. Current AppStore / prod version with Publicize title
image

**Comment by frosty** [comment]
Thanks for the review, @sla8c! This is a known issue, and will be addressed in a follow-up PR:

> The 'no data yet' appearance for cells isn't updated

**Comment by sla8c** [comment]
> Thanks for the review, @sla8c! This is a known issue, and will be addressed in a follow-up PR:
> 
> > The 'no data yet' appearance for cells isn't updated

Hey James.  sorry I didn't put the two together while sipping coffee early this morning but that makes sense! Thanks :)

**Review by sla8c — APPROVED** [review]
LGTM!

**Pull request merged**
