### PR TITLE
[Gutenberg] - PR 03 - Adding `UserDefaults` to Environment

### PR DESCRIPTION
**Pull request by etoledom**
On https://github.com/wordpress-mobile/WordPress-iOS/pull/12189 it was needed to add a `database: KeyValueDatabase` property on `EditorSettingsService.init`, in order to inject the Mock version and let the UnitTests pass.

This is a small PR to help simplify dependency injection on init signatures and on unit tests.

To test:
- Check that the changes look good.
- Unit Tests should pass

### CODE REVIEW

**Comment by jkmassel** [comment]
I'm bumping this to 13.0 as part of the code freeze. If we'd like to release it as part of 13.0, just merge it into `release/13.0`, and DM me – I'll be happy to cut a new beta build!

**Comment by loremattei** [comment]
I'm moving this to 13.2 since 13.1 has been cut. If you want this to make it to 13.1, please move it back, target the `release/13.1` branch and ping me to build a new beta.

**Comment by loremattei** [comment]
Hey! I'm moving this to 13.5 because 13.4 has been cut. If you want this PR to make it to 13.4, please feel free to move it back, target the release branch and ping me to build a new beta.

**Comment by loremattei** [comment]
Hey! I'm moving this to 13.6 because 13.5 has been cut. If you want this PR to make it to 13.5, please feel free to move it back, target the release branch and ping me to build a new beta.

**Comment by koke** [comment]
@etoledom since this one has been stale for a while and most files have conflicts now, I think it'd be better to close it and create a new one when you have time to work on it.

**Comment by etoledom** [comment]
> @etoledom since this one has been stale for a while and most files have conflicts now, I think it'd be better to close it and create a new one when you have time to work on it.

I agree, let's close it for now. 👍

**Pull request closed without merging**
