### PR TITLE
Adds some site creation UI improvements

### LINKED ISSUE #11686: Site Creation: Improve "creating new site" screen.
## Description:

When creating a site through our New Site Creation flow, the screen that tells the user the site is being created could use some design improvements.

## Image:

IMG_93155CCFF54F-1

## Matching Android Issue:

https://github.com/wordpress-mobile/WordPress-Android/issues/9854

### PR DESCRIPTION
**Pull request by emilylaguna**
Fixes #11686 subtask: Update the `SiteAssemblyContentView` UI

**Changes:**
- `AppImages.xcassets`
  - Added a new imageset `site-creation-loading` that is displayed while the user is waiting for their site to be created in both dark and light modes

- `SiteAssemblyContentView`:
  - Added 3 new properties:
    - `statusTitleLabel` and `statusSubtitleLabel`: Display the title and subtitle copy specified here: https://github.com/wordpress-mobile/WordPress-iOS/issues/11686#issuecomment-558860091
    - `statusImageView`: Displays the new `site-creation-loading` image

**To test:**
- Launch the app
- Go to the 'My Sites' tab
- Go to the 'Switch Sites' view
- Tap the + button to add a new site
- Tap the `Create WordPress.com site` option
- Tap any site option
- Tap Skip to skip the about
- Tap Skip to skip the basic information
- Search for any domain and select it
- Tap the 'Create Site' button

Example expected screenshots

| Device  | iOS Version | Mode | Screen |
|----------|----------|----------|----------|
| iPhone 5s  |  11.4 | N/A - Light | |
| iPad Air 2 | 12.4 | N/A - Light |  |
| iPhone 11 Pro | 13.2.2 | Light |  |
| iPhone 11 Pro | 13.2.2 | Dark |  |
| iPad Pro (12.9 inch) | 13.2.2 | Light |  |
| iPad Pro (12.9 inch) | 13.2.2 | Dark |  |

**Other notes:**
- I noticed there was the `TitleSubtitleHeader` class that already handles the title/subtitle flow which I initially tried to use, but in practice the constraints that were being added to it internally didn't match the design I was given so I reverted back to my own title/subtitle properties

**PR submission checklist:**
- [X] I have considered adding unit tests where possible.

- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by leandroalonso** [comment]
Hi @emilylaguna, just reviewed and it works as expected and the code looks good. :)

I will just wait for @mbshakti to approve the design changes before we merge. In the meantime, you can open new PRs and just state that they depend on this one.

**Comment by leandroalonso** [comment]
@mbshakti Can you please take a look at the screenshots? :)

**Comment by mbshakti** [comment]
I think the text ("your site will be ready shortly") is a bit too close to the illustration. Can we double the spacing at the top of the illustration please? https://drive.google.com/file/d/1Jw884W5AzHVBHL2wI6nrBz47s4IEuBag/view?usp=sharing

**Comment by emilylaguna** [comment]
Hi @mbshakti, I've updated the spacing which you can see below:

|Before | After |
--------|------|
| |  |

**Comment by leandroalonso** [comment]
@emilylaguna the icons seem outdated — we should replace them by the non-puking-rainbow version. Or this is something you're going to change in a future PR?

**Comment by emilylaguna** [comment]
That was changed in a future PR, here's the commit: https://github.com/wordpress-mobile/WordPress-iOS/pull/13105/commits/615e0f6d679dd964c7bb76bd871b020a232e5541

**Pull request merged**
