### PR TITLE
Login: fix Google button covering error label

### LINKED ISSUE #7898: Google button covers error label
As discovered by @jklausa the Google button in debug builds covers the error label, as seen here:

screen shot 2017-10-02 at 10 34 49 pm

Obviously, the layout is kind of broken.

### PR DESCRIPTION
**Pull request by nheagy**
Fixes #7898 

simulator screen shot - iphone 8 - 2017-10-03 at 11 07 51

To test:
- ensure the input field and labels still work as before
- ensure the error label can't be covered by the Google button

Needs review: @aerych 
*Note:* forked from #7887

### CODE REVIEW

**Comment by aerych** [comment]
Looks like there is some spacing issues on the SE when the keyboard is present.
### Before:
simulator screen shot - iphone se - 2017-10-03 at 15 06 02
### After:
simulator screen shot - iphone se - 2017-10-03 at 14 55 50

Notice how the info text is truncating where it wasn't before. 

I also noticed the same thing you did, when the error screen is visible space is *very* tight. 
simulator screen shot - iphone se - 2017-10-03 at 14 56 12

Localizations can make this worse. German is one example that comes to mind.  I wonder if the error should replace the Google button in these cases.  Not sure.  Thoughts?

**Comment by nheagy** [comment]
>  I wonder if the error should replace the Google button in these cases. 

Ya, that's probably the right thing to do. @folletto any thoughts?

**Comment by folletto** [comment]
I replied on Slack, reporting here too:

> The mental model for that should be that the bottom "log into... Next" is on a separate floating block on top (`z-index: 1` equivalent) so the "page" scrolls below
>  Another alternative would be to hide Google login message when this condition is true: `keyboard visible && error message`

**Comment by aerych** [comment]
> Another alternative would be to hide Google login message when this condition is true: keyboard visible && error message

👍

**Comment by nheagy** [comment]
Ok, @aerych this is ready for another look.

Here's how hiding the Google button looks, cc @folletto 

7879-google-button-animation-flat

**Comment by aerych** [comment]
Small nitpick... could we leave the button visible when there is an external keyboard in use? 

simulator screen shot - ipad pro 9 7-inch - 2017-10-11 at 07 25 28

**Comment by aerych** [comment]
By the way... the button transition when the keyboard hides/shows is very nice :)

**Comment by folletto** [comment]
Well done 👍

**Comment by nheagy** [comment]
Fixed the appearance on iPad and the conflicts.

Assuming Hound is pleased, this should be ready for another loock @aerych

**Pull request merged**
