### PR TITLE
[Home Page Picker] Adds sample URL to the Choose a Domain Screen

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes** https://github.com/wordpress-mobile/gutenberg-mobile/issues/3019

### To test:

1. Start the site creation flow (e.g. *Choose site > Add button*)
1. Select the *Create WordPress.com site* option
1. Press **Skip** or select a domain and press **Choose**
1. Verify that the sample URL view is shown
1. Search for something 
1. **Expect** the UI to disappear
1. Clear the results
1. **Expect** the UI to reappear

### Screenshots

Phone | Tablet
--- | ---
<a href="https://user-images.githubusercontent.com/3384451/108866978-b8d4ef80-75c2-11eb-9672-1952d76e7edd.png"></a> | <a href="https://user-images.githubusercontent.com/3384451/108867088-d2763700-75c2-11eb-9f64-06bfd8029d33.png"></a>
<a href="https://user-images.githubusercontent.com/3384451/108867150-e4f07080-75c2-11eb-9c04-74a0f6faaea6.png"></a> | <a href="https://user-images.githubusercontent.com/3384451/108867204-f33e8c80-75c2-11eb-8c3e-c866d9d6bf50.png"></a>

### PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by chipsnyder** [comment]
@kyleaparker Here's a build with the changes for this site domain. When you get a chance to take a look, I would love your feedback!

**Review by antonis — APPROVED** [review]
Great job @chipsnyder 👍 
I tested this on an iPhone SE 2020 (iOS 14.2) and on an iPad simulator. The app works as expected. The code changes are clean and LGTM 🎉 

I noticed only two minor things/suggestions:
* The `Search Domains` hint should change to `Type a name for your site` to match the design.
* Probably we can also get `example.com` string from a localisable resource. I'm not sure if this is meant to be translated thought.

**Comment by chipsnyder** [comment]
>The Search Domains hint should change to Type a name for your site to match the design.

Good eye! I had missed that originally I made the change now. 

> Probably we can also get example.com string from a localisable resource. I'm not sure if this is meant to be translated thought.

I had thought about this and wasn't sure if we would want it to be translated. I see now that we did translate this on Android so It's best to be consistent. 

I went ahead and made those changes.

**Comment by kyleaparker** [comment]
This looks good, nice job! Is it possible to remove the scroll on the empty state?

**Comment by chipsnyder** [comment]
> Is it possible to remove the scroll on the empty state?

@kyleaparker Yeah, we can do this. I made the change and added a build. As a side-effect of this change, the header will expand if you clear the content (where it would maintain its position previously). Take a look at the latest build, and if that looks good to you, we can get this merged.

**Comment by kyleaparker** [comment]
>Take a look at the latest build, and if that looks good to you, we can get this merged.

I think it's good. Thank you!

**Pull request merged**
