### PR TITLE
NotificationsViewController: Updates tracking behavior

### PR DESCRIPTION
**Pull request by jleandroperez**
Needs Review: @astralbodies 
Thanks Aaron!

### CODE REVIEW

**Comment by astralbodies** [comment]
Looks good to me, @jleandroperez. We should probably let whomever know on the business side that the numbers for this stat were low. Would that be @roundhill? Not sure who looks at usage stats for notes.

**Comment by astralbodies** [comment]
:shipit:

**Comment by jleandroperez** [comment]
Thanks for the review @astralbodies! I'll poke Dan on slack!

**Comment by roundhill** [comment]
Thanks for the heads up on the dip.

**Pull request merged**
