### PR TITLE
Release 11.3.1

### PR DESCRIPTION
**Pull request by jkmassel**

### CODE REVIEW

**Comment by jkmassel** [comment]
Thanks @jtreanor! 

@loremattei – I'm not sure how you want to handle the version strings conflicts – I'm thinking we just use the newer values, but lmk how you'd like to handle it, or if you'd like to finish merging this one so as not to conflict with 11.4? 😄

**Comment by jtreanor** [comment]
@jkmassel Ah, I didn't see the conflicts. The way I have been handling conflicts without merging develop into the release branch (which we don't want) is like this:
```
git checkout develop
git checkout -b merge-x.x.x-into-develop
git merge release/x.x.x
git push
```
The you can open a PR from `merge-x.x.x-into-develop` without modifying the release branch.

Maybe @loremattei has a better way though 😄

**Comment by loremattei** [comment]
No, I haven't @jtreanor :-) 
I usually do exactly the same thing.

Anyway, I set up this https://github.com/wordpress-mobile/WordPress-iOS/pull/10600 to merge the fix into 11.4, so the commit will be merged into develop when we'll merge that branch back (and we don't risk cherry-picking related conflicts).

**Comment by loremattei** [comment]
TIL about this GH magic: it recognised that the commit was merged (through the 11.4 release branch) and automatically updated this one. 👍

**Comment by jtreanor** [comment]
Oh, thats really neat!

**Pull request merged**
