### PR TITLE
Update to gutenberg-mobile 1.13.0

### PR DESCRIPTION
**Pull request by mchowning**
Update gutenberg to v1.13.0 (gutenberg-mobile PR)

Gutenberg Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1351
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/17329
WPAndroid PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10483

To test
- Smoke test gutenberg editor.

#### Remaining tasks
~- [ ] Add implementation for [`editorDidAutosave` function](https://github.com/wordpress-mobile/WordPress-iOS/commit/af6588f451b03877a002a3508b9b8ba03e80dc25)~ (Not needed anymore for this release)
- [x] Update to reference gutenberg-mobile release tag instead of commit hash

#### Update release notes:

- [X] I have considered if this change warrants user-facing release notes and have added them to RELEASE-NOTES.txt if necessary.

### CODE REVIEW

**Comment by mchowning** [comment]
I needed to update `GutenbergViewControl` because it did not have the `editorDidAutosave` function implemented for the `GutenbergBridgeDelegate` protocol. I just added an empty stub implementation to get this PR building, so we still need to take care of this. I haven't had a chance to look into this much, but it looks like we probably need an update similar to what @daniloercoli did [on the Android side](https://github.com/wordpress-mobile/WordPress-Android/pull/10483). I'll try to take a look at this later this afternoon after I grab some lunch, but if @etoledom or @SergioEstevao want to take a look, I could use the help. :smile:

**Comment by daniloercoli** [comment]
@mchowning I guess we need to merge this PR here:  https://github.com/wordpress-mobile/WordPress-iOS/pull/12489 that introduces the iOS changes.

**Comment by etoledom** [comment]
> @mchowning I guess we need to merge this PR here: #12489 that introduces the iOS changes.

Yes, we need that one first 🤔 
I thought we weren't shipping autosave on this version? From https://github.com/wordpress-mobile/gutenberg-mobile/pull/1351#issuecomment-528801015

**Comment by daniloercoli** [comment]
> I thought we weren't shipping autosave on this version? From [wordpress-mobile/gutenberg-mobile#1351 (comment)](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1351#issuecomment-528801015)

There was a mention to the frozen (1.12.0) branch in the comment mentioned above, that is why i said no to target that branch. Instead this is a new version (1.13.0). It's safe to release the changes now, since it will be included in the next apps cut and tested for 2 weeks before going to the public.

**Pull request merged**
