### PR TITLE
Build Warnings: Remove invalid relationships from old models

### PR DESCRIPTION
**Pull request by hassaanelgarem**
## Description
Removes an invalid relationship from old models (102-109) to fix warnings.

I installed WP version 16.3 (09c1f2b3532ae719e95f53f87e52529022497834) and ran the app. This version has model version 102, which is the first model with the invalid relationship.
I then built and installed this branch with these changes and verified that the app launches normally and the model gets migrated correctly.

## Testing Instructions

No testing is needed.

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by leandroalonso** [comment]
@hassaanelgarem there are two unit tests failing when loading the model `103`: `improper model with nonsensical relationship definitions (NSInternalInconsistencyException)`

**Comment by hassaanelgarem** [comment]
@leandroalonso Fixed in 829a0b85436411e0fec4db1f3ea633bb59f54723 👍

**Review by leandroalonso — APPROVED** [review]

**Comment by leandroalonso** [comment]
Just to be on the safe side though, @aerych do you think you would have a few minutes to test this?

Basically, we're getting rid of warnings and there was an invalid relationship in quite a few old models. As Hassaan stated in the PR description installing a super old version of the app and running this PR doesn't crash or cause any issues. Anything else you think might go wrong with this change?

We also accept "I don't have time" as an answer. :)

**Comment by aerych** [comment]
> We also accept "I don't have time" as an answer. :)

There is always time to be paranoid for safety sake. ;) 

I looked into this a little, and did my homework to [find the commit that introduced the relation](https://github.com/wordpress-mobile/WordPress-iOS/commit/38dc03b19df8dd4e793f10a6f56efd07a5e29a62#) in version [16.0](https://github.com/wordpress-mobile/WordPress-iOS/tree/16.0/WordPress/Classes/WordPress.xcdatamodeld), another [commit](https://github.com/wordpress-mobile/WordPress-iOS/commit/6b334fd5b06d15b7ca4e2cdafff6aaa33234a407) that removed the relationship [in 16.5](https://github.com/wordpress-mobile/WordPress-iOS/tree/16.5/WordPress/Classes/WordPress.xcdatamodeld) and an old slack conversation about the warnings when they were first noticed (scroll down a bit to see the full conversation): p1609184214229100-slack-apple-dev.  (Ah, memories.)

> I then built and installed this branch with these changes and verified that the app launches normally and the model gets migrated correctly.

This sort of core data change makes me nervous even when it works in testing. I would normally not be in favor except that it only affects these older versions, reducing the risk of a broken migration testing didn't reveal. 

That said, if we still have active users on versions 16.0 - 16.4 they are unlikely to ever upgrade so I don't think we need to worry too much here.  For inactive users who may return with version 16.0-16.4, if there is a migration issue when they upgrade they'll be prompted to login fresh and _probably_ wouldn't have had time to loose anything important (saved drafts etc.). I can get comfortable with this small level of risk.
:shipit:

**Comment by hassaanelgarem** [comment]
@aerych Thank you for looking into this Eric! I will be merging this then 👍 

_PS: Out of curiosity I looked into how many users on versions 16.0-16.4 interacted with the app during the past month. There are 1664 users, and they represent 0.32% of our active users._

**Pull request merged**
