### PR TITLE
Posts & Pages: Move authors filter button to navigation bar

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/21715

To test:

- Verify that the authors filters is now displayed in the navigation bar
- Verify that the filter is available for both Posts and Pages
- Verify that after a fresh install the default filter is "Everyone"

Screenshot 2023-10-13 at 9 32 39 PM

## Regression Notes
1. Potential unintended areas of impact: Posts & Pages
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual
3. What automated tests I added (or what prevented me from doing so): n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by momo-ozawa — COMMENTED** [review]
Hey @kean, the new authors filter looks great! A few things:
- Should default to "Me" or "Everyone"? "Me" is the default filter on ~mobile~ iOS, but it's "Everyone" on web. cc: @zwarm @AjeshRPai 
- I don't see the author filter on Pages for a site that should display filters - this should be resolved by applying this change from `trunk`

Screenshot 2023-10-16 at 10 00 58

**Comment by zwarm** [comment]
> * Should default to "Me" or "Everyone"? "Me" is the default filter on mobile, but it's "Everyone" on web. 

@momo-ozawa - On Android, fresh install, "Everyone" is selected as the default. I vote for staying consistent with the web, but will go with the majority.

**Comment by kean** [comment]
Other folks also agree, and there is an existing task for that https://github.com/wordpress-mobile/WordPress-iOS/issues/16593. I'm going with "Everyone" by default.

**Comment by kean** [comment]
@momo-ozawa, I addressed both of these issues. Thank you!

**Review by momo-ozawa — APPROVED** [review]

**Pull request merged**
