### PR TITLE
[Stats Refresh] Period Overview card: filter tab bar sized properly

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #n/a

This change:
- Fixes the Filter Tab Bar on the Overview Card to display properly on small devices. 
(As noted on https://github.com/wordpress-mobile/WordPress-iOS/pull/11204#issuecomment-470369452)
- Updates the Filter Tab Bar to emulate the Android implementation, i.e:
  - Centered tab labels.
  - Label in all caps.
  - Reduced label size to 12pt (just the label text, not the data part).
- This is unrelated, but it also removes the table footer from the detail list view. It was a 2 line change, so I threw it in.

To test:

---
- On devices of varying sizes, go to the Period > Overview card.
  - To note, the Filter Tab Bar was scrunched on the iPhone SE and XS.
- Verify the Filter Tab Bar is sized properly, i.e. the tab labels are two lines and not wrapped more. Examples:

iPhone SE:

filter_tab_bar_SE

iPad:

ipad

---
- Go to any "standard" details list (i.e. _not_ Latest Post Summary or Posting Activity).
- Scroll to the bottom of the list. Verify there is no longer a space between the table bottom and the tab bar.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @SylvesterWilmott . iPhone X screenshot as requested. Please let me know if you need anything else.


iphone_x

**Comment by ScoutHarris** [comment]
Hey @stevebaranski .

> Have we examined how changing the left & right insets for buttonInsetsAttributedTitle impact the other FilterTabBar uses within the app?

The `attributedTitle`, and thus the `buttonInsetsAttributedTitle`, was added specifically for this usage of FilterTabBar, so there is no impact elsewhere.

**Comment by ScoutHarris** [comment]
Thanks @stevebaranski !

**Comment by SylvesterWilmott** [comment]
This looks good @ScoutHarris 

A few of things:
- Let's reduce the label size even more to 11pt
- Let's truncate the labels when they get too long instead of dropping to a new line
- Let's use dynamic text sizing for the numbers

**Comment by ScoutHarris** [comment]
Hey @SylvesterWilmott .

> Let's reduce the label size even more to 11pt

Done.

> Let's truncate the labels when they get too long instead of dropping to a new line
> Let's use dynamic text sizing for the numbers

These are proving to be a bit troublesome. Because of the way the FilterTabBar is written, the tab titles are actually just one label. I had format each bit separately, then concatenate them into one label using the `attributedTitle` property. This obviously restricts the ability to modify them separately as if they were two labels.

I'll have to think about this, and address these in a separate PR.

**Pull request merged**
