### PR TITLE
Stories: Deleting one of the images causes the next one not to load

### LINKED ISSUE #16966: Stories: Deleting one of the images in my story draft causes the next one to not load
### Expected behavior
deleting an image should not affect the others in the story

### Actual behavior
https://user-images.githubusercontent.com/66104034/127920796-2e188b3d-953c-46f4-86e7-7702477e0743.MP4

### Steps to reproduce the behavior
1. Create a Story Post 
2. Add 2 or more images (from camera or gallery, doesn't matter)
3. Delete one, the other one will not load

### PR DESCRIPTION
**Pull request by staskus**
Fixes #16966

## Description

Deleting one image causes the next one not to load in the editor. The issue happens due to a bug in [kanvas-ios repository which was fixed, reviewed, and merged.](https://github.com/tumblr/kanvas-ios/pull/147)

## Solution

Use newest `kanvas-ios` version

## Testing instructions

1. Log in to WordPress/Jetpack app with a WordPress account
2. Create a Story post
3. Make / Select multiple (more than 2) photos
4. Delete one of the images by dragging
5. Another picture should load

### Before

https://user-images.githubusercontent.com/4062343/193037528-e7062915-f99c-4ece-86e1-dbaaf7af8fc5.mp4

### After

https://user-images.githubusercontent.com/4062343/193037668-5f062a9d-606b-47f2-96bf-5d947af8e682.MP4

### CODE REVIEW

**Comment by guarani** [comment]
Hi @staskus, thanks for fixing this! I'll review this now 👍

**Review by guarani — COMMENTED** [review]
I first reproduced the bug on 20.8 and then installed the JP build here and the bug was no longer present 👍 

I think this bug fix is worthy of inclusion in the release notes, wdyt?

On a side note, I couldn't see the usual PR template used here. Was that intentional?

**Review by guarani — APPROVED** [review]
Since this is working well and none of the issues here is a blocker, I'm approving this now.
Even if you do decide to add release notes, feel free to merge without re-requesting a review.

**Comment by staskus** [comment]
> On a side note, I couldn't see the usual PR template used here. Was that intentional?

Good point, I copied the description from PR in [kanvas-ios repo](https://github.com/tumblr/kanvas-ios/pull/147), that's why it doesn't have a usual description 🫢

> I think this bug fix is worthy of inclusion in the release notes, wdyt?

Thanks for suggesting, I'll include a release note 👍.

**Pull request merged**
