### PR TITLE
Onboarding Improvements: Epilogue (select site / create a new site) + Quick Start prompt

### LINKED ISSUE #17383: Onboarding Improvements: Project Issue
## Description 

This is the parent project issue for Onboarding Improvements. We'll be using this issue to keep track of the project's progress.

Ref: pbArwn-35A-p2

## Tasks
- #17385 
- #17386 
- #17387 
- #17390
- #17500 

## Pre-release Tasks

- [x] A11y (https://github.com/wordpress-mobile/WordPress-iOS/pull/17540)
- [x] Event tracking (https://github.com/wordpress-mobile/WordPress-iOS/pull/17537)
- [x] Release Notes (https://github.com/wordpress-mobile/WordPress-iOS/pull/17565)

### PR DESCRIPTION
**Pull request by momo-ozawa**
Fixes #17383

## Description

This PR merges the feature branch for the Onboarding Improvements project into `develop`

Ref: pbArwn-35A-p2

## How to test

Follow testing directions from:
- #17411
- #17449
- #17484

Case | JP iPhone | WP iPhone | WP iPad
-- | -- | -- | --
No sites |   |  |  
1-3 sites |  |  |  
4+ sites |   |  |  

## Regression Notes
1. Potential unintended areas of impact
- Login Epilogue flow
- Quick Start
- Site creation

2. What I did to test those areas of impact (or what existing automated tests I relied on)
- Tested the flows above manually

3. What automated tests I added (or what prevented me from doing so)
- Added UI tests #17561

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by leandroalonso** [comment]
@momo-ozawa I found one small issue that doesn't prevent this to be merged on `develop` (I'd say it's an edge case). Basically, when the user is logged in and adds a self-hosted site we show the epilogue to them.

### Steps to reproduce

1. Login
2. Add a self-hosted site
3. Notice that the epilogue is show (asking the user to select a site or to create a new one)
4. The prompt is displayed

**Review by leandroalonso — APPROVED** [review]

**Comment by momo-ozawa** [comment]
@leandroalonso (cc: @osullivanchris)

 > I found one small issue that doesn't prevent this to be merged on develop (I'd say it's an edge case). Basically, when the user is logged in and adds a self-hosted site we show the epilogue to them.
 
Do you think it would make the most sense to just dismiss the login vc and go back to mysite w/o showing the epilogue?
FWIW, in 18.7 we show the epilogue after adding a self-hosted site. But given the new epilogue designs, it doesn’t make much sense to show a choose site / create a new site option.

**Comment by leandroalonso** [comment]
> Do you think it would make the most sense to just dismiss the login vc and go back to mysite w/o showing the epilogue?

I guess so, yes. Unless it's super complicated!

**Comment by osullivanchris** [comment]
Good spot @leandroalonso . Proposed solution sounds good to me 👍

**Comment by AliSoftware** [comment]
Kudos @momo-ozawa for testing and including screenshots to JPiOS (and not just WP) 👏 , which already answers the question I almost had when drafting the release notes: with the clear PR description and screenshots I know without a doubt that this does apply to both WP and JP (and should thus be included in JP release notes too) 🙇 🎉

**Pull request merged**
