### PR TITLE
UL&S: Send the correct errors to the user when SMS requests exceeded

### LINKED ISSUE #13807: Login: "Text me a code instead" sometimes doesn't result in an SMS with a verification code when using Google login plus 2FA
Steps to reproduce:

1. Start with an account with Google sign-in and two-factor authentication enabled.
1. Tap "Log in".
1. Tap "Continue with Google".
1. Tap "Text me a code instead".
1. Wait for an SMS.
1. If an SMS doesn't arrive, try tapping "Text me a code instead" again.
1. If you are able to log in successfully, log out and try the steps again a few times.

**Result:** sometimes tapping "Text me a code instead" doesn't send a code or the code isn't received quickly enough, this happens most often after logging in using SMS successfully just prior to trying it a second time. ([1m52s](https://cloudup.com/cLsgcdSJUGR), [2m45s](https://cloudup.com/ckM1hTn0ZMp))

IMG_3715
<sup>Tested with WPiOS 14.5.0.1 TestFlight beta on iPhone 11 iOS 13.4.</sup>

### PR DESCRIPTION
**Pull request by mindgraffiti**
Fixes #13807 

Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/469

### To test
**Test Case 1**
1. Use an account that receives 2fa codes through a mobile app (like Authy)
2. Log in normally and wait for the 2fa view to appear
3. Tap "Text me a code instead"
4. **Expected:** This should continue to work normally, with no error messages appearing.

**Test Case 2**
1. Use a social account (Google or SIWA) that receives 2fa codes by SMS.
2. Log in normally and wait for the 2fa view to appear.
3. Tap "Text me a code instead".
4. Back out of logging in and go through the flow again.
5. Tap "Text me a code instead".
6. An error message should appear

**Expected:**
<a href="https://user-images.githubusercontent.com/1062444/93394323-ab5c5200-f839-11ea-931e-893ae25ddb84.png"></a>
PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @mindgraffiti .

I'm a bit confused as to why the functionality change in Test Case 1.  Getting a code via SMS is a valid option even if you use an authenticator app. Why are we no longer allowing it?

**Review by Gio2018 — COMMENTED** [review]
Hey @mindgraffiti , while reviewing the **Test case 1** I ran in this situation:

I used an account with 2FA that uses an authenticator app, and when i tapped "Text me a code instead", it looked like the SMS had been sent, but i didn't really receive it, and I saw this message in the console:

`Possible failure when requesting a one time code: Optional("Please enter the verification code generated by your Authenticator mobile application.")`

To be noted that initially i did not have a recovery phone number, and I thought that was the problem, so I set it, tested again and got the above result.

**Comment by mindgraffiti** [comment]
Closing this PR. There is a deeper issue with the API response that isn't easily worked around on the client side, and this proposed solution doesn't improve the problem.

**Comment by mindgraffiti** [comment]
> To be noted that initially i did not have a recovery phone number, and I thought that was the problem, so I set it, tested again and got the above result.

For the record, a recovery phone number isn't required. When the user requests an SMS OTP, it uses the stored phone number that was entered when signing up for 2fa.

**Pull request closed without merging**
