### PR TITLE
[Gutenberg] Enable file block

### PR DESCRIPTION
**Pull request by etoledom**
This PR enables the File Block on the gutenberg block editor.

To test:

- Install the CI build on your device.
- Follow the manual tests document: TBD

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by etoledom** [comment]
✅ TC001: Upload completes successfully from the device library.
✅ TC002: Upload completes successfully from the WordPress Media library.
✅ TC003: Upload fails from the device library.
✅ TC004: Stop the file upload before it completes.
✅ TC005: Close the post with an ongoing file upload.
✅ TC006: Replace the selected files.
✅ TC007: Change the alignment in the File Block.
✅ TC009: Open link in new tab.
✅ TC0010: Show/hide download button.
✅ TC0011: Copy file URL.
✅ TC0012: [(Not yet on the document)](https://github.com/wordpress-mobile/test-cases/pull/57/files#r531566870) Close and reopen post with an ongoing file upload.

**Comment by jkmassel** [comment]
👋 Hey there! We are freezing `16.3` today, so this PR is being bumped to `16.4`. If you need it to be part of the `16.3` release, please merge it to the `release/16.3` branch and send me a DM – I'll be happy to cut a new beta release!

**Comment by etoledom** [comment]
Updated with the following changes:
https://github.com/WordPress/gutenberg/pull/27228#issuecomment-738300019

**Comment by jd-alexander** [comment]
@etoledom could you update the gb mobile submodule to the latest changes here. I appreciate the help.
https://github.com/WordPress/gutenberg/pull/27228#issuecomment-738600342
 I would, but I am not sure how to generate the bundle. I think I saw the command recently but I haven't used it as yet.

**Comment by etoledom** [comment]
✅ Tested [again](https://github.com/wordpress-mobile/WordPress-iOS/pull/15400#issuecomment-734916563) with the new build and everything looks shinny ✨

**Review by jd-alexander — APPROVED** [review]
@etoledom I ran thorough tests using all the latest changes and all the test cases worked as expected. 

- ✅ **TC001:** Upload completes successfully from the device library.
- ✅ **TC002:** Insert completes successfully from the WordPress Media library.
- ✅ **TC003:** Upload fails from the device library.
- ✅ **TC004:** Stop the file upload before it completes.
- ✅ **TC005:** Close the post with an ongoing file upload.
- ✅ **TC006:** Replace the selected files.
- ✅ **TC007:** Change the alignment in the File Block.
- ✅ **TC009:** Open link in new tab.
- ✅ **TC0010:** Show/hide download button.
- ✅ **TC0011:** Copy file URL.
- ✅ **TC0012:** Close and reopen post with an ongoing file upload.

**Pull request merged**
