### PR TITLE
Merge release 17.8 into trunk

### PR DESCRIPTION
**Pull request by mokagio**
Merges the 17.8 changes into `trunk`.

Leaving this as a draft till we actually release it. Still, I'd appreciate a review anyway.

Thanks 🙇‍♂️ .

- [x] WordPress submitted for App Store Review
- [x] Jetpack submitted for App Store Review
- [x] WordPress approved by Apple and started phased release
- [x] Jetpack approved by Apple and started phased release

### CODE REVIEW

**Comment by mokagio** [comment]
This has now been published on the Store: Marking it "Ready for Review".

**Comment by mokagio** [comment]
I'm seeing this, but I don't think it will block the merge.

image

I'll enable auto-merge and see what happens after someone approves.

**Review by oguzkocer — APPROVED** [review]
@mokagio I think we have decided to not mark release PRs as draft (including the ones against `trunk`) per @jkmassel earlier request/question on Slack. Although I have seen @jkmassel also marked one as draft iirc, after this discussion, so.. maybe I am imagining things 🤔

**Comment by mokagio** [comment]
Thanks for mentioning this @oguzkocer! 

I'm on board with not using the draft 👍 I used it here because... I totally forgot about the discussion 🙃 

On the other hand. I checked back in Slack and the discussion was actually brief and with no clear conclusion. I think that's because we trailed off discussing folding `develop` into `trunk`, got excited about that idea, and forgot about this one 😳.

**Pull request merged**
