### PR TITLE
Added Action sheet title that shows word and character count

### LINKED ISSUE #10176: Editor: Word count
A number of users have requested a word/character count in the editor.

Currently in Calypso web this appears in the bottom right corner of the editor:

Previous issue here: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/606

### PR DESCRIPTION
**Pull request by yaelirub**
Fixes #10176  

To test:
• New Post *	
-      Create a new post
-      Type something in title
-      Type something in text view.
-      Tap on the 3 dots menu in the top right corner.
-      See the title of the action sheet shows the number of words and characters .

• Editing post *
-      open an existing post
-      Tap on the 3 dots menu in the top right corner
-      See the title of the action sheet shows the number of words and characters .
-      Continue editing.
-      Tap on the 3 dots menu in the top right corner.
-      See the title of the action sheet shows the updated number of words and characters.

word_counting1

### CODE REVIEW

**Comment by yaelirub** [comment]
Per suggested design:
image from ios

**Comment by iamthomasbishop** [comment]
Looks good to me! Thanks for tackling this @yaelirub!

**Comment by yaelirub** [comment]
Updated

**Comment by jklausa** [comment]
Thanks for getting this over the finish line :)

**Comment by jklausa** [comment]
(sorry for the reopening/closing — trying to get CI to build!)

**Pull request merged**
