### PR TITLE
Issues/2978 move defaultdtcoretextoptions

### LINKED ISSUE #2978: Move defaultDTCoreTextOptions into WPRichTextView where it belongs
Since `WPRichTextView` is the only class still using `defaultDTCoreTextOptions` from the `WPStyleGuide` move those methods for better encapsulation of usage, and to simplify the shared pod dependencies.

### PR DESCRIPTION
**Pull request by aerych**
Closes #2978 

Note: Make sure the shared pod is updated before merging since this PR references the updated pod version!

### CODE REVIEW

**Comment by sendhil** [comment]
Hrm... pod install is failing

**Comment by sendhil** [comment]
Oh wait... woops didn't see this - https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/45

**Comment by sendhil** [comment]
I misunderstood your comment about updating the pod, I thought you just meant run `pod install` :facepalm:

**Comment by sendhil** [comment]
:shipit:

**Comment by sendhil** [comment]
@aerych - :shipit: once this can be merged...

**Comment by aerych** [comment]
Thanks @sendhil

**Pull request merged**
