### PR TITLE
Add clang format file.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Clang Format is a tool that is part of the <a href="http://clang.llvm.org">Clang toolset</a> and it helps to automatically format Objective-C code. Out of the box, clang-format is a command-line tool that you can run directly on your source files. It doesn’t add/remove code from your source, instead focusing on adjusting the whitespace characters within your source to make code more consistent.

With a little bit of extra effort, you can make clang-format available from within Xcode. <a href="http://ClangFormat-Xcode">ClangFormat-Xcode</a> is an Xcode plugin developed by Travis Jeffery that makes Clang’s format tools available within Xcode.

Travis has made the plugin available via Alcatraz. Alternately if you don't want to install <a href="http://alcatraz.io">Alcatraz</a> and prefer to install the plugin manually follow the instructions on the repository.

After you install it there will be a new menu item under Edit → Clang Format where you can configure and trigger automatic formatting of code in your project.

You can format the current file, selected text within the current file or more than one file selected in the Xcode project navigator. The style used to format is also available on this menu, there is a set of pre-configures styles (LLVM, Google, WebKit) but there is also the possibility to create our own style trough a configuration file.

To make our life easier I already created a <a href="https://gist.githubusercontent.com/SergioEstevao/fcacf0ba6dacdced4113/raw/89f61047db6fe83c2016769083b77d6839287247/.clang-format" target="_blank">configuration file</a> for clang-format that follows WordPress code formatting guidelines and add it to our WordPress repo. So you just need to configure the plugin to use the File configuration option.

To make the process of formatting quicker I’ve assigned keystrokes to these using System Preferences → Keyboard → Shortcuts → App Shortcuts. Ctrl+F to format selected text and Ctrl+Shif+F for the all file.

cc @sendhil, please review

### CODE REVIEW

**Comment by sendhil** [comment]
@SergioEstevao - been playing around with this. Right now it seems to mess up some of the formatting with dictionaries. For example, go over to `WordPressAppDelegate.m` and navigate down to `fixKeychainAccess` and format that method. This is what I got:
screen shot 2015-03-19 at 4 15 45 pm

**Comment by SergioEstevao** [comment]
I tested a bit more the formatting around dictionaries literals and it works well in the majority of cases, this thing here it's caused by the bridge castings we are doing on this specific. 
I've been trying to fix it but it looks it's a edge case on clang-format. 
We may need to wait for them to release a new version to fix this specific problem. Meanwhile I think this is good enough to release anyway because it works on majority of scenarios.

**Comment by sendhil** [comment]
@SergioEstevao have you tested it out on a few other files to make sure it's not doing strange things? Also i noticed for some of the lines got reformatted to two a little aggressively. Is the line length set to 120 right now?

**Comment by SergioEstevao** [comment]
I've been using it on my code day to day and I'm not seeing any strange things.

The line length configured at the moment is unlimited. It shouldn't break lines can you point me to an example?

**Comment by sendhil** [comment]
Ahh I see why I thought it was messing with the lines (the formatting file adds in an extra line with dictionaries). Was this intentional?

Before:
before

After:
after

**Comment by sendhil** [comment]
@diegoreymendez thoughts on the options in here?

**Comment by SergioEstevao** [comment]
Looking at the configuration file there isn't anything explicit about the dictionaries literals it could be related to some bug regarding the brackets.

**Comment by SergioEstevao** [comment]
@sendhil  how did you install clang-format on Xcode? Alcatraz or build it yourself?

And are you using the default clang format that comes with it?

**Comment by diegoreymendez** [comment]
@SergioEstevao - Can you please add contextual info as to what this PR does and why.  Also please add information on what the steps are to run this tool and test it.

**Comment by SergioEstevao** [comment]
@diegoreymendez the information was in a CoreApps post but I will duplicate it here.

**Comment by sendhil** [comment]
@diegoreymendez  any updated thoughts on this?

**Comment by diegoreymendez** [comment]
My initial thoughts, without having tested this myself, is that if it's causing issues with some of our code, it'll be doing more harm than good.

I'll test this tomorrow myself though.

**Comment by diegoreymendez** [comment]
Checking this out now...

**Comment by diegoreymendez** [comment]
Right now the plugin is not working for me.  When I format the code I'm getting two spaces for indentation.  This is part of what worries me - since there's no supported public plugin interface in Xcode, any plugin we find is basically a hack.

Can you try again @SergioEstevao and see if it works for you?

**Comment by diegoreymendez** [comment]
PS: I built and installed from their repo.

**Comment by diegoreymendez** [comment]
@SergioEstevao - I've tested this with the latest version of ClangFormat-Xcode and it's working very well for me.  I wasn't able to reproduce the issues @sendhil found, so I guess those have been fixed.

Since this is just a configuration file it sounds safe enough to add as an optional tool we can use.

I don't think this should be mandatory though... at least not yet.  The Xcode interface for plugins is private, which means any Xcode plugin is basically a hack at this time.  I don't think it'd be wise for us to force our devs to install it unless they themselves decide to use the tool.

I'd like to hear your opinion on this, together with @sendhil's.

**Comment by SergioEstevao** [comment]
It was never planned to be mandatory, it was something to help developers to make the code follow the code layout guidelines. I personally use it every time I do new code or refactor something to layout the code properly.
If we start a new project or get to a point where the code is all well formatted we could enable the options to layout on save for every file or/and put a step on the build process to do this.

**Comment by diegoreymendez** [comment]
Then let's :shipit:

**Pull request merged**
