### PR TITLE
HACK week: Add new tab icons

### PR DESCRIPTION
**Pull request by momo-ozawa**
## Description
- Adds new tab icons (Design ref: eYeHXEMDbnFptE40xUqZ2T-fi-1862%3A3175)
- Controlled by a local feature flag "New Tab Icons"

## How to test
- Verify new tab icons adapt to environment (light vs dark)
- Verify notification icon shows the correct badge color when there are unread notifications (blue for WP, green for JP)
- Verify you can toggle the "New Tab Icons" feature flag

https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/b1a64a65-2216-4468-8ce2-dff30bea8248

## Regression Notes
1. Potential unintended areas of impact
n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a

3. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] VoiceOver.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] iPhone and iPad. 
- [x] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by osullivanchris — CHANGES_REQUESTED** [review]
Great to play with a build! cool stuff. Some questions/ideas (happy to discuss on slack too):
- Can we hide the tab bar by default on scroll on all views?
- Is the tab bar still using a flat 100% white color? Can we bring back the native blur and transparency? 
- The unselected icons are a little lighter than I expected. Is there any alpha being applied in code? I already have an alpha in the asset.
- WDYT about using the icon for me rather than person's avatar? I'm split. The avatar is more clear. But it also puts the most visual emphasis on this tab, when its the least important one. Want to try the 'Me' assets I gave?

**Comment by mokagio** [comment]
Moving this to 24.0 as I'll run the 23.9 code freeze and this has not been approved yet.

**Comment by momo-ozawa** [comment]
@osullivanchris 

> Can we hide the tab bar by default on scroll on all views?

I'm not sure if we should be hiding the tab bar on scroll. Apple doesn't provide any nice APIs for animating hiding/showing the tab bar.

> Is the tab bar still using a flat 100% white color? Can we bring back the native blur and transparency?

Done! https://github.com/wordpress-mobile/WordPress-iOS/pull/22197/commits/f1287b9c38e69a7186ee40f4bcf70a60de77c97c


https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/09dac1c3-5958-4917-8147-7ae7ac683b48



> The unselected icons are a little lighter than I expected. Is there any alpha being applied in code? I already have an alpha in the asset.

AFAICT there's no alpha being applied via code. Can you provide an icon that has 100% alpha (solid color) to see if that makes a difference? Just one icon is okay for now, so I can figure out whether the built-in alpha is causing issues.

> WDYT about using the icon for me rather than person's avatar? I'm split. The avatar is more clear. But it also puts the most visual emphasis on this tab, when its the least important one. Want to try the 'Me' assets I gave?

Right now the new icon is used as a placeholder image - it's displayed if the user hasn't set a profile icon. I wasn't sure if I should completely replace the me tab icon, or just update the placeholder image, since we recently re-worked the me tab profile icon.

I can change it to always show the static icon instead. Does this mean that we should also change the profile icon shown in the menu for the simplified WP UI (see: [screenshot](https://private-user-images.githubusercontent.com/6711616/262692162-a2bb1cfb-4d3b-4bf4-8cb8-ab8f6dccfcbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTE3NDUsIm5iZiI6MTcwMjI5MTQ0NSwicGF0aCI6Ii82NzExNjE2LzI2MjY5MjE2Mi1hMmJiMWNmYi00ZDNiLTRiZjQtOGNiOC1hYjhmNmRjY2ZjYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMTA0NDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M3MTVkZWQyNTAyZTE5NGQ3OThkMzBjNGFmMTgwZmUxZmNlMjEyZDNlZDhiMTNhMDljNTJmODI4M2NmNTJjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uCU6HYcvLd3uKF_qn99U_oVkjqt4XdlHPJxDsqZB9SY))?

**Comment by osullivanchris** [comment]
> I'm not sure if we should be hiding the tab bar on scroll. Apple doesn't provide any nice APIs for animating hiding/showing the tab bar.

Ok sure. Might be something to consider on a case by case basis instead. Relevant in Reader for example. Maybe not everywhere.

> Done

Transparency looks good. Are there choices of materials/transparencies or one default provided? Do you like how it looks now? Same question for @kean 

> AFAICT there's no alpha being applied via code. Can you provide an icon that has 100% alpha (solid color) to see if that makes a difference? Just one icon is okay for now, so I can figure out whether the built-in alpha is causing issues.

Attached below

> Right now the new icon is used as a placeholder image - it's displayed if the user hasn't set a profile icon. I wasn't sure if I should completely replace the me tab icon, or just update the placeholder image, since we recently re-worked the me tab profile icon.

Leave this with me as an open question, along with the new reader icon. I need to get some answers from the design team. Will get them this week.

[tab bar non transparent.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/13638455/tab.bar.non.transparent.zip)

**Comment by momo-ozawa** [comment]
@osullivanchris Thanks for reviewing!

> Might be something to consider on a case by case basis instead. Relevant in Reader for example. Maybe not everywhere.

Ok - will keep this in mind

> Transparency looks good. Are there choices of materials/transparencies or one default provided? Do you like how it looks now? Same question for @kean

It's the default transparency. Personally I think it looks good!

> Attached below

Thanks! The opaque images worked like a charm!

 | 
-- | --

> Leave this with me as an open question, along with the new reader icon. I need to get some answers from the design team. Will get them this week.

Sounds good - thanks!

**Comment by momo-ozawa** [comment]
Closing this in favor of https://github.com/wordpress-mobile/WordPress-iOS/pull/22325

**Pull request closed without merging**
