### PR TITLE
Fixing/updating travis

### PR DESCRIPTION
**Pull request by kwonye**
Updating to use Xcode 7.1 and deleting nonexistent import.

Also adds cases for 3D Touch in Tracks to fix a unit test.

Needs review: @aerych

### CODE REVIEW

**Comment by aerych** [comment]
Code looks good to me @kwonye.  Tested in the simulator, no problems.  Ran the test suite, no problems. 
I say :shipit:

**Comment by kwonye** [comment]
Thanks @aerych!

**Comment by koke** [comment]
Since I renamed the enums in https://github.com/wordpress-mobile/WordPressCom-Analytics-iOS/pull/38 should I change those strings as well or do they need to stay the same?

**Comment by kwonye** [comment]
> Since I renamed the enums in wordpress-mobile/WordPressCom-Analytics-iOS#38 should I change those strings as well or do they need to stay the same?

They should be changed, but that doesn't have to be done until this repo is pulling 0.40 (right now it's on 0.39)

**Pull request merged**
