### PR TITLE
Fix checkmark fading animation when choosing a site design

### LINKED ISSUE #16690: very tiny visual bug: Blue selected state flickers when choosing a design
- Create a new site
- in the new site creation flow, you can choose between designs
- when I select a design, there's a blue circle with a white checkmark
- when I change between designs, the colour flickers to white for a second on the unselected one
- I think it might be a transition thats happening, or something, but doesn't look quite right to me

suggestion either:
- dont have a transition. When item is unselected, instantly disappear
- if transition, fade out the opacity of the blue dot and white check mark, but retain the colour

https://user-images.githubusercontent.com/50576199/122033052-18504880-cdc8-11eb-9314-581eb4157fb9.MP4

### PR DESCRIPTION
**Pull request by twstokes**
Fixes #16690

### Description

This PR corrects a minor issue where the white background view behind the blue checkmark image would cause a flickering effect due to how their opacities would blend. The solution proposed here is to combine both views into one container view.

A 3D view of the view hierarchy

### To test

**Choosing a design**

1. In the "My Sites" view, tap the "+" symbol at the top right.
2. Choose "Create WordPress.com site".
3. Tap different designs to toggle the checkmark icon animation.
4. Observe that the checkmark's location is the same relative location as before to the top right corner of its view.

**Choosing a layout**

Prerequisites: _This view may be shown with all configurations, but definitely works with WordPress.com sites and a theme from WordPress (e.g. Alves)_

1. In the "My Sites" view, tap Pages, then the blue button to create a new page.
2. Tap the blue button to show the "Choose a Layout" view.
3. Tap different layouts to toggle the checkmark icon animation.
4. Observe that the checkmark's location is the same relative location as before to the top right corner of its view.

**Before**

https://user-images.githubusercontent.com/2092798/152246523-795d040d-eb96-43d9-8a4a-ab87e3f8676d.mp4

**After**

https://user-images.githubusercontent.com/2092798/152246562-7296be56-15cb-41dd-a01d-f7db99cb3372.mp4

### Other notes

Eventually we can move to `UIImage.SymbolConfiguration` (needs iOS 15+) and define the symbol's colors, which is a simpler solution.

## Regression Notes
1. Potential unintended areas of impact
 - The site design picker when creating a new WordPress.com site from the app.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I tested the steps above manually on a device.

3. What automated tests I added (or what prevented me from doing so)
None.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
You can test the <strong>Jetpack</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/jetpack-installable-builds/'>here</a> with build number: <code>pr17868-a001683</code>. IPA is available <a href='https://appcenter-filemanagement-distrib5ede6f06e.azureedge.net/af83cef0-3f05-487b-af83-0421bcb3bb20/Jetpack%20Alpha.ipa?sv=2019-02-02&sr=c&sig=QF0W3cx9qyF5AjG87Quf099TCB7PkvNrMAZ%2B7nUtGLg%3D&se=2022-02-05T15%3A39%3A26Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

**Comment by jkmassel** [comment]
You can test the <strong>WordPress</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/WPiOS-One-Offs/'>here</a> with build number: <code>pr17868-a001683</code>. IPA is available <a href='https://appcenter-filemanagement-distrib4ede6f06e.azureedge.net/fd7c624f-4733-4e4f-a4a0-ad2896aac64b/WordPress%20Alpha.ipa?sv=2019-02-02&sr=c&sig=HFJPwwLDHFTWvJ3GM6A98DOLvoF5DjhPOnrsG2PGaNI%3D&se=2022-02-05T15%3A42%3A01Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

**Review by antonis — APPROVED** [review]
Great work @twstokes 👍 
I tested this on a iPhone SE 2020 (iOS 14.7.1) and everything worked as expected. The code changes also look consistent to me 🎉 

I also validated that the fix also applies to the page layout picker selector 👍 

<details>
<summary>Page layout picker before</summary>

https://user-images.githubusercontent.com/304044/152502592-8688511b-a924-4c8c-85fa-e174bf5e8a4a.mov
</details>

<details>
<summary>Page layout picker after</summary>

https://user-images.githubusercontent.com/304044/152502586-fd1757aa-bccc-4b28-9678-745bb9cfd621.mov
</details>

**Comment by twstokes** [comment]
> I also validated that the fix also applies to the page layout picker selector 👍

Thanks for highlighting that @antonis! I'll update the testing steps to include that view as well. 🙇

**Pull request merged**
