### PR TITLE
Posts: Moves blog post specific logic from BasePost into AbstractPost.

### LINKED ISSUE #5523: Posts: Move logic specific to AbstractPost into that model and out of BasePost
The BasePost model has quite a bit of code that is specific to AbstractPost and not shared by ReaderPost.  Mostly this is code related to publishing and publish status. Let's move the relevant logic into AbstractPost since its a better fit there.

### PR DESCRIPTION
**Pull request by aerych**
Closes #5523 
This PR just moves logic specific to AbstractPost to that class and out of BasePost.  I tried to organize the moved methods into related groups but not shuffle existing methods too much.  There are other opportunities for clean up but that's for another time. 

To test: 
Test the posts feature. Make sure you can sync, edit, etc without errors. 
Test the reader. Make sure you can sync and view post details without errors. 

Needs review: @diegoreymendez

### CODE REVIEW

**Comment by aerych** [comment]
Once this one is merged we can look at #5522

**Comment by diegoreymendez** [comment]
I think the unit tests need some fixes too.  This is what I'm getting on a "clean" build:

screen shot 2016-06-14 at 11 40 03 am

**Comment by aerych** [comment]
Sorry. I always for get the tests. :(  I'll ping ya when I've updated them.

**Comment by aerych** [comment]
@diegoreymendez Tests fixed.  At your leisure sir!

**Comment by diegoreymendez** [comment]
@aerych - Sorry for the big delay.  I'm reviewing this one now.

**Comment by diegoreymendez** [comment]
Nice work.  :shipit:

**Comment by aerych** [comment]
Thanks @diegoreymendez !

**Pull request merged**
