### PR TITLE
Issues/6332 flag and preserve inuse posts

### LINKED ISSUE #6332: Reader: Don't delete reader posts while they are in use.
This is a follow up to the crash described in #6297.  Ideally, when syncing is completed we do not want to have deleted from core data any posts the user was currently using. 

Let's add a new boolean field to ReaderPost called "inUse" or something similar and set it to true when a post is being used by a detail vc.  When a sync completes and the new posts are merged to core data, rather than deleting posts missing from a batch that are also marked as inUse, we'll just nullify their topic relationship.   This allows the post to continue to be present in core data for the user's needs, while still removing it from the posts for the topic.  Like any other "orphan" post it will be cleaned up during the next launch of the app (assuming its not needed for state restoration.)

This will be a more robust fix for situations like #6297 and we can then remove the band-aid patch in #6305.

### PR DESCRIPTION
**Pull request by aerych**
Fixes #6332 

To test:
Repeat the steps outlined in #6297.
Confirm that the post is not deleted (watch for the NSLog or set a breakpoint), that instead its topic is set to nil, and there is no crash.

Needs review: @koke would you mind since you are familiar with the issue?

Note: State restoration appears recently broken in develop on the iPhone (Swift 3 merge maybe?) so try testing via the iPad.

### CODE REVIEW

**Comment by aerych** [comment]
> Any sync that happens after that could delete the post, right

As state is restored the inUse flag will be set back to `true` for any post that's used in a restored reader detail.  Maybe a comment is needed to clarify why calling `markAllPostsNotInUse` during cleanup isnt necessarily a destructive action?

**Comment by koke** [comment]
Gotcha, I think it should work then. I don't think it's very likely to happen, but there's a small gap of time between the init and the reader detail restoration where something could delete the post. If we were to `markAllPostsNotInUse` from `application:didFinishLaunchingWithOptions` where state restoration is already complete this would be more robust. I'm not really sure if it's worth it but up to you. I'll test this tomorrow (or maybe later today)

**Comment by aerych** [comment]
> If we were to markAllPostsNotInUse from application:didFinishLaunchingWithOptions where state restoration is already complete this would be more robust.

I think that would end up clearing a desired `inUse` flag in a restored detail vc.

> there's a small gap of time between the init and the reader detail restoration where something could delete the post

True, but I agree its unlikely to happen.  During restoration ReaderPostServiceViewController will call `syncIfAppropriate` *before* the detail is restored (starting the process that will eventually delete posts), but the detail is still restored before the sync and subsequent merge can be performed.

Either way I'm keen to avoid adding more things to the app delegate if there is an alternative. :)

**Comment by koke** [comment]
I merged `develop` back in to have the changes in #6354 so it's easier to test 😄

**Comment by koke** [comment]
> instead its topic is set to nil

That might me think of a different scenario:

- Add a new tag to your reader that's not in the default list (e.g. swift)
- View a post from that tag
- Put the app in the background
- From a browser, remove that tag from you reader
- Relaunch the app, wait for the topic sync to delete the tag topic
- Interact with the (now faulted) post
- 💣💥  Crash

This one is a little trickier as not only the post gets invalidated but the parent stream as well. I'm happy to consider that a separate issue though

**Comment by koke** [comment]
I'm a bit confused about `inUse` vs `preserveForStateRestoration`. What's the difference? Do we need both or can we have just one flag?

**Comment by aerych** [comment]
> This one is a little trickier as not only the post gets invalidated but the parent stream as well. I'm happy to consider that a separate issue though

Sounds like we need to prevent inUse topics from being cleaned up the same as we do inUse posts.  Good catch. 

> What's the difference? Do we need both or can we have just one flag?

I love that you ask questions like this during reviews. :)  So often its been the right nudge to get me to rethink some preconceptions. 

My train of thought has been:
`preserveForStateRestoration` ensures content that would normally be cleaned up at launch (previewed topics and orphan posts from notifications) survive the clean up as they are still needed. 
`inUse` ensures content that is actively being used survives cleanup during a merge when it would otherwise be discarded, and to ensure the flag is never stale its reset globally at launch.

Two separate flags were needed only because of where the clean up is being performed at launch -- i.e. prior to state restoration completing.  But maybe changing this would improve the patch and let us use a single `inUse` flag.  We would still globally unset `inUse` when initializing the menu. As state restoration is processed the inUse flag will be reset where needed. Then we would perform the topic and orphan post cleanup by listening for the `UIApplicationDidFinishLaunching` notification.

Let me tweak this patch a bit and we can also address the issue with a deleted topic that you found.  There will be fewer model revisions that way and the topic issue is so similar to the post issue we might as well consider them related.

**Comment by aerych** [comment]
Closing in favor of #6355

**Pull request closed without merging**
