### PR TITLE
Integrates Aztec v1.3

### PR DESCRIPTION
**Pull request by diegoreymendez**
### Description:

Integrates Aztec v1.3. 

This integration includes the fixes listed in Aztec v1.3 and v1.3.1:

https://github.com/wordpress-mobile/AztecEditor-iOS/milestone/56?closed=1
https://github.com/wordpress-mobile/AztecEditor-iOS/milestone/59?closed=1

### Notes:

I'm using a commit number right now, but once this PR is validated I'll publish Aztec v1.3 and update this PR.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@loremattei - I'll retarget to 11.4 and ping you when ready.  Thanks.

**Comment by diegoreymendez** [comment]
@loremattei - Once this is merged, can we do another internal?

I'm not extremely happy about this being released into frozen so late, but it includes some important fixes we want out there sooner rather than later.

I'll try to have another release ready before the next code freeze.

**Comment by rachelmcr** [comment]
@diegoreymendez Thanks for the heads up about testing these fixes. I have been AFK so I'm catching up on a lot of things this week — I'll at least test the high priority toolbar fix in 11.4, and let me know if you think other fixes need special attention for internal testing.

**Comment by diegoreymendez** [comment]
I think this one is a good candidate for testing: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1082

Thanks @rachelmcr!

**Pull request merged**
