### PR TITLE
Improve performance of Cover block processor

### PR DESCRIPTION
**Pull request by fluiddot**
This PR follows the same approach taken in https://github.com/wordpress-mobile/WordPress-iOS/pull/22896 to improve the performance of Gutenberg processors. The overall improvement will be less significant in this case (that's why the PR is marked as `Enhancement` instead of `Bug`) mainly because the File block is used by fewer users than Image/Gallery blocks. Nevertheless, it will speed up the post-saving process.

**To test:**

Follow the testing instructions to cover the functionality related to the processors for the block:

* Cover Block:
  * [Close/Re-open post with an ongoing image upload](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/cover.md#closere-open-post-with-an-ongoing-image-upload)
  * [Close post with an ongoing image upload](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/cover.md#close-post-with-an-ongoing-image-upload)

## Regression Notes
1. Potential unintended areas of impact
The block processors are only used when saving a post. No other area should be impacted.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested saving a post with Cover blocks.

3. What automated tests I added (or what prevented me from doing so)
Unit tests of the Cover block have been updated.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by fluiddot** [comment]
While testing this PR, I spotted the issue https://github.com/wordpress-mobile/WordPress-iOS/issues/22901. I'll take the opportunity to address it here.

**Comment by irfano** [comment]
I'm moving this to the next milestone since this is not a blocker, and the code freeze will be completed today.

**Comment by momo-ozawa** [comment]
👋 Hey @fluiddot, I'm bumping this PR to 24.8 since it's code freeze day. If this PR needs to target 24.7, please target the release branch once it's been cut. Thanks!

**Pull request closed without merging**
