### PR TITLE
Enable siteCreationDomainPurchasing feature flag

### PR DESCRIPTION
**Pull request by salimbraksa**
Ref p1683908457918289/1683885303.015829-slack-C04M1NX8YCR

## Description

This PR enables the Domain Purchasing in Site Creation feature.

### 🅰️ Control Variation

Verify free sites can be created as before (regression test)

1. Install the Jetpack app & login
2. Tap the `▽` icon at the right of the site name on the `My Site` screen
3. Tap the `+` icon. at the top right on the Site picker screen
4. Select `⊕ Create WordPress.com site` on the modal dialog
5. Tap `Skip` at top right on the first step (topic screen)
6. Tap `Skip` at top right on the next step (theme screen)
7. Enter a random search query
8. Select a domain suggestion
9. Tap the green button that appears at the bottom
10. **Expect** to see the success screen
11. Tap the green button at the bottom
12. **Expect** to see the quick start full screen modal
13. Tap `No Thanks` button
14. **Verify** you end up on `My Site` viewing the newly created site

#### Prerequisites:
Go to **Abacus** (internal ref:  21064-explat-experiment) and assign to your test a8c-user the treatment variation.

1. Repeat steps `1`-`7` from control variation test case above
2. Select a **.blog** paid domain suggestion
3. Tap the green button that appears at the bottom
4. **Expect** to see the checkout page
5. Enter your payment details and submit for purchase
6. Repeat steps `10`-`14` from the control variation test case above

## Regression Notes
1. Potential unintended areas of impact
Creating a site with Free domain should tested for both **Control** and **Treatment** variations.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Existing unit tests and manual testing.

3. What automated tests I added (or what prevented me from doing so)
None.

## PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by antonis — APPROVED** [review]
Thank you for your work on this @salimbraksa  🙇
The introduced code change LGTM and work as expected 🎉
I've also verified that the build flag is used along with the experiment variation in all flows: `FeatureFlag.siteCreationDomainPurchasing.enabled && ABTest.siteCreationDomainPurchasing.isTreatmentVariation` 👍

**Comment by mokagio** [comment]
@antonis @salimbraksa out of curiosity, I see this PR uses the Abacus A/B testing infra, which is remote, but the feature flag is a build time one. Did you consider using a remote feature flag? (I had a scroll through the thread linked in the PR description, but I couldn't find a mention of the remote flag option).

**Comment by antonis** [comment]
Thank you for the ping @mokagio

> Did you consider using a remote feature flag?

Good point! We decided to use Abacus for A/B testing early in the project lifecycle instead of a remote feature flag. My understanding is that having two remote switches (Abacus and a remote feature flag) might have been an overkill. Revisiting this decision I think it might have been handy since we would have avoided this last minute PR.
@salimbraksa and @ovitrif might have extra context on this 🙇

**Comment by ovitrif** [comment]
> Good point! We decided to use Abacus for A/B testing early in the project lifecycle instead of a remote feature flag. My understanding is that having two remote switches (Abacus and a remote feature flag) might have been an overkill. Revisiting this decision I think it might have been handy since we would have avoided this last minute PR. @salimbraksa and @ovitrif might have extra context on this 🙇

Yup, a point I plan to add to the deltas of our retro on the project is that we should start to use remote feature flags from now on. The whereabouts of last week and the need of these PRs convinced me 😄

**Pull request merged**
