### PR TITLE
Design Review - Menus

### PR DESCRIPTION
**Pull request by kurzee**
This PR is for reviewing the Menus design implementation on iOS.

_DO NOT MERGE_

**Testing:**

- Build the `feature/menus-views` branch on a device or simulator.
- Menus supports all devices and tries to make use of as much screen space as possible.
- iPhone 4S and iPad have notable differences to standard iPhone 6 and Plus screen sizes.
- Menus works on both landscape and portrait orientations for all devices with varying layouts.

@mattmiklic Please review and let me know of any questions along the way.

### CODE REVIEW

**Comment by kurzee** [comment]
@mattmiklic one icon I need is the menus icon for the blog details cells. Currently it's using a placeholder icon from the "Blog Posts" cell, PDF `icon-menu-posts`.

screen shot 2016-03-30 at 2 01 25 pm

**Comment by kurzee** [comment]
screen shot 2016-03-30 at 6 45 30 pm

@mattmiklic love the reuse. I'll also create a separate PR that consolidates all of these to the single grid-icons files and tintColor.

Does theme icon seem a bit wider than the rest of the icons?

**Comment by mattmiklic** [comment]
> I'll also create a separate PR that consolidates all of these to the single grid-icon files and tintColor.

Awesome. We've got the entire Gridicons set being exported to PDFs in the gridicons repo now. https://github.com/Automattic/gridicons/tree/master/pdf

**Comment by mattmiklic** [comment]
> Does theme icon seem a bit wider than the rest of the icons?

It is a bit wider, but what you've got matches Calypso-web, so nothing to worry about here. We may look at addressing that inside of Gridicons.

**Comment by kurzee** [comment]
@mattmiklic I've pushed a slew of design changes and fixes for you to review fine sir.

- Scrolling performance should be super smooth now.
- The heights of menu items are expanded to be at 54px instead of 44px. We can certainly go back down to 44px, the standard, however this crowds the two line labels with long titles. We can definitely limit the labels to one line, but this might have the same issues of long titles being prefixed similarly to each other. Two lines offers a nice length, but requires a bit of padding overall.
- The detail view, for editing an item, needs some more design direction if you want to go more vanilla iOS than it currently is. The previous mockups clashed with the design in landscape on iPhone and in general on iPad. Be sure to test this out in all orientations on iPad and iPhone.
- I haven't moved the "Save" button to the top yet.

Let me know of further tweaks you'd like to make. I definitely may have missed some colors, sizing or font styles.

**Comment by kurzee** [comment]
@mattmiklic I've pushed new commits adding the "Save" button to the top right of Menus instead of in-line above the items.

Also, I noticed changing the item detail view's save button from "OK" to "Save" likely indicates that changes in the detail view will be saved remotely without having to press the primary save button after dismissal. We should probably go back to using "Done" or "OK" as is currently used on the web to indicate that the user is simply done editing the item but the changes are not yet saved to the site.

**Comment by mattmiklic** [comment]
- I think the "uses" dropdown needs to include an option for "no menu." If I currently have a menu area set to "no menu" in Calypso, I can change it to use a menu here, but I can't change it back.
- When I tap "Create a new menu", the menu name is changed to "Menu [x]", but all of the existing links are still there. If I create a new menu, I'd expect it to be empty rather than inheriting the contents of another menu (double-check to make sure this is how Calypso menus works)
- If I've made changes that haven't been saved, and I tap the Back button, I should be prompted to save or discard my changes. Should this be a Cancel button instead, for that reason? The Back Button seems to make sense because it matches the way all other sections are designed, but this is the only section of the app, besides publishing a post, that requires the user to tap a Save button to save their changes, all others are saved immediately.
- In landscape mode, tapping either the "menu areas" or "menus available" dropdowns opens both of them. This may be intentional since they're side by side, but it seemed a little bit strange because the "menus available" dropdown is much longer for my site, and it looked like the wrong item was animating in response to my touch.
- I think the detail view is in good shape, the customizations for landscape make sense, though it's definitely a little non-native I think it's the best we can do with the current design at this time.
- When opening one of the two dropdowns the chevron icon disappears; it would be nicer to use the "up" chevron when the dropdown is in an open state, to indicate that it can be tapped again to close it back. Animating the chevron to rotate 180º when it's opened/closed would be a nice touch.

> The heights of menu items are expanded to be at 54px instead of 44px. We can certainly go back down to 44px, the standard, however this crowds the two line labels with long titles. 
Would love to make single-line items 44px, and expand them if necessary for two-line titles. Not a huge deal though.

> We should probably go back to using "Done" or "OK" as is currently used on the web to indicate that the user is simply done editing the item but the changes are not yet saved to the site.
Seems fine.

**Comment by kurzee** [comment]
> Would love to make single-line items 44px, and expand them if necessary for two-line titles. Not a huge deal though.

I've pushed a commit that pulls this off. Originally I had some performance issues with this, but found a nice way to resolve it. Single line items are now 44px and double lines stretch a bit to fill their intrinsic size with padding. We can play with the padding a bit if needed.

**Comment by kurzee** [comment]
> If I've made changes that haven't been saved, and I tap the Back button, I should be prompted to save or discard my changes. Should this be a Cancel button instead, for that reason? The Back Button seems to make sense because it matches the way all other sections are designed, but this is the only section of the app, besides publishing a post, that requires the user to tap a Save button to save their changes, all others are saved immediately.

I did some experimenting with this and implemented the following:

1. When a change is made, the **Save** button is enabled in the top right and a new button takes over the back button as **Discard**.
2. When the **Save** button is hit and a save is successful, the **Discard** button reverts to the original back button.
3. When the **Discard** button is hit a confirmation alert for unsaved changes is presented.
4. When a user confirms the discard of changes, the **Discard** button disappears and the original back button reappears.
5. Also when discarding changes, the Menus and items re-sync with the server as kind of a hard reset.
6. The user can start over with editing, or go ahead and hit the back button to go back as usual.

The advantage here is that we don't mess around with the standard iOS back button, only hide it. This enforces a discard action, just like the web, and clearly communicates to the user what is going on. The other plus is it also doubles as a reset action so the user could revert and start over.

Modifying the iOS back button can be tricky and a bit hacky when combining the native _back_ action with some other action. I think this is a really smooth solution for now, until we nix a "Save" and "Cancel/Discard" altogether.

Let me know what you think @mattmiklic

**Comment by kurzee** [comment]
> When I tap "Create a new menu", the menu name is changed to "Menu [x]", but all of the existing links are still there. If I create a new menu, I'd expect it to be empty rather than inheriting the contents of another menu (this is how Calypso menus works)

This was a bug actually, fixed this to correctly create an empty menu.

**Comment by kurzee** [comment]
> When opening one of the two dropdowns the chevron icon disappears; it would be nicer to use the "up" chevron when the dropdown is in an open state, to indicate that it can be tapped again to close it back. Animating the chevron to rotate 180º when it's opened/closed would be a nice touch.

I've added this as an animation flipping the arrow along the Z axis, so flipping away/towards the screen. The rotation looked a bit strange, but here's the two for comparison @mattmiklic:

chevron_flip
chevron_rotation

**Comment by kurzee** [comment]
> In landscape mode, tapping either the "menu areas" or "menus available" dropdowns opens both of them.

This is now resolved by only opening one at a time and keeping the views top-aligned. Still looks a bit funky but we'll roll with it for now.

> I think the "uses" dropdown needs to include an option for "no menu."

I've added support for the "No Menu" option.

Menus is ready for the next round of review @mattmiklic, I think we're just about in good shape and ready to start the code review for the UI to start merging.

**Comment by mattmiklic** [comment]
> The advantage here is that we don't mess around with the standard iOS back button, only hide it. This enforces a discard action, just like the web, and clearly communicates to the user what is going on. The other plus is it also doubles as a reset action so the user could revert and start over.

Perfect. I think this is the best way to manage this interaction, given the user experience of Menus.

> I've added this as an animation flipping the arrow along the Z axis, so flipping away/towards the screen. The rotation looked a bit strange, but here's the two for comparison @mattmiklic:

Nice, I like the z-axis animation.

> This is now resolved by only opening one at a time and keeping the views top-aligned. Still looks a bit funky but we'll roll with it for now.

This is a good improvement, definitely feels a bit easier to understand.

> I've added support for the "No Menu" option.

Works well now.

**Comment by kurzee** [comment]
Thanks for all your insight and help @mattmiklic!

**Pull request closed without merging**
