### PR TITLE
Refactoring WPAnalyticsTrackerMixpanel's email update

### LINKED ISSUE #2984: Refactor WPAnalyticsTrackerMixpanel for updating email
Since we are [starting to store](https://github.com/wordpress-mobile/WordPress-iOS/pull/2977) `email` for default WordPress.com accounts, we probably don't need to do any checks for the existence of email in `WPAnalyticsTrackerMixpanel`. I wasn't absolutely sure about removing the whole logic for getting the user email so I haven't removed it in [that PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/2977). This might affect existing users somehow even though their accounts should have been setup by now. In any case I wanted to separate it just to make sure it's done properly.

@sendhil Could you take a look at this? You can let me know about the changes and I can handle it as well, if you prefer. Thanks!

### PR DESCRIPTION
**Pull request by sendhil**
Original version https://github.com/wordpress-mobile/WordPress-iOS/pull/3314
Fixes #2984 

cc @oguzkocer, @astralbodies

### CODE REVIEW

**Comment by sendhil** [comment]
@astralbodies  as per your comment about a unit test - I'm going to hold off for now. To get a proper unit test in there i'd have to redo some parts of `WPAnalyticsTrackerMixpanel` and I'm reluctant to do so this late in the game lest I break our stats :grin:

**Comment by sendhil** [comment]
Was referring to this comment - https://github.com/wordpress-mobile/WordPress-iOS/pull/3314#issuecomment-75756493

**Comment by oguzkocer** [comment]
The changes look good to me @sendhil! :shipit:

**Comment by astralbodies** [comment]
Looks good @sendhil :shipit:

**Pull request merged**
