### PR TITLE
Primary Site Order

### LINKED ISSUE #2599: Make default/primary site first in site selector & site lists
Since #2546 the concept of a default blog/site for an account exists.  Adjust the sort order of site lists so that the default site is at the top of the site selector and site listing under Me.  It might be good to put it in a separate section with a small gap under it to differentiate it from the rest subtly.

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes #2599

#### To test:
1. Launch WPiOS
2. Log into a WordPress.com with multiple blogs
3. Tap over My Sites Tab
4. Verify that the `Primary Blog` shows up on top

Needs review: @astralbodies 
Thanks in advance!

### CODE REVIEW

**Comment by astralbodies** [comment]
We should probably update `BlogSelectorViewController` as well to put the default site at the top.

**Comment by jleandroperez** [comment]
@astralbodies `BlogSelectorViewController` has been updated as well. Please, whenever possible, verify that:

1. The Primary Blog shows grouped, on top, when opening the Blog Selector from the `Post Editor`
2. There is no grouping when the Blog Selector is displayed from `Account Settings > Primary Site`

Thanks in advance!!

**Comment by astralbodies** [comment]
:shipit:!!

**Comment by jleandroperez** [comment]
Thank you sir!

**Pull request merged**
