### PR TITLE
Site Settings: Improve scroll performance

### PR DESCRIPTION
**Pull request by dvdchr**
Refs `p5T066-2yQ-p2#comment-9613` (& the threads)

This fixes a frame drop issue while accessing and scrolling in the Site Settings page. Upon investigation, this is because the `tableSections` method always returns a new array object, populated with various conditionals and potential expensive operations. The `tableSections` method is called on these methods:

- `numberOfSectionsInTableView:`
- `tableView:cellForRowAtIndexPath:`
- `tableView:didSelectRowAtIndexPath:`
- `tableView:heightForRowAtIndexPath:`
- `tableView:numberOfRowsInSection:`
- `tableView:titleForHeaderInSection:`
- `tableView:viewForFooterInSection:`

The fix was to turn `tableSections` into an `NSArray<NSNumber *> *` instance variable. This makes the current `- (NSArray *)tableSections` method a setter override, and the method body is only invoked when the variable is nil.

Note that the page supports pull to refresh, which calls `refreshData`. To properly repopulate `tableSections`, the variable is reset to `nil` in order to properly repopulate the value.

--- 
cc: @mokagio if this is cutting too close to the submission, just let me know and I'll update this to target 18.1 instead. Thank you! 🙂 

### Scenario 1: The page should no longer be laggy.
- Select a site where you're an Administrator
- Open Site Settings.
- Verify that the page feels buttery smooth ✨ 

### Scenario 2: Data should be refreshed with new changes upon pull to refresh.
- Select a site where you're an Administrator.
- Open Site Settings.
- Open wordpress.com from the web, go to Settings, and change the Site Name and Site Tagline. Tap Save.
- Go back to the app, and perform a pull to refresh on the Site Settings page.
- Verify that the page is updated with the newest changes.

## Regression Notes
1. Potential unintended areas of impact
Table sections having stale values after pull to refresh.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually verified that the content is updated on pull to refresh.

3. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dvdchr** [comment]
Huh, the tests failed due to Podfile.lock changes 🤔 . I'll try to revert it.

**Comment by ScoutHarris** [comment]
>  Huh, the tests failed due to Podfile.lock changes 🤔 . I'll try to revert it.

Yea, I was getting those changes too locally. You probably don't want to commit those. 😄 I had to completely reinstall pods to get it to stop happening. (`rm -rf Pods vendor && bundle install && bundle exec pod install`)

**Comment by dvdchr** [comment]
Thanks @ScoutHarris ! It's fixed now after removing all the pods. 🙂

**Review by ScoutHarris — APPROVED** [review]
Nice! LGTM.

:shipit:

**Comment by dvdchr** [comment]
Thanks @ScoutHarris. 🙇

**Pull request merged**
