### PR TITLE
Fix an issue with widget data sometimes showing zeros

### PR DESCRIPTION
**Pull request by kean**
Please refer to the original PR https://github.com/wordpress-mobile/WordPress-iOS/pull/21429. This one is a cherry-pick.

### CODE REVIEW

**Comment by mokagio** [comment]
@kean @staskus the 23.0.1 hotfix had already been [submitted](https://github.com/wordpress-mobile/WordPress-iOS/pull/21437#issue-1867863673) to the App Store for review at the time this PR was [opened](https://github.com/wordpress-mobile/WordPress-iOS/pull/21430#issue-1867409255).

I moved it against 23.1 pending approval of the PR from which this was cherry-picket. Let me know if that sounds good.

**Comment by kean** [comment]
Thanks, Gio. It doesn't seem major, so it should wait.

**Comment by mokagio** [comment]
@twstokes approved the PR against `trunk` https://github.com/wordpress-mobile/WordPress-iOS/pull/21429#pullrequestreview-1599361277.

He also added: "_I'd consider a release note for this one._"

+1. Considering the fix will land on 23.1, we should add it in that part of `RELEASE-NOTES.txt`. But it's good to keep in mind that _it won't be part of editorialized release notes_ which have already been submitted.

**Review by staskus — APPROVED** [review]
👍

**Pull request merged**
