### PR TITLE
Add more tracking to the Change Username flow

### LINKED ISSUE #17503: Project Thread: iOS App Data Coverage Followup
## Description
Improve our data quality and coverage.

### Login
- [x] ~The wpios_unified_login_failure passes the localized failure message to the failure property. When I segmented this to see the top errors the data is extremely difficult to decipher. If I wanted to make a funnel to see how many users hit a certain type of error I don’t think it would be possible with this property.~ We can use the `login_failed_to_login` `error_domain` and `error_code` for this

#### Change Username
- [x] Adding an event when the Change Username flow is presented, and the source it was presented from (epilogue, or account settings).: https://github.com/wordpress-mobile/WordPress-iOS/pull/17616
- [x] Similar to above, adding an event when the Change Username flow is dismissed/closed.: https://github.com/wordpress-mobile/WordPress-iOS/pull/17616
- [x] Adding an event when the user searches for a new username, and how many times they’ve performed a search could provide an interesting metric. How many searches do users make before making their final selection?: https://github.com/wordpress-mobile/WordPress-iOS/pull/17616

#### Post Sign Up Interstitial			
- [x] When I tap on any action it triggers a unified_login_interaction with the correct click type, however the step displayed as magic_link_requested even though it should be step success like is used on the Sign Up Epilogue: https://github.com/wordpress-mobile/WordPress-iOS/pull/17617

#### Add Site Buttons
- [x] Unfortunately, there is not an event that tracks when an add site button is tapped, or what the source was when the user enters the site creation flow: https://github.com/wordpress-mobile/WordPress-iOS/pull/17612

#### Blog Details / My Site Tab						
- [x] When you tap on the People section 2 of the same event is tracked but with different properties: https://github.com/wordpress-mobile/WordPress-iOS/pull/17514
🔵 Tracked: people_management_list_opened <blog_id: 193735397, site_type: blog>
🔵 Tracked: people_management_list_opened <>

#### Site Switcher									
- [x] Site switcher is presented: https://github.com/wordpress-mobile/WordPress-iOS/pull/17512
- [x] The user selects a site: https://github.com/wordpress-mobile/WordPress-iOS/pull/17512
- [x] The view is dismissed without select a site: https://github.com/wordpress-mobile/WordPress-iOS/pull/17512
- [x] The user taps the + button to add a site that includes the source the alert was presented from: https://github.com/wordpress-mobile/WordPress-iOS/pull/17512
- [x] A site is hidden from the list: https://github.com/wordpress-mobile/WordPress-iOS/pull/17512

#### Me / My Profile / Account Settings/ App Settings												
- [x] Add a new event that tracks when a settings value is changed: https://github.com/wordpress-mobile/WordPress-iOS/pull/17539
- [x] On the App Settings view, when you slide the ‘Max Image Upload Size’ to a new value. All the values in between are tracked which can result in lower quality tracking data. We should change this to only log the value when the user has finished their selection: https://github.com/wordpress-mobile/WordPress-iOS/pull/17523
- [x] Add new events that track when a user uses the ‘Clear’ buttons for Media Cache, Spotlight, and Siri Shortcuts.: https://github.com/wordpress-mobile/WordPress-iOS/pull/17539
- [x] We currently track when a user changes their app icon, however I think it could be useful if we also tracked which icon the user selected. : https://github.com/wordpress-mobile/WordPress-iOS/pull/17539
- [x] We can also add tracking when the user toggles crash reporting off or on.: https://github.com/wordpress-mobile/WordPress-iOS/pull/17539
- [x] The account closed button is tapped, and the account is closed: https://github.com/wordpress-mobile/WordPress-iOS/pull/17539
	
#### Stats															
- [x] The only action that is not tracked on the stats view is when you expand/collapse a section on the Post Stats view. The only reason I mention this is because each toggle on the main stats view sections is tracked. For consistency sake we should also track this as well.: https://github.com/wordpress-mobile/WordPress-iOS/pull/17552

#### Jetpack Settings																												
- [x] When a user changes the value of a setting: https://github.com/wordpress-mobile/WordPress-iOS/pull/17545
- [x] When the user taps the Learn More button: https://github.com/wordpress-mobile/WordPress-iOS/pull/17591

#### Posts															
- [x] Each action on this view is tracked, with the exception of tapping the share action in the more menu: https://github.com/wordpress-mobile/WordPress-iOS/pull/17522

#### Pages
- [x] Set as post page: https://github.com/wordpress-mobile/WordPress-iOS/pull/17553
- [x] Set as homepage: https://github.com/wordpress-mobile/WordPress-iOS/pull/17553
#### Sharing
- [x] Settings changes are tracked but toggling the ‘Edit sharing buttons’ option on/off doesn’t trigger the event.: https://github.com/wordpress-mobile/WordPress-iOS/pull/17555
#### People
- [x] When a filter is changed: https://github.com/wordpress-mobile/WordPress-iOS/pull/17555
- [x] When a person is invited along with a property that tracks which role they’ve been invited for: https://github.com/wordpress-mobile/WordPress-iOS/pull/17555
#### Site Settings
- [x] The user changes any settings value: https://github.com/wordpress-mobile/WordPress-iOS/pull/17545
	
#### Tab bar
- [x] "If you tap on the Saved section, I see a duplicate log: https://github.com/wordpress-mobile/WordPress-iOS/pull/17514
🔵 Tracked: reader_saved_list_shown <source: reader_filter, subscription_count: 54>
🔵 Tracked: reader_saved_list_shown <source: reader_filter, subscription_count: 54>"

#### Following Filter
- [x] When the view is opened: https://github.com/wordpress-mobile/WordPress-iOS/pull/17518
- [x] When a tab is selected: https://github.com/wordpress-mobile/WordPress-iOS/pull/17518
- [x] When a user selects a site: https://github.com/wordpress-mobile/WordPress-iOS/pull/17518
- [x] When a user selects a topic: https://github.com/wordpress-mobile/WordPress-iOS/pull/17518
- [x] When the filter is cleared: https://github.com/wordpress-mobile/WordPress-iOS/pull/17518

#### Manage
- [x] When the manage view is opened: https://github.com/wordpress-mobile/WordPress-iOS/pull/17518
- [x] Change the source when a user adds a filter: https://github.com/wordpress-mobile/WordPress-iOS/pull/17518
- [x] When following a site fails/ Log the error message: https://github.com/wordpress-mobile/WordPress-iOS/pull/17518

#### Search
- [x] When a user taps the 'clear search history' button: https://github.com/wordpress-mobile/WordPress-iOS/pull/17558
- [x] When a user performs a search we currently track reader_search_performed however I think we could also track which type of search they performed (Posts or Site, or an item from their history): https://github.com/wordpress-mobile/WordPress-iOS/pull/17558

#### Reader Card
- [x] If you tap the More button on the card, then turn on or off notifications I get 2 logs for: https://github.com/wordpress-mobile/WordPress-iOS/pull/17558/files
🔵 Tracked: followed_blog_notifications_reader_menu_off <blog_id: 182933070, subscription_count: 54>
🔵 Tracked: followed_blog_notifications_reader_menu_off <>

#### Reader Detail
- [x] When a link in an article is tapped: https://github.com/wordpress-mobile/WordPress-iOS/pull/17558/files
- [x] When an image is tapped: https://github.com/wordpress-mobile/WordPress-iOS/pull/17558/files

#### Reader Web View (WebKitViewController)
- [x] Is Presented: https://github.com/wordpress-mobile/WordPress-iOS/pull/17591
- [x] Is Dismissed: https://github.com/wordpress-mobile/WordPress-iOS/pull/17591
- [x] Open in Safari: https://github.com/wordpress-mobile/WordPress-iOS/pull/17591
- [x] Refreshed: https://github.com/wordpress-mobile/WordPress-iOS/pull/17591
- [x] Sharing: https://github.com/wordpress-mobile/WordPress-iOS/pull/17591
- [x] Navigation Actions (back / forward): https://github.com/wordpress-mobile/WordPress-iOS/pull/17591

#### Comments
- [x] When the comment field is expanded / collapsed: https://github.com/wordpress-mobile/WordPress-iOS/pull/17558/files
- [x] When a link is tapped: https://github.com/wordpress-mobile/WordPress-iOS/pull/17558/files

### Notifications			
- [x] Tapping the up and down arrows on the notification details view: https://github.com/wordpress-mobile/WordPress-iOS/pull/17558/files
- [x] Tapping a link on the notification detail view (Can be done in the WebKitViewController): https://github.com/wordpress-mobile/WordPress-iOS/pull/17591

### PR DESCRIPTION
**Pull request by emilylaguna**
Project #17503

Closes: #17503 

### Description
This adds 3 new tracking events to the change username flow:
- when it's displayed, and the source
- when it's dismissed, and the source
- when a user performs a search, and the number of searches performed, and the source

Since the change username flow is use differently in parts of the app I added the tracking to the `SignupUsernameTableViewController` which is always used when changing the username. 

### To test:
1. Launch the app
2. Logout
3. Create a new account
4. Once you get to the 'Signup epilogue' tap the 'Change username' item
5. Verify you see `🔵 Tracked: change_username_displayed <source: signup_epilogue>`
6. Perform a search,
7. Verify you see `🔵 Tracked: change_username_search_performed <search_count: 1, source: signup_epilogue>`
8. Perform a few more searches and verify the search_count reflects the number of searches you performed
9. Tap the back button
10. Verify you see `🔵 Tracked: change_username_dismissed <source: signup_epilogue>`
11. Continue into the app
12. Tap the My Site tab
13. Tap your user icon in the top right corner of the view
14. Tap on the 'Account Settings' item
15. Tap on the Username item
16. Verify you see `🔵 Tracked: change_username_displayed <source: account_settings>`
17. Perform a series of searches
18. Verify you see `🔵 Tracked: change_username_search_performed <search_count: 1, source: account_settings>`
    - Make sure the search_count goes up each time
19. Tap back and verify you see `🔵 Tracked: change_username_displayed <source: account_settings>`

### Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
None

3. What automated tests I added (or what prevented me from doing so)
None

### PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by momo-ozawa — COMMENTED** [review]
When I tap on the change username row in the Login Epilogue, the Change Username screen gets pushed onto the stack twice. 

```
2021-12-03 12:17:57:219 WordPress[2670:280473] 🔵 Tracked: unified_login_interaction <click: edit_username, flow: signup, source: default, step: success>
2021-12-03 12:17:57:248 WordPress[2670:280473] 🔵 Tracked: change_username_displayed <source: signup_epilogue>
2021-12-03 12:17:58:073 WordPress[2670:280473] 🔵 Tracked: unified_login_interaction <click: edit_username, flow: signup, source: default, step: success>
2021-12-03 12:17:58:690 WordPress[2670:280473] 🔵 Tracked: change_username_displayed <source: signup_epilogue>
2021-12-03 12:17:58:724 WordPress[2670:280473] 🔵 Tracked: change_username_dismissed <source: signup_epilogue>
```


https://user-images.githubusercontent.com/6711616/144601545-c6240cd9-de29-45cb-830a-9c980e061704.MP4

Otherwise, all other events worked as expected

**Comment by emilylaguna** [comment]
> When I tap on the change username row in the Login Epilogue, the Change Username screen gets pushed onto the stack twice.

That's odd. I'm not able to reproduce this on my end. Does this happen in the AppStore version of the app as well?

**Comment by momo-ozawa** [comment]
> That's odd. I'm not able to reproduce this on my end. Does this happen in the AppStore version of the app as well?

Hmmm! Not happening on the AppStore version for me.

FWIW I built and tested this PR on a real device. I didn't test on a simulator.

**Comment by emilylaguna** [comment]
@momo-ozawa Ah I figured it out and was able to reproduce this on the AppStore version:

1. Launch app, make a new account
2. On sign up epilogue, tap on the username field. You'll only be pushed once
3. Tap back
4. Tap on the Display Name
5. Tap done
6. Tap on the username field. You'll be pushed twice.

https://user-images.githubusercontent.com/793774/144639050-aae1b374-c4ab-4767-85ae-6898ccaf0756.mov

**Comment by emilylaguna** [comment]
@momo-ozawa since I'm able to reproduce this in production I went ahead and made an issue for this: https://github.com/wordpress-mobile/WordPress-iOS/issues/17624

**Review by momo-ozawa — APPROVED** [review]

**Pull request merged**
