### PR TITLE
Fix memory leak in domain flow

### LINKED ISSUE #20747: Memory leak in domain flow
### Expected behavior

Closing the domain flow should release all view controllers from memory.

### Actual behavior

Closing the domain flow leaves some view controllers in memory. I noticed this because when I had Safari open to inspect some of the flow's web views, the inspector didn't close automatically when I closed the flow. Xcode memory inspector also shows an increase in memory each time the flow is opened and Xcode's Debug Memory Graph shows the cause might a retain cycle.

- `RegisterDomainSuggestionsViewController` has a strong reference to `DomainSuggestionsTableViewController` via its `domainsTableViewController` property.
- `DomainSuggestionsTableViewController` has a strong reference back to `RegisterDomainSuggestionsViewController` via its `delegate` property.

### Steps to reproduce the behavior

1. Open the domain flow (e.g. via one of the domain dashboard cards or the My Site > Menu > Domains option
2. Tap into the domain search screen and then close the flow 
3. Notice that memory increases
4. Repeat Step 1 and 2 and notice that memory usage keeps increasing

### PR DESCRIPTION
**Pull request by staskus**
Fixes #20747

### Investigation

There were 2 main issues making `RegisterDomainSuggestionsViewController` not released from the memory:
- Using strong reference to the `RegisterDomainSuggestionsViewController` acting as a delegate for `DomainSuggestionsTableViewController`
- Referencing yourself in the closure:

```swift
 let viewController = RegisterDomainSuggestionsViewController()

viewController.domainPurchasedCallback = { domain in
     viewController.present(...)
}
```

## Solution

There're multiple possible solutions:

#### Referencing variable as weak:

```swift
 let viewController = RegisterDomainSuggestionsViewController()

viewController.domainPurchasedCallback = { [weak viewController] domain in
     viewController.present(...)
}
```

However, although this solution helps to solve the memory leak issue, it's error-prone and the code could get messy with multiple callbacks

#### Avoid using closures

We could refactor the coordinator to use a delegate pattern instead of closures, helping avoid the pitfalls of closures and potentially making the code structure more readable. However, this would generate more changes around the usage of coordinators so I decided not to choose this approach.

#### Pass self through the closure parameters

We could pass a self-reference through the closure parameters, allowing the creators of the closure to access self without creating a strong reference cycle.

I chose this approach, since it reliability helps avoid reference cycles while avoiding major restructuring of the code

```swift
 let viewController = RegisterDomainSuggestionsViewController()

viewController.domainPurchasedCallback = { viewController, domain in
     viewController.present(...)
}
```

### To test:

**Repeat with 3 flows:**
- Menu -> Domains
- Domain Dashboard Card (enable Domain Dashboard Card feature flag)
- Free to Paid Plans Card (enable Free to Paid Plans feature flag)

1. Make sure the navigation forward and back works
2. Make sure expected view controllers are presented or dismissed during the flow
3. After dismissing the flow, open Memory Debugger and make sure there're no instances of `RegisterDomainSuggestionsViewController`, `DomainSuggestionsTableViewController`, `PlanSelectionViewController`, `CheckoutViewController` still alive

## Regression Notes
1. Potential unintended areas of impact

Breaking the domain purchasing flow

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing and currently existing dashboard tests

3. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
👋 Hi @staskus, is merging this critical for [releasing plans](https://github.com/wordpress-mobile/WordPress-iOS/issues/20817)? I haven't gotten to this today yet and might leave this for tomorrow.

**Comment by staskus** [comment]
> 👋 Hi @staskus, is merging this critical for https://github.com/wordpress-mobile/WordPress-iOS/issues/20817? I haven't gotten to this today yet and might leave this for tomorrow.

@guarani, it's not critical but it would be nice to get this into production. Having a memory leak is not ideal, the domain flow wouldn't get deallocated after opening and closing it. 

Although it looks like many changes, I only passed `self` through all the callbacks to ensure we don't capture view controllers inside their own closures. This way the code structure and logic didn't change. This lowers the probability of this fix breaking the flow.

**Comment by staskus** [comment]
I'm increasing the milestone to `22.7` to indicate that it's not critical to include this into `22.6`

**Comment by guarani** [comment]
Thanks @staskus, I'll review this asap 👍

**Comment by staskus** [comment]
@guarani it would be great to include it in 22.8. Let me know if you won't be able to review it, I'll request other devs. Thanks! 👍

**Comment by guarani** [comment]
Sorry for the delay. I'll review this 👍

**Review by guarani — APPROVED** [review]
Thanks for fixing this and spotting the additional cause of the memory leak.

The code changes look good. Looking at the possible solutions, using `[weak viewController]` seems simpler than injecting the view controllers into each closure. However, I didn't try it out and this solution seems correct as well.

Here's what I tested:

- [x] Menu -> Domains
- [ ] ~~Domain Dashboard Card (enable Domain Dashboard Card feature flag)~~
- [x] Free to Paid Plans Card (enable Free to Paid Plans feature flag)

I didn't test the old card because as it was disabled in D113235-code for 22.6 onwards, it doesn't seem like we need to test it. Based on https://github.com/wordpress-mobile/WordPress-iOS/issues/20987, I think it'll be removed now at any time. Let me know if you think I should still test it though.

**Comment by staskus** [comment]
Thanks for testing!

> I didn't test the old card because as it was disabled in D113235-code for 22.6 onwards, it doesn't seem like we need to test it. Based on https://github.com/wordpress-mobile/WordPress-iOS/issues/20987, I think it'll be removed now at any time. Let me know if you think I should still test it though.

Yes, it's no longer necessary to test domain dashboard card cases.

**Pull request merged**
