### PR TITLE
Stats Traffic: Create Today card

### LINKED ISSUE #22393: Stats Traffic: Create Today card
Parent: https://github.com/wordpress-mobile/jetpack-issue-repo/issues/1
Image

### PR DESCRIPTION
**Pull request by staskus**
Fixes #22393

This is a card that should show 4 values. We already have such a card to show "All-Time" and "Today" views on Insights. According to designs (IqhXWz3Iir7RMb5XH5gGfZ-fi-108%3A4611) we should in fact have similar looking cards for both Insights and Traffic tabs

image

### Other similar cards

There's also Today Stats Dashboard card, that relies on complete different implementation. As Ravi pointed out (https://github.com/wordpress-mobile/WordPress-iOS/issues/22393#issuecomment-1892964654) it would make sense to update it as well. Created a separate issue for it https://github.com/orgs/wordpress-mobile/projects/222/views/7?pane=issue&itemId=50791091
image

## Solution

Instead of creating new card, update styles and spacing of `StatsTwoColumnRow` and `TwoColumnCell` which uses it to correspond to updates designs.

We can then use `TwoColumnCell` as a Today card in `StatsTraffic` view. We already have `StatsSummaryData` struct that will contain all the information we need.

## To test:

1. Open designs (IqhXWz3Iir7RMb5XH5gGfZ-fi-108%3A4611)
2. Open Jetpack app
3. Stats
4. Insights tab
5. Open Insights management and add all the cards
6. Compare `All Time` and `Today` cards with designs, this will be the look of `Today` card on Stats Traffic tab as well
7. Switch light/dark mode, increase font size, change orientation
8. Observe other cards as well

## Regression Notes
1. Potential unintended areas of impact

Breaking already created cards visually

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing

3. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by irfano** [comment]
I reviewed the updated design of the Today and All-Time cards. They look good!
- ✅ The design is updated despite the feature flag being disabled. But I think it's okay.
- ⚠️ The label's color was white in the dark mode before. Now, they are gray. I think they should be white. Do you think they're still readable in gray and should remain gray?

**Comment by staskus** [comment]
> ⚠️ The label's color was white in the dark mode before. Now, they are gray. I think they should be white. Do you think they're still readable in gray and should remain gray?

Thanks! Yes, I agree with you. I'll make the changes. 

Update:

In light mode, those labels used to be black so they become white in dark mode. Now they are grey so they remain grey on dark mode as well. What we should do, however, is to make sure cards such as "Latest Post Summary" also share the same style.

**Comment by irfano** [comment]
I believe gray can remain gray in the dark mode, but we should address the inconsistency. I see two logical options:
- Revert the label color to black.
- Change the label colors to gray for all cards.

**Comment by staskus** [comment]
@irfano 

> I believe gray can remain gray in the dark mode, but we should address the inconsistency.

I agree. I changed `the label colors to gray for all cards`, so both Latest Post Summary and already changed cards would have the same look.

**Review by guarani — APPROVED** [review]
The cards look great with the updated design.
Thanks @staskus and @irfano for the testing help!

**Pull request merged**
