### PR TITLE
Add specific reasons for ContextManager save: errors

### PR DESCRIPTION
**Pull request by nheagy**
Refs #12028 

One thing making #12028 hard to diagnose is that very little information is being reported. This change gives a unique error name for each specific core data error, and will also add multiple errors to the `reason` argument, if multiple are present.

**Note:** I couldn't find a great way to test this :( 

To test:
- kind of look over the code to suss out if it might work
- i tried really hard to find a good way to make CD save fail, but couldn't

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by jkmassel** [comment]
I'm moving this PR's milestone forward to `13.1`, which is the next unfrozen release branch. If we need it released sooner, please merge it into `release/12.9` or `release/13.0` and DM me and I'll be happy to include it in a beta or hotfix, as required.

ps – I'll try to get it reviewed this week for inclusion in `13.0`

**Comment by nheagy** [comment]
@jkmassel I updated the target on this one. Ready for your review!

**Comment by designsimply** [comment]
Thanks for working on this @nheagy! Since there are new reports of v13.0 crashing for some users (see https://github.com/wordpress-mobile/WordPress-iOS/issues/12338), I want to make sure we loop back to this PR to see if it can help. I will check in with @jkmassel today to see if he's available to help or find someone else if not!

**Comment by nheagy** [comment]
Thanks @jkmassel!

**Pull request merged**
