### PR TITLE
Fix/clarify site storage

### LINKED ISSUE #8926: Media: Clarify that disk quota refers to site storage and not device storage
This is cool and is great information for the user but when I first saw it, I wasn’t sure if that was the space on my phone as it says “0% of 6 GB used”. Maybe need to add “on your site storage” to the end so it is not confusing.

### PR DESCRIPTION
**Pull request by rfaile313**
Fixes #8926 

To test:

1. Head to My Site > Settings 
2. Scroll down to Media

screenshot

Notes: 
- At first I was trying to add more context but it looks terrible with anymore words added. i.e. 
screenshot
- Lines 34 and 37 are duplicate in `Localizable.strings` and I'm not sure what 37 affects. 34 changes the display in settings.
- It seems like a good idea to leave this alone for now in `Blog+Quota.swift` and `MediaService.m` as those cases seem to be related to a direct response of a user action. I think it would be harder to confuse this. Could be wrong.

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by rachelmcr** [comment]
>Lines 34 and 37 are duplicate in Localizable.strings and I'm not sure what 37 affects. 34 changes the display in settings.

Line 34 comes from the Site Settings View Controller:

https://github.com/wordpress-mobile/WordPress-iOS/blob/e1c351dcbed356604707938a81076b4f17e77fcb/WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m#L504

Line 37 is a slightly different string (includes the word "used") and comes from `Blog+Quota.swift`:

https://github.com/wordpress-mobile/WordPress-iOS/blob/4ac54edd8c4db2978a0122f97e137c755e627d4a/WordPress/Classes/Models/Blog%2BQuota.swift#L44

The first one is what you see under My Sites > Settings (in your screenshot), while the other is shown in the media section as a warning if you try to upload media when there isn't available space — you can see an explanation and screenshot in the PR that added it here: https://github.com/wordpress-mobile/WordPress-iOS/pull/8834

**Comment by rfaile313** [comment]
Hey @rachelmcr ! Thanks so much for taking a look at this! 

I thought it was odd how `Localizable.strings` was configured I should have realized it was a build file.

I saw those lines in `SiteSettingsViewController.m` and `Blog+Quota.swift`

Before I make the changes. How do you feel about changing it in both places? It seems like we only need to change the view controller as it might be more obvious during the upload that we're referring to site storage and not device storage.

**Comment by rachelmcr** [comment]
>How do you feel about changing it in both places? It seems like we only need to change the view controller as it might be more obvious during the upload that we're referring to site storage and not device storage.

Could you bring that up for discussion on the original issue? The original report refers to the string in `Blog+Quota.swift`, so it's worth clarifying if the confusion was originally from the settings screen or during media upload.

**Comment by rfaile313** [comment]
It was discussed in the original issue a bit:

>One thing to keep in mind – the string in Blog+Quota.swift is also used in MediaService.m to notify users that they don't have space for the object they're currently attempting to upload. Any text change here will need to be useful in both places, or we'll need to split them up :)

I guess for now I'll submit changes in both places and y'all can let me know 😄

**Comment by rfaile313** [comment]
Okay I think I have this one squared away.

> [WordPress-iOS/WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m](https://github.com/wordpress-mobile/WordPress-iOS/blob/e1c351dcbed356604707938a81076b4f17e77fcb/WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m#L504)

Changes "Settings" to clarify that the storage is on the site and not the device.

Test:

screenshot

> [WordPress-iOS/WordPress/Classes/Models/Blog+Quota.swift](https://github.com/wordpress-mobile/WordPress-iOS/blob/4ac54edd8c4db2978a0122f97e137c755e627d4a/WordPress/Classes/Models/Blog%2BQuota.swift#L44)

Changes the prompt when uploading to the media library to clarify the storage is on the site and not the device.

Test:

screenshot

**Comment by rachelmcr** [comment]
Those string changes look good to me. 👍 As a nitpick, there's an example included in the translator's note for each string that you could also update to match the new string. Up to you!

The only before merging this is that I'm seeing a message about a conflict on `Localizable.strings`; could you take a look at that to resolve the conflict?

**Comment by rfaile313** [comment]
Hey @rachelmcr I resolved the merge conflicts and updated the translator comments per our discussion 😄. Hoping this is good to go now 🚀

**Pull request merged**
