### PR TITLE
Adds support for photon quality. Reader uses medium quality.

### LINKED ISSUE #3081: Photon: Add the quality param to photon requests.
By default photon returns images at 100% quality. By specifying the quality in the request we can reduce the file size for faster downloads.  Pick a reasonable quality level to use as a default.

### PR DESCRIPTION
**Pull request by aerych**
Closes #3081

### CODE REVIEW

**Comment by aerych** [comment]
cc @jleandroperez

**Comment by aerych** [comment]
Quick note about the approach. I choose to use the different consts as a simpler implementation than defining one const and passing that value through the view hierarchy.  I think this is an indicator that we could do a bit more work to improve the reader view structure but there will be an opportunity for that as a party of calypsifcation.

**Comment by jleandroperez** [comment]
Looks great @aerych!

Just a minor note: Develop is still 4.8 (as far as i can tell we don't have a `release/4.8` branch yet). Maybe the milestone should be 4.8 instead?

:shipit: !!

**Comment by aerych** [comment]
Good call on the milestone. Switched to 4.8 as this isn't really a new feature addition (more of a performance tweak) and we'll have ample time for testing. 
Thanks @jleandroperez !

**Pull request merged**
