### PR TITLE
Log In: Display new login flow

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #n/a 
WPAuthenticator PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/111

This shows the new Log In flow added in the above WPAuth PR.

Previously, when 'Log In' was selected, the email entry view was immediately displayed. Now when 'Log In' is selected, a button view now appears with available options. These options then display the appropriate view.

---
**Old Log In**
old_flow

**New Log In**
new_flow

-----

**To test:**
- Run the app. Log out if necessary.
- Select 'Log In'.
- A button view should appear with log in options (as shown above).
  - Selecting 'Continue with Google' launches the existing Google auth flow.
  - Selecting log in by site address launches the existing self-hosted flow.
  - Select 'Continue with WordPress.com' shows a slightly modified email entry view.

**WordPress view:**
- The instruction text has been modified.
- 'Log in with Google' has been removed.
- Only the log in by site address option is displayed.

login_wp

Each login flow still follows their respective paths, so logging in should not be affected.

**Old flow:**
- To verify the old flow still works as expected:
  - In `WordPressAuthenticationManager:initializeWordPressAuthenticator`, change `showNewLoginFlow` to `false`.
  - Rerun the app. The old 'Log In' flow should display (as shown above).

---
Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@mattmiklic - this is what I'm going to call "v1" of the log in redesign. Meaning, it's my plan to use this flow to implement Sign In with Apple. After SIWA is complete, I'll circle back around to the remaining changes from [the design](https://wp.me/pauD4L-li-p2).

**Comment by ScoutHarris** [comment]
Hey @rachelmcr . I added you as a reviewer if you'd like to take a look at the UI test changes for the new flow. Thanks!

**Comment by ScoutHarris** [comment]
Thanks @rachelmcr !

**Comment by mattmiklic** [comment]
> @mattmiklic - this is what I'm going to call "v1" of the log in redesign. Meaning, it's my plan to use this flow to implement Sign In with Apple. After SIWA is complete, I'll circle back around to the remaining changes from the design.

This looks great! Plan makes sense. When you circle back around to pick up the remaining stuff, could you see if you can match the margin below the email input field to the margin above it? I think there should be ~16pt of space between the input and the "Or log in by entering your site address" text.

**Comment by ScoutHarris** [comment]
Thanks @mattmiklic !

> When you circle back around to pick up the remaining stuff, could you see if you can match the margin below the email input field to the margin above it? I think there should be ~16pt of space between the input and the "Or log in by entering your site address" text.

Ah, now that you mention it, it's obvious now. Yep, can do!

**Pull request merged**
