### PR TITLE
Posts: Fixes issue with post updating and status changes

### LINKED ISSUE #6113: Posts are published immediately when dateCreated matches dateModified
In `PostServiceRemoteREST`, this block of code creates an issue:

```
    if ([post.date isEqualToDate:post.dateModified]) {
        // publish immediately when date created matches date modified
        parameters[@"date"] = [[NSDate date] WordPressComJSONString];
    } else if (post.date) {
        parameters[@"date"] = [post.date WordPressComJSONString];
    } else if (existingPost) {
        // safety net. An existing post with no create date should publish immediately
        parameters[@"date"] = [[NSDate date] WordPressComJSONString];
    }
```

https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Networking/PostServiceRemoteREST.m#L375

The first condition, `if ([post.date isEqualToDate:post.dateModified])`, creates an issue where if an older post is slightly modified without the `dateModified` changing, and the user hits the "Update" button, the condition passes and the `date` parameter is set as the current date. This ends up changing the post to have been "published immediately" and appear as a new post in their post list, losing the original created date.
## Steps:
1. Find an older post in **Blog Posts**.
2. Edit that post.
3. Select the post options.
4. Add a tag to that post, go back.
5. Hit "Update" to update the post with the new tag you just set.
6. The post's created date has now been updated to the current date and lost its original date.

@aerych looks like you made the change last, can you take a peak and perhaps tweak it just a bit? There may be something else going on that expected the `post.date` to be == `post.dateModified` that you might be familiar with.

### PR DESCRIPTION
**Pull request by kurzee**
Fixes #6113, #3973, and partially #5992

This fixes two issues, one we were overriding the `"date"` for a remote post when it's modified date matched the `date`. This looks like it was added to help fix the issues in #5483 but _seems_ unnecessary and actually creates the issues seen in #6113 and #3973.

Second, this fixes an issue with the post filter not updating when opening the editor and changing the status of a post. Which will now select the correct filter, which it was trying to do before but never updated the UI. This addresses part of #5992.

To test:
- Follow the same steps seen in #5483, #6113, #3973, making sure the issues don't reproduce.
- Second, while testing, ensure that the expected filter list is selected when a post's status changes and the editor dismisses.

Needs review: @diegoreymendez can you take a whirl?
cc @aerych

### CODE REVIEW

**Comment by kurzee** [comment]
Note, I targeted this fix for landing in `6.7`, but perhaps it would be best to instead land in `6.8` and not rush it?

**Comment by diegoreymendez** [comment]
@kurzee - I think you're the best person to evaluate the risks related to pushing this in 6.7.  Whatever you decide will be fine for me.

**Comment by kurzee** [comment]
Thanks so much @diegoreymendez!

I've taken a deeper look at the testing issues you outlined and have come to the conclusion that those have made their way into dev between the original PR #5483 and now, or were already present. I think those are largely side affects with the issue of how we manage statuses and dates for posts. I think it'd be best to leave those alone for this PR, especially for merging into this `release/6.7`.

>@kurzee - I think you're the best person to evaluate the risks related to pushing this in 6.7. Whatever you decide will be fine for me.

I think it would be best to merge this now rather than later, I think the risk of letting these bugs proliferate further outweighs any potential oversights in the changes (which I don't think there are).

**Comment by kurzee** [comment]
Closing this one for now to address our primary date issue separately, and to not rush it into 6.7.

**Pull request closed without merging**
