### PR TITLE
Fixes for Xcode 6.3/Swift 1.2 #3514

### PR DESCRIPTION
**Pull request by nheagy**
Builds and tests pass on my machine 😉

## Changes due to Swift 1.2
- force downcasts
- can't rely on bridging from NSString to String anymore
- no more convenience init() in UIView and UIImageView
- same for tests

## Note
Travis-CI can't yet run Xcode 6.3 and Swift 1.2 (see [their issue 3216](https://github.com/travis-ci/travis-ci/issues/3216)), which means this PR will fail to build there.

### CODE REVIEW

**Comment by aerych** [comment]
cc @astralbodies and @sendhil

**Comment by sendhil** [comment]
Let's hold off on this for now while we wait for Xcode 6.3's bugs to stabilize.

**Comment by sendhil** [comment]
Hey @nheagy  - we really appreciate this PR and we're super excited to try out Swift 1.2 but the reason I decided to hold off on this was we think that Xcode 6.3 introduced a few deal killer bugs for now and forcing the upgrade to 1.2 would mean those of us still on 6.2 would be unable to compile our app. That being said, we'll probably start a branch here soon for the swift 1.2 changes and maybe you could re-submit your changes there?

**Comment by nheagy** [comment]
@sendhil sure, when I notice the new branch I'll resubmit.

**Comment by sendhil** [comment]
Hey @nheagy - we're getting close to bumping up to 6.3. Would you mind re-submitting this against `develop`?

**Comment by nheagy** [comment]
Ok, @sendhil: #3554

**Pull request closed without merging**
