### PR TITLE
Reader: Enable the Reader Improvements v1 feature flag

### LINKED ISSUE #21761: Reader Improvements: Enable the Reader Improvements v1 feature flag
Enable the `readerImprovements` feature flag.
```[tasklist]
### Tasks
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21771
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/21772
```

### PR DESCRIPTION
**Pull request by wargcm**
Closes #21761 
Relies on: #21771
Ref: pcdRpT-3Eb-p2

## Description

- Enables the Reader Improvements v1 feature flag
- Fixes the Reader UI tests after enabling the new changes

## Testing

To test:
- Perform a fresh installation of Jetpack to prevent any overridden feature flags
- Login
- Tap on Reader
- Go through the various screens and cards
- 🔎 **Verify** all the screens and cards from the PT (pcdRpT-3Eb-p2) are now enabled

## Regression Notes
1. Potential unintended areas of impact
Reader

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dvdchr** [comment]
Unit test failed with error:

```
testSyncBlogsAndSignOut() in BlogJetpackTests (3 times)
  Asynchronous wait failed: Exceeded timeout of 1 seconds, with unfulfilled expectations: "Blogs sync". (#CharacterRangeLen=0)
```

I've retried the test for now and will do further investigation if it fails again.

---

**Update**: Looks like it passed.

**Review by dvdchr — APPROVED** [review]
Tests are passing. Smoke tested with and without the feature flag, and found nothing out of the ordinary. LGTM :shipit:

**Comment by mokagio** [comment]
Took over merging to make sure this PR marked for [23.5](https://github.com/wordpress-mobile/WordPress-iOS/milestone/259) made it on `trunk` before I started the code freeze.

**Comment by dvdchr** [comment]
Thank you @mokagio, appreciate it! 🙂

**Pull request merged**
