### PR TITLE
Migrate WPWebViewController and SharingAuthorizationWebViewController to WKWebView.

### LINKED ISSUE #13179: Migrate WPWebViewController to WKWebView
Tasks:

- [x] Replace UIWebView and any related code with WKWebView.
- [x] Replace UIWebViewDelegate implementation.

## Dependencies:

This issue will most likely need to be resolved together with https://github.com/wordpress-mobile/WordPress-iOS/issues/13181

### LINKED ISSUE #13181: Migrate SharingAuthorizationWebViewController to WKWebView
`SharingAuthorizationWebViewController` subclasses `WPWebViewController`, and reimplements some of the methods from `UIWebViewDelegate`.

We need to update / replace these methods.

## Dependencies:

This issue will most likely need to be resolved together with https://github.com/wordpress-mobile/WordPress-iOS/issues/13179

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes #13179
Fixes #13181 

Migrates both `WPWebViewController` and `SharingAuthorizationWebViewController` to `WKWebView`.

## Notes for testing:

I recommend checking out `WordPress-iOS` in another branch so you can test this PR alongside `develop`. Some things may look broken at first but behave just like the original (for example I couldn't connect Facebook).

## Testing:

1. Go to "My Sites"
2. Select a site from your list of sites.
3. Tap on "Sharing"
4. Tap on any of the services.
5. Tap "Connect" and go through the steps.

Read "Notes for testing" if you find anything broken.

## PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by loremattei** [comment]
Hey! I moved this to 14.2 because 14.1 has been cut. Please, ping me if you want it to make it to 14.1 😀

**Comment by diegoreymendez** [comment]
@leandroalonso - That was an extremely good catch!  This PR is ready for another look.

**Comment by diegoreymendez** [comment]
Yeah - although one was created just 1 hour ago: https://github.com/wordpress-mobile/WordPress-iOS/issues/13306.

Thanks for the review @leandroalonso .

**Comment by diegoreymendez** [comment]
I've restored this branch to run some tests.  Please don't delete for now.

**Pull request merged**
