### PR TITLE
Notifications > Comment details header: fix misc issues

### PR DESCRIPTION
**Pull request by ScoutHarris**
Ref: #17790 

This fixes a few issues with the Comment details header when displayed in Notifications:
- Tapping the header now always shows the comment thread with the notification comment highlighted.
- When viewing the threaded comments, the nav back button now has no label. Previously, it would display the previous view's title - Reply, Mention, etc.
- When navigating through the Comment notifications via the previous/next buttons, the header now updates for the displayed comment.

To test:

**Header tapping:**
- Enable `notificationCommentDetails`.
- Go to Notifications > Comments.
- Select any notification.
- Tap the header.
- Verify the threaded comments are displayed, and the notification comment is highlighted.
  - Note: sometimes the comment is not highlighted/scrolled to as it seems that action can happen before the comment is loaded. This is a legacy issue, not introduced here.
- Verify the back nav bar button has no label.

**Header updating:**
- Go to Notifications > Comments > select a notification.
- Tap the previous/next buttons on the nav bar.
- Verify the Comment detail header is updated for the Comment being displayed.
- Note: This is not specific to the new Notification Comments. The same behavior can be seen when moderating comments from My Site > Comments, and selecting `Next` on the confirmation notice.

## Regression Notes
1. Potential unintended areas of impact
N/A. Feature is disabled.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
There is still one more issue with the header (that I'm aware of). Some reply notifications don't have the parent information where it's expected 🤦 , resulting in Comment Details thinking it's a post comment. So the header says `Comment on` instead of `Reply to`. The parent information is contained elsewhere in the notification content, so I think I can dig it out. But I'll do it separately.

**Review by dvdchr — APPROVED** [review]
Tested and it works! LGTM. I wanted to clarify about this:

> When navigating through the Comment notifications via the previous/next buttons, the header now updates for the displayed comment.
> ...
> Note: This is not specific to the new Notification Comments. The same behavior can be seen when moderating comments from My Site > Comments, and selecting Next on the confirmation notice.

Looks like I might be misunderstanding this 😅 , but are you saying that before this PR, the comment detail header doesn't update its values ("Comments on", "Reply to John Doe" and the text below it) after navigating to the next comment (either through Notification pagination, or Site Comments' snackbar Next button)?

The reason I asked is because it works fine in `trunk`, so I got confused and wanted to make sure 😅 .

**Comment by ScoutHarris** [comment]
> The reason I asked is because it works fine in trunk

Sorry to be unclear. This is what I meant:
- Go to My Site > Comments.
- Select a comment. Note the header.
- Moderate the comment. 
- Select `Next` on the confirmation notice.
- Before this fix, the header did not change to match the next comment. The comment content did, but the header did not. 

I retested on `trunk` again to be sure, and I do see the problem there (as well as the app store version).

**Comment by dvdchr** [comment]
> I retested on trunk again to be sure, and I do see the problem there (as well as the app store version).

@ScoutHarris Thanks for clarifying! Looks like I wasn't thorough in verifying that 😅 . When navigating from a post comment to a post comment (different post), it works as expected; tapping the header also leads to the correct post. However, when navigating from a post comment to a reply comment (or vice versa), the header bugged out just as you described.

In any case, thank you for fixing my oversight!! 👍

**Comment by ScoutHarris** [comment]
> When navigating from a post comment to a post comment (different post), it works as expected

Ah! I hadn't noticed that. Now I can see the confusion. I guess I got "lucky" with my comments. 😆

**Pull request merged**
