### PR TITLE
Fixes a memory issue in our share extension.

### LINKED ISSUE #16731: Crash when sharing from screenshot
### Expected behavior
no crash, share to WP

### Actual behavior
crash and cannot share from screenshot

### Steps to reproduce the behavior
**This goes at least as far back as 17.2**
1. Take a screenshot
2. Tap on the screenshot in the bottom left corner
3. Share
4. WP
5. Crash

Uploading RPReplay_Final1624490949.MP4…

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/16731

Fixes a crasher in the Share Extension.

## To test:

Execute the steps in the original issue, which I report here to make the review simpler:

1. Take a screenshot
2. Tap on the screenshot in the bottom left corner
3. Share
4. WP
5. Crash

## Regression Notes

1. Potential unintended areas of impact

None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by leandroalonso — APPROVED** [review]
Reproduced the bug on the current beta version: ☑️
Tested the same behavior on this branch and it works fine, no crashes: ☑️

**Comment by diegoreymendez** [comment]
Thanks @leandroalonso !

**Comment by diegoreymendez** [comment]
I'll give some time for @mokagio to chime in if he wants, and I'll merge tomorrow morning.

**Comment by diegoreymendez** [comment]
Sorry folks I just realized this should instead be targetted at 17.6.  I've created another PR here: https://github.com/wordpress-mobile/WordPress-iOS/pull/16744

**Pull request closed without merging**
