### PR TITLE
Notifications Control Center: Master PR

### LINKED ISSUE #3807: Notifications Control Center
#### Notifications Control Center
The new Notifications Control Center allows our users to control at a granular level what kind of notifications they'd like to receive for each one of their sites per stream: Push Notifications, Emails, and WordPress.com Timeline.

You may find a [Sample Mockup Here](https://marvelapp.com/1d6ab96#5175476). Given the size of this feature, we've split the work in several Pull Requests, each one dealing with a different layer / aspect of the feature. Test scenarios have been detailed, in each one of the Pull Requests.

Please, note that **no code** has been directly pushed to the main feature branch.

--

**Service Layer: PR #3917 (Merged!)**
- [x] Implement **NotificationsService**: Retrieve / Update Settings API
- [x] Implement Unit Tests for the new Service.

**Interface Layer: PR #3929 (Merged!)**
- [x] Implement a new **NotificationSettingsViewController**, to render / update the settings.
- [x] Update EditSiteViewController: Remove Push Notifications Row

**Disabled Push Notifications: PR #4138 (Merged!)**
- [x] After tapping the Push Notifications Settings Row, whenever Notifications are disabled, let's open WPiOS's Settings.app section. (iOS 8)
- [x] Since the above is not technically possible in iOS 7 devices, let's display a popup indicating how to enable Push Notification Settings.

**Event Trackers: PR #4068 (Merged!)**
- [x] Wire Analytics events, to be incremented everytime each of the new screens is rendered.

**Cleanup: PR #3997 (Merged!)**
- [x] Make sure that legacy settings (**key: notification_preferences**) are removed from User Defaults.

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:
This PR represent the sum-up of several smaller PR's, which have been already reviewed, verified and merged altogether into the `feature/3807-notifications-control-center` branch.

- #3917: Service Layer
- #3929: Interface Layer
- #4138: Disabled Push Notifications Handling
- #4068: Events Trackers
- #3997: Code Cleanup

Since no code has been pushed directly into the `feature/3807-notifications-controlcenter` (other than merge conflict resolutions), i'm pasting below the sum of all of the test cases that have been verified.

Closes #3807
Needs Review: @sendhil @diegoreymendez @SergioEstevao @aerych @astralbodies 

--

#### Test Scenario A: Nuked Legacy Push Switch
1. Launch WPiOS and log into a Dotcom Account
2. Tap over `My Sites`
3. Pick any site
4. Tap over Settings

Make sure that the `Push Notifications` Flip Switch Cell is gone.

-- 

#### Test Scenario B: Notification Settings only for Dotcom
1. Launch WPiOS and log into a Self Hosted site
2. Tap over the `Me` Tab
3. Note that there shouldn't be a `Notifications` row.
4. Log into your WordPress.com account

As a result, the `Notifications` row should show up.

--

#### Test Scenario C: Manage Notifications
1. Launch WPiOS and log into a dotcom account
2. Tap over the `Notifications` tab

The top right icon (`Manage`) should be gone.

--

#### Test Scenario D: Load More Settings
1. Launch WPiOS
2. Log into an account that has +3 DotCom blogs
3. Tap over `Me` > `Notifications`
4. Note that only the first three blogs should show up
5. Tap over the `View All...` cell

As a result, all of the blogs that support Notifications should show up. Please, test this scenario in both, iPad + iPhone.

--

#### Test Scenario E: Primary Blog
1. Launch WPiOS and log into a dotcom account
2. Tap over `Me` >  `Notifications`

Verify that the Primary Blog should show up on top.

--

#### Test Scenario F: Updating Settings
1. Launch WPiOS and log into a dotcom account
2. Tap over `Me` >  `Notifications`
3. Open the settings for any of your blogs
4. Change a setting
5. Hit `Back` until you reach the main `Me` tab
6. Open the Notification Settings for the site that you just updated

As a result, the updated settings should be onscreen.
Please, repeat this procedure for `Other Sites` and `WordPress.com` sections as well

--

#### Test Scenario G: Update Error Handling
1. Launch WPiOS and log into a dotcom account
2. Tap over `Me` >  `Notifications`
3. Open the settings for any of your blogs
4. Change a setting
5. Enable your phone's *airplane mode*
6. Hit back

As a result, you should get an alertView indicating that there was an error. This alertView should allow you to `Retry` / `Cancel`.

--

#### Test Scenario H: Load Error Handling
1. Launch WPiOS and log into a dotcom account
2. Enable your phone's *airplane mode*
3. Tap over `Me` >  `Notifications`

As a result, you should get an alertView indicating that there was an error loading your settings. This alertView should allow you to `Retry` / `Cancel`.

--

#### Test Scenario I: Disabled Push Notifications in iOS 7 
1. Launch WPiOS in a iOS 7 device (OR simulator)
2. Make sure that Push Notifications for WPiOS are disabled
3. Open `Me` > `Notifications`
4. Attempt to open the `Push Notification` Settings for any of your blogs

As a result, you should get a nice AlertView indicating that Push Notifications are disabled. Switch to Settings.app and enable Push Notifications.

After going back to WPiOS, the Push Notifications row should be enabled.

--

#### Test Scenario J: Disabled Push Notifications in iOS 8
1. Launch WPiOS in a iOS B device (OR simulator)
2. Make sure that Push Notifications for WPiOS are disabled
3. Open `Me` > `Notifications`
4. Open the `Push Notification` settings of any of your blogs

As a result, the interface should display a row that reads `Go to iPhone Settings`, and the tableView footer should detail what's going on..

Please, go to Settings.app, enable Push Notifications, and bring WPiOS to foreground. Note that the view should refresh automatically, and you should be able to update the settings.

--

#### Test Scenario K: Enabled Push Notifications
1. Launch WPiOS in a iOS B device (OR simulator)
2. Make sure that Push Notifications for WPiOS are **enabled**
3. Open `Me` > `Notifications`
4. Open the `Push Notification` settings of any of your blogs

Note that the app should allow you to update anything, and no popup (or tableView Footer) should show up. Please, verify in both iOS 7 and 8.

### CODE REVIEW

**Comment by sendhil** [comment]
@jleandroperez I got a crash while testing the first scenario :\. Note that it happened on my device but I was able to reproduce it on my simulator.

Here's a video:
https://cloudup.com/cFWYwnL8zoS

Here's the stack trace:
```
2015-08-21 18:54:46.143 WordPress[98641:11654357] -[__NSCFBoolean isEqualToString:]: unrecognized selector sent to instance 0x6a72f60
2015-08-21 18:54:46.147 WordPress[98641:11654357] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean isEqualToString:]: unrecognized selector sent to instance 0x6a72f60'
*** First throw call stack:
(
	0   CoreFoundation                      0x067f4746 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x0647da97 objc_exception_throw + 44
	2   CoreFoundation                      0x067fc705 -[NSObject(NSObject) doesNotRecognizeSelector:] + 277
	3   CoreFoundation                      0x06743287 ___forwarding___ + 1047
	4   CoreFoundation                      0x06742e4e _CF_forwarding_prep_0 + 14
	5   WordPress                           0x0024a159 -[BlogServiceRemoteREST remoteBlogSettingFromJSONDictionary:] + 713
	6   WordPress                           0x00248350 __61-[BlogServiceRemoteREST syncSettingsForBlog:success:failure:]_block_invoke + 256
	7   WordPress                           0x005ac59b __64-[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke46 + 43
	8   libdispatch.dylib                   0x072995ea _dispatch_call_block_and_release + 15
	9   libdispatch.dylib                   0x072bbbef _dispatch_client_callout + 14
	10  libdispatch.dylib                   0x072a16bb _dispatch_main_queue_callback_4CF + 993
	11  CoreFoundation                      0x0674d8ee __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	12  CoreFoundation                      0x0670b5f0 __CFRunLoopRun + 2256
	13  CoreFoundation                      0x0670aa5b CFRunLoopRunSpecific + 443
	14  CoreFoundation                      0x0670a88b CFRunLoopRunInMode + 123
	15  GraphicsServices                    0x07f802c9 GSEventRunModal + 192
	16  GraphicsServices                    0x07f80106 GSEventRun + 104
	17  UIKit                               0x043090b6 UIApplicationMain + 1526
	18  WordPress                           0x00104d39 main + 73
	19  libdyld.dylib                       0x072e6ac9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by jleandroperez** [comment]
@sendhil `BlogServiceRemoteREST` has been untouched in this PR. I've filed another [issue here](https://github.com/wordpress-mobile/WordPress-iOS/issues/4187) to address it.

Thank you!

**Comment by jleandroperez** [comment]
@sendhil #4189 reviewed + merged + merged into this branch. Should be good to go!

**Comment by sendhil** [comment]
:shipit:

**Pull request merged**
