### PR TITLE
[Gutenberg] Highlight text bug fixes

### PR DESCRIPTION
**Pull request by geriux**
**Related PRs:**
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/6517
- https://github.com/WordPress/gutenberg/pull/57650
- https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1352

Fixes several issues related to the Highlight text formatting in the Gutenberg editor.

-----

## To Test:

Please check the testing instructions in the [Gutenberg PR description](https://github.com/WordPress/gutenberg/pull/57650).

-----

## Regression Notes

1. Potential unintended areas of impact

    - It should only affect the editor.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing, and integration tests in both Aztec and Gutenberg.

3. What automated tests I added (or what prevented me from doing so)

    - Visual E2E tests added in Gutenberg Mobile.

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing [24.3](https://github.com/wordpress-mobile/WordPress-iOS/milestone/271) today and it seems like this has not been approved yet.

For the record, I also checked the [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/57650) in the hope that it was already merged and shipped, meaning this PR could be closed as the changes would be fetched as part of the next Gutenberg release, but that was not the case.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by geriux** [comment]
Hey @twstokes 👋 I was wondering if you'd be able to review this PR if you have some time. It only updates the Aztec and Gutenberg references, although it won't be merged until both Gutenberg Mobile and Aztec have their new tag released with the new changes. Thank you!

**Review by twstokes — APPROVED** [review]
Looks right to me @geriux! 🚀

**Pull request merged**
