### PR TITLE
Modernize the push notification sound

### LINKED ISSUE #9594: Modernize the push notification sound
It's 2018 and the push notification sound from 2009 is ... well ... dated.

Find something pleasant that isn't piercing and sounds like it wasn't recorded through a coffee can.

### PR DESCRIPTION
**Pull request by astralbodies**
Fixes #9594 

Updates the sound file for push notifications to something relatively similar in nature of a higher quality.

To test:

1. Install on a device.
2. Make sure a dev push notification server is up and running in someone's WordPress.com developer sandbox.
3. Send a push notification to your device.

### CODE REVIEW

**Comment by loremattei** [comment]
Hey! I moved the milestone to 10.4 since 10.3 has been cut. Please, feel free to move it back to 10.3 if it has to land there: just update it to target the release branch and ping me to update the build!

**Comment by astralbodies** [comment]
@loremattei I'm putting this PR on hold as there might be licensing issues.

**Comment by astralbodies** [comment]
Will need a different source for the new file. Drat.

**Comment by aerych** [comment]
Boo 😭

**Comment by loremattei** [comment]
😢

**Pull request closed without merging**
