### PR TITLE
Stats: add File Downloads to Core Data

### LINKED ISSUE #11963: [Stats Refresh] Period: add File Downloads stats
Add _File Downloads_ Period stat.

- Add card to bottom of Period table.
- `View more` option to show details.
- Add new Track event(s).
- Add support in WPKit for `/sites/$site/stats/file-downloads` query. (https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/stats/file-downloads/)
- Save to Core Data.

Design from [P2](https://wp.me/paCL20-cM):
file_downloads_design

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #11963 
WPKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/175

To test:
- Go to Stats period.
  - Verify File Downloads now has data. (This verifies the WPKit change.)
  - FD is not live in Calypso yet. Data can be verified via the console with the `file-downloads` endpoint. Ex: `/sites/<site_id>/stats/file-downloads?period=day&date=2019-08-05&num=1`
  - The filenames are displayed as-is. I've inquired on the FD P2 exactly how filenames are going to be displayed/formatted in Calypso, and will make any adjustments with a future change if necessary.

file_downloads

- Disable your network.
  - Return to stats.
  - Verify File Downloads has data.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@SylvesterWilmott  - screenshots:

iphone

ipad_portrait

ipad_landscape

**Comment by SylvesterWilmott** [comment]
Looks good @stephenie thanks.

>The filenames are displayed as-is. I've inquired on the FD P2 exactly how filenames are going to be displayed/formatted in Calypso, and will make any adjustments with a future change if necessary.

Is there a possibility that we can ditch the path and only show the actual filename for this version?

**Comment by ScoutHarris** [comment]
Hey @SylvesterWilmott .

> Is there a possibility that we can ditch the path and only show the actual filename for this version?

Removing the path creates a potential for duplicate filenames. I did ask on the FD P2 if improvements could be made to the filename.

**Comment by ScoutHarris** [comment]
Hey @danielebogo .

> I noticed only that the text is truncated if it's too long but I think it's the current behaviour for all the rows right?

Yep, you are correct.

**Pull request merged**
