### PR TITLE
Enable performance monitoring

### PR DESCRIPTION
**Pull request by wzieba**
This PR enables Performance Monitoring in the app.

To test:
1. Open `WPCrashLoggingProvider`
2. Update `sampler` to `{ 1.0 }` and `profilingRate` to `1.0`
3. Run the app in Release variant
4. Verify that in Sentry Performance and Profiling tabs there are new reports generated by your device.

## Regression Notes
1. Potential unintended areas of impact

5. What I did to test those areas of impact (or what existing automated tests I relied on)

6. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by wzieba** [comment]
@mokagio hi Gio! Friendly ping in case you missed this PR - do you think we could merge it this or next week? 🙂

**Comment by guarani** [comment]
👋 I bumped the milestone because this doesn't seem like a blocker for the 25.0 release cut today.

**Review by mokagio — APPROVED** [review]
Hey @wzieba ! Sorry for the late followup. Missed this due to AFK etc.

Looking good. Thanks!

**Comment by wzieba** [comment]
Thanks @mokagio !

**Comment by kean** [comment]
I've been getting some odd crashes in `SentryTracer` in `startDeadlineTimer` when debugging, which might be related to this change. @mokagio wdyt about disabling it for now just to be safe unless there is a need for this feature? I think we should be a bit more reserved in terms of what tracking features are enabled.

**Comment by wzieba** [comment]
Addressed in #23372

**Comment by kean** [comment]
Hey, thanks @wzieba. The team agreed to disable it for now to reduce the risk in the upcoming releases. I took care of it in https://github.com/wordpress-mobile/WordPress-iOS/pull/23372 and it was already merged back in trunk.

**Pull request merged**
