### PR TITLE
Adds shared git hooks

### PR DESCRIPTION
**Pull request by koke**
This introduces a few git hooks to help with development:

- pre-commit: runs rake lint and prevents commits with lint errors.
- post-checkout/post-merge: checks for dependency changes and prompts you to
  run rake dependencies. The most common case would be that Podfile.lock has
  changed and you need to run pod install.

I decided to leave those as opt-in for now, but we could make them mandatory by running `githooks` on `dependencies`.

Also, for the dependency checks, I decided to just print a message as installing can take a while, and I'd rather let the developer decide. Sometimes you just want to quickly switch to another branch to check something in the source, a git hook shouldn't be getting in the way.

To test:

- Run `rake githooks`
- Add a swift style violation to any swift file. Run `git commit` and make sure the hook prevents it
- Merge a branch with CocoaPods changes, after the merge it should show `CocoaPods dependencies missing or outdated. Run rake dependencies to install them.`

Needs review: @astralbodies

### CODE REVIEW

**Comment by astralbodies** [comment]
Is it easy enough to write an uninstall githooks in the Rakefile?

**Comment by koke** [comment]
I doesn't sound too hard, but I'm not sure if I want it :wink:
I see `githooks` as an opt-in experiment now, but I wouldn't mind to eventually make them mandatory to ensure a consistent development environment. If pre-commit (or pre-push) can catch an error in a few seconds, there's no point in having travis tell you 20 minutes later.

**Comment by koke** [comment]
Renamed command to `git:install_hooks` and added a `git:uninstall_hooks`. It will try to restore the previous hooks from backup

**Comment by astralbodies** [comment]
The Travis CI build was failing - I cleared the cache and restarted it. Code looks good - just need to merge in develop before the PR can be merged.

:shipit:

**Pull request merged**
