### PR TITLE
Blaze: Hide dashboard card

### PR DESCRIPTION
**Pull request by momo-ozawa**
Part of #20090

- Adds logic for hiding the Blaze dashboard card
- Analytics will be addressed in a different PR
- Figma: cEGtlsm6xijEswaKkrQrIj-fi-477%3A5675

## How to test
0. Make sure that Blaze is enabled via the debug menu
1. Switch to a site that has Blaze enabled - let's call this site A (See peeHDf-zm-p2 for more info on Blaze requirements)
2. Switch to the dashboard
3. ✅ A Blaze dashboard card is displayed
4. Tap on the ellipsis button and tap on "Hide this"
5. ✅ The Blaze dashboard card is hidden
6. Switch to another site hat has Blaze enabled - let's call this site B
7. ✅ A Blaze dashboard card is displayed
8. Switch back to site A
9. ✅ A Blaze dashboard card is NOT displayed

https://user-images.githubusercontent.com/6711616/220175750-51a4fdf2-85b1-4210-ac61-743dcef3dbe7.mp4

## Regression Notes
1. Potential unintended areas of impact
n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a

3. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by hassaanelgarem — APPROVED** [review]
Works as described! Nicely done 🚀

**Comment by tiagomar** [comment]
Hi @momo-ozawa 👋 

Functionality-wise  this is good to go! 

I just notice a small UI thing. There's something slightly off on iPhone, more visible on `Light` mode. It looks perfect on iPad.

| **iPhone** | **iPad** | 
| - | - |
| image | image |
| image | image |

Obviously not critical but it might be worth it if it's a quick fix? =]

**Comment by momo-ozawa** [comment]
Hey @tiagomar 👋 
I can't reproduce the issue you're seeing on an iPhone 14 pro simulator. Which model are you using? 

Screenshot 2023-02-27 at 10 49 39


I'm using the default Apple API for displaying a context menu from a button - we aren't using any customized UI, so I'm not sure why this might be happening.

I'm going to merge this PR for now since there's a couple of other PRs on top of this one that needs to be merged. If this seems like an issue we should investigate further, could you open a new issue? Thank you! 🙇‍♀️

**Comment by tiagomar** [comment]
👋 @momo-ozawa ! 

I have tested on an actual device, iPhone 13 - iOS 16.1.1. [I created a ticket to track it](https://github.com/wordpress-mobile/WordPress-iOS/issues/20218).

**Pull request merged**
