### PR TITLE
Send in-app feedback to Zendesk

### PR DESCRIPTION
**Pull request by staskus**
Context: pc8HXX-1B3-p2

Send in-app feedback to Zendesk, instead of tracking in tracks. 

## Solution

When a user submits feedback, I try to create a Zendesk ticket. If the user isn't allowed to create a Zendesk identity, I submit the feedback anonymously. 

If submission fails, I don't hold user any longer and keep logging feedback to tracks.

### Identified user

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/714fb10f-0dca-40a2-b756-965676e9441a

1. Change `InAppFeedbackPromptCoordinator shouldShowPromptForAppReview` to `true`
2. Fresh install the app
3. Login
4. Kill the app and relaunch
5. "Not Really"
6. "Sure"
7. Enter feedback
8. Tap submit
9. Confirm that the alert appears to enter credentials
10. Submit credentials
11. Confirm that the ticket is submitted
12. Check Zendesk with `tags:in_app_feedback` search, it should contain a ticket with the user. Example ticket 8033979-zd-a8c 

### Anonymous user

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/8eefaf9b-9455-45c2-95c9-e17e74d91686

1. Change `InAppFeedbackPromptCoordinator shouldShowPromptForAppReview` to `true`
2. Fresh install the app
3. Login
4. Kill the app and relaunch
5. "Not Really"
6. "Sure"
7. Enter feedback
8. Tap submit
9. Confirm that the alert appears to enter credentials
10. Cancel credentials input
11. Confirm that the ticket is submitted
12. Check Zendesk with `tags:in_app_feedback` search, it should create an anonymous ticket. Example ticket 8033998-zd-a8c

## Regression Notes
1. Potential unintended areas of impact

HEs. We need to inform them separately about these updates.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by guarani — APPROVED** [review]
Both scenarios worked for me 👍 I'll leave it to @salimbraksa to review as well since seeing pc8HXX-1B3-p2#comment-1427, it looks like don't want to merge this today as-is without confirmation.

**Comment by hassaanelgarem** [comment]
@staskus Thanks for picking this up!
One area I think we can improve is the messaging in the credentials alert. It is not clear that you have the option to submit anonymously and it is not clear that the "Cancel" button submits the feedback anonymously.

@osullivanchris Any thoughts on how we can improve the messaging?

**Comment by staskus** [comment]
That's a good point, @hassaanelgarem.

How about:

"Would you share your email address and name so we can follow up on your feedback?"
"Ok"
"No, thanks"

image

**Comment by osullivanchris** [comment]
@staskus thats better but its like we're retrofitting what we want to say into this UI a little bit.

In the original form we could have a checkbox to include contact information or not? Then it would more naturally just allow the user to submit without a second step with blocking UI?

**Comment by salimbraksa** [comment]
Code looks good to me, and both scenarios worked for me. I have one minor feedback on this message:

> "Would you share your email address and name so we can follow up on your feedback?"

This message might lead users to assume they will not receive follow-up communication regarding their feedback. However, based on this anonymous ticket 8033998-zd-a8c, you still got a reply from an HE even though the feedback was submitted anonymously. So It appears that tapping `No, thanks` could create an expectation among users that they will not hear back from us.

**Review by salimbraksa — APPROVED** [review]

**Comment by staskus** [comment]
> This message might lead users to assume they will not receive follow-up communication regarding their feedback. However, based on this anonymous ticket 8033998-zd-a8c, you still got a reply from an HE even though the feedback was submitted anonymously. So It appears that tapping No, thanks could create an expectation among users that they will not hear back from us.

That's a good question, @salimbraksa. I did assume that we cannot reply to anonymous tickets. Theoretically, it may appear in the app under "Tickets" but I need to test that. However, if that's the case then we need to show the users that they can track the feedback in the "Tickets" menu. 🤔 

> thats better but its like we're retrofitting what we want to say into this UI a little bit.
> In the original form we could have a checkbox to include contact information or not? Then it would more naturally just allow the user to submit without a second step with blocking UI?

Thanks for the feedback, @osullivanchris. 👍  That's true. I reused the existing Zendesk flows for the quickest possible solution. However, a checkmark could be friendlier. I'm not sure if there're cases when we don't know the user's email, I'll check that.

**Comment by salimbraksa** [comment]
> However, if that's the case then we need to show the users that they can track the feedback in the "Tickets" menu.

I agree with informing users they can track their feedback in the "Tickets" menu, but I suggest including this information in the confirmation message ( the notice that appears after the feedback is submitted ):

> Feedback sent
> Thanks for helping us improve the app.

This is because the prompt for email/name does not appear if the Zendesk identity is already set. And we need to ensure all users are aware of this feature, even if they didn't see the email/name prompt.

> In the original form we could have a checkbox to include contact information or not? Then it would more naturally just allow the user to submit without a second step with blocking UI?

I think this is a better UX. But just want to point out that among users who disliked the app, **90.8%** of them opted NOT to share feedback. So, perhaps this suggestion shouldn't be blocking this PR?

**Comment by osullivanchris** [comment]
The experience is a bit weird here but if we don't want to redesign the flow, we could improve the language and actions in the existing flow. In the existing UI it looks like you cannot submit feedback anonymously. 

In this quick wireframe:
- The headline indicates that they are already sending us feedback
- The subheading explains they can include their email optionally
- There is only one CTA, 'done', as they have already chosen to submit feedback so there is no real choice here
- After they clear the email/password the empty field says 'No email entered' to make it clear they're not sending anything
- The success message could be customised for this case to again reassure that the feedback has been sent without including their details


Screenshot 2024-04-16 at 09 56 41

**Comment by staskus** [comment]
Thanks, @osullivanchris! 

> The subheading explains they can include their email optionally

👍

> There is only one CTA, 'done', as they have already chosen to submit feedback so there is no real choice here

Good point, no need to confuse users with multiple options that both result in feedback being submitted.

> The success message could be customised for this case to again reassure that the feedback has been sent without including their details

Good, I can do that 👍 

I'll make improvements.

**Comment by staskus** [comment]
@salimbraksa 

A clarification on this point:

> However, based on this anonymous ticket 8033998-zd-a8c, you still got a reply from an HE even though the feedback was submitted anonymously.

I checked, and anonymous tickets don't appear in the Tickets section on the app. Therefore, we'll be able to reach out only to those users who shared their email. I think that's a fair compromise from both sides. I'll later share a post with HEs so they will be aware of us sending in-app-feedback to Zendesk.

**Comment by staskus** [comment]
Made the last changes according to the comments:

✅ Headline to indicate that they are already sending us feedback
✅  The subheading explaining they can include their email optionally
✅  One CTA, 'done', as they have already chosen to submit feedback so there is no real choice here
✅  After they clear the email/password the empty field says 'No email entered' to make it clear they're not sending anything
✅ Loading message indicates whether feedback is anonymous or not

### Anonymous

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/792c884d-8eaf-481b-8777-12fee35ad225

### Identified

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/c6bbb554-c2b2-4cb5-b0ad-728bf527bef8

**Comment by osullivanchris** [comment]
that was quick @staskus  - looks good! 

Am open to feedback if anything feels off to you or anyone else on this direction. Cheers.

**Comment by salimbraksa** [comment]
LGTM! 🚀

**Pull request merged**
