### PR TITLE
Do not upload a build to App Center during release cycle

### PR DESCRIPTION
**Pull request by mokagio**
We've been discussing internally the value of these builds and struggled to make a strong case for them. The data confirmed this feeling, with only a couple of downloads over the past months.

With the recent Microsoft announcement of [App Center shutting down next year](https://learn.microsoft.com/en-us/appcenter/retirement), the time seems ripe for removing this low value step.

**Notice that prototype builds are intact.** Those App Center builds are frequently used. We'll need to find an alternative, but we shall keep using the App Center in the meantime.

## Testing

I started a manual release buildhttps://buildkite.com/automattic/wordpress-ios/builds/21251 to verify the pipeline runs fine:

image

Of course, I cancelled it before it finished, to avoid App Store Connect errors.

## Regression Notes

1. Potential unintended areas of impact – N.A.
2. What I did to test those areas of impact (or what existing automated tests I relied on) – N.A.
3. What automated tests I added (or what prevented me from doing so) – N.A.

---

**PR submission checklist:**

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes. **N.A.**
- [x] I have considered adding accessibility improvements for my changes. **N.A.**
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary. **N.A.**

**UI changes testing checklist:** Not a UI PR.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR has the <code>Releases</code> label: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by staskus — COMMENTED** [review]
Thanks!

I ran grep -r `AppCenter` through the project. We have a few dependencies within the project that we can remove together as well:

- `AppCenter` pods in `Podfile`
- `AppCenter` configuration in `WordPressAppDelegate`
- `AppCenter` secrets

**Comment by mokagio** [comment]
Thanks for looking into additional App Center usages @staskus 🙇‍♂️ 

They should all be related to the prototype builds, which I think for the moment we should keep given we don't have a replacement in place for App Center on that avenue and folks still use them. What do you think?

**Review by crazytonyli — APPROVED** [review]

**Comment by staskus** [comment]
> They should all be related to the prototype builds, which I think for the moment we should keep given we don't have a replacement in place for App Center on that avenue and folks still use them. What do you think?

Got it, @mokagio. Yes, it makes sense keeping the code then 👍

**Pull request merged**
