### PR TITLE
Media Library: Add support for other file types

### PR DESCRIPTION
**Pull request by frosty**
This PR goes with https://github.com/wordpress-mobile/MediaPicker-iOS/pull/167 to add support for non-image / video filetypes to the media library. 

You should now see these items in the media library for a site (but not yet in the editor picker). There are a few differences in `MediaItemViewController` for these items:

* You'll see a placeholder icon in the preview area at the top of the screen instead of an image preview
* This icon will be different for audio files
* The 'dimensions' metadata row will be hidden
* If you tap the header row, you'll see a preview presented in a `WPWebViewController`
* No previews for audio yet, due to some auth issues – that'll be addressed in the future.

media-types

Needs review: @SergioEstevao

### CODE REVIEW

**Comment by frosty** [comment]
Note: I'll update the `Podfile` when we do the next release of MediaPicker-iOS.

**Comment by frosty** [comment]
@SergioEstevao Updated for the new pod file – care to check over for me?

**Comment by SergioEstevao** [comment]
:shipit: the speed of this version is amazing!

**Comment by frosty** [comment]
Thanks for all the help landing this one and the updated picker pod, @sergioestevao!

**Pull request merged**
