### PR TITLE
Ensure there's an active plan before showing the plans list

### LINKED ISSUE #4818: Refresh plan when needed if not there
We currently only get the plan for a blog on `syncBlogs` which is called when the blogs list appears. However that doesn't guarantee we know a blog's plan when we need it. For instance:

- Run 5.9 on a fresh install, login, go to a site and tap the home button
- Run `develop`, it should launch on the site screen. Since we haven't passed through the sites list, there's no blog sync
- "Plans" shows no current plan
- Tapping on "Plans" shows the three available plans with no "CURRENT PLAN"

### PR DESCRIPTION
**Pull request by koke**
Before this, there's a chance you could go into the plans list for a blog with a `nil` plan, because we only sync the active plan when we sync the list of blogs. If this was the case, I wanted to show the list as loading until we could fetch the active plan for the current blog. This brings more questions though:

- Should we cache a blog's active plan at all? For how long? How do we store how old is the cached value? Do we use core data to cache it?
- The blog details view has the active plan displayed in the plans row, so we'll want to request it before we even get to the plans list. This makes me want to cache it. How do we prevent duplicate requests if we tap on plans while fetching the active plan?
- Other parts of the app might need to know the active plan, like conditional features or the upgrade nags. Will this design work there?
- The purchase process will change the active plan, how will we propagate that change?

There's more work to be done here, but I think it's ready to merge to avoid later conflicts when fetching features from the API. Plan details still uses hardcoded prices.

Fixes #4818 
Needs Review: @frosty

### CODE REVIEW

**Comment by frosty** [comment]
Some initial thoughts...

- Should we cache a blog's active plan at all? 

I think it makes sense to cache it, as we need to display it on the Plan row at the top level of the blog (as you mentioned).

- For how long? How do we store how old is the cached value? Do we use core data to cache it?

Can we not just store it indefinitely, until we fetch a newer value? Core Data would seem to make sense here, as the plan ID is really part of the blog's metadata which we're already storing there.

- How do we prevent duplicate requests if we tap on plans while fetching the active plan?

Is this something we actually need to worry about? What's the worst thing that can happen? How often are users likely to tap in-and-out of plans?

- Other parts of the app might need to know the active plan, like conditional features or the upgrade nags. Will this design work there?

If we use Core Data, then it's just a case of checking the current blog?

- The purchase process will change the active plan, how will we propagate that change?

I guess if we're using Core Data, either we can check when the context changes, rely on FRCs, or otherwise send a specific notification when a blog's active plan changes?

**Comment by koke** [comment]
> Can we not just store it indefinitely, until we fetch a newer value?

If you open the app and go to Plans, and we have a cached active plan from a month ago, is that still useful?

For plans, we definitely want some caching because we don't want to be requesting the active plan on consecutive screens, but other than that I think we'd want to have the data as fresh as possible: if you recently purchased a plan from another device, you probably don't want the app to show you're still on "Free".

An alternative to caching with expiration, is to do something similar at the service layer. When you request the active plan, if there's one cached it's returned regardless of age, but then it triggers a refresh if needed. But then, how do you communicate the new value? In our current architecture, service calls can return (`success`) once, but there's no way to send more than one value.

Even if we had RxSwift or a similar solution, the UI would show an old value, then change to a newer value. I'd rather show a loading indicator than an value that's really old.

**Comment by frosty** [comment]
> An alternative to caching with expiration, is to do something similar at the service layer. When you request the active plan, if there's one cached it's returned regardless of age, but then it triggers a refresh if needed. But then, how do you communicate the new value? In our current architecture, service calls can return (success) once, but there's no way to send more than one value.

We could, as mentioned above, post a notification whenever a site's active plan changes? 

> Even if we had RxSwift or a similar solution, the UI would show an old value, then change to a newer value. I'd rather show a loading indicator than an value that's really old.

I'm happy with us showing a spinner if a site's active plan is 'old'. How old is 'really old' though? :) More than a day? A week?

**Comment by koke** [comment]
Ready to review

**Comment by frosty** [comment]
:shipit:

**Pull request merged**
