### PR TITLE
Merge branch 'release/6.0' into develop - **DO NOT MERGE**

### PR DESCRIPTION
**Pull request by sendhil**
While merging `release/6.0` into `develop` hit a bit of a bump in `WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift`. @koke since you made a bunch of updates to that file across branches would you mind resolving the merge?

### CODE REVIEW

**Comment by koke** [comment]
Conflicts in the account settings side are solved. cc @jleandroperez 

There were conflicts in the Xcode project file as well which I tried to solve, but you should review those. Also it looks like it changes provisioning profiles, so that might need to be updated

**Comment by jleandroperez** [comment]
Thanks @koke!! I've updated the App + Today Widget Provisioning Profiles, as follows. CC'ing @astralbodies for an eye sanity check.

Other than that, :shipit: on my side gentleman.

screen shot 2016-03-14 at 16 14 33

screen shot 2016-03-14 at 16 14 38

**Comment by astralbodies** [comment]
Profiles look good - feels good having gotten rid of `Distribution` config

**Comment by sendhil** [comment]
Merging it.

**Pull request merged**
