### PR TITLE
Reader Improvements: Add "Discover more topics" button to Followed Topics screen

### LINKED ISSUE #15806: Show topics picker screen to allow users to add topics to their initial selection
Based on user feedback - Show the topic picker again to allow adding topics. 
One suggestion was to replace "Add a topic" on the setting screen to "add topics" and show the topic picker from there but this needs design 

### Design
a

### PR DESCRIPTION
**Pull request by momo-ozawa**
Fixes #15806

## Description
-  Added a "Discover more topics" button to the Followed Topics screen (under the settings icon on Reader), so that users can re-visit the topic picker screen.

## Notes

I noticed that in WPiOS 16.7, if you entered a tag with multiple words, the tag would show up as hyphenated in the list of Followed Topics (i.e. "social media" is displayed as "social-media"). 

I created a separate issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/15985

## How to test
1. Go to the Reader tab
2. Tap the settings icon > tap on "Discover more topics"
3. ✅ The topics picker screen should be presented
4. Tap any topic > tap "Done"
5. ✅ The new topic should show up in the list of Followed Topics
6. Tap on "Discover more topics" again
7. ✅  The topic you added in step 4 should not be included in the list of available topics to follow

## Screenshots
Followed topics screen | Follow topics screen 
--- | ---
Simulator Screen Shot - iPhone 12 Pro - 2021-02-26 at 16 30 07 | Simulator Screen Shot - iPhone 12 Pro - 2021-02-26 at 16 30 26

## PR submission checklist

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by momo-ozawa** [comment]
@emilylaguna Lmk what you think about https://github.com/wordpress-mobile/WordPress-iOS/issues/15985#issuecomment-786486048 😄 

> Will there be any side-effects if we change the mapping logic for the topic title to
> 
> topic.title = [topicDict stringForKey:TopicDictionaryTitleKey];
>

**Review by emilylaguna — CHANGES_REQUESTED** [review]
Looking good, I had a few suggestions:

#### Should we change the loading title to something else since we're not going to the discover view in this flow?



#### If I follow all the topics when I tap on the discover more button again the error is blank and off centered.

**Comment by momo-ozawa** [comment]
@emilylaguna 
Thanks for the suggestions! Will update the copy (and maybe even the illustration) once I get the updated design files 😄 
p1614288856021500/1614182067.009400-slack-CVASUPH2M

**Comment by momo-ozawa** [comment]
@emilylaguna 👋  

I updated the loading / empty state text so we can merge this PR. I'll open a new PR once we get updated copy / illustrations for these states. (Issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/16018)

> Should we change the loading title to something else since we're not going to the discover view in this flow?

Changed it to "Following new topics..." for now. 619ef00

> If I follow all the topics when I tap on the discover more button again the error is blank and off centered.

Configured the NoResultsVC to display "No new topics to follow" for now. cabd117

Loading state | Empty state
--- | ---
<image src="https://user-images.githubusercontent.com/6711616/110069150-8f824380-7dba-11eb-8d6c-4366aecf9614.png" width=50%> |

**Review by emilylaguna — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
