### PR TITLE
Remove extract notifications feature flag

### LINKED ISSUE #9877: Remove the `extractNotifications` feature flag.
This is the last task the `Extract Notification Interactions` project.
We should remove the feature branch after one release cycle of this feature in production.

### PR DESCRIPTION
**Pull request by etoledom**
Fixes #9877 

This PR removes all the extra code left from the `Extract Notification Interactions` project, plus the feature flag. In general it was a clean removal of "duplicated" code. (Code that's now implemented by `FormattableContent`.

The `ActionableObject` protocol was meant to be a temporary helper while `NotificationBlock` was still around, but now it also was removed. 

There was a small complication since `ActionContext` was depending on `ActionableObject`, and it was quite `Notification` specific. This issue was solved by making `ActionContext` generic on the block type it holds.

**To test:**
- Build and run.
- Check that `Notifications` displays and behaves as always.
- Check that Activity log events display and behave as they should.

*Note*:
Do not merge yet, until the destino is made to remove the feature flag.

### CODE REVIEW

**Comment by ctarda** [comment]
I've merged `develop` into this branch to bring it up to date. I will change the base branch to target `develop`

**Comment by ctarda** [comment]
@stevebaranski would you mind taking a look at this? The branch seems to build without issues on my side, and the tests pass.

**Comment by ctarda** [comment]
Thanks @stevebaranski ! I guess there is always one more merge that can potentially break the build 😛.

Your update looks good to me. Let's merge!

**Comment by etoledom** [comment]
Hey @ctarda and @stevebaranski - Thank you both so much for taking care of this! ❤️

**Pull request merged**
