### PR TITLE
Dark mode: loading animations and no results view text

### PR DESCRIPTION
**Pull request by nheagy**
Refs #12320

This PR updates the colors for the loading animation, and text colors in the no results controller. It also moves `NoResultsViewController.swift` to be in the same folder as its storyboard 😎

no results dark mode
image

To test:
- View a screen that has to do some loading, like stats.
- Ensure the colors look better
- Test in dark mode, too 🌑

Update release notes:
- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @nheagy .

This doesn't look quite right. I'm running the app in Xcode 11 13.0 simulator. I toggle dark/light modes via the Environment Overrides.

dark

light

**Comment by mattmiklic** [comment]
The box animation in the gif above doesn't look right (using the old colors, I think) but it does look right when I test on the simulator in dark and light modes. 👍

**Comment by nheagy** [comment]
@mattmiklic ha, I think I uploaded the wrong GIF 🤦‍♂️

**Comment by nheagy** [comment]
Thanks @ScoutHarris and @mattmiklic

**Pull request merged**
