### PR TITLE
ULS: Add visual blur to Prologue button view

### PR DESCRIPTION
**Pull request by ScoutHarris**
Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/401
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/487

This uses the Auth changes to show the visual blur behind the Prologue button view.

To test:
- Verify the Prologue button view background is a bit blurry. 😄 

| Before | After |
|--------|-------|
| before_light | after_light |
| before_dark | after_dark |

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@mattmiklic @osullivanchris I went ahead and created an installable build in case you wanted to see it IRL.

**Comment by osullivanchris** [comment]
> @mattmiklic @osullivanchris I went ahead and created an installable build in case you wanted to see it IRL.

Thanks @ScoutHarris I downloaded it and took a look! Its hard to tell in the current build where there's not much going on behind the buttons, as you pointed out. But nothing looks wrong anyway! 👍

**Review by mindgraffiti — APPROVED** [review]
looks good!

:shipit:

**Review by mattmiklic — COMMENTED** [review]
Looks just as I intended -- thank you @ScoutHarris!

**Pull request merged**
