### PR TITLE
Threaded comment moderation: don't show non-approved cached comments

### LINKED ISSUE #17752: Comment Threads: Add undo functionality for moderation actions
Refs `pbArwn-2ks-p2#comment-4465`

Comment thread moderation functionality is currently hidden behind the feature flag `commentThreadModerationMenu` since 18.9. When opening Reader comments using an account that has moderation capabilities, the Share button turns into an ellipsis icon that shows an overlay context menu when tapped:

Screen Shot 2022-01-13 at 15 41 56

`pbArwn-2ks-p2#comment-4465` suggested that an undo functionality is added to allow the user to revert their action in case of misclicks. I'm thinking that the implementation should be similar to Follow Conversation where an actionable "Undo" button is shown after enabling push notifications.

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #17752
Ref: #17629, #17758, p5T066-2Wh#comment-11057

This fixes some issues with `Undo`ing moderated comments in the threaded comments view. 

As noted on the [previous](#17834) attempt to fix: The cause was that, to facilitate `Undo`ing comment moderation, the comment was kept in the cache. However, because it was in the cache, the table's `fetchedObjects` still contained it, thus the table tried to show it.

The previous approach of restoring the undone comment to cache failed miserably. So this goes the other way - leave the comment in the cache and update the applicable views to not display them. The moderated comments are removed from the cache when a full comment sync is performed, so they don't linger for very long.

To test:

- Go to the Reader. Select a post with comments and that you have permission to moderate comments on.
- Go to the Comments view.
- Comment moderation:
  - On any comment, tap the ellipsis button and select any status. 
  - Verify the comment is removed from the view, and the table updates correctly.
  - Go back to the post details view, and verify the Comments snippet count is correct.
- Comment moderation Undo:
  - On any comment, tap the ellipsis button and select any status. 
  - Verify the comment is removed from the view, and the table updates correctly.
  - Tap `Undo` on the confirmation notice.
  - Verify the comment is restored and has the same hierarchy as before.
- Moderate all comments:
  - Moderate all the comments on a post.
  - Verify the `Be the first to leave a comment` view is displayed.
  - Go back to the post details view, and verify the Comments snippet is empty.

## Regression Notes
1. Potential unintended areas of impact
N/A. Feature is disabled.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A. Feature is disabled.

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
You can test the <strong>Jetpack</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/jetpack-installable-builds/'>here</a> with build number: <code>pr17869-0c0c1d0</code>. IPA is available <a href='https://appcenter-filemanagement-distrib5ede6f06e.azureedge.net/0debc4ab-4470-4800-9487-0f6c7c7c735f/Jetpack%20Alpha.ipa?sv=2019-02-02&sr=c&sig=CscAE4Fe45WKoX7xcUutmZorQWEfyVOHRXOkqPn1UdQ%3D&se=2022-02-03T23%3A43%3A43Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

**Comment by jkmassel** [comment]
You can test the <strong>WordPress</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/WPiOS-One-Offs/'>here</a> with build number: <code>pr17869-0c0c1d0</code>. IPA is available <a href='https://appcenter-filemanagement-distrib3ede6f06e.azureedge.net/da95d0aa-e921-403a-8a17-6a9852da8ae4/WordPress%20Alpha.ipa?sv=2019-02-02&sr=c&sig=hFWtrFjTogGlfDfMswNFhCFuMHDE7toBhXyByRXjcoI%3D&se=2022-02-03T23%3A44%3A07Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

**Review by frosty — APPROVED** [review]
Working perfectly! 🎉 

I spotted one slightly odd thing where the app is behaving differently to the web, but I don't think it's necessarily related to this PR and could be addressed separately. I had a post with 5 comments:

```
A
B
\__ C
     \__ D
E
```

If I unapprove B from the moderation screen, here's what happens in various places:

**Reader comments view in the app**
* Continues to show A, C, D and E.
* C and D are now shown as replies to B, which I think is probably a bug.
* The app shows a count of 4 comments – the total number of approved comments, even though two of them are replies to a comment that is no longer visible.

**Reader on the web**
* Only shows the top level comments, A and E. The replies to the unapproved comment are not visible.
* Shows a comment count of 2 to match the visible comments.

**Frontend of the website**
* Only shows the top level comments, A and E. The replies to the unapproved comment are not visible.
* Shows a comment count of 4 – the total number of approved comments, even though two of them aren't visible. I wonder if this is a bug!

As both of the interfaces on the web no longer show the child comments, I presume we should probably hide those too. But as I said, I think this is something we can and should address separately!

**Comment by ScoutHarris** [comment]
Hey @frosty .

Yea, the issues you noted are not new. The same thing happens when you moderate comments from My Site. We've just made it more obvious. 😆 I know @dvdchr was looking into this before his AFK. I'm not sure of the status, but I know it's on his radar. But the details are helpful. Thank you!

**Comment by dvdchr** [comment]
Thanks @frosty for the detailed description and @ScoutHarris for the ping! 

> I know @dvdchr was looking into this before his AFK. I'm not sure of the status, but I know it's on his radar.

Yeah, this was sitting on my backlog 😅 . I'm going to fix this for the upcoming release. In the meantime, I've created an issue for this: https://github.com/wordpress-mobile/WordPress-iOS/issues/18081

**Pull request merged**
