### PR TITLE
Integrate gutenberg-mobile release 1.62.0

### PR DESCRIPTION
**Pull request by enejb**
## Description
This PR incorporates the 1.62.0 release of gutenberg-mobile.
For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3984

Release Submission Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mokagio — APPROVED** [review]
I'm going to approve and merge this because I'm running the code freeze for 18.3 today and it would be handy if this the latest `mobile-gutenberg` stable was already on `develop`.

I feel comfortable approving this because this is only the version bump. The actual changes have already been tested [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3984#pullrequestreview-757887854).

I'd rather ship the first beta and take onboard the limited risk of having to revert the version or merge a hotfix later because the payoff is that the other parts of the area will be available for testing and we can get ahead with those.

You might have noticed that there are CI failures, but they are all in the UI tests and due to an issue in the tests themselves (see #17177). I'm going to merge this PR first and #17177 after to make the conflict resolution on the `Podfile*` easier. If this PR introduced new genuine failures in UI tests, the #17177 merge into `develop` will reveal it to us 👍

**Comment by jd-alexander** [comment]
> I feel comfortable approving this because this is only the version bump. The actual changes have already been tested here.

Appreciated @mokagio I was just about to do this merge! 😄 Thanks for handling it!

> You might have noticed that there are CI failures, but they are all in the UI tests and due to an issue in the tests themselves (see #17177). I'm going to merge this PR first and #17177 after to make the conflict resolution on the Podfile* easier. If this PR introduced new genuine failures in UI tests, the #17177 merge into develop will reveal it to us 👍

Makes sense! I appreciate you creating that fix to resolve the UI test issues 🙇🏾

**Comment by mokagio** [comment]
Followup on the UI tests. As you can see on [the checks for this commit](https://github.com/wordpress-mobile/WordPress-iOS/pull/17177/commits/180122f13956653ddd29ad0edb80f8da3f9fbfd3) based on top of `develop` after this was merged, the UI tests are all green 😄

**Comment by jd-alexander** [comment]
> Followup on the UI tests. As you can see on [the checks for this commit](https://github.com/wordpress-mobile/WordPress-iOS/pull/17177/commits/180122f13956653ddd29ad0edb80f8da3f9fbfd3) based on top of `develop` after this was merged, the UI tests are all green 😄

Great! Thanks for the update @mokagio   :shipit:

**Comment by enejb** [comment]
Thanks for approving and fixing the UI tests! @mokagio

**Pull request merged**
