### PR TITLE
[Gutenberg] Implement aztec attachment delegate

### PR DESCRIPTION
**Pull request by etoledom**
This PR implement the changes introduced by https://github.com/wordpress-mobile/gutenberg-mobile/pull/281 , and implements `AztecAttachmentDelegate` in `GutenbergViewController`.

The main objective of this PR is to avoid a crash when an instance of Aztec try to load an image. It's not common scenario for Alpha but it might happen.

**To test:**

- Run `pod install`
- Clean build folder.
- Build and run the app in Gutenberg mode.
- Start a new post (+ button in the middle of the tab bar)
- Switch to HTML mode and paste this snippet:
```html
<!-- wp:paragraph -->
<p>Hi there</p>
<img src="https://etoledomatomicsite01.blog/wp-content/uploads/2018/04/kitty-cat-kitten-pet-45201.jpg" alt="" class="wp-image-43">
<!-- /wp:paragraph -->
```
- Switch back to blocks view.
- Check that it shows the placeholder image.
  - If it shows the image directly, it means that the image was cached.
  - If you want you can try again with another image url. 
- Check that the image appears when the placeholder disappears.
  - It might happen that the loaded image won't appear after the placeholder.
  - If this happen, switch to html view and back and the image should be there.
  - This issue seems to be non-trivial and is not really important for Alpha, so I'd prefer get back to it later on.

simulator screen shot - iphone 8 - 2018-11-27 at 19 21 49

### CODE REVIEW

**Comment by loremattei** [comment]
Hey! I'm moving this to 11.5 since 11.4 has been cut. If you want it to be into 11.4, please feel free to target the release branch and to ping me to build a new beta.

**Comment by etoledom** [comment]
As discussed internally, we will merge this PR to `release/11.4` to fix the crash this PR was intended to fix.
There is still a smaller issue where sometimes the images won't load correctly inside the paragraph block, but that will be addressed separately.

@pinarol could you take another look please?
Be sure that [this post](https://frontenberg.tomjn.com) doesn't crash the app.

I removed the tag from the `Gutenberg` pod to test this PR, but we should add it back as soon as we release the Gutenberg-mobile version with the current changes.

cc @loremattei

**Comment by etoledom** [comment]
Since the Gutenberg-mobile release 0.2.1 is ready, I updated the `podfile` directly here to avoid a second PR.
Now we can test this fix without the need of `metro` running. 🎉

**Comment by etoledom** [comment]
Thank you @pinarol for your fast review!

**Pull request merged**
