### PR TITLE
Add autosave attributes to Core Data

### PR DESCRIPTION
**Pull request by guarani**
Post autosave attributes are saved to Core Data upon retrieval from the remote service.

Issue: wordpress-mobile/WordPress-iOS#12141
Related PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/192

Although the changes in the WordPressKit PR map all autosave attributes, only those necessary for wordpress-mobile/WordPress-iOS#12141 are now persisted to Core Data.

### Testing Details

1. On WordPress.com, create a new post or open an existing post for editing
2. Set the title to “Hello, world!”, the body to “One.”, and the excerpt to "An excerpt"
3. Publish the post
4. Re-open the post and add a new line, “Two.” – then close the browser tab without saving
5. Again, re-open the post and notice the following message -  “The backup of this post in your browser is different from the version below. Restore the backup”  – this signifies that an autosave was made
6. Run the iOS app from Xcode and [locate the path to iOS app Core Data's sqlite file](https://stackoverflow.com/a/47402447/1305067), `WordPress.sqlite` and open a database browser at this location
6. On the WordPress for iOS app, under the My Sites tab, navigate to the list of posts containing the post
8. Run the query `SELECT ZAUTOSAVETITLE, ZAUTOSAVEEXCERPT, ZAUTOSAVECONTENT, ZAUTOSAVEMODIFIEDDATE FROM ZBASEPOST;` and observe that the title, excerpt, content, and timestamp contain the expected values:

Screen Shot 2019-11-01 at 12 23 02 AM

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
> Warnings
> ⚠️	PR is missing at least one label.
> ⚠️	PR has more than 500 lines of code changing. Consider splitting into smaller PRs if possible.
> Generated by 🚫 [dangerJS](https://danger.systems/js)

- The **"Do Not Merge"** label needs to be added, but I don't have permission. The changes made to `Podfile` and `Podfile.lock` are temporary - they only serve to point to the feature branch of WordPressKit-iOS - and should be reverted once the feature branch PR is merged.
- Most of the new line count comes from `WordPress 93.xcdatamodel`, changes to Core Data required a new data model version.

**Comment by guarani** [comment]
Very helpful list, thanks @shiki! I'll reply to each of my items in turn as I can't mark them off directly due to permissions.

> Finish discussions in [wordpress-mobile/WordPressKit-iOS#192](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/192)

Done ✅

> Increment the WordPressKit pod version. See [wordpress-mobile/WordPressKit-iOS#192 (comment)](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/192#issuecomment-549466600).

Done ✅

> * [ ]  Fix the conflicts in this PR

Done ✅

> Update this branch with the released WordPressKit version. Version number waiting for @shiki.

I'll be on this once the new release of WordPressKit is ready.

**Comment by shiki** [comment]
@guarani [WordPressKit-iOS 4.5.3-beta.2](https://github.com/wordpress-mobile/WordPressKit-iOS/releases/tag/4.5.3-beta.2) has been released. You should be able to update the `Podfile` to point to that now. Please let me know if you run into any issues.

**Comment by guarani** [comment]
r.e. https://github.com/wordpress-mobile/WordPress-iOS/pull/12826#pullrequestreview-311244415
> Update this branch with the released WordPressKit version.

@shiki, I've updated this project to point to https://github.com/wordpress-mobile/WordPressKit-iOS/releases/tag/4.5.3-beta.2 👍

**Comment by guarani** [comment]
Thank you, @shiki!

**Pull request merged**
