### PR TITLE
Issues/12672 fix notification setup glitch

### PR DESCRIPTION
**Pull request by aerych**
Refs #12672 

H/T @frosty who troubleshooted this one. 
An earlier patch to fix a disassociated default account was a bit too aggressive in its approach. As a consequence, setting a default account during login never executed code to setup notifications.  This patch moves the disassociation fix out of the getter into a separate method and calls it during application launch.  This should be sufficient to restore an account that was disassociated during an upgrade/restore. 

@koke, if you have a free moment I'd appreciate your 👀 on this one too. 

To test:
Run unit tests. Confirm they pass. 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by aerych** [comment]
We apparently have a perilous peril glitch. Jk "Danger" Massel is aware and hopes for a resolution in the near future.

**Comment by frosty** [comment]
giphy

**Comment by loremattei** [comment]
Hey! I'm moving this to 13.6 because 13.5 has been cut. If you want this PR to make it to 13.5, please feel free to move it back, target the release branch and ping me to build a new beta.

**Comment by frosty** [comment]
If possible, I think it'd be good if we could bring this into 13.5.

**Comment by aerych** [comment]
Thanks @frosty and @koke !  
@loremattei I went ahead and set the milestone back to 13.5 and targeted the release branch.  Showing no conflicts so I'm going to go ahead and merge. 

Cheers all!

**Pull request merged**
