### PR TITLE
Remove Alamofire dependency from WordPressKit

### PR DESCRIPTION
**Pull request by kean**
It was "needed" for tests.

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by jkmassel — CHANGES_REQUESTED** [review]
These tests ensures that we're creating valid multipart requests.

If we were to remove them, we'd lose that validation.

I'm fine to remove Alamofire here, but we should replace it with static test data that can be validated against, not just delete the test entirely.

**Comment by kean** [comment]
I honestly didn't read the tests because the use of Alamofire didn't seem to make sense.

> but we should replace it with static test data that can be validated against

Done. Right, this way it'll catch if there any regressions.

**Review by jkmassel — CHANGES_REQUESTED** [review]
Sorry to be annoying – can we use multi-line Swift strings for this so developers can read it right in the code?

It makes the test longer, but more clear IMHO

**Comment by kean** [comment]
> Sorry to be annoying – can we use multi-line Swift strings for this so developers can read it right in the code?

Can you drop a comment on the lines you are referring to please?

There are inline base64 binary: 

```
let expected = Data(base64Encoded: "LS10ZXN0Ym91bmRhcnkNCkNvbnRlbnQtRGlzcG9zaXRpb246IGZvcm0tZGF0YTsgbmFtZT0ia2V5LTEiDQoNCmENCi0tdGVzdGJvdW5kYXJ5DQpDb250ZW50LURpc3Bvc2l0aW9uOiBmb3JtLWRhdGE7IG5hbWU9ImtleS0yIg0KDQpiDQotLXRlc3Rib3VuZGFyeS0tDQo=")!
```

**Comment by jkmassel** [comment]
Yeah, all the binary data is just a string like:

```
--wpkit.boundary.9d4adfc909a08bfa
Content-Disposition: form-data; name="world"

hello
--wpkit.boundary.9d4adfc909a08bfa--
```

We could probably just use that in the test for easier comparison?

**Comment by kean** [comment]
> We could probably just use that in the test for easier comparison?

It actually is, isn't it? There are just boundaries and .utf8 "blobs".

I tried it, but there is an issue with newlines. It encodes them as `\r\n` aka Windows encoding. Swift uses just `\n` if you have a multiline string.

```
--testboundary\r\nContent-Disposition: form-data; name=\"key-1\"\r\n\r\na\r\n--testboundary\r\nContent-Disposition: form-data; name=\"key-2\"\r\n\r\nb\r\n--testboundary--\r\n
```

So this won't be the same:

```swift
let expected = """
        --testboundary
        Content-Disposition: form-data; name="key-1"

        a
        --testboundary
        Content-Disposition: form-data; name="key-2"

        b
        --testboundary--

        """.data(using: .utf8)
```

**Comment by kean** [comment]
But this will work:

```
let expected = "--testboundary\r\nContent-Disposition: form-data; name=\"key-1\"\r\n\r\na\r\n--testboundary\r\nContent-Disposition: form-data; name=\"key-2\"\r\n\r\nb\r\n--testboundary--\r\n".data(using: .utf8)
```

I'm changing it to that.

**Review by jkmassel — APPROVED** [review]

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>Modules/Package.swift</code> was changed without updating its corresponding <code>Package.resolved</code>. Please resolve the Swift packages in Xcode.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
