### PR TITLE
[Stats Refresh] Insights Comments: add detail list view

### LINKED ISSUE #11160: [Stats Refresh] Insights Comments: add detail list view
On Insights Comments, display detail list view when `View more` is selected.

Detail view design:
detail

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #11160 

On the Insights Comments card, selecting `View more` will now show a full list of Comments.
- Currently, there is no API call to get the full list of Comments for either tab. So for now, this displays the data fetched from the "top" Comments API call used for the Insights Comments card. (cc @jklausa  issue #11182)
- When `View more` is selected, the filter tab (and thus the data) will be the tab selected on the overview card.
- Pull to refresh updates the data.
- If one tab has data and the other does not, the empty tab will display `No data yet`.

NOTE: The UI for the details view still needs to be updated. That will be done with https://github.com/wordpress-mobile/WordPress-iOS/issues/11165.

To test:

---
- On a site with more than 6 comments, go to Insights > Comments > View more.
- Verify:
  - The tab titles match the overview card.
  - The selected tab match the overview card.

comments_list

---
- On the Posts and Pages tab, selecting a row opens a web view for that post/page.

---

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @stevebaranski ! Thanks for the review. 

> If I tap a row, can the expected behavior open the site, or should the URL include the specific comment?

For Posts & Pages, the row selection is the same behavior as selecting a row from the Insights Comments card, which is it opens the _post_ URL. If @SylvesterWilmott  desires different behavior, it can be changed in a future PR (with some accompanying backend data alteration).


> If _Posts and Pages_ was selected when I navigate **to** _Comments_ via _View More_, I'm observing that _Authors_ is selected when I navigate back. Should that original selection be preserved?

The Android implementation does not persist the filter selection from details back to Insights, so I copied that behavior. However, if @SylvesterWilmott  wishes it to be persisted, it can be done in a separate PR (as it should be the same for Insights Followers).

**Comment by stevebaranski** [comment]
@ScoutHarris sounds good! I'm happy to approve once he provides that clarity.

> For Posts & Pages, the row selection is the same behavior as selecting a row from the Insights Comments card, which is it opens the post URL.

Acknowledged. I think this could be a nice enhancement, provided we have that information at our disposal. If we choose to create an issue for this, I agree that it should be considered in a future release release.

> The Android implementation does not persist the filter selection from details back to Insights, so I copied that behavior.

I'm happy to defer to Sylvester here. Personally I think this one warrants resolution prior to shipping, but I'm open to considering it subsequent to this PR. As it stands, the behavior is inconsistent: 
 • A → B → A 
 • A' → B' → A

**Comment by SylvesterWilmott** [comment]
Looks awesome @ScoutHarris !

>If I tap a row, can the expected behavior open the site, or should the URL include the specific comment?

I'm a little confused, the rows don't refer to specific comments but instead only to that post and the number of comments it has.

>If Posts and Pages was selected when I navigate to Comments via View More, I'm observing that Authors is selected when I navigate back. Should that original selection be preserved?

You're right @stevebaranski, we should preserve the tab selection. We can create an issue for this one but it isn't critical.

**Comment by stevebaranski** [comment]
> we should preserve the tab selection. We can create an issue for this one but it isn't critical.
I have added this to the list of outstanding issues in #10840. Proceeding to merge / approve.

**Comment by ScoutHarris** [comment]
> I have added this to the list of outstanding issues

Thanks @stevebaranski !

**Pull request merged**
