### PR TITLE
Issue/498 editor airplane mode add image

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fix for this https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/498

For the legacy editor the main work was copying code from the new editor to update the save logic when media was pending.

For the new editor the fix was to change the moment where the stop editing was done. It's now done after all possible changes on the post content can happen.

can you please review @diegoreymendez or @bummytime

### CODE REVIEW

**Comment by bummytime** [comment]
Looks and works well @SergioEstevao :shipit:

**Comment by bummytime** [comment]
@SergioEstevao you prolly need to cherry pick these changes into the 4.8 branch or create a new PR that points at it.

**Comment by sendhil** [comment]
@SergioEstevao - would you mind just re-submitting this against `release/4.8`?

**Comment by sendhil** [comment]
Oh n/m you did.. just forgot to close this one ;). I'm going to close this one for now as we'll merge https://github.com/wordpress-mobile/WordPress-iOS/pull/3143 into `develop` soon enough.

**Pull request closed without merging**
