### PR TITLE
Add UI testing tips to docs

### PR DESCRIPTION
**Pull request by guarani**
The proposal moves the newly added UI testing checklist to the existing `docs` folder and turns them from an explicit list of testing steps into testing considerations. These considerations are roughly split between various existing docs: accessibility, localization, pull requests, and RTL language support.

If you prefer the current checklist, that's OK. This PR is meant to help us figure out the best approach. There are trade-offs to be considered including:
- Having an explicit list of UI testing scenarios increases the size of the PR template, making it less approachable. 
- Should authors delete UI testing scenarios if they're not applicable? Should they explain why?
- Moving these scenarios to the docs encourages authors to take a holistic approach to testing, giving them the tools to support accessibility, localization, and different device sizes alongside testing considerations for each. 

To test: Read through the changes and see if you agree with them.

## Regression Notes
1. Potential unintended areas of impact

Not applicable.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Not applicable.

3. What automated tests I added (or what prevented me from doing so)

Not applicable.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist: Not applicable.

### CODE REVIEW

**Comment by staskus** [comment]
👍 I agree that it's important to define common standards. 

I also agree that linking them, instead of listing them in every single PR is a better approach. We don't have that many one-time contributors in the repository. Since the same group of people is continuously contributing to the repository, we can expect them to read the documentation and apply the same standards in every PR.

**Comment by tiagomar** [comment]
👋 Hey, @guarani @staskus!

Adding the instructions to the docs makes total sense. However, I don't think we should remove the checklist (we could definitely tweak it) from the PR template at the moment and I'll try to explain why. Also, I think I should have linked [the discussion that motivated the decision to add the checklist](pbArwn-61Z-p2#comment-7587) in the [PR that introduced the change](https://github.com/wordpress-mobile/WordPress-iOS/pull/20546), sorry about that. 

> Moving these scenarios to the docs encourages authors to take a holistic approach to testing, giving them the tools to support accessibility, localization, and different device sizes alongside testing considerations for each.

Yes, I totally agree that we should **add** the scenarios to the existing docs.

> Since the same group of people is continuously contributing to the repository, we can expect them to read the documentation and apply the same standards in every PR.

Yeah, it's mostly the same group of people but it doesn't mean that the whole group is considering everything that's on the docs all the time and it's not uncommon that simple UI issues are discovered too late in the process, especially now that we no longer have release CfTs. 

> Having an explicit list of UI testing scenarios increases the size of the PR template, making it less approachable.
I agree and am open to discuss 

The ideia was really to give it the best visibility for authors and reviewers so that it makes it harder to be overlooked because we've been failing to prevent such issues. Yes, the current checklist in the PR template doesn't look great and it's probably not the best solution but instead of just removing it we should maybe improved it? Could it be automatically included when a certain label is added? 

> Should authors delete UI testing scenarios if they're not applicable? Should they explain why?

That's fine to delete if there are no UI changes and making it explicit, as you did in this PR, is great.

**Comment by guarani** [comment]
👋 Hey @tiagomar, thanks for the reply! 

> The ideia was really to give it the best visibility for authors and reviewers so that it makes it harder to be overlooked because we've been failing to prevent such issues.

Fair, a checklist like this could have possibly prevented some recent issues. For now, I'm happy to update this proposal to just add the info to the docs without removing the checklist. We can discuss improving the checklist separately 👍 

I'll update the PR and re-request an approval.

**Comment by guarani** [comment]
This is now ready to re-review, @tiagomar 🙇

**Review by tiagomar — APPROVED** [review]
Thanks for bringing up the points for discussion and the suggestions, @guarani! 
That's a great addition to our docs!

**Comment by guarani** [comment]
Thank you @tiagomar!

**Pull request merged**
