### PR TITLE
Stats Traffic: Create Bar Chart card UI

### LINKED ISSUE #22392: Stats Traffic: Create Bar Chart card UI
Parent: https://github.com/wordpress-mobile/jetpack-issue-repo/issues/1
image

### PR DESCRIPTION
**Pull request by staskus**
Fixes #22392

Create Bar Chart card UI based on Figma designs (IqhXWz3Iir7RMb5XH5gGfZ-fi-181_7346):
- Display title combining 2 strings
- Display difference label made from `NSAttributedStrings`
- Display tabs reusing `FilterTabBar`. Added missing functionality and configurability to support our 
- Create a bar chart using DGCharts library https://github.com/danielgindi/Charts, reusing code and patterns from already existing `StatsBarChartView` that is displayed in `Days/Weeks/Months/Years`

For now, it's only a UI logic, therefore the last commit provides a testing environment within Traffic to see different configurations. I'll remove it before merging.

I leave for the future to:
- Provide 7 sets of data for a week, 4-5 for a month, 12 for a year
- Provide dummy days/weeks/months if the period hasn't ended yet
- Handle analytics

### Design
1. Set `StatsTrafficBarChartMockVC` instead of `trafficTableViewController` in `SiteStatsDashboardViewController`
2. Enable Stats Traffic feature flag
3. Open Stats
4. Open Traffic tab
5. Compare cards with the designs
6. Change dynamic type, dark/light mode, voiceover, orientation, languages

### Integration

There's soft integration implemented replacing the old chart with a new chart within Traffic tab. However, view mode is not yet configured so I think it's worth staying with UI tests for now.

| Image 1 | Image 2 |
|---------|---------|
| Simulator Screenshot - iPhone 15 - 2024-01-19 at 13 26 36 | Simulator Screenshot - iPhone 15 - 2024-01-19 at 13 26 32 |

## Regression Notes
1. Potential unintended areas of impact

None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing

3. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [x] VoiceOver.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by irfano** [comment]
Great job! Graphs are very identical to the design. 👏🏻 

### Some nitpicks regarding sizes



- Is the comparing sentence lost due to the test data? 



- The traffic tab doesn't keep its state when selecting tab changing tabs, while the INSIGHTS tab does that. See the video. After reselecting the TRAFFIC tab, the page is being scrolled to the top. The behavior was not like this on the DAYS, WEEKS tabs.

https://github.com/wordpress-mobile/WordPress-iOS/assets/2471769/a2c64f5c-4f62-4337-9ed8-7030ed299941

**Comment by staskus** [comment]
@irfano, thanks for testing! 🙇 

> Some nitpicks regarding sizes

Thanks, I'll check those out!

> image

This is a testing view, plus the date picker will be shown but we'll have that in mind.

> image

That's a great observation. I spent way too much time on this and couldn't do it. This 3rd party chart library has a setting to automatically have half of a bar width margin OR one needs to calculate bar placement manually. However, the calculations weren't done in pixels but in proportions. I have 2 pages in my notebook full of math equations but there was always a variable I hadn't taken into account when calculating and something would be off. 🤔 I decided to keep a default behavior. 

image

Yes, it's 11. Languages with longer names didn't fit. Unless I could shrink all the label sizes only if one of the labels reaches a certain character limit. There's no automatic on iOS to shrink the font size of all these labels together if one of the labels doesn't fit.

> Is the comparing sentence lost due to the test data?

Yes. I wanted to show how the card would look when comparison exists vs when it doesn't exist. This comparison is a big question for me:

1. When we have the current date selected, period data will be incomplete, so a comparison is misleading. Unless we compare the same amount of days (weeks, months) from the previous period vs the same amount of the current period, we could say: _it's higher or lower by x% so far_. 
2. I will now fetch data for total numbers using `stats/$site/summary`, which only allows fetching a single period at a time, compared to `stats/$site/visits` which returns an array of data for a given period and unit. Comparing two `stats/$site/summary` won't allow to display Comparison label for the current date, since the period won't be complete. (Coming back to the first point)

I'm interested in how you're planning to handle it on Android?

> The traffic tab doesn't keep its state when selecting tab changing tabs, while the INSIGHTS tab does that. See the video. After reselecting the TRAFFIC tab, the page is being scrolled to the top. The behavior was not like this on the DAYS, WEEKS tabs.

Thanks! Good point. I made a note to do this functionality when we integrate the view within the real Traffic tab. Since the view is refreshed when it appears, we need to remember the selection from the view model side.

**Comment by staskus** [comment]
>  image

I made the change to have a default (13) font size, unless a label is longer:

| Spanish                                                   | English                                                   |
|-----------------------------------------------------------|-----------------------------------------------------------|
| Spanish | English |

**Review by guarani — APPROVED** [review]
👋 This looks great! 
I didn't verify each calculation (e.g. the positioning the ticks), and instead looked at the overall structure of the code, looked for memory leaks or anything that looked off in the code, and tested on iPad. I didn't find any issues, so I'm approving. Let me know if you think a detailed code review is necessary. 

About the comparison for the current period vs. the previous period: The app currently compares the current (incomplete) period with the past (complete) period, but I think this could be confusing and not showing the comparison in this case seems more intuitive to me.

Thanks @irfano for testing the UI! ❤️

**Pull request merged**
