### PR TITLE
Reader: Enable comments button for Jetpack sites

### LINKED ISSUE #7660: Jetpack: add support for comments on reader
We have some inconsistencies on comments for JP sites, for example on the Followed sites section, there's no comments button for JP sites:

simulator screen shot aug 4 2017 12 45 03

However, navigating to Manage->Site does display the comments button, and works as expected in properly configured JP sites. 
simulator screen shot aug 4 2017 12 45 57

JP Comments are coming soon to reader and we want to fully support them in the apps too.

### PR DESCRIPTION
**Pull request by elibud**
Fixes #7660 

To test:
1. Follow a Jetpack site with comments enabled
2. Reader->Followed Sites->check that the comment button is there
3. Check that you can post a comment

Needs review: @aerych

### CODE REVIEW

**Comment by elibud** [comment]
There are still some server sides issues that need to be sorted before merging this one.

**Comment by aerych** [comment]
Tested on my own Jetpack sites and commenting worked as expected, but these sites avoid the server-side pitfalls others have found. 
Once the server-side issues are sorted, and the squad gives their blessing, this is good to :shipit:

**Comment by elibud** [comment]
Thanks a million for the review and for checking with the Reader team @aerych

**Comment by elibud** [comment]
Moving this to target 8.5 since there are some server side issues still pending.

**Comment by elibud** [comment]
@aerych can you take a quick look at this one again so we can merge before the code freeze? I've hid it behind a feature flag for internal testing as I've learned today that's what we are doing on Reader too.

**Comment by aerych** [comment]
Retested to confirm nothing went awry between now and the last time I checked.  Everything still worked.
Tested the flag to confirm showing/hiding the feature. 👍 
:shipit: @elibud :)

**Pull request merged**
