### PR TITLE
Making Post Card adapt to bigger font sizes.

### PR DESCRIPTION
**Pull request by etoledom**
This PR fixes an issue on the Post List, where the layout was broken when using big font sizes.

post-list-accessibility

**Notes:**
My first strategy was to replace many of the manually added constraints with StackView, since it's a lot easier to manage self sizing views with them.

Stack Views also makes it trivial to adapt the UI Layout when showing/hiding views, so all the code managing constraints became not necessary.

This is also true for the featured image view, just by assigning `isHided = true`, the layout will adapt as the view was never there, making the `PostCardImageCell.xib` unnecessary. (As noted by @pinarol )

A last detail, using the power of stack views was to layout the time label with the metadata labels vertically when bigger fonts are on use. This gives more horizontal space for the labels to show it's content properly. (cc @iamthomasbishop )

Hopefully with these changes it will be easier in the future to add/remove elements to the post cards, since they are now based mostly on StackView and there is just one `xib` to modify. It will also be more difficult to make them not adaptable to dynamic font sizes.

**To test:**

- Check that the post list displays correctly with normal font size.
  - Be sure to test posts with and without images.
  - Also test posts on sites that will and won't display the header (personal site vs sites with multiple users)
- Increase the font size to one of the accessibility font sizes.
  - iOS Settings -> General -> Accessibility -> Larger Text -> Turn the switch ON -> Increase the font size.
- Make the same test than before.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
@etoledom This is looking wonderful – thanks for wrangling this! I know it's a challenge to make the UI look clear and orderly with such large fonts, so I think that's about as good as it's going to get. :shipit:

**Comment by pinarol** [comment]
thanks a lot for this @etoledom I love this PR! 🎉I love when deleted code is bigger than added code :) getting rid of the duplicate xib is awesome! and we get to have some really robust layout constraints anymore, thanks to you!

**Comment by iamthomasbishop** [comment]
@etoledom A couple very small things that I missed on first review (apologies!):

* Can we make the blavatar image stay at the same size it was previously?

* The spacing to the right of the `clock` icon looks okay with the large font-size, but it looks a bit much on the "normal" example. Is this a static value, regardless of font-size? I think we could tighten that up a bit

Thanks again and apologies for missing this on the first glance! :)

**Comment by etoledom** [comment]
Thank you @nheagy for the review!

@iamthomasbishop - I made the requested changes.

> Is this a static value, regardless of font-size?

Yes it is. But we can convert it on a dynamic value if necessary.
I tried the smaller spacing and, for me, it doesn't look really bad with big text sizes. Let me know if you think otherwise so I can make it increase in those special cases.

This is the updated screenshot:

post-card

**Comment by iamthomasbishop** [comment]
Thanks @etoledom, this looks better. One more last thing: the spacing between the site and author labels looks like a lot, but it's not a huge issue and can be addressed separately if need be.

Example:

screen shot 2019-01-16 at 10 56 02 am

**Comment by iamthomasbishop** [comment]
Awesome, thank you! :shipit:

**Pull request merged**
