### PR TITLE
Issues/6358 reusable card view

### PR DESCRIPTION
**Pull request by aerych**
Refs #6358
This is part 2 of a multi-part PR to add support for related posts to the reader detail.

This PR extracts the reader's card view from ReaderPostCardCell into its own reusable view: ReaderCard.  This is mostly just moving code around but there is a small refactor to use the ReaderPost model directly instead of indirectly via the ReaderPostContentProvider protocol.

To test:
Test the cards in the reader stream.  Confirm that layout is correct and controls (buttons etc.) are properly responsive.

Needs review: @jleandroperez could I trouble you with this one?

### CODE REVIEW

**Comment by jleandroperez** [comment]
Hey there @aerych!! I'll be afk-ish this week (on holidays!). Just in case i don't make it on time for 6.9, would it be possible to signup somebody else? (Don't wanna delay you!!!).

Apologies about this!!!

**Comment by aerych** [comment]
No worries @jleandroperez !   Happy holiday!

**Comment by aerych** [comment]
@kurzee can I pass the baton to you?

**Comment by kurzee** [comment]
Interesting bug, maybe not related to these changes:

1. Open up a stream of sites you're following.
2. Hit the top-right Follow/Unfollow button to unfollow the site in the cell.
3. After it unfollows, hit the but again to follow it.
4. After it follows, notice you can't tap on any of the buttons in the cell, but you can scroll.
5. Reusing the cells fixes the issue, naturally.

**Comment by kurzee** [comment]
Just a quick note, would it make sense to refactor the use `ReaderPostContentProvider` in the other cells/views in this PR as well? (Probably for another day)

**Comment by aerych** [comment]
> would it make sense to refactor the use ReaderPostContentProvider in the other cells/views in this PR as well

Yah, we can phase it out over time.

**Comment by aerych** [comment]
> Interesting bug, maybe not related to these changes.

Oh interesting... and good catch.   I can reproduce this in release/6.8 so I think its not new. :/  I'll open a new issue for it and we can tackle it there.

**Comment by kurzee** [comment]
>Oh interesting... and good catch. I can reproduce this in release/6.8 so I think its not new. :/ I'll open a new issue for it and we can tackle it there.

Sounds good to me. :shipit:

**Comment by aerych** [comment]
Thanks @kurzee !!

**Pull request merged**
