### PR TITLE
Update WordPressAuthenticator to sign-up bug

### PR DESCRIPTION
**Pull request by guarani**
Fixes an issue were login via A8c WP.com account was not working

To test:
1. Log in using an A8c WP.com account
2. Verify you can log in successfully

## Regression Notes
1. Potential unintended areas of impact

3. What I did to test those areas of impact (or what existing automated tests I relied on)

4. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by guarani** [comment]
👋 @mokagio, looping you in here for the beta release.

**Review by mokagio — APPROVED** [review]
The upgrade looks good.

I was able to reproduce the Webauthn error in the 23.5.0.1 TestFlight build:

And I was able to login with the App Center build from this branch ✅

But ☝️ : 

1. The 1Password flow from the prologue screen remained stuck on the spinner
 
Screenshot 2023-10-20 at 1 18 47 pm

2. My security key didn't work. However, that might be because I only created one on my Mac? I don't know I haven't started using passkeys yet 😳 
3. 
Screenshot 2023-10-20 at 1 29 50 pm

Approving because even if there's an issue in the code, it's likely to be in the auth lib, so there's little that can be done here. Plus, releasing to TestFlight will allow more people to try the flow.

**Comment by mokagio** [comment]
cc @antonis @Ecarrion

**Review by antonis — COMMENTED** [review]
Thank you for the fix @guarani 🙇 
I've tested with the latest beta (23.5.0.2) on my iPhone SE (2nd gen, iOS 16.4.1):
* I was able to login with an authentication code ✅ 
* When using a passkey I get the same error as Gio above ❌ 

|Authentication screen|Passkey error|
|---|---|
|IMG_0219|IMG_0220|

I think this unblocks the usage of the app for A8Cs 🎉 

For full passkey support I think we also need the entitlements file @Ecarrion has added on his PR https://github.com/wordpress-mobile/WordPress-iOS/pull/21739

**Comment by staskus** [comment]
Yes, @antonis and @mokagio the alert is not descriptive but the error message is:

> The operation couldn’t be completed. Application with identifier 3TMU3BH3NK.com.automattic.jetpack is not associated with domain wordpress.com

Maybe that PR https://github.com/wordpress-mobile/WordPress-iOS/pull/21739 is addressing it, need to find out more.

**Pull request merged**
