### PR TITLE
Rename feature flag build configurations to be easier to understand

### PR DESCRIPTION
**Pull request by nheagy**
To make it clearer where our feature build configurations apply.

### Discussion:
When setting up a feature flag, it's not entirely clear where a build configuration will apply, especially 'alpha' and 'internal'. By renaming them, hopefully setting up a new feature flag will be easier thus encouraging their use.

To test:
- make sure everything still builds
- make sure the BuddyBuild build still runs

Needs review: @astralbodies

### CODE REVIEW

**Comment by elibud** [comment]
This is spot on, I keep getting confused about what alpha is.

**Comment by nheagy** [comment]
Well to be fair it was your idea @elibud 😆

**Comment by astralbodies** [comment]
Calling a feature targeted for buddybuild isn't entirely accurate as well. In most cases buddybuild uses the "WordPress-Alpha" scheme - but there are some instances where the WordPress scheme is built in addition. At some point we're going to make our CI solution also handle our App Store builds and probably the internal beta builds too.

Any suggestions on a name that declares a build meant for PR/branch testing (pre-beta) that isn't alpha? Some of the confusion may also come from WP Android using alpha to describe a build used for beta testing. If you can come up with a good alternative we should also update the scheme name and associated compiler flags for consistency. 😄

**Comment by elibud** [comment]
@nheagy I said it confused me, but you took the initiative to fix it :)

The best name I can think of is: WordPress-CI

What do you think?

**Comment by nheagy** [comment]
Ok @astralbodies here's another attempt, with what I hope are workable names.

Let me know what you think!

**Pull request merged**
