### PR TITLE
Reader: Add reader post card cell actions

### PR DESCRIPTION
**Pull request by wargcm**
Part of #21645 
Merges into #21687

## Description

Adds:

- Tap actions to the new reader post card cell
- A "Save" action in the more menu

## Testing

To test:
- Launch Jetpack and login
- Enable the `Reader Improvements v1` feature flag if necessary
- Tap on Reader
- Tap on a **post's site title**
- 🔎 **Verify** it navigates to the site's details
- Navigate back to the reader posts
- Tap on the **Reblog** action
- 🔎 **Verify** a site picker appears
- Dismiss the site picker
- Tap on the **Comment** action
- 🔎 **Verify** it navigates to the comment section of the post
- Navigate back to the reader posts
- Tap on the **Like** action
- 🔎 **Verify** the post updates indicating the post is liked and the like count increases
- Tap on the **Liked** action
- 🔎 **Verify** the post is no longer liked and the like count decreases
- Tap on the **More (`...`)** action
- 🔎 **Verify**:
  - The actions work correctly
  - A new "Save" action appears and works correctly
- Save a post if necessary
- Navigate to your `Saved` posts
- Tap on the **More (`...`)** action for one of your saved posts
- 🔎 **Verify** a `Remove Saved Post` action appears
- Tap on `Remove Saved Post`
- 🔎 **Verify** the post is replaced by an "Undo" cell
- Tap on `Undo`
- 🔎 **Verify** the saved post reappears

**iPad**:
- Launch the app on iPad
- Navigate back to the Reader
- Tap on the **More (`...`)** action
- 🔎 **Verify** the menu appears next to the More (`...`) button

## Regression Notes
1. Potential unintended areas of impact
Removing saved posts for the old reader card

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by dvdchr — APPROVED** [review]
LGTM with one minor issue as this is a work in progress. Tested these changes:
- Tapping on the site title navigates to the site stream ✅ 
- Tapping Reblog shows a site selector sheet ✅ 
- Tapping the Like button increases the Like counter, but the button state is inconsistent ⚠️ 
- Tapping More > Save saves the post correctly ✅ 
- The More menu appears next to the ellipsis icon on iPad ✅ 

Found a small issue regarding the Like button state, which seems to be a race condition. Here's a quick recording:

https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/bc0e3111-6637-4312-9583-6977e44fefe5

**Comment by wargcm** [comment]
@dvdchr I wasn't able to reproduce that on my end (race conditions are fun 😆).

https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/4f7fb1ab-ba5b-4244-89e1-f3686c44e5c3

But I think I know why that happens. There was some code I copied over with the like button that I considered deleting, but I wasn't sure if it was accounting for some edge case. Could you try again with the changes from https://github.com/wordpress-mobile/WordPress-iOS/pull/21696/commits/2c0d1eb9fb3db286203b4557604d8277b598dead and let me know if you still see the issue?

**Comment by dvdchr** [comment]
Okay, it might be an edge case. I tried to like a post from the Following tab, which was a test site (Riccardo's). Here is another recording from a Simulator, running the latest commit https://github.com/wordpress-mobile/WordPress-iOS/pull/21696/commits/9870408a0b75d71e2601d7e4b04ae7e4fe0a9fb2:

https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/f8335069-c695-4a12-9b31-51c60e6c0438

However, it worked fine when I tried liking other posts, so let's roll with it for now, and I can open a separate ticket for us to investigate further.

**Comment by wargcm** [comment]
I accidentally merged the accessibility PR into this one, but it should be fine since it was already reviewed.

@dvdchr Thanks for checking again!

**Pull request merged**
