### PR TITLE
Fix/16941 - Close account displayed localizable string

### PR DESCRIPTION
**Pull request by nikola-milicevic**
This PR changes localizable string displayed when close account error occurs due to having atomic site to a more generic one, with the instruction to contact support.
This change is needed because having an atomic site is something that's considered being an implementation detail user might not necessarily know about.

## To test:
1. Make sure the current user has an atomic site
2. Under **My Site** tab tap on profile button at the top right corner
3. Tap on **Account Settings**
4. Tap on **Close account**
5. Close account alert is displayed

## Screenshot:
Screen Shot 2021-08-24 at 01 56 30

## Regression Notes
1. Potential unintended areas of impact
n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a

3. What automated tests I added (or what prevented me from doing so)
n/a
PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nikola-milicevic** [comment]
@leandroalonso @mokagio This PR is simpler version of [#17076](https://github.com/wordpress-mobile/WordPress-iOS/pull/17076), so only one of these two should be merged.

**Comment by mokagio** [comment]
@nikola-milicevic @leandroalonso can I have more context on why this change is Priority High and cannot wait until the next release? In asking that, I realize that the next release will actually reach users four weeks from now so we'd have extra two weeks in with this suboptimal messaging.

I'm asking that not because I want to delay your work, but because we tend to merge PRs in the release branch only if they are important bug fixes or in cases such as #17065, where we have a new feature scheduled to ship.

Just want to make sure, that's all. 😄 

If this kind of tweak is necessary for 18.1, I'd rather merge this PR than #17076. This one doesn't change any of the app logic, so there's basically no risk of a regression being introduced.

Thanks! 👍

**Comment by nikola-milicevic** [comment]
Hey @mokagio 👋 this [WPiOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/17029) and [WPKit-iOS](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/435) PRs solved the [original issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/16941). Apple introduced a [change in App Store Review Guidelines](https://developer.apple.com/news/?id=dovxb62h), so we had to add close account functionality to the app itself. 

This PR changes a displayed error message to a more generic one (with added contact support instructions) in one of the cases where user account cannot be closed due to having atomic site, which is an implementation detail.

So in order not to confuse the user potentially (which was spotted by a translator 😊) it would be good to have this in 18.1. And we can wait for the next release for [#17076](https://github.com/wordpress-mobile/WordPress-iOS/pull/17076).

**Review by leandroalonso — APPROVED** [review]

**Comment by leandroalonso** [comment]
@mokagio The intent with this PR is to be merged only if it will not require additional work on your side (like resubmitting strings for translation).

If that's the case we can go ahead and merge it, if not, no problem to target `develop`. What would you suggest?

> And we can wait for the next release for #17076.

@nikola-milicevic agree. Can you change it to `develop`, please? :)

**Comment by nikola-milicevic** [comment]
> @nikola-milicevic agree. Can you change it to `develop`, please? :)

Sure thing! Thanks @leandroalonso!

**Comment by mokagio** [comment]
>  The intent with this PR is to be merged only if it will not require additional work on your side (like resubmitting strings for translation).

Ah, no worries about that. Apart from the fact that release engineering _is_ my work (so it wouldn't count as extra work but just as one of the task I do as part of my role) the process only requires running a script 👍 

Given this extra context, I'm happy to merge it against the release branch so we can close the loop and give our users a better experience from the get go.

**Comment by mokagio** [comment]
@nikola-milicevic this has been bundled as part of [18.1 beta 2 (18.1.0.2)](https://github.com/wordpress-mobile/WordPress-iOS/pull/17080).

Thanks for your work 🙌

**Comment by leandroalonso** [comment]
Thank you so much, @mokagio!

**Pull request merged**
