### PR TITLE
My Site Dashboard: Remove table header view from BlogDetailsViewController

### LINKED ISSUE #17805: My Site Dashboard: Remove tableheaderview from BlogDetailsVC
## Description

Refactor the BlogDetailsVC to remove the tableheaderview and reuse SitePickerVC, regardless of the MSD flag state.

Currently we're only using the SitePickerVC if the MSD flag is true.

## Tasks

- [x] Completely remove tableheaderview from BlogDetailVC #17805
- [x] Use SitePickerVC if MSD flag is false #17805

### LINKED ISSUE #17853: Quickstart: View your site does not scroll the my site list to the View Site menu button.
### Expected behavior
During quickstart, when covering the View your site step, the my site list should scroll to the View Site menu button.

### Actual behavior
During quickstart, when covering the View your site step, the my site list should does not scroll to the View Site menu button.

### Steps to reproduce the behavior
Note: I tested this with an iPad that has a split view. Not sure if the issue is only relevant to iPad or can occur in iPhones as well.

- Opt into the QuickStart steps
- Complete the steps for "Customise Yout Site"
- When coming to the 6th step ("View your Site") notice the my site list is not scrolled to the View Site menu button

image

### PR DESCRIPTION
**Pull request by momo-ozawa**
Fixes #17805
Fixes #17853 / #16402

## Description

This PR removes the table header view from BlogDetailsViewController, and completely switches over to using the SitePickerViewController as an embedded child view controller (regardless of whether the My Site Dashboard is enabled or disabled).

This completes phase 1 of the My Site Dashboard project. (Ref: pbArwn-3mP-p2)

## How to test

⚠️ Do a clean install, and make sure the MSD feature flag is **disabled** (should be disabled by default)

### Quick Start auto scroll 

1. Log in
2. Tap "Show me around" in the post-epilogue Quick Start prompt
3. Go through every single Quick Start element for both check lists
4. ✅ Make sure the screen scrolls to the correct position for Quick Start elements in the site menu

### FAB

1. Go to My Site > Site menu
2. Tap on the FAB > Blog post
3. Create a draft post
4. ✅ Make sure that the draft post is there when you go to Posts > Drafts
5. Tap on the FAB > Site page
6. Create a draft page
7. ✅ Make sure the the draft page is there when you go to Pages > Drafts

### Site Picker

1. Tap on the site title
2. Change the title and tap Save
3. ✅ The site title should be updated
4. Tap on the site icon
5. Update your site icon (Choose image from device, Create with emoji, Remove site icon)
6. ✅ The site icon should be updated
7. Tap on the site url
8. ✅ A webview of your site should be displayed
9. Switch to a different site
10. ✅ The site switcher displays the selected site
11. ✅ The site menu (BlogDetailsVC) has updated to the selected blog

### Pull to refresh

1. Open the app
2. Change the name of your blog on your browser
3. Pull to refresh
4. ✅ The title change should be reflected

## Regression Notes
1. Potential unintended areas of impact
- Site Picker
- Pull to refresh 
- Quick Start auto scroll
- FAB

2. What I did to test those areas of impact (or what existing automated tests I relied on)
- Tested the above steps manually

3. What automated tests I added (or what prevented me from doing so)
- N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by leandroalonso — COMMENTED** [review]
@momo-ozawa I had an issue with the "Stats" step on Quick Start, the inset doesn't return to its initial state after finishing this step:

https://user-images.githubusercontent.com/7040243/152166112-f78264bf-aa51-4b67-9db5-b3429315cc16.mp4

**Comment by momo-ozawa** [comment]
@leandroalonso 

Fixed! f6b6828

<details>
  <summary>Click to expand for video</summary>
  
  https://user-images.githubusercontent.com/6711616/152174937-8ed2d9f5-61b3-4720-9230-8d5c824fc41d.mp4
</details>

This was happening because we weren't explicitly scrolling to the top when we start Site Icon and Site Title Quick Start tours. (Note: This is a pre-existing issue, and can be reproduced in prod.)

**Comment by jkmassel** [comment]
You can test the <strong>Jetpack</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/jetpack-installable-builds/'>here</a> with build number: <code>pr17863-f6b6828</code>. IPA is available <a href='https://appcenter-filemanagement-distrib5ede6f06e.azureedge.net/5ded0dcf-e5b6-4dd6-9be2-da2442b9bdfe/Jetpack%20Alpha.ipa?sv=2019-02-02&sr=c&sig=gR6nGkscdJt%2BVot%2F2b3heNX7cp7SsqB%2B5XCDX6R00eg%3D&se=2022-02-03T14%3A51%3A04Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

**Comment by jkmassel** [comment]
You can test the <strong>WordPress</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/WPiOS-One-Offs/'>here</a> with build number: <code>pr17863-f6b6828</code>. IPA is available <a href='https://appcenter-filemanagement-distrib4ede6f06e.azureedge.net/c3412f0c-f3e7-48f6-91bb-b07c12370c26/WordPress%20Alpha.ipa?sv=2019-02-02&sr=c&sig=r5TQz7YMmZPNU4f4oA6dnD9dB8JRY1hJ1RsUL6N%2BwyE%3D&se=2022-02-03T14%3A52%3A30Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

**Comment by momo-ozawa** [comment]
@leandroalonso @pachlava 
Just a heads up that I addressed the site icon spotlight getting cut off in a separate PR (https://github.com/wordpress-mobile/WordPress-iOS/pull/17865)

**Review by leandroalonso — APPROVED** [review]

**Review by pachlava — APPROVED** [review]
Thanks for the outstanding manual test steps included into the PR! Firstly, it reflects your care about testing, and secondly, it helps others to test 👍 

I tested under real iPhone XR and not so real iPad 9th Gen. The only issue(?) I found is that on iPhone XR, in split view, it's quite hard to make PTR work (no matter how "far" I tried to pull, the refresh wasn't initiated in most of the cases). I know that split view is not expected to appear on iOS, and I think there's a minimum amount of users that will stick to it, even if they can activate it, so I'm not sure if it's a valid issue:

<details>
  <summary>Click to expand for video</summary>

https://user-images.githubusercontent.com/73365754/152348359-6ebf8b38-c4f7-4921-86d7-cbaec954925d.MOV
</details>

I'm switching to #17865 now...

**Comment by pachlava** [comment]
> I know that split view is not expected to appear on iOS, and I think there's a minimum amount of users that will stick to it, even if they can activate it, so I'm not sure if it's a valid issue

Hm I just tested on iPhone 13 sim, and realized that PTR is similarly hard to activate in non-split, but landscape mode, which makes the issue a bit more accessible:

<details>
  <summary>Click to expand for video</summary>

https://user-images.githubusercontent.com/73365754/152352130-e1aba3ac-58c0-4db0-afe3-30faa3a8a026.mov
</details>

**Comment by leandroalonso** [comment]
@pachlava I saw the same while testing a previous PR. At the time I checked the current version available on the App Store and the issue is there too.

Given it was never reported before I assume is not a blocker. Could you please open an issue for that? I think maybe it might be a good first issue. :)

**Comment by pachlava** [comment]
Created #17882 for the PTR issue.

**Pull request merged**
