### PR TITLE
Jetpack Migration: Clean up exported content on WP log out

### LINKED ISSUE #19738: iOS - Exported data from WordPress not purged on log out
Refs pcdRpT-1i3-p2#comment-2187

### Expected behavior
- Jetpack should import the current account logged in to WordPress.
- The exported content from the previous account in WordPress should've been wiped upon logging out.

### Actual behavior
Under certain conditions, Jetpack imports the previous account logged out from WP instead.

### Steps to reproduce the behavior

Note that the `contentMigration` flag needs to be switched on. Refer to pcdRpT-1i3-p2#comment-2187 for a demo video.

1. Start without JP installed.
2. Log in to account A on WordPress.
3. Tap the Jetpack-powered banner > bottom sheet > Try button to trigger the export. Don’t install JP for now, and return to WP.
4. Log out from WP, and log in with account B.
5. Install JP.
6. Open the JP app and go through the migration process.
7. Observe that a login popup screen is shown.

This happens because we only trigger the export on the app start-up or after tapping the “Try the new Jetpack” button. After logging in to account B, we didn’t replace or wipe the exported data from the previous account. 

~~Additionally, when JP imported account A, I expected things not to work since the auth token should’ve been account B’s. But surprisingly, it works pretty well.~~ This only happens in the Simulator environment. When tested on a real device, the auth token is properly removed, and the login screen is presented instead. For more info, refer to pcdRpT-1i3-p2#comment-2235

##### Tested on iPhone 14 Pro Simulator, iOS 16.1, WPiOS release/21.3

### PR DESCRIPTION
**Pull request by dvdchr**
Fixes #19738 

As titled, this will update the exported data when the user logs out from their dotcom account OR removes a self-hosted site. The logic is as follows: 

- After logging out / removing a site, if the user is still eligible, try to re-export the data again. This ensures that the exported data will match the latest state of the Account and/or Blogs on the WP app.
- Otherwise, remove all exported content.

#### 1️⃣ Verify that the clean up behavior is correct in WordPress

- Ensure that the `contentMigration` and `jetpackPoweredBottomSheet` feature flags are turned on in WP.
- Ensure that the Jetpack app is not installed.
- Select one of the starting states listed in the table below, and perform the necessary steps to set up the WP app according to the chosen starting state.
- Tap on any Jetpack-powered banner > "Try the new Jetpack app" button to trigger the export.
- Perform the user action listed in the table below, according to your chosen scenario.
- Verify the expected clean-up action.
  - To verify 🧹  Remove exported data, there are two ways:
    - Install the Jetpack app with the `contentMigration` flag turned on (e.g., `21.3.0.1` from TestFlight) and verify that the **migration welcome screen is NOT shown**.
    - Perform the testing actions on a developer build targeting the Simulator. Navigate to the location of the App Group `group.org.wordpress` (via tools like [SimSim](https://github.com/dsmelov/simsim)), and verify that **the database backup file is not present in that directory.**
  - To verify ♻️  Re-export data, there are two similar ways:
    - Install the Jetpack app with the `contentMigration` flag turned on (e.g., `21.3.0.1` from TestFlight) and verify that the **migration welcome screen is shown**. Additionally, verify that the Blogs you've removed **do not exist within the list of blogs in the welcome screen**.
    - Perform the testing actions on a developer build targeting the Simulator. Navigate to the location of the App Group `group.org.wordpress` (via tools like [SimSim](https://github.com/dsmelov/simsim)), and view the contents of `WordPress.sqlite` with an [SQLite Browser](https://sqlitebrowser.org/). Verify that the `Blog` (or `Account`) you've removed is no longer there.
- Repeat the steps above, with a different starting state and user action.

Starting state | User action | Expected clean-up action
-|-|-
Dotcom account | Log out from dotcom account | 🧹  Remove exported data
Dotcom account + 1 self-hosted site | Log out from dotcom account | ♻️ Re-export data
Dotcom account + 1 self-hosted site | Remove site | ♻️  Re-export data
Dotcom account + multiple self-hosted sites | Remove site | ♻️ Re-export data
Multiple self-hosted sites | Remove site | ♻️ Re-export data
Single self-hosted site | Remove site | 🧹  Remove exported data

#### 2️⃣ Verify that Jetpack should be unaffected by this change

- Ensure that the `contentMigration` and `jetpackPoweredBottomSheet` feature flags are turned on in JP.
- Select any one of the starting states listed in table above 👆🏼 , and perform the necessary steps to set up the WP app according to the chosen starting state.
- Perform the user action listed in the table below, according to your chosen scenario.
- Verify that the expected clean-up action is not executed in JP.

### Unit tests

Ensure that all the tests are green. 🟢 

## Regression Notes
1. Potential unintended areas of impact
Should be none.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the changes.

3. What automated tests I added (or what prevented me from doing so)
Added unit tests to `ContentMigrationCoordinator` and `DataMigrator`.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by twstokes** [comment]
Reviewing this now. 👀  I've merged in the latest on `trunk` so the appropriate feature flags are enabled.

**Comment by twstokes** [comment]
Row 1: ✅ I did not see the migration welcome screen. I _did_ see the "It looks like you have the WordPress app installed." screen, but that's expected since it shows when no export data is detected but a [compatible WordPress version is installed](https://github.com/wordpress-mobile/WordPress-iOS/issues/19640).
Row 2: ✅ 
Row 3: ✅ 
Row 4: ✅ 
Row 5: ⚠️ 
Row 6: ✅ 

For row 5 of the above table (Multiple self-hosted sites), I started with two self-hosted sites in the WP app. I then removed one of the sites and restarted WP (wasn't sure if this was necessary).

After clean-installing the Jetpack app I was prompted with the migration screen, but after completing the migration the site I removed from WP was in JP. cc @dvdchr

**Review by twstokes — COMMENTED** [review]
Hey @dvdchr! 👋 This is looking really good. I only had one test case that didn't succeed for me - [see the comment here](https://github.com/wordpress-mobile/WordPress-iOS/pull/19754#issuecomment-1344436530) (I tested it twice just to be sure).

**Comment by dvdchr** [comment]
> I started with two self-hosted sites in the WP app. I then removed one of the sites and restarted WP (wasn't sure if this was necessary).

Yes, that's the correct way to ensure that the export-on-launch is kickstarted. 👍🏼 

**EDIT:** When you remove the Blog, the export process should've kicked off there to overwrite the existing data. So I guess something went awry there.

> after completing the migration, the site I removed from WP was in JP.

Hmm, that is strange 🤔 I was sure it worked as expected when I tested it, but I did refactor the test a bit since I confirmed the case passed. I'll take a look and fix it!

Thank you for taking the time to review and test this! @twstokes

**Review by wargcm — COMMENTED** [review]
Also tested this with slightly different results than @twstokes.

1️⃣ Verify that the clean up behavior is correct in WordPress
1. ✅
2. ✅
3. ⚠️ I see the data get exported again but the blog still appears in the database. Maybe this is a race condition?
4. Same as 3.
5. Same as 3.
6. ✅

For this set of tests, I was directly checking the contents of the database. I didn't go through the migration on the Jetpack side.

2️⃣ Verify that Jetpack should be unaffected by this change

1 - 2: ⚠ Logging out clears the shared data.
3 - 6: ⚠ Removing the site on Jetpack deletes the shared data.

I think the likelihood of someone hitting these scenarios in the Jetpack app to be really low. It'd require a user to already be logged in or have self-hosted sites in Jetpack, then go to WordPress, migrate their data, and then perform the logout/remove site action in Jetpack. Just doesn't seem like something that will actually happen IMO.

**Comment by dvdchr** [comment]
> I see the data get exported again but the blog still appears in the database. Maybe this is a race condition?

@wargcm Yes, you're spot on! I just pushed https://github.com/wordpress-mobile/WordPress-iOS/pull/19754/commits/a4cc8cc87a65c0e52b149fc2b9bd1755773d8079, and it should fix the issue. 🙂 

This should also fix @twstokes 's ⚠️ on row no. 5 too.

**Comment by dvdchr** [comment]
> I think the likelihood of someone hitting these scenarios in the Jetpack app to be really low. It'd require a user to already be logged in or have self-hosted sites in Jetpack, then go to WordPress, migrate their data, and then perform the logout/remove site action in Jetpack. Just doesn't seem like something that will actually happen IMO.

Yeah, that makes sense. I guess it just dawned on me now how unlikely this scenario will happen, and I kinda already went and fixed it in https://github.com/wordpress-mobile/WordPress-iOS/pull/19754/commits/85638feb6915efb04f83922f6ab55c551c09fa17 😅

**Review by twstokes — APPROVED** [review]
I re-tested the "Multiple self-hosted sites" flow and everything worked great! 🚀

**Review by wargcm — APPROVED** [review]
Same, 1️⃣ tests worked as expected!

For 2️⃣ tests, logging out in Jetpack still clears the shared data. Removing the sites no longer clears it. But as I already mentioned, I don't think it's a big deal.

**Pull request merged**
