### PR TITLE
Posts & Pages: Hide author if "me" is selected or blog has only one author

### PR DESCRIPTION
**Pull request by momo-ozawa**
Part of https://github.com/wordpress-mobile/WordPress-iOS/issues/21900

## Description
- Hides the author badge if "me" is selected, or if the blog has only one author
- Note that the search screen always shows the author

## How to test
- Switch to a site that only has one author
- Go to the posts screen
- Verify no author badge is shown
- Switch to a site that has multiple authors
- Go to the posts screen and show posts from "me"
- Verify no author badge is shown
- Show posts from "everyone"
- Verify the author badge is shown

https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/8b848f91-f492-4599-bd1b-db87ec0cbb26

## Regression Notes
1. Potential unintended areas of impact
Post screen / search screen

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested manually

3. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by kean** [comment]
Looks good!
Do you think search should be updated too?

**Review by kean — APPROVED** [review]

**Comment by momo-ozawa** [comment]
> Do you think search should be updated too?

@kean Actually on second thought, yeah. 

Another thought: should we disable author tokens if "me" is selected? Only enable them if "everyone" is selected?

Here's what happens when you select "me", but filter by a different author:

https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/bfb36f46-0f30-4dd6-b71c-e1aab925fdb2

**Comment by kean** [comment]
> Another thought: should we disable author tokens if "me" is selected? Only enable them if "everyone" is selected?

We touched upon the "Me" filter thing earlier with @osullivanchris earlier. So, the production behavior is to apply the "Me" filter to search results by default. And there is no indication to the user that that's happening, but maybe that's OK.

I had an idea earlier where if "Me" is selected, the app would display the search bar pre-populated with "Your Name" author search token. It'll make it clearer what's going on, and you'll be able to remove it if you want to.

Alternatively, the app could drop the "Me" filter when entering search, the same way it ignores the selected post status filter.

**Comment by momo-ozawa** [comment]
@kean - gotcha. Both alternatives make sense to me

**Comment by osullivanchris** [comment]
I'm ok with both those alternatives!

**Comment by kean** [comment]
I'm leaning toward searching all posts by default. It's simpler, and if your intention when opening search is to search for other people's posts, it'll work just as you would expect. If it's not, in the worst-case scenario, you'll see a few more posts in the results than you expected. You have an option to filter by author using search tokens. Most blogs only have one author anyway.

**Pull request merged**
