### PR TITLE
[Jetpack Remote Install] Enable feature flag

### PR DESCRIPTION
**Pull request by danielebogo**
Refs. #10277 

This small PR enables the Jetpack Remote Install feature for all the build configurations.

## To test
• Add a self-hosted site with no Jetpack installed
• Open Stats from your site dashboard
• Click on Install Jetpack
• Complete all the steps to install Jetpack

**Update release notes:**

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by danielebogo** [comment]
Thanks @frosty

**Comment by danielebogo** [comment]
@designsimply thanks for testing this. I saw the Jetpack install took around 6 seconds but the setup (WebView) is really slow. Do you know who can have a look to it? If we can improve it till we will have a full native flow.

**Comment by decipher05** [comment]
I tested the install on my XR on 12.2 and it failed the first time. I believe it failed due to the site using a self-signed cert while trying to use https. I went and got a valid cert and re-tried and it completed quickly within 5 or so seconds.

**Comment by designsimply** [comment]
I am not sure, but I think we should circle back to look at this later once we do have a full native flow.

**Pull request merged**
