### PR TITLE
Empty state view: Update UI to match new design

### LINKED ISSUE #10126: Empty state view: Update UI to match new design
Update the empty state view (i.e. NoResultsView) UI to match new design for Actionable Empty States (fonts, spacing, text colors, etc).

**Current Example:**
current

**Design Example:**
tags

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #10126 

This updates the UI components to match the new Actionable Empty States design. Specifically:
- Title: update font size and text color.
- Subtitle: update font size and text color.
- Image: 
  - Set default to be "wp-illustration-empty-results". This image will be used for empty states unless another image is specified.
  - Use "mysites-nosites" image only for no sites, all sites hidden, and site creation progress view.
- Button: update text font size.
- Update spacing between elements.

wp-illustration-empty-results image:
empty_results

mysites-nosites image:
no_sites

NOTE: There is an issue with the display on iPad (https://github.com/wordpress-mobile/WordPress-iOS/issues/10128). That will be addressed separately.

To test:

---
**UI updates:**
- Go to a page that displays the No Results View. Verify the view looks similar to this (depending on the view, the image may differ):

no_tags

---
**No sites:**
- Either sign into an account with no sites or hide all sites on an account.
- Go to My Sites.
- Verify the image is the 'no sites' image:

hidden_sites

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @SylvesterWilmott . If you need more/different images or something just let me know.

**Comment by SylvesterWilmott** [comment]
It's looking good @ScoutHarris 

One question, how do these scale on iPad? We should probably include a maximum width to the bounding box. Can you include a tablet screenshot and we can figure it out from there.

**Comment by ScoutHarris** [comment]
Hey @SylvesterWilmott . I used the the spacing from the Zeplin project, which is 38 from the left and right edges (i.e. the labels will wrap accordingly). The iPad looks like this:

ipad_portrait

ipad_landscape

**Comment by ScoutHarris** [comment]
@SylvesterWilmott maybe this is better - is shows wrapping so you can see the width boundaries:

no_sites_port

no_sites_land

**Comment by SylvesterWilmott** [comment]
@ScoutHarris thanks for those tablet examples.

Can we just add a maximum width on all the empty state content bounding boxes of 360pt.

**Comment by ScoutHarris** [comment]
Hey @SylvesterWilmott . I updated the view to be a max width of 360. How's this?

pad_tags_port

pad_tags_land

pad_nosites_port

pad_nosites_land

**Comment by SylvesterWilmott** [comment]
Looks great @ScoutHarris ! Let's roll with these constraints across all empty states.

**Comment by ScoutHarris** [comment]
Thanks @SylvesterWilmott !

**Pull request merged**
