### PR TITLE
feat: Retry all failed uploads on manual retry

### LINKED ISSUE #6408: Introduce a “Retry all” option in the bottom sheet displayed upon upload failure
Ideally, uploads should automatically restart when reestablishing a connection. Providing an explicit option within the ActionSheet to retry all failed uploads can be valuable, especially when adding Gallery blocks.

**NOTE**: This change would primarily affect the iOS version, as the Android version already restarts all uploads when tapping on the “Retry” button.

Image

### PR DESCRIPTION
**Pull request by dcalhoun**
## Description

Retrying all failed media uploads when tapping the "Retry" button for a
single media item improves the UX and aligns with the Android product's
existing behavior.

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/6408.

## Testing Instructions
1. Disable network connectivity for your device.
1. Launch editor.
1. Add a Gallery block.
1. Add two or more images to the block.
1. Enable network connectivity for your device.
1. Tap one of the images.
1. Tap "Retry."
1. Verify all images retry uploads.

## Regression Notes
1. Potential unintended areas of impact
    Media upload for various block types.
2. What I did to test those areas of impact (or what existing automated tests I relied on)
    Inserted and attached media for various block types.
3. What automated tests I added (or what prevented me from doing so)
    None, lack of familiarity with testing technology and lack of example unit
tests.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by derekblank — APPROVED** [review]
I was able to test successfully using an internal build and observed that all failed uploads retried when one failed item was tapped. 🚀 

As with other related PRs, removing the release note until we remove the debug/internal build flag.

**Comment by guarani** [comment]
👋 I came across this while testing 24.1's features. Is it still possible to manually retry an image upload? When I turn the network back on, the uploads automatically resume (so there's no opportunity to retry manually). Was this superseded by https://github.com/wordpress-mobile/WordPress-iOS/pull/22282 which made the upload automatically resume after the network returns?

**Comment by derekblank** [comment]
> Is it still possible to manually retry an image upload?

Yes, it is still possible to manually retry an upload. Although the uploads will attempt to restart automatically, the upload failed state still exists. It's possible to trigger a failure by throttling the device connection to a weak 3G/4G -- we're working on improving the UX of that scenario in https://github.com/wordpress-mobile/gutenberg-mobile/issues/6583 (with video examples of failed uploads and manual retry attempts). If you have any further feedback on the upload failures/retries, it is very welcome on that thread. And thanks for testing! 🙇

**Comment by dcalhoun** [comment]
@Guarani thank you for testing. Leveraging a proxy — like Charles Proxy — to temporarily force a server error might be a straightforward way to test manual retries, as it will not trigger automatic retries.

**Comment by guarani** [comment]
Thanks for the info folks! 🙇

**Pull request merged**
