### PR TITLE
Caption shortcode support

### LINKED ISSUE #7715: Caption shortcode support.
## Description

We need Aztec to support the `caption` shortcode.  Extensive details can be found in the original issue [here](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/281).

## Details

This issue depends on another one from Aztec: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/723.

In terms of WPiOS the work that needs to be done is to convert caption shortcodes to `figure` + `figcaption` tags.

[Here's an example](https://www.w3schools.com/tags/tag_figcaption.asp) showing standard figcaption usage.

```html
<figure>
  <img src="img_pulpit.jpg" alt="The Pulpit Rock" width="304" height="228">
  <figcaption>Fig1. - A view of the pulpit rock in Norway.</figcaption>
</figure>
```

### PR DESCRIPTION
**Pull request by diegoreymendez**
## Description

Adds caption support to WPiOS through Aztec.

Fixes #7715 

## Details

To implement Caption support into WPiOS, this PR migrates some of the code we already have in Aztec's Example app.

What changed:

* New UI support for editing image captions in the image details view.
* Added `CaptionShortcodePreProcessor.swift` and `CaptionShortcodePostProcessor.swift` to handle the shortcode conversions to and from HTML.

## Testing

* Make sure you test editing both the caption and ALT fields.  Clear the fields.  Make sure any change is saved.
* Edit caption styles by right clicking on the text and using iOS's built-in styling options.
* Make sure captions are rendered.
* Make sure the HTML view shows captions properly.
* Make sure `<figure>` html elements are properly parsed too.  Pase the following snippet in HTML mode and switch back to visual:

```html
<figure>
  <img src="img_pulpit.jpg" alt="The Pulpit Rock" width="304" height="228">
  <figcaption>Fig1. - A view of the pulpit rock in Norway.</figcaption>
</figure>
```

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Ping @elibud to keep you updated on our 9.2 progress.

**Comment by diegoreymendez** [comment]
I found another issue.  It seems that if you combine captions with links, the output is incorrect.

Expected:

```html
[caption]<a href="www.wordpress.com"><img src="image.jpg" height="90" width="135"></a>Some text[/caption]
```

Actual:

```html
<a href="www.wordpress.com">

[caption]<img src="image.jpg" height="90" width="135">Some text[/caption]

</a>
```

**Comment by diegoreymendez** [comment]
The issue I found is reported [here](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/893).

**Comment by elibud** [comment]
@diegoreymendez should we move this one to 9.4?

**Comment by diegoreymendez** [comment]
Cleared the milestone since it's taking me more time than expected.

**Comment by diegoreymendez** [comment]
Aimed at `develop` since this is delayed.

**Comment by diegoreymendez** [comment]
@SergioEstevao, @bummytime - Can I ask you for a review of this PR?

This touches some of the code from the share extension because it integrates the latest from Aztec.  A lot of changes are included so please review and test with care!

Thanks!

**Comment by SergioEstevao** [comment]
Found a strange bug on the PR.

So if you do the following steps:

- Start a new post
- Tap on the + to add media
- Insert three images in one go
- After they are uploaded
- Tap on each of them and add a caption to each
- Switch to HTML and see that only one image is in the HTML

My main suspicious is that something is wrong on the Caption processor and we are replacing/capturing an extra character.

If you insert a character or a breakline between each image, all works correctly.

**Comment by SergioEstevao** [comment]
And it looks you still need addressed the concerns of a previous comment I made:

While the caption presentation and edition on the mobile editor is working perfectly, when the posts are save and sent to the server, the caption is not processed correctly on the web editors.

It looks that they need to be in the following format:
`[caption id="attachment_2816" align="alignnone" width="4032"]`.

It looks that this attributes of the caption shortcode need to be kept in sync with the correspondent attributes in the img element.

At a minimum I found that you need to write this on the opening shortcode: `[caption id=""]`

**Comment by diegoreymendez** [comment]
Thanks @SergioEstevao, will look into that.

**Comment by diegoreymendez** [comment]
Delayed for now: it seems captions are breaking when dealing with multiple adjacent images.  Will need to review.

**Comment by diegoreymendez** [comment]
As discussed privately with @SergioEstevao, I'll take care of the remaining issue as a bug report: https://github.com/wordpress-mobile/WordPress-iOS/issues/9219

**Pull request merged**
