### PR TITLE
Update hybrid editor to 1.9.7

### PR DESCRIPTION
**Pull request by SergioEstevao**
This PR updates the WordPress-Editor pod to version 1.9.7.

This updates addresses the following issues:

- Problems with the icons on the format toolbar being resized or going missing.
- Substitution of quotes and dashes for special quotes and special dashes. Ticket here: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/904
- It also prepare the editors for the iPhoneX

To test:
 - Launch the app
 - Activate the hybrid editor
 - Check if format toolbar works in the different orientations, devices, and iOS (10 and 11)
 - Test the same using the old legacy editor.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@frosty ready for a look.

**Comment by SergioEstevao** [comment]
@frosty update the reference to a real version of the pod and sorted out the merge conflicts.

**Comment by SergioEstevao** [comment]
@elibud Please keep this in your list to be merged before 8.6 goes out.

**Comment by elibud** [comment]
Will do, thanks for the heads up @SergioEstevao

**Pull request merged**
