### PR TITLE
Fix an issue with WebKitViewController not observing scroll view for edge appearance

### LINKED ISSUE #23493: Domains - TabBar has a transparent background in the detail screen when using Dark Mode
In `trunk` the TabBar does not have a background when using the app in Dark Mode and accessing the Domain's detail screen.

### Expected behavior
The TabBar should have a background in Dark mode

https://github.com/user-attachments/assets/37ee1cef-1fb7-4d33-b769-1bd30da153ec

### Actual behavior
The TabBar has a transparent background

https://github.com/user-attachments/assets/89a3192e-2551-450e-81e0-0810dce29287

### Steps to reproduce the behavior
- Open the app
- Go to "Me" in the TabBar
- All Domains
- Open a Domain

### PR DESCRIPTION
**Pull request by kean**
Fixes #23493.

(yes, there is a bottom padding on this page)

Screenshot 2024-08-13 at 1 21 12 PM

Screenshot 2024-08-13 at 1 21 18 PM

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by geriux** [comment]
Hey @kean 👋 

Part of the issue seems to be solved, one thing I noticed is that when scrolling down, the background disappears.

https://github.com/user-attachments/assets/dcef3fa1-cce0-4693-be71-abde02dc6b73

**Comment by kean** [comment]
It's a separate issue with dark mode, but we need to disable the scroll edge appearance for this screen. I'm going to move it back to draft.

**Comment by kean** [comment]
I switched to the standard approach for presenting wp.com pages in the app – presenting them in a modal screen with hardcoded `.light` color scheme:

Screenshot 2024-08-15 at 10 24 29 AM

**Review by geriux — APPROVED** [review]
LGTM! Thanks for addressing this! 🚀

**Pull request merged**
