### PR TITLE
Update screenshot test with new mocks

### PR DESCRIPTION
**Pull request by rachelmcr**
Updates the screenshot test with new mock data for new app store screenshots.

### Notable changes:

* Depends on https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/493 to support running the tests in any language.
* Depends on https://github.com/wordpress-mobile/WordPressMocks/pull/20 for the new mocks.
* Adds a new accessibility ID to the comment notification reply button.
* Makes some updates to the screenshot test to support the new mocked data (e.g. switching sites).
* Makes some updates to the UI tests and screen objects to support the new mocked data.

Note: We're aiming to use the new screenshots with the 15.9 release, but I'm targeting `develop` because we don't expect any significant UI differences between the `release/15.9` and `develop` branches.

#### Screenshots

Sample iPad screenshots:

Editor|Reader|My Site/Stats|Notifications|Editor with keyboard|Media
--|--|--|--|--|--
iPad Pro (12 9-inch) (2nd generation)-1-Editor-With-BlockPicker|iPad Pro (12 9-inch) (2nd generation)-2-Discover|iPad Pro (12 9-inch) (2nd generation)-3-Stats|iPad Pro (12 9-inch) (2nd generation)-5-Notifications|iPad Pro (12 9-inch) (2nd generation)-6-Editor-With-Keyboard|iPad Pro (12 9-inch) (2nd generation)-6-Media

Sample iPhone screenshots:

Editor|Reader|Stats|My Site|Notifications|Media
--|--|--|--|--|--
iPhone Xs Max-1-Editor|iPhone Xs Max-2-Discover|iPhone Xs Max-3-Stats|iPhone Xs Max-4-MySite|iPhone Xs Max-5-Notifications|iPhone Xs Max-6-Media

### To test:

* Confirm all the regular UI tests pass (WordPressUITests) on this PR.
* Confirm the WordPressScreenshotGeneration tests produces the expected screenshots:
  * Run `rake mocks` to start the mock server.
  * Open the fastlane directory with `cd Scripts/fastlane`.
  * Generate a set of screenshots: `bundle exec fastlane screenshots` for a full set in all languages (this takes a while) or e.g. `bundle exec fastlane screenshots language:"es-ES"` for a set of screenshots in a single non-English language to confirm it works for all targeted devices regardless of language.

### Before merge

- [x] Update the Podfile/Podfile.lock to use to the published WordPressAuthenticator and WordPressMocks pods (once those PRs are merged).

### PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by startuptester** [comment]
@rachelmcr, the first thing I ran across was that the image from the Editor screenshot is missing
image

**Comment by startuptester** [comment]
- [X] The UI tests pass
- [X] Script runs and screenshots are correct except for the missing image in the dog grooming page

**Comment by rachelmcr** [comment]
> the image from the Editor screenshot is missing

We currently don't mock the requests for media files, so likely the file wasn't loaded fast enough during your run.

I confirmed that it loaded and appeared in the screenshots when I generated them. Since it worked well on my end I thought we wouldn't need anything extra for that screenshot, but to avoid that flakiness I've added `sleep(imagesWaitTime)` before both of the editor screenshots to make sure the images have time to load.

I still need to resolve the Podfile.lock conflict, but I also need to update the two pod references that this PR depends on, so I'll plan to take care of that once those PRs are merged and the new pods are available.

**Comment by rachelmcr** [comment]
@startuptester Ok, pods are updated, conflicts resolved, and this is ready for another review!

**Review by startuptester — APPROVED** [review]
Ran script again in Spanish after merging of the two associated PRs. Ran without error and screenshots look good! 
💯

**Pull request merged**
