### PR TITLE
Stats Revamp: Updated Latest Post Summary Card

### LINKED ISSUE #18431: [iOS] Stats:  Latest Post Summary Card
We'll update the appearance of the Latest Post Summary card, showing:

* Post title
* Post timestamp
* Post thumbnail
* Views, likes, comments for the post

iOS-Insights-light-2

### PR DESCRIPTION
**Pull request by frosty**
Fixes #18431. This PR updates the appearance of the Latest Post Summary insights card to match the revamp designs.

Please see also this associated WordPressKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/499. It was necessary to add an extra property to a model that's defined there.

| Before | Design | After |
|---|---|---|
| Screenshot 2022-04-29 at 01 04 15 | iOS-Insights-light-2 | Simulator Screen Shot - iPhone 13 Pro - 2022-04-28 at 15 54 14 |

**Known issues**

- Loading and no data states are not addressed in this PR
- Dynamic type handling requires improvement

**To test**

- First, build and run, navigate to Stats Insights for a site, add the Latest Post Summary cell and ensure the cell looks as it does on the currently shipping app.
- Now enable both of the new stats feature flags and build and run again.
- Navigate to the Latest Post Summary card, and ensure it looks as per designs. The designs show `body` font styles for some labels, but the sizes of the text looks more correct when using `subhead`, so that's what I've gone for.
- Check the cell on a number of different sites.
- Also test with posts that do and do not have featured images.

## Regression Notes
1. Potential unintended areas of impact

Existing Latest Post Summary card (with feature flag disabled).

2. What I did to test those areas of impact (or what existing automated tests I relied on)

I ensured that any relevant changes were feature flagged, and tested this card with the feature flag disabled.

3. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by sla8c — APPROVED** [review]
LGTM!

**Comment by mokagio** [comment]
I took over merging this because I'm about to start the code freeze for version 19.8.

**Comment by frosty** [comment]
Hi @mokagio – this PR relies on a WordPressKit PR that hasn't been reviewed yet: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/499

**Comment by mokagio** [comment]
@frosty gosh... sorry about it and the issue it might have caused.

I see that while I was offline @ScoutHarris addressed the problem on `trunk` and I since shipped a new WordPressKit stable version and [updated the release branch to use it](https://github.com/wordpress-mobile/WordPress-iOS/pull/18486/commits/4a4126a1f1ad2df889a34539983327779909a5f2).

See also pbArwn-4yw-p2

**Pull request merged**
