### PR TITLE
Privacy: Add explanation to Remove Location from Media feature

### LINKED ISSUE #10407: Privacy: Add explanation to Remove Location from Media feature
For more context see p77Llu-bgA-p2

The purpose of the Remove Location from Media feature might not be obvious.  Let's add some clarifying descriptive text to clarify that it removes location exif data from any  uploaded images.   Exact wording tbd.
simulator screen shot - iphone 8 - 2018-11-06 at 11 45 15

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #10407 

To test:
- Go to Me > App Settings > Privacy section.
- Verify `Remove Location from Media` is at the bottom of the section.
- Verify the footer text is:
`Removes location metadata from photos before uploading them to your site.`

remove_location

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@iamthomasbishop - this look ok to you?

**Comment by iamthomasbishop** [comment]
I think something along the lines of this might read clearer: 

"Removes location metadata from photos before uploading them to your site."

We might want to get a editorial copy review here to get their opinion.

One more thing I noticed: it feels a little odd having centered buttons between table cells. // cc @sylvesterwilmott because he mentioned he might have worked on a design for this recently

**Comment by ScoutHarris** [comment]
Thanks @iamthomasbishop . I updated the text and screenshot with your suggested text so editorial can see the latest.

**Comment by michelleweber** [comment]
Looks good!

**Comment by ScoutHarris** [comment]
Thanks @michelleweber !

**Comment by ScoutHarris** [comment]
> One more thing I noticed: it feels a little odd having centered buttons between table cells. // cc @SylvesterWilmott because he mentioned he might have worked on a design for this recently

@iamthomasbishop , @SylvesterWilmott - I'm going to go ahead and merge this. We can re-think the table layout separately if we like.

**Pull request merged**
