### PR TITLE
[Dark Mode]Fix/stats insights white space

### PR DESCRIPTION
**Pull request by danielebogo**
Refs. #12320 

This PR fixes some white background in Stats, mostly in Insights Overview and some detail.

stats-dark-mode-01
stats-dark-mode-02

## To test:
- Run the App with Xcode 11 and iOS 13 with Dark Mode enabled
- Select a site with data like `en.blog` site
- Open Stats -> Insights and scroll the whole overview to check if there are still white backgrounds
- Click on View More from the Insights Posting Activities section and check the detail
- From the LPS (or select a post in the Post and Pages section in DWMY) select view more and check the detail.

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by frosty** [comment]
Actually, one thing I did just notice – I think the placeholder posting activity color might be a little dark in light mode and iOS 12 now. It's a bit difficult to distinguish from the lightest blue:

post-activity

**Comment by danielebogo** [comment]
@frosty I made the range 1 color (Posting activity) lighter

Screenshot 2019-08-30 at 09 13 52

**Comment by frosty** [comment]
Looks good in light mode, but annoyingly I think this shade is too dark in dark mode 🙃 

How about let's do this?

```
UIColor(light: .neutral(.shade5), dark: .neutral(.shade10))
```

**Comment by danielebogo** [comment]
Thanks @frosty @nheagy

**Pull request merged**
