### PR TITLE
Replace ios.wordpress.org with apps.wordpress.com/mobile in metadata

### PR DESCRIPTION
**Pull request by jkmassel**
Fixes App Store Connect warnings when uploading the binary

### CODE REVIEW

**Comment by loremattei** [comment]
Hey @jkmassel, are we actually using this file during uploads? It seems its content is older than what we have on ITC. Like, some URLs are already updated on ITC, but aren't here. Also, the description fields seem outdated in this file. 

I agree with using this file to update the fields on ITC, but I think we want to download the latest version.

**Comment by loremattei** [comment]
I think it's the standard Fastlane one. `ios_update_metadata` pulls the data from GlotPress, but I think we need to pull it from ITC for this file.
I'd try `bundle exec fastlane deliver download_metadata` (probably you want to change the `app_version` in the `DeliverFile` to the latest valid one (11.3 at this time).

**Comment by jkmassel** [comment]
Heh, so this file is a total red herring. It's not updated by that, and in a complete search through the source code, it's not referenced once. 

I'm deleting the file so it doesn't confuse anyone else, and I think that's all we can do in this PR 🙃

**Comment by jkmassel** [comment]
Ok – so I've added a step to the `download_metadata.swift` file to create another `.txt` file for the marketing URL, which `deliver` _should_ pick up and upload as part the rest of the metadata upload (it shows up in the preview `.html` file, but I don't want to _actually_ send these to the App Store).

**Comment by loremattei** [comment]
@jkmassel you're right! These files should be the right way to do the update using Fastlane these days.
A couple of thoughts:
1. I'm wondering why we're adding the generation to `download_metadata.swift`. We aren't really downloading anything, so it looks a bit hack-ish. Also, we probably want to add the files to the repo for consistency, as we have everything we upload but the screenshots in it.
2. Could you target the release/11.4 branch, so that we'll fully test it out when we create the next release?

**Comment by jkmassel** [comment]
>I'm wondering why we're adding the generation to download_metadata.swift

I figured for the next person trying to figure out how this file is created, it'd make sense to have it with the script that creates all of the other files in the same directories. It _is_ a little out-of-place because it doesn't download anything, but it keeps it all together 😅 

>Also, we probably want to add the files to the repo for consistency, as we have everything we upload but the screenshots in it.

For sure – just committed those. When I ran the scripts, the following languages have a marketing URL, but no other metadata: 

- da
- no
- pt-PT
- th

WDYT about commenting those out in the `languages` dictionary for now, until we have full translation support?

>Could you target the release/11.4 branch, so that we'll fully test it out when we create the next release?

Done!

**Comment by loremattei** [comment]
> I figured for the next person trying to figure out how this file is created, it'd make sense to have it with the script that creates all of the other files in the same directories. It is a little out-of-place because it doesn't download anything, but it keeps it everything together nicely 😅

I see. Though I don't like it too much because, as you note, it doesn't actually download the value for that key... I'd rather go with a separate script or at least add a comment in `download_metadata` to make it clear that it's a bit of a hack. Wdyt?

> WDYT about commenting those out in the languages dictionary for now, until we have full translation support?

The languages are on GlotPress and a couple of them have some translations for other keys. I'd like to keep them in the script so that we will get the translations as soon as someone adds them on GlotPress. 

> Could you target the release/11.4 branch, so that we'll fully test it out when we create the next release?
Done!

Mmm... I see you changed the milestone, but it looks like the target branch is still `develop`...

**Comment by jtreanor** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR has more than 500 lines of code changing. Consider splitting into smaller PRs if possible.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Podfile: reference to a commit hash</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jkmassel** [comment]
>I see. Though I don't like it too much because, as you note, it doesn't actually download the value for that key... I'd rather go with a separate script or at least add a comment in download_metadata to make it clear that it's a bit of a hack. Wdyt?

I added in the comment – that totally makes sense. I considered making a separate file, but I'd need to bring over the languages dictionary to do that, and I feel like having two copies of that floating around could cause a bit more overhead (we'd have to remember to update both if we ever make changes).

One further change I could make to clarify the separation is extract the marketing URL file creation into a separate method?  That way it's distinct from the `downloadTranslation` method? It doesn't nicely colocate the file writing calls, but may help with the logical separation you're hoping to see?

>The languages are on GlotPress and a couple of them have some translations for other keys. I'd like to keep them in the script so that we will get the translations as soon as someone adds them on GlotPress.

Sounds good! I've added a check for whether there's other metadata present. That way, as soon as those translations show up, the marketing URL will automatically be present, but it won't be the _only_ piece of metadata present. 

>Mmm... I see you changed the milestone, but it looks like the target branch is still develop...

Derp. I shouldn't do PRs until the coffee kicks in. Fixed _for real_ this time.

**Comment by loremattei** [comment]
@jkmassel thank you!
The PR itself looks good to me now! 
But I think there's something off with the change in the target branch as I see too many files to be added to `release/11.4`.
If it's difficult to move it, let's merge it to `develop` and I'll cherry pick the commits from there.

**Comment by jkmassel** [comment]
>I think there's something off with the change in the target branch as I see too many files to be added to release/11.4.

I've fixed this up so it only contains the commits we actually want to consider!

**Pull request merged**
