### PR TITLE
Issue/4756 Reorganizes appearance of geotagging and post defaults.

### PR DESCRIPTION
**Pull request by kurzee**
As discussed in https://github.com/wordpress-mobile/WordPress-iOS/pull/4757, the best approach for resolving our feature confusion with default post options is to disable toggling the options for non-admin or XML-RPC users in Site Settings.

This PR changes the Site Settings to only show the default post options for admin REST API users. This also moves the Geotagging option within a new section titled "This Device", which is available for all users.

This brings parity with the Calypso web handling of default post options, in which the options are only available sites connected as admin users.

The only concern I could see with this change is potential confusion with any users who might have already changed their default post options in-app as non-admin REST or XML-RPC users. An upcoming update including this change would disallow them from changing their default options again, in-app. The only way for the user to update their previously made changes in-app would be to re-connect their site or account, restoring the site defaults.

REST Testing:
1. Open Site Settings for a site connected via the REST-API and as an admin user.
2. Observe the available default category, post format and related posts options.
3. Observe the available Geotagging option under "This Device".

REST Testing:
1. Open Site Settings for a site connected via the REST-API and as a non-admin user.
2. Observe no availability for the default category, post format and related posts options.
3. Observe the available Geotagging option under "This Device".

XML-RPC Testing:
1. Open Site Settings for a site connected via the XML-RPC.
2. Observe no availability for the default category, post format and related posts options.
3. Observe the available Geotagging option under "This Device".

@aerych please review. Also, @mattmiklic please review the text changes.

### CODE REVIEW

**Comment by kurzee** [comment]
simulator screen shot feb 3 2016 3 16 44 pm

**Comment by mattmiklic** [comment]
Tested all three states and design looks good.

I noticed for a REST blog, admin user, the "This Device" section is above writing. Can we move that so that it always appears at the bottom of the list of settings (but still above the "remove site" button if xml-rpc)?

**Comment by aerych** [comment]
> Can we move that so that it always appears at the bottom of the list

I was going to ask the same thing ;)

**Comment by aerych** [comment]
> The only concern I could see with this change is potential confusion with any users who might have already changed their default post options in-app as non-admin REST or XML-RPC users. An upcoming update including this change would disallow them from changing their default options again, in-app. The only way for the user to update their previously made changes in-app would be to re-connect their site or account, restoring the site defaults.

Ouch. 
In that case, should the defaults be cleared if the user does not have a REST connection? I'm not sure. Being stuck with one they previously chose vs using what the app would normally default to otherwise doesn't seem like too much of a difference to me, but I do share the concern.

**Comment by kurzee** [comment]
Added commit to move "This Device" to below all options except "Advanced" and "Delete Site" options. I think it should still be above the Advanced section as it is more in-context with the items above it.

simulator screen shot feb 3 2016 4 28 25 pm

**Comment by kurzee** [comment]
> In that case, should the defaults be cleared if the user does not have a REST connection?

I would then worry that the maintenance method for clearing that up would be a bit messy.

**Comment by mattmiklic** [comment]
> I think it should still be above the Advanced section as it is more in-context with the items above it.

Makes sense; delete site is similar to remove site for self-hosted, makes sense to keep that at the very bottom.

**Comment by aerych** [comment]
> I would then worry that the maintenance method for clearing that up would be a bit messy.

Fair enough.  We should probably give a heads up to our friendly HEs that this is a potential question. cc @rachelmcr

**Comment by kurzee** [comment]
Pushed a commit that changes the behavior of using the currently set default post category and format to instead relying on the remote setting, or using app defaults as expected.

**Comment by rachelmcr** [comment]
Thanks for the heads up! It looks like this is no longer an issue, with the new approach in #4767, so I'll just keep an eye on those changes during beta testing.

**Comment by aerych** [comment]
Thanks @rachelmcr :)

**Pull request closed without merging**
