### PR TITLE
Issue/4707 widget layout

### LINKED ISSUE #4707: Today widget needs additional layout fine-tuning
Before PR #4686 was merged there were some issues discovered with the alignment and top/bottom spacing of the widget. Spend some time and see if that layout glitchiness can be fixed. For details regarding the glitches, review the mentioned PR.

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #4707 

Warning: Stackviews on stackviews on stackviews

To test:

See both the widget configured and not configured modes. Also, verify that the widget scales correctly when changing the system text size (Settings > Display & Brightness > Text Size)

img_0605
img_0606

Needs review: @astralbodies

### CODE REVIEW

**Comment by kwonye** [comment]
Also changed the font color to be black to match widget styling on iOS 10

**Comment by astralbodies** [comment]
OMG THANK YOU

I had UIStackViews originally but they were WONKY AS HECK.

**Comment by astralbodies** [comment]
I'm getting this compilation error for some reason -

**Comment by astralbodies** [comment]
Nevermind I bet it's my toolchain with Rake.

**Comment by astralbodies** [comment]
The background effect in iOS 9 is incorrect; and dismissing and bringing back the notification center causes some wonky alignment.
simulator screen shot oct 20 2016 8 57 06 pm

simulator screen shot oct 20 2016 8 57 12 pm

**Comment by kwonye** [comment]
Ok, disabling the widget for iOS 9. (I wish)

Thanks for testing iOS 9! Totally my fault for forgetting about that, sorry. I'll let you know when it's all good on iOS 9 as well.

**Comment by astralbodies** [comment]
@kwonye Those layout issues in iOS 9 look very familiar to the issues why I ripped out UIStackView. If you can fix them I owe you a basket of tots.

**Comment by astralbodies** [comment]
@kwonye Is this ready for review now?

**Comment by kwonye** [comment]
@astralbodies not quite yet, sorry! Only thing left is figuring out iOS 9's layout issues and we're there! I'm actually going to close this and open another PR against `6.7` as we missed the cutoff date and the white text is a decent bug for most.

**Pull request closed without merging**
