### PR TITLE
Remove unused `release_management_in_ci.rb` lanes

### PR DESCRIPTION
**Pull request by mokagio**
We no longer need repo-level automation to trigger release lanes. We
have a dedicated internal app to do so. Keeping the lanes here would be
more of a liability in terms of code that never gets used and is bound
to become out-of-date.

In the rare occasion where one might need to trigger those builds
manually, it can be done via the Buildkite GUI or API directly.

To verify they are unused I run `git grep -e 'trigger_.*_in_ci'`, which
returned only the lane declarations. Of course, this does not guarantee
there are no references outside of the repo, but based on my
understanding of our Automation I think it's safe to assume there are
none. (But just to be sure, I grepped our backend codebase for `_in_ci`,
and got no results.)

See also conversation at
https://github.com/Automattic/simplenote-ios/pull/1655#discussion_r1753900531

## Regression Notes

1. Potential unintended areas of impact – N.A.
2. What I did to test those areas of impact (or what existing automated tests I relied on) – N.A.
3. What automated tests I added (or what prevented me from doing so) – N.A.

---

**PR submission checklist:**

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes. **N.A.**
- [x] I have considered adding accessibility improvements for my changes. **N.A.**
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary. **N.A.**

**UI changes testing checklist:** Not a UI PR.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by iangmaia** [comment]
@mokagio note that we'd also need to update the WPiOS Rv2 scenarios together with this.
There's specific reference to these lanes and suggestions to run them again if something doesn't work.

I've also jinxed this update on [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/23585) yesterday, I should've mentioned it here 😓 .
I'm fine keeping this change only in this PR to make things more focused, though we have to remember to do the Rv2 changes together with it as well.

**Comment by iangmaia** [comment]
For the record: I've disabled auto-merge as we don't want to merge this without the required Rv2 changes.

**Comment by iangmaia** [comment]
@mokagio update: I've created an [Android counterpart](https://github.com/wordpress-mobile/WordPress-Android/pull/21228) of this PR and the diff D161466-code with the corresponding changes for both iOS and Android.

**Review by spencertransier — APPROVED** [review]
Looks great 👍

**Comment by mokagio** [comment]
Thanks @iangmaia for wrangling the dependency tree and for the Android counterpart. I should have thought of that, but I clearly have an iOS bias 😳

**Comment by iangmaia** [comment]
@mokagio
> but I clearly have an iOS bias 😳

It happened with me before, so I guess we all do to either platform 😅 
FYI, I've landed D161466-code.

**Pull request merged**
