### PR TITLE
Domains Dashboard Card: Shorten the flow by immediately showing domain list

### PR DESCRIPTION
**Pull request by staskus**
## Description

pc8eDl-NP-p2#comment-703

For Domains Dashboard Card, shortened the flow on iOS to immediately open the domain selection list and not the domains dashboard. The same shortened flow is developed for Android

### Domains Dashboard Card flow (iPhone / iPad)
1. Open the Jetpack app
2. Log into the account with free WP.com account that doesn't have domains
3. Click a dashboard card
4. Domain list should open
5. Back action should exist and work
6. Selecting a domain from the list and selecting "select domain" should open a web view
7. After the purchase is done, the success view should be shown and the flow should return to the dashboard

### Menu -> Domains flow (iPhone / iPad)
1. Open the Jetpack app
2. Log into the account with free WP.com account that doesn't have domains
3. Go to Menu
4. Select Domains
5. Domains dashboard should open
6. Click "Select a domain"
7. "Cancel" action should be visible and work
8. Selecting a domain from the list and selecting "search domain" should open a web view
9. After the purchase is done, success view should be shown and the flow should return to the domains dashboard

## Regression Notes
1. Potential unintended areas of impact

Breaking the current domain purchasing flow

10. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing and existing automated tests

11. What automated tests I added (or what prevented me from doing so)

Updated Dashboard tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] iPhone and iPad. 
- [x] Multi-tasking: Split view and Slide over. (iPad)

## Images & Photos

https://user-images.githubusercontent.com/4062343/236333391-3ecb8343-e840-4e83-98cf-373d25d24e73.mov

https://user-images.githubusercontent.com/4062343/236333446-786d1073-a2b8-41ca-b981-4d2f59e1c151.mp4

### CODE REVIEW

**Review by pachlava — COMMENTED** [review]
Thanks for adding a new ScreenObject for this screen and updating the UI test @staskus ⭐ 

I reviewed only the UI-tests related code, and it looks good. Also, works with no issues on CI and locally 👍.

I'm not giving an explicit approval, only because I think the rest of the code should be reviewed by a developer.

P.S. I know this is out of scope, but does it make sense to do the same for `Menu` ~> `Domains` flow 🤔

**Comment by staskus** [comment]
> P.S. I know this is out of scope, but does it make sense to do the same for Menu ~> Domains flow

@pachlava 

Since all the infrastructure seemed to be already there, I wanted to try adding such a test. [And yes, it's straightforward.](https://github.com/wordpress-mobile/WordPress-iOS/pull/20638/commits/3ba3df942bddf8e5976aea5b2471fa40093bdc1e) Now the tests confirm that clicking a card opens a domain suggestion list, and going through menu opens a domain dashboard. 

My only question is about the test structure. I created new `MenuNavigationTests` but I'm thinking about whether I should put both domain-related tests to `DomainsTests`. What do you think?

### Here's the test
https://user-images.githubusercontent.com/4062343/236448439-8817d3e7-0eec-4c25-8ac0-7731dd8e391d.mov

**Comment by pachlava** [comment]
> P.S. I know this is out of scope, but does it make sense to do the same for Menu ~> Domains flow 🤔

Oh, I'm so sorry. My wording was poor. By `do the same` I meant not adding another test, but making the tap on Menu ~> Domains open the domains list too 🤦. Not in this PR, but just consider if this makes sense. I'm sorry for misunderstanding, and making you spend your time on adding another test.

**Comment by staskus** [comment]
> ...but making the tap on Menu ~> Domains open the domains list too 

@pachlava, for now probably no, since the domains dashboard is not only for selling domains but also showing the domains that the user owns. Since we show the domain card only to users that don't have any other domains, it doesn't make sense to show the domains dashboard and we can immediately open a domains search.

**Comment by staskus** [comment]
@pachlava 

> I meant not adding another test

That's fine, it took me 10 minutes and it's good to learn about the app's UI tests infrastructure. Let me know if it's better to remove the test.

**Comment by pachlava** [comment]
Since the test is already there, let's keep it, @staskus. 🙇 But I'm still very sorry for the mix-up I introduced by my ambiguous message.

> My only question is about the test structure. I created new MenuNavigationTests but I'm thinking about whether I should put both domain-related tests to DomainsTests. What do you think?

I think keeping it as is a good option. New tests for other cards might then be added to `DashboardTests`, and potential tests for menu navigation will go to `MenuNavigationTests` that you've added.

**Review by guarani — APPROVED** [review]
Changes look great! I verified that the app now takes me to the domain search screen after I tap on the dashboard card. After completing this flow, the dismissing the screen correctly takes me back to the dashboard card where I started. 

I checked the flow from My Site > Menu > Domains and verified that it takes me to the domain dashboard (where I can see any other domains I might have). After purchasing a domain this flow takes me back to the same domain dashboard where I see the new domain listed 👍

**Pull request merged**
