### PR TITLE
Fix an issue with WordPress → Jetpack migration not working for new accounts with no sites

### LINKED ISSUE #21959: Bug: Not logged in after downloading the Jetpack App via the WP app.
### Expected behavior
When I don't have the Jetpack app installed and am asked by the WordPress app to create a new site in the Jetpack app. 
After I install the app I would expect us to be logged in to the Jetpack App. 

### Actual behavior
When I don't have the Jetpack app installed and am asked by the WordPress app to create a new site in the Jetpack app. 
After I install the app I need to go though the login process in to the Jetpack App. To complete the site creation process. 

### Steps to reproduce the behavior
Download the WP App. 
Create a new user account. 
Try to Create a new Site. 
Download the Jetpack app. 
Launch the Jetpack App. 
Notice that you are not logged in. 

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
Latest.

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/21959 and shortens the ~~darkness~~ migration flow for the new users with no sites.

To test:

(Can be fully tested in a simulator)

**Scenario 1**

Recording: https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/77affad8-74ce-46c3-be2d-620f0ac8befb 

1. Install the WordPress app and create a new account (don’t create any sites!) or log in using an account with no sites
2. Tap “Create a new site” and when presented with the “Welcome to WordPress” screen
3. A “Give WordPress a boost with Jetpack” screen appears
4. Tap “Switch to the Jetpack app”
5. Install the Jetpack app (from Xcode or a one-off build)
6. Verify that it shows the “Migration Done” confirmation screen 
7. Tap “Finish”
8. Verify that you land on the home page with a “Create Site” CTA
9. Verify that you are logged in and can create a site now
10. Verify that you got no “Migration Done” emails from WordPress (we don’t want to spam you, assuming you _just_ created an account anyway)

**Scenario 2**

Recording: https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/4b2d22bc-8fd0-4db0-b7af-09a9cf3d2c69

1. Install the WordPress app and create a new account (don’t create any sites!) or log in using an account with no sites
2. Tap “Skip” and when presented with the “Welcome to WordPress” screen. Don't accept any prompts to install Jetpack
3. Install the Jetpack app (from Xcode or a one-off build)
4. Verify that it prompts you to migrate your account from the WordPress app
5. Tap "Open WordPress"
6. Verify that the systems briefly opens the WordPress app and returns you to the Jetpack app
7. Verify that it shows the “Migration Done” confirmation screen 
8. Tap “Finish”
9. Verify that you land on the home page with a “Create Site” CTA
10. Verify that you are logged in and can create a site now
11. Verify that you got no “Migration Done” emails from WordPress (we don’t want to spam you, assuming you _just_ created an account anyway)

## Regression Notes
1. Potential unintended areas of impact: Migration to Jetpack
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual
3. What automated tests I added (or what prevented me from doing so): n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by kean** [comment]
cc @twstokes, @enejb, @zwarm

**Review by momo-ozawa — APPROVED** [review]
🚀

**Comment by kean** [comment]
I updated the "Done" screen according to the latest suggestions from Chris and added analytics.
I re-tested it, but it might need a second pair of eyes, @momo-ozawa .

**Review by momo-ozawa — APPROVED** [review]
Re-tested - LGTM!

**Pull request merged**
