### PR TITLE
Fixing TableView Footer Inconsistencies

### LINKED ISSUE #3989: WPTableViewSectionFooterView Inconsistencies
#### Steps:
1. Launch WPiOS
2. Log into your account
3. Tap over `Me` > `Help & Support`
4. Note that there are two Section Footers, and the heights are inconsistent
5. Tap over `Activity Logs`
6. Note that there is another Section Footer, with yet a different height

I've noticed this while working on a new feature. **WPTableViewSectionFooterView**'s style [has been updated here](https://github.com/wordpress-mobile/WordPress-Shared-iOS/pull/68).

Let's update the Shared Pod, and fix any issues in **SupportViewController** and **ActivityLogViewController**, as required.

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Steps:
1. Launch WPiOS
2. Log into your account
3. Tap over `Me` > `Help & Support`
4. Verify that the Footers look okay (iPhone + iPad)
5. Tap over `Activity Logs`
6. Verify that the Footers look okay (iPhone + iPad)

Plus: The extra top padding that was being displayed in the `Help + Support` view has been removed.

Fixes #3989. Props to @drw158 for helping me out with the new metrics. Thanks Dave!

Needs Review: @diegoreymendez (Thanks in advance!)

--

#### Screenshot: SupportViewController @iPhone

  ios simulator screen shot jul 7 2015 6 17 02 pm
<br/><br/><br/><br/>

-- 

#### Screenshot: ActivityLogsViewController @iPhone

  ios simulator screen shot jul 8 2015 10 46 25 am
<br/><br/><br/><br/>
--

#### Screenshot: SupportViewController @iPad

  ios simulator screen shot jul 8 2015 10 51 10 am
<br/><br/><br/><br/>
--

#### Screenshot: ActivityLogsViewController @iPad

  ios simulator screen shot jul 8 2015 10 45 27 am
<br/><br/><br/><br/>

### CODE REVIEW

**Comment by drw158** [comment]
In your first iPad screenshot: it looks like the footer text (Visit the Help...) has a bigger top margin then the rest.

**Comment by jleandroperez** [comment]
@drw158 Nice catch Dave! will get that fixed soon, just spotted the bug, it's a height calculation glitch actually. Margins are constants all over.

**Comment by jleandroperez** [comment]
Update: Invalid height calculation [fixed here](https://github.com/wordpress-mobile/WordPress-Shared-iOS/pull/69)

**Comment by jleandroperez** [comment]
### Update:

Shared Pod bumped up, with the invalid height calculation fix. PR **Ready for review**. Sample screenshot below!

ios simulator screen shot jul 10 2015 2 00 50 pm

**Comment by diegoreymendez** [comment]
:shipit: Works great on all iOS versions I tested and all devices.

**Comment by jleandroperez** [comment]
Thank you @diegoreymendez !!

**Pull request merged**
