### PR TITLE
[Gutenberg] Expose display preview function to Gutenberg

### PR DESCRIPTION
**Pull request by fluiddot**
`gutenberg` PR: https://github.com/WordPress/gutenberg/pull/33266
`gutenberg-mobile` PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3710
`WordPress-Android` PR: https://github.com/wordpress-mobile/WordPress-Android/pull/15001

**NOTE:** The PR includes the changes from https://github.com/wordpress-mobile/WordPress-iOS/pull/16818.

## Regression Notes
1. Potential unintended areas of impact
Initially none as this PR only introduces a new function in the Gutenberg bridge.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ceyhun — APPROVED** [review]
LGTM! Changed the base branch to `gutenberg/after_1.57.0` for now as there is a Gutenberg Mobile release going on and main apps still didn't cut their next releases.

**Comment by ceyhun** [comment]
Main apps have cut their releases, reverting the base branch back to `develop`.

**Comment by fluiddot** [comment]
I'm trying to solve the conflicts but using the new tag `v1.58.0-alpha1 ` makes the Gutenberg and RNTAztecView references downgrade to `1.56.0` in the `Podfile.lock` file. Looks like that until [this PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3718) gets merged into GB-mobile I can't really solve them.

**Comment by fluiddot** [comment]
> I'm trying to solve the conflicts but using the new tag `v1.58.0-alpha1 ` makes the Gutenberg and RNTAztecView references downgrade to `1.56.0` in the `Podfile.lock` file. Looks like that until [this PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3718) gets merged into GB-mobile I can't really solve them.

Solved 🎊 !

**Pull request merged**
