### PR TITLE
Adjust i18n issues for Page Design and Site Design flows

### PR DESCRIPTION
**Pull request by chipsnyder**
## Description

**Related PR:** https://github.com/wordpress-mobile/WordPressKit-iOS/pull/393

In #15231 we added `language` as a parameter to the site-design endpoint based on the current server-side specifications. That has been carried over with our other changes to this endpoint. 

This PR does three things:
1. Updates the site design flow to use the v2 locale key `_locale`
2. Updates the page design flows to use the v2 locale key `_locale`
3. Corrects an issue on the Site Design Preview screen where the `Choose` button wasn't translated.

## To test:

> Updates the site design flow to use the v2 locale key `_locale`

This is easiest to test with a Proxy tool like [Charles Proxy ](https://www.charlesproxy.com/) since the backend has made the necessary changes to support our live apps.

1. Set up your proxy service of choice
2. Set your device language to be something other than English. I tested with US Spanish (slug = `es`)
3. Navigate to site design screen in site creation
4. Expect to see a request similar to:
`https://public-api.wordpress.com/wpcom/v2/common-starter-site-designs?_locale=es&....{{remaining_request_parameters}}... `
    - Notice: `_locale=es` where the `_locale` key should be populated with your selected language's slug.
    - Notice: `language` and `locale` should not be present

> Updates the page design flows to use the v2 locale key `_locale`

This is easiest to test with a Proxy tool like [Charles Proxy ](https://www.charlesproxy.com/) since the backend has made the necessary changes to support our live apps.

1. Set up your proxy service of choice
2. Set your device language to be something other than English. I tested with US Spanish (slug = `es`)
3. Navigate to page design screen in the page creation flow for a dotCom site.
4. Expect to see a request similar to:
`https://public-api.wordpress.com/wpcom/v2/sites/176997822/block-layouts?_locale=es&....{{remaining_request_parameters}}...`
    - Notice: `_locale=es` where the `_locale` key should be populated with your selected language's slug.
 5. Regeat for a Self-hosted site
     - 📓 The request will now be made to `https://public-api.wordpress.com/wpcom/v2/common-block-layouts?_locale=es`

> Corrects an issue on the Site Design Preview screen where the `Choose` button wasn't translated.

1. Set your device language to be something other than English. I tested with US Spanish
2. Navigate to site design screen in site creation
3. Select a Design
4. Select the Preview Button (LHS)
5. Expect the `Choose` Button to be Translated

 
## Regression Notes
1. Potential unintended areas of impact
None outside of the changes mentioned here.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

## PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by enejb** [comment]
Thanks for getting this started @chipsnyder.

What do you think about doing something similar to Android and make the default be `_locale` when the v2 path matches
instead of updating all the API calls that make sure that the correct locale key is being used?

See https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/5f2fb2f652ec711d17c5b7392c54491b1259f370/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/BaseWPComRestClient.java#L137-L139

**Comment by chipsnyder** [comment]
> What do you think about doing something similar to Android and make the default be _locale when the v2 path matches
instead of updating all the API calls that make sure that the correct locale key is being used?

That seems like a good idea but I would prefer to address that in a different PR as making that change holistically would touch a lot of code. This change was approached by choosing to align with the existing architecture.

**Comment by enejb** [comment]
Sounds like a plan. Will review this PR shortly.

**Comment by enejb** [comment]
I just tested this and it worked as expected for me. 
The API calls were being made with `_locale=` query parameter instead of `locale` and they also didn't include `language`

Thanks for these fixes!

**Review by enejb — APPROVED** [review]
This testes as expected for me!

**Pull request merged**
