### PR TITLE
Integrate gutenberg-mobile release v1.111.1

### PR DESCRIPTION
**Pull request by SiobhyB**
## Description
This PR incorporates the 1.111.1 release of gutenberg-mobile.
For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/6567

Release Submission Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/267">24.1 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by fluiddot** [comment]
@SiobhyB I noticed that this PR points to `trunk`. Since it's a beta fix, we should point it instead to [`release/24.1`](https://github.com/wordpress-mobile/WordPress-iOS/tree/release/24.1). This change will imply generating new installable builds and maybe testing again the editor (https://github.com/wordpress-mobile/gutenberg-mobile/pull/6567#issuecomment-1906227665), although I presume there won't be any significant difference as (AFAIK) we haven't pushed any change in the host apps.

**Comment by SiobhyB** [comment]
@fluiddot, thank you for spotting! The branch was created off `release/24.1`, but I forgot to update the PR to reflect that when I created it. I've updated the PR now.

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

**Pull request merged**
