### PR TITLE
Upgrade to support Xcode 14.0

### PR DESCRIPTION
**Pull request by mokagio**
Note: While I am listed as the PR author, @crazytonyli did all the heavy lifting to get the app building and up-to-date through all the betas! —@mokagio

---

This is going to be a long running branch to (try to) stay on top of the Xcode 14 betas PRs.

I expected many of you will want to checkout this branch locally to play with it. As such, I think we should keep it alive by merging trunk into it. But, I think once we'll officially switch to Xcode 14 stable, it'll make sense to do a big rebase so the history stays tidy.

I called the branch `xcode-14-support`. This might give us the option to keep the beta branch stable (🙃 🙂) and work on a new beta support without breaking the "stable" branch. That is, we might have an xcode-14-beta-2 branch in the future.

Ideally, we should implement as many fixes for errors and warnings found here as possible on trunk.

## Related PRs

- #18834 

## Testing

Download Xcode 14 beta 1 and run this branch 😅 .

## Regression Notes

1. Potential unintended areas of impact – N.A.
2. What I did to test those areas of impact (or what existing automated tests I relied on) – N.A.
3. What automated tests I added (or what prevented me from doing so) – N.A.

---

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes. **N.A.**
- [x] I have considered adding accessibility improvements for my changes. **N.A.**
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary. **N.A.**

### CODE REVIEW

**Comment by crazytonyli** [comment]
Hi @mokagio , do you think this PR is ready for review now?

**Comment by mokagio** [comment]
> Hi @mokagio , do you think this PR is ready for review now?

Yes. Clicking the button and getting in touch with the iOS devs.

**Review by pachlava — APPROVED** [review]
@mokagio / @crazytonyli 👋 

I've updated to Xcode 14 - and can see that the app can be built, and UI tests for iPhone and iPad are executed (`testViewPostInSafari` failed for me on iPhone, but it passes on CI - so I'm good with it).

Also, I know that elements locators that have `.sheets` removed will still work for Xcode 13.4.1 - so there should be no issues with running tests locally on earlier Xcode.

I'm curious why `iPhone SE` was selected, but not `iPhone 14`? (I'll measure the execution time differences locally for them - but it's not a blocker, it can be changed in separate).

Thank you 👍

**Comment by twstokes** [comment]
👋 Just wanted to chime in that I also tested this in Xcode 14 and didn't spot any major issues compiling WPiOS, JPiOS, and tests. Thanks for the great work! 🙇

**Comment by crazytonyli** [comment]
Thanks for testing @pachlava @twstokes 

@pachlava about your question
> I'm curious why iPhone SE was selected, but not iPhone 14? (I'll measure the execution time differences locally for them - but it's not a blocker, it can be changed in separate).

🤔 I forgot why I didn't pick a newer model, which seems a saner things to do. But I don't think there is any performance impact in choosing different model. To my knowledge, the difference would only be the device frame, like screen size, resolution, notch or notch-less, etc.

**Comment by pachlava** [comment]
> I don't think there is any performance impact in choosing different model.

Actually, there is a small difference. For several runs on `SE` the average time was 15:58. For `iPhone 14` it was 16:26. So there's a half minute difference between them. I don't know why, though.

We had a project, and a part of it was checking if there's an impact of the selected device on execution speed - and it turns out that `SE` was the fastest: pdcxQM-RL-p2#comment-788. I forgot about that. So let's keep using `SE` 👍

**Pull request merged**
