### PR TITLE
Integrate gutenberg-mobile release 1.58.1

### PR DESCRIPTION
**Pull request by fluiddot**
## Description
This PR incorporates the 1.58.1release of gutenberg-mobile.
For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3769

Release Submission Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mokagio** [comment]
@fluiddot, just to double check, this PR is against the 17.9 release branch because it brings a mobile Gutenberg patch update which includes [this fix](https://github.com/WordPress/gutenberg/pull/33707) for [this crash](https://github.com/wordpress-mobile/WordPress-iOS/issues/16942) introduced in 17.9. Right?

**Comment by fluiddot** [comment]
> @fluiddot, just to double check, this PR is against the 17.9 release branch because it brings a mobile Gutenberg patch update which includes [this fix](https://github.com/WordPress/gutenberg/pull/33707) for [this crash](https://github.com/wordpress-mobile/WordPress-iOS/issues/16942) introduced in 17.9. Right?

Exactly, this PR brings a Gutenberg patch that includes a fix for that crash, as well as [these changes](https://github.com/WordPress/gutenberg/pull/33745).

**Review by SiobhyB — APPROVED** [review]
Looks good to me, following test results at https://github.com/wordpress-mobile/gutenberg-mobile/pull/3769.

**Comment by mokagio** [comment]
@fluiddot  this has been bundled as part of [17.9 beta 2 (17.9.0.2)](https://github.com/wordpress-mobile/WordPress-iOS/pull/16959).

Thanks for your work 🙌

**Pull request merged**
