### PR TITLE
Jetpack Migration Flow: Address rare blogging reminder crashes during the migration flow

### LINKED ISSUE #19864: Jetpack Migration Flow: An app can crash when setting reminders during the migration flow due to memory issues
### Description

An app can occasionally crash when setting reminders during the migration flow due to memory issues. So far it would only happen in some scenarios when getting calls and allowing notifications at the same time. Due to rarity of the issue and unclear stack trace keeping the issue with lower priority.

Sentry Issue: [JETPACK-IOS-CN](https://sentry.io/organizations/a8c/issues/3853218512/?referrer=github_integration)

```
EXC_BAD_ACCESS: Exception 1, Code 16, Subcode 8 >
Attempted to dereference garbage pointer 0x8000000000000010.
  File "<compiler-generated>", in Dictionary.subscript.getter
  File "BloggingRemindersStore.swift", line 87, in BloggingRemindersStore.scheduledReminders
  File "BloggingRemindersScheduler.swift", line 417, in BloggingRemindersScheduler.scheduledReminders
  File "BloggingRemindersStore.swift", line 87, in BloggingRemindersStore.scheduledReminders
  File "BloggingRemindersScheduler.swift", line 417, in BloggingRemindersScheduler.scheduledReminders
...
(20 additional frame(s) were not displayed)
```

### Steps to reproduce

1. Starting the Jetpack migration flow
2. Tapping “Continue” on the notifications screen to bring the notifications permissions notice up
3. Initiating the FaceTime audio call from other device
4. Attempting to answer that call by tapping the green button, then attempting to dismiss by tapping the red button (no response to either!)
5. After tapping both call buttons a few time, tap “Accept” on the notifications permissions notice

### PR DESCRIPTION
**Pull request by staskus**
Fixes: #19864

## Description

An app can occasionally crash when setting reminders during the migration flow due to memory issues. So far it would only happen in some scenarios when getting calls and allowing notifications at the same time.

### Solution

I wasn't able to reproduce the crash but there's a memory optimization that deallocates `BloggingReminderScheduler` after blogging reminders scheduling is done which could be responsible.

I'm reverting memory optimization code to guard against reported memory issues related to setting blogging reminders during the migration. We'll test if this change will make the difference. `BloggingRemindersScheduler` and `NotificationSettingsService` will be deallocated after the app restarts.

### Case 1 crash testing:
1. Start the Jetpack migration flow
2. Tap “Continue” on the notifications screen to bring the notifications permissions notice up
3. Initiate the FaceTime audio call from other device
4. Attempt to answer that call by tapping the green button, then attempting to dismiss by tapping the red button (no response to either!)
5. After tapping both call buttons a few time, tap “Accept” on the notifications permissions notice

### Case 2 regression testing:
1. Install WordPress and Log in
2. Set blogging reminders (Site Settings -> Blogging reminders)
3. Install Jetpack
4. Go through the migration flow and accept notifications
5. Go to blogging reminders (Site Settings -> Blogging reminders)
6. Confirm the same blogging reminders appear

## Regression Notes

1. Potential unintended areas of impact

Blogging reminder scheduling continues working

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by staskus** [comment]
⚠️ Not setting reviewers for now. I will allow testing this PR before the review since I wasn't able to reproduce the original issue.

**Comment by staskus** [comment]
✅ The issue is confirmed to have fixed the issue, the crashes when answering calls and accepting notifications are not happening in this branch

**Comment by staskus** [comment]
@guarani, @sla8c the testing of the issue is already done during CfT and branch testing, so code review should be enough.

I'm reverting from memory optimization to a safer approach to avoid any potential crashes.

Let me know if you have any questions or concerns, thank you! 🙏

**Review by guarani — COMMENTED** [review]
👋 Thanks for the PR! I'm reviewing now. The code changes look safe, the only changes I see are the two variables are now `lazy` initialized and there's no attempt to force-deallocate them anymore (by setting them to `nil`).

I tried to reproduce this on 21.5 (current TestFlight build) but couldn't reproduce the crash. The call (answer/decline buttons) weren't responsive, but I think that's expected because the alert is probably a higher window level than the FaceTime call. What do you think?

> I will allow testing this PR before the review since I wasn't able to reproduce the original issue.

> ✅ The issue is confirmed to have fixed the issue, the crashes when answering calls and accepting notifications are not happening in this branch

I'm not sure I follow – were you initially not able to reproduce this but later you did manage to reproduce (thus confirming this PR fixed the issues), or have you not been able to reproduce it yet?

**Comment by guarani** [comment]
Here's a screen recording that starts after I've began the migration to the Jetpack app:

https://user-images.githubusercontent.com/1898325/212399694-d16e304e-5e53-43c4-abab-7e9162b4bc27.mov

I don't see anything unexpected in the video - what do you think?

**Comment by staskus** [comment]
Thanks for reviewing, @guarani, sorry I didn't explain the testing situation more clearly.

- @thehenrybyrd reproduced the crash during the 21.4 testing
- I myself couldn't reproduce the crash and based the fix on Sentry logs

I shared this PR's AppCenter build with @thehenrybyrd and it was confirmed that the crash is not reproducible anymore after the changes were made.

**Review by guarani — APPROVED** [review]
Hey @staskus, no worries and thanks for the explanation. 
I tested the migration flow using the two builds from this PR and found no regressions, so looks good to merge!

**Pull request merged**
