### PR TITLE
QR Login: Add Networking

### PR DESCRIPTION
**Pull request by emilylaguna**
| 📚 Project: #18594 | 🔗  Depends on: #18752 | 🤝 WPKit Related PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/513|
|:---:|:---:|:---:|

### Requirements 
Prior to testing the PR you will need to:
- Follow the testing steps in the related Calypso PR: 
    - https://github.com/Automattic/wp-calypso/pull/63257
- Make sure your **real device** is sandboxed: pbArwn-24D-p2
- Make sure your sandbox is pointed to D79766-code 

### Description
- Implements the QR Login network requests
- Adds some extra error states to the verify view
- Adds a class `QRLoginURLParser` that parses the real QR login token URLs
- Adds a way to "scan again" from the verify view 
- Updates the verify view to show the requesting users Browser, and approximate location

### Notes
- In a later PR a "cancel" button is added to the error states to allow the user to leave the flow without needing to tap scan again
- In a later PR the red subtitle label on the "You're logged in" state is changed to gray

### Demo Video

https://user-images.githubusercontent.com/793774/170776717-9e81c6e5-7d18-47b1-a40c-5cbf6bfd2f20.mov

### Screenshots
| Are you sure? | Success! | No connection | Invalid Data | Expired Token | 
|:---:|:---:|:---:|:---:|:---:|
|01 - are you sure|01 - logged in|01 - no connection|01 - invalid data|01 - expired|

#### Scanning a token with invalid data
invalid-qrlogin-code

1. Launch the app
2. Navigate to My Site > Me > Scan Login Code
3. Scan the QR code image from above
4. 👁️ Verify you see the "Could not validate" error view
5. 👁️ Verify tapping Scan again takes you to the scanning view again

#### Scanning a valid but expired token
qrlogin-expired

1. Launch the app
2. Navigate to My Site > Me > Scan Login Code
3. Scan the QR code image from above
4. 👁️ Verify you see the "Expired log in code" error view
5. 👁️ Verify tapping Scan again takes you to the scanning view again

#### Scanning a valid token
1. Launch the app
2. Navigate to My Site > Me > Scan Login Code
3. Scan the QR Code from the related Calypso PR (See above)
4. 👁️ Verify you see a "Are you trying to login" message that displays your web browser and approximate location
    5. "Are you trying to login to Chrome near Los Angeles, California?"
6. 👁️ Verify tapping Cancel exits out of the flow and nothing else happens
7. Scan the valid code again
8. Tap the 'Yes, log me in' button
9. 👁️ Verify you see a loading indicator with the current message faded out
10. 👁️ Verify after a second you see the "You're logged in!" message
11. 👁️ Verify tapping Dismiss exits the flow
12. 👁️ Verify you are logged in on your web browser

#### Testing no internet error
1. Launch the app
3. Navigate to My Site > Me > Scan Login Code
4. Turn on Airplane mode
5. Scan the QR Code from the related Calypso PR (See above)
6. 👁️ Verify you see a "No connection" error state
7. 👁️ Tapping Scan again brings you back to the scanning view
8. Enable your internet and scan again
9.  👁️ Verify the scanning works correctly 

### Regression Notes
1. Potential unintended areas of impact
None

13. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

14. What automated tests I added (or what prevented me from doing so)
None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by momo-ozawa — COMMENTED** [review]
@emilylaguna 
- Scanning a token with invalid data -> ✅ works as described
- Scanning a valid but expired token -> ❌ I get a "could not validate the log in code" error
- Scanning a valid token -> ❌ I get a "could not validate the log in code" error
- Testing no internet error: no connection -> ✅ works as described
- Testing no internet error: re-enabling internet -> ❌ I get a "could not validate the log in code" error

For the cases where I'm seeing a "could not validate" error, I'm getting a 403 forbidden error for the `qr-code/validate` endpoint. (cc: @enejb any idea what might be happening?)

**Comment by momo-ozawa** [comment]
Hmmm. So I was able to get the `/log-in/qr` screen (slack ref: p1654093547846419/1654090743.168859-slack-C02ENRE1QRX), but I'm still getting 403s for the cases I mentioned above 🤔

**Comment by enejb** [comment]
@momo-ozawa This endpoint returns a 403 error for users that have 2FA enabled or are a8c users.

**Comment by momo-ozawa** [comment]
@emilylaguna @enejb I re-tested w my non-a8c / non-2fa account 🙈🙈🙈
  
- Scanning a token with invalid data -> ✅ works as described
- Scanning a valid but expired token -> ✅ works as described
- Scanning a valid token -> ✅ works as described on mobile, though I get a "Uh oh. Page not found." error on the Calypso Live link upon logging in
- Testing no internet error: no connection -> ✅ works as described
- Testing no internet error: re-enabling internet -> ✅ works as described on mobile, though I get a "Uh oh. Page not found." error on the Calypso Live link upon logging in

Jotting down a couple notes about scanning here but I don't think they're related to the changes in this specific PR:

- If you rotate the device to landscape mode on the scanning screen, half of the screen is blank (see image below)
- The camera scans QR codes when the Control Center is obscuring the scanning screen. Imo I think we should only scan if the scanning screen is in the foreground 

IMG_2420

**Comment by emilylaguna** [comment]
@momo-ozawa 

> If you rotate the device to landscape mode on the scanning screen, half of the screen is blank (see image below)

I restricted the camera scanning view to portrait mode only in here: https://github.com/wordpress-mobile/WordPress-iOS/pull/18716/commits/64634f041a2e9faaa8734b44a7fe8b77250a126f

> The camera scans QR codes when the Control Center is obscuring the scanning screen. Imo I think we should only scan if the scanning screen is in the foreground

Hmm. I can see your point, but I think this use case may be too small to warrant adding the handling for this right now.

**Review by momo-ozawa — APPROVED** [review]

**Pull request merged**
