### PR TITLE
Comments: fix crashes

### PR DESCRIPTION
**Pull request by ScoutHarris**
Ref: #16876

This fixes the following issues:
- My Site > Comments > where a comment has no body: app crashes.
- My Site > Comments > where a user has no avatar: app crashes.
- My Site > Comments > Comment details > Reply: app crashes.
- Self-hosted > Comments: all the comment bodies are empty.

To test:
- Go to My Site > Comments with comments:
  - That have no body.
  - A commenter has not avatar.
- Verify the app doesn't crash, and the comments appear as expected.
- Reply to a comment. 
- Verify the app doesn't crash and the reply is sent successfully.
- On a self-hosted site, verify the comments have content.

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A 

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@mokagio this will need to go in the next `17.9` release when merged. Thank you!

**Review by aerych — APPROVED** [review]
Looks good @ScoutHarris :) 

Tested: 
- Comment with no body
- Comment with no avatar
- Replied to a comment successfully
- Self-hosted comments show content.
:shipit:

**Comment by ScoutHarris** [comment]
Thanks @aerych !

**Comment by mokagio** [comment]
@ScoutHarris this has been bundled as part of [17.9 beta 1 (17.9.0.1)](https://github.com/wordpress-mobile/WordPress-iOS/pull/16952).

Thanks for your work 🙌

**Pull request merged**
