### PR TITLE
Adds Jetpack Add-ons to Zendesk tickets

### PR DESCRIPTION
**Pull request by Gio2018**
Fixes #NA

[Related WordPressKit PR](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/414)

This PR updates the creation of a Zendesk ticket as follows:

1. The `plan`(and the priority of the ticket) sent to Zendesk will reflect the site in use.
2. When opening a ticket for a Jetpack site, if the jetpack site has add-ons (and no other plan) the ticket plan in Zendesk will be `add-on`, and the add-ons will appear in the Jetpack Add-ons field (see screenshots below). Note that if the Jetpack site has a plan, this will prevail over the add-ons.
3. If the current site is a self hosted site, a `selected_site_self_hosted` tag will be added to the request

Zendesk Plan | Zendesk Jetpack Add-ons
-- | --
 | 

Zendesk ticket list

**Note: please don't forget to delete any ticket that was created to test this PR once you are finished reviewing. Thank you.**
To test:
Pre requisites:
- Have an account with at least a self-hosted, jetpack connected site with one or more add-ons (e.g. Jetpack Scan realtime) and one or more wp.com sites.
- Build/run and select the jetpack site on my site
- Open a support request, then go to Zendesk and make sure that the Add-ons show up in the ticket as in the above screenshots.
- Switch site (either wp.com or another Jetpack site with a paid plan, e.g. premium), open another request and make sure that the plan in the ticket always matches the selected site
- Make sure that any request you open from a self hosted site (jetpack connected or not) contains the tag `mobile_self_hosted`

## Regression Notes
1. Potential unintended areas of impact
Limited, this change only affects the plan and add-on fields sent to Zendesk

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Test the feature with a variety of combinations of sites/plans/add-ons

3. What automated tests I added (or what prevented me from doing so)
none
PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by bjtitus** [comment]
@Gio2018 I may be testing this wrong, but I'm not seeing the "Add-on" plan or add-ons in my Zendesk ticket.

Screen Shot 2021-07-08 at 6 44 50 PM

Screen Shot 2021-07-08 at 3 51 53 PM

The data posted to Zendesk does match the metadata from `ZendeskUtils.getZendeskMetadata`.

Do I need to be using a paid Jetpack plan?

**Review by bjtitus — APPROVED** [review]
✅  Verified that the plan is set to "Add-on" and the Add-ons show up in the "Jetpack Add-ons" list.

**Comment by reginabally** [comment]
Hi @Gio2018 I notice the `selected_site_self_hosted` tag was added to 4176134-zd-woothemes but the only site is a WoA (WordPress.com Atomic) site. Can you take a look and see why the tag was added? Thanks!

**Comment by Gio2018** [comment]
> Hi @Gio2018 I notice the `selected_site_self_hosted` tag was added to 4176134-zd-woothemes but the only site is a WoA (WordPress.com Atomic) site. Can you take a look and see why the tag was added? Thanks!

Thanks for bringing this up @reginabally , I'll look into it ASAP!!

**Comment by Gio2018** [comment]
Hi @reginabally , #16947 addresses the issue. Thanks for your patience.

**Comment by reginabally** [comment]
Thanks for the quick fix, @Gio2018!

**Pull request merged**
