### PR TITLE
Reader: Recalculate cell height when Discover tab is reloaded

### LINKED ISSUE #21867: Bug: Reader recommended tags' bottom border is clipped
### Expected behavior

The recommended tags list should be displayed correctly.

### Actual behavior

The tags' bottom border is clipped. See screenshot below:

img_0116

### Steps to reproduce the behavior

- Launch the Jetpack app.
- Navigate to Reader > Discover tab.
- Observe that the recommended tags' bottom border is clipped.

### PR DESCRIPTION
**Pull request by dvdchr**
Fixes #21867

The new recommended tags card somehow doesn't refresh the cell's height on `reloadData`, which gets called after switching tabs. This PR fixes it with a workaround, by forcing the table view to update it's cell height by calling `beginUpdates` and followed with `endUpdates` immediately on the main queue.

## To test

- Launch the Jetpack app.
- Go to Reader > Discover tab.
- Refresh until you have a recommended tags card that spans two lines.
- Tap the Following tab.
- Tap to go back to Discover again. 
- 🔎 Verify that the recommended tags cell is displayed correctly.

## Regression Notes
1. Potential unintended areas of impact
The Discover tab will now be forced to re-render its cells' height when reloaded. 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the changes.

3. What automated tests I added (or what prevented me from doing so)
N/A.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by wargcm — COMMENTED** [review]
It appears this introduces a new issue:

https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/4ff25c5e-802b-467b-981b-8409215e9b97

**Comment by dvdchr** [comment]
Ah good catch @wargcm. Since this is a workaround anyway, I will look into this and try to find a better solution. I'll target 23.6 instead.

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing 23.7 today and this is still a draft.

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing 23.8 today and this is still a draft.

@dvdchr just checking in on this, since it's been a draft with not activity for a few weeks. Is this still relevant?

**Comment by dvdchr** [comment]
Hi @mokagio, thanks for moving the milestone. This is an issue that I encountered back during beta, but the solution in this PR introduced side effects — and I didn't have time to work on a proper fix to address the issue. 

I'll set the milestone to `Someday` for now, but our team is currently in Release Rotation; I plan to come back to this issue sometime during this sprint. If it works out, I'll update the milestone again, targeting 23.9. 🙂

**Comment by mokagio** [comment]
Hey @dvdchr  👋 You might notice a merge `trunk` commit here from me. That is to bring this branch up to date with the latest CI changes on `trunk` and ensure everything works on the new Xcode 15.1 CI stack.

Don't hesitate to ping me if there's any trouble.

**Pull request closed without merging**
