### PR TITLE
Social account logins: Don't update username when using a password manager.

### LINKED ISSUE #14620: Google login: can inadvertently link two accounts when using password manager
### Expected behavior
When starting Google login with one account, then selecting a different one on the password view, neither account should be affected. 

### Actual behavior
When starting Google login with one account, then selecting a different one on the password view, the first account is linked via Google to the second account. 

### Steps to reproduce the behavior

Prereqs:
- Two gmail accounts that:
  - Have been used to create WP accounts.
  - Are _not_ connected to Google*.
  - Have WP passwords set.

* You can check Google connection at https://wordpress.com/me/security/social-login:

Screen Shot 2020-08-11 at 1 59 25 PM

- Go to Log In > Continue with Google.
- Select account A.
- On the password entry view, tap the password manager button on the keyboard, and select account B. Notice the email address field updates to account B.
- Finish logging in.
- Log out.
- Go to Log In > Continue with Google.
- Select account A.
- You get immediately logged in with account B.

Go to https://wordpress.com/me/security/social-login for account B and it will show Google connected with account A's email address. If you disconnect Google here, account A is fixed.

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #14620 
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/372

This uses the Auth changes to _not_ update the username on the Password view when logging in via a social account. To note, this fixes the issue in the current flow, not the unified. I'll fix that in a later PR.

**Prereqs:**
- You'll need to use an actual device to get the password manager button on the keyboard. 
- Two gmail accounts that:
  - Have been used to create WP accounts.
  - Are _not_ connected to Google*.
  - Have WP passwords set.

* You can check Google connection at https://wordpress.com/me/security/social-login:

Screen Shot 2020-08-11 at 1 59 25 PM

**To test:**

Google Login:
- Go to Log In > Continue with Google.
- Select account A.
- On the password entry view, tap the password manager button on the keyboard, and select account B. 
- Verify:
  - The displayed email address _does not_ change.
  - The password field is populated.
- Finish logging in with account A. Verify it is the correct account.
- Log out.
- Go to Log In > Continue with Google.
- Verify you can login with both accounts successfully, and they are the correct accounts.

WP Login:
- Go to Log In > Continue with WordPress.com.
- Select account A.
- On the password entry view, tap the password manager button on the keyboard, and select account B. 
- Verify:
  - The email address _does_ change.
  - The password is populated.
  - You successfully log into account B.

1Password:
- On a device with 1Password set up, please test both scenarios above (Google Login and WP Login), using the 1Password button on the username field:

1p_button

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @diegoreymendez .

> The second case felt confusing to me, but is working exactly as described.

Can you explain what was confusing? I didn't change that behavior, so it should be as before.

> Not strictly related to this PR but worth noting... there's a really awkward transition when selecting the account from iOS's popup as shown here

Yea, not related to what I did. Also, I don't think that's something we need to worry about fixing since we're replacing this flow. However, if you see that happen with the unified flow we could look at that.

> Will there be a separate PR to fix this for OnePassword users? The bug exists there as well and is still reproducible.

Grrr. @mindgraffiti I forgot about 1Password. I'll add it to this one, as it should be. Thank you!

**Comment by ScoutHarris** [comment]
@mindgraffiti @diegoreymendez I've 🤞 fixed it for 1Password. Please to retest. Thank you!

**Comment by diegoreymendez** [comment]
> Can you explain what was confusing? I didn't change that behavior, so it should be as before.

It felt weird to me you'd be able to change the username after explicitly selecting it in the first step, but that's honestly beyond the scope of this review.

**Comment by ScoutHarris** [comment]
@mindgraffiti @diegoreymendez - thanks for your help in troubleshooting 1P! @diegoreymendez I used your idea of a `allowUsernameChange` flag when fetching 1P credentials.

I've also updated the 1P testing description to be more specific, i.e.:  `On a device with 1Password set up, please test both scenarios above (Google Login and WP Login), using the 1Password button on the username field.`

🤞 it's fixed this time. Ready for another review please!

**Pull request merged**
