### PR TITLE
ULS Get Started: email handling

### PR DESCRIPTION
**Pull request by ScoutHarris**
Ref: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/404
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/435
Kit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/278

This uses the Kit and Auth changes to process an entered email address.

Notes:
- You may want to test on a real device to ensure magic link emails work.
- All these flows should be fully functional, so you should be able to login and signup as expected.

To test:

---
- Enable the `unifiedWordPress` feature flag.
- On the prologue, `Continue with WordPress.com`.
- The Get Started view appears.

get_started

---
Passwordless WP account:
- Enter an email that has a WP account with no password.
- Verify you receive a login link email, and the `Check your email...` view is displayed.

open_mail

---
WP account with password:
- Enter an email that has a WP account with a password set.
- Verify the Password view is displayed.

password

---
No matching WP account:
- Enter an email that has not been used on a WP account.
- Verify the Sign Up view is displayed.

sign_up

---
PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by diegoreymendez — CHANGES_REQUESTED** [review]
✅ Passwordless WP account
✅ WP account with password
✅ No matching WP account

❌ That said, the email field is not letting me pick any type of stored credentials.  (missing toolbar above the keyboard)

**Comment by ScoutHarris** [comment]
Thanks @diegoreymendez .

I can't believe I totally spaced on password manager support. Do you mind if I do that in another PR? This one is already pretty large, and it'll take a bit of time to work out.

**Comment by diegoreymendez** [comment]
> Do you mind if I do that in another PR?

Not at all.  I'll approve.

**Review by diegoreymendez — APPROVED** [review]

**Comment by mindgraffiti** [comment]
Taking over this PR while ScoutHarris deals with more important things. Thanks @ScoutHarris!

**Pull request merged**
