### PR TITLE
Gutenberg: Update gutenberg to use RN version 0.59.0

### PR DESCRIPTION
**Pull request by etoledom**
This PR implements the changes made on https://github.com/wordpress-mobile/gutenberg-mobile/pull/741, meant to update React Native to 0.59.0

I made a few changes to Podfile to simplify future updates and to keep the react-native `podfile.json` dependencies always tagged, instead of pointing to `master` branch (or branches in general).

This will avoid problems where podfile keeps pointing to the same branch but the file itself was updated in that branch.

To test:

- Run `rake dependencies`
- Check that all react-native dependencies are updated.
- Checkout the `gutenberg-mobile` branch and run `metro` server.
- Run the WPiOS app and open a gutenberg instance.
- Check that everything works fine.

**Note:** Since the JS Bundle haven't been updated yet, this won't work without metro running.

### CODE REVIEW

**Comment by etoledom** [comment]
Opent a PR to fix the Danger check:
https://github.com/wordpress-mobile/peril-settings/pull/1

**Comment by etoledom** [comment]
Danger check ready! Thank you @jtreanor !

**Comment by etoledom** [comment]
Thank you @SergioEstevao !
Let's wait for the JS Bundles to be generated and https://github.com/wordpress-mobile/gutenberg-mobile/pull/741 to be merged 👍

**Comment by etoledom** [comment]
@SergioEstevao - Updated to include the JS Bundles 👍

**Comment by SergioEstevao** [comment]
Looking great on iOS! It's a merge for me!

**Comment by etoledom** [comment]
Updated to the latest `gutenberg-mobile` develop after 
https://github.com/wordpress-mobile/gutenberg-mobile/pull/741 was merged 🎉

Merging this on ✅

**Pull request merged**
