### PR TITLE
Stats Revamp: Inconsistent rounding of numbers in the cards

### LINKED ISSUE #19346: [iOS] Stats: Inconsistent rounding of numbers in the cards of Insights tab
The rounding of numbers differ between iOS and Android/Web. Make it consistent with Android.

image
image

### Expected behavior

1. Most Popular Time percentages match Android and Web
2. If the previous period was empty, don't show zero increase in the brackets: Show `+6` instead of `+6 (0%)`
3. This Year's statistics rounding matches Android

### Steps to reproduce the behavior

1. Enable statsRevamp feature flag
2. Open Stats
3. Open Insights Tab
4. Compare "Most popular time" and "This Year" information with Android and Web

### PR DESCRIPTION
**Pull request by staskus**
Fixes #19346

Related PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/543/files

## Description

There're some inconsistencies between how numbers are rounded between iOS and Android.

1. [Wrong rounding of percentages fixed on WordPressKit](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/543/files), since `Double` were turned into `Int` there
2. Presenting averages as decimals and not whole numbers by removing `round` function. We still use `abbreviatedString()` which internally uses `decimal NumberFormatter`.
3. Not showing 0% difference.

### Before all:
Enable `statsRevamp` feature flag and open "Stats"

### Case 1 wrong rounding:
1. Add "Most Popular Time" card
2. Percentages should match between `iOS` and `Android`

### Case 2 averages as decimals:
1. Add "This year" card
2. Average Comments, Words, Likes should be represented as a decimal number instead of whole number, unless the average number *is* a whole number

### Case 3 0% difference:
1. Add "Views and Visitors" card
2. If necessary, click "View More" and come back to a week where "Previous Week" had 0 views, and "This week" has more than 0 views
3. The difference should only be represented in actual number and 0% should not be shown in brackets

## Regression Notes

1. Potential unintended areas of impact

Currently implemented functionality breaks

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Tested the cards that were changed with various types of blogs 

3. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

#### Wrong percentages (always rounded down)
drawing

#### Averages represented as whole numbers
drawing

#### 0% difference shown
drawing

#### Percentages rounded same way as on Android
drawing

#### Averages represented as decimal numbers
drawing

#### 0% difference not shown
drawing

### CODE REVIEW

**Review by guarani — COMMENTED** [review]
> ### Case 1 wrong rounding:
> 1. Add "Most Popular Time" card
> 2. Percentages should match between `iOS` and `Android`

| iOS | WordPress.com | Android
| - | - | - |
| Screen Shot 2022-10-06 at 16 04 26 | Screen Shot 2022-10-06 at 16 04 21 |  |

Android differs from iOS and the web with regard to the "% of view" for "Best Day". All three platforms seem to align on "Best Day". Is this what you also see?


> ### Case 2 averages as decimals:
> 1. Add "This year" card
> 2. Average Comments, Words, Likes should be represented as a decimal number instead of whole number, unless the average number _is_ a whole number

nitpick: Before this PR, neither the web nor iOS used decimal averages in the "This Year" card, only Android did. Is it better to switch iOS to match Android (as is done here), or make Android match the other platforms? Personally, I see the benefit in decimal averages, but curious to know your thoughts.

> 
> ### Case 3 0% difference:
> 1. Add "Views and Visitors" card
> 2. If necessary, click "View More" and come back to a week where "Previous Week" had 0 views, and "This week" has more than 0 views
> 3. The difference should only be represented in actual number and 0% should not be shown in brackets

This is working great 👍

**Comment by guarani** [comment]
I ran into a couple of bugs that I will report separately (I believe they're unrelated to this PR). To summarize:

### This Year card cut-off

The last row on the This Year card only shows titles, not values. Android shows these values correctly.

| Screen Shot 2022-10-06 at 16 05 45 |
| - |

### Stats showing data for previously selected site

Steps to reproduce:
1. Switch to site A
2. Go to the Views & Visitors card
3. Go to a previous week (⚠️ if you don't do this, the bug doesn't seem to happen)
4. Switch to site B
5. Go to the Views & Visitors card
6. Notice that the chart is showing data for Site A ❌

### Views & Visitors card shows blank screen

| Screen Shot 2022-10-06 at 16 07 18 |
| - |



1. Go to the Views & Visitors card
2. Go back to previous weeks until you encounter a blank screen (only the date picker is shown, no chart)

**Comment by staskus** [comment]
> I ran into a couple of bugs that I will report separately (I believe they're unrelated to this PR)

Thanks for testing and reporting more issues 👍

## This Year card cut-off ✅

[I fixed it in a separate PR: Stats Revamp: Two Column Cell with View More button cuts off](https://github.com/wordpress-mobile/WordPress-iOS/pull/19416)

## Stats showing data for the previously selected site

This issue is reproducible even without changing sites. The last selected period is remembered and then shown once we come back to Stats screen:

1. Open Stats
2. See Views & Visitors 
3. Open Week >
4. Change period (come back in weeks)
5. Go back to Stats
6. Go back to main menu
7. Select Stats
8. Views & Visitors card will show date for changed period and not for "This week".

## Views & Visitors card shows blank screen

Note: They could theoretically be related to some recent changes related to [stores](https://github.com/wordpress-mobile/WordPress-iOS/pull/19003) and [views&visitors](https://github.com/wordpress-mobile/WordPress-iOS/pull/19393).

You can leave the creation of issues / fixes to me.

**Comment by staskus** [comment]
## Best day issue
> Android differs from iOS and the web with regard to the "% of view" for "Best Day". All three platforms seem to align on "Best Day". Is this what you also see?

I certainly saw it differently, and all platforms matched/matches for me.

image

I checked the rounding code [that Android uses](https://github.com/wordpress-mobile/WordPress-Android/pull/16422/files) and compared it to Swift and it has the exact same behavior. Maybe you caught some case that had Android results cached? 🤔

image

## Decimal Averages

> Before this PR, neither the web nor iOS used decimal averages in the "This Year" card, only Android did.

Yes, it's inconsistent. The Web shows different patterns in different places:
image

If we click View All it starts showing decimal averages:
image

> Is it better to switch iOS to match Android (as is done here), or make Android match the other platforms?

I see the benefit of having decimal averages as it gives more precision to this metric.

**Comment by guarani** [comment]
> ## This Year card cut-off ✅
> [I fixed it in a separate PR: Stats Revamp: Two Column Cell with View More button cuts off](https://github.com/wordpress-mobile/WordPress-iOS/pull/19416)

Thanks for the fix, I reviewed it now ✅ 

> ## Stats showing data for the previously selected site
> This issue is reproducible even without changing sites. The last selected period is remembered and then shown once we come back to Stats screen:

Thanks for finding shorter steps to reproduce!

> ## Views & Visitors card shows blank screen
> Note: They could theoretically be related to some recent changes related to [stores](https://github.com/wordpress-mobile/WordPress-iOS/pull/19003) and [views&visitors](https://github.com/wordpress-mobile/WordPress-iOS/pull/19393).

Ok, I haven't checked previous versions.

> You can leave the creation of issues / fixes to me.

Thanks @staskus! ❤️ 

---

> ## Best day issue
> I checked the rounding code [that Android uses](https://github.com/wordpress-mobile/WordPress-Android/pull/16422/files) and compared it to Swift and it has the exact same behavior. Maybe you caught some case that had Android results cached? 🤔

That's a good idea. I tried reinstalling the Android app and still see a difference:

| Screen Shot 2022-10-07 at 10 24 51 |
| - |
 
Maybe it needs investigation on the Android side since web and iOS match, wdyt?

> ## Decimal Averages
> I see the benefit of having decimal averages as it gives more precision to this metric.

Sounds good 👍 And thanks for spotting that web uses decimal averages in some places, I hadn't noticed that.

**Comment by guarani** [comment]
Feel free to re-request a review if this is ready again 👍

**Comment by staskus** [comment]
> Maybe it needs investigation on the Android side since web and iOS match, wdyt?

Definitely. I don't see where the problem is myself.

**Comment by staskus** [comment]
@ravishanker / @irfano do you have any idea why in [this case](https://github.com/wordpress-mobile/WordPress-iOS/pull/19400#issuecomment-1271594692) we have different rounding of "Most Popular Time" numbers on Android compared to Web and iOS?

Let me know if you need me to create a separate issue or provide more steps.

**Review by guarani — APPROVED** [review]
I tested this in my previous review and the only open question was about the differing Best Time values on Android, which don't seem related to this PR. 
It looks like this PR has only been updated to point to the merged WP Kit release and updated from `trunk`, so I'm approving this without re-testing.

**Comment by irfano** [comment]
> @ravishanker / @irfano do you have any idea why in [this case](https://github.com/wordpress-mobile/WordPress-iOS/pull/19400#issuecomment-1271594692) we have different rounding of "Most Popular Time" numbers on Android compared to Web and iOS?
> 
> Let me know if you need me to create a separate issue or provide more steps.

Thanks for finding these issues. The rounding was wrong on the stats screen (not just Most Popular Time). I fixed them in https://github.com/wordpress-mobile/WordPress-Android/pull/17302

**Pull request merged**
