### PR TITLE
Domains Dashboard Card: Presentation & Analytics

### LINKED ISSUE #20412: Domains Dashboard Card: Analytics
**Specification:** pc8eDl-LC-p2
**Project board:** [GitHub](https://github.com/orgs/wordpress-mobile/projects/154/views/19)

Implement analytics for domains dashboard card

## Requirements

| Event                                            | Description                                                 | Properties      |
|--------------------------------------------------|-------------------------------------------------------------|-----------------|
| direct_domains_purchase_dashboard_card_shown     | Tracked when a site meets the criteria and the app shows the dashboard card.   | position_index  |
| direct_domains_purchase_dashboard_card_tapped    | Tracked when a user taps a dashboard card.                  | position_index  |
| direct_domains_purchase_dashboard_card_hidden    | Tracked when a user taps a CTA to hide a dashboard card.    | position_index  |

`position_index`  describes the current placement of the card in the dashboard
- number, from 0 to the total number of dashboard cards

### PR DESCRIPTION
**Pull request by staskus**
Fixes #20412

Connect [UI](https://github.com/-mobile/-iOS/issues/20409) and [Functionality](https://github.com/-mobile/-iOS/issues/20411) together for Domains Dashboard Card

- [x] Add release notes

### 1. Implement analytics events

| Event                                            | Description                                                 | Properties      |
|--------------------------------------------------|-------------------------------------------------------------|-----------------|
| direct_domains_purchase_dashboard_card_shown     | Tracked when a site meets the criteria and the app shows the dashboard card.   | position_index  |
| direct_domains_purchase_dashboard_card_tapped    | Tracked when a user taps a dashboard card.                  | position_index  |
| direct_domains_purchase_dashboard_card_hidden    | Tracked when a user taps a CTA to hide a dashboard card.    | position_index  |

### 2. Hooking the dashboard card with the functionality

- Hide the card when the "Hide" option is selected
- Present domains dashboard when the card is tapped
- Call the analytics events

### Before all:
1. Launch Jetpack app
2. Go to AppSettings -> Debug and enable `Domains Dashboard Card` feature flag
3. Use WP.com site without domain or domain credits

### Case 1 Appearance:
1. Domains card appears
2. Confirm `Tracked: direct_domains_purchase_dashboard_card_shown <position_index: 4>` being tracked
3. Confirm the position is correctly represented by where the first card has `position_index: 0`

### Case 2 Hide:
1. Domains card appears
2. Select the context menu and "Hide" CTA
3. Confirm `Tracked: direct_domains_purchase_dashboard_card_hidden <position_index: 2>` being tracked
4. Confirm the position is correctly represented by where the first card has `position_index: 0`
5. Confirm that the card disappears
6. Close the app
7. The card should not reappear
8. Change another eligible site
9. The unhidden card should appear in another site

### Case 3 Show:
1. Domains card appears
2. Click on the card
3. Confirm `Tracked: direct_domains_purchase_dashboard_card_tapped <position_index: 4>` being tracked
4. Confirm the position is correctly represented by where the first card has `position_index: 0`
5. Confirm that Domains Dashboard view opens

## Regression Notes

1. Potential unintended areas of impact

Domains Dashboard presentation, since the code was refactored

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing: Menu -> Domains

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Video

https://user-images.githubusercontent.com/4062343/228847848-5a593102-6857-479b-8357-c45c97c7492c.mp4

### CODE REVIEW

**Comment by mokagio** [comment]
@staskus I'm going to bump this to 22.3 because it hasn't been reviewed yet and I'll be working on the 22.2 code freeze tomorrow.

Events logging is crucial, and depending on the domains dashboard timeline it might be worth targeting `release/22.2` with this one. Feel free to update if that's the case.

**Comment by mokagio** [comment]
> @staskus I'm going to bump this to 22.3 because it hasn't been reviewed yet and I'll be working on the 22.2 code freeze tomorrow.

Apologies. I got the wrong milestone last night 🤦‍♂️  I'll be working code freezing _22.1_ shortly, not 22.2.

I'll fix the milestone now.

**Comment by staskus** [comment]
> Apologies. I got the wrong milestone last night 🤦‍♂️ I'll be working code freezing 22.1 shortly, not 22.2.

All good! Thanks for going through these PRs and making sure that we include what we expect in the release 👍

**Comment by sla8c** [comment]
@staskus this looks good to me except you have a merge conflict on xcodeproj.  If you update the PR to fix the merge conflict, I'll do a quick test again + recompile to make sure all looks good after thx

**Comment by staskus** [comment]
@sla8c Thanks! I fixed the conflicts and provided release notes.

**Review by sla8c — APPROVED** [review]
LGTM

**Pull request merged**
