### PR TITLE
[Stats Refresh] Add Period > Authors card

### LINKED ISSUE #10946: [Stats Refresh] Add Period > Authors card
- [ ] Card showing authors and number of views on DWMY views
- [ ] When row is tapped expand to show individual posts/pages + number of views

(8)

Design:
authors

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #10946 

To test:

---
- On a site with some posts, go to Stats > Period > Authors.
  - Note when switching between the Period filters, the expanded rows will reset.
- Verify the view is:

authors_init

---
- Select an Author row.
  - Max 10 child rows will be displayed, showing the Author's posts.
  - There is no action for selecting a child row.
- Verify the view is:

authors_expanded

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@jklausa - the constraint warnings mentioned in https://github.com/wordpress-mobile/WordPress-iOS/pull/10944#issuecomment-460770023 still exist, and are actually exacerbated when a cell is expanded. (Try expanding a row and then rotate. G'head, try it. 😄 ) It's still my plan to fix that ASAP in a separate PR (since it pre-dated the expanding rows).

**Comment by ScoutHarris** [comment]
@SylvesterWilmott  - 

---
authors_init

---
authors_expanded

---
ipad_portrait

---
ipad_landscape

**Comment by ScoutHarris** [comment]
Hey @jklausa . Sorry for the spam. The constraint issues were so bad with the expanded rows, sometimes they wouldn't even render. So I fixed the constraint issues on this PR. 

When switching period filters or scrolling, you should _not_ see a slew of warnings like this:
```
    "<NSLayoutConstraint:0x6000010a1a90 UIView:0x7fc39ea331f0.height == 0.5   (active)>",
    "<NSLayoutConstraint:0x6000010a1b80 UIButton:0x7fc39ea2d580.top == UILayoutGuide:0x6000009b2f40'UIViewSafeAreaLayoutGuide'.top   (active)>",
    "<NSLayoutConstraint:0x6000010a1f40 UILayoutGuide:0x6000009b2f40'UIViewSafeAreaLayoutGuide'.bottom == UIView:0x7fc39ea331f0.bottom   (active)>",
    "<NSLayoutConstraint:0x6000010a2120 V:[UIButton:0x7fc39ea2d580]-(0)-[UIView:0x7fc39ea331f0]   (active)>",
    "<NSLayoutConstraint:0x6000010a2ee0 UIView:0x7fc39ea357c0.height == 0.5   (active)>",
    "<NSLayoutConstraint:0x6000010a2fd0 UIButton:0x7fc39ea219c0.top == UILayoutGuide:0x6000009b31e0'UIViewSafeAreaLayoutGuide'.top   (active)>",
    "<NSLayoutConstraint:0x6000010a3390 UILayoutGuide:0x6000009b31e0'UIViewSafeAreaLayoutGuide'.bottom == UIView:0x7fc39ea357c0.bottom   (active)>",
    "<NSLayoutConstraint:0x6000010a3570 V:[UIButton:0x7fc39ea219c0]-(0)-[UIView:0x7fc39ea357c0]   (active)>",
    "<NSLayoutConstraint:0x6000010d1ea0 UIView:0x7fc39ea37e70.height == 0.5   (active)>",
```

**Comment by jklausa** [comment]
This is unrelated to the PR itself, but: 

Should we maybe indent the blog post names in this view, or add an icon? _I_ can sorta guess that’s what the expanded items are, but without any labels or icons it all just blends together with the author name — it feels like this might be a source of confusion for our users.

**Comment by SylvesterWilmott** [comment]
>Should we maybe indent the blog post names in this view, or add an icon? _I_ can sorta guess that’s what the expanded items are, but without any labels or icons it all just blends together with the author name — it feels like this might be a source of confusion for our users.

Thanks for the feedback @jklausa . I'll look into this

**Comment by ScoutHarris** [comment]
Hey @jklausa . Unless I'm missing something, those warnings are caused by the split view, and have been around a while.

I've already branched off of this, so I’ll look again in my current branch to make sure I didn’t miss any that I caused.

**Pull request merged**
