### PR TITLE
Adds icon for homepage and posts page

### PR DESCRIPTION
**Pull request by antonis**
**Fixes** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2937

## Description
This PR adds icons for homepage and posts page and lists the homepage first (only if it is [at the top level](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2937#issuecomment-756069847))

### Homepage
1. From *My Site* press the *Pages* button or scroll down and select *Site Pages* from the list
1. If no pages are listed press the fab icon at the bottom-right to create one
1. If no homepage is set press the *dots* at the right of a page listing and choose **Set as Homepage**
1. **Verify** that the homepage is listed **first** with an **icon** before the `Homepage` label

### Nested Homepage
1. From *My Site* press the *Pages* button or scroll down and select *Site Pages* from the list
1. Create a page hierarchy
1. Press the *dots* at the right of a nested page and choose **Set as Homepage**
1. **Verify** that the homepage does not move to the top and has an **icon** before the `Homepage` label

### Homepage with children
1. From *My Site* press the *Pages* button or scroll down and select *Site Pages* from the list
1. Create a page hierarchy
1. Press the *dots* at the right of a page with children and choose **Set as Homepage**
1. If no homepage is set press the *dots* at the right of a page listing and choose **Set as Homepage**
1. **Verify** that the homepage is listed **first** with an **icon** before the `Homepage` label and the children below it

### Posts page
1. From *My Site* press the *Pages* button or scroll down and select *Site Pages* from the list
1. If no pages are listed press the fab icon at the bottom-right to create one
1. If no Posts Page is set press the *dots* at the right of a page listing and choose **Set as Posts Page**
1. **Verify** that the Posts Page is listed with an **icon** before the `Posts Page` label

## Screenshots

|Before|After|
|---|---|
|old|new|

|Nested homepage|Homepage with children|
|---|---|
|Screen Shot 2021-01-07 at 3 35 42 PM|Screen Shot 2021-01-07 at 3 37 29 PM|

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by enejb** [comment]
I tested this and the ordering worked well and as described in https://github.com/wordpress-mobile/gutenberg-mobile/issues/2937. 

I noticed a couple of things. 
1. The font colour of "Homepage" and "Posts page" don't match the icon. I think they should be a slightly ligher gray. 
2. When I changed the parent by three dots menu > Set Parent. The list didn't update as expected. Can changing the parent trigger a reorder of the list? (It works as expected when you when you select the homepage) I am not sure we this needs to be fixed in this PR but would be good to address it in a different one.

**Comment by antonis** [comment]
Hey @enejb 👋 

Thank you for reviewing and bringing up the two issues 🙇 

> 1. The font colour of "Homepage" and "Posts page" don't match the icon. I think they should be a slightly ligher gray.

Fixed with 31349d3617a5785eb1336bb92265ea69e83c05c7

> 2. When I changed the parent by three dots menu > Set Parent. The list didn't update as expected. Can changing the parent trigger a reorder of the list? (It works as expected when you when you select the homepage) I am not sure we this needs to be fixed in this PR but would be good to address it in a different one.

Fixed with 96f70a732e243ff73ee7adbd7518956987ff0339

**Comment by enejb** [comment]
Thanks for the fixes @antonis. 

I confirmed that the colour as well as changing the Parent now works as expected. 
Nicely done.

**Review by enejb — APPROVED** [review]
Nice work!

**Pull request merged**
