### PR TITLE
WordPressAuthenticator asume https

### PR DESCRIPTION
**Pull request by etoledom**
When the site address for log in has no scheme, the app will asume https instead of http

This PR fixes a wrong error message when the server blocks http requests and it doesn't redirect to https.

To test:

- Go to `Log in by site address`
- Enter a magic address that has this problem (without specifying scheme)
- **Before**: It was giving an error: `Not a WP site`
- **Now**: It should let you go to the user/password screen

### CODE REVIEW

**Comment by kwonye** [comment]
@etoledom looking at Android, they're trying both `http` and `https`. It looks like we're simply trying `https` now, which I don't believe will work since not all sites are configured for that. Any ideas on how we try both?

Android adds both to a list to try.

**Comment by etoledom** [comment]
I see, that could be a problem. Let's see how can we do that.

@kwonye Is it to try the whole process with `https` and then to repeat everything again with `http`?

**Comment by kwonye** [comment]
@etoledom yup! What Android does it try it twice, first with `https`

https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9bea621bbd03e112e180b6eb348fc4bbb24dae76/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/SelfHostedEndpointFinder.java#L199

**Comment by etoledom** [comment]
@kwonye  Following the Android app, now it will try to get the xmlrpc url from the url with `https` scheme (default) and if it fails, it will try with `http` scheme. 

In the case that the user specifies `http`, it will try `http` first and then `https`.

I tried doing this just for the `guessXMLRPCURLFromHTMLURL` process, but it was returning an ssl error for https (in sites without valid certificate) instead of asking for trusting the site.

I also did a merge test with #8846 and it seems to work fine.

**Pull request merged**
