### PR TITLE
[Site creation] Style WebAddressWizardContent

### LINKED ISSUE #10480: [Site creation] Style WebAddressWizardContent
- [ ] Update styles of cells
- [ ] Scroll header up when textfield in focus

Edited on January 14th. 

The scope is reduced to applying style to the cells, according to the UI designs.

### PR DESCRIPTION
**Pull request by ctarda**
Fixes #10480 

Before and after:
web-cell-before-after

iPhone X:
simulator screen shot - iphone xr - 2019-01-15 at 09 19 37

iPhone SE:
simulator screen shot - iphone se - 2019-01-15 at 09 29 03

iPad Pro 11 (2018):
simulator screen shot - ipad pro 11-inch - 2019-01-15 at 09 43 54

This PR changes:
- [ ] Update styles of cells
- [ ] Scroll header up when the textfield is in focus
- [ ] Make header and table view honour the layout guides

To test:
- Check the branch
- Navigate to Enhanced Site Creation until the Web address selection screen is reached.

Update release notes:
- Nothing worth mentioning in the release notes.

There is significant duplication between WebAddressWizardContent and VerticalsWizardContent. I have added a ticket to look into it later on ( #10821 ), and see if we can find a way to remove some of that duplication

### CODE REVIEW

**Comment by stevebaranski** [comment]
@ctarda I'll leave the final call to @SylvesterWilmott, but the UI changes you've applied look good to my eye. Moreover, the headers remain visible on iPad, consistent with the expectation noted in #10688 and applied to _Verticals_ in #10816.

I am seeing some functional issues, however, that are best illustrated in the GIF below:

1. The headers hide as soon as the text field acquires focus, when it is supposed to respond to the content of the text field. This was prescribed [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/10494#issuecomment-453143212) & logged in #10812
1. The headers do not reset properly when exiting the screen (via _Back_), as noted in #10791.

Both of these changes were applied to _Verticals_ just yesterday in #10820.

10822pr_b

Regarding your comment:
> There is significant duplication between WebAddressWizardContent and VerticalsWizardContent. I have added a ticket to look into it later on ( #10821 ), and see if we can find a way to remove some of that duplication

I intended to address this via #10811 today. Would you like me to (a) assign that issue to you; (b) document the expected results in #10821 and close #10811?

**Comment by ctarda** [comment]
Thanks @stevebaranski . If you already had removing that duplication in mind, would you mind attacking it please?

**Comment by stevebaranski** [comment]
> If you already had removing that duplication in mind, would you mind attacking it please?
Let me check with @kwonye, and we can update #10811 & #10821 accordingly.

**Comment by SylvesterWilmott** [comment]
Looks great @ctarda thanks!

**Pull request merged**
