### PR TITLE
Implement Stats Refresh analytics events

### LINKED ISSUE #11730: [Stats Refresh] Implement & validate analytics events
Capture analytics events to measure performance of the Stats Refresh project. 

This should maintain parity with the Android implementation, implemented [here](https://github.com/wordpress-mobile/WordPress-Android/pull/8836) & [here](https://github.com/wordpress-mobile/WordPress-Android/pull/9757).

### PR DESCRIPTION
**Pull request by stevebaranski**
### Summary
Fixes #11730.

To test:
- Checkout the branch and confirm that existing tests pass, including those in `WPAnalyticsTrackerAutomatticTracksTests`.
- Review the code changes, and confirm that everything looks square.
- As a user, launch the app on-device or in the Simulator, logged in with _Collect Information_ toggle enabled in _Me : App Settings : Privacy Settings_.
- Step through the Stats functionality, taking note that these events are logged* as expected.

It's probably easiest to validate events in one of the following two ways:
1. The event and properties are logged to the console [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m#L72-L76).
1. You can search for the events in post via _Tracks Live View_. Once the events are captured, be sure they are sent across the wire. This is easiest to accomplish by backgrounding the app, initiated [here](https://github.com/Automattic/Automattic-Tracks-iOS/blob/develop/Automattic-Tracks-iOS/TracksService.m#L269).

Update release notes:

- [X] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### Discussion
Absent explicit requirements, it took some time & energy to distill the specific changes that needed to be made. For this reason, I've chosen to chronicle my approach below. Please advise if I missed something!

1. Examined the Android implementation of analytics; the PRs for these changes are noted in the issue.
1. Defined the net new events in `WPAnalytics.h` (see `WordPressShared`).
1. Absorbed these new events in WPiOS, ensuring that `WPAnalytics.m` prescribes `eventName` properties that match the aforementioned Android implementation.
1. Implemented the events below:

#### "Legacy" Events
- `WPAnalyticsStatStatsInsightsAccessed`
- `WPAnalyticsStatStatsPeriodDaysAccessed`
- `WPAnalyticsStatStatsPeriodWeeksAccessed`
- `WPAnalyticsStatStatsPeriodMonthsAccessed`
- `WPAnalyticsStatStatsPeriodYearsAccessed`
- `WPAnalyticsStatStatsScrolledToBottom`
- `WPAnalyticsStatStatsSinglePostAccessed`

#### _Latest Post Summary_ Events
- `WPAnalyticsStatStatsItemTappedLatestPostSummaryNewPost`
- `WPAnalyticsStatStatsItemTappedLatestPostSummaryPost`
- `WPAnalyticsStatStatsItemTappedLatestPostSummarySharePost`
- `WPAnalyticsStatStatsItemTappedLatestPostSummaryViewPostDetails`

#### _View More_ Events
- `WPAnalyticsStatStatsViewAllAccessed` (legacy event)
- `WPAnalyticsStatStatsViewMoreTappedAuthors`
- `WPAnalyticsStatStatsViewMoreTappedClicks`
- `WPAnalyticsStatStatsViewMoreTappedComments`
- `WPAnalyticsStatStatsViewMoreTappedCountries`
- `WPAnalyticsStatStatsViewMoreTappedFollowers`
- `WPAnalyticsStatStatsViewMoreTappedLatestPostSummary`
- `WPAnalyticsStatStatsViewMoreTappedPostsAndPages`
- `WPAnalyticsStatStatsViewMoreTappedPublicize`
- `WPAnalyticsStatStatsViewMoreTappedReferrers`
- `WPAnalyticsStatStatsViewMoreTappedSearchTerms`
- `WPAnalyticsStatStatsViewMoreTappedTagsAndCategories`
- `WPAnalyticsStatStatsViewMoreTappedVideoPlays`

#### Additional Row Selection Events
- `WPAnalyticsStatStatsItemTappedAuthors`
- `WPAnalyticsStatStatsItemTappedClicks`
- `WPAnalyticsStatStatsItemTappedPostsAndPages`
- `WPAnalyticsStatStatsItemTappedSearchTerms`
- `WPAnalyticsStatStatsItemTappedSummaryPost`
- `WPAnalyticsStatStatsItemTappedTagsAndCategories`
- `WPAnalyticsStatStatsItemTappedVideoPlays`

The following events required no changes:
- `WPAnalyticsStatStatsAccessed`, still implemented in `BlogDetailsViewController`.
- `WPAnalyticsStatStatsOverviewBarChartTapped`, implemented [previously](https://github.com/wordpress-mobile/WordPress-iOS/pull/11372).

The following event(s) appear to be obsolete, and can be removed via #10975:
- `WPAnalyticsStatStatsTappedBarChart`

### CODE REVIEW

**Comment by stevebaranski** [comment]
Once the [backing PR](https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/205) in `WordPressShared` has been approved, we can initiate a new pod release and update the `Podfile` here to reference a proper version.

**Comment by ScoutHarris** [comment]
Thanks for the details in the description @stevebaranski . That's very helpful!

**Comment by ScoutHarris** [comment]
Hey Steve.

> You can search for the events in post via Tracks Live View.

Are you sure dev tracks go there? I didn't see any. I used the Event Name `wpios_stats%` and only saw the legacy tracks from what appeared to be actual users. I didn't see _any_ dev triggered tracks.

I do see them as `Tracked` in the logs, so I'm going to assume all is good, as I can't imagine why they wouldn't show in Tracks once published.

**Comment by stevebaranski** [comment]
Thanks for the review @ScoutHarris.

> Are you sure dev tracks go there?

Yes, though there is generally some latency. I took the liberty to express the same query for your username, and found some now. Hopefully that provides you some assurance that things are working as expected.



In any case, I'll merge this tomorrow, once I take care of versioning `WordPressShared`.

**Comment by ScoutHarris** [comment]
> Yes, though there is generally some latency.

Ah! Apparently I wasn't patient enough. Thanks!

**Pull request merged**
