### PR TITLE
Fix compiler warning

### PR DESCRIPTION
**Pull request by jklausa**
Fixes n/a

To test:
Verify that the compiler no longer complains about this line.

### CODE REVIEW

**Comment by loremattei** [comment]
Oh, yes, please @nheagy!

**Comment by jklausa** [comment]
@loremattei do you want me to change a target brach or submit a separate PR that’ll cherrypick it against the release brach?

**Comment by loremattei** [comment]
@jklausa changing the target branch to the release branch would be great!  👍 
btw I'm about to merge the release branch back to develop in order to push the new strings to GlotPress, so we'll have the fix on develop as well in minutes.

**Comment by jklausa** [comment]
wow that didn't work out at all

**Comment by jklausa** [comment]
@loremattei i'll open a second PR with this commit cherry-picked, gimme a sec

**Pull request closed without merging**
