### PR TITLE
Prompts: Show Bloganuary modal when Learn more is tapped

### LINKED ISSUE #22127: iOS - Bloganuary Learn More modal
Refs pcdRpT-4FE-p2, E03vXONBSf15iTe6QHh841-fi-0%3A1

Show a modal when the 'Learn more' button is tapped in the Bloganuary dashboard card. We'll show two slightly different versions between those who have the blogging prompts card enabled and disabled.

```[tasklist]
### Tasks
- [ ] Show a modal when learn more is tapped.
- [ ] When Blogging Prompts is enabled, dismiss the modal when the button is tapped.
- [ ] When Blogging Prompts is disabled, enable the feature when the button is tapped.
```

### PR DESCRIPTION
**Pull request by dvdchr**
Addresses #22127
Depends on #22121

This PR adds the Bloganuary modal screen, displays a slightly different variation of text depending on the prompt dashboard card state, and implements the tap action when the primary button is tapped. When the prompt card is disabled, tapping on the button should shortly enable the prompt card on the dashboard.

Note that tracking is excluded from this PR. I'll address them there along with any accessibility issues for both the card and the modal component.

> [!NOTE]
> I added a new local feature flag, `bloganuaryCardDebugOverride`, which aims to simplify testing without changing anything in the code. When this is turned on, the card should always show (except when it's set to hidden from the ellipsis menu). This flag is enabled by default for local and branch test builds, and I'll remove them on the PR that enables the remote feature flag.

## To test

- Launch the Jetpack app.
- Log in with your WP.com account.
- Turn off the prompts dashboard card from the ellipsis menu.
- Tap 'Learn more' on the Bloganuary dashboard card.
- 🔎  Verify that the modal screen is shown.
- 🔎  Verify that the primary button says 'Turn on blogging prompts'. 
- Tap the primary button.
- 🔎 Verify that the modal is dismissed, and the prompts dashboard card now appears.
- Tap 'Learn more' on the Bloganuary dashboard card again.
- 🔎  Verify that the primary button says `Let's go!`.
- Tap the primary button. 
- 🔎 Verify that the modal is dismissed

Please test the modal in portrait / landscape orientations, and in iPad devices.

## Regression Notes
1. Potential unintended areas of impact
Should be none. The modal screen is completely new and doesn't touch any of the existing code.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the changes.

3. What automated tests I added (or what prevented me from doing so)
N/A.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dvdchr** [comment]
### Updated the overlay with the latest design:

• | Prompts card enabled | Prompts card disabled
-|-|-
Light | light_enabled_new | light_disabled_new
Dark | dark_enabled_new | dark_disabled_new

**Review by wargcm — APPROVED** [review]
I found this issue with the menu items on the dashboard:

https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/7bce9bde-3ab3-4eb5-8bd7-1f0af5fc374a

Since you're only calling into a function that enables the card, this appears to be an issue with that. Due to that, I'm going to still approve this. LGTM! 🚢

**Comment by dvdchr** [comment]
Hmm, I'm getting a UI test failure in the test: 

```
testActivityLogCardHeaderNavigation() in DashboardTests

XCTAssertTrue failed - Activity Log card: "The Jetpack connection" activity not displayed. (/usr/local/var/buildkite-agent/builds/MV-MKE-X64-016/automattic/wordpress-ios/WordPress/UITests/Tests/DashboardTests.swift#CharacterRangeLen=0&EndingLineNumber=53&StartingLineNumber=53)
```

It kept failing consistently after rebuilding the CI job. It seems unrelated because this PR doesn't touch any Jetpack-related cards on the dashboard. Will take a look.

**Comment by dvdchr** [comment]
> I found this issue with the menu items on the dashboard

Hmm yes, good catch. However, as you mentioned, it does seem like an issue with how the dashboard handles state changes (perhaps, specifically the menu list component). I'm not able to find a quick and safe resolution for this issue, but this is easily fixable by doing a pull-to-refresh. So I'll hold off on fixing this in this PR to avoid unwanted side effects.

**Review by osullivanchris — APPROVED** [review]
Ah glad we did the new layout - looks a lot better. Small suggestions if time:

- reduce the small print text size to footnote 13, so it doesn't go to 3/4 lines
- dark mode is a little stark. We could change the bullet point text to secondary label in dark mode, and change the fill on the circles to "system background / dark elevated / tertiary"(#3A3A3C) to soften a little.

image

**Comment by dvdchr** [comment]
### Updated dark mode version:

cc: @osullivanchris 

Light mode | Dark mode
-|-
new_new_light_mode | new_new_dark_mode

**Comment by osullivanchris** [comment]
ah that looks great - thanks @dvdchr  🙌

**Comment by dvdchr** [comment]
The UI test [failed 2 cases](https://buildkite.com/automattic/wordpress-ios/builds/18829#018c2627-6825-4daf-95db-871bbb1a3a75):
- `testActivityLogCardHeaderNavigation()` – I tested this locally and it passed. It seems like this test is flaky with a higher rate of failure. This test passed at some earlier point ([CI job here](https://buildkite.com/automattic/wordpress-ios/builds/18797#018c2089-1863-4ab5-9123-baefc2364012)).
- `testScheduledPosts()` – This should be addressed by https://github.com/wordpress-mobile/WordPress-iOS/pull/22135.

**Pull request merged**
