### PR TITLE
Update uses of `accent` color with `primary`, to replace pink with blue

### LINKED ISSUE #15853: [Colors] Replace usages of Pink with equivalent shades of Blue
To ensure that we are up to date with the latest best practices of the [Color Studio palette](https://github.com/Automattic/color-studio/blob/master/CHANGELOG.md), we should replace our current uses of Pink (for links, buttons, etc) with the equivalent shade of the new blue. It should just be a case of replacing it with the equivalent numbered shade of Blue.

We should also take this opportunity to update our color palette asset catalog to use the latest colors. The Color Studio repo contains a builder script that should automatically generate this.

### PR DESCRIPTION
**Pull request by frosty**
Fixes #15853. This PR replaces most uses of the `accent` color (pink) with `primary` (blue). I did consider redefining `accent` to use the blue color, but we still do need to use the pink in a couple of places like stats charts, and keeping a separate accent gives us more flexibility in the future.

As with [Android](https://github.com/wordpress-mobile/WordPress-Android/pull/14376), I've left a few elements using pink:

- Stats bar chart
- Small badges, such as the badge in the Help section of the app that shows the user has a new message, and the unread notifications badge in the tab bar

|   |   |   |   |
|---|---|---|---|
| Simulator Screen Shot - iPhone 12 Pro - 2021-04-01 at 14 11 09  |  Simulator Screen Shot - iPhone 12 Pro - 2021-04-01 at 14 12 03 | Simulator Screen Shot - iPhone 12 Pro - 2021-04-01 at 14 12 22  |  Simulator Screen Shot - iPhone 12 Pro - 2021-04-01 at 14 17 00 |
| Simulator Screen Shot - iPhone 12 Pro - 2021-04-01 at 14 34 08  |  Simulator Screen Shot - iPhone 12 Pro - 2021-04-01 at 14 16 41 | Simulator Screen Shot - iPhone 12 Pro - 2021-03-31 at 20 46 45  |  Simulator Screen Shot - iPhone 12 Pro - 2021-03-31 at 20 45 21 |
|  Simulator Screen Shot - iPhone 12 Pro - 2021-03-31 at 20 44 46 |  Simulator Screen Shot - iPhone 12 Pro - 2021-04-01 at 14 49 06 | Simulator Screen Shot - iPhone 12 Pro - 2021-04-01 at 14 48 50  |  Simulator Screen Shot - iPhone 12 Pro - 2021-04-01 at 14 47 41 |
| Simulator Screen Shot - iPhone 12 Pro - 2021-04-01 at 14 47 28  |   |   |   |

**To test**

- Build and run. Test in light and dark mode.
- Go through the main flows - Login, Create a site, Quick start
- Check the buttons and the links are all blue now
- Check nothing is out of place
- Be cautious about dialogs

**Also**

-  Go to stats with a lot of data
- Go to Year view
- Notice the selected day in the bar chart is still pink
- Scroll to the Countries block
- Notice the countries are now in blue

## Regression Notes
1. Potential unintended areas of impact

The entire app

2. What I did to test those areas of impact (or what existing automated tests I relied on)

I went through the login/create a site flow, smoke tested stats, notifications, comments and other areas of the app

3. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

cc @leandroalonso @momo-ozawa Would one of you mind doing a quick check through the Jetpack build and ensure I haven't messed anything up there?

### CODE REVIEW

**Comment by emilylaguna** [comment]
👋 @frosty I took a quick Jetpack look at this and found it doesn't build because `UIColor.lightAppBarTint` wasn't added to 'UIColor+JetpackColors.swift`. 

I'm not sure if we're going to be adding new colors to this category, but if we do could we also please copy them over to the Jetpack colors file as well? 

Thank you!

**Comment by frosty** [comment]
@emilylaguna Thank you! I just pushed up some fixes that should get this working for Jetpack. Apologies for missing this out!

**Comment by emilylaguna** [comment]
Awesome, thank you! Just a heads up, we recently merged those unified login changes into develop: https://github.com/wordpress-mobile/WordPress-iOS/pull/16201

**Review by mattmiklic — APPROVED** [review]
Everything looks as expected here.

**Review by Gio2018 — APPROVED** [review]
I assume the QuickStart "Grow Your Audience" icon is another element that should stay pink?

In this case :shipit: !

**Comment by mattmiklic** [comment]
> I assume the QuickStart "Grow Your Audience" icon is another element that should stay pink?

Yep, makes sense to leave that one pink.

**Pull request merged**
