### PR TITLE
Post List: Reset action buttons when cell is configured.

### LINKED ISSUE #4999: Post List: Action buttons not properly reset when cell is reused.
There is a small glitch in the post list where the post card's action buttons do not properly reset when the cell is reused.  

To reproduce: 
View the post list for a blog with lots of posts. 
Tap the `More` button in the first post card to reveal its extra options. 
Scroll down the post list until the card is reused.  This may take a bit of scrolling. 
Notice the the reused card will still have its action buttons showing the additional options. 

Props @SergioEstevao for the find.

### PR DESCRIPTION
**Pull request by aerych**
Fixes #4999 

To test: Repeat the steps outlined in the issue and confirm the action buttons are properly reset.

Needs review: @SergioEstevao would you do the honors?

### CODE REVIEW

**Comment by SergioEstevao** [comment]
Hmm, it looks that now you have the issue the other way around, if for example on the first cell you click on the more button, then scroll to the end and the scroll back the cell will forget that the more button was clicked. Is that ok?

**Comment by aerych** [comment]
I think its fine.  If you've tapped the more button to reveal other actions you'll probably complete whatever you were doing then.  If you scroll away it likely means you didn't want to do any of those actions.

**Comment by SergioEstevao** [comment]
:shipit: then.

**Comment by aerych** [comment]
Thanks @SergioEstevao !

**Pull request merged**
