### PR TITLE
Plans: load localized copy from the API

### PR DESCRIPTION
**Pull request by koke**
To test: visit plans with a non-English language/region, make sure the content is localized.

I've included a few changes to `Languages` here to avoid postponing this PR even more (previously on Languages: #5246, #5251, #5252)

Needs review: @frosty

### CODE REVIEW

**Comment by frosty** [comment]
Changes all look good! I just found a couple of things that don't appear to be getting localised:

* Feature titles and descriptions (you've already addressed this)
* The price text (e.g. £79 _per year_) in the plan detail header.

The latter doesn't come from the API, so I'm not sure if you want to fix it in this PR or not? It works on the plans list, but not detail, and it looks like we're just localising it differently ("%@ per year" vs price + "per year").

**Comment by koke** [comment]
I think the price text is localized, but hasn't been translated yet as it's a new string (I see `%@ per year` in the English strings file but not in the translations). We should make those two use the same string though: #5281

**Comment by frosty** [comment]
Okay, let's handle it there. One final thing –  the test `testPlanListRowAttributedTitleWhenNotCurrent()` is broken when the simulator isn't in English ("expected to equal <Title $99 per year>, got <Title $99 al año>").

**Comment by koke** [comment]
> the test testPlanListRowAttributedTitleWhenNotCurrent() is broken when the simulator isn't in English

Added that to #5281. I think I'll have to change how we build the price string for the plans list, so both issues are likely to have the same solution

**Comment by frosty** [comment]
Okay, in that case :shipit:!

**Pull request merged**
