### PR TITLE
Update OCMock

### PR DESCRIPTION
**Pull request by jkmassel**
Updates OCMock to the latest version

To test: Ensure tests pass

## Regression Notes
1. Potential unintended areas of impact
This change only relates to automated testing, so shouldn't affect any user-facing functionality. 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Automated tests can evaluate this change.

3. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by AliSoftware** [comment]
Unit Tests failed with what is indeed related with OCMock (failing to record an invocation), so that CI failure is probably not a fluke but indeed related to the version bump.

```
PushNotificationsManagerTests
  testAuthenticationNotificationIsProperlyHandled, Did not record an invocation in OCMStub/OCMExpect/OCMReject.
  <unknown>:0

  testBackgroundNotificationIsProperlyHandled, Did not record an invocation in OCMStub/OCMExpect/OCMReject.
  <unknown>:0

  testBadgeResetNotificationDoesntAttemptToHandleAnyNotificationKind, Did not record an invocation in OCMVerify.
  <unknown>:0

  testHandleNotificationUpdatesApplicationBadgeNumber, Another mock is already associated with object <UIApplication: 0x7fd044605270> (NSInternalInconsistencyException)
  <unknown>:0

  testInactiveNotificationIsProperlyHandled, Another mock is already associated with object <UIApplication: 0x7fd044605270> (NSInternalInconsistencyException)
  <unknown>:0

  testQuickStartLocalNotificationIsProperlyHandled, Another mock is already associated with object <UIApplication: 0x7fd044605270> (NSInternalInconsistencyException)
  <unknown>:0

  testRegisterForRemoteNotificationsCallsSharedApplicationRegisterForRemoteNotifications, Another mock is already associated with object <UIApplication: 0x7fd044605270> (NSInternalInconsistencyException)
  <unknown>:0

  testZendeskNotificationIsProperlyHandled, Did not record an invocation in OCMStub/OCMExpect/OCMReject.
  <unknown>:0


	 Executed 8 tests, with 8 failures (8 unexpected) in 0.671 (0.676) seconds

2021-05-03 20:10:42.280 xcodebuild[89091:288283] [MT] IDETestOperationsObserverDebug: 78.716 elapsed -- Testing started completed.
2021-05-03 20:10:42.280 xcodebuild[89091:288283] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2021-05-03 20:10:42.280 xcodebuild[89091:288283] [MT] IDETestOperationsObserverDebug: 78.716 sec, +78.716 sec -- end
Failing tests:
	WordPressTest:
		-[PushNotificationsManagerTests testAuthenticationNotificationIsProperlyHandled]
		-[PushNotificationsManagerTests testBackgroundNotificationIsProperlyHandled]
		-[PushNotificationsManagerTests testBadgeResetNotificationDoesntAttemptToHandleAnyNotificationKind]
		-[PushNotificationsManagerTests testHandleNotificationUpdatesApplicationBadgeNumber]
		-[PushNotificationsManagerTests testInactiveNotificationIsProperlyHandled]
		-[PushNotificationsManagerTests testQuickStartLocalNotificationIsProperlyHandled]
		-[PushNotificationsManagerTests testRegisterForRemoteNotificationsCallsSharedApplicationRegisterForRemoteNotifications]
		-[PushNotificationsManagerTests testZendeskNotificationIsProperlyHandled]
```

**Comment by mokagio** [comment]
I wanted to see how the failures looked like on my end, but I can't get past this unrelated (?) error:

image

Has any of you ever seen this? 🤔

**Comment by AliSoftware** [comment]
> Has any of you ever seen this? 🤔

@mokagio Doesn't ring a bell, no. I checked out this branch then ran `rake dependencies` then opened the project in Xcode (it has been quite a while, so indexing was 🔥 😅), then ⌘B, then ⌘U, and didn't see that error you have in the `Pods-Apps-WordPress-resources.sh` in either case (but saw the same test failures as CI though).

I can confirm that I hit the test failures locally; but I won't have time to dig deeper and investigate them today (so just saying that it's reproduced on local builds at least)
image

**Comment by jkmassel** [comment]
Seems like perhaps OCMock did a SemVer oops 😜

I'll try to get back to this soon, for now I'll kick it down the road a sprint or two since we're cutting `17.4` today.

**Comment by jkmassel** [comment]
This isn't currently working – closing to get rid of some spam

**Pull request closed without merging**
