### PR TITLE
Contact Info - Adding Feature Flag + Jetpack API for version check

### PR DESCRIPTION
**Pull request by illusaen**
## Description
Added capabilities in order to determine whether contact info should be shown or not.

See further descriptions in linked PRs:
* `gutenberg-mobile`: [#3001](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3001)
* `gutenberg`: [#28168](https://github.com/WordPress/gutenberg/pull/28168)
* `WPAndroid`: [#13758](https://github.com/wordpress-mobile/WordPress-Android/pull/13758)

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
👋 Howdy! We are cutting the `16.6` release today.

Because of that, this PR will be bumped to `16.7`. If you need it to be part of `16.6`, please merge it into the `release/16.6` branch and DM me – I'll be happy to cut a new beta release!

**Comment by illusaen** [comment]
See https://github.com/wordpress-mobile/gutenberg-mobile/issues/3064 for issue coming up with contact info block itself.

**Comment by jkmassel** [comment]
👋 We're freezing `16.7` today, so this PR is being bumped to `16.8`. If you need this to be part of the `16.7` release, please merge it into the `release/16.7` branch and DM me – I'll be happy to cut a new beta release!

**Comment by cameronvoell** [comment]
Hey @illusaen I wasn't able to verify the functionality using the WPiOS build from this PR. Digging a little ([comment here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3001#issuecomment-775727798)), I'm guessing maybe this feature is still DEV only so the only way to test is to run while connected to metro bundler locally. Can you confirm?

While testing locally with metro the feature seemed to be working correctly, I just want to ensure that this is what we intended.

**Comment by illusaen** [comment]
> Hey @illusaen I wasn't able to verify the functionality using the WPiOS build from this PR. Digging a little ([comment here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3001#issuecomment-775727798)), I'm guessing maybe this feature is still DEV only so the only way to test is to run while connected to metro bundler locally. Can you confirm?
> 
> While testing locally with metro the feature seemed to be working correctly, I just want to ensure that this is what we intended.

@cameronvoell Yes that's correct! I haven't removed the DEV flag yet because there's still a keyboard bug that needs to be fixed first.

**Review by cameronvoell — APPROVED** [review]
Tested successfully with emulator connected to my local bundler. I confirmed a jurassic ninja site with jetpack enabled showed the contact info block, and no jetpack did not show the block. I also had an old version of jetpack on one site that also correctly did not show the contact info block available. This should be good to go once we update podfile, etc.

**Comment by jkmassel** [comment]
👋 We're freezing `16.8` today, so this PR is being bumped to `16.9`. If you need this to be part of the `16.8` release, please merge it into the `release/16.8` branch and DM me – I'll be happy to cut a new beta release!

**Comment by jkmassel** [comment]
We've pushed this out from several releases, so I'm moving this to the `someday` milestone 😃

**Comment by illusaen** [comment]
> We've pushed this out from several releases, so I'm moving this to the `someday` milestone 😃

Lol yes, been doing my different rotations, sorry!

**Pull request merged**
