### PR TITLE
Minor improvements to Siri Shortcuts experience

### LINKED ISSUE #10544: Siri Shortcuts : Improvements
During a recent App Store submission, we were asked for clarification regarding the introduction of Siri Shortcuts. This exposed some potential improvements to the existing experience, including:

- Ensure that existing `NSUserActivityTypes` are cited in the app's `Info.plist`, as prescribed [here](https://developer.apple.com/documentation/foundation/nsuseractivity).
- Ensure that `NSUserActivity` types donated for Siri Shortcuts can be deleted by the user, as suggested [here](https://developer.apple.com/documentation/sirikit/deleting_donated_shortcuts).

At a later date, we might consider an in-app UI for users to more actively manage these shortcuts. Because of the complexity, that kind of improvement should be considered separately. iOS offers a few alternatives for [managing shortcuts](https://developer.apple.com/design/human-interface-guidelines/sirikit/overview/siri-shortcuts/) that we should evaluate.

### PR DESCRIPTION
**Pull request by stevebaranski**
### Description 
Fixes #10544.

### Testing

- Checkout the branch and verify that existing test pass.
- For context, it may be helpful to refer to these [prior instructions](https://github.com/wordpress-mobile/WordPress-iOS/pull/10225)
- Navigate to _Me : App Settings_ & confirm that the new settings appear as shown below.
- Verify that the new button works.

### Screenshot(s)
pr

### CODE REVIEW

**Comment by stevebaranski** [comment]
@bummytime if you have a free moment, would you be willing to review this as well?

**Comment by koke** [comment]
Until I read the doc linked in the issue, I would have had no idea what "Siri Activity Donations" meant, it sounds like Siri is raising funds 😂 Would "Clear Siri Shortcuts" still be accurate?

**Comment by stevebaranski** [comment]
@iamthomasbishop after I reached out to you via Slack yesterday, I neglected to add the `[Status] Needs Design Review` tag to this PR. 

@koke raises a good point about the copy on the new button, which is privacy-motivated. I agree that "donations" doesn't sound so user-friendly. What do you think about `Clear Siri Shortcuts` or `Clear Suggested Siri Shortcuts`?

**Comment by stevebaranski** [comment]
@iamthomasbishop thank you!

As a user interacts with the app, we "donate" these [activities](https://github.com/wordpress-mobile/WordPress-iOS/pull/10225) to Siri. In turn, these appear as "Suggested Shortcuts" in _Settings : WordPress : Siri & Search.

This button clears the history of those suggestions, just giving the user a bit of assurance that we respect his/her privacy. That is to say, these won't appear as suggestions unless or until the user performs those actions again.

Sound good?

**Comment by iamthomasbishop** [comment]
Ah ok that makes sense. Thanks for clarifying!

**Comment by stevebaranski** [comment]
I have updated the copy and conferred with @ctarda regarding a question he had. We've agreed that once build checks pass, this PR is ready to be merged.

**Pull request merged**
