### PR TITLE
Blogging Prompts: Configure prompt card bottom row for answered state

### PR DESCRIPTION
**Pull request by dvdchr**
Refs #18250

This adds the UI for the prompt card's bottom row when the prompt has been answered. Some screenshots:

• | Portrait | Landscape
--|--|--
iPhone 11 Pro Max | iphone_portrait | iphone_landscape
iPad | ipad_portrait | ipad_landscape

Other notes:
- Also added basic accessibility support, but there's still an unhandled case when using the largest accessibility sizes, where the "answered" label and the Share button fight for horizontal space 😅 . I'll note this for the accessibility review round.
- For testing purposes, tapping on the ellipsis menu now toggles between the prompt card's answered state. This will be removed in the next PR.
- The Share button's tap action is not yet implemented.

## To test

- Ensure that the Blogging Prompts and My Site Dashboard feature flags are enabled.
- Tap on the ellipsis menu to toggle the card into an "answered" state.
- Verify that the Answered label and the Share button are displayed correctly.

## Regression Notes
1. Potential unintended areas of impact
n/a. Feature under development.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a. Feature under development.

3. What automated tests I added (or what prevented me from doing so)
n/a. Feature under development.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
> still an unhandled case when using the largest accessibility sizes, where the "answered" label and the Share button fight for horizontal space

👍 . Also, just wanted to point out, if it's not already on your list, the `Share` button doesn't resize with text. 

Screen Shot 2022-04-01 at 2 06 25 PM

**Comment by ScoutHarris** [comment]
> tapping on the ellipsis menu now toggles between the prompt card's answered state

Well that was handy! 😄

**Review by ScoutHarris — APPROVED** [review]
LGTM!

**Comment by mokagio** [comment]
Note that the Jetpack installable build is failing here. See [my comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/18251#pullrequestreview-929723124) on #18251, since this PR is based off that and the failure was introduced there (as far as I can see).

@ScoutHarris approved this PR, but I'd like to suggest to:

1. Fix the issue in #18251
2. Merge #18251 (likely into `release/19.6`) given today is code freeze day
3. Change the base for this PR to `release/19.6` (Assuming GitHub doesn't do it automatically, I'm not sure how it behaves when the base branch doesn't land into `trunk`. I guess we'll find out)
4. Verify CI is all green here after those changes
5. Merge this one, too
6. (Likely ship a new beta)

**Pull request merged**
