### PR TITLE
Refactor WPUserAgent

### PR DESCRIPTION
**Pull request by SergioEstevao**
Refactor WPUserAgent to use static methods that are thread safe and invoked once.

To test: 
 - Run unit tests see if they are correct.
 - Run the app on the simulator using a Charles or similar program and see if the user agent is correct.

Needs review: @koke, @astralbodies and @aerych mind to have a look?

### CODE REVIEW

**Comment by SergioEstevao** [comment]
Just some extra detail on the issues I found with the original implementation:

 - The original methods if they where called outside the main thread they will crash because of the use of the UIWebView.
 - Every time that the class WPUserAgent was created and used, that involved a creation of a UIWebView, that isn't one of the most lightweight classes.
 - The original code to get the default user agent have this snippet here:
```
    // Temporarily unset "UserAgent" from registered user defaults so that we
    // always get the default value, independently from what's currently set as
     // User-Agent
    NSDictionary *originalRegisteredDefaults = [[NSUserDefaults standardUserDefaults] volatileDomainForName:NSRegistrationDomain];

    NSMutableDictionary *tempRegisteredDefaults = [NSMutableDictionary dictionaryWithDictionary:originalRegisteredDefaults];
    [tempRegisteredDefaults removeObjectForKey:WPUserAgentKeyUserAgent];
    [[NSUserDefaults standardUserDefaults] registerDefaults:tempRegisteredDefaults];
```
I don't know if this worked on previous version of iOS but on my tests on iOS 9 this didn't restore the user agent for it's original default value. What I found out it's to do it correctly we need to use this code:

```
 [[NSUserDefaults standardUserDefaults] registerDefaults:@{WPUserAgentKeyUserAgent:@(0)}];
```

**Comment by aerych** [comment]
Hi @SergioEstevao 
Changes look good to me. Tests pass and I've confirmed via Charles the WP useragent is sent.
:shipit: from me.

**Comment by astralbodies** [comment]
I've always wondered - when we call `registerDefaults` we're not persisting these to disk. Is that what we want or should they be persisted along with the standard user defaults?

**Comment by SergioEstevao** [comment]
Register defaults are not persisted to disk ever, they are the defaults values if you don't set any value explicitly to NSUSerDefaults.

And for the webview to grab the value you need to do the register defaults if you just set the NSUserDefaults by doing setObject:ForKey and save that value will not get grabbed by the UIWebView.

**Comment by astralbodies** [comment]
Oh right, I understood they aren't persisted to disk; meant to just say they aren't persisted - is that okay - sort of thing.

Seems to work fine so why change 😛. :shipit:

**Pull request merged**
