### PR TITLE
Merge beta 26.1.0.2 into `trunk` with conflicts resolution

### PR DESCRIPTION
**Pull request by mokagio**
Conflicts on `Podfile.lock` because the `Podfile` changed in both `trunk` and `release/21.6`, resulting in the lockfile checksum conflicting. Addressed by re-running `bundle exec pod install` to generate an up-to-date checksum

## Includes

- [Gutenberg mobile 1.87.3](https://github.com/wordpress-mobile/WordPress-iOS/pull/20026) by @fluiddot 
- [Show stats insights changes prompt in alert and not actionSheet on iPad](https://github.com/wordpress-mobile/WordPress-iOS/pull/20013) by @staskus 

Also, already merged in `trunk` but shipped with this beta:

- [Fix crash after backgrounding app from Stats screen](https://github.com/wordpress-mobile/WordPress-iOS/pull/20008) by @staskus 
- [Fix Total cards show "higher" word instead of "lower" label](https://github.com/wordpress-mobile/WordPress-iOS/pull/20000) by @staskus 

## Release checks

- [x] Updates to the localization files (`.strings` and Fastlane metadata) automatically pulled for the new translations that have already been approved in GlotPress
- [x] Version update in `.xcconfig`
- [x] Diffs from the PRs that made it into this beta

### CODE REVIEW

**Comment by mokagio** [comment]
@spencertransier @JB184351 @lmischner, sorry for the spam. I selected the `@platform9` group for review by mistake.

**Comment by fluiddot** [comment]
@mokagio Heads up that I've just merged a PR that updated the Gutenberg Mobile reference, the latest tag and the one to use for solving the conflict is: `v1.88.0-alpha1`. Today we'll create a new Gutenberg Mobile version so the reference will point to `v1.88.0` once we integrate it into `trunk`. Not sure if this PR will be merged before or after the new version, but wanted to let you know in case it produces another conflict. If that's the case, we should solve the conflict with the tag `v1.88.0`. Thanks!

**Comment by mokagio** [comment]
Thanks for the ping @fluiddot .

**Comment by mokagio** [comment]
Superseded by #20062

**Pull request closed without merging**
