### PR TITLE
Custom icons: add upgrade alert

### PR DESCRIPTION
**Pull request by frosty**
This PR adds an alert informing users about the new custom icons we've added to the app. The alert will be displayed under the following conditions:

- The user already has a custom icon set
- We haven't already shown the alert
- The app supports custom app icons (Jetpack doesn't, WordPress does)

I also ensured that the alert won't be shown to a user who selects a custom icon for the first time and returns to the My Site screen.

**To test**

**Scenario 1**

- Build and run `develop`, and ensure you don't have a custom icon selected
- Build and run this branch, and check that you don't see the new alert on the My Site screen
- Head to Me > App Settings > App Icon and select an icon
- Navigate back to My Site and check that you still don't see the alert

**Scenario 2**
- Build and run `develop`, and select a custom icon from Me > App Settings > App Icon
- Build and run this branch, and check that you see the new alert on the My Site screen
- Tap Keep my current app con – nothing should happen except the alert should be dismissed
- Re-test and tap Choose a new app icon and check that you are presented with the icon picker
- Ensure if you navigate away from My Site and back again that you're not shown the alert a second time

**Scenario 3**
- Ensure that existing fancy alerts with a border style of `top` aren't changed by:
- Logging out
- Tapping Enter my existing site address
- Tapping Find your site address
- Check the alert looks fine

## Regression Notes
1. Potential unintended areas of impact

- The alert being shown multiple times
- The appearance of existing alerts being changed

2. What I did to test those areas of impact (or what existing automated tests I relied on)

I ensured I tested these situations.

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mattmiklic** [comment]
I wasn't able to test the alert live; when I installed the build via App Center, I couldn't get it to appear for me. The instructions above mention building develop first, so I'm wondering if that's why I don't see it via the App Center build. If there's steps I can take to see it live I'd love to! But the screenshot looks good to me.

**Comment by frosty** [comment]
@mattmiklic You could try installing a one-off App Center build for a different branch first – one that won't contain these changes. Then in that build, select a custom icon. Then install this build over the top. I think that should do it.

**Review by Gio2018 — COMMENTED** [review]
Scenario 1 and 2 worked well! I also tested scenario 2 with a version that has feature announcements: the icon alert shows and the feature announcement does not show on My Site, but it will show up when navigating to another tab, which I think it's acceptable considering that we don't have feature announcements in the upcoming release and this alert will be removed after a couple of releases.

For scenario 3, see my comment [here](https://github.com/wordpress-mobile/WordPressUI-iOS/pull/85#pullrequestreview-637997126): maybe this is expected?

**Review by mattmiklic — APPROVED** [review]
Thanks for the tip, that worked! Everything looks good.

**Review by Gio2018 — APPROVED** [review]
The issue with the alert is fixed now. LGTM!

**Pull request merged**
