### PR TITLE
Add mobile and tablet screenshots in previews and thumbnails

### LINKED ISSUE #2978: [Layout Switching] Add mobile/tablet/desktop thumbnails in HPP design selection screen
## Description
The HPP design selection screen should be enhanced by adding the ability to select between mobile(default) and desktop thumbnails.
The HPP API call should be enhanced to provide the mobile and tablet thumbnail urls.

<image width="360" src="https://user-images.githubusercontent.com/304044/103789359-96096e80-5048-11eb-84aa-4450a608ed15.png"/>

## Goals
* The HPP design selection screen displays a thumbnail mode icon.
* When the icon is pressed a popup appears with “Desktop”, “Tablet”, “Phone”options.
* The “Default” “Phone” option shows the mobile thumbnails and loads on first launch.
* The “Tablet” option switches to a tablet thumbnail mode.
* The “Desktop” option switches to a desktop thumbnail mode.

## Additional context
This issue is part of the [Layout Switching project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Layout%20Switching)

### PR DESCRIPTION
**Pull request by mkevins**
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2978, https://github.com/wordpress-mobile/gutenberg-mobile/issues/2977

#### Related PR

`WordPressKit-iOS`: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/330

### Description

This PR adds mobile and tablet previews and thumbnails to the site design steps, and also adds the same options in the post editor preview.

### Testing steps

<details>
<summary><strong>To start the Home Page Picker screen</strong></summary>

1. Start the site creation flow (e.g. *Choose site > Add button*)
1. Select the *Create WordPress.com site* option
</details>

### Site design thumbnails

<details>
<summary>Tests</summary>

#### Initial Mode on a Phone
1. Start the Home Page Picker on a phone
1. **Verify** that **mobile** thumbnails are displayed

#### Initial Mode on a Tablet
1. Start the Home Page Picker on a tablet
1.  **Verify** that **tablet** thumbnails are displayed

#### Thumbnail options availability
1. Start the Home Page Picker on a phone
1.  **Verify** that there is a **thumbnail button** at the left of skip
1. Press the thumbnail button
1.  **Verify** that three options are displayed: **Mobile, Tablet, Desktop**

#### Change to Tablet
1. Start the Home Page Picker on a phone
1. Press the thumbnail button (at the left of skip)
1. Select **Tablet**
1.  **Verify** that tablet thumbnails are displayed

#### Change to Desktop
1. Start the Home Page Picker on a phone
1. Press the thumbnail button (at the left of skip)
1. Select **Desktop**
1.  **Verify** that desktop thumbnails are displayed

#### Change to Mobile
1. Start the Home Page Picker on a phone
1. **Change to Desktop** as above
1. Press the thumbnail button (at the left of skip)
1. Select **Mobile**
1.  **Verify** that mobile thumbnails are displayed
</details>

### Site design previews

<details>
<summary>Tests</summary>

#### Preview options availability
1. Start the Home Page Picker
1. Select a design
1. Press the **Preview** button
1. **Verify** that there is a preview mode button at the top right of the screen
1. Press the **preview mode button**
1. Verify that three options are displayed: Mobile, Tablet, Desktop

#### Mobile preview
1. Start the Home Page Picker
1. Select a design
1. Press the **Preview** button
1. Press the **preview mode button**
1. Select **Mobile**
1. **Verify** that a mobile preview is displayed

#### Tablet preview
1. Start the Home Page Picker
1. Select a design
1. Press the **Preview** button
1. Press the **preview mode button**
1. Select **Tablet**
1. **Verify** that a tablet preview is displayed

#### Desktop preview
1. Start the Home Page Picker
1. Select a design
1. Press the **Preview** button
1. Press the **preview mode button**
1. Select **Desktop**
1. **Verify** that a desktop preview is displayed

</details>

### Mode between steps

<details>
<summary>Tests</summary>

#### Change mode on the preview screen

1. Start the Home Page Picker on a phone
1. Select a design
1. Press the **Preview** button
1. Press the preview mode button
1. Select **Desktop**
1. **Verify** that desktop mode is displayed
1. Close the preview screen (back or swipe down)
1. **Verify** that desktop thumbnails are displayed

#### Change mode from the design screen
1. Start the Home Page Picker on a phone
1. Press the preview mode button
1. Select **Desktop**
1. Select a design
1. Press the **Preview** button
1. **Verify** that a desktop preview is displayed
</details>

### Preview in the editor

<details>
<summary>Tests</summary>

#### Opening the editor preview

1. Open a post in the editor
2. Tap the post menu button (upper right corner)
3. Tap "Preview"

#### Initial Mode on a Phone
1. Start the editor preview on a phone
1. **Verify** that **mobile** preview is displayed

#### Initial Mode on a Tablet
1. Start the editor preview on a tablet
1.  **Verify** that **tablet** preview is displayed

#### Change modes in the editor on a phone

1. Try mobile, tablet, and desktop preview modes
2. Verify that the previews are displayed correctly

#### Change modes in the editor on a tablet

1. Try mobile, tablet, and desktop preview modes
2. Verify that the previews are displayed correctly
3. The phone preview should not be full-width on a tablet

</details>

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by antonis — CHANGES_REQUESTED** [review]
Great work @mkevins 👍 
This PR actually resolves three issues: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2978, https://github.com/wordpress-mobile/gutenberg-mobile/issues/2977 and part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/3009 🎉 

I tested on an iPhone SE 2020 with iOS 14.2 and on iPad simulator and the app behaves as expected 👍 
The code is consistent and LGTM 🎉 

* I notice a minor issue (probably unrelated with this PR). When you open the **preview** and get back the **selection overlay** is missing. I feel that this is the only thing that would be nice to be resolved before merging.

https://user-images.githubusercontent.com/304044/105506556-dddbf700-5cd2-11eb-8915-f1c494c8fba1.mov

* On Android I used a preview mode indication (at the bottom right corner) on the HPP preview screen but I don't think it is necessary

* Regarding the code duplication in the popover delegate methods we discussed, I don't see an easy way to avoid it. I made a [draft attempt to extract the logic in a separate class](https://gist.github.com/antonis/cdb9d0b2d20b83fa09ae35477674eb37) but I feel it gets too complicated and does not worth it.

**Comment by mkevins** [comment]
> * I notice a minor issue (probably unrelated with this PR). When you open the **preview** and get back the **selection overlay** is missing. I feel that this is the only thing that would be nice to be resolved before merging.

Good catch Antonis! This was happening when the `collectionView` was reloaded (the selection was lost). It also happened when changing the device. I've pushed an update to address it.

Also, previously, the content collection view was not updating to the device mode selected in the preview screen when the preview was dismissed by swiping down. It only updated when tapping the close button. I've pushed changes to address this as well. Thanks for reviewing and testing! Ready for another look.

**Comment by antonis** [comment]
Hello @mkevins 👋 

> Good catch Antonis! This was happening when the `collectionView` was reloaded (the selection was lost). It also happened when changing the device. I've pushed an update to address it.

Thank you for looking into this. I noticed a minor related issue with the checkmark disappearing after the re-selection of the design. 

https://user-images.githubusercontent.com/304044/105675839-5967bf00-5ef2-11eb-99be-979466ddd7b7.mov

I think this might be some kind of synchronisation issue between animations. Setting the `animate=false` [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/a3c9668b53621f26d9f555b4b49cef177e404bbf/WordPress/Classes/ViewRelated/Gutenberg/Collapsable%20Header/Collapsable%20Header%20Collection%20View%20Cell/CollapsableHeaderCollectionViewCell.swift#L62) seems to make this work 🤷

**Comment by jkmassel** [comment]
👋 Howdy! We are cutting the `16.6` release today.

Because of that, this PR will be bumped to `16.7`. If you need it to be part of `16.6`, please merge it into the `release/16.6` branch and DM me – I'll be happy to cut a new beta release!

**Comment by mkevins** [comment]
> Setting the `animate=false` [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/a3c9668b53621f26d9f555b4b49cef177e404bbf/WordPress/Classes/ViewRelated/Gutenberg/Collapsable%20Header/Collapsable%20Header%20Collection%20View%20Cell/CollapsableHeaderCollectionViewCell.swift#L62) seems to make this work

You are right that there was a synchronization issue. I didn't encounter it at first, but after trying a few times, I observed the same. The animation completion for the checkmark is setting "stale" values for `isHidden`, which should be `!isSelected`. I was able to fix this missing checkmark by making the animation completion reference the _current_ selection state, that way the animations can still be enabled: (https://github.com/wordpress-mobile/WordPress-iOS/pull/15688/commits/f5631385e9b59f39aa4f451449f9cf416c0531b8).

Thanks for reviewing again. Ready for another look. :smile:

**Review by antonis — APPROVED** [review]
Hey @mkevins 👋 
Thank you for the fix 🙇 
I tested it on an iPhone SE 2020 (iOS 14.2) and everything works as expected 🎉

**Comment by mkevins** [comment]
Thank you Antonis for reviewing and testing. :smile:

**Pull request merged**
