### PR TITLE
Prevent Homepage from being deleted or moved to a draft

### LINKED ISSUE #15729: User can delete Homepage and break their site
### Description
It is possible to delete your Homepage while it's set as your static Homepage. This is a feature that is disabled on dotCom. If a user does delete their Homepage then their site will render with an error when you navigate there. 

### Steps to reproduce the behavior
**_Setup:_** Set your site's Homepage settings to use a Static Homepage

1. Navigate to pages
2. Tap the `...` 
3. Tap `Move to Trash`

##### Tested on iPhone 11, iOS 13.5, WPiOS 16.6

Android ticket: https://github.com/wordpress-mobile/WordPress-Android/issues/13908

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes:** https://github.com/wordpress-mobile/WordPress-iOS/issues/15729

## To test:
📓 Make sure your site is set to have a Static Homepage

### Attempt to delete Homepage
1. Navigate to the Page List 
2. Select the `...` on the Homepage
3. **Expect** to _NOT_ see the `Move to Trash` option
📓 If the Homepage has been moved out of the Published filter then the `Move to Trash` option will still be there. The site is already broken so no reason to restrict it.

<details>
<summary>Screenshot</summary>
<kbd><a href="https://user-images.githubusercontent.com/3384451/107688732-f6a64f80-6c75-11eb-8fc3-eab8980cf9fd.png"></a></kbd>
</details>

### Attempt to move Homepage to Draft - Page List
📓 This doesn't apply if you've trashed your Homepage.

1. Navigate to the Page List 
2. Select the `...` on the Homepage
3. **Expect** to NOT see the  `Move to Draft` 

<details>
<summary> Screenshot</summary>
<kbd><a href="https://user-images.githubusercontent.com/3384451/107688732-f6a64f80-6c75-11eb-8fc3-eab8980cf9fd.png"></a></kbd>
</details>

### Attempt to move Homepage to Draft - Page Settings
📓 This doesn't apply if you've trashed your Homepage.
1. Navigate to the Page List 
2. Select Homepage to open the Editor
3. Select the `...` in the top right-hand corner
4. Select `Page Settings`
5. Select `Status`
6. **Expect** to only have the Publish option.

<details>
<summary> Screenshot</summary>
<kbd><a href="https://user-images.githubusercontent.com/3384451/107691816-eee8aa00-6c79-11eb-901f-dd0b489ae164.png"></a></kbd>
</details>

### Attempt to delete Page
1. Navigate to the Page List 
2. Select the `...` on a page that is not the Homepage
3. **Expect** to see the `Move to Trash` option
4. Select `Move to Trash` 
5. **Expect** for the page to be deleted

### Attempt to move Page to Draft - Page List
1. Navigate to the Page List 
2. Select the `...` on a page that is not the Homepage
3. Select `Move to Draft` 
4. **Expect** to see the page be moved to a draft.

### Attempt to move Page to Draft - Page Settings
1. Navigate to the Page List 
2. Select a page (not Homepage) to open the Editor
3. Select the `...` in the top right-hand corner
4. Select `Page Settings`
5. Select `Status`
6. Change the status
7. **Expect** to see the screen to dismiss and the page will modify to the new status.

## PR submission checklist:
- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Discovered issues
- You can set your homepage to be a draft page in static homepage settings
- Homepage picker says "Choose Posts Page"

### CODE REVIEW

**Comment by chipsnyder** [comment]
@iamthomasbishop I picked up this issue to help out and because I had some bandwidth for a quick task. I was wondering if I could get your input on my approach for preventing moving Homepages to a draft state (effectively breaking the site).

I decided to allow it, because dotCom does, and then just pop an alert. WDYT? (or if there is someone better to ping let me know)



cc @yaelirub

**Comment by chipsnyder** [comment]
@kyleaparker you probably also have good feedback on my design attempt (https://github.com/wordpress-mobile/WordPress-iOS/pull/15797#issuecomment-773642868).

**Comment by kyleaparker** [comment]
> I decided to allow it, because dotCom does, and then just pop an alert. WDYT? (or if there is someone better to ping let me know)

I don't see an option to delete the homepage on .com, where do you see this? 

I think it would be better if we don't allow this, every site needs to have a homepage and I'm not sure what the case would be for needing to delete it. If you want to create a new homepage, you can create a new page, reassign the homepage, and then delete the existing homepage.

**Comment by chipsnyder** [comment]
> I don't see an option to delete the homepage on .com, where do you see this?

@kyleaparker This PR actually takes care of two issues (so maybe it's better to split it to separate ones).

The first is to match dotCom and prevent deleting the HomePage. This [build](https://github.com/wordpress-mobile/WordPress-iOS/pull/15797#issuecomment-773640969) removes the delete option in the app so we're on the same page there 👍 

While working on this though I noticed you can also convert your Homepage to a draft (which should also be restricted or removed in my opinion.) However, this is currently allowed in the editor on dotCom. This is where I added the Alert although I am in favor of removing this option instead. WDYT?

**Comment by kyleaparker** [comment]
> The first is to match dotCom and prevent deleting the HomePage. This build removes the delete option in the app so we're on the same page there 👍

Ok perfect 👌 

>While working on this though I noticed you can also convert your Homepage to a draft (which should also be restricted or removed in my opinion.) However, this is currently allowed in the editor on dotCom. This is where I added the Alert although I am in favor of removing this option instead. WDYT?

I think it would be fine to remove this option, especially if doing so breaks the site

**Comment by chipsnyder** [comment]
> I think it would be fine to remove this option, especially if doing so breaks the site

Sounds good to me. Thanks @kyleaparker!

**Review by antonis — APPROVED** [review]
Great work @chipsnyder 👍 
Tested on an iPhone SE 2020 and the app behaves as expected! The code changes LGTM 🎉

**Pull request merged**
