### PR TITLE
Manually fixed French translation to prevent crash in stats

### LINKED ISSUE #4602: Insights in Stats Crashes with French Locales
There is a translation error in a string used in the Insights screen. This is causing a crash for French users of the application when the screen is shown. It doesn't crash in every case but for some users its consistent. 

Crash reports: http://crashes.to/s/66bf19ed103

### PR DESCRIPTION
**Pull request by astralbodies**
Fixes #4602 

Updates the translation for a string in Stats Insights that was crashing the app. I couldn't get my own test to cause the app to crash but I could visually see the corrupted strings being generated by referencing the NSString as a C-String. 

Sorry for the delay on the PR - I know we probably won't make it to the App Store in time for the holiday shutdown.

Needs Review: @sendhil

### CODE REVIEW

**Comment by astralbodies** [comment]
@sendhil I don't think we are doing a 5.8.1 to address this are we?

**Comment by sendhil** [comment]
@astralbodies no - 5.9 is almost out the door...

**Comment by sendhil** [comment]
@astralbodies lets just hold off until then.

**Comment by astralbodies** [comment]
@sendhil That's cool - I had fixed the translation in GlotPress so it'll be naturally fixed in 5.9

**Pull request closed without merging**
