### PR TITLE
Decoupling Authentication Flow: Mark VII

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details: 
We're attacking few technical debt tasks
- **BlogSyncFacade** and **LoginFacade** got Nullability Specifiers
- Updated **BlogSyncFacade**'s api, and simplified things a little bit.
- Removed several **ImplicitlyUnwrappedOptionals** that are not needed.
- Moved all of the **LoginFields** validation routines, from WordPressAuthenticator over **LoginFields+Validation**.
- Moved all of the **SafariCredentials** helpers over to **SafariCredentialsService**
- Moved the **NSNotification.Name** extension (contained within **WordPressAuthenticator.swift** to it's very own file).
- And, of course, updated the Unit Tests accordingly.

Needs Review: @nheagy 

### Testing:
This PR does not introduce new logic, but reorganizes several Authentication snippets into different containers. Please: run a smoke test over the login flows:

1. Log into a Self Hosted Site
2. Log into a Dotcom account, with the following variations:
   1.  No 2FA / No Social Auth
   2.  No 2FA / Social Login
   3.  2FA Protected / No Social Auth
   4.  2FA Protected / Social Auth

### CODE REVIEW

**Comment by nheagy** [comment]
Just a note-to-self: testing should also include signups, as `loginFields` is used for both.

**Comment by jleandroperez** [comment]
Thanks a lot for the review @nheagy!!. All feedback addressed, ready for another peek!.

**Comment by nheagy** [comment]
Nice! :shipit:

**Comment by jleandroperez** [comment]
Thanks Nate, muuuch appreciated!!

**Pull request merged**
