### PR TITLE
Re-implement building page tree hierarchy

### LINKED ISSUE #22283: Pages are not displayed in a hierarchy
Reported by user [here](https://a8c.slack.com/archives/C04HB8JU78A/p1703315190170519), and I confirmed it on my site that I used for testing pages hierarchy.

Screenshot 2023-12-23 at 9 35 14 AM 

Screenshot 2023-12-23 at 9 35 27 AM

### PR DESCRIPTION
**Pull request by crazytonyli**
Fixes #22283. This PR is a follow-up of #22338.

While working on the issue yesterday, probably due to having a holiday break which made me look back at the implementation, I realised that I had over-engineered the implementation and made it unnecessarily complicated.

There is a big undocumented intention of using and maintaining a `PageTree` struct. I thought it'd be nice to use a `PageTree` struct instance throughout the lifecyle of the Pages List, where we can add/remove pages to the instance as new pages are loaded from the server or when user deletes a page. That's why I didn't go with a pure function that turns a list of pages into another lists of pages.

But since we are really hold onto `PageTree` struct instances in the view controller, and I don't foresee we are going to do that in any time soon, I decided to scratch the implementation and re-implementing using a pure function, which only has 30 lines of code and is pretty easy to read.

Also, the new algorithm is much faster (about x3 times faster) and has 0(n) time complexity, because it builds an index of parent-child page before assembling them into a tree.

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Verified #22283

3. What automated tests I added (or what prevented me from doing so)
A few unit tests.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist: N/A

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/265">24.0 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by crazytonyli** [comment]
> Note that these changes won't affect the final version of the release notes as this version is in code freeze.
> Please, get in touch with a release manager if you want to update the final release notes.

@mokagio , this PR targets 24.0 and I think it may be worthy while to update the release notes to include this bug fix?

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/265">24.0 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by mokagio — APPROVED** [review]
Screenshot 2024-01-09 at 12 07 00

👏

**Comment by mokagio** [comment]
> @mokagio , this PR targets 24.0 and I think it may be worthy while to update the release notes to include this bug fix?

Sure. We're in luck in that the release notes haven't been sent to editorialization yet, so anything goes 😄

**Pull request merged**
