### PR TITLE
Remove stats from Core Data

### PR DESCRIPTION
**Pull request by kean**
Related #20773

More details in https://github.com/wordpress-mobile/WordPress-iOS/pull/21067

This PR removes stats from Core Data. The cache is not stored outside of Core Data

## To Test

- Install the previous production release version
- Browse the Stats (both the Insights and the stats be periods)
- Upgrade to the version form this PR
- Verify that the migration is performed and the app continues to work

I used a DB browser to confirm that the tables were removed. There were only two: `ZSTATSRECORD` and `ZSTATSRECORDVALUE` (one table containing all columns for all the stats record subclasses).

## Regression Notes
1. Potential unintended areas of impact: Core Data store
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual test
3. What automated tests I added (or what prevented me from doing so) n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by staskus — COMMENTED** [review]
👍

- Confirmed that migration is happening
- Confirmed that db does not contain StatsRecord and StatsRecordValue
- Confirmed that updating App Store version to this version on the device works fine as well

There're some failures in tests, they possibly need to be removed, not sure if they can still be updated to bring some value

**Comment by kean** [comment]
> There're some failures in tests

Great, more code to remove. I pushed the change; these tests were covering conversion to and from Core Data.

**Review by staskus — APPROVED** [review]

**Comment by kean** [comment]
@crazytonyli, I would appreciate your review as well before we merge this, just to make sure I haven't missed anything when it comes to migration. I added a new model (152), set it as the current model, and updated the migration notes.

**Review by crazytonyli — APPROVED** [review]
I have never changed the data model. I'm not aware of anything special we need to do around data migration. The changes looks good though.

**Comment by kean** [comment]
OK, merging it 😰

**Pull request merged**
