### PR TITLE
Issue/5184 Display current plan title

### LINKED ISSUE #5184: Plans: Display current plan title in BlogDetailsViewController
As part of #5181, we removed the existing functionality to display the site's current plan title on the Plans cell in `BlogDetailsViewController`. We should reinstate this functionality by fetching the plan title from the server.

### PR DESCRIPTION
**Pull request by frosty**
Closes #5184. This PR adds a `planTitle` property to `Blog`, and populates it when sites are updated. 

To test: verify that the correct plan title is displayed on the Plans cell for various sites.

Needs review: @koke @astralbodies (would you mind taking a super quick look at my Core Data changes please?)

### CODE REVIEW

**Comment by koke** [comment]
You should add the `locale` parameter to the `me/sites` request. Other than that code looks good, I'll give it a test when the locale is fixed.

**Comment by frosty** [comment]
@koke Locale added to `me/sites` request!

**Comment by koke** [comment]
Looks good, but I'm not sure if we need a new model version. I'll let @astralbodies give the :shipit: on that

**Comment by astralbodies** [comment]
@koke Nope no model version required as 49 was "new" since 6.2 was cut. 👍

**Pull request merged**
