### PR TITLE
Update RELEASE-NOTES for Stats Subscribers

### PR DESCRIPTION
**Pull request by staskus**
Updating release notes for Stats Subscribers project
More information: https://github.com/Automattic/wordpress-mobile/issues/47

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by staskus** [comment]
@aditi-bhatia, @irfano 

Feel free to use the testing app version generated by this PR for testing if you prefer not to build the Xcode version.

Also, let me know if you think that release notes should be reformulated. 

Thanks!

**Comment by irfano** [comment]
> Also, let me know if you think that release notes should be reformulated.

I initially used a shorter description for the RELEASE notes. But yours is good as well. I updated (https://github.com/wordpress-mobile/WordPress-Android/pull/20756/commits/511d5900fd2f19ade812f5ace24837076aabb927) mine.

**Review by guarani — APPROVED** [review]
Looks good!

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/289">24.9</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
