### PR TITLE
Rich Text: Do not set frame if it has an infinite origin.

### LINKED ISSUE #6276: Reader Detail: Images disappear when rotating the iPad
h/t @frosty 

images in the post disappear once rotated:

reader-rotation

They reappear by scrolling enough to trigger the navigation bar show / hide animation.

### PR DESCRIPTION
**Pull request by aerych**
Fixes #6276 
When a 180 degree rotation occurs, `frameForTextInRange` will return a rect with an infinite origin, and cgsize zero.  This pr checks for such a frame and avoids setting it on attachment views.

To test:
Set a breakpoint on the return so its easier to test the fix.
Repeat the steps outlined in the issue and confirm that images do not vanish when a 180 degree rotation occurs.

Needs review: @frosty

### CODE REVIEW

**Comment by kurzee** [comment]
@aerych I'm not able to get the `frame == infiniteFrame` expression to pass and `return`. Does this only occur with spit-view maybe?

(@frosty, @aerych asked me to give this a spin while you're AFK)

**Comment by aerych** [comment]
> Does this only occur with spit-view maybe?

Try as I might I can't repro *unless* its with the split-view.  I assumed that it could still happen without the splitview but I guess not. 🤔  I'll retarget to develop.

**Comment by kurzee** [comment]
@aerych nice! All good, :shipit:

**Comment by aerych** [comment]
Thanks @kurzee !

**Pull request merged**
