### PR TITLE
Fixes auto rotate cell configuration

### LINKED ISSUE #8752: Signup: Rotating "New Account" screen changes username to dots
### Expected behavior

I expect that all of the values on the New Account screen will be saved and appear correctly even after rotating my device.

### Actual behavior

After rotating my device, the username field turned to dots:

When I tap on the username it still appears on the "Change Username" screen as expected, but even if I change it there it still appears as dots on the New Account screen.

### Steps to reproduce the behavior

1. Select the Signup button.
2. Select "Sign up with email."
3. Enter a new email address and tap "Next."
4. Open the mail app and tap the button in the magic link email.
5. On the New Account screen, rotate your device.

Result: The username field has dots instead of the username in plain text.

##### Tested on iPhone 6, iOS 11.2.6, WPiOS 9.5.0.20180227

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #8752 

To test:

1. Create a new WordPress.com account
2. Open the magic link that gets sent
3. Rotate the screen when you're shown a possible username/password

@elibud we may want to just disable rotation as well (no other login screen allows rotation)

But this fix works for now.

### CODE REVIEW

**Comment by elibud** [comment]
Interesting @kwonye so maybe it was an oversight to allow rotation there, I'll wait until @ScoutHarris or @nheagy can give us more info on that. Thanks for tackling this!

**Comment by nheagy** [comment]
I’ll confirm that none of the NUX screens should allow rotation. This should be inherited from the NUX base class.

**Comment by kwonye** [comment]
Thanks @nheagy! I think I know what’s going on in that case so I’ll try and push something up tomorrow morning @elibud

**Comment by ScoutHarris** [comment]
@elibud , @kwonye , @nheagy - the epilogue view should not rotate. But like Eli, I couldn't figure out why it is (to note, the username view is rotating as well and should not). So I created #8833 to fix the rotation issue. @kwonye 's fix here is fine, and is good to have even if the rotation worked right.
I say :shipit: .

**Pull request merged**
