### PR TITLE
Dashboard Cards: Add page creation section to Pages card

### LINKED ISSUE #20441: Dashboard Cards: Handle empty state of the Pages card

### LINKED ISSUE #20444: Dashboard Cards: Implement the "Create a new page" section in the Pages card
## Tasks

- [ ] Implement the "Create another page" section
- [ ] Handle different states (New user with 1 page/existing user with multiple pages)
- [ ] Handle tap action and open page creation flow

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Closes #20444
Closes #20441

## Description
Adds page creation section to the Pages card. The new section has three different states:
* If the user has more than one page, the section is collapsed and only holds a button.
* If the user has 1 page, the section is expanded and holds a label, button, and promo image.
* If the user doesn't have pages, the section is expanded and holds a label, button with different text, and promo image.

## Screenshots

|/|Zero Pages|One Page|Multiple Pages|
|-|-|-|-|
|Light Mode|zero-light|one-light|many-light|
|Dark Mode|zero-dark|one-dark|many-dark|

### Site with zero pages

1. Run the Jetpack app
2. Enable the Pages Card Remote Feature Flag from the debug menu
3. Navigate to the dashboard
4. Switch to a site with zero pages
5. Make sure the Pages card is displayed
6. Make sure the create button reads "Add pages to your site" and matches the design
7. Make sure the description label is displayed and matches the design
8. Make sure the promo image is displayed and matches the design
9. Tap on the Create button
10. Make sure the page creation flow starts as expected
11. Dismiss the flow
12. Tap anywhere else in the bottom section
13. Make sure the page creation flow starts as expected

### Site with one page

1. Run the Jetpack app
2. Enable the Pages Card Remote Feature Flag from the debug menu
3. Navigate to the dashboard
4. Switch to a site with 1 page
5. Make sure the Pages card is displayed
6. Make sure the create button reads "Create another page" and matches the design
7. Make sure the description label is displayed and matches the design
8. Make sure the promo image is displayed and matches the design
9. Tap on the Create button
10. Make sure the page creation flow starts as expected
11. Dismiss the flow
12. Tap anywhere else in the bottom section
13. Make sure the page creation flow starts as expected

### Site with multiple pages

1. Run the Jetpack app
2. Enable the Pages Card Remote Feature Flag from the debug menu
3. Navigate to the dashboard
4. Switch to a site with more than 1 page
5. Make sure the Pages card is displayed
6. Make sure that only the create button is displayed and matches the design
7. Make sure the create button reads "Create another page"
8. Tap on the Create button
9. Make sure the page creation flow starts as expected

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] VoiceOver.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] iPhone and iPad. 
- [x] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by hassaanelgarem** [comment]
@osullivanchris For the description label, I’m using the system’s secondary label color. This is the color used in the Figma design for dark mode. But a different - slightly darker - color is used for light mode. I feel this unifies the colors used throughout the card. Is this fine, or do you prefer the slightly darker color?

|Design|Build|
|-|-|
|||

**Comment by hassaanelgarem** [comment]
@osullivanchris For the description label, I’m using the system’s secondary label color. This is the color used in the Figma design for dark mode. But a different - slightly darker - color is used for light mode. I feel this unifies the colors used throughout the card. Is this fine, or do you prefer the slightly darker color?

|Design|Build|
|-|-|
|||

**Comment by osullivanchris** [comment]
> @osullivanchris For the description label, I’m using the system’s secondary label color. This is the color used in the Figma design for dark mode. But a different - slightly darker - color is used for light mode. I feel this unifies the colors used throughout the card. Is this fine, or do you prefer the slightly darker color?

Yep was meant to use the secondary label color on light mode and dark mode. The other color must have been used in error. Thanks for spotting and using the correct one 👍

**Comment by osullivanchris** [comment]
Tried out the build and all looks great - nice job @hassaanelgarem

**Review by momo-ozawa — COMMENTED** [review]
If I switch to a self-hosted site with no pages, the pages card never stops loading. If I then navigate to some other screen then come back to the dashboard, the pages card is blank. I think it might have to do with the site being self-hosted? I didn't see this behavior on wp.com sites


https://user-images.githubusercontent.com/6711616/233646819-35c87193-1336-4b94-a05b-84e75c57f13d.mp4

**Comment by hassaanelgarem** [comment]
> If I switch to a self-hosted site with no pages, the pages card never stops loading. If I then navigate to some other screen then come back to the dashboard, the pages card is blank. I think it might have to do with the site being self-hosted? I didn't see this behavior on wp.com sites

@momo-ozawa This is weird, I'm unable to reproduce this, but mainly because I can't reach a state where the dashboard is shown for a self-hosted site. The site you were using, is it a connected self-hosted site? If not, and the dashboard is showing, then this is a bug on its own. Also, what about the rest of the cards, especially the stats card, is it working normally?

**Comment by momo-ozawa** [comment]
>  The site you were using, is it a connected self-hosted site?
Yes, it's a connected self-hosted site.

I can reproduce this bug 100% on the Jetpack Complete site. It only seems to happen when there are no pages. Everything works as expected when there's one or more pages.

**Comment by hassaanelgarem** [comment]
@momo-ozawa I created #20593 to track the contributor issue, and I'll open a new PR shortly addressing this 👍

**Comment by hassaanelgarem** [comment]
cc: @startuptester 👋 

This PR satisfies the following testing milestones:

- Card Content and Page Tags
- Context Menu
- Tap Actions
- Error Handling
- Empty State
- Dark Mode
- Accessibility
- i18n

**Review by momo-ozawa — APPROVED** [review]

**Pull request merged**
