### PR TITLE
[Zendesk] Update Zendesk to 3.0.3

### PR DESCRIPTION
**Pull request by danielebogo**
This PR updates Zendesk to 3.0.3 version, which fixes `Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler`

## To test:
- Use Xcode 11.2 or 11.2.1
- Make sure it builds
- Run WP iOS and check everything Zendesk related works as before.

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by designsimply** [comment]
I don't mind testing this! I'd like to try with the installable build.

**Comment by jkmassel** [comment]
FYI – this is on hold until CircleCI releases a `11.2.1` machine image – tests always fail on `11.2`.

**Comment by jkmassel** [comment]
In order to test installable builds, we'll need to merge in https://github.com/wordpress-mobile/WordPress-iOS/pull/12939, then rebase on `develop`. 

If installable builds work correctly, this PR is ready to be merged.

**Comment by danielebogo** [comment]
@jkmassel I merged develop in this branch (which already contains #12939 ) fixing the conflict. I kept the origin _config.yml_ file but maybe we want [this](https://github.com/wordpress-mobile/WordPress-iOS/blob/db8e8b40f67805f541045fe7a1601d67c2d55175/.circleci/config.yml) instead? Feel free to revert to https://github.com/wordpress-mobile/WordPress-iOS/pull/12902/commits/db8e8b40f67805f541045fe7a1601d67c2d55175 if it's better.

**Comment by jkmassel** [comment]
This PR seems to mostly work – @designsimply, would you be able to begin testing the ZD integration? :) 

It looks like there's a bug remaining around posting the installable build message – I'll take a look at that soon, but I think we're ready to validate the rest using Xcode 11.2.1.

**Comment by loremattei** [comment]
Hey there! I've moved this to 13.8 since 13.7 has been cut. If you want this to make it to 13.7, please feel free to ping me.

**Comment by designsimply** [comment]
I had some trouble with the installable build yesterday, but it turned out to be a problem with access and @loremattei helped me get it fixed up. 🎉

**Comment by designsimply** [comment]
I tested just now with installable build WPiOS 13.6 (17266) on iPhone 6S iOS 13.2.2 and I could send messages without any problems and everything else is working well except the attachment button does not work for me even after allowing access to photos and the camera. ([1m24s](https://cloudup.com/cDnd4y5fT9v))

camera-access-prompt photos-access-prompt contact-us-form

<sup>(internal reference with app logs: 2503971-zen)</sup>

**Comment by danielebogo** [comment]
@ScoutHarris can this be a problem related to their SDK? I don't think it's a VC we built right?

**Comment by ScoutHarris** [comment]
Hey @danielebogo. Yes this functionality is most definitely is the ZD SDK. 

I've only seen this happen in simulators, so @designsimply is going to try it directly from Xcode just in case there was an issue with the installable build.

**Comment by designsimply** [comment]
Tested again with the `issue/update-zendesk` branch for good measure and the attachment button is still unresponsive. ([2m12s](https://cloudup.com/cUdIOBcpBco))

**Comment by melindahelt** [comment]
Side note - I just tested attachments using WPiOS 13.5, upgraded to 13.6, and used beta 13.7 and had no issues at all attaching a photo from my camera roll and confirming the attachment came into ZD. 

iOS 13.1.2 on iPhone Xr

**Comment by designsimply** [comment]
After updating to iOS 13.2.3, it let me access attachments once but the message failed. After that, the attachment button became unresponsive. ([2m52s](https://cloudup.com/cfNSaEg4rXc))

After a fresh install of WPiOS 13.6 (17266) installable build on iOS 13.2.3, I could send messages again but the attachment button is still unresponsive in my testing. ([1m53s](https://cloudup.com/cOWkWfSVvga))

<sup>Tested with WPiOS 13.6 (17266) installable build on iPhone 6S iOS 13.2.2.</sup>

**Comment by ScoutHarris** [comment]
FWIW, I'm able to add attachments and can't yet repro what @designsimply is seeing. I'm using an iPhone 8 Plus. Was successful with iOS 13.2 and 13.2.3, with Xcode 11.2 and 11.2.1.

**Comment by ScoutHarris** [comment]
Oh, also - 

> the message failed to send

Is caused by https://github.com/wordpress-mobile/WordPress-iOS/issues/12297.

**Comment by yaelirub** [comment]
Tested on iPhone 11, iOS 13.2.2 and iPhone 7 iOS 13.2.3 and I am able to add attachments with no issues

**Comment by designsimply** [comment]
Figured out the attachment button problem!!! The attachment button goes kaput when an external keyboard is attached. Goodness gracious! 

To get some extra debug info, I also opened `WordPressAppDelegate.swift` and found `CoreLogger.logLevel = .debug` and changed it to `CoreLogger.logLevel = .verbose` and checked the debug log in XCode and saw things like: 

```
2019-11-20 15:03:37.560392-0700 WordPress[688:277105] [VERBOSE]: Showing ImagePicker from visible keyboard
2019-11-20 15:03:37.612927-0700 WordPress[688:277105] [VERBOSE]: Unable to find window to present ImagePicker
```

and

```
2019-11-20 15:04:05.737577-0700 WordPress[688:277105] [VERBOSE]: Showing ImagePicker from visible keyboard
2019-11-20 15:04:06.891113-0700 WordPress[688:277105] [VERBOSE]: Showing ImagePicker from visible keyboard
2019-11-20 15:04:07.906804-0700 WordPress[688:277105] [VERBOSE]: Hiding ImagePicker
2019-11-20 15:04:07.946884-0700 WordPress[688:277105] [VERBOSE]: Hiding ImagePicker
2019-11-20 15:04:09.006276-0700 WordPress[688:277105] [VERBOSE]: Showing ImagePicker from hidden keyboard
2019-11-20 15:04:09.707496-0700 WordPress[688:277105] [VERBOSE]: Showing ImagePicker from hidden keyboard
```

And in my tests today so far, I'm seeing failed messages intermittently and the external keyboard doesn't seem relevant to those.

**Comment by ScoutHarris** [comment]
I merged `develop` into this branch, which includes the fix for #12297. So the messages failing should be resolved.

**Comment by designsimply** [comment]
I also tested with 13.7.0.0 (TestFlight beta) and saw the same behavior where the attachment button (paperclip icon) becomes unresponsive if my external bluetooth keyboard is attached. What a riot.

**Comment by ScoutHarris** [comment]
@jkmassel I'm going to turn this over to you know. We're good to go when you are. Thanks!!

**Comment by jkmassel** [comment]
Currently planning to merge this Monday at 4PM UTC in order to give everyone a change to get their local machine prepared. I'll rebase as needed prior to that.

Thanks for the testing y'all! 🎉

**Pull request merged**
