### PR TITLE
Fix app freeze on fresh install when access the dashboard

### LINKED ISSUE #18256: My Site Dashboard freezes on fresh install, iOS 15.4
Refs `p1648811499644559-slack-C011BKNU1V5`, https://github.com/wordpress-mobile/WordPress-iOS/pull/18251#issuecomment-1084907112

### Expected behavior
The dashboard does not freeze.

### Actual behavior
When switching from Site Menu to the Home dashboard, the app freezes.

### Steps to reproduce the behavior
- Modify the code so that the feature flag for My Sites Dashboard is turned on.
- Uninstall the WordPress app from the simulator.  ⚠️ NOTE: **This issue only happens on a fresh install**. ⚠️ 
- Build the app using Xcode 13.3, targeting iOS 15.4.
- After logging in and selecting a site, you should see the Site Menu dashboard being active/selected.
- Tap on the Home section.
- Observe that the app freezes.

The dashboard works just fine on subsequent runs (after the app is killed and started again). Here are some screenshots:

On fresh install, app freezing | After reruns, working just fine
-|-
freezing | reruns

### Tested on

- iOS 15.4 Simulator:
  - iPhone 8
  - iPhone 11 Pro Max
  - iPhone 12
  - iPhone 12 Pro Max
- Device:
  - iPhone 11 Pro Max (iOS 15.4)

Note that this problem is not reproducible on iPads.

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Fixes #18256 

## Testing Instructions

1. Uninstall the WordPress app from the simulator. ⚠️ NOTE: This issue only happens on a fresh install. ⚠️
2. Build the app using Xcode 13.3, targeting iOS 15.4.
3. Log in
4. Select a site that doesn't have draft or scheduled posts
5. Tap on the Home section.
6. Observe that the app does not freeze.

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hassaanelgarem** [comment]
@mokagio This PR fixes an issue that is quite critical. However, we're not sure if this issue will affect our users, as we were only able to reproduce this using Xcode 13.3 on iOS 15.4, and our builds are not using this Xcode version, so we're not sure yet.

As per this https://github.com/wordpress-mobile/WordPress-iOS/issues/18256#issuecomment-1085896197, once `19.6` is on TestFlight, we will test this, and if the issue isn't there, then this PR can wait till the next release. But if it's reproducible, we'll need to include this fix in `19.6`.

**Comment by mokagio** [comment]
> As per this https://github.com/wordpress-mobile/WordPress-iOS/issues/18256#issuecomment-1085896197, once 19.6 is on TestFlight, we will test this, and if the issue isn't there, then this PR can wait till the next release. But if it's reproducible, we'll need to include this fix in 19.6.

Sounds good to me. Thank you for the heads up @hassaanelgarem

**Review by dvdchr — APPROVED** [review]
LGTM. Tested and verified that the frost has melted :shipit:

**Review by momo-ozawa — APPROVED** [review]
Works as described, no freezing for me either

**Comment by hassaanelgarem** [comment]
I tested the issue on the current TestFlight build on iOS 15.4.1, and I couldn't reproduce it. This means the assumption that this issue won't affect our users because we don't create our builds with Xcode 13.3 is correct.

There's no need to include the fix in the current release. I will proceed with merging this to trunk so that we're future-proof.
cc @leandroalonso @mokagio

**Pull request merged**
