### PR TITLE
Posts/Themes: Preventing call to willDismissSearchController.

### PR DESCRIPTION
**Pull request by kurzee**
Setting the `searchController` to not `active` when it already wasn’t active subsequently called `willDismissSearchController` on the delegate, producing unexpected search cancelling results.

This specifically caused an issue with the tableView's offset when leaving the view controller, where `willDismissSearchController` is called, `searchText` is set to `nil`, and the tableView's content and offset are updated.

To test:

1. Open Blog Posts.
2. Scroll down a bit, select a post.
3. Go back.
4. The tableView offset should be where it was originally.
5. The `willDismissSearchController` should not have been called.

To Test:

1. Open Blog Posts.
2. Search for posts.
3. Select a post.
4. Search should be cancelled, as expected.

To Test:

1. Repeat above, but for Themes.

Needs review: @frosty (no rush)

Note: Perhaps we shouldn't be deactivating search when selecting a search result? 🤔

### CODE REVIEW

**Comment by frosty** [comment]
Thanks for catching this, @kurzee! I tested your changes and everything looks good.

However, I think your query about whether we need to deactivate _at all_ is probably correct. The calls to deactivate search were present in our old WPSearch implementation, and I just left them there presuming they were required. If we make a few changes like this, it seems to work okay for me: https://gist.github.com/frosty/2d2257a22d27d10c80d6c06248e51c82

... with one small issue. In the posts list, with search active, after tapping into a post and then tapping back the tableview's y content offset has moved slightly – it seems around 64px (status bar + search / nav height) lower than it was when you left the view. At first glance I can't see the reason for this, although I don't think it's a big issue.

What do you think, should we drop the deactivation altogether?

**Comment by kurzee** [comment]
@frosty I think I'd agree with hanging on to the search results after tapping. Particularly if you tapped on the wrong post, the original list is lost and you'd have to type it out again, like a sucker.😭 😭 😭 

I'd say we ship this one, once you approve, and then we can explore an implementation that hangs on to those search results. I had a fix in my posts readability branch for an offset issue, I bet this is a similar issue. I'll take a look myself and see if I can make a quick fix.

**Comment by frosty** [comment]
Okay, then let's :ship: this, and we can look at not deactivating the results later.

**Comment by kurzee** [comment]
Thanks @frosty!

**Pull request merged**
