### PR TITLE
Fix wrong FAB position after Quick Start -> Visit Site

### LINKED ISSUE #14287: Quick Start pushing Floating Action Button out of position
### Steps to reproduce the behavior
- create a new site
- accept the quick start guide
- go to step 6/6 'view your site' 
- Tap on 'View site'
- Modal view opens with your site
- Close the modal
- The Floating Action Button is now hovering too high up, in the same position as when the SnackBar was there
- The Floating Action Button should move back down once the SnackBar is gone

##### Tested on [iPhone Xs], iOS [13.5], WPiOS [14.9 and 15.0]

Screenshot 2020-06-10 at 12 32 02

### PR DESCRIPTION
**Pull request by Gio2018**
Fixes #14287

To test:

- create a new site
- accept the quick start guide
- go to step 6/6 'view your site' 
- Tap on 'View site'
- Modal view opens with your site
- Close the modal
- Verify that the notice bar has been dismissed and the FAB is in the expected position

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by osullivanchris** [comment]
@Gio2018 sorry I just found a bug. The first time I did the flow everything worked as expected.

However, I took the following steps

- went back to the 'Customise your site' guide
- went into completed items
- tapped 'view your site' again (now with strike through to indicate its completed)
- notice bar appears 'Select View Site to preview', along with blue indicator
- tap to view site
- see preview then close
- **the blue indicator dot persists even though the task is complete. The only way I can get rid of it is if I bring up another task**

I tested creating another site and I didn't have the issue again. Only seems to happen going into the completed task again within the same site.

**Comment by Gio2018** [comment]
> @Gio2018 sorry I just found a bug. The first time I did the flow everything worked as expected.
> 
> However, I took the following steps
> 
> * went back to the 'Customise your site' guide
> * went into completed items
> * tapped 'view your site' again (now with strike through to indicate its completed)
> * notice bar appears 'Select View Site to preview', along with blue indicator
> * tap to view site
> * see preview then close
> * **the blue indicator dot persists even though the task is complete. The only way I can get rid of it is if I bring up another task**
> 
> I tested creating another site and I didn't have the issue again. Only seems to happen going into the completed task again within the same site.

Thanks for finding this @osullivanchris ! Will update this PR as soon as I fix this other one.

**Comment by bjtitus** [comment]
Noticed a couple of issues that I think predate this branch:

https://github.com/wordpress-mobile/WordPress-iOS/issues/14441 - Blue indicator shown without a notice
https://github.com/wordpress-mobile/WordPress-iOS/issues/14442 - Floating Action Button is obscured by _certain_ quick start items.

**Comment by Gio2018** [comment]
> Noticed a couple of issues that I think predate this branch:
> 
> #14441 - Blue indicator shown without a notice
> #14442 - Floating Action Button is obscured by _certain_ quick start items.

Thanks for finding these two @bjtitus ! I have added them to the list of [Quick Start Fixes](https://github.com/wordpress-mobile/WordPress-iOS/projects/16)

**Pull request merged**
