### PR TITLE
[Gutenberg] Test persisting local media files when uploading images 

### PR DESCRIPTION
**Pull request by derekblank**
Test build to persist local media file without flicker between downloading a server image asset. 

Related:

* https://github.com/WordPress/gutenberg/pull/57869
* https://github.com/wordpress-mobile/gutenberg-mobile/pull/6550

Fixes:
* https://github.com/wordpress-mobile/gutenberg-mobile/issues/6510

To test:
TBD

## Regression Notes
1. Potential unintended areas of impact
TBD

2. What I did to test those areas of impact (or what existing automated tests I relied on)
TBD

3. What automated tests I added (or what prevented me from doing so)
TBD

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>[Status] DO NOT MERGE</code> label(s).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by derekblank** [comment]
## Regression Testing
Device: Samsung Galaxy SE20
Build: [pr22409-73ce4d2](https://github.com/wordpress-mobile/WordPress-iOS/pull/22409#issuecomment-1897688547)


### Image - 1
- [ ] Image block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc001)
- [ ] Image block - Insert image from device (cancel) - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc002)
- [ ] Image block - Add Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc003)
- [ ] Image block - Close/Re-open post with an ongoing image upload - [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc004)
- [ ] Image block - Close post with an ongoing image upload - [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc005)

### Gallery - 1

- [ ] Gallery block - Close/Re-open post with an ongoing image upload - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc001)
- [ ] Gallery block - Close post with an ongoing image upload - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc002)

### Gallery - 2

- [ ] Gallery block - Insert image from device (failing) - [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc006)
- [ ] Gallery block - Insert image from device (cancel) - [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc009)

### MediaText - 1

- [ ] Media Text block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-text.md#tc001-i)
- [ ] Media Text block - Close/Re-open post with an ongoing image upload - [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-text.md#tc003-i)

### MediaText - 2

- [ ] Media Text block - Insert video from device - [TC002-v](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-text.md#tc002-v)
- [ ] Media Text block - Insert image from device - [TC002-i](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-text.md#tc002-i)

### MultipleUpload - 1

- [ ] Simultaneous uploads - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-interaction.md#tc001)

### Cover - 1

- [ ] Cover - Add image background from WordPress Media library - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/cover.md#tc001)
- [ ] Cover - Image focal point is rendered properly - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/cover.md#tc002)
- [ ] Cover - Custom color is rendered properly - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/cover.md#tc003)

**Comment by derekblank** [comment]
## Regression Testing
Device: iPhone SE
Build: [pr22409-73ce4d2](https://github.com/wordpress-mobile/WordPress-iOS/pull/22409#issuecomment-1897688547)


### Image 
- [x] Image block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc001)
- [x] Image block - Insert image from device (cancel) - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc002)
- [x] Image block - Add Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc003)
- [x] Image block - Close/Re-open post with an ongoing image upload - [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc004)
- [x] Image block - Close post with an ongoing image upload - [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc005)
- [x] Image block - Border style setting - [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc006)
- [x] Image block - Image size setting - [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc007)

### Gallery 

- [x] Gallery block - Close/Re-open post with an ongoing image upload - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc001)
- [x] Gallery block - Close post with an ongoing image upload - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc002)
- [x] Gallery block - Choose from device (stay in editor) - Successful upload [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#choose-from-device-stay-in-editor---successful-upload)
- [x] Gallery block - Insert image from device (failing) - [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Take a photo - [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#take-a-photo)
- [x] Gallery block - Choose from the free photo library [TC008](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#choose-from-the-free-photo-library)
- [x] Gallery block - Insert image from device (cancel) - [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc009)
- [x] Gallery block - Columns - [TC0013](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc013)
- [x] Gallery block - Crop images - [TC0014](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#settings---crop-images)

### MediaText

- [x] Media Text block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-text.md#tc001-i)
- [x] Media Text block - Close/Re-open post with an ongoing image upload - [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-text.md#tc003-i)
- [x] Media Text block - Insert video from device - [TC002-v](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-text.md#tc002-v)
- [x] Media Text block - Insert image from device - [TC002-i](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-text.md#tc002-i)

### MultipleUpload

- [x] Simultaneous uploads - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-interaction.md#tc001)

### Cover 

- [x] Cover - Add image background from WordPress Media library - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/cover.md#tc001)
- [x] Cover - Image focal point is rendered properly - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/cover.md#tc002)
- [x] Cover - Custom color is rendered properly - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/cover.md#tc003)

**Note:** A minor regression was identified in the Cover and Media-Text blocks where the network image would not display in the Editor unless the Editor was closed and re-opened. This was fixed by the commit https://github.com/WordPress/gutenberg/pull/57869/commits/70b003a66aea6ee7d326638d0bfc33fd73c304e2 and the regression disappeared.

**Comment by derekblank** [comment]
Closing, no longer needed.

**Pull request closed without merging**
