### PR TITLE
Jetpack App: Change navigation titles to sans serif font

### PR DESCRIPTION
**Pull request by momo-ozawa**
## Description
This PR updates the navigation titles and the blog detail header title to a sans serif font for the Jetpack target.

## Screenshot

Screen | WordPress | Jetpack
--- | --- | ---
My Site | simulator_screenshot_9B6303F7-EA78-4D76-8D9B-6F69E67F6E70 | simulator_screenshot_B43FAF22-154C-4BB8-916A-67A696DDA383
Stats | simulator_screenshot_9B50925B-AEAE-4809-B303-CD1EF887F00F | simulator_screenshot_774C39CF-EE7D-4918-A467-D41B0A567794

### Jetpack
1. Build and run the Jetpack scheme
2. ✅ Notice the navigation titles (both large and standard) are in a sans serif font
3. Go to My Site
4. ✅ Notice the blog detail header title is in a sans serif font

### Regression (WordPress)
1. Build and run the Jetpack scheme
2. ✅ Notice the navigation titles (both large and standard) are in a serif font
3. Go to My Site
4. ✅ Notice the blog detail header title is in a serif font

### CODE REVIEW

**Review by emilylaguna — CHANGES_REQUESTED** [review]
Heya, this looks good but I'm getting a build error when I try to build WordPress. 

Update: Looks pretty simple to fix so I pushed a fix for it.

**Comment by emilylaguna** [comment]
Was thinking more about this and I'm thinking having style related items inside the AppConfiguration seems a bit odd. 

How do you feel about moving them to a `StyleGuide`  struct? that way semantically it makes a bit more sense. 



cc: @leandroalonso

**Review by leandroalonso — APPROVED** [review]
I agree. We can keep the `AppConfiguration` there but probably add a `StyleGuide` similar one.

As for now, I can see two different things:

1) Properties that define how the app behaves (like the `isJetpack`)
2) Styles: fonts, colors, images, etc.

Also, I'm not entirely sure if the protocol makes any sense in this case.

Wdyt @momo-ozawa?

Besides that, tested both WP and Jetpack. All working fine.

**Comment by momo-ozawa** [comment]
@leandroalonso @emilylaguna 

> How do you feel about moving them to a StyleGuide struct?

> As for now, I can see two different things:
> 
>    1. Properties that define how the app behaves (like the isJetpack)
>    2. Styles: fonts, colors, images, etc.

👍 Done in https://github.com/wordpress-mobile/WordPress-iOS/pull/16161/commits/5251405aa20e21468757b3e8346c0ae0afcd2b64

> Also, I'm not entirely sure if the protocol makes any sense in this case.

Yeah, I wasn't so sure about having a protocol either. Ended up deleting the protocol. https://github.com/wordpress-mobile/WordPress-iOS/pull/16161/commits/69e0328bacf502f5239fe0e6bfd724a1fa0ad772

**Review by emilylaguna — APPROVED** [review]
Nice job! Looks good to me!

**Pull request merged**
