### PR TITLE
Updates GB version to support list blocks

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/208

Related GB-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/704

To test:
 - Create a new post using GB
 - Add a list block to it
 - See if it shows correctly
 - Add list items
 - Change type of list (ordered, unordered)
 - Split list items in the middle
 - Split block by inserting two empty list items 

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by etoledom** [comment]
An example with ordered list:

splitting_ordered

**Comment by SergioEstevao** [comment]
@etoledom both your findings also happen on the web version, so I assume that is by design :).

Thanks for the review!

**Comment by hypest** [comment]
The ordered-list-becomes-unordered-on-split feels like a bug. @ellatrix maybe you have some clue on this one?

**Comment by ellatrix** [comment]
> When splitting the list block, I get a paragraph block in the middle.

What's not expected about this? What do you expect?

> Also, when splitting an ordered list, the second half is converted into an unordered list.

@hypest @SergioEstevao I don't see this happening for web.

**Comment by etoledom** [comment]
> >When splitting the list block, I get a paragraph block in the middle.

>What's not expected about this? What do you expect?

My first expectation was to have just two list blocks, as when splitting a paragraph block. But on a second thought, it makes total sense. If I split a list, it would most probably be to write something in between. 👍

**Comment by ellatrix** [comment]
@etoledom It's the same in most editors I've come across. :)

**Comment by SergioEstevao** [comment]
> @hypest @SergioEstevao I don't see this happening for web.

I just tested in WP.com and saw this happening:

Create a list block
Make it a numbered one
Write some lines/items
Split the list in the middle.
The bottom part gets converted to a bullet list.

**Comment by hypest** [comment]
> > Also, when splitting an ordered list, the second half is converted into an unordered list.
>
> @hypest @SergioEstevao I don't see this happening for web.

Here's what I see on the web (Frontenberg) at the time of writing:

list-block-split-numbers-to-bullets

The second half of the ordered list becomes unordered. Not sure if Frontenberg has the latest of Gutenberg or this behavior is by design.

**Comment by ellatrix** [comment]
@hypest Ah, I was on a different branch. Looks like #14840 fixes it.

**Comment by ellatrix** [comment]
@hypest Added a test: https://github.com/WordPress/gutenberg/pull/14840/commits/1aec480f37992747fcfd1e9064b6b6fa45a44ae0

Would appreciate a review of the PR. :)

**Pull request merged**
