### PR TITLE
Updates the editor pod to v1.8

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/839.

To test:
- Replicate the steps in [this video]() and make sure the weird behavior is gone.

Needs review: @sendhil, @SergioEstevao

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@diegoreymendez tests are failing to do you want to give it a look?

**Comment by diegoreymendez** [comment]
@SergioEstevao - The tests are not compiling but that wasn't introduced by this PR.

I created [a ticket](https://github.com/wordpress-mobile/WordPress-iOS/issues/5752) to fix that separately.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Just merged the unit tests fix into this PR.

**Comment by sendhil** [comment]
Fixed a merge conflict. Besides that :shipit:

**Pull request merged**
