### PR TITLE
Issue/link to existing content

### PR DESCRIPTION
**Pull request by SergioEstevao**
Refs: #10059 #7670 

This PR adds the interface to the Link UI to allow link to existing content in the blog.

screen shot 2018-08-30 at 11 31 48
screen shot 2018-08-30 at 11 37 39
screen shot 2018-08-30 at 11 37 49

To test:
 - Open the app
 - Start a post in a blog with other content
 - Tap on insert a link
 - Select the option `link to existing content`
 - Select one of the existing post
 - See if the the post url is selected 
 - Optional if no text for the link is selected, the title get's update with the title of the post
 - Go again inside the 'link to existing content' screen
 - Check if there is a checkmark showing the current selecte post
 - Check if the search bar filters the content correctly.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
Looks right to me! :shipit:

**Comment by SergioEstevao** [comment]
@diegoreymendez fixed issued you found, can you please give it another spin.

**Comment by diegoreymendez** [comment]
This is working fine, nice job!

@iamthomasbishop - In terms of UX I think the "Link to existing content" option may be a bit clearer if placed inside of the URL section, instead of in the main "Link Settings" view, since it's pretty much relevant only for setting the URL.

link_to_existing

**Comment by diegoreymendez** [comment]
The only way to revert the "Link to existing content" option at this time is by removing the link manually from the URL section.

That's why, to me, it feels a bit fragmented right now.

**Comment by iamthomasbishop** [comment]
If I tap on `Link to existing content`, and select a post to select it, I should be able to tap it again to de-select the selection, in other words revert?

**Comment by iamthomasbishop** [comment]
@SergioEstevao I meant to say _ideally_ the user should be able to do that, but honestly considering we do show an `X` inside the URL text input (to clear the URL), I'm not sure if it's a huge deal. Let's implement this way and see if we get any feedback that tells us we should fix.

**Pull request merged**
