### PR TITLE
New post cards show the first actionBar page by default.

### LINKED ISSUE #5006: New post cards sometimes show the action bar's second "page".
### Expected behavior

New posts should show the action bar's first page right after created.

### Actual behavior

At least sometimes, new posts show the action bar's second page right after created.

### Steps to reproduce the behavior

1. Create a post
2. Press the "More" button.
3. Create another post
4. Right after creation you'll see the post' card is at the second page.  Since this depends on the dequeueing mechanism of iOS it may not happen at your first attempt.  Repeat from step 2 if it doesn't trigger.
5. You'll notice the new post' card is showing its action bar in the second page.

##### Tested on [device], iOS [version]

Simulator.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes #5006 

**To test:**

Create new posts, press the "More" button in exiting ones, repeat.  Make sure new posts always show the action bar in its first page.

**Needs review:** @jleandroperez 

/cc @aerych

### CODE REVIEW

**Comment by aerych** [comment]
This is already addressed in https://github.com/wordpress-mobile/WordPress-iOS/pull/5000 :)

**Comment by diegoreymendez** [comment]
Amazingly similar approach.  Closing.

**Comment by aerych** [comment]
GMTA ;)

**Comment by jleandroperez** [comment]
Wow. Easiest code review ever.

**Comment by jleandroperez** [comment]
(Just noting that i'm nuking the orphan branch)

**Pull request closed without merging**
