### PR TITLE
Issues/4094 minor fixes, and removes feature flag

### PR DESCRIPTION
**Pull request by aerych**
Refs #4094 

This PR removes the new Reader menu's feature flag, enabling the new menu and navigation flow in the app for everyone. Also, as it was convenient, it includes some small fixes to #5799 and #5800, and a slight style tweak to an icon requested by @jancavan.

Needs review: @kurzee, would you be so kind sir?

### CODE REVIEW

**Comment by kurzee** [comment]
One thing, we have the `ReaderMenu` feature flag test still active in `FeatureFlagTest`:
```
    func testEnsureDisabledFeaturesInProduction() {
        Build.withCurrent(.AppStore) {
            expect(FeatureFlag.ReaderMenu.enabled).to(beFalse())
        }
    }
```

Note: I had previously added this one myself as I was updating which flags were currently being toggled.

**Comment by kurzee** [comment]
Kind of unrelated to this PR, but just in case, do we still intend to use `FollowedSitesViewController` in `ReaderSubscriptionViewController` for:
```
- (UIViewController *)controllerForPlaceholder:(ReaderSubscriptionPagePlaceholder *)placeholder
```

**Comment by aerych** [comment]
> we have the ReaderMenu feature flag test still active in FeatureFlagTest

doH!  Note to self.. always re-rerun the tests!

> do we still intend to use FollowedSitesViewController in ReaderSubscriptionViewController

Nope. There will be another PR full of red where all the old stuff is nuked.  Waiting on that to A) keep this PR more legible, B) make it easier to roll back in case there is unforeseen breakage.

**Comment by kurzee** [comment]
@aerych everything looks good! After the test fix, :shipit:!

**Comment by aerych** [comment]
@kurzee, to fix the test I commented out what was there, tweaked it to be a bit more generic and left some comments to make it an example for future tests.  Seemed more forward-thinking and practical than removing the test altogether.  Wanna take one last quick peek for a sanity check?

**Comment by kurzee** [comment]
@aerych great additions. Everything looks good, tests still pass :shipit: 🚀

**Comment by aerych** [comment]
Thank ya sir!!

**Comment by jancavan** [comment]
Just want to say that icon size LGTM, thanks @aerych!

**Comment by aerych** [comment]
Thanks @jancavan!!

**Pull request merged**
