### PR TITLE
Introduce SwiftLint

### PR DESCRIPTION
**Pull request by koke**
As the first step towards a Swift common style, this integrates SwiftLint.

I've only enabled one rule for now: _Files should have a single trailing newline_.
I'd start with zero rules, but if the whitelist is empty, SwiftLint uses the default rules.

I'm still trying to figure out why `xcpretty` isn't showing warnings generated by SwiftLint 😕 

Needs review: @SergioEstevao

### CODE REVIEW

**Comment by sendhil** [comment]
Nice.

**Comment by koke** [comment]
We might want to postpone merging unless someone else is taking the lead with the swift style guide, or at least remove the build step so we don't force every developer to install SwiftLint just to check for one rule.

**Comment by SergioEstevao** [comment]
@koke from my previous experience of adding a  OCLint step beside adding the rules we need to make it very clear on the results on why the lint step failed or else I think people will just ignore the errors being reported and blame Travis for it.

**Comment by koke** [comment]
They way I added it, it's just a build step in the regular build process, so warnings would show up in Xcode. If we disable the Xcode step, it'd also be disabled on travis, but you could still run `Scripts/lint.sh` manually. I'm also fine with closing this and integrating it when I come back.

**Comment by SergioEstevao** [comment]
@how about to create a separate target/scheme the same way I did for OCLint?

**Comment by koke** [comment]
At this point, I don't see how it'd be useful. If we're going to enforce style, lint warnings should be treated as normal warnings, and generated on every build.

**Comment by SergioEstevao** [comment]
I think that will help in the transition process to enforce it, we already have a lot of code in Swift and a lot of it is not following any style, so in a normal build process you will get a lot of "noise" warning regarding the lint. This way we can  have a build scheme that allows to run the tests and fix things was we go along.

**Comment by koke** [comment]
That's one of the reasons why I wanted to start from scratch and introduce rules one by one. Any new rule should come with making sure the existing code conforms to it. If we don't do that, then I agree the linter becomes noise, and it's ignored.

**Comment by koke** [comment]
Change of plans, since @sendhil is willing to take the lead on the style guide efforts while I'm out, let's review and merge this.

I've enabled a couple more rules:
- Lines should not have trailing semicolons
- Lines should not have trailing whitespace

Of all the available rules, I only enabled those that supported `autocorrect` (pushed style fixes in #5340), and couldn't imagine anyone arguing against them.

I've also tweaked the `lint.sh` script so it runs with `--strict` on Release builds. Style violations still show up as `warning: ` but it exits with a non-zero code, so the build fails:

screen shot 2016-05-10 at 09 38 49

Ideally, I'd like to implement our linter as a clang plugin, but I think this is the best available option today.

**Comment by SergioEstevao** [comment]
:shipit:

**Pull request merged**
