### PR TITLE
Update Gutenberg to 1.6.0

### PR DESCRIPTION
**Pull request by hypest**
This PR updates the gutenberg-mobile reference to point to the latest release, v1.6.0.

The reference is currently pointing to the release/1.6.0 branch on https://github.com/wordpress-mobile/gutenberg-mobile. Relevant PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1036.

To test:
The block editor should work as normal.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by hypest** [comment]
FYI, produced the changes in 61a503c80c27e6a4b3fceac0f04b54321e73b752 by manually editing the `Podfile` to point to the gutenberg-mobile commit hash and then ran `pod update` in the command line.

**Comment by hypest** [comment]
We found some issues with the video and the quote blocks so, we've decided over Slack to hold back the release, put the video, quote blocks behind the `__DEV__` flag to only have them on debug builds, and then do the code freeze.

**Comment by koke** [comment]
Found some issues that I mentioned on Slack:

- Video seems to have no sound. Known issue at https://github.com/react-native-community/react-native-video/issues/1192
- The setting icon on the video block seems to do nothing.
- Inserting a quote freezes the app. On relaunch, focusing on the quote leaves the keyboard flickering and unresponsive.

**Comment by CHaNGeTe** [comment]
> Video seems to have no sound. Known issue at react-native-community/react-native-video#1192 
Try this PR:
https://github.com/react-native-community/react-native-video/pull/1654

**Pull request merged**
