### PR TITLE
Show no connection error & push web view for stats

### PR DESCRIPTION
**Pull request by astralbodies**
1. Show connection error message as was done before 0.2.0.
2. Push chromeless web view when a URL is loaded from stats UI instead of launching out to Safari.
3. Resolved iOS 7 loading problems with Storyboard and call made to NSCalendar that doesn't exist until iOS 8.

### CODE REVIEW

**Comment by astralbodies** [comment]
Can you take a quick peek @jleandroperez?

**Comment by jleandroperez** [comment]
@astralbodies code looks good, however, i found a bug:

https://cloudup.com/cLi5bhHHOXA

It would appear that there is a missing solid bg color perhaps?

**Comment by astralbodies** [comment]
@jleandroperez Can you verify setting the background color fixes it for you too? :smile:

**Comment by jleandroperez** [comment]
@astralbodies looking great!.

:shipit:

**Pull request merged**
