### PR TITLE
Jetpack Focus: Hook up the CTA button for the fullscreen overlay

### LINKED ISSUE #19601: Jetpack Focus: Hook up the CTA button for the fullscreen overlay

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Closes #19601 

## Description
This PR implements the redirect action for the switch button in the fullscreen overlays.
The PR depends on #19603. The redirection logic is refactored into a separate class and reused by the fullscreen overlay.

## Testing Instructions

P.S: To be able to override remote feature flag values, you can apply the changes made in https://github.com/wordpress-mobile/WordPress-iOS/pull/19645 locally.

### Redirect to the app store

1. Ensure you don't have the Jetpack app on your test device.
2. Build the WordPress app targeting your test device.
3. Open the WordPress app.
4. Go to the debug menu
5. Enable "Jetpack Features Removal Phase One"
6. Go back to My Site
7. Navigate to the Sites list
8. Tap plus button
9. Tap "Create WordPress.com site"
10. The overlay is displayed
11. Tap the "Try the new Jetpack app" button
12. Verify that the WordPress app redirects you to Jetpack's App Store page.

### Redirect to the JP app

1. Don't delete the previously built WordPress app!
2. Ensure you don't have the Jetpack app on your test device.
3. This time, build the Jetpack app targeting your test device.
4. Open the WordPress app.
5. Navigate to the Sites list
6. Tap plus button
7. Tap "Create WordPress.com site"
8. The overlay is displayed
9. Tap the "Try the new Jetpack app" button
10. Verify that the WordPress app now opens the Jetpack app.

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hassaanelgarem** [comment]
Since this PR depends on changes in trunk and #19603. I’ll open this PR once #19603 is merged or once it is updated with the latest changes from trunk.
cc @dvdchr

**Comment by dvdchr** [comment]
> once https://github.com/wordpress-mobile/WordPress-iOS/pull/19603 is merged or once it is updated with the latest changes from trunk.

Thanks for the ping @hassaanelgarem ! Sorry it's still stuck in the queue for CI. However, I've [merged the latest trunk](https://github.com/wordpress-mobile/WordPress-iOS/pull/19603/commits/926c91b46326bae86e79e1e19cc70bc957aafb3a) into that branch for you.

Note: since this depends on my PR, and now that my PR is up to date with `trunk`, I'd suggest updating the base branch to target my branch instead if it's possible. This is to exclude the changes from my PR when reviewing this PR. 🙂

**Comment by hassaanelgarem** [comment]
Thanks @dvdchr 🙌

**Review by momo-ozawa — APPROVED** [review]
Works as described 🚀

**Pull request merged**
