### PR TITLE
Work around for issues with basic http auth. *** Do not merge til 4.7.1 ***

### LINKED ISSUE #3016: Multiple prompts to enter Basic HTTP Auth credentials
To reproduce:
Add a site that is secured with Basic HTTP Auth.  You will be prompted to enter credentials when you add the site to the app. 
Once added, tap to view the site's details screen (the list of posts, pages, comments, etc.) 
You will encounter multiple prompts to enter credentials, one for each request being made.  
View the post list and pull to refresh.  You are again prompted to enter credentials. 

It seems like every unique URL request eventually triggers the check `WPHTTPRequestOperation connection:willSendRequestForAuthenticationChallenge:` but subsequent requests of a previously requested URL do not.  I haven't gotten to the root of why subsequent requests do not show the prompt (maybe caching related?). 

Also, as far as I can tell we're not adding an authorization header to any request on the secured site and I'm not sure why we wouldn't be doing that. 

I used our site on bh.wpmt.co when testing.

### PR DESCRIPTION
**Pull request by aerych**
Closes #3016

cc @sendhil @jleandroperez

### CODE REVIEW

**Comment by sendhil** [comment]
As we discussed, lets hold off on merging this for now and instead merge it 4.7.1.

**Comment by aerych** [comment]
> lets hold off on merging this for now and instead merge it 4.7.1

:+1:  Would it be easier to leave this PR open and targeted at the 4.7 branch or close and resub later?

**Comment by jleandroperez** [comment]
@aerych (Maybe) we could rename the PR with the "DO NOT MERGE" legend, just for the sake of not loosing this from sight, and create a new PR once 4.7.1 branch is in place?

**Comment by aerych** [comment]
wfm!

**Comment by aerych** [comment]
Closing here. Retargeted in #3057.

**Pull request closed without merging**
