### PR TITLE
Add dark mode to acknowledgements

### PR DESCRIPTION
**Pull request by jkmassel**
Ensures that the autogenerated acknowledgements look right in dark mode. Screenshot is what it looks like:

Simulator Screen Shot - iPhone Xs - 2019-09-05 at 12 51 04

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
@jkmassel Is it just me or does the navigation bar title appear north of center vertically? Maybe it's because the navigation bars on some of these new sheets are 56pt tall? Either way, I think it would be nice to clean up.

Also, I'm not sure if it's limited to this view, but it looks like we're using a mix of brand and system grays – especially on the navigation and bottom toolbars – so the tints clash a little.

Otherwise, looks good to me!

**Comment by mattmiklic** [comment]
> Is it just me or does the navigation bar title appear north of center vertically?

Yeah, would be good to fix this -- but it's like this in the current version too, fwiw, so not specific to this PR.

**Comment by jkmassel** [comment]
@iamthomasbishop  - it was an easy enough fix. Also got rid of the repeated "Acknowledgements" heading since I was in there.

Simulator Screen Shot - iPhone Xʀ - 2019-09-06 at 09 54 37

**Comment by iamthomasbishop** [comment]
@jkmassel awesome! Thanks for the fix! It looks aligned to me:

D701414C-1D1D-4ECE-895C-993543DE7F0D

**Comment by iamthomasbishop** [comment]
Ah, maybe the text **is** 1pt south of center, but it could be something with line height?

**Comment by jkmassel** [comment]
It's possible! I think this component needs adjustment for the new popover style, so it might make more sense to adjust it in that PR – the component is used elsewhere so I'd rather not risk breaking it at this point? 

WDYT?

**Comment by iamthomasbishop** [comment]
Definitely makes sense to adjust separately 👍

**Comment by mattmiklic** [comment]
Agreed; actually it looks pretty close to perfect to my eyes already. The modal sheet presentation is a lot nicer than the previous full-screen view.

**Pull request merged**
