### PR TITLE
Edit Comment: add initial view

### PR DESCRIPTION
**Pull request by ScoutHarris**
Ref: #17000 

This adds an initial new `Edit Comment` view. 
- It has sections for each editable field.
- The actual fields are empty and not editable yet.
- The nav bar `Cancel` and `Done` buttons simply dismiss the view for now.
- Display is controlled by the `newCommentEdit` feature flag, which is disabled by default.

To test:

---
With `newCommentEdit` enabled:
- Go to My Site > Comments > Comment details > Edit.
  - Verify the new edit view is displayed.
- Go to Notifications > Comments > Notification details > Edit. 
  - Verify the new edit view is displayed.

| iPhone | iPad |
|--------|-------|
| iphone | ipad |

---
With `newCommentEdit` disabled:
- Go to My Site > Comments > Comment details > Edit.
  - Verify the existing edit view is displayed.
- Go to Notifications > Comments > Notification details > Edit. 
  - Verify the existing edit view is displayed.

edit_old

---

## Regression Notes
1. Potential unintended areas of impact
N/A. Feature is incomplete and disabled.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A. Feature is incomplete and disabled.

3. What automated tests I added (or what prevented me from doing so)
N/A. Feature is incomplete and disabled.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @mattmiklic . I wasn't sure if the new Edit Comment view should be a modal or not. The old one is, and I think that works well, at least on iPad. So I left it that way. But let me know if you think otherwise.

**Comment by mattmiklic** [comment]
> Hey @mattmiklic . I wasn't sure if the new Edit Comment view should be a modal or not. The old one is, and I think that works well, at least on iPad. So I left it that way. But let me know if you think otherwise.

Yep, that's correct. In the designs I'd mocked it up as a fullscreen modal rather than a sheet, but there's functionally not a big difference and this should be fine.

**Comment by ScoutHarris** [comment]
Thanks @mattmiklic .

> In the designs I'd mocked it up as a fullscreen modal rather than a sheet

Yea, I totally didn't get fullscreen vs sheet 🤦. Sorry! I'll make that change in the next PR.

**Comment by mattmiklic** [comment]
No problem; thanks!

**Comment by ScoutHarris** [comment]
Since @dvdchr hasn't reviewed this yet, I went ahead and updated it to show the new edit view in a full screen modal. Note the nav bar background matches what the app uses, not what's in Zeplin.

**Review by dvdchr — APPROVED** [review]
Tested on iPhone and iPad. Everything looks good! 👍  :shipit: 

- [x] Go to My Site > Comments > Comment details > Edit. Verify the new edit view is displayed.
- [x] Go to Notifications > Comments > Notification details > Edit. Verify the new edit view is displayed.

**Comment by ScoutHarris** [comment]
Thanks @dvdchr !

**Pull request merged**
