### PR TITLE
Merge 18.6 version published to the Store into `trunk`

### PR DESCRIPTION
**Pull request by mokagio**
This supersedes https://github.com/wordpress-mobile/WordPress-iOS/pull/17458 to ensure we only merge the code that we actually shipped.

I already started and submitted the 18.6.1 hotfix, see https://github.com/wordpress-mobile/WordPress-iOS/pull/17471. I'll open the 18.6.1 into `trunk` PR after this has been merged.

- [x] WordPress submitted for App Store Review
- [x] Jetpack submitted for App Store Review
- [x] WordPress approved by Apple and started phased release
- [x] Jetpack approved by Apple and started phased release

### CODE REVIEW

**Comment by AliSoftware** [comment]
I'm on my iPad so not the easiest to check this in more details right this moment but I'm surprised to see that the list of commits in this PR contains commits from 1 month ago… while we're supposed to merge into trunk every sprint aka every 2 weeks? 🤔

**Comment by mokagio** [comment]
Good catch! 🤔

**Review by AliSoftware — APPROVED** [review]
Ok I _think_ I finally managed to make sense of why there were some old commits from 1 month ago in the commit list of this PR.

The commits from #17221, some of which being pushed in that PR back in Oct 5, finally got merged in `develop` on Oct 19, i.e. right after `release/18.5` was cut on Oct 18.
So despite that PR containing commits older than 1 month, they didn't make it to 18.5, and instead shipped in `18.6`.

This can be confirmed by GitHub by opening the page for [the first commit of this PR (and of 17221 too)](https://github.com/wordpress-mobile/WordPress-iOS/pull/17221/commits/679fec9c4cf16c5dddfc937859f8c1981f2efea9) which shows that the commit was only part of tags `18.6` and `18.6.1` but not `18.5`

trunk-commits

So everything seems ok after all! :shipit:

**Comment by mokagio** [comment]
Ah! Thanks @AliSoftware 🎉 

I've failed to make up some time to go on that investigation, I'm very grateful you went out of your way for it.

:shipit:

**Pull request merged**
