### PR TITLE
Reader Comments: Fixes stackview alignment setting so label isn't cropped

### LINKED ISSUE #6567: Reader Comments: Timestamp labels are cropped vertically
When viewing comments in the Reader, any descenders on the timestamp label are cropped off:

img_0111

##### Tested on iPad Pro 9.7", iOS 10.3 (beta), WPiOS 6.9.0.20170203

cc @aerych

### PR DESCRIPTION
**Pull request by aerych**
Fixes #6567 
The stackview for the header had its alignment set to fill which ended up cropping the label.  This PR changes that setting to `top` allowing the stackview to accommodate the full label height. 

To test:
View reader comments and confirm that the date label is no longer cropped

Needs review: @frosty would you do the honors?

### CODE REVIEW

**Comment by frosty** [comment]
Hey @aerych!

So this fixes the issue – the label is no longer collapsed. But I wonder, do we want the baselines of the timestamp and the gravatar image to be aligned? Here's a before and after:

reader-comment-label

**Comment by aerych** [comment]
> do we want the baselines of the timestamp and the gravatar image to be aligned?

Many thanks for those keen eyes of yours, sir.  I've changed the alignment from "top" to "center".  This keeps the timestamp from appearing below the gravatar.  I think centering is the way to go as aligning the baseline would position things a tad too low. 
Ready for another peek.

**Comment by frosty** [comment]
Looks good! :shipit:

**Comment by aerych** [comment]
Thanks @frosty !!!

**Pull request merged**
