### PR TITLE
Build improvements - tests, CocoaPods, project config

### LINKED ISSUE #4783: Multiple tests not part of the WordPressTest target
There are a handful of tests that are not part of the test target and therefore aren't being executed. Enable, fix or delete.

* SettingsViewControllerTest (probably will be handled in #4740)
* CoreDataConcurrencyTest
* LocalCoreDataServiceTests

### LINKED ISSUE #4794: Modernize Cocoapods integration to help speed up builds
There might be a small configuration issue with how CocoaPods is integrated into WPiOS. Remove all traces of CocoaPods and do a fresh install/create of the workspace folder. Also remove the previous hacks for things like #2917.

### LINKED ISSUE #4795: Set the iOS deployment target version at the root project level

### PR DESCRIPTION
**Pull request by astralbodies**
Fixes #4783 
Fixes #4795 
Fixes #4794 

* Sets the iOS deployment target at the root project level to iOS 9.0. It was previously unset and I believe causing some problems with HockeyApp allowing users on iOS 8 to install it.
* Modernizes the CocoaPods integration to use the most recent install config. I removed all traces of CocoaPods including the workspace directory and installed fresh. This should help with some strange build order issues causing a slowdown in build times.
* Re-enables a test that was previously disabled and deletes a legacy Core Data test that was not in use.

Please make sure to test deployment to an actual device as this has affected the Today Extension as well.

Needs Review: @bummytime, @jleandroperez

### CODE REVIEW

**Comment by jleandroperez** [comment]
Fixes #2920 as well. Verifying that right now, thanks Aaron!!!

**Comment by jleandroperez** [comment]
Unit tests cleanup / missing in target verified. All green!

**Comment by jleandroperez** [comment]
App Installation Workaround confirmed not to be required anymore. *Pure awesomeness!!!*

Thanks for tackling this one Aaron!!

:shipit: on my side

**Comment by bummytime** [comment]
9.0 target is set, tests are green, deployment to device is :+1: Nice work @astralbodies!

:shipit:

**Comment by astralbodies** [comment]
Thanks for the reviews @jleandroperez and @bummytime!

**Pull request merged**
