### PR TITLE
Gravatar Picker: replace No Results view

### LINKED ISSUE #9902: Gravatar Picker: replace No Results view
In the Gravatar Picker, replace `WPNoResultsView` with `NoResultsViewController`.

The No Results view is displayed when the user has no media.

Current view:
old_nrv

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #9902 

In the Gravatar Picker, replace `WPNoResultsView` with `NoResultsViewController`.

The No Results view is displayed when the user has no media.

The idea here is to replace `MediaNoResultsView` with `NoResultsViewController+MediaLibrary` (which was introduced in #9897). `MediaNoResultsView` will be removed once all relevant ViewControllers are updated.

**To test:**

---
**No Media - device with camera:**
- On an actual device, go to Me and tap on the user icon.
- The initial view is Selfies. If you don't have any, you'll see the following view. 
- If you do have Selfies, tap Albums and pick one that has no media.

camera_new_nrv

---
**No Media - device with no camera (or simulator):**
- Follow the same steps as above.
- Verify the view is:

no_camera_new_nrv

### CODE REVIEW

**Comment by aerych** [comment]
Howdy @ScoutHarris 👋 
When testing I noticed some console logs about breaking constraints. For example:
```
2018-08-03 09:14:39.657361-0500 WordPress[96818:2158682] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x604000686a40 UILayoutGuide:0x6040001aa9c0'UIViewSafeAreaLayoutGuide'.trailing == UIView:0x7fb5b6e47080.trailing + 10   (active)>",
    "<NSLayoutConstraint:0x604000686cc0 UIView:0x7fb5b6e47080.centerX == UILayoutGuide:0x6040001aa9c0'UIViewSafeAreaLayoutGuide'.centerX   (active)>",
    "<NSLayoutConstraint:0x60000069f220 'UIView-Encapsulated-Layout-Width' UIView:0x7fb5b6daac10.width == 0   (active)>",
    "<NSLayoutConstraint:0x604000686ae0 'UIViewSafeAreaLayoutGuide-left' H:|-(0)-[UILayoutGuide:0x6040001aa9c0'UIViewSafeAreaLayoutGuide'](LTR)   (active, names: '|':UIView:0x7fb5b6daac10 )>",
    "<NSLayoutConstraint:0x604000686bd0 'UIViewSafeAreaLayoutGuide-right' H:[UILayoutGuide:0x6040001aa9c0'UIViewSafeAreaLayoutGuide']-(0)-|(LTR)   (active, names: '|':UIView:0x7fb5b6daac10 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x604000686cc0 UIView:0x7fb5b6e47080.centerX == UILayoutGuide:0x6040001aa9c0'UIViewSafeAreaLayoutGuide'.centerX   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful. 
```


Maybe we need to `translatesAutoresizingMaskIntoConstraints = NO;` somewhere?

**Comment by aerych** [comment]
Tested both scenarios and works as advertised :)  It would be nice to fix the constraint issue and then we can :shipit: :)

**Comment by ScoutHarris** [comment]
Hey @aerych . 

> When testing I noticed some console logs about breaking constraints.

🤦‍♂️ 

A quick check confirmed I broke the constraints well before this, 3 views ago. @frosty noticed it too on a related PR. Would you mind if I address it separately? I'll want to ensure I fix it for all the views.

**Comment by aerych** [comment]
Sounds good to me :)   :shipit: when ready!

**Comment by ScoutHarris** [comment]
Thank you!!

**Pull request merged**
