### PR TITLE
Conditionally include HockeyApp for internal builds only

### LINKED ISSUE #5053: Do not include HockeySDK pod in non-internal builds
Update the Podfile and conditionally exclude any HockeySDK code from the app for non-internal release builds.

### PR DESCRIPTION
**Pull request by astralbodies**
Fixes #5053 

To test:
Build for debug, archive for App Store and archive for Internal. Ensure no compilation errors and inspect bundles to check for HockeyApp artifacts. 

It does feel a little dirty having a couple conditionals based on a preprocessor macro.

Needs review: @sendhil, @koke

### CODE REVIEW

**Comment by astralbodies** [comment]
You will have to wait for #5046 to get merged or cherry pick that commit into the branch to test archiving the internal build.

**Comment by koke** [comment]
> It does feel a little dirty having a couple conditionals based on a preprocessor macro.

How about something like #5060?

**Comment by astralbodies** [comment]
Merged in @koke's implementation into this PR for review. Thanks :smile:

**Comment by sendhil** [comment]
Still getting that error we talked about :\

**Comment by astralbodies** [comment]
@sendhil I merged in develop which had a few provisioning profile updates. Can you try again? You may want to delete all of the profiles from your machine and refetch them.

**Comment by sendhil** [comment]
:shipit:

**Pull request merged**
