### PR TITLE
Removes unused image assets from the AppImages collection.

### LINKED ISSUE #4700: Remove unused image assets.
This week I've been working on replacing the existing icons in the app with <a href="https://github.com/Automattic/wp-calypso/blob/a7478174b0441760c332fcb4b8c454f5b8d73dfc/docs/icons.md">Gridicons</a>. In order to do this, I've audited the assets in  `AppImages.xcassets` to discover where in the code each image is currently being used.

The following assets appear to be unused and can be safely deleted.

- action-icon-followed
- action-icon-replied
- action-icon-success
- blueArrow (part of EGORefreshTableHeaderView, which seems unused)
- date_picker_selected
- date_picker_unselected
- default-identicon
- doneButton
- icon-check-small-blue
- icon-check-small-white
- icon-check
- icon-left-chevron
- icon-media-edit-grab
- icon-media-multiselect-deselect
- icon-reader-visit-highlight
- icon-reader-visit
- icon-reader-x-post
- icon-themes-sort
- icon-toolbar-share
- icon-whats-new
- keyboardButton
- keyboardClose
- logo_wpcom
- media_checkbox_empty
- media_checkbox_filled
- media_image
- movie
- NNGPlusActivity
- NNInstapaperActivity
- NNPocketActivity
- NNReadabilityActivity
- note_header_shadow
- notifications-more
- reader-postaction-comment-active
- reader-postaction-comment-blue
- reader-postaction-comment
- reader-postaction-like-active
- reader-postaction-like-blue
- reader-postaction-like
- reader-postaction-reblog-active
- reader-postaction-reblog-blue
- reader-postaction-reblog-done
- reader-postaction-reblog
- reader-postaction-tag
- redoDisabled
- Safari
- sync
- transparent-point
- ui-line-dark
- ui-line
- UIButtonBarTrash
- undoDisabled
- uploading_spin_blue
- uploading_spin_red
- video_play
- welcome_bg
- welcome_button_bg_full_highlighted
- welcome_button_bg_full
- welcome_button_bg
- wp_vid_placeholder

These assets have generic names, which made it difficult for me to determine whether they are being used or not. I *don't believe* that they are, however.

- approve
- attachment
- autosave
- background
- blockquote
- bold
- down
- help
- italic
- left
- link
- list
- lock
- next
- photos
- preview
- read
- redo
- right
- settings
- stats
- unapprove
- undo
- up
- write

If anyone has any suggestions on how to thoroughly search for the generically-named images, or knows of any reason why we might need to keep some of the images I believe are being unused, please let me know.

### PR DESCRIPTION
**Pull request by kurzee**
Cleaned up the AppImages collection of assets that were old and unused.

There are a still few assets that currently don't have any references but appear recently added and intended for use (Plans icons, for example). Additional gridicon assets remain that are currently unused, but I'd say should be left for now as we continue to expand their usage.

Resolves #4700 

Needs review: @frosty Please review. Do you have any testing/validation ideas for ensuring none were removed that shouldn't be? Please take a look at the changes and let me know if anything stands out.

@mattmiklic Of the remaining image assets in the app, you'll see a few PNGs that could use a PDF versioning for a future PR.

### CODE REVIEW

**Comment by mattmiklic** [comment]
Red is my favorite color! :heart: 

screen shot 2016-04-01 at 5 21 28 pm


@mattmiklic Of the remaining image assets in the app, you'll see a few PNGs that could use a PDF versioning for a future PR.

:+1:

**Comment by kurzee** [comment]
Updating this to not ready for review. I'm putting together a solution to review asset deletions like this since we'll likely have a few more of these down the line.

**Comment by frosty** [comment]
Cool, thank you @kurzee!

**Comment by kurzee** [comment]
I've done some experimenting with an approach for reviewing deleted image assets and worked up an experimental shell script: https://github.com/wordpress-mobile/WordPress-iOS/pull/5074/commits/8906cd6565f47e304b5cebed36d10062474276b7

This script can be run with:

`./review-deleted-images-for_commit.sh f70dc70 WordPress-iOS/WordPress/Classes`

1. The first argument being the hash of the commit that deleted the images assets.
2. The second argument benig the directory the script should run the check on, but could be the base project directory if needed.

The idea is that the script works as a review aide by listing warnings for deleted assets that may still be used in the project (or search directory). So rather than a reviewer having to double check each removed asset by hand, they could instead reference the output warnings and run their own search on the project to double check the warning assets are indeed unused.

@frosty what do you think about this approach? I'm not 100% sold on this, but then again we ideally wouldn't delete this many assets at once again.

**Comment by frosty** [comment]
Thanks for putting the script together, @kurzee! It was a great start for verifying the images – I searched through the project for any warnings it flagged up and couldn't see any usages, so I think we're good to go. 

Incidentally, I found this was a good set of search criteria to use to limit the amount I had to look through:

screen shot 2016-04-05 at 10 55 25

The script worked well. I think there were one or two things it missed (cases where the asset name doesn't match the image name, and cases where the image is prepended with `~ipad`) but you're right – this isn't a situation that's going to come up very often, and it's a helper tool rather than a do-all tool.

:shipit:!

**Comment by frosty** [comment]
Actually, one last thing – I noticed that `WPNUXBackButton.m` has some references in comments to `btn-back` and `btn-back-tapped` which have both been removed, if you fancied cleaning that up a little ;)

**Comment by frosty** [comment]
I ran the project back through Slender and it flagged two extra images that it thinks we're not using:

* `notifications-more`
* `icon-check` (we use `icon-check-blue` in `WPWalkthroughOverlayView`, but I can't see this one anywhere)

**Comment by kurzee** [comment]
@frosty pushed a couple of commits, can you take one more peak?

> Actually, one last thing – I noticed that WPNUXBackButton.m has some references in comments to btn-back and btn-back-tapped which have both been removed

I went ahead and updated those comment references.

> notifications-more
> icon-check (we use icon-check-blue in WPWalkthroughOverlayView, but I can't see this one anywhere)

I went ahead and removed these two assets as well.

I also renamed the script file, if you run it again.

> The script worked well. I think there were one or two things it missed (cases where the asset name doesn't match the image name, and cases where the image is prepended with ~ipad) but you're right – this isn't a situation that's going to come up very often, and it's a helper tool rather than a do-all tool.

I think that's where a script like this would likely get fairly complicated and then being error prone to changes. I'll go ahead and leave the script in the project for now and we can reference it as we continue to remove PNGs and reuse PDFs. Seems like a great review flow between the script and your project searching example.

**Comment by kurzee** [comment]
One more note for history on this PR. The Xcode search feature makes me nervous for 100% validation of changes as I've been bitten in the past between either indexing delays or search result misses for content that was indeed in a project (likely just a bug of some kind).

**Comment by frosty** [comment]
Yep, and the other place we could be bitten is if a Pod was using an asset that's in the main project (I think WPStyleGuide does this?). 

Changes look good – let's :shipit:

**Comment by kurzee** [comment]
Thanks for the great review @frosty!

**Pull request merged**
