### PR TITLE
ActivityLog: add detail view.

### PR DESCRIPTION
**Pull request by jklausa**
Adds detail view to display after tapping on an item in Activity Log. 

(after tearing my hairs out debugging autolayout/tableView issue here for 3h I realised that this isn't necessarily a tableView and after rewriting this into bunch of `UIStackView`s, it's now magic)

Here's how it looks like: 

simulator screen shot - iphone 8 plus - 2018-04-20 at 09 40 47
simulator screen shot - iphone 8 plus - 2018-04-20 at 09 40 28

To test:
1. Open activity log
2. Tap on an item
3. Verify that it looks like on designs

### CODE REVIEW

**Comment by jklausa** [comment]
@elibud reassigning the review to you, since @nheagy is AFK for the next few days

**Comment by dmsnell** [comment]
awesome @jklausa! hey what "detail view" are you talking about? can we get some screenshots in here? have you interacted with the Activity Log teams to coordinate what views are being built?

> It seems like the roles, like we get them from the API are not properly cased (administrator vs Administrator) @dmsnell where can I report this?

@elibud I don't know what right and wrong are. the best place to raise it would be as a p2 post. How are they being used? how do we know they are wrong? why not just capitalize them in the client?

**Comment by jklausa** [comment]
Now with 100% more storyboards! (I'll put the main Activity Log VC in storyboard next, wanted to get this out of the way first.)

@elibud do you have time to look at this or would you rather me ping someone else?

I've gone ahead to locally capitalise the `role` field, so no changes from backend required on that front.

**Comment by elibud** [comment]
@etoledom can you check if the choices made here work fine with your recent accessibility work?

**Comment by etoledom** [comment]
Sure! Here are my findings

## Right to Left Layout
It's working great! 🎉

## Voice over:
As it is it would work, but we could make it a bit more friendly:

voiceover

## Dynamic type:
This one is mostly working. All fonts will adjust to changes but not `live` (it needs to recreate the controller to adopt the changes)

Be sure to ✅ the `Automatically Adjust Font` option in the storyboard when using the preferred text styes. That should solve most of the issues.

For labels that can't use preferred fonts, is good practice to refresh them inside `traitCollectionDidChange` as it's explained [here](https://github.com/wordpress-mobile/WordPress-iOS/wiki/Dynamic-type-guideline#how-to).

And a very small detail:
This horizontal layout could be a problem when `Accessibility font sizes` is activated.

horizontal

[Here](https://github.com/wordpress-mobile/WordPress-iOS/wiki/Dynamic-type-guideline#accessibility-content-size-category) you can find a simple way how we can fix these problems using stack views :)

----

I hope you can find this helpful!

**Comment by jklausa** [comment]
@etoledom Thanks so much for this!

Fixed the issues you mentioned — the VC now automagically adjusts to preferredContentSize changes,  has better support for VoiceOver:
untitled
and switches stackViews to vertical if the selected font size is in AX-category:
simulator screen shot - iphone 8 plus - 2018-04-20 at 22 58 41


@elibud ready for another look!

**Comment by jklausa** [comment]
(I'm surprised how much I like the vertical layout on this screen!)

**Comment by elibud** [comment]
On an unrelated matter, rewind was not working for my site, can you double check if that's still working and if not trouble shoot it? Thx

**Comment by jklausa** [comment]
@elibud Thanks for the review! I'm working with the rewind code next, so I'll definitely get that fixed up :)

**Pull request merged**
