### PR TITLE
Fix crash on Notifications tab when device is offline

### LINKED ISSUE #15873: EXC_BAD_ACCESS: Exception 1, Code 1859272688, Subcode 8 >
**Sentry Url**: https://sentry.io/share/issue/5ab5aaf422374306b9ef30690a2b485c/
**User Count**: 116
**Count**: 235
**First Release**: 16.5.0.3
**First Seen**: 2021-01-22T17:53:24Z
**Last Seen**: 2021-02-11T21:41:36Z
**24 Hours**: 35
**30 Days**: 234
**LogID:** 2AB81A27-8107-4798-9D24-5F8F874BE2BE

```
EXC_BAD_ACCESS: Exception 1, Code 1836482496, Subcode 8 >
  File "Classes/Services/BlogService.m", line 822, in -[BlogService blogsWithPredicate:]
  File "Classes/Services/BlogService.m", line 811, in -[BlogService blogWithPredicate:]
  File "Classes/Services/BlogService.m", line 39, in -[BlogService blogByBlogId:]
  File "Classes/Services/SuggestionService.swift", line 131, in SuggestionService.persistedBlog
  File "SuggestionsTableView.swift", line 15, in SuggestionsTableView.userSuggestions
  File "null", line null, in SuggestionsTableView.userSuggestions
  File "<compiler-generated>", line null, in SuggestionsTableView.fetchSuggestions
  File "<compiler-generated>", line null, in SuggestionsTableView.fetchSuggestions
  File "Classes/ViewRelated/Suggestions/SuggestionsTableView.m", line 322, in -[SuggestionsTableView suggestions]
  File "Classes/ViewRelated/Suggestions/SuggestionsTableView.m", line 288, in -[SuggestionsTableView tableView:numberOfRowsInSection:]
...
(91 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by guarani**
The app crashed when the device was offline and the suggestions code (which handles Mentions and Cross-posts) returned a `nil` result. This result was interpreted by the `SuggestionsTableView` code as "suggestions haven't been fetched yet". The code, which has logic for fetching suggestions tied to the suggestions data source (a property), then entered an infinite loop of reloading the suggestions list.

The fix here is to undo an architectural decision made long ago to tie the fetching of suggestions to the suggestions data source. I've used `didMoveToSuperview` on the suggestions view as the trigger to fetch suggestions. This method, somewhat similar to `UIViewController`'s `viewDidLoad`, is called once each time the suggestions UI is shown.

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/15873

### To test

**Note: While testing, you might notice inconsistencies with regard to offline support for suggestions. If you come across any, please check https://github.com/wordpress-mobile/WordPress-iOS/issues/15919 to ensure they are already tracked.**

```
- [ ] Reproduce the crash on 16.7 beta
- [ ] Verify the crash is fixed on this branch
- [ ] Regression testing
```

#### Reproduce the crash on 16.7 beta

To ensure the fix addresses the bug, first download the 16.7 beta from TestFlight (any 16.7 build is fine). Log in to the app and before doing anything else, turn off the device wifi and data connections. Then tap the Notifications tab and expect the app to crash.

#### Verify the crash is fixed on this branch

Download the build from this PR and repeat the same steps as above, expect no crash to occur.

#### Regression testing

Mention suggestions should work just as they did before this bug fix was applied. Check mentions in Reader, the Block editor, Notifications replies, comments (My Site > Comments), etc.

Cross-post suggestions – which are available by typing the `+` character (or long-pressing the toolbar button labelled with an @-symbol) in a post on a site that has the O2 plugin installed (e.g. [P2 sites](https://wordpress.com/p2/) – should continue to work as before. These are only available within the Gutenberg editor (not in other places such as comments, replies, etc).

Expect a slight network delay the first time suggestions are displayed for a particular site. However, if they are displayed before one minute has passed, they should be shown immediately.

Suggestions (mentions and cross-posts) should be available when the device is offline, _if_ they were used previously while the device was online.

### PR submission checklist

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
Tested build 42500:

- [x] Reproduce the crash on 16.7 beta
- [x] Verify the crash is fixed on this branch
- [x] Regression testing

✅ Tested mentions in notifications, block editor, Reader and site comments
✅ Tested suggestion throttle
✅ Tested suggestions while offline (only noticed known issues tracked in https://github.com/wordpress-mobile/WordPress-iOS/issues/15919)

**Comment by guarani** [comment]
Just noting @illusaen that it's best to test this change locally instead of using [the build made by CircleCI](https://github.com/wordpress-mobile/WordPress-iOS/pull/15916#issuecomment-781496289), since the installable build workflow on CircleCI is broken due to an unrelated issue (https://github.com/wordpress-mobile/WordPress-iOS/pull/15932) that hasn't been merged back into `develop` yet.

**Review by illusaen — APPROVED** [review]
Looking good!

**Comment by guarani** [comment]
Thank you, @illusaen!

**Pull request merged**
