### PR TITLE
Jetpack Focus: Update raw screenshots

### PR DESCRIPTION
**Pull request by momo-ozawa**
Part of #18960

## Description
- Added new mocks to API-Mocks
- Updated raw screenshots generated in the `JetpackScreenshotTarget` to match new design specs (ref: pcdRpT-z4-p2#comment-731)
- Refactored the `removeApp()` method to accept an app name as a parameter

## Note
- ⚠️ This PR doesn't handle iPads yet. The notification screenshot flow fails on iPads -- I'll address this in a separate PR

## How to test

1. Run `rake mocks`
2. Switch to the `JetpackScreenshotGeneration` target
3. Run `testGenerateScreenshots()` on an iPhone simulator
4. ✅ Verify: tests succeed and the screenshots match design specs
5. Run `testGenerateScreenshots()` again
6. ✅ Verify: tests succeed and the screenshots match design specs

1 | 2 | 3 | 4 | 5 
-- | -- | -- | -- | --
Simulator Screen Shot - iPhone 13 - 2022-07-21 at 15 37 24 | Simulator Screen Shot - iPhone 13 - 2022-07-21 at 15 37 32 | Simulator Screen Shot - iPhone 13 - 2022-07-21 at 15 37 38 | Simulator Screen Shot - iPhone 13 - 2022-07-21 at 15 37 44 | Simulator Screen Shot - iPhone 13 - 2022-07-21 at 15 40 07

## Regression Notes
1. Potential unintended areas of impact
- WordPressScreenshotGeneration

2. What I did to test those areas of impact (or what existing automated tests I relied on)
- Ran the WordPressScreenshotGeneration target manually

3. What automated tests I added (or what prevented me from doing so)
- n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mokagio** [comment]
@momo-ozawa sorry I didn't get a chance to test this before the 20.4 code freeze 😞 

I'm going to bump it to 20.5 under the assumption that we'd want to update both iPhone and iPad screenshots in one go, and since this one doesn't address iPad, we'd need to wait for that future PR anyway.

But, I can see a path to faster feedback where we update the iPhone screenshots first. In such cases, we should merge this in 20.4 and run the automation there. (I think the automation works now after Olivier's recent work, but I'd have to double check).

What do you think? I'm happy with both options.

I'll try to review this today-tomorrow. Thanks!

**Comment by momo-ozawa** [comment]
@mokagio 👋 

No worries -- 20.5 sounds good to me!

**Review by hassaanelgarem — COMMENTED** [review]
I've tested this and I've encountered two cases where the test fails.
1. If the Jetpack is already installed on the simulator, the test fails at the beginning, not sure if that's expected? (Maybe we can add a conditional step to delete the app if it exists?)
2. 4 out of 5 times, the test has failed for me during the teardown. Specifically when trying to delete the app. I've attached screenshots of the error and where the test ends. I'm using Xcode 13.3 with iPhone 13 Pro iOS 15.4 simulator.

Error | Last State
-|-
Screen Shot 2022-07-26 at 2 53 05 PM|

Besides these two issues, the screenshots generated are as expected 🚀

**Comment by enejb** [comment]
I tested this and it worked as expected for me!

**Comment by momo-ozawa** [comment]
@hassaanelgarem 👋 

> If the Jetpack is already installed on the simulator, the test fails at the beginning, not sure if that's expected? (Maybe we can add a conditional step to delete the app if it exists?)

Done! dbea6f7

> 4 out of 5 times, the test has failed for me during the teardown. Specifically when trying to delete the app. I've attached screenshots of the error and where the test ends. I'm using Xcode 13.3 with iPhone 13 Pro iOS 15.4 simulator.

Hmmm. I'm on Xcode 13.4.1 / iOS 15.5. I tested 5 times consecutively and found no issues on teardown. I can add a note on the parent issue to keep track of the teardown issue -- wdyt?

**Review by hassaanelgarem — APPROVED** [review]
>  I tested 5 times consecutively and found no issues on teardown. I can add a note on the parent issue to keep track of the teardown issue

Yeah that sounds good 👍

---

:shipit:

**Pull request merged**
