### PR TITLE
Update Reader Card Design

### PR DESCRIPTION
**Pull request by emilylaguna**
**Fixes** #14005

**Subtasks:**
- [X] Relative Date Formatter: https://github.com/wordpress-mobile/WordPress-iOS/pull/14186
- [x] Update cross post design: https://github.com/wordpress-mobile/WordPress-iOS/pull/14207

This applies the new reader card design in both dark and light modes. 

### Light Mode
| Before | After |
|---|---|
|  before-discover-light | Simulator Screen Shot - iPhone 11 Pro - 2020-05-25 at 19 36 39 |

### Dark Mode
| Before | After |
|---|---|
| before-discover-dark|Simulator Screen Shot - iPhone 11 Pro - 2020-05-25 at 19 36 19|

### Other Card States

| Default | Text Only | Photo and title only | 
|---|---|---|
| Screen Shot 2020-05-25 at 7 38 41 PM|Screen Shot 2020-05-25 at 7 43 14 PM |Screen Shot 2020-05-25 at 7 44 58 PM|

| Photo Only | No site icon w/ comments disabled | Title only |
|---|---|---|
|Screen Shot 2020-05-25 at 7 46 18 PM|Screen Shot 2020-05-25 at 7 46 48 PM|Screen Shot 2020-05-25 at 7 41 56 PM|

### Other Devices
| iPhone 5s | iPad |
|---|---|
| Simulator Screen Shot - iPhone 5s - 2020-05-25 at 20 07 13 | Simulator Screen Shot - iPad Air (3rd generation) - 2020-05-25 at 20 11 02|

### Notes
- This does not include the updated relative time logic yet
- The action icons on the discover view are disabled even though when you tap on the post itself its enabled. This is because the discover post itself has comments disabled, but when you tap on it, it loads the attributed post.
- Some elements have not been updated such as the attribution label since the design wasn't updated for them yet.

## To test:
1. Launch the app
2. Tap on the Reader tab
3. Tap on any section
4. Scroll and make sure the card content and design matches
5. Close the app
6. Enter dark mode
7. Follow steps 1 - 4 to make sure the card looks good in dark mode

## PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by emilylaguna** [comment]
@leandroalonso I applied the following fixes:
| Changed how I was laying out the domain/date with the separator to better support RTL languages |
|---|
|Screen Shot 2020-05-26 at 12 49 06 PM|

| iPad button titles now display for all buttons |
|---|
|Screen Shot 2020-05-26 at 12 49 52 PM|

| Image aspect ratio now displays correctly |
|---|
|Screen Shot 2020-05-26 at 12 51 17 PM|

| Added more padding between the site name and byline|
|---|
|Screen Shot 2020-05-26 at 12 51 32 PM|

| Blog title font is the system serif font (New York) On iOS 13+ and Noto for 12 and below |
|---|
| Screen Shot 2020-05-26 at 12 54 06 PM|


| Changed blog summary size to `footnote` |
|---|
|  Screen Shot 2020-05-26 at 12 55 12 PM |


| Replaced the comment icon with just the outline |
|---|
| Screen Shot 2020-05-26 at 12 55 45 PM |

**Comment by mbshakti** [comment]
Thanks for getting the next build out so quickly :)) A couple of nits:

- Something about the post header (site name, site icon, URL) felt off but I couldn’t tell what exactly. I think it might be because I’m using a slightly bigger font size for the URL in the mock up, and the build site URL font size is smaller. I’m using “Caption 1” style from the iOS type scale; the build seems to be using the “caption 2” style, can you confirm if that’s correct? If it is, can we please use Caption 1 instead?  If you are using "caption 1" feel free to ignore this...

- What’s the size of the site icon? In the mocks, it’s 40x40pts. I took a screenshot from the build into Figma, looks like around ~35x35pts. Can you confirm if that is so? If it’s 35, can we change it to match 40pt instead of 35pt?

- The post actions icon size seems smaller (seems around ~16pt?). In the mock ups, I’m using 18pt x 18pt. 

- The comment icon seems to have a thinner stroke outline relative to the other icons in the post actions. I think having a stroke of 1.5 instead of 1 should fix this.

- Can we keep the attribution text on the discover postcards the same font size and color as the body / excerpt text? 

- What's the padding above the post actions? In the mock ups, I'm maintaining a 24pt top padding. In the build, it looks like it's 16pt? If it's 16pt, can we change to 24pt please? 

Thanks a lot!

**Comment by emilylaguna** [comment]
@mbshakti 
> What’s the size of the site icon? In the mocks, it’s 40x40pts. I took a screenshot from the build into Figma, looks like around ~35x35pts. Can you confirm if that is so? If it’s 35, can we change it to match 40pt instead of 35pt?

I can confirm it is 40x40: 

**Screenshot from my device:** 
Screen Shot 2020-05-27 at 7 01 52 AM

**Screenshot from the interface builder itself**
Screen Shot 2020-05-27 at 7 01 27 AM

**Comment by emilylaguna** [comment]
> The post actions icon size seems smaller (seems around ~16pt?). In the mock ups, I’m using 18pt x 18pt.

The size I'm using for the icons is 18x18, I'll change it to 20x20 in code to make them slightly bigger.

**Comment by emilylaguna** [comment]
> Something about the post header (site name, site icon, URL) felt off but I couldn’t tell what exactly. I think it might be because I’m using a slightly bigger font size for the URL in the mock up, and the build site URL font size is smaller. I’m using “Caption 1” style from the iOS type scale; the build seems to be using the “caption 2” style, can you confirm if that’s correct? If it is, can we please use Caption 1 instead? If you are using "caption 1" feel free to ignore this...

I can confirm that I am using `caption1` for the url section: 
Screen Shot 2020-05-27 at 9 05 44 AM

**Pull request merged**
