### PR TITLE
Fixes a crash due to an unregistered cell in Stats Insights

### PR DESCRIPTION
**Pull request by Gio2018**
This PR adds `ViewsVisitorsRow` among the registered cells in `SiteStatsInsightsTableViewController`. Note that this registration would happen if the `statsNewInsights` feature flag was enabled, but it would seem that the cell is still used even if the same feature flag is disabled.

I observed the event specifically on iPad.

@sla8c , @Guarani, @frosty  not sure this was due to some wip in the stats revamp project, so it might require more work, but we should make sure the crash does not go into the next release.

Fixes #NA

To test:

- checkout/build/run another branch on iPad
- Play around with stats, switch between insights and days then insights again, switch to another item (e.g. Posts), then go back to Stats: you should observe a crash due to an unregistered `ViewsVisitorsLineChartCell`
- checkout/build/run this branch on iPad
- Repeat the test: the crash should not occur anymore

## Regression Notes
1. Potential unintended areas of impact
It should be fine, looks like we are registering a cell that was needed.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Since this might be an effect of an ongoing project, I asked review from the team that's working on that project

3. What automated tests I added (or what prevented me from doing so)
none

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mokagio** [comment]
I'll be starting the 19.9 code freeze soon. Given this "fixes a crash" I think it ought to be part of 19.9. We'll ship a new beta for this once merged 👍

**Comment by sla8c** [comment]
Hey @Gio2018 thanks for raising this.  I tried to duplicate the crash but unfortunately I wasn't able to using iPad simulator and iPhone device.  I took a deeper look though and I think I don't need to FeatureFlag this though
I've made that change and I've pushed an update to this branch.  I've changed the reviewer to @frosty for my change as well (hope that's ok re: process)

**Comment by frosty** [comment]
After chatting to @sla8c, I was able to recreate this – I think it may need you to have previously run the app on the same device before applying the latest trunk but I'm not 100% sure.

I think the registering of the cell isn't actually required, and there's a different underlying issue that needs to be resolved.

The new `viewsVisitors` insight type was added to the top of the `InsightType` enum, which means it replaces the existing value 0 (which was `growAudience`). If a user had an existing `growAudience` card, the new code will match that to a `viewsVisitors` row and try to display that. I think it'll also have the knock-on effect of all of the user's insights cards being off-by-one and displaying the wrong type.

I think the best fix is likely to be to move the new `viewsVisitors` type to the end of the `InsightsType` enum (same goes for any other new cards we add).

Thanks for raising this, @Gio2018!

**Comment by sla8c** [comment]
I've made this change tried to test / break this exhaustively + have pushed the change.  Thanks @frosty !

**Review by frosty — APPROVED** [review]
This looks good to me, although @Gio2018 I'd appreciate if you have time to confirm!

**Comment by Gio2018** [comment]
> This looks good to me, although @Gio2018 I'd appreciate if you have time to confirm!

Thank you @sla8c and @frosty ! I tested and the issue does not seem to happen anymore.
@mokagio , how do you want me to proceed on this? Just merge it into `trunk`? Cherry pick the commits into `release/19.9` and open another PR for that? Something else?

**Comment by mokagio** [comment]
@Gio2018 I can take care of the merge in the release branch, no worries. 

I usually go for a change of the base branch in these cases. Merging on `trunk` then cherry-picking works too, of course, but it requires one extra merge whereas by merging into the release branch, the change will automatically go to `trunk` too on the next beta merge.

**Comment by mokagio** [comment]
@Gio2018  this has been bundled as part of [19.9 beta 1 (19.9.0.1)](https://github.com/wordpress-mobile/WordPress-iOS/pull/18631).

Thanks for your work 🙌

**Comment by frosty** [comment]
Thanks everybody!

**Comment by Gio2018** [comment]
I believe this can be closed now, since the relevant commit is merged into the release branch

**Pull request merged**
