### PR TITLE
Transitioned to use custom chart legend

### LINKED ISSUE #11266: [Stats Refresh] Chart highlight bar overlaps the legend
In the review for #11263, it was observed that the orange highlight bar overlaps the legend. This only impacts the Period chart, when Views are selected, as the legend only appears when Views & Visitors are presented together.

### PR DESCRIPTION
**Pull request by stevebaranski**
Fixes #11266 and in doing so, updates the legend to more closely respect the specification in Zeplin.

To test:
- Checkout the branch, confirm that it builds & tests pass.
- For a site, navigate to Stats, and select a given period (i.e., Days, Weeks, Months, Years). The image should look like the exhibits below.
- Please note that at the moment, the chart is the same regardless of period or dimension (Views, Visitors, Likes, Comments).

Update release notes:

- [X] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

_iPhone SE (Portrait)_
11266_SE_portrait

_iPhone SE (Landscape)_
11266_SE_landscape

### CODE REVIEW

**Comment by stevebaranski** [comment]
@ScoutHarris the images above show the position of the custom legend with respect to the viewport of the chart. Note that the appearance of the highlight.

@SylvesterWilmott I have included the following additional screenshots for iPad. I hope you'll agree that this more closely resembles what you've depicted in Zeplin.

I would like to make a couple of additional improvements subsequently (e.g., #11069).

1. Adjust the gridlines so that they look a bit nicer with respect to the legend position.
1. Ensure that the bar highlight / width work with the legend once we have integrated with "real" data.

_Portrait_
11266_iPad_portrait

_Landscape_
11266_iPad_landscape

**Comment by SylvesterWilmott** [comment]
Looks great @stevebaranski 

>Adjust the gridlines so that they look a bit nicer with respect to the legend position, specifically with regard to vertical spacing.

I would suggest adding bottom margin of 16pt on the legend. I'm thinking that when you're on visitors, likes or comments tab we will hide that legend completely and so any additional spacing between the legend and the chart should be hidden as well.

**Comment by stevebaranski** [comment]
> I would suggest adding bottom margin of 16pt on the legend. I'm thinking that when you're on visitors, likes or comments tab we will hide that legend completely and so any additional spacing between the legend and the chart should be hidden as well.

Thanks for this input @SylvesterWilmott - it's the second day in a row where a suggestion you've made inspired an idea that led to an easier-than-previously considered fix. 😄 

The Charts framework supports offsets on each dimension. I am pushing an additional commit that only applies one when we have a legend to display, and it's equal to the height of the legend. I also constrained the legend width to the chart width, which prevents the clipping issue I was worried about when bars are wide.

I was pleased with how this turned out. Here is an example on the XS Max for variety.

11285_max

**Comment by SylvesterWilmott** [comment]
>it's the second day in a row where a suggestion you've made inspired an idea that led to an easier-than-previously considered fix.

My pleasure! It looks great!

**Pull request merged**
