### PR TITLE
Removes the what's new popup.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Removes the what's new popup in order to resolve [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/4573).

The reason why I'm removing the what's new popup code in its entirety is because I don't feel it was programmed to be reusable enough to make it worth keeping.

**Test 1:**
1. Launch the app for the first time.
2. Make sure the app is usable without the popup coming up at all.

**Test 2:**
1. Launch the app a second time.
2. Make sure the app is usable without the popup coming up at all.

### CODE REVIEW

**Comment by aerych** [comment]
This makes me sooooo happy :)

**Comment by diegoreymendez** [comment]
@aerych - [This one](https://github.com/wordpress-mobile/WordPress-iOS/issues/4580) may make you happy too in case you want to chime in.

**Comment by astralbodies** [comment]
:shipit: 

We should probably extract this into a project or something so if we need a similar UI back we'll have it accessible.

**Comment by diegoreymendez** [comment]
Ty @astralbodies!

I agree but I also think we should revise from a UI design perspective if we want to have a "what's new" feature that's updated on each release or similar.

**Pull request merged**
