### PR TITLE
Use illustration on notes to prompt for Jetpack install

### PR DESCRIPTION
**Pull request by elibud**
**Part 2 of** #8571 
In this PR we have updated the prompt to install Jetpack on the notifications screen to use the appropriate illustration.

**To test:**
1. Start with a clean slate.
2. Add a self hosted site: https://jurassic.ninja/create/?nojetpack
3. Go to Notifications and check that the illustration looks good.
4. Just for fun connect the site to Jetpack and see that everything works as expected.
5. Repeat on an iPad (simulator or device)

simulator screen shot - iphone 8 - 2018-02-13 at 14 49 49

### CODE REVIEW

**Comment by elibud** [comment]
> Rotating it to landscape on iPhone cuts off content

But scrolling is enabled right, so you are able to reach the button?

> it doesn't respect Dynamic Type:

Yes this one is perfect for our upcoming groundskeeping week. This screen was created  outside of the scope of this PR so I'm happy to tackle it there. Would you mind creating a ticket and label it as "Broken Window" and "Jetpack"?

**Comment by jklausa** [comment]
>But scrolling is enabled right, so you are able to reach the button?

Scrolling is enabled, but I think the view itself doesn't relayout on rotation so when you scroll up and down it's still clipped to what you see in that screenshot.

**Comment by elibud** [comment]
@jklausa I see what you mean now, great catch, looking into it.

**Comment by elibud** [comment]
@jklausa let me start by saying that that screen is not the finest work of software engineer we've made. However by removing `clipToBounds` and allowing it to scroll it now works correctly upon rotation. In the future I would like us to be fancier with autolayout when a view is rotated but for this instance I think what we have should be fine.

**Comment by elibud** [comment]
Thank you @jklausa

**Pull request merged**
