### PR TITLE
Integrate gutenberg release 1.34.0

### PR DESCRIPTION
**Pull request by ceyhun**
This PR incorporates the 1.34.0 release of gutenberg-mobile. For details about the changes included in this PR and testing instructions please see the related gutenberg-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2529

To test:

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by chipsnyder** [comment]
I was just doing some spot checking and it looks like the Starter Page template buttons, and bottom spacing for the editor is a bit off:

Screen Shot 2020-08-05 at 11 05 52 AM

It appears to be locking to the bottom of the screen instead of the safe area. 

cc @pinarol

**Comment by pinarol** [comment]
That doesn’t look good. How did you reproduce it? I wonder if that’s a breakage or an edge case. @chipsnyder

**Comment by chipsnyder** [comment]
This appears to be a breakage it happens every time when I run on my iPhone 11. 

Also worth noting I'm not able to create it in my branch for MLP https://github.com/wordpress-mobile/WordPress-iOS/pull/14553 which is a bit behind develop. 

I can take some time to investigate if no one else is looking at it

**Comment by chipsnyder** [comment]
[Reverted]( https://github.com/WordPress/gutenberg/pull/24388 ) the change that was causing https://github.com/wordpress-mobile/WordPress-iOS/pull/14565#issuecomment-669249079 and reopened the original issue to reinvestigate a fix.

**Review by guarani — APPROVED** [review]
Tested working great 👍 
The changes described here for iOS worked are present:
- https://github.com/WordPress/gutenberg/pull/24388
- https://github.com/WordPress/gutenberg/pull/24192
- https://github.com/WordPress/gutenberg/pull/23280 (inserting images into any block is failing, but seems to be an iOS 14 issue)
- 1.33.1 changes: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2538

**Review by cameronvoell — APPROVED** [review]
LGTM!

**Pull request merged**
