### PR TITLE
Fix flaky test - testContactUsCanBeLoadedDuringLogin()

### PR DESCRIPTION
**Pull request by jostnes**
### Description
`testContactUsCanBeLoadedDuringLogin()` started failing in the CI because the email field that was previously empty is now pre-filled with the value of the user in the last executed test. On the retry though, the email field is set back to empty so the test only fails the first time and passes on the retry. Test was updated so that if the email field is not empty, the test will skip the add email address step.

Not sure what changed that made this test flaky recently but to reproduce locally, run the test back to back and see that the email field will be pre-filled with the previous email on the second run (I believe this is the same behavior in production too but cc: @tiagomar in case this looks like a bug and we shouldn't be updating this test)

### Testing
Test `testContactUsCanBeLoadedDuringLogin()` should not fail the first time anymore in CI runs

### CODE REVIEW

**Comment by tiagomar** [comment]
> the email field that was previously empty is now pre-filled with the value of the user in the last executed test

This is weird! It shouldn't be possible to have data from previous runs since we delete user data after each test.

https://github.com/wordpress-mobile/WordPress-iOS/blob/80fd94f707157caf93075261a944bb50d5bcc2be/WordPress/Classes/System/WordPressAppDelegate.swift#L374-L378

At least in one of the failed runs I noticed that the existing email address is `main.ee0zglcj@mailosaur.io` which is different from the email used in `testContactUsCanBeLoadedDuringLogin` (`user@test.zzz`). 

I've found this email address in two API mock files:

https://github.com/wordpress-mobile/WordPress-iOS/blob/80fd94f707157caf93075261a944bb50d5bcc2be/API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/me/me.json#L13

https://github.com/wordpress-mobile/WordPress-iOS/blob/80fd94f707157caf93075261a944bb50d5bcc2be/API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/rest_sites_181851495_posts-draft%2Cpending.json#L37

While the mock files were modified 14 months back, the test started failing regularly starting on Aug 25th.

image

image


Le me ping @kean and @momo-ozawa to help us understand how could the changes in https://github.com/wordpress-mobile/WordPress-iOS/commit/45834c6dd948c573acf9fea1a111dfa91712f1bc could contribute to it?

**Comment by tiagomar** [comment]
`main.ee0zglcj@mailosaur.io` is apparently set during tests like `testAddSelfHostedSiteAfterWPcomLogin()`  and unless the user is logged out via UI, the email persists. It seems like logging out from the UI now is different from `AccountHelper.logOutDefaultWordPressComAccount()` which is run before each UI Test?

**Comment by jostnes** [comment]
A couple of things related to the test:
1. As @tiagomar found, the email address was added after `testAddSelfHostedSiteAfterWPcomLogin()` was run and the email persisted when running `testContactUsCanBeLoadedDuringLogin()`
2. On the Contact Support page, even though there is an email address (the one added from `testAddSelfHostedSiteAfterWPcomLogin()` test ), the "add email address and name" modal is still prompted. This looks like a bug to me - should the modal still be prompted if there's an email address? Managed to reproduce this locally by running `testAddSelfHostedSiteAfterWPcomLogin()` first then `testContactUsCanBeLoadedDuringLogin()`:

https://github.com/wordpress-mobile/WordPress-iOS/assets/17252150/4e6a29e2-848d-42bf-9b22-b56acf05c65c

3. The odd thing is that when I run `testContactUsCanBeLoadedDuringLogin()` locally back-to-back (where only the email address is added and the name is auto-filled), on the second run, the modal is not prompted. Screen recording for run `testContactUsCanBeLoadedDuringLogin()` back-to-back:

https://github.com/wordpress-mobile/WordPress-iOS/assets/17252150/3c07ef3d-3aae-46de-b001-b23f4d902d92

4. Currently on CI runs, `testContactUsCanBeLoadedDuringLogin()` fails on the first run. On the retry run though, the email field is cleared so the test passes on the retry (which explains the test analytics chart where it only fails the first run but not on the retry)

@momo-ozawa @kean I think point 2 above is a bug that should be fixed, wdyt? I updated the test in this PR to work with all cases, but I can revert if it's a confirmed bug or leave the changes if that's expected.

**Comment by tiagomar** [comment]
> 2. On the Contact Support page, even though there is an email address (the one added from testAddSelfHostedSiteAfterWPcomLogin() test ), the "add email address and name" modal is still prompted. This looks like a bug to me - should the modal still be prompted if there's an email address? Managed to reproduce this locally by running testAddSelfHostedSiteAfterWPcomLogin() first then testContactUsCanBeLoadedDuringLogin():

The modal is actually expected to be prompted in the first time accessing Contact Support page, you can test it by Fresh install > Log in > Me > Help & Support > _(your email should be displayed)_ > Contact Support > "add email address and name" modal is prompted. You'll need to confirm the email to be able to access Contact Support.

**The issue here is** really that the app holds the previously logged in account information after `AccountHelper.logOutDefaultWordPressComAccount()` being called.

|  |  |
| - | - |
| The test actually only started failing in the first run because the resultant address, after typing the test email, is an invalid address (`OzgIc@mailosauruser@test.zzz.irg`), so the `OK` button is disabled. |  |

@jostnes the current changes are working as expected, I think we could proceed with this PR. 👍

**Review by tiagomar — APPROVED** [review]
The changes look good and are necessary to accommodate a new behavior under investigation.

**Pull request merged**
