### PR TITLE
Posts & Pages: Enable long press in search results

### PR DESCRIPTION
**Pull request by kean**
To test:

- Open Posts/Pages
- Verify that context menus open and test some of the actions (if one works, so should the others)
- Open search
- Verify that the same content menus open on long press

## Regression Notes
1. Potential unintended areas of impact: Posts & Pages search
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual
3. What automated tests I added (or what prevented me from doing so): n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x]  I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by momo-ozawa — COMMENTED** [review]
Works as described! I noticed the "posts page" / "home page" attributes don't get updated in search results. 


https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/6b1a9091-97f7-4bc1-847c-18b56ea643d0

**Comment by kean** [comment]
Thanks, I added it to the defects list.

**Comment by kean** [comment]
FYI, I pushed a couple of changes. I was working on another fix, I couldn't get it to work, but I added a minor improvements I made here.

**Review by momo-ozawa — APPROVED** [review]
Nice improvements!

**Pull request merged**
