### PR TITLE
Adds the new domain purchase flow

### LINKED ISSUE #17150: New domain purchase flow #1
This task covers the addition of the new domain purchase flow to the domains dashboard. More specifically:

- The Domains Dashboard will include an actionable "Get your domain" item (it will not reflect the final designs at this stage)
- Tapping on the item, will start the domain purchase flow. From here, users can:
    - choose a domain in the predefined list, that uses the primary domain name as a search criteria
    - Insert a custom search criteria for domain names
    - choose a domain resulting from the custom search
    - Tap on "Choose domain" to select the domain they want to purchase
    - Display the purchase form inside a we view
    - Complete the purchase

### PR DESCRIPTION
**Pull request by Gio2018**
Fixes #17150

Related [WordPressKit PR](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/444)

This PR adds the new domain purchase flow to the Domains Dashboard

To test:
Pre-requisites
- It is recommended to use the store sandbox to avoid actual purchases while testing
- it is recommended to setup mock payment methods in the store sandbox to test more than one payment method (refer to the field guide for details)

Testing
- Build/run then go to My Site -> Domains
- Tap on "Get your domain"
- Either choose a domain from the predefined search or insert a custom search criteria, obtain a new list and choose a domain
- Tap on "Choose domain" and make sure that the domain purchase page opens in a web view (see screenshot below)
- Select a payment method of your choice and tap on Pay xxx with yyy (where xxx and yyy should report details about the price and the selected payment method)
- Make sure the purchase completes successfully. At this time, you will not see the native post purchase screen, and you should dismiss the web view manually

Known issues:
- The post purchase screen is not final. The web post purchase screen will be shown when the purchase completes
- The Domains dashboard is not final, nor it will update after the successful domain purchase
- The existing redeeming flow for paid plans is unchanged, and will not show the web view
- The cart created with the purchase is not deleted if the view is dismissed before completing the purchase, so it will persist in the user's cart on the same store used for the purchase (sandbox or live)

<p align=center>

</p>

## Regression Notes
1. Potential unintended areas of impact
None: this adds a  new flow

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by diegoreymendez — COMMENTED** [review]
Hey @Gio2018 - I'm seeing the natvie purchase view instead of the web view that should come up.  Any ideas why this may be happening?

This is what happens when I tap "Choose a domain" in step 4 from the test instructions.

nativeRegisterDomainScreen

I'm testing on an iPhone 12 Simulator using the Sandbox Store.

**Comment by Gio2018** [comment]
> Hey @Gio2018 - I'm seeing the natvie purchase view instead

Hey @diegoreymendez , that is expected. As the description says, to see the new flow you need to use the Domains Dashboard, accessible through My Site -> Domains

**Review by diegoreymendez — APPROVED** [review]
Works as described.

**Comment by startuptester** [comment]
Testing notes added to the project thread

**Pull request merged**
