### PR TITLE
Categories: Add refresh control and sync for categories.

### LINKED ISSUE #2573: Categories is sometimes missing items from the list.
We've received a few reports that categories are missing from the iOS app. In some cases an incomplete list is described, in other cases the list is blank.   While testing a user's blog I saw different lists of categories depending on if I tested in the Simulator (current develop branch) or on a real device (v4.4 & v4.5). Querying the xmlrpc endpoint with XML-RPC Client yields results that matched the device.

Documenting here since there seems to be something going on but its not clear what. 

See forum threads:
http://ios.forums.wordpress.org/topic/app-cant-see-my-catagories?replies=14 
http://ios.forums.wordpress.org/topic/categories-not-updating-on-ipad?replies=3

### PR DESCRIPTION
**Pull request by kurzee**
Fixes #2573 

This adds a simple `UIRefreshControl` to the `PostCategoriesViewController` and reloads the table once synced. This resolves the issue of users not being able to pull in any recent changes to categories if the app hasn't synced the blog. It also wasn't obvious how to refresh categories without force-closing the app and relaunching.

To test:
1. Add a self-hosted site.
2. Go straight to Post Options > Categories.
3. Check that the list is currently in sync with the web.
4. Make a change on the web.
5. Pull down the refresh, check that the list is again in sync with the web.

To test:
1. Repeat steps for a .com or Jetpack site.

Needs review: @frosty can you give this is a gander?

### CODE REVIEW

**Comment by frosty** [comment]
Hey @kurzee! This works great on each of the sites I tested on (dotcom, self hosted, Jetpack). One tweak I might suggest: why don't we call `syncCategories` on `viewWillAppear`? That would mean we always have up-to-date data when the user first views the screen.

I also saw the issue your previous PR fixed – an empty categories list and Unavailable post format when I first viewed Post Options for my dotcom site. That should be fixed, right?

**Comment by kurzee** [comment]
>I also saw the issue your previous PR fixed – an empty categories list and Unavailable post format when I first viewed Post Options for my dotcom site. That should be fixed, right?

@frosty good catch! Turns out, this happens after "disconnecting" and logging back in. Separate issue with a separate PR coming up.

>One tweak I might suggest: why don't we call syncCategories on viewWillAppear? That would mean we always have up-to-date data when the user first views the screen.

I though about this but I feel as though we might be making an unnecessary request in that case, every time someone opens up the categories list. Maybe it's better to always keep it in sync regardless? What do you think @frosty?

**Comment by kurzee** [comment]
>why don't we call syncCategories on viewWillAppear?

@frosty I've gone ahead and added this to `viewDidLoad` to we sync every time the user loads this controller. @catehstn had mentioned she was also a fan of automatically syncing!

@frosty one more peak and test?

**Comment by kurzee** [comment]
Changed my mind, syncing once on `viewWillAppear` now 😃 .

**Comment by frosty** [comment]
So I found a bug when deleting categories (tested with .com sites):

* Start a new post, open Post Options
* If you like, visit Post Categories to ensure the list is correct
* Head back to the Post Options screen
* On the web, delete one of the categories
* Tap into Post Options on the app. The deleted category is still there.
* If you tap the deleted category, the app will crash.
* Otherwise, if you tap back out of Post Categories and back in again, _then_ the deleted category will disappear.

Added categories seem to be working fine.

**Comment by kurzee** [comment]
Great find @frosty! I went ahead and tweaked the service code to unset the blog. This also requires removing any previously selected categories if they were selected on deletion.

Can you retry your steps, and also with a category that was selected and then deleted?

**Comment by frosty** [comment]
Looks good! :shipit:

**Comment by kurzee** [comment]
Thanks @frosty!

**Pull request merged**
