### PR TITLE
Updates Certificates

### PR DESCRIPTION
**Pull request by jleandroperez**
#### WordPress Provisioning Profiles:
wordpress

#### Widget Provisioning Profiles:
widget

Needs Review: @astralbodies

### CODE REVIEW

**Comment by astralbodies** [comment]
Distribution should match Release (WordPress App Store) - ideally we should just get rid of this configuration.

**Comment by jleandroperez** [comment]
@astralbodies thanks for checking!. Updated as follows:

wordpress

widget

**Comment by astralbodies** [comment]
:shipit: !

**Comment by jleandroperez** [comment]
Thank you!

**Pull request merged**
