### PR TITLE
Fix ghost not disappearing from Insights cards in certain conditions

### LINKED ISSUE #17904: [iOS] Stats: Caching improvements
When monitoring the app's network traffic using Charles Proxy, we can see that when you switch between tabs or dates in the Stats view we seem to make requests to the server every single time even if we've just fetched data for the current view.

We should improve caching and make better use of the caching we have in place to ensure that we don't continually hit the network. Each of these views has pull to refresh, so users can always manually fetch the latest data.

### PR DESCRIPTION
**Pull request by Gio2018**
Fixes #17904

To test:
Pre-requisite: use a wp.com account with one or more site that have stats, preferably with many accesses

Testing:
1. Build/run and go to "My Site"
2. Tap on "Stats" then "Insights" (if you're not already there)
3. Screen should load normally
4. Navigate / back out to "My Site"
5. Repeat step 2
6. No ghost cards should appear

## Regression Notes
1. Potential unintended areas of impact
Stats -> Insights

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual test and run UI tests

3. What automated tests I added (or what prevented me from doing so)4. 
Some changes to the UI tests
PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by Gio2018** [comment]
@mokagio this PR follows #18072  to fix the issues that cause ui tests to fail. Still draft for now, but wanted to let you know we're on it

**Comment by mokagio** [comment]
Beautiful! Thank you @Gio2018. cc @tiagomar

**Comment by mokagio** [comment]
This fixes the ghost views appearing in the iPad UI tests 🎉 but the tests are still [failing](https://buildkite.com/automattic/wordpress-ios/builds/5808#e1fdd52d-0535-4709-bc8d-49b19ff37f5f) 🤔 

The difference from #18072 is that they now all fail because the screen says "no data yet" in every field. Here's a screenshot from the CI `.xcresult`:

image

**Review by sla8c — CHANGES_REQUESTED** [review]
Hey @Gio2018 the direction + outcome of all the new state status(es) being set need to be reversed.

Example for a single status - it should be like:
`state.allTimeStats != nil ? .success : .error`

OR 
`state.allTimeStats == nil ? .error : .success`

Instead of:
`state.allTimeStats != nil ? .error : .success`

I made this mistake the first time and this was my first commit before I corrected it so I'm sure that's what has transpired.

Link to my correction [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/18102/commits/966beb1940e162510530deed22d280cc621bf7f7)

**Comment by mokagio** [comment]
FYI, #18119, which addresses the UI tests issue, has been merged in the release branch. 

A merge or rebase here should address the UI tests failures because of the "No data yet" and move along testing the new logic.

**Review by sla8c — APPROVED** [review]
LGTM!

**Comment by mokagio** [comment]
@Gio2018  this has been bundled as part of [19.4 beta 2 (19.4.0.2)](https://github.com/wordpress-mobile/WordPress-iOS/pull/18136).

Thanks for your work 🙌

**Pull request merged**
