### PR TITLE
Activity log content routes

### PR DESCRIPTION
**Pull request by etoledom**
A recent change in the backend made the routing of Activity Log actions to break, opening all comment and posts links on WebViews.

Since those changes are aimed to be how routing will start working from now on, and since this feature is not yet public, we decided to make a fast fix on the mobile side.

The changes are:
- Ranges will have a `section` instead of a `type`. This with correlation to the sections where the routing should point to.
- Comments `post_id` was renamed `root_id`. It was originally removed but we need it to show the comments of a post. We took the opportunity to rename it to make it more generic.

@loremattei I would like to merge it to the release branch so we avoid releasing the broken version.
@ctarda The changes are quite small. Most of them are updating the test data.

Also a heads up to @malinajirka and @planarvoid about these changes.

**To tests:**
- Build and run.
- Go to the Activity Log.
- Open a comment event.
- Check that both, the comment and the post open in a native view.

### CODE REVIEW

**Comment by malinajirka** [comment]
I think you might have wanted to ping @0nko, as I didn't work on the Activity Log.

**Comment by planarvoid** [comment]
hey @etoledom, thanks pinging me! I was wondering if this changes the format also for Notifications since the point of this project is reusing the same logic in both features. Is it possible this is breaking notifications?

**Comment by etoledom** [comment]
Thank you all! :) 

@planarvoid - The notifications payload remains untouched for now. But there are plans (afaik) to make similar changes in the future.

Since notifications have been in production for so long, I believe we can request those changes to not break old code.

**Comment by planarvoid** [comment]
@etoledom that's both good and bad news 😄 . The good news is that the notifications feature is not broken. The bad news is that the model that's supposed to be reusable and consistent will now be different on both features. That might break our plan and double the testing effort. I'd probably go for not touching the Notifications at all and not reusing the code if the endpoints are not consistent.

**Pull request merged**
