### PR TITLE
[Dark Mode] Crash for unexpected state

### LINKED ISSUE #12519: NSInternalInconsistencyException: unexpected start state
Sentry Issue: [WORDPRESS-IOS-1QS4](https://sentry.io/share/issue/8c97fd6aa4d44f5ab67c5b5e8b158099/)

```
NSInternalInconsistencyException: unexpected start state
  File "<compiler-generated>", in NSMutableAttributedString.init
  File "<compiler-generated>", in NSMutableAttributedString.init
  File "<compiler-generated>", in NSMutableAttributedString.__allocating_init
  File "WPRichTextFormatter.swift", line 73, in WPRichTextFormatter.attributedStringFromHTMLString
  File "NSAttributedString+WPRichText.swift", line 25, in NSAttributedString.attributedStringFromHTMLString
...
(82 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by danielebogo**
Fixes #12519 

This PR fixes a crash that happens when the app changes its app state to `.background`. 
Because the app [is notified that the trait is changed](https://twitter.com/smileyborg/status/1175199999367368704), it reloads the content to update the style. That generates an exception with the mutable attributed string used to generate the post content.

## To test:
• Run this branch and go to the reader
• Open a post and check everything works normally
• Switch user interface style (light to dark or vice versa)
• Put the app in background and check it doesn't crash
• Switch user interface style (light to dark or vice versa) and bring back the app
• Put the app in background again and check it doesn't crash

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
I'll leave this for @jtreanor to 👍 as how is now the release manager for WPiOS , but it looks like this PR needs changes to Podfile.lock committed – you can fix this by running bundle exec pod install in the repo, then committing the changes! :)

**Comment by jtreanor** [comment]
I'm happy to include this in 13.3 once someone with some Dark Mode context performs the review.

**Comment by danielebogo** [comment]
Thanks @frosty @loremattei !

**Comment by koke** [comment]
I missed this one, so I re-investigated this in #12554. The PR fixed the crash, but broke the app switcher when changing color schemes while the app is in the background: https://github.com/wordpress-mobile/WordPress-iOS/issues/12554#issuecomment-535459463

**Pull request merged**
