### PR TITLE
Prevent crash by not presenting the editor without a site, allow user to create a site.

### LINKED ISSUE #6736: Crash: hitting the post tabbar button creates a crash, if num sites = 0
Creating here for posterity.

1. Log in to an account with no sites.
2. Hit the new post button on the tab bar.
3. This presents the NUX flow, for some reason, (should present flow to create a site).
4. Log in to the same account, which will still not have any sites.
5. Crash after log in, since we try to continue the action of opening the editor, but still without any sites.

```#0. Crashed: com.apple.main-thread
0  WordPress                      0x10037e418 EditPostViewController.(blog.getter).(closure #1) (EditPostViewController.swift:16)
1  WordPress                      0x10037c3dc @objc EditPostViewController.blog.getter (EditPostViewController.swift:17)
2  WordPress                      0x1001276c4 -[WPTabBarController showPostTabAnimated:toMedia:] (WPTabBarController.m:431)
3  WordPress                      0x1003707cc partial apply for static SigninHelpers.(createControllerForSigninFlow(showsEditor : Bool) -> UIViewController).(closure #1) (SigninHelpers.swift)
4  WordPress                      0x100457438 specialized SigninWPComSyncHandler.handleSyncSuccess(Bool) -> () (SigninWPComSyncHandler.swift)
5  WordPress                      0x100458230 specialized SigninWPComSyncHandler.(syncWPCom(String, authToken : String, requiredMultifactor : Bool) -> ()).(closure #1).(closure #1) + 4300063280
6  WordPress                      0x10045ce50 _TPA__TTSg5C9WordPress25SigninWPComViewControllerS0_S_22SigninWPComSyncHandlerS____TFFFE9WordPressPS_22SigninWPComSyncHandler9syncWPComFTSS9authTokenSS19requiredMultifactorSb_T_U_FT_T_U_FT_T_ (SigninWPComSyncHandler.swift)
7  WordPress                      0x1000c924c __62-[AccountService updateUserDetailsForAccount:success:failure:]_block_invoke (AccountService.m:248)
8  WordPress                      0x10007fdbc __65-[AccountServiceRemoteREST getDetailsForAccount:success:failure:]_block_invoke (AccountServiceRemoteREST.m:66)
9  WordPress                      0x1003df2e4 thunk (WordPressOrgXMLRPCApi.swift)
10 WordPress                      0x10049eac4 specialized WordPressComRestApi.(GET(String, parameters : [String : AnyObject]?, success : (AnyObject, HTTPURLResponse?) -> (), failure : (NSError, HTTPURLResponse?) -> ()) -> Progress?).(closure #2) (WordPressComRestApi.swift:124)
11 WordPress                      0x1004a01a4 partial apply for WordPressComRestApi.(GET(String, parameters : [String : AnyObject]?, success : (AnyObject, HTTPURLResponse?) -> (), failure : (NSError, HTTPURLResponse?) -> ()) -> Progress?).(closure #2) (WordPressComRestApi.swift)
12 WordPress                      0x100498418 thunk (WordPressComRestApi.swift)
13 AFNetworking                   0x100a6e14c __116-[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:]_block_invoke.80 (AFHTTPSessionManager.m:290)
14 AFNetworking                   0x100a814f4 __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.150 (AFURLSessionManager.m:308)
15 libdispatch.dylib              0x18c6fe1fc _dispatch_call_block_and_release + 24
16 libdispatch.dylib              0x18c6fe1bc _dispatch_client_callout + 16
17 libdispatch.dylib              0x18c702b2c _dispatch_main_queue_callback_4CF + 428
18 CoreFoundation                 0x18d822810 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
19 CoreFoundation                 0x18d8203fc __CFRunLoopRun + 1660
20 CoreFoundation                 0x18d74e2b8 CFRunLoopRunSpecific + 444
21 GraphicsServices               0x18f202198 GSEventRunModal + 180
22 UIKit                          0x1937957fc -[UIApplication _run] + 684
23 UIKit                          0x193790534 UIApplicationMain + 208
24 WordPress                      0x1000232c0 main (main.m:5)
25 libdispatch.dylib              0x18c7315b8 (Missing)
```

### PR DESCRIPTION
**Pull request by kurzee**
Fixes #6736

This fixes the primary issue of the crash created in #6736, as seen in Fabric, by instead presenting the Create a Site flow via the My Sites tab.

To test:
1. Follow the steps in #6736
2. Instead, you should be presented with the alert controller to create or add a new site.
3. The tab should automatically switch for you, and no crashes.
4. Upon actually creating/adding a site, we won't follow through with the post button action and let the user decided what to do afterwards.

Needs review: @astralbodies this is the most ideal solution to fix this in the wild, but technically a more minimal fix would be to simply ignore taps on the post button instead of trying to do anything, if there aren't any sites. If we want to go that route with `7.0` instead, we totally can.

### CODE REVIEW

**Comment by astralbodies** [comment]
@kurzee I'm not going to be able to review this before tonight's internal beta build but I will review it Wednesday. I get skiddish any time we touch the tab bar so we're going to want to test this one well. Maybe @frosty can give it a set of eyes on iPad too. 😄

**Comment by kurzee** [comment]
>I get skiddish any time we touch the tab bar so we're going to want to test this one well. 

Valid, @frosty it would be great to have you take a run through this one!

**Comment by frosty** [comment]
@kurzee So this fixes the crash, and presents the create / add site picker. However, I think there are a couple of odd use cases:

1) On iPad, it feels weird tapping the navigation bar and then having a popover appear from the top of the screen:

simulator screen shot 22 feb 2017 16 29 35

2) I'm not sure if it's a bit weird displaying this picker in the (admittedly probably fairly unlikely) situation where the user _has_ sites but has just hidden them all.

I wonder if we'd be better presenting an alert to the user, that mirrors the copy on the no results screen in the blog list VC? Either:

* "You have 3 hidden sites. To create a post, set a site to visible." Actions: "Dismiss" / "Change Visibility"
* "You don't have any WordPress sites yet. Would you like to start one?" Actions: "Dismiss" / "Create or Add site"

Maybe the wording on that second one is a little odd because you could create a site or add self hosted. Just thinking aloud here, would be interested to hear what you think.

In the case of the first issue there, perhaps we'd be better extracting the `addSite` method to a separate presenter object, which we could also use to present from the tab bar? (just give it a `sourceRect` of the entire tab bar, and it'll present from the center)

Thoughts?

**Comment by kurzee** [comment]
>I'm not sure if it's a bit weird displaying this picker in the (admittedly probably fairly unlikely) situation where the user has sites but has just hidden them all.

Ah, I didn't even realize the condition I copied over was looking for visible sites. We could switch it to `blogCountForAllAccounts` instead on: https://github.com/wordpress-mobile/WordPress-iOS/pull/6737/files#diff-3c33f95cbd8a337b48935b5161440cc6R413

**Comment by kurzee** [comment]
>In the case of the first issue there, perhaps we'd be better extracting the addSite method to a separate presenter object, which we could also use to present from the tab bar? (just give it a sourceRect of the entire tab bar, and it'll present from the center)

I think this is a better approach, and we could avoid having to force a tab bar selection. I'll rework this fix to instead share an alert controller that can be presented from the tabbar. Which would also fix the issue of the action sheet presenting from the bar button on iPad.

**Comment by kurzee** [comment]
@frosty after fiddling with this for a bit... it gets a bit out of hand when trying to share the alert controller code. I think it would be best for this PR, targeting `release/7.0`, to remain as is and clean the whole thing up later on `develop`. Also using `blogCountForAllAccounts` now.

@astralbodies also with this PR, since we don't touch too many other things, the only case in which the tabbar is affected is in the case of zero sites. While being uncommon, I think it's at least uncommon enough to move forward with this on `7.0` to at least prevent the crashes.

Let me know if you all think otherwise!

**Comment by astralbodies** [comment]
Merge once green light from Buddybuild arrives 😄

**Comment by kurzee** [comment]
Thanks @frosty @astralbodies

**Pull request merged**
