### PR TITLE
Issues/7675 add google framework via plistpre

### PR DESCRIPTION
**Pull request by nheagy**
Refs #7675 
Alternate implementation of #7790

To test:
- add new google client ID values to `~/.wpcom_app_credentials` (see template file for key names)
- ensure the wordspace still builds
- tap the "Login in with Google" button
- login to Google
- ensure the success alert appears

*Discussion:*
The values are stored in the credentials file, and either added to the Plist preprocessor or ruby-generated `ApiCredentials.m` as appropriate.

Needs review: @SergioEstevao

### CODE REVIEW

**Comment by aerych** [comment]
I've been having some trouble retrieving a valid `ID token` via this branch.  I'm calling `user.authentication.idToken` which appears to be correct [according to the docs](https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_authentication.html#ae18883846956cdd9393b46e46fe1b218).  I'm then testing the `id token`, using `curl` to query the social login endpoint.  Tokens generated via calypso will work but a token created via this branch fails with the following error: 
```
{"success":false,"data":{"errors":[{"code":"invalid_token","message":"The given token is invalid."}]}
```
This error originates from the WPCOM REST API code that queries Google to validate the `id_token`.

I'm not sure why the id token doesn't validate. @theck13 suggested it might be a configuration issue -- something related to the way things are set up in the Google console or something missing from the implementation in the iOS app (like an API key).  To test this second part, I added the plist with all the keys back to the project. No luck, id tokens were still invalid.

I think we need to confirm the `id tokens` from this branch validate before merging.  The code looks good to me (still deferring to @SergioEstevao for final review) but its possible we've overlooked something we need to implement in the client.... I'm just not sure what. 🤷‍♂️

**Comment by SergioEstevao** [comment]
In terms of the credential code it's all looking good on my side. 
Regarding to what @aerych found I'm a bit out of depth to find the reason. 
@nheagy do you know what is going on ?

**Comment by aerych** [comment]
Fwiw, I really do think the problem is going to be with the the configuration in one of the the Google consoles, but for caution sake I don't think we should merge until we know for sure.

**Comment by nheagy** [comment]
@aerych updated with server client id. `GOOGLE_LOGIN_SERVER_ID` needs a value in the credentials file, now.

**Comment by aerych** [comment]
@SergioEstevao gave us his blessing previously, and the issue with the invalid id_token is now resolved when testing. 
Nice work @nheagy. :shipit: with much 🚢 ing.

**Comment by SergioEstevao** [comment]
@nheagy today while updating other pods on the app I noticed that we use three different credentials file depending if are doing a build for debug, alpha or internal.

So I was thinking instead of having this: 

```
GOOGLE_LOGIN_CLIENT_ID=
 GOOGLE_LOGIN_SCHEME_ID=
 GOOGLE_LOGIN_ALPHA_CLIENT_ID=
 GOOGLE_LOGIN_ALPHA_SCHEME_ID=
 GOOGLE_LOGIN_INTERNAL_CLIENT_ID=
 GOOGLE_LOGIN_INTERNAL_SCHEME_ID=
```

Why not have only
```
GOOGLE_LOGIN_CLIENT_ID
GOOGLE_LOGIN_SCHEME_ID=
```

And then have the correct key in each credential file?

So ```.wpcom_app_credentials``` will have the production key ```wpcom_internal_app_credentials``` the internal key and ```wpcom_alpha_app_credentials``` will have the alpha key?

**Comment by nheagy** [comment]
@SergioEstevao I wasn't sure of the build system for those credentials. If that works, it sounds good to me!

**Pull request merged**
