### PR TITLE
Update 'clear media cache' labelling

### LINKED ISSUE #9485: Improve labeling of "Clear media cache" button
In the app settings, implication and labeling of "Clear media cache" button are not too clear.
Some users are confused about what effect this button will have on their website and assume that it will delete everything.

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #9485 

From the discussion on #9485 , the following labels have been updated:
- The clear cache button label is now `Clear Device Media Cache`.
- The `Media` section now has a footer: `Free up storage space on this device by deleting temporary media files. This will not affect the media on your site.`

To test:
Go to Me > App Settings.
Verify the changes in the Media section:
clear_cache

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@iamthomasbishop - since you provided the new text, care to take a look?

**Comment by michelleweber** [comment]
I would make the tiniest tweaks:

Free up storage space on this device by deleting temporary media files. This will not affect the media on your site.

Just to make the distinction between types of media (temp vs. stuff on my site) -- deleting the "your" re: the temporary files. If we wanted to be even clearer we could call them "temporary files from sites you've visited," but that might be too long/not necessary.

**Comment by iamthomasbishop** [comment]
@michelleweber that works for me!

@ScoutHarris let's make that change and :shipit: !

**Comment by ScoutHarris** [comment]
Thanks @michelleweber & @iamthomasbishop !

**Pull request merged**
