### PR TITLE
Confirm that site is indeed not a WordPress site after XML-RPC validation fails

### PR DESCRIPTION
**Pull request by staskus**
Partially addresses #18497 
Related WordPressAuthenticator PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/796
Related WordPressKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/655

## To test:

A URL for testing can be found at pbArwn-4xZ-p2#comment-5712 and/or 5170539-zd-a8c (not included in this ticket to protect user privacy):

1. Navigate to the app's login screen and select the "Log in by entering site address" option.
2. Submit the test URL.
3. Confirm that XML-RPC error is shown instead of invalid WordPress site error

### Regression

- Valid site scenario
- Running through a few cases described in https://github.com/wordpress-mobile/WordPress-iOS/pull/17724

## Regression Notes
1. Potential unintended areas of impact

Breaking site address login

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing, existing tests

3. What automated tests I added (or what prevented me from doing so)

Added new tests into WordPressAuthenticator-iOS

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by staskus** [comment]
https://github.com/Automattic/peril-settings/pull/118 and https://github.com/Automattic/dangermattic/pull/30 will resolve Danger warnings.

**Comment by staskus** [comment]
Hey @SiobhyB, I saw you originally reported this issue https://github.com/wordpress-mobile/WordPress-iOS/issues/18497 maybe you could to take a look at the solution? This is not urgent. 

My proposal was to do an additional check to determine if a site is a WP site if XML-RPC validation fails, just so we wouldn't confuse users with incorrect error messages.

- Explanation of the issue (https://github.com/wordpress-mobile/WordPress-iOS/issues/18497#issuecomment-1779361108)
- WordPressAuthenticator updates (https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/796)

**Review by SiobhyB — APPROVED** [review]
Approving via https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/796#pullrequestreview-1748240294, with the note that I think it'd be wise for @guarani or another iOS developer to also do a review, based on my lower level of experience in iOS. (I also see a couple of failing tests, which I assume are the ones [referenced here](https://github.com/wordpress-mobile/WordPress-iOS/pull/21904#issuecomment-1824652393).)

Thanks again for working on this @staskus! 🙌

**Comment by staskus** [comment]
@SiobhyB thank you very much for your testing and review! 🙇 

> I feel some users won't know what next steps to take or perhaps even what XML-RPC is. How would you feel about adding a sentence like Please check with your hosting provider to find out if they are blocking XML-RPC access? Or perhaps even linking to [our support doc](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/P7jrAc-1tl-p2)?
> https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/796#pullrequestreview-1748240294

I think that's a very good point. Given the goal of this fix is to reduce the number of confused and misled users. I will see what could be the improvement! 

> with the note that I think it'd be wise for @guarani or another iOS developer to also do a review

👍

**Comment by staskus** [comment]
Improved error messages to suggest contacting the host: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/655

**Review by guarani — APPROVED** [review]
Sorry for the long delay reviewing this, @staskus! 

Tested:
- [x] I see the new "Couldn't connect. Required XML-RPC methods are missing on the server. Please contact your hosting provider to solve this problem." message as expected when using the test URL "https://www.inter..." (redacted)
- [x] Using the XMLRPC tweak tool and `Mode 4: Block All Calls`, the new & updated message is also shown (as above)
- [x] The other XMLRPC tweak tool scenarios also work as expected
- [x] Login to a functional self-hosted site continues to work

**Pull request merged**
