### PR TITLE
NotificationDetails + Swift Mk5: Lifecycle

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:

Migrating **NotificationDetailsViewController**, step by step!. Reference #5613

Notes:
- This PR Migrates the View Lifecycle methods
- Zero new functionality has been added

#### Testing:
- Please, perform a smoke test, and verify nothing breaks.
- Also, please, validate that State Restoration works:
 - Launch wpios and open any notification's details.
 - Hit the Home button to send the app to BG.
 - Once in BG, hit Xcode's **stop** button.
 - Relaunch the app. As a result, you should see the notification that was previously onscreen.

Needs Review: @kwonye 
Thanks in advance sir!!!

### CODE REVIEW

**Comment by jleandroperez** [comment]
@kwonye sir, please, delay reviewing this one. Found out that state restoration is broken.

Sorry about the noise!!

**Comment by jleandroperez** [comment]
@kwonye state restoration fixed!. Ready for review, thanks!!!

**Comment by kwonye** [comment]
Crash when clicking a "commented on" notification in line 209 of `NotificationDetailsViewController+Extension.swift`

**Comment by jleandroperez** [comment]
Hey there @kwonye!

Can't repro on my side. Can you please try reproducing again, + paste the stack trace? (w/clean build, just in case a nib is bothering!). I've had a bunch of **WEIRD** crashes caused by stale code.

Line 209 shouldn't cause any kind of trouble (since the optional is being handled).

**Comment by kwonye** [comment]
After clean+build unable to break

:shipit:

**Comment by jleandroperez** [comment]
YAY!! thanks for the review @kwonye!!!

**Pull request merged**
