### PR TITLE
Comment Threads: enable comment moderation menu

### PR DESCRIPTION
**Pull request by ScoutHarris**
Ref #17629, #17752

This enables comment moderation from the threaded comments view. 

***NOTE*** Auto-merge is enabled.

To test:
- Go to the threaded comments view on a post that you have permission to moderate comments on.
- Verify the ellipsis icon is displayed on each comment instead of the share icon.
- Verify moderating/editing comments works as expected.

| Before | After |
|--------|-------|
| Screen Shot 2022-02-01 at 11 45 46 AM | Screen Shot 2022-02-01 at 11 46 29 AM |

## Regression Notes
1. Potential unintended areas of impact
Should be none.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
You can test the <strong>WordPress</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/WPiOS-One-Offs/'>here</a> with build number: <code>pr17888-8cedc50</code>. IPA is available <a href='https://appcenter-filemanagement-distrib4ede6f06e.azureedge.net/300dfc3c-b92c-407b-a806-b64c17020d53/WordPress%20Alpha.ipa?sv=2019-02-02&sr=c&sig=JKd411Y5xQVkj2sg4osmcXxK78UUVlENRKIp1l5Lo9U%3D&se=2022-02-05T15%3A03%3A33Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

**Comment by jkmassel** [comment]
You can test the <strong>Jetpack</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/jetpack-installable-builds/'>here</a> with build number: <code>pr17888-8cedc50</code>. IPA is available <a href='https://appcenter-filemanagement-distrib3ede6f06e.azureedge.net/f415c3c6-08d6-457b-92ff-c889412b2635/Jetpack%20Alpha.ipa?sv=2019-02-02&sr=c&sig=JxK%2FMfXgQSgW%2BqqGfW5RsbvPCfIYa1L1w%2FMqlPTNKW4%3D&se=2022-02-05T15%3A06%3A36Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

**Review by frosty — APPROVED** [review]
🎉

**Comment by ScoutHarris** [comment]
Thanks @frosty !

**Pull request merged**
