### PR TITLE
Implement mentions in gutenberg by intercepting @ in the keyboard

### PR DESCRIPTION
**Pull request by SergioEstevao**
Test triggering mentions using the keypress on @

GB PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2424

To test:
 - Start the app
 - Create a new post on a blog/site on WP.com
 - Tap @ on the keyboard inside a paragraph block
 - Check that the mentions interface shows up
 - Check that selecting one user in the list inserts the mention in the block
 - Write a word and without adding a space type the @ on keyboard
 - Check that mentions suggestions doesn't show
 
 - Check that on self-hosted sites the mentions button in the toolbar is not shown, and the keypress of @ doesn't activate it.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by loremattei** [comment]
Hey! I'm moving this to 15.0 because 14.9 has been cut. If you want this to make it to 14.9, please feel free to ping me.

**Comment by jkmassel** [comment]
Howdy friends – we're freezing `15.0` today, so I'm bumping this PR forward to `15.1`. If it needs to land in the `15.0` series, please merge it to `release/15.0` and DM me – I'll be happy to create a new beta release!

**Comment by jkmassel** [comment]
Howdy friends – we're freezing `15.1` today, so I'm bumping this PR forward to `15.2`. If it needs to land in the `15.1` series, please merge it to `release/15.1` and DM me – I'll be happy to create a new beta release!

**Comment by SergioEstevao** [comment]
@ceyhun do you mind giving a look to this again, now that we have updated it for all the monorepo changes?

**Comment by jkmassel** [comment]
I saw that this was approved and tried to merge it with `develop` for inclusion in `15.2`, but something appears to have gone wrong. 

I'll leave it for `15.3` since it looks like it'd require a new Gutenberg release, but if you'd like it in `15.2`, DM me and I'll cut a new beta for it.

Sorry!!

**Pull request merged**
