### PR TITLE
Update FSE theme checks

### PR DESCRIPTION
**Pull request by dvdchr**
Refs #20635
Depends on https://github.com/wordpress-mobile/WordPressKit-iOS/pull/598

> **Warning**:
> This depends on a development branch of WordPressKit, and should be updated once https://github.com/wordpress-mobile/WordPressKit-iOS/pull/598 is merged and released.

- Added a feature flag for the Site Editor MVP.
- Temporarily changed the WordPressKit dependency to the development branch.
- Updated the `BlockEditorSettings` initialization to check FSE from the remote theme object.

## To test

No visual tests for now, since it's mostly behind-the-scene changes. However, I've added unit tests so please make sure that they are passing.

## Regression Notes
1. Potential unintended areas of impact
Should be none. The `isFSETheme` property is not used anywhere currently.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the changes.

3. What automated tests I added (or what prevented me from doing so)
Added unit tests.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist: 

N/A

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by wargcm — APPROVED** [review]
✅ Tests pass. LGTM! 🚀

**Comment by dvdchr** [comment]
Updated the dependency to 8.1.0-beta and merged the latest trunk. Turning on auto-merge.

**Comment by dvdchr** [comment]
Hmm strange. Why is this `closed`  instead of `merged`? 🤔

**Comment by AliSoftware** [comment]
> Hmm strange. Why is this `closed` instead of `merged`? 🤔

This glitch in GitHub reporting the wrong status for this PR was likely due to [this GitHub incident](https://www.githubstatus.com/incidents/f0mhbz9xn497).

In practice we can see via [this merge commit in trunk](https://github.com/wordpress-mobile/WordPress-iOS/commit/d8a27f895c29ea879cd8664697366c7e5effcf49) that the changes from this PR were properly **merged** as expected, so we should be all good.

**Pull request closed without merging**
