### PR TITLE
Feature/4105 sharing management

### PR DESCRIPTION
**Pull request by aerych**
Refs #4105 

This is a partial implementation of Publicize sharing management presenting the overall publicize flow. This PR is submitted in the interest of keeping code reviews to relatively small sets of code. Sharing remains behind a feature flag.
Remaining work includes:
- implementing some missing graphics or changing placeholders.
- implement some designs around multiple account connections once the designs are complete.
- improvements to error / success prompts and "busy" status 
- all of sharing button management.

To test:

Choose a wpcom blog and visit its details screen. 
Select the Sharing option. 
For each publicize service perform the following:
- Connect to the service.
- Confirm the service is properly connected by checking the site's publicize settings in a browser. 
- Publish a post and confirm it is shared to the target service. (Optional, we assume publicize works correctly.)
- Toggle the share globally setting and confirm the change is reflected on the web.
- Disconnect from the service. 
- Confirm the service is disconnected by checking the site's publicize settings in a browser. 

Needs review: @jleandroperez would you do the honors?

### CODE REVIEW

**Comment by aerych** [comment]
Oops!  Sorry @jleandroperez, I forgot you were taking off :) 

@alexcurylo could I trouble you for a code review?

**Comment by jleandroperez** [comment]
**Apologies** about that Eric!!!

**Comment by alexcurylo** [comment]
Absolutely!

**Comment by alexcurylo** [comment]
Unchecking shared connection on the web is not reflected in the app.

**Comment by alexcurylo** [comment]
Multiple accounts and correct publicizing of post verified with Twitter. Will assume Publicize works as expected when connections are shown on the web for other services.

**Comment by alexcurylo** [comment]
Attempting to add an existing connection results in a failure alert although the received explanation is "A publicize connection for this blog ID and Keyring connection ID already exists. You should be able to find it via the `/sites/$site/publicize-connections` endpoint. [duplicate]}". Perhaps that should be treated as a cancellation of the add?

**Comment by alexcurylo** [comment]
Attempting to sign into Google+, `selectKeyring()` failed its `NSParameterAssert` as it was passed an empty array. `fetchKeyringConnectionsForService` should probably handle that case as a failure. (Attempting that account again, then with a second Google account, everything proceeded to work as expected.)

**Comment by alexcurylo** [comment]
This may be part of the WIP you mentioned, but just in case it indicates a general problem:
1. Sign into Google+. Leave detail window open in app.
2. Disconnect from the web.
3. Attempt to disconnect in app. Get failure notification.
4. Attempt to disconnect again. Bad access crash in `deletePublicizeConnection`.

**Comment by aerych** [comment]
> Attempting to add an existing connection results in a failure alert

Noted.  Tho the expectation is the final design of the account selection will mimic the web in that it won't allow an existing account to be chosen again.  Probably a good idea to add a safety net just the same.

**Comment by aerych** [comment]
> This may be part of the WIP you mentioned, but just in case it indicates a general problem

Doh!! Thanks for thinking of testing that.

**Comment by alexcurylo** [comment]
Tumblr picks from multiple accounts correctly but won't let you switch connections without logging out first. Part of that WIP I assume.

**Comment by alexcurylo** [comment]
Path and LinkedIn appear to work as expected.

**Comment by alexcurylo** [comment]
That's all I have for now. Solid work!

**Comment by aerych** [comment]
Hiya @alexcurylo. Thanks for the thorough review! I've gone through and made the relevant changes.  A few notes:

> Seems conventional to always have a space following a colon in declarations

I realize I've been a bit mixed with this this.  Adding a space between argument declaration and type seems to help readability and examples are reflected that way in our style guide. Rather than do a sweeping style update in this PR (which I'm afraid will add clutter) I'll handle that in a separate PR that is just targeting code style. 

> Crashes here after authorizing a Twitter account on iPad

Even tho this is placeholder UI, I've made things play nice on the iPad.

> Also crashes here on iPad when asked to confirm disconnect

Fixed

> Unchecking shared connection on the web is not reflected in the app

Fixed

> Attempting to add an existing connection results in a failure alert

I've changed things so selecting an already selected account is treated as being successful. The message in the log isn't shown in the web UI so I'm thinking its fine to not show it here. The change is a safety net and the final multi-account selection should be such that an existing connection is not able to be selected.

> Attempting to sign into Google+, selectKeyring() failed its NSParameterAssert as it was passed an empty array.

I've added a safety net for situations where no keyring connections are returned. Its an odd case I wasn't able to reproduce but now I know to watch for it. 

> This may be part of the WIP you mentioned, but just in case it indicates a general problem

So glad you caught that!  This will be treated as a successful disconnect now.

> Tumblr picks from multiple accounts correctly but won't let you switch connections without logging out first

Yep! This will be handled when the designs for multi-account selection are finalized.


I’ve also opened an issue for the remaining tasks: #4733. Ready for another round!

**Comment by alexcurylo** [comment]
Everything single-account related appears in order -- I can't reproduce the missing keyring connection issue either. Looking good, :shipit: !

**Comment by aerych** [comment]
Woot!  Thanks @alexcurylo :)

**Pull request merged**
