### PR TITLE
Jetpack App (Emphasis): Download App Store Strings

### PR DESCRIPTION
**Pull request by momo-ozawa**
Part of #16395

## Description 
This PR adds the`download_jetpack_promo_strings` lane, which downloads the app store metadata strings from GlotPress 

Design ref: pcdRpT-n0-p2

## How to test

Download app store strings
1. Run `bundle exec fastlane download_jetpack_promo_strings`
2. ✅ Check that the strings are downloaded to `fastlane/appstoreres/jetpack_metadata`

Create Jetpack promo screenshots

0. You can download the Jetpack promo screenshots here (p1623662644138700-slack-C0180B5PRJ4), or go through the steps below to generate your own.
1. First we need to generate raw screenshots. If you already have raw screenshots for all four devices defined in `ScreenshotFastfile`, go ahead and skip to Step 5
2. Run`rake mocks`
3. Run `bundle exec fastlane jetpack_screenshots`
4. ✅ The raw screenshots are generated in the `fastlane/jetpack_screenshots` directory
5. ⚠️ The current release toolkit version returns an error `[!] Unable to determine the plugin root directory`. Here's a workaround: open `fastlane/Pluginfile` and point the release toolkit to `1.0.0` 
```
gem 'fastlane-plugin-wpmreleasetoolkit', git: 'https://github.com/wordpress-mobile/release-toolkit', tag: '1.0.0'
```
6. ⚠️ You also need to comment out this line in`fastlane/Fastfile`. We need to do this because the `check_for_toolkit_updates` action relies on release toolkit `1.2.0`, but we're setting the toolkit to `1.0.0` in the previous step
```
check_for_toolkit_updates unless is_ci || ENV['FASTLANE_SKIP_TOOLKIT_UPDATE_CHECK']
```
7. Run `bundle install`
8. Run `bundle exec fastlane create_jetpack_promo_screenshots`
9. ✅ The promo screenshots are generated in the `fastlane/jetpack_promo_screenshots` directory

## Blockers

1. ` create_jetpack_promo_screenshots` is failing when using the current release toolkit version (1.2.0). The error message is `[!] Unable to determine the plugin root directory`. Since this is a release toolkit issue, [this also affects Android](https://github.com/wordpress-mobile/WordPress-Android/pull/14744). I haven't done much digging, but I noticed ` create_jetpack_promo_screenshots` works if you revert the toolkit version to 1.0.0.
2. `jetpack_screenshots` is failing on iPad devices for Russian. It works fine for all other devices/language combos. I think this is happening because the simulator keyboard is Russian, but "typing" in the password in the automated test requires an English keyboard. I haven't been able to find a proper solution, but a hacky workaround is to quickly tap on the 'ABC' button on the Russian keyboard to switch to the English keyboard, while the UI test is running on the iPad simulator. I have no idea why this only happens on iPad devices for Russian. 😞 

## Regression Notes
1. Potential unintended areas of impact
WordPress fastlane logic

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Ran and checked the Wordpress screenshot lanes

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by momo-ozawa** [comment]
Hi @jkmassel, can I get you blessing on this PR? 🙇‍♀️ 

FYI, although this PR is for downloading translated strings, I've also added some detailed instructions on how to generate the app store images for completeness. Let me know if you have any questions.

Also -- I added a blockers section above and would love it if you could give me some pointers. For now, both blockers have workarounds (so I guess they aren't true blockers..) I'm thinking they can be addressed in a separate PR, let me know what you think.

**Review by momo-ozawa — COMMENTED** [review]
f6f0802

I manually added the English strings (en-US, en-CA, en-GB, en-AU) to `fastlane/appstoreres/jetpack_metadata`, since you can't download them from GlotPress. Let me know if there's a better way to add the English strings. 🙏

**Review by leandroalonso — APPROVED** [review]
Tested with `pt-br` and it looks as described. :)

I also had to comment this line, not sure why:

```
check_for_toolkit_updates unless is_ci || ENV['FASTLANE_SKIP_TOOLKIT_UPDATE_CHECK']
```

Anyway, would love to get @jkmassel eyes on this one too. :)

**Comment by momo-ozawa** [comment]
> I also had to comment this line, not sure why:
> 
> check_for_toolkit_updates unless is_ci || ENV['FASTLANE_SKIP_TOOLKIT_UPDATE_CHECK']

@leandroalonso Oh yeah! I forgot to mention you need to comment out that line -- sorry! 

We need to comment out `check_for_toolkit_updates` because that action relies on release toolkit v1.2.0, but our workaround (to prevent the `[!] Unable to determine the plugin root directory` error from happening on the `create_jetpack_promo_screenshots` lane) uses release toolkit v1.0.0.

**Comment by jkmassel** [comment]
> create_jetpack_promo_screenshots is failing when using the current release toolkit version (1.2.0). The error message is [!] Unable to determine the plugin root directory. Since this is a release toolkit issue, this also affects Android. I haven't done much digging, but I noticed create_jetpack_promo_screenshots works if you revert the toolkit version to 1.0.0.

This is a bug – we should get it addressed ASAP!

> jetpack_screenshots is failing on iPad devices for Russian. It works fine for all other devices/language combos. I think this is happening because the simulator keyboard is Russian, but "typing" in the password in the automated test requires an English keyboard. I haven't been able to find a proper solution, but a hacky workaround is to quickly tap on the 'ABC' button on the Russian keyboard to switch to the English keyboard, while the UI test is running on the iPad simulator. I have no idea why this only happens on iPad devices for Russian. 😞

This has been happening for ages, and we've never really found a great workaround for it besides things like what you've suggested here. Some of the work @pachlava and @mokagio are doing might help us get a cross-project fix for this though? 🤞

**Comment by AliSoftware** [comment]
> I also had to comment this line, not sure why:
> 
> ```
> check_for_toolkit_updates unless is_ci || ENV['FASTLANE_SKIP_TOOLKIT_UPDATE_CHECK']
> ```

@leandroalonso FYI: this is because this `check_for_toolkit_updates` method is a new feature of the toolkit 1.2.0, and since you had to apply Momo's workaround to revert the toolkit to 1.0.0 temporarily given the bug she found, that method was not available back in 🧰 1.0.0 😉 

[EDIT] Dammit, I read the thread too fast and missed Momo's comment where she already answered you on that earlier. Sorry!

**Review by jkmassel — APPROVED** [review]
This LGTM – given the fact that it's already output valid screenshots I trust it 😅 

One thing to note though – this doesn't currently produce `ar-SA` or `he` screenshots (which are part of the MAG-16 and should be included).

That can be a subsequent PR though

**Comment by mokagio** [comment]
@momo-ozawa @leandroalonso @jkmassel: I wonder whether this PR should target `release/17.6`. I assume we'll want localized release notes for that release, right?

In a Slack conversation, @leandroalonso mentioned to apply the following rule of thumb for the Jetpack release notes: "everything in WordPress other than the Reader".

I didn't think about automation at the time. Easy enough to edit the notes manually when pasting to TestFlight, but it's something we need to think about now right? Editing _localized_ release notes manually would be risky on top of time consuming.

Localization related but out of scope for this PR, I'm not sure whether we have automation that update GlotPress with the release notes 🤔 And, given the "everything in WordPress other than the Reader" rule, we ~~might need~~ need (in this release there's a Reader change that I manually removed from the TestFlight notes) a different source for Jetpack.

Apologies if I missed some earlier conversation and this has already been discussed

**Comment by momo-ozawa** [comment]
> I didn't think about automation at the time. Easy enough to edit the notes manually when pasting to TestFlight, but it's something we need to think about now right? Editing localized release notes manually would be risky on top of time consuming.

@mokagio About generating a .po[t] file for the Jetpack release notes -- I made a request here (paaHJt-1VJ-p2#comment-4681)

> I wonder whether this PR should target release/17.6. I assume we'll want localized release notes for that release, right?

~I can open a new PR targeting release/17.6.~ I changed the base branch to release/17.6.

I'm a little confused about localized release notes though -- aren't localized release notes downloaded in a different lane? The  `download_promo_strings` lane looks like it's only downloading the screenshot strings.

**Comment by mokagio** [comment]
> I'm a little confused about localized release notes though -- aren't localized release notes downloaded in a different lane? The `download_promo_strings` lane looks like it's only downloading the screenshot strings.

Yes. Localized release notes are downloaded by their own lane, `finalize_release`, which calls `ios_update_metadata`, which in turn calls the `download_metadata.swift` script.

I got confused because I saw the call to:

```
download_translated_strings(
  project_url: "https://translate.wordpress.com/projects/jetpack/apps/ios/release-notes/",
```

I should have spent more time to understand the whole PR. Apologies 🙇 .

I think we'll have to do something along those lines of what you did here to download the rest of the Jetpack translations. @jkmassel and @JavonDavis are likely onto this already (but folks do let me know if you need help) so I'll leave it to them to suggest whether:

- This PR ought to go against `release/17.6` to reuse some of the flexibility introduced in the `download_translated_strings` helper lane; or
- Reset the target branch to `develop` because the changes involved are different

Sorry for the extra work I may have caused @momo-ozawa 🙇

**Comment by momo-ozawa** [comment]
@mokagio No problem! All I did was change the base branch from `develop` to `release/17.6` in the Github UI. No conflicts, thankfully!!! 
Screen Shot 2021-06-17 at 17 15 55

I'll hold off merging this until I hear back from @jkmassel about which base branch to point to (`develop` or `release/17.6`) 😄

**Comment by mokagio** [comment]
The release branch is fine. Thanks @momo-ozawa 👍 

I'll go ahead and merge this to keep the wheels turning.

**Comment by mokagio** [comment]
This PR has been "shipped" as part of [17.6 beta 3](https://github.com/wordpress-mobile/WordPress-iOS/pull/16718).

**Pull request merged**
