### PR TITLE
Jetpack overlay - left alignment and copy update

### LINKED ISSUE #19155: [iOS] Update overlay layout: update copy and align the content to the leading edge (left).
Update the overlay layout by left aligning the content, and updating the copy as shown in the screenshot below
<p align=center>

</p>

### PR DESCRIPTION
**Pull request by Gio2018**
Fixes #19155

This PR updates the layout of the Jetpack overlay to be aligned to the leading edge, and updates the copy as well (see animation below)

<p align=center>

</p>

To test:
Test with one LTR and one RTL language
- Enable the `jetpackBottomSheet` feature flag
- build/run this branch
- go to My Site/Home
- tap the Jetpack powered badge
- Make sure the overlay appears and its content is aligned to the leading edge (left for a LTR, right for a RTL)
- Make sure the copy looks correct.

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] ~~I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.~~ Not released

### CODE REVIEW

**Review by twstokes — COMMENTED** [review]
This is looking good @Gio2018! 👏 

I enabled the feature flag and tested:
- Light / dark modes
- Landscape and portrait orientations
- iPhone and iPad
- RTL mode

The only part that stuck out to me was the spacing below the title:



If this is outside this PR's scope and coming later, just let me know and I'll approve.

**Comment by Gio2018** [comment]
> The only part that stuck out to me was the spacing below the title:

Thanks for catching this @twstokes ! Given the extent of the fix, it makes perfect sense to do it here.
I also replaced the animation with one that shows the hairline between the two logos, as discussed on Slack with Ballio!

**Review by twstokes — APPROVED** [review]
Looks great to me @Gio2018. I really like the addition of the hairline separator. 🚀

**Comment by Gio2018** [comment]
Thank you for reviewing @twstokes !!

**Pull request merged**
