### PR TITLE
Show message when image fails to load

### PR DESCRIPTION
**Pull request by leandroalonso**
Ref #13098

Review first: https://github.com/wordpress-mobile/WordPress-iOS/pull/13227

#### Single image

1. In `PHAsset+AsyncImage.swift` inside the method `full` change `finishedRetrievingFullImage(image)` to `finishedRetrievingFullImage(nil)` to simulate an image failing to load
2. Create a new post using Aztec
3. Tap "+" and then 
4. Select a single image, tap "Preview 1"
5. Check that a message saying that the media couldn't be loaded appears right away

Put a breakpoint inside the `full()` method in `PHAsset+AsyncImage.swift` and make sure it's hit when tapping retry icon.

#### Multiple image

1. In `PHAsset+AsyncImage.swift` inside the method `full` change `finishedRetrievingFullImage(image)` to `finishedRetrievingFullImage(nil)` to simulate an image failing to load
2. Create a new post using Aztec
3. Tap "+" and then 
4. Select multiple images, tap "Preview X"
5. Tap the crop button
6. Check that a message saying that the media couldn't be loaded appeared

Put a breakpoint inside the `full()` method in `PHAsset+AsyncImage.swift` and make sure it's hit when tapping retry icon.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mbshakti** [comment]
Overall, looks great. Two comments:

(1) Since the user can't crop when the image fails to load, can we disable the crop button for this view? You mentioned that technically the crop button still works (user can still tap the crop button again to try to load the image), but I think we can just disable it since the retry button works; the user can just tap the retry button if they want to try reload the image. 

(2) Can we change the copy to: "Failed to insert media. Please tap to retry."

**Comment by leandroalonso** [comment]
@mbshakti 

1) Right now we only have the crop button, but there might be more buttons in the near future. That means we would block the user from trying to tap into something else (other than crop, for example). What do you think?

2) Do you mean changing the text to "Failed to insert media. Please tap to retry."? If that's the case, the Media Editor is trying to retrieve the image so the user can manipulate it somehow — instead of trying to insert it. What about "We couldn't retrieve this media. Please tap to retry."? I'm using this tone because it was the one we used through the [Offline Support project strings](https://github.com/wordpress-mobile/WordPress-Android/pull/10542).

**Comment by mbshakti** [comment]
> Right now we only have the crop button, but there might be more buttons in the near future. That means we would block the user from trying to tap into something else (other than crop, for example

Would those buttons also not work like the crop button doesn't work here? We should disable any button that doesn't work. 

Re the copy, that sounds good!

**Comment by leandroalonso** [comment]
> Would those buttons also not work like the crop button doesn't work here? We should disable any button that doesn't work.

All of them would still work, they will retry fetching the image again. That's why I think we might let them enabled, the user will have the option to tap to retry again or tap in any of the available capabilities too. Otherwise, let's say that the user tapped crop, it failed, and then he changed his mind and tapped "filters". By disabling the buttons that wouldn't be possible.

JFYI, the buttons are disabled while the image is _being_ fetched.

> Re the copy, that sounds good!

Updated!

**Comment by leandroalonso** [comment]
@mbshakti I'll merge this PR but we still have to figure out if we're going to keep the buttons enabled or not.

Since there's another PR on the way, we can do this change there. Hope that's reasonable for you.

**Comment by leandroalonso** [comment]
@mbshakti Yes!

**Pull request merged**
