### PR TITLE
Fix Scheduled Post displayed status

### LINKED ISSUE #13654: Cannot change a draft to a use a date in the past without publishing it
Steps to reproduce:

1. Go to My Site > Blog Posts > + to start a new draft.
1. Add a title and content.
1. Go to More > Post Settings > Publish. 
1. Change to a date in the past.
1. Go back to the edit view.
1. Tap the X button at top left.
1. Tap "Update Post".

**Result:** the post is published when I thought a draft would be saved. ([2m21s](https://cloudup.com/cbvtcS95kbq))

Screen Shot 2020-03-13 at Mar 13 4 35 55 PM Screen Shot 2020-03-13 at Mar 13 4 36 07 PM
<sup>Tested with WPiOS 14.4.0.0 TestFlight beta on iPhone 11 iOS 13.3.1.</sup>

### LINKED ISSUE #13655: "Move to Draft" removes date and time from post settings
Steps to reproduce:

1. Go to My Site > Blog Posts > Published.
1. Pick out a post that was published in the past and note the publish date.
1. Tap More > Move to Draft.
1. Go to Drafts in the Posts Lists.
1. Open the post.
1. Tap More > Post Settings.
1. Notice that the publish date is lost.

**Result:** if I move a post from published to draft, the post date is lost. The expected behavior is that the post date should be kept and only the state should change. ([42](https://cloudup.com/clGyL27joGW))

Screen Shot 2020-03-13 at Mar 13 4 59 16 PM
<sup>Tested with WPiOS 14.4.0.0 TestFlight beta on iPhone 11 iOS 13.3.1.</sup>

### PR DESCRIPTION
**Pull request by bjtitus**
Fixes #13655
Fixes #13654

- Addresses a few bugs with post status not being changed when scheduling a post.
- Adds a confirmation prompt when a post is Published (seems like the logic for this was not checking the original post status)

To test:
- Schedule or update a post and check the resulting labels

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by bjtitus** [comment]
@designsimply Build #24644 should be available here whenever you get a chance to take a look: https://install.appcenter.ms/orgs/automattic/apps/WPiOS-One-Offs/

**Comment by bjtitus** [comment]
Thanks @designsimply! I think these are all good points where the flow becomes confusing.

> the date on the draft in the Posts List appears to be timestamp the draft was last modified and the date in the Post Settings is the publish date before "Move to Draft was used.

I did cross check this behavior with Calypso on the web because it looked a bit odd to me also. It seems like the modified date is shown for drafts and the scheduled/published date for other sections.

> once I've made any date change at all to the draft I'm editing, I'm forced to choose to either publish the post (if the date was set to immediately or to the past) or schedule the post (if the date is set to something in the future). Once I've changed the date in Post Settings for a draft, there's no way to save a draft.

I think there is one unintuitive way around this: you can change the Post Status to Draft from Post Settings. I love the idea of adding a better modal that shows more information and possibly giving more adjustment options.

**Comment by loremattei** [comment]
Hey! I moved this PR to 14.6 as because 14.5 has been cut. If you want this to make it to 14.5, please feel free to ping me!

**Comment by yaelirub** [comment]
@bjtitus , what is the status on this PR??

**Comment by bjtitus** [comment]
@yaelirub 

There are really 2 main changes aimed at bug fixes in this PR:

1. "Publish Immediately" logic being shown when Draft was back scheduled. (seems to be the same issue seen in https://github.com/wordpress-mobile/WordPress-iOS/issues/13710)
2. Fixing some issues with the Post button displaying the wrong action after changing the publish date.

A 3rd addition adds a dialog so it is extra clear when a Post moves from a non-published status to Published. I think this addition may need some extra review, so we could remove it for now to try and get a limited change set in to 14.5 if that makes more sense.

**Comment by bjtitus** [comment]
Build 14.5 (25496) from the one-off builds is most up to date with this PR: https://install.appcenter.ms/orgs/automattic/apps/WPiOS-One-Offs/

**Comment by designsimply** [comment]
> A 3rd addition adds a dialog so it is extra clear when a Post moves from a non-published status to Published.

To clarify, the extra dialog you're referring to is the one that says "Are you sure you want to publish?" which appears after backdating a post then tapping "X" then "Update Post"? ([2m13s](https://cloudup.com/cNH5lrAEHhY))

Screen Shot 2020-03-24 at Mar 24 3 32 23 PM Screen Shot 2020-03-24 at Mar 24 3 32 29 PM 
<sup>Tested with WPiOS build 14.5 (25496) from MS App Center on iPhone 11 iOS 13.3.1.</sup>

**Comment by bjtitus** [comment]
@designsimply Yep! That's the confirmation dialog I was referring to.

I think an option could be added to Save as Draft to that menu to make it easier to switch from Published to Draft instead of having to go back to Post Settings to make the change. I think that's better for a future release, though.

**Comment by bjtitus** [comment]
Merged into release 14.5: https://github.com/wordpress-mobile/WordPress-iOS/pull/13726

**Pull request closed without merging**
