### PR TITLE
Aztec: Adds all editor analytics tracking events to Aztec VC

### LINKED ISSUE #6549: Aztec: Add all the analytics
Make sure we're tracking everything the hybrid editor is.

### PR DESCRIPTION
**Pull request by astralbodies**
Fixes #6549 

Testing this PR could be a bit of a challenge. I ended up going through the existing editor VC and finding all of the methods that had events and added them into similar places in Aztec. You could perform checks on each event making its way into Tracks & Mixpanel.

Needs review: @bummytime, @nheagy

### CODE REVIEW

**Comment by astralbodies** [comment]
Just realized I forgot to add the parameter to the events to distinguish which editor is being used. I can try to address that now or in a subsequent PR.

**Comment by bummytime** [comment]
Sorry for the late review on this @astralbodies. I am getting a crasher in `persistTracksEvent` when publishing a post:

```
2017-04-04 10:25:57.771 WordPress[27137:376062] -[_SwiftValue encodeWithCoder:]: unrecognized selector sent to instance 0x610000841aa0
2017-04-04 10:25:57.772 WordPress[27137:376062] *** -[NSKeyedArchiver dealloc]: warning: NSKeyedArchiver deallocated without having had -finishEncoding called on it.
2017-04-04 10:25:57.819 WordPress[27137:376062] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_SwiftValue encodeWithCoder:]: unrecognized selector sent to instance 0x610000841aa0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010da30b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010d49c141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010daa0134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010d9b7840 ___forwarding___ + 1024
	4   CoreFoundation                      0x000000010d9b73b8 _CF_forwarding_prep_0 + 120
	5   Foundation                          0x00000001078c9996 _encodeObject + 1224
	6   Foundation                          0x00000001078cad30 -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 439
	7   Foundation                          0x00000001078d5d94 -[NSDictionary(NSDictionary) encodeWithCoder:] + 907
	8   Foundation                          0x00000001078c9996 _encodeObject + 1224
	9   Foundation                          0x00000001078fd27e +[NSKeyedArchiver archivedDataWithRootObject:] + 156
	10  CoreData                            0x000000010baf19cb -[NSSQLiteConnection execute] + 1035
	11  CoreData                            0x000000010bb34e12 -[NSSQLiteConnection insertRow:] + 450
	12  CoreData                            0x000000010bcc8ad0 _writeChangesForSaveRequest + 1056
	13  CoreData                            0x000000010bcca546 _executeSaveChangesRequest + 390
	14  CoreData                            0x000000010bb61fb6 -[NSSQLSaveChangesRequestContext executeRequestUsingConnection:] + 38
	15  CoreData                            0x000000010bc74908 __52-[NSSQLDefaultConnectionManager handleStoreRequest:]_block_invoke + 216
	16  libdispatch.dylib                   0x000000010ecaa05c _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x000000010ec87de6 _dispatch_barrier_sync_f_invoke + 346
	18  CoreData                            0x000000010bc747db -[NSSQLDefaultConnectionManager handleStoreRequest:] + 235
	19  CoreData                            0x000000010bc7bba6 -[NSSQLCoreDispatchManager routeStoreRequest:] + 342
	20  CoreData                            0x000000010bbffd55 -[NSSQLCore dispatchRequest:withRetries:] + 229
	21  CoreData                            0x000000010bbfc64d -[NSSQLCore processSaveChanges:forContext:] + 189
	22  CoreData                            0x000000010baf8541 -[NSSQLCore executeRequest:withContext:error:] + 881
	23  CoreData                            0x000000010bbe7a8b __65-[NSPersistentStoreCoordinator executeRequest:withContext:error:]_block_invoke + 4363
	24  CoreData                            0x000000010bbdfb6d -[NSPersistentStoreCoordinator _routeHeavyweightBlock:] + 381
	25  CoreData                            0x000000010baf7f98 -[NSPersistentStoreCoordinator executeRequest:withContext:error:] + 632
	26  CoreData                            0x000000010bb20488 -[NSManagedObjectContext save:] + 3368
	27  AutomatticTracks                    0x0000000106a88452 -[TracksEventPersistenceService saveManagedObjectContext] + 98
	28  AutomatticTracks                    0x0000000106a864c9 __52-[TracksEventPersistenceService persistTracksEvent:]_block_invoke + 89
	29  CoreData                            0x000000010bb38b52 developerSubmittedBlockToNSManagedObjectContextPerform + 178
	30  libdispatch.dylib                   0x000000010ecaa05c _dispatch_client_callout + 8
	31  libdispatch.dylib                   0x000000010ec87de6 _dispatch_barrier_sync_f_invoke + 346
	32  CoreData                            0x000000010bb38a4e -[NSManagedObjectContext performBlockAndWait:] + 286
	33  AutomatticTracks                    0x0000000106a8642b -[TracksEventPersistenceService persistTracksEvent:] + 203
	34  AutomatticTracks                    0x0000000106a89090 -[TracksEventService createTracksEventWithName:username:userID:userAgent:userType:eventDate:customProperties:deviceProperties:userProperties:] + 1264
	35  AutomatticTracks                    0x0000000106a8a026 -[TracksService trackEventName:withCustomProperties:] + 582
	36  WordPress                           0x0000000104a39ade -[WPAnalyticsTrackerAutomatticTracks track:withProperties:] + 654
	37  WordPressComAnalytics               0x000000010885d759 +[WPAnalytics track:withProperties:] + 713
	38  WordPress                           0x0000000104ad3929 +[WPAppAnalytics track:withProperties:] + 73
	39  WordPress                           0x0000000104ad36d9 +[WPAppAnalytics track:withProperties:withBlogID:] + 297
	40  WordPress                           0x0000000104ad357a +[WPAppAnalytics track:withProperties:withBlog:] + 170
	41  WordPress                           0x0000000104b8dabc _TFC9WordPress23AztecPostViewControllerP33_F42D62EF28423FC3E1ECE3591044A58313trackPostSavefT4statOSC15WPAnalyticsStat_T_ + 3852
	42  WordPress                           0x0000000104b8cb86 _TFC9WordPress23AztecPostViewController19publishButtonTappedfT6senderCSo15UIBarButtonItem_T_ + 166
	43  WordPress                           0x0000000104b8e6da _TToFC9WordPress23AztecPostViewController19publishButtonTappedfT6senderCSo15UIBarButtonItem_T_ + 58
	44  UIKit                               0x0000000108b15d22 -[UIApplication sendAction:to:from:forEvent:] + 83
	45  UIKit                               0x0000000108f505c7 -[UIBarButtonItem(UIInternal) _sendAction:withEvent:] + 149
	46  UIKit                               0x0000000108b15d22 -[UIApplication sendAction:to:from:forEvent:] + 83
	47  UIKit                               0x0000000108c9a25c -[UIControl sendAction:to:forEvent:] + 67
	48  UIKit                               0x0000000108c9a577 -[UIControl _sendActionsForEvents:withEvent:] + 450
	49  UIKit                               0x0000000108c9a6eb -[UIControl _sendActionsForEvents:withEvent:] + 822
	50  UIKit                               0x0000000108c994b2 -[UIControl touchesEnded:withEvent:] + 618
	51  UIKit                               0x0000000108b8349a -[UIWindow _sendTouchesForEvent:] + 2707
	52  UIKit                               0x0000000108b84bb0 -[UIWindow sendEvent:] + 4114
	53  UIKit                               0x0000000108b317b0 -[UIApplication sendEvent:] + 352
	54  UIKit                               0x0000000109314adc __dispatchPreprocessedEventFromEventQueue + 2926
	55  UIKit                               0x000000010930ca3a __handleEventQueue + 1122
	56  CoreFoundation                      0x000000010d9d6c01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	57  CoreFoundation                      0x000000010d9bc0cf __CFRunLoopDoSources0 + 527
	58  CoreFoundation                      0x000000010d9bb5ff __CFRunLoopRun + 911
	59  CoreFoundation                      0x000000010d9bb016 CFRunLoopRunSpecific + 406
	60  GraphicsServices                    0x00000001107c8a24 GSEventRunModal + 62
	61  UIKit                               0x0000000108b140d4 UIApplicationMain + 159
	62  WordPress                           0x000000010485fabe main + 62
	63  libdyld.dylib                       0x000000010ecf665d start + 1
	64  ???                                 0x0000000000000001 0x0 + 1
```

**Comment by astralbodies** [comment]
Nice catch @bummytime. Ready for another review!

**Comment by astralbodies** [comment]
Thanks so much @bummytime!

**Pull request merged**
