### PR TITLE
[Gutenberg] UBE - Implement custom JS code 

### PR DESCRIPTION
**Pull request by etoledom**
gb-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2561
gutenberg PR: https://github.com/WordPress/gutenberg/pull/24658

This PR implements the changes from the previously mentioned PRs.

With these changes we are able to inject custom JS scripts to the Unsupported Block Editor. This is needed to do modifications related to WPCom, that are not allowed to do on gutenberg repo directly.

We inject `remove-nux.js` and `extra-localstorage-entries` already provided by `gutenberg-mobile`. This will remove the WPCom NUX screen when a new user opens gutenberg for the first time.

To test:

- Create a new wpcom account.
- On the newly created site, create a new gutenberg post.
- On HTML mode, paste this snippet (or any other unsupported block HTML code): `<!-- wp:file /-->`
- Go back to visual mode.
- Open the unsupported block with the Unsupported Block Editor.
- Check that Gutenberg editor loads without the NUX UI covering it.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
We're cutting the `15.6` release today, so this PR is being bumped to `15.7`. If it needs to land in the `15.6` release, please merge it to the `release/15.6` branch, and DM me so that I can release a new beta build.

Thanks!

**Comment by loremattei** [comment]
Hey there! I'm moving this to 15.8 because 15.7 has been cut. If you want this to make it to 15.7, please, feel free to ping me.

**Comment by etoledom** [comment]
Updated with `develop` and with the latest from https://github.com/wordpress-mobile/gutenberg-mobile/pull/2561

**Comment by guarani** [comment]
@etoledom just a headsup that I tried to create an App Center build and it failed, looks like it's due to the changing Podfile.lock.

**Review by guarani — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/24658#pullrequestreview-485995555

**Pull request merged**
