### PR TITLE
[Gutenberg] Support POST requests

### PR DESCRIPTION
**Pull request by fluiddot**
**Related PRs:**
* https://github.com/WordPress/gutenberg/pull/49371
* https://github.com/wordpress-mobile/gutenberg-mobile/pull/5596
* Android
    * https://github.com/wordpress-mobile/WordPress-Android/pull/18181
    * https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2691
* iOS
    * https://github.com/wordpress-mobile/WordPressKit-iOS/pull/589
    * https://github.com/wordpress-mobile/WordPress-iOS/pull/20428

## Description

This PR adds support for POST requests coming from the editor.

## To test

**The editor doesn't make POST requests yet, hence this change can only be tested with a test PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/20430**

Alternatively, we can also follow testing instructions from https://github.com/Automattic/jetpack/pull/29756 to test a POST request in the VideoPress block.

## Regression Notes
1. Potential unintended areas of impact
This change shouldn't impact any unintended area. The only area that could be impacted is the network logic used in the editor.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I tested that GET requests coming from the editor work as expected.

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by SiobhyB — APPROVED** [review]
Similar to the review I left on [the Android PR](https://github.com/wordpress-mobile/WordPress-Android/pull/18181#pullrequestreview-1365464022), I'm approving this code based on the following:

* I went through the test plan outlined in https://github.com/wordpress-mobile/WordPress-iOS/pull/20430 and verified I could go through all of the steps successfully using the installable build.
* I reviewed the code in this PR, https://github.com/wordpress-mobile/WordPressKit-iOS/pull/589, and the iOS-specific code in https://github.com/WordPress/gutenberg/pull/49371. I verified the code follows the logic I'd expect, matching the same patterns as those previously defined for GET requests.

👏 👏 🚀

**Comment by mokagio** [comment]
I just shipped [WordPressKit 7.1.0](https://github.com/wordpress-mobile/WordPressKit-iOS/releases/tag/7.1.0) and updated the `Podfile` accordingly.

Enabling auto-merge as this PR has already been approved to get ahead with the work for the 22.2 code freeze.

**Comment by mokagio** [comment]
@fluiddot @SiobhyB sorry for the spam folks. For some reason, I convinced myself 22.2 was the next release, while it's actually 22.1.

I did all the work to get this ready to merge into trunk from a dependencies point of view, but didn't account for changes in what the code would have to do after updating to the latest Gutenberg:

Screenshot 2023-04-03 at 10 31 26 am

The method Xcode suggests to insert is

```swift
func gutenbergDidRequestFetch(path: String, completion: @escaping (Result<Any, NSError>) -> Void)
```

But I'm not sure what to write into it.

However, given this PR was intended for 22.2, I think it's fine for me to wait for your input on how to get this to compile and merge. Thanks!

**Comment by fluiddot** [comment]
> @fluiddot @SiobhyB sorry for the spam folks. For some reason, I convinced myself 22.2 was the next release, while it's actually 22.1.

No worries, I set this PR for the next release because I wasn't sure that we could merge it on time for `22.1`.

> I did all the work to get this ready to merge into trunk from a dependencies point of view, but didn't account for changes in what the code would have to do after updating to the latest Gutenberg:
> 
> Screenshot 2023-04-03 at 10 31 26 am
> 
> The method Xcode suggests to insert is
> 
> ```swift
> func gutenbergDidRequestFetch(path: String, completion: @escaping (Result<Any, NSError>) -> Void)
> ```
> 
> But I'm not sure what to write into it.

Thanks @mokagio for working on the PR to have it ready 🙇 . This PR depends on the following Gutenberg changes:
* https://github.com/WordPress/gutenberg/pull/49371
* https://github.com/wordpress-mobile/gutenberg-mobile/pull/5596

We'd need first to merge those in order to solve the build failures. Once they are merged, we'll bump the Gutenberg Mobile reference and we could consider this PR ready to merge.

> However, given this PR was intended for 22.2, I think it's fine for me to wait for your input on how to get this to compile and merge. Thanks!

Yep, we can wait, especially as the Gutenberg PRs aren't approved yet. I hope to have them approved by this week to include them in `22.2` 🤞 .

**Comment by mokagio** [comment]
> This PR depends on the following Gutenberg changes:
>
> - https://github.com/WordPress/gutenberg/pull/49371
> - https://github.com/wordpress-mobile/gutenberg-mobile/pull/5596

🤦‍♂️ ... It was written in the description.

Thanks! @fluiddot

**Comment by fluiddot** [comment]
> 🤦‍♂️ ... It was written in the description.

Yep, although I think I could have been more explicit in saying that this PR depends on those ones 😅 .

**Review by twstokes — APPROVED** [review]
LGTM @fluiddot! 🚀 

I ran the [.com test](https://github.com/wordpress-mobile/WordPress-iOS/pull/20430) and it worked great.

**Pull request merged**
