### PR TITLE
Improve RTL of placeholders.

### LINKED ISSUE #7560: RTL support on Aztec
Currently it doesn't look like the Aztec editor is supporting RTL languages. 
As a reference see the Hybrid Editor vs Aztec:

hybrid|aztec

### PR DESCRIPTION
**Pull request by SergioEstevao**
Refs #7560 

To test:
 - Set the simulator to use pseudo RTL language (Edit Scheme option in Xcode)
 - On the simulator add a keyboard with an RTL langauage (arabic for example)
 - Create a new post using Aztec and see if placeholder are show correctly

One small note regarding the cursor initial position, it looks that inside an UITextView the caret is only positioned on the right if you are using an RTL language so to see the cursor on the correct position the keyboard must be arabic

Needs review: @elibud

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@elibud - Adding myself as reviewer upon request by @SergioEstevao through DM.  Sorry for the intrusion!

**Comment by diegoreymendez** [comment]
@SergioEstevao - While the placeholder fix is fine, this PR doesn't fix the entirety of RTL support from #7560.

Can you modify the description so that this PR won't close the parent issue?

**Comment by elibud** [comment]
@diegoreymendez if you use an Arabic keyboard the text appears correctly right aligned, but if you switch to the English keyboard it goes to the left. Pretty cool TBH:
interesting
This might be what's expected when using the components we are on Aztec?

@SergioEstevao there is a conflict with this branch, can you fix it and I can take another look? 
The placeholders are effectively fixed, and if I use the Arabic keyboard everything seems to be working correctly. Do we have anyone that actually knows Arabic that can test this?

I found a problem though, might be unrelated but I want to double check with you. When typing in Arabic, if I switch to HTML, this happens:

arabicandhtmlswitch

Maybe we can loop in @koke to have another set of eyes on how the RTL support is working since I believe he's our expert.

**Comment by SergioEstevao** [comment]
@elibud the HTML switch is another issue, I think is the way we encode stuff. That will need to be addressed on another PR, do you mind to copy that across to the Aztec PR.

**Comment by SergioEstevao** [comment]
@elibud merge done and pushed.

**Comment by elibud** [comment]
@SergioEstevao sure thing, here's the issue: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/631

**Comment by elibud** [comment]
Found one more detail, the placeholders are too close to the right (or the caret too close to the left), it affects both the Title and the Share your story placeholders.

caret1

Other than that it works good as far as I can tell from my limited RTL knowledge.

**Comment by diegoreymendez** [comment]
Since @elibud is doing an excellent job at reviewing this PR I'm removing myself as reviewer for now to focus on other priority tasks.

**Comment by SergioEstevao** [comment]
@koke will you have time to have a look?

**Comment by koke** [comment]
Looks good to me 👍

**Pull request merged**
