### PR TITLE
[Stats Refresh] Update Countries Map colours

### PR DESCRIPTION
**Pull request by danielebogo**
Refs. #11852

This PR updates the colours used in the Countries Map.

Simulator Screen Shot - iPhone X - 2019-07-02 at 13 28 57

## To test:
• Open Stats -> DWMY Period (Use a site with data)
• Scroll until the map is displayed
• Be sure the map uses the pink colour.

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks good @danielebogo !

**Comment by nheagy** [comment]
From the palette guidelines: 

> Hot Pink is exclusive to primary buttons and calls to action

I think this should probably be another color? I'd suggest hot blue, but that's being replaced today. @SylvesterWilmott — thoughts?

**Comment by danielebogo** [comment]
That's perfect @nheagy ! Thanks a lot!

**Comment by SylvesterWilmott** [comment]
Looks good @danielebogo 

Do we shorten the legend number after it hits a certain value?

**Pull request merged**
