### PR TITLE
Added accessibility label to add image in new user epilogue

### LINKED ISSUE #11489: New Account VoiceOver: add image button label is not accessible
Steps to reproduce:

1. Log out of the WPiOS app.
1. Go to Settings > General > Accessibility > VoiceOver and toggle the setting on.
1. Go to WPiOS and double tap the "Sign up for WordPress.com" button.
1. Follow the prompts until you reach the New Account screen.
1. Tap the "Add Image" button to find that doesn't have a label.

Result: only "button" is announced when you tap on the "Add Image" button on the New Account screen. ([5s](https://cloudup.com/cV5xWztv8Rx))

voiceover-add-image-button-is-not-announced
<p style="clear:both;"><sup>Tested with WP Internal 12.2.0.20190412 on iPhone 6S iOS 12.2.</sup></p>

<p style="clear:both;"><sub>(internal reference: p77Llu-bQ6-p2 h/t @etoledom)</sub></p>

### PR DESCRIPTION
**Pull request by stevebaranski**
Fixes #11489.

To test:
- Checkout the branch, verify it builds, and that tests pass.
- Replicate the steps in the issue with VoiceOver, and verify that the accessible description is read.

Update release notes:

- [X] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

@danielebogo or @etoledom , would one of you be willing to take a look at this?

### CODE REVIEW

**Comment by etoledom** [comment]
Thank you @danielebogo for testing it!

My grain of salt: I think it would be good to add a hint stating what this image is for. By the shape of the image you can tell that it will be used as an avatar for the site, but a VoiceOver user won't know that.

Or instead of a simple "Add image", it could be a more descriptive, something like "Add account image" (plus the hint).

**Comment by danielebogo** [comment]
@etoledom that's a good point!

**Comment by stevebaranski** [comment]
@danielebogo thanks for the review!

> My grain of salt: I think it would be good to add a hint stating what this image is for. By the shape of the image you can tell that it will be used as an avatar for the site, but a VoiceOver user won't know that.
> 
> Or instead of a simple "Add image", it could be a more descriptive, something like "Add account image" (plus the hint).

@etoledom that's valid feedback, thank you. 

I have pushed an additional commit that revises the description, and adds a hint as you suggested. I took special care to honor the distinctions between the two. Can you let me know if this is more inline with your expectations?

**Comment by etoledom** [comment]
That looks great! Thank you @stevebaranski for updating it 👍 

:shipit:

**Comment by designsimply** [comment]
LGTM! Dropping by with a video for reference because I re-tested this today using WP Internal 12.8.0.201907011 on iPhone 6S iOS 12.31. ([39s](https://cloudup.com/cnfOnDotUHS))

**Pull request merged**
