### PR TITLE
Add accessibility labels to media library nav buttons

### LINKED ISSUE #12954: [VoiceOver] Media Library concerns
### ~[A1] The _Preview_ and _Insert_ buttons should be visible but disabled by default~

~They are not discoverable if they are hidden until you select an image. It may be difficult for users to figure out how to interact with the UI.~

~The behavior of hiding and showing also interrupts with the scrolling dictation like:~ 

~1. Scroll down. ”Page 6 of 7”~
~2. Scroll down. “Page 7 of 7”~
~3. Select an image.~ 
~4. Scroll up. “Page 7 of 8”.~ 

~The number of pages _changed_ even though the data didn't change.~ 

~The buttons can also make use of `.accessibilityValue` if they don't have that already.~ 

### [A2] Buttons are missing labels

- [ ] The _Cancel_ button shown after pressing _Edit_ can probably be better labeled as “Cancel editing”.
- [ ] The _Trash_ button shown when editing doesn't have a label. VoiceOver just says “Dimmed. Button”

## Media Library → Image Details

- [ ] The _Trash_ and _Share_ button have no labels
- [ ] The image has no `.image` trait

### PR DESCRIPTION
**Pull request by rohanrk**
Fixes #12954 

To test:

Voiceover labels on the media library table view and the media library item view nav buttons.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
Just a heads-up: I ran into https://github.com/wordpress-mobile/WordPress-iOS/issues/14938 (a bug I've seen on other branches) again while trying to test this. I'll see if I can test this anyway though, since the changes on this PR are not causing that issue.

**Review by guarani — COMMENTED** [review]
I gave this a test and the changes are sounding good!

On the Media Library screen I can now hear the "Cancel editing" and "Trash button", which is great.

On the Media Item screen however, there's two places that are missing accessibility improvements:
- The share button currently just says "Button" — it could say "Share. Button"
- The single image shown on this screen has the wrong trait (currently it's "Static Text" but it should be "Image")

Here's a video with sound of what I'm referring to: [10s](https://cloudup.com/cbqjP89cCrU)

**Comment by rohanrk** [comment]
@guarani The share button is handled in a different PR (due to being linked to a different issue). Here's the link to that: https://github.com/wordpress-mobile/WordPress-iOS/pull/15109

I'll take a look at the static text label, I think it might be a default which is weird

**Comment by guarani** [comment]
> @guarani The share button is handled in a different PR (due to being linked to a different issue). Here's the link to that: #15109

Gotcha, makes sense.

> I'll take a look at the static text label, I think it might be a default which is weird

👍 Feel free to re-request a review once it's ready.

**Comment by jkmassel** [comment]
We're cutting `16.1` today, so this PR is being bumped to the `16.2` release. If you need it to be part of the `16.1` series, please merge it into `release/16.1` and DM me – I'll be happy to create a new beta release!

**Comment by jkmassel** [comment]
👋 Howdy! We are freezing `16.2` today, so this PR is being pushed to `16.3`. If you need it to be part of the `16.2` release, please merge it to the `release/16.2` branch, then DM me – I'll be happy to cut a new beta release!

**Comment by jkmassel** [comment]
👋 Hey there! We are freezing `16.3` today, so this PR is being bumped to `16.4`. If you need it to be part of the `16.3` release, please merge it to the `release/16.3` branch and send me a DM – I'll be happy to cut a new beta release!

**Comment by jkmassel** [comment]
👋 Howdy! Today's the day we're cutting the `16.4` release.

Because of that, this PR will be bumped to `16.5`. If you need it to be part of `16.4`, please merge it into the `release/16.4` branch and DM me – I'll be happy to cut a new beta release!

**Comment by rohanrk** [comment]
Oh shoot this actually reminds me! @guarani. I've tried several methods but I cannot figure out how to change the accessibility trait of the image preview in MediaItemViewController to an image instead of static text. Not sure if that's worth cutting and making a new issue instead of this PR but I wanted to add an update now that I have some more time on my plate

**Comment by jkmassel** [comment]
👋 Howdy! We are cutting the `16.6` release today.

Because of that, this PR will be bumped to `16.7`. If you need it to be part of `16.6`, please merge it into the `release/16.6` branch and DM me – I'll be happy to cut a new beta release!

**Comment by jkmassel** [comment]
This PR has been pushed from a couple of releases now, so it'll be moved into the `Someday` milestone. 

Thanks!

**Comment by twstokes** [comment]
👋 I'm going to close this PR due to lack of activity, but please reopen if this was an error. Thank you.

**Pull request closed without merging**
