### PR TITLE
Comment Detail: Add regular text cells

### PR DESCRIPTION
**Pull request by dvdchr**
Refs #17087

Adds the regular text cells for comment detail view. Some notes:

- The cells are again, using plain `UITableViewCell` since the design matches the `.subtitle` cell style from iOS. 
- Configured table footer view to show a 1pt high plain `UIView`, to hide the separator for last cell.
- Configured the table's leading inset to 20pt as per the design.

Here's a peek:
Simulator Screen Shot - iPhone 8 - 2021-09-01 at 16 04 34

---

Question for @mattmiklic:

- How do we want to treat empty values on the cells? e.g. Web address on the screenshot 👆 . Should we put a placeholder text indicating that the value is empty, or should we just hide cells with empty values altogether?
- Specific for Web address field, if we want to use a placeholder text for empty values, should we hide the external icon on the right? Since empty values shouldn't lead the user anywhere when the cell is tapped.

---

## To test
- Ensure the `New comment detail` feature flag is switched on.
- Go to My Site > Comments, and tap on any comment.
- Verify that the new fields: web address, email address, and IP address is there.
- Verify that the web address can be tapped, and it shows the author's site in modal style.
- Verify that email and IP address doesn't do anything when tapped.
- Pick a comment where the author's URL is empty, and verify that tapping on the web address field does nothing.

## Regression Notes
1. Potential unintended areas of impact
n/a, feature is hidden behind a flag.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a, feature is hidden behind a flag.

3. What automated tests I added (or what prevented me from doing so)
n/a, feature is hidden behind a flag.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
This is unrelated to this PR, but I noticed an issue on an iPhone with split view (ex iPhone 12 Pro Max). When the device is rotated to landscape and back to portrait, the label is lost on the nav bar Back button.

Initial view in portrait:
port_init

Rotated to landscape:
landscape

Rotated back to portrait:
port_after

**Review by ScoutHarris — APPROVED** [review]
I'm not quite sure this was ready for review since there were no testing instructions and outstanding questions to Matt. But as it is, LGTM .

**Comment by dvdchr** [comment]
> there were no testing instructions

You're right 🤦 . Although it's practically a visual check, I forgot to add testing instructions for this. I've now added it for documentation purposes. Thank you!

**Comment by dvdchr** [comment]
> This is unrelated to this PR, but I noticed an issue on an iPhone with split view (ex iPhone 12 Pro Max). When the device is rotated to landscape and back to portrait, the label is lost on the nav bar Back button.

Noted. I'll address this in a separate PR! For now, I've tracked this in #17087. 👍

**Comment by dvdchr** [comment]
I'll go ahead and merge this for now. Will address follow-up suggestions from @mattmiklic through a separate PR! 🙂

**Comment by mattmiklic** [comment]
Hey @dvdchr --

> How do we want to treat empty values on the cells? e.g. Web address on the screenshot 👆 . Should we put a placeholder text indicating that the value is empty, or should we just hide cells with empty values altogether?

Good catch. I'm leaning toward saying we should hide the cell if there's no content. We could do a placeholder like "None" or "Not provided" but it seems a little bit superfluous. AFAIK web address is the only cell where this applies since all the others are required.

> Specific for Web address field, if we want to use a placeholder text for empty values, should we hide the external icon on the right? Since empty values shouldn't lead the user anywhere when the cell is tapped.

Since I think we should hide the field this is moot, but in case we do decide to use a placeholder, yes we should hide the external icon since there's nothing to link to.

**Pull request merged**
