### PR TITLE
Reader: add P2 section

### PR DESCRIPTION
**Pull request by ScoutHarris**
Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/15343
WPKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/312

This adds a "P2s" section to the Reader. 
- It appears if you are following or are a user of a P2.
- It does not appear if you are not.

Known issue: If you are simply following a P2, the reader card header is not the [P2 header](https://github.com/wordpress-mobile/WordPress-iOS/pull/15315). This is due to the `is_wpforteams_site` flag missing from the site options for followed P2s. Resolution is pending Lighthouse issue https://github.com/Automattic/p2/issues/1542.

To test:

---
No P2s:
- Log in with an account that is not subscribed to any P2s.
- Verify the Reader does not have a `P2s` menu item.

<kbd>no_p2</kbd>

---
P2s:
- Log in with an account that is following/a user on a P2.
- Verify the Reader does have a `P2s` menu item.
- Due to the Known Issue mentioned above, the card headers will differ by role.
  - On a P2 that you are following, or are a Viewer, the header will be default. (The first card in the screenshot below.)
  - On a P2 where your role is higher that Viewer, the header will be P2. (The second card in the screenshot below.)

<kbd>p2s</kbd>

---
Roles reference, from https://wordpress.com/people/new/:

<kbd>roles</kbd>

---
PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by JeromeMcGinn — APPROVED** [review]

**Review by mindgraffiti — APPROVED** [review]
✅  Code
✅  UI smoke tested in dark mode

### Screenshots
| No P2s | Empty state P2s |
| --- | --- |
| Simulator Screen Shot - iPhone 11 Pro - 2020-12-07 at 10 31 13 | Simulator Screen Shot - iPhone 11 Pro - 2020-12-07 at 10 33 11 |
| Subscribed with different levels of access |
| Simulator Screen Shot - iPhone 11 Pro - 2020-12-07 at 10 39 57 |

:shipit:

**Review by aerych — COMMENTED** [review]
One thought.  With the v1.3 endpoint there was a change to the topic "type" that's returned. (Ref  p1606934550051600-slack-hummingbird).  Would it make sense to update ReaderTopicService.topicForRemoteTopic [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/5a3d37e1ec249efbacf4e1d281790a4074698f89/WordPress/Classes/Services/ReaderTopicService.m#L776) to check for "organization" instead of "team"?  Looks like without that change the a8c and p2 will be `ReaderDefaultTopic`s vs `ReaderTeamTopics`. Not sure what impact that might have.

**Comment by ScoutHarris** [comment]
Hey @aerych .

> Would it make sense to update ReaderTopicService.topicForRemoteTopic here to check for "organization"

Yea, probably. Sorry, I didn't think to mention. It's on my list to see about replacing "team" with "organization". There's a couple places that's specified. I just didn't do it here as I figured there were enough changes in one PR.

> Not sure what impact that might have.

Me either. Another reason I wanted to do this separately. 😄

**Comment by ScoutHarris** [comment]
> Known issue: If you are simply following a P2, the reader card header is not the P2 header. 

Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/15461.

**Pull request merged**
