### PR TITLE
Gravatar Analytics

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:
This PR adds Gravatar Analytics for the following events:

- Gravatar Tapped
- Gravatar Cropped
- Gravatar Uploaded

Needs review: @astralbodies 
Thanks in advance Aaron!

### CODE REVIEW

**Comment by astralbodies** [comment]
Looks like we're missing a few events if we're going to stay in sync with Android - 

https://github.com/wordpress-mobile/WordPress-Android/pull/4076/files#diff-b746b023ad22dfe67f64acc153c207deR420

**Comment by jleandroperez** [comment]
@astralbodies skipped those on purpose. Reason: `WPMediaPickerViewController` doesn't really indicate us whether a gravatar was picked from the library, or the user took a snapshot.

Although we could just extend the WPMedia framework, differentiating those events (IMHO) don't really add value.

**Comment by astralbodies** [comment]
That makes sense @jleandroperez. 

Can you remove the import for `WordPressComAnalytics` and use `WPAppAnalytics.track(_:)` instead? We wrapped it for convenience but haven't really done a good job educating people.

**Comment by jleandroperez** [comment]
Sorry @astralbodies! i wasn't aware of `WPAppAnalytics`. Ready for another look.

Thank you!

**Comment by astralbodies** [comment]
:shipit:

**Comment by jleandroperez** [comment]
Thank you sir!

**Pull request merged**
