### PR TITLE
Update required Xcode version to 15.4

### PR DESCRIPTION
**Pull request by mokagio**
What it says on the title. Thanks @kean for the ping about this and to @spencertransier for doing the provisioning work that made the 15.4 image available in CI.

## Testing

Let's see if CI is green...

## Regression Notes
N.A., in that if there are new Xcode 15.4 specific issues, we should see them locally first. 

1. Potential unintended areas of impact – N.A.
2. What I did to test those areas of impact (or what existing automated tests I relied on) – N.A.
3. What automated tests I added (or what prevented me from doing so) – N.A.

---

**PR submission checklist:**

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes. **N.A.**
- [x] I have considered adding accessibility improvements for my changes. **N.A.**
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary. **N.A.**

**UI changes testing checklist:** Not a UI PR.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by kean** [comment]
Thanks, Gio. Ready and waiting 😊 

Screenshot 2024-05-31 at 12 50 44 PM

**Comment by mokagio** [comment]
@kean and any other iOS developer interested in upgrading to Xcode 15.4

As you can see, this PR sets up CI to use the new Xcode image. Everything builds and runs fine _except_ for the UI tests 😓 

From the logs, it looks like they didn't run at all:

image

It's possible the issue is due to some silly mistake I made in https://github.com/wordpress-mobile/WordPress-iOS/pull/23259/commits/7eb219e4042f214b763b8582743678226407cc4d when addressing the new Swift concurrency compiler error. 

Unfortunately, I don't have bandwidth to look into this at the moment. I won't be able to come back here till at least Tuesday 6/11. Depending on how eager you are to run Xcode 15.4 locally and in CI, you might want to take a stab at it.

**Comment by kean** [comment]
> Everything builds and runs fine except for the UI tests 😓

Tested locally: builds & runs, UI test work.
Interestingly, "UI Tests (iPhone) — Passed". The only tests that failed are iPad tests.

Logs:

```
[23:46:14]: $ xcodebuild -showBuildSettings -workspace /opt/ci/builds/builder/automattic/wordpress-ios/WordPress.xcworkspace -scheme JetpackUITests 2>&1
[23:46:17]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[23:46:23]: Command timed out after 6 seconds on try 2 of 4, trying again with a 12 second timeout...
```

Folks suggesting trying to increase the timeout https://github.com/fastlane/fastlane/issues/20919#issuecomment-1344976529. I'm not sure how it could help, but I'm out of idea why it works on iPhone but no iPad.

**Comment by dvdchr** [comment]
Hey @mokagio 👋 , I'll push the milestone to 25.2 for now as I'm starting code freeze for 25.1. Feel free to change it back to 25.1 if it's necessary for the beta!

**Comment by jostnes** [comment]
👋 @mokagio, the issue seems very similar to what happened on the upgrade in WCiOS recently, the reason the tests on iPad were failing was because it couldn't find the device that was set on CI builds and used the default device instead which was iPhone SE (more context: p1717452376837839-slack-C6H8C3G23). i didn't test it, but sharing it here in case it's really the same issue

**Comment by mokagio** [comment]
Hey @jostnes ! Thanks for stopping by and sharing your experience.

Fun fact, I tried the Simulator destination change before reading your comment: It worked 🎉 

image

Now I merged `trunk` into this old branch. Fingers crossed nothing changed on that end and we can move forward.

**Review by twstokes — APPROVED** [review]
Looks to be all ✅ so approving. Thanks @mokagio!

**Pull request merged**
