### PR TITLE
Integrate media picker 0.25

### PR DESCRIPTION
**Pull request by SergioEstevao**
Update to version 0.25 of the picker. Details of changes here: https://github.com/wordpress-mobile/MediaPicker-iOS/releases/tag/0.25

To test:
 - Check if the main uses of the picker are all correct:
 - Media Library
 - Site icon picker
 - Gravatar user picker
 - Edit Post, media picker

### CODE REVIEW

**Comment by frosty** [comment]
Also seeing it in the device photos picker:

screen shot 2017-11-20 at 14 05 18

**Comment by SergioEstevao** [comment]
@frosty Good catches, I think they are all being sorted out in this PR from Eduardo: https://github.com/wordpress-mobile/WordPress-iOS/pull/8192

**Comment by SergioEstevao** [comment]
@etoledom Ideally I would like to have all the uses of the MediaPicker to show this "No Results" view from the Media Library. Even in cases when we are not searching but just looking to a an empty data source/library we should show the view, probably just saying: No media files.

**Comment by frosty** [comment]
I think if we're going to roll that into WPiOS, we should have the no results views match the style / text that we currently use?

**Comment by SergioEstevao** [comment]
@frosty Ready for another look.

**Comment by etoledom** [comment]
@SergioEstevao @frosty Would you like me to add the styled 'no results' view also in the gravatar picker and the site icon picker in this PR #8192  ?

I will also check out the issue with the media picker where the default empty view is not centered when first loading.

**Comment by SergioEstevao** [comment]
@etoledom it will be great to have the styled "empty view" in all places we use the picker :).

**Pull request merged**
