### PR TITLE
Quick Start for Existing Users: All tours complete notice

### PR DESCRIPTION
**Pull request by momo-ozawa**
Part of #18389

## Description 

- Added a Congrats notice that's displayed when all tours are complete

### Existing Site 

1. Trigger Quick Start for an existing site via the debug menu
2. Go through all the tours
3. ✅ Verify: once you're back on the My Site screen, the congrats notice is displayed
4. ✅ Verify: The congrats notice is automatically dismissed after 5 seconds (or you can manually dismiss it by tapping on it)
5. Switch to the Reader tab
6. Switch back to the My Site tab
7. ✅ Verify: The congrats notice isn't displayed
8. Force quit the app
9. Open the app
10. ✅ Verify: The congrats notice isn't displayed

https://user-images.githubusercontent.com/6711616/166895518-5429557b-7da4-4aa1-baf4-d40a9a5e2548.mp4

### New Site

1. Trigger Quick Start for a new site via the debug menu
2. Go through all the tours
3. ✅ Verify: once you're back on the My Site screen, the congrats notice is displayed
4. ✅ Verify: The congrats notice is automatically dismissed after 5 seconds (or you can manually dismiss it by tapping on it)
5. Switch to the Reader tab
6. Switch back to the My Site tab
7. ✅ Verify: The congrats notice isn't displayed
8. Force quit the app
9. Open the app
10. ✅ Verify: The congrats notice isn't displayed

## Regression Notes
1. Potential unintended areas of impact
- QS for new sites

2. What I did to test those areas of impact (or what existing automated tests I relied on)
- Tested the steps above manually

3. What automated tests I added (or what prevented me from doing so)
- N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by osullivanchris — APPROVED** [review]
Works as expected and looks good to me!

**Review by leandroalonso — APPROVED** [review]
Tested on Menu and Home, with an existing site and new site, all looks good!

One small thing (unrelated to this PR): from "View your site" to "Connect with other sites" there's no notice being displayed, I have to go there manually and tap on the tour. Not sure if it's intended or not.

**Comment by leandroalonso** [comment]
@momo-ozawa I haven't tested the delay added on the last commit though. 😅

**Comment by leandroalonso** [comment]
Tested with the delay: ✅

**Comment by momo-ozawa** [comment]
> One small thing (unrelated to this PR): from "View your site" to "Connect with other sites" there's no notice being displayed, I have to go there manually and tap on the tour. Not sure if it's intended or not.

@leandroalonso Yeah I noticed that too. I don't think it's related to this PR though -- I created a separate issue to investigate / fix this behavior. https://github.com/wordpress-mobile/WordPress-iOS/issues/18521

**Comment by osullivanchris** [comment]
> One small thing (unrelated to this PR): from "View your site" to "Connect with other sites" there's no notice being displayed, I have to go there manually and tap on the tour. Not sure if it's intended or not.

this happened to me as well. I just thought I had done something weird testing.

re; the delay: my intention was a small delay before the Snackbar appears for task completed. But what I think I'm noticing is there's more delay in the auto-dismiss. Have I seen it right?

**Comment by momo-ozawa** [comment]
> re; the delay: my intention was a small delay before the Snackbar appears for task completed. But what I think I'm noticing is there's more delay in the auto-dismiss. Have I seen it right?

@osullivanchris I added a .5 second delay before showing the little toast message. The auto-dismiss delay remains the same 😄 

I included a video of a 1 second delay just for comparison -- lmk what you think!

<details>
  <summary>1 second delay</summary>
  
https://user-images.githubusercontent.com/6711616/166947071-03da6217-ab69-4e9c-8d8e-0374fdc6f8ed.mp4

</details>

<details>
  <summary>0.5 second delay</summary>
  
https://user-images.githubusercontent.com/6711616/166946568-a9feac9b-89d0-4c1b-b32c-0e9bcf775533.mp4

</details>

<details>
  <summary>No delay</summary>
  
https://user-images.githubusercontent.com/6711616/166946679-96f6c4ea-5ea2-4da5-9d3f-e25a32629249.mp4

</details>

**Comment by osullivanchris** [comment]
> @osullivanchris I added a .5 second delay before showing the little toast message. The auto-dismiss delay remains the same 😄

A-ha. Then we are on the same page. My eagle eyes let me down this time. Thanks for the video comparison, it makes it easier to compare!

Seeing those I think the 0.5 delay strikes the right balance, so let's keep it 👍 😄

**Pull request merged**
