### PR TITLE
[JP Plugin] Tweak the Jetpack Remote Install UI

### LINKED ISSUE #20204: Improve the UI of Jetpack remote install flow
Designs: qk5s4q4mZsXknwhMWo2vIY-fi-9613%3A21166

Screenshot 2023-02-23 at 21 57 37

Update the current Jetpack remote install flow:

- Use the correct Jetpack logo. The current one uses the wrong green color.
- Use a similar button style to the Jetpack Install overlay.
- Modify some spacing values.

This is targeted for 21.9.

### PR DESCRIPTION
**Pull request by dvdchr**
Resolves #20204 

This PR refactors the Jetpack Remote Install UI a bit to implement the improvements detailed in #20204, along with some accessibility fixes. 

Here's a preview video:

> **Note**: For the error flow video, perhaps the duration was too short so I couldn't see the error screen when playing the video from start to finish. But, it appears for me when you click on the video seeker thingy and manually drag it to the end.

Success flow | Error flow
-|-
<video src="https://user-images.githubusercontent.com/1299411/221668409-0f563f2b-76d6-4ad0-b2ad-6c92cc5b7a78.mp4"> | <video src="https://user-images.githubusercontent.com/1299411/221668429-4dd705a3-31b2-4cb3-aed8-4adad264f951.mp4">

For @osullivanchris, this is not testable yet from the Installable Build since you'll still need to make some code changes locally to enable the whole thing. For now, please verify visually through the recordings I've attached above. Thanks!

## To test

- Enable the `jetpackIndividualPluginSupport` feature flag.
- Prepare a self-hosted site with an individual Jetpack plugin and have it connected to your WordPress.com account.
- Run the Jetpack app and log in with your WordPress.com account.
- Switch to the self-hosted site.
- When the overlay appears, tap the "Install the full plugin" button.
- 🔎 Verify that the screen is displayed according to the new design.
- To verify the error path first, turn on airplane mode / turn off your connection. 
- Tap "Continue".
- The loading state only appears for a short bit, but you can verify this later. 
- 🔎  The error screen should appear. Verify that the screen is displayed according to the new design.
- Now, turn off airplane mode and tap "Retry".
- 🔎 Verify that the button shows a loading state.
- 🔎 Verify that tapping on the button does nothing.
- The success screen should appear after the installation succeeded.
- 🔎 Verify that the screen is displayed according to the new design.

## Regression Notes
1. Potential unintended areas of impact
Should be none.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the changes.

3. What automated tests I added (or what prevented me from doing so)
N/A.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by wargcm — COMMENTED** [review]
✅ verified each of the test steps.

I did notice a constraint breaking for the iPhone in landscape and the iPad:

<details><summary>iPhone Landscape</summary>

Simulator Screen Shot - iPhone 14 Pro - 2023-02-28 at 12 52 39

```
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60000193b2f0 UIStackView:0x2a77cb380.width <= 360   (active)>",
    "<NSLayoutConstraint:0x60000193be30 H:[UIStackView:0x2a77cb380]-(30)-|   (active, names: '|':UIView:0x2c6851570 )>",
    "<NSLayoutConstraint:0x60000193ad00 UIStackView:0x2a77cb380.centerX == UIView:0x2c6851570.centerX   (active)>",
    "<NSLayoutConstraint:0x60000190b840 UIView:0x2c6851570.width == UIScrollView:0x1292dee00.width   (active)>",
    "<NSLayoutConstraint:0x60000190ac60 UIScrollView:0x1292dee00.leading == UILayoutGuide:0x60000002ff00'UIViewSafeAreaLayoutGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x600001909e50 UILayoutGuide:0x60000002ff00'UIViewSafeAreaLayoutGuide'.trailing == UIScrollView:0x1292dee00.trailing   (active)>",
    "<NSLayoutConstraint:0x600001901fe0 'UIView-Encapsulated-Layout-Width' UIView:0x2c6856930.width == 852   (active)>",
    "<NSLayoutConstraint:0x60000190a5d0 'UIViewSafeAreaLayoutGuide-left' H:|-(59)-[UILayoutGuide:0x60000002ff00'UIViewSafeAreaLayoutGuide'](LTR)   (active, names: '|':UIView:0x2c6856930 )>",
    "<NSLayoutConstraint:0x60000190ae90 'UIViewSafeAreaLayoutGuide-right' H:[UILayoutGuide:0x60000002ff00'UIViewSafeAreaLayoutGuide']-(59)-|(LTR)   (active, names: '|':UIView:0x2c6856930 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000193b2f0 UIStackView:0x2a77cb380.width <= 360   (active)>
```

</details>

<details><summary>iPad</summary>

Simulator Screen Shot - iPad Pro (11-inch) (4th generation) - 2023-02-28 at 12 59 00

```
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000193b2f0 UIStackView:0x2a77cb380.width <= 360   (active)>

[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60000094d310 UIStackView:0x13fd81aa0.width <= 360   (active)>",
    "<NSLayoutConstraint:0x60000094fd40 H:[UIStackView:0x13fd81aa0]-(30)-|   (active, names: '|':UIView:0x139a1ab70 )>",
    "<NSLayoutConstraint:0x60000094ceb0 UIStackView:0x13fd81aa0.centerX == UIView:0x139a1ab70.centerX   (active)>",
    "<NSLayoutConstraint:0x60000094ff20 UIView:0x139a1ab70.width == UIScrollView:0x148437c00.width   (active)>",
    "<NSLayoutConstraint:0x600000953e80 UIScrollView:0x148437c00.leading == UILayoutGuide:0x600001380700'UIViewSafeAreaLayoutGuide'.leading   (active)>",
    "<NSLayoutConstraint:0x600000950ff0 UILayoutGuide:0x600001380700'UIViewSafeAreaLayoutGuide'.trailing == UIScrollView:0x148437c00.trailing   (active)>",
    "<NSLayoutConstraint:0x600000918370 'UIView-Encapsulated-Layout-Width' UIView:0x139a48350.width == 580   (active)>",
    "<NSLayoutConstraint:0x600000950a00 'UIViewSafeAreaLayoutGuide-left' H:|-(0)-[UILayoutGuide:0x600001380700'UIViewSafeAreaLayoutGuide'](LTR)   (active, names: '|':UIView:0x139a48350 )>",
    "<NSLayoutConstraint:0x600000951360 'UIViewSafeAreaLayoutGuide-right' H:[UILayoutGuide:0x600001380700'UIViewSafeAreaLayoutGuide']-(0)-|(LTR)   (active, names: '|':UIView:0x139a48350 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000094d310 UIStackView:0x13fd81aa0.width <= 360   (active)>
```

</details>

They still appear correct (assuming the logo isn't supposed to show for the iPhone landscaped) but should probably be addressed.

**Comment by dvdchr** [comment]
@wargcm 

> constraint breaking

Good catch! I forgot to reduce the leading & trailing constraint priority 😆. This should now be fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/20220/commits/3988ce320643784d7d42fe2cd47a79ec68b8b467 (along with the removal of an unused user-defined property from the XIB).

> **Warning**:
I'm turning on auto-merge.

**Review by osullivanchris — APPROVED** [review]
@dvdchr looks much better, nice work. One small nice-to-have. When the error message appears, the text and icon jump up in position from where they are in the loading state.

If the text and icon were positioned relative to the top of the screen, or the height of the device, rather than the height of that content area minus button, it could stay in the same position?

**Comment by dvdchr** [comment]
> the text and icon jump up in position from where they are in the loading state.

Good point. I anchored it based on the height of the content view right above the button container, but the content view height shrinks because the buttons take up more space in the error state.

This got merged as soon as you approved since I turned auto-merge on 😅 But I'll open a separate PR later to address this. Thanks @osullivanchris !

**Comment by osullivanchris** [comment]
> Good point. I anchored it based on the height of the content view right above the button container, but the content view height shrinks because the buttons take up more space in the error state.

Nice. Thought it was something like that. Hope its not too complex.

> This got merged as soon as you approved since I turned auto-merge on 😅 But I'll open a separate PR later to address this. Thanks @osullivanchris !

No worries...I only dip into GitHub briefly to cause havoc. Its not a blocker so its fine to address later, if possible.

**Pull request merged**
