### PR TITLE
Reader: Cache attributed string building to avoid crashes and performance issues

### LINKED ISSUE #21461: NSRangeException   -[ReaderCommentsViewController navigateToCommentIDIfNeeded]
Sentry Issue: [JETPACK-IOS-WM4](https://a8c.sentry.io/issues/4348147616/?referrer=github_integration)

```
NSRangeException: Attempted to scroll the table view to an out-of-bounds row (7) when there are only 7 rows in section 0. Table view: <UITableView: 0x155817600; frame = (0 0; 390 613); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x2819945a0>; backgroundColor = <UIDynamicSystemColor: 0x28031d5c0; name = systemBackgroundColor>; layer = <CALayer: 0x2817e40e0>; contentOffset: {0, 0}; contentSize: {390, 2459.0000305175781}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <WPTableViewHandler: 0x28247d050>>
  File "ReaderCommentsViewController.m", line 887, in -[ReaderCommentsViewController navigateToCommentIDIfNeeded]
  File "ReaderCommentsViewController.m", line 847, in -[ReaderCommentsViewController refreshTableViewAndNoResultsView]
  ?, in WPContentSyncHelper.syncContentWithUserInteraction
  File "<compiler-generated>", in WPContentSyncHelper.syncContentWithUserInteraction
  File "<compiler-generated>", in thunk for closure
...
(59 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by staskus**
Fixes #21461

Building NSAttributedString from HTML within tableView cell configuration methods triggers nested table view reloads that cause inconsistency between tableView and resultController states and lead to a crash.

More details: https://github.com/wordpress-mobile/WordPress-iOS/issues/21461#issuecomment-1840435759

### Solution

A caching mechanism was created and still exists within ReaderCommentsViewController but was abandoned for no clear reason and not used. Building attributed string from html inside cell configuration creates performance issues and also triggers CoreData and tableView reloads that cause crashes. NSAttributedString should be built outside tableView cellForRowForIndexPath and cached for performance.

I pass cached attributed string to a cell that was already being cached in `updateCachedContent` of `ReaderCommentsViewController`  https://github.com/wordpress-mobile/WordPress-iOS/pull/11582 

## To test:

1. Select a comment from notifications
2. Change to "Pending"
3. Open comment
4. Come back
5. Change to "Approved"
6. Open comment
7. No crash should happen and view should scroll to comment

Video: https://github.com/wordpress-mobile/WordPress-iOS/issues/21461#issuecomment-1840435759

## Regression Notes
1. Potential unintended areas of impact

I want to make sure that Reader comments loading is not breaking in any way. The caching mechanism looks to be quite safe, since it creates attributed text if it doesn't exist yet, so there shouldn't be cases where the comment doesn't appear.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing of Reader comments.

3. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by staskus** [comment]
@dvdchr 👋 I saw you worked on `RichCommentContentRenderer` some time ago. Would you mind taking a look at this PR? Maybe there were some reasons that caching for attributed string was eventually abandoned? Thank you!

**Comment by alpavanoglu** [comment]
The comments screen seem to be extremely glitchy. Is this a known problem?

When you mention "cache" I thought we were persistently storing it. We are only keeping a reference to the value right?

**Comment by dvdchr** [comment]
@staskus Thanks for the ping and for tackling this issue 🙂 

> I saw you worked on RichCommentContentRenderer some time ago. Would you mind taking a look at this PR? Maybe there were some reasons that caching for attributed string was eventually abandoned? Thank you!

Ah, yep.  `RichCommentContentRenderer` was actually a fallback created at the last minute because we identified problems with the comment thread when using the `WebCommentContentRenderer`. Since we were running out of time, we decided to use the "previous" rendering method instead of making it work because, at the time, I remember the task was non-trivial.

I made some follow-ups in pctCYC-lD-p2 and pctCYC-m7-p2 to try and tackle the caching problem in the comment threads (along with addressing performance issues), but I ended up never getting the time to "officially" work on this due to team priority shifts. 

In regards to the caching mechanism, unfortunately, I couldn't remember if it was just a plain oversight, or an intentional decision to not use the existing caching mechanism. 😓 I'll review my past notes and see if some info or "gotchas" led me to that decision. I'll also share some test steps (if any) to ensure all aspects/cases are covered.

**Comment by staskus** [comment]
> The comments screen seem to be extremely glitchy. Is this a known problem?

Good question, @alpavanoglu. Without caching and with the debugger connected I found it extremely slow. At least partially it was related to making attributed strings from HTML. I experienced a very similar issue with Stats so I was aware of such problems.

What other glitches are you experiencing?

> When you mention "cache" I thought we were persistently storing it. We are only keeping a reference to the value right

We were keeping `attributedString` cache but we weren't using it for some reason. So we built attributed strings when the view was loading, but also we were building attributed strings every time the cell was rendered. 

My change simply passes already cached attributed string into the cell.

**Comment by staskus** [comment]
Thanks for sharing context @dvdchr. Yes, I found this area to be tricky as well. I spent the whole day experimenting with different mechanisms to solve these crashes and performance issues before noticing that some sort of caching mechanism was already there.

>  I'll review my past notes and see if some info or "gotchas" led me to that decision. I'll also share some test steps (if any) to ensure all aspects/cases are covered.

Thanks! I would appreciate that. I agree that there's a chance that caching attributed strings can create other types of issues with cells.

**Review by dvdchr — APPROVED** [review]
Hey @staskus 👋🏼 , apologies for the delayed response.

> I'll review my past notes and see if some info or "gotchas" led me to that decision. I'll also share some test steps (if any) to ensure all aspects/cases are covered.

I couldn't find anything in my notes about avoiding the existing caching mechanism. So, not using the cache may have been an oversight.

I've smoke-tested it several times (including using pcl4cA-191-p2 and pcl4cA-wc-p2 for testing purposes) and found nothing out of the ordinary. The comment threads screen still needs a major retouch overall, but any improvements are very much welcome—so thank you for spending your time to improve this! 🙂

LGTM.

**Comment by staskus** [comment]
@dvdchr thank you very much for testing this! 👍  I'll keep an eye on comment threads to see if anything unexpected comes out.

**Pull request merged**
