### PR TITLE
My Site: Tighten spacings in the my site screen

### LINKED ISSUE #18268: My Site: Tighten spacings between elements in the site menu
We want to tighten up some of the spacings on the site menu screen.

image

Left is the current spacings and right is the new spacings.

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Fixes #18268

## Description
Tightens some spacings on the My Site screen.

/ | Before | After | After with Dimenions
-|-|-|-
Top | Before-Top | After-Top | After-Top-Dimensions
Bottom | Before-Bottom | After-Bottom | After-Bottom-Dimensions
Top With QuickStart | Before-Top-QuickStart | After-Top-QuickStart | After-Top-QuickStart-Dimensions
Top With Section Footer | Before-Top-Footer-title | After-Top-Footer-title | Same dimensions for the footer

## Testing Instructions

1. Run the app
2. Open the site menu
3. Check that the spacings match the new specs

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by momo-ozawa — APPROVED** [review]
✨

**Comment by osullivanchris** [comment]
@hassaanelgarem thanks for the fix here. Generally looks much better. I hope that you didn't have to hack at default component values to achieve this? My assumption was we had added extra custom space, which we're now taking away. But if you're actually having to reduce padding in the native components themselves please let me know.

Some minor pedantic details for further fine tuning if you're up for it...

First, the Site Menu content still starts 4pt lower down than the Home content. Its tiny. But you can see in the video it slightly breaks the illusion of them sitting in the same segmented control. For me anyway, if they had the exact same top position, it would feel more seamless.
Screenshot 2022-04-05 at 10 39 15

https://user-images.githubusercontent.com/50576199/161726365-51881bda-6d01-49ce-b673-4222d6b68ebe.MP4

Second, while looking closely at that, I actually noticed that our cards don't align to the same margins as the indented table view. 
- The site header, segmented control, and cards all have 20pt margin left/right, and align nicely
- The indented table view has 16pt margin left and right, so it sticks out a bit

I actually reckon 16 is more 'correct'. But given everything else seems to be at 20, maybe we could shift the table view to that value.

Screenshot 2022-04-05 at 10 39 21

**Review by osullivanchris — APPROVED** [review]
I forgot to use the 'review changes' action. I'm gonna approve this anyway, as the details I've noted are tiny and not in the original request here.

**Comment by hassaanelgarem** [comment]
@osullivanchris 

First of all, kudos on catching these tiny discrepancies between the dashboard and the site menu! 🔍 

> But if you're actually having to reduce padding in the native components themselves please let me know.

Our changes so far include nothing hacky or too complex, just customizing some values. So don't worry about that.

> First, the Site Menu content still starts 4pt lower down than the Home content. Its tiny. But you can see in the video it slightly breaks the illusion of them sitting in the same segmented control. For me anyway, if they had the exact same top position, it would feel more seamless.

The difference here is the top margin of sections/cards. This applies to the space above the first section (or cell) and the space between sections/cards. The site menu was 24pts (as detailed in the original issue), and the dashboard was 20pts. I opted to change the spacing on the dashboard to 24pts to follow the 8 point grid.

 

They are now starting at the same position, and the spacing between sections or cards is the same. If you instead want to make them both 20pts, let me know!

> Second, while looking closely at that, I actually noticed that our cards don't align to the same margins as the indented table view.

This, sadly, will be too tricky to solve. We're using a native option to add the indentation to the table. However, the indentation is dynamic based on the device size. So on larger devices, it's 20pts, and on smaller devices, it's 16pts. To unify the left and right margins for the dashboard and site menu, we can do one of two things:
1. Ditch the native approach for table indentation, and implement it ourselves. Then the indentation will be static.
2. Change the margins on the dashboard. However, we'll have to make them dynamic.

Sadly, both options are pretty complex. And in my opinion, it might not be worth the effort and the risk of breaking things. Let me know what you think though!

**Comment by osullivanchris** [comment]
> First of all, kudos on catching these tiny discrepancies between the dashboard and the site menu! 🔍

Appreciate it, glad I'm not just being a pain 😄 

> Our changes so far include nothing hacky or too complex, just customizing some values. So don't worry about that.

ok cool...as long as this is not something we shouldn't change. 

> They are now starting at the same position, and the spacing between sections or cards is the same. If you instead want to make them both 20pts, let me know!

Ok understood and thanks for the reasons above too. Thanks for the explanation. So I have to choose one value which will affect both the vertical space between the segmented control and the cards, and the vertical space between cards. 

I've had a close look, and beneath the segmented control and the start of the cards or list, 20pt looks best. I tried 24pt. I tried 16pt. Both would be preferable for the grid. But 20 looked best 🤷‍♂️ 

20pt is also be preferable because that seems to be the left and right margin on the cards as well. This way the card has 20pt all the way around. Whereas if we do 24 or 16, it has different padding top/bottom to left/right. I do feel like with the 24 in this screenshot the cards are too far apart as well.

So my first choice would be 20pt, unless you think we're breaking things going off that grid. At least it is still on a 4pt grid and not something totally conflicting.


> Sadly, both options are pretty complex. And in my opinion, it might not be worth the effort and the risk of breaking things. Let me know what you think though!

Making the cards also go 16pt/20pt depending on screensize sounds potentially nice. But I agree if there's any complexity here the value is quite low so we can park it.

**Comment by hassaanelgarem** [comment]
> So I have to choose one value which will affect both the vertical space between the segmented control and the cards, and the vertical space between cards.

Yes, exactly!

> So my first choice would be 20pt, unless you think we're breaking things going off that grid.

Done! I updated the spacing on both to 20 👍

**Comment by osullivanchris** [comment]
> Done! I updated the spacing on both to 20 👍

Great, thanks. Looks good to me! I'm happy with it if you are.

**Pull request merged**
