### PR TITLE
Login: fix wpcom password placement with on-screen keyboard

### PR DESCRIPTION
**Pull request by nheagy**
The new wpcom password screen gets slightly weird layout with the on screen keyboard.

Before | After
----|----
wpcom-fix-before|wpcom-fix-after

To test:
- make sure wpcom login via password still works 😜
- ensure the placement of the password field works well

### Note:
this was branched off #7465 and will show its changed until they're merged.

Needs review: @aerych

### CODE REVIEW

**Comment by aerych** [comment]
Nice catch.  I think the way the center-y constraint is set will end up positioning the form a tad too low.  I'd suggest a small tweak, rather than centering the containing stackview vertically relative to the wrapper view, place the constraint on the password field, and center the password field vertically relative to the wrapper view.  This brings form up a smidge so it feels more balanced.  What do ya think?

simulator screen shot jun 30 2017 3 40 24 pm

**Comment by nheagy** [comment]
@aerych yup, I like that.

**Comment by nheagy** [comment]
@aerych change made! How's it look now?

**Comment by aerych** [comment]
Looks good :)  :shipit: once the Podfile conflicts are resolved

**Pull request merged**
