### PR TITLE
Issue/609 upload unsupported media formats

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fix for https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/609

cc @bummytime can you please review?

### CODE REVIEW

**Comment by bummytime** [comment]
@SergioEstevao I ran this branch through a quick smoke test on the iOS 8.2 sim and was not able to upload a small TIFF file. It looks like we are still sending the original TIFF over the wire and therefore the server still responds with a 400:

napkin 04-15-15 9 08 58 pm

**Comment by SergioEstevao** [comment]
@bummytime Can you please sign-out and sign-in to WP.com to force the app to sync the blog properties and then test again. Thanks in advance.

**Comment by bummytime** [comment]
@SergioEstevao So your last batch of fixes seemed to help matters on iOS 8 once I signed out and signed in to refresh the blog metadata...I was able to upload Tiff files like a champ. However on iOS 7 (simulator) it still did not work for me at all.

Also just thinking out loud here, do we think having the users log out and in again in order to gain TIFF support is a good thing? Is there another way we can force the blog refresh?

**Comment by SergioEstevao** [comment]
@bummytime We don't need to force user to logout, the blog properties will sync if they open the blog details page where you see blogs post and page. It will also sync if you click on the drop down blog selector. 
The only scenario that it does't sync the properties in when you only click on the post icon on the main tab. So if we put the fix in the users sooner or later will the blog option sync and the fix will start to be used. 
I can add a blog sync every time we enter the editor page if you think will make it better.

**Comment by SergioEstevao** [comment]
> However on iOS 7 (simulator) it still did not work for me at all.

I've tested this and the app is converting the format and uploading it, did you make sure that the blog options where synced?

**Comment by bummytime** [comment]
> I can add a blog sync every time we enter the editor page if you think will make it better.

Nah, that's ok.

> I've tested this and the app is converting the format and uploading it, did you make sure that the blog options where synced?

Yeah. I tried resetting the simulator as well.  https://cloudup.com/c4pBLMIHxtp

**Comment by bummytime** [comment]
:shipit:

**Pull request merged**
