### PR TITLE
Danger: Add a rule for PRs tagged 'DO NOT MERGE'

### PR DESCRIPTION
**Pull request by frosty**
This PR adds a new Danger rule to fail PRs that are tagged with the 'DO NOT MERGE' label.

**To test**

* Check that this PR fails while it has the DO NOT MERGE label applied.

### CODE REVIEW

**Comment by frosty** [comment]
@astralbodies My main query with this is whether it should be a `warn` instead of a `fail`, so you don't have to rebuild in order to merge.

**Comment by frosty** [comment]
(You can view the revisions of wpmobilebot's comment above to see when it failed the earlier build due to the DO NOT MERGE label)

**Comment by astralbodies** [comment]
@frosty If the Buddybuild status is still a green check mark with the fail on Danger, I think we're good to go. It's not obvious on how to re-trigger Danger to run since label changes don't cause Buddybuild to rebuild but I think it's fine. :shipit: 😄

**Comment by frosty** [comment]
The Danger `fail-on-errors` flag didn't seem to do what I've expected, so I've reverted that change and instead changed the `fail` rule to a `warn` so it doesn't fail the build.

**Comment by frosty** [comment]
Just testing once more...

**Pull request merged**
