### PR TITLE
Disallow spaces in every field except password

### PR DESCRIPTION
**Pull request by kwonye**
Addresses #4459 

Decided to go with option 1 (Disallow them to input a space in relevant fields) with the relevant fields being email, username, and site address as other apps follow this strategy.

Needs review: @koke

### CODE REVIEW

**Comment by koke** [comment]
It works for typing but you can still paste text with spaces in those fields. Do we also need to handle that case? If that's acceptable, :shipit:

**Comment by kwonye** [comment]
> It works for typing but you can still paste text with spaces in those fields. Do we also need to handle that case? If that's acceptable, :shipit:

Thanks for that @koke! I have addressed it by doing a double-check when they click the "Create Account" button. If any of those fields contain a space this pop up will show:

simulator screen shot nov 16 2015 9 18 20 am

**Comment by koke** [comment]
Looks good :+1:

**Comment by kwonye** [comment]
Thanks for the review!

**Pull request merged**
