### PR TITLE
[Dark Mode] Multiple Fixes

### PR DESCRIPTION
**Pull request by danielebogo**
Refs. #12320 

This PR fixes:
- Muriel placeholder color: [bd29ac8](https://github.com/wordpress-mobile/WordPress-iOS/commit/bd29ac834e1ace71c5838c02ee47bc71df49ec24)

- Page List cell labels colors & Delete Button in Site Settings
dark-mode-mix
- Site creation flow
site-creation-dark-mode-dark-01
site-creation-dark-mode-dark-02
site-creation-dark-mode-dark-03
site-creation-dark-mode-dark-04
site-creation-dark-mode-light-01
site-creation-dark-mode-light-02
site-creation-dark-mode-light-03
site-creation-dark-mode-light-04
- Fix Quick Start
quick-start-dark-mode-dark
quick-start-dark-mode-light

## To test:
• Run this branch with Xcode 11 and iOS 13
• Create a new WordPress.com site and check everything works fine in dark and light mode
• Then activate QuickStart and check the site dashboard header has the right color.
• Check the 2 QuickStart checklist have the right colors
• Go to the site settings and try to cancel it. Check the cancel button has the right color.
• Do the same thing building for iOS 12

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
These changes are looking great, @danielebogo! I'll defer to @mattmiklic on the details, but one thing that stood out to me is the address bar on the site preview on dark mode. I believe this can probably stay the same color as it is in light mode. Example:

image

**Comment by mattmiklic** [comment]
I'm on the fence about the background of the site address -- I agree with @iamthomasbishop that the lighter contrast in the light mode example is better; there it's kind of a representation of UI chrome, which will have a high contrast with the site front-end in dark mode since themes aren't dark mode-aware yet.

**Comment by mattmiklic** [comment]
Oh, and on the "We're creating your new site..." screen, that text can be `textSubtle`.

**Comment by danielebogo** [comment]
@mattmiklic 
site-creation-dark-mode-dark-05
site-creation-dark-mode-light-05

**Pull request merged**
