### PR TITLE
Removed split view full screen mode.

### PR DESCRIPTION
**Pull request by frosty**
I'm temporarily removing split view full screen mode (Reader) from `release/6.9` whilst we work out one or two issues. Will reintroduce to `develop` in the near future.

To test: ensure nothing's broken and the Reader section behaves as you'd expect. Also, this should restore back gesture functionality to the app.

Needs review: @kurzee 
cc @catehstn

### CODE REVIEW

**Comment by catehstn** [comment]
Thanks @frosty - LGTM :)

**Comment by kurzee** [comment]
Just in case this is related:

reader-navbar-backbutton

1. iPhone Plus
2. Open Discover.
3. Open a post with a lengthy title.
4. Upon opening (maybe the second time), the title will overlap without any animation in the navbar transition.

Maybe something leftover? Maybe an unrelated issue.

**Comment by frosty** [comment]
Thanks for catching that, @kurzee. Looks like I took out something I shouldn't have. Should be okay now, would you mind retesting the back button?

**Comment by kurzee** [comment]
@frosty that works! :shipit:

**Pull request merged**
