### PR TITLE
Use a 64bits simulator on Travis

### LINKED ISSUE #3870: Tests are failing on Travis
We found out that in Xcode 6.3 Unite Tests that check for throwing exceptions fail on 32 bits architectures.

http://stackoverflow.com/questions/30313658/xctassertthrows-crashes-on-32-bits-architectures

### PR DESCRIPTION
**Pull request by SergioEstevao**
Closes #3870 

Needs Review: @diegoreymendez

### CODE REVIEW

**Comment by diegoreymendez** [comment]
:shipit:

**Comment by sendhil** [comment]
Could we use both @SergioEstevao? Sometimes there are subtle bugs that creep up only on 32-bit devices.

**Comment by SergioEstevao** [comment]
I could configure it, but at the moment there is issue in Xcode 6.3 that
makes our tests fail when running a 32 bits simulator.
Basically tests that try to check if an exception is throw fail and Diego
recently added some of those.

**Comment by sendhil** [comment]
@SergioEstevao @diegoreymendez any idea why those tests fail in the 32 bit simulator?

**Comment by SergioEstevao** [comment]
There was link in the original ticket: http://stackoverflow.com/questions/30313658/xctassertthrows-crashes-on-32-bits-architectures.

It looks it's a Xcode 6.3 bug

**Pull request merged**
