### PR TITLE
New Reader: accessibility improvements

### PR DESCRIPTION
**Pull request by Gio2018**
Adds remaining accessibility labels and idenitifiers
ref  #13580

To test:
- Go to the reader, launch the accessibility inspector and verify that all the elements are accessible

PR submission checklist:

- [x] ~~I have considered adding unit tests where possible.~~ Added in a separate PR.
- [x] I have considered adding accessibility improvements for my changes.
- [x] ~~I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.~~ Not yet released.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @Gio2018 .

I ran through VoiceOver in the new Reader elements and found some issues. Not sure if they're related to this PR as what you added isn't really specified, but for consideration:

Manage > Followed Tags: 
- Tap X button on a tag. VO says 'button possibly close'.
- Tap a tag name. VO says '<tag name> button'. But double tapping it does nothing.

Manage > Followed Sites:
- Tap the right button on a site row. VO just says 'button'.
- Tap a site. VO reads site info, but doesn't indicate what double tapping will do. 

Filter > Tags:
- Select tag - the tag name is read, but nothing says what action is available. 
- Double tapped & filtered by tag, but VO didn't indicate what would happen.

Filter > Sites:
- Select site - the site info is read, but nothing says what action is available. 
- Double tapped & filtered by site, but VO didn't indicate what would happen.

Filter menu:
- When it's first shown on iPad (not having selected anything yet) I couldn't dismiss it. Double tapping somewhere in the Reader view did nothing. 
- Sites and Tags: when I tap once on a site/tag, then double tap off to close the menu, the Reader is filtered by that selection. I expected it to just dismiss without selecting anything.

**Comment by Gio2018** [comment]
> Hey @Gio2018 .
> 
> I ran through VoiceOver in the new Reader elements and found some issues. Not sure if they're related to this PR as what you added isn't really specified, but for consideration:

Thanks so much for these findings @ScoutHarris !! Looks like some of these could definitely be related to this PR; if some aren't, I'll open a separate PR for them. Thanks!!!!

**Comment by ScoutHarris** [comment]
Hey @Gio2018 @bjtitus .

This is much better!

Some additional thoughts:

---
There is inconsistency in managing followed Tags and Sites: 

Tags:
- When a row is selected, the unfollow button is selected and VO reads `unfollow <tag> button`.
- The Tag itself is not selectable.

Sites:
- The Site is selectable separately - VO reads the site info.
- The unfollow button is selectable separately - `unfollow <site name> button`.

---
When selecting the filter Manage button, VO says `Settings. Button`. Can this be more specific?

---
I don't see that these were addressed, so reiterating as they're still present.

Filter menu:
- When it's first shown on iPad (not having selected anything yet) I couldn't dismiss it. Double tapping somewhere in the Reader view did nothing.
- Sites and Tags: on iPad, when I tap once on a site/tag, then double tap off to close the menu, the Reader is filtered by that selection. I expected it to just dismiss without selecting anything.

**Comment by bjtitus** [comment]
> There is inconsistency in managing followed Tags and Sites

So this inconsistency is consistent with the inconsistency in the UI (and also stays consistent with Android atm).🤣 

After talking with @osullivanchris either the Tag needs to also show a preview like Sites, or the Site preview needs to be removed. Since this will have a larger effect we think it should be done separately. For now, I've just disabled the Site preview while using Accessibility. Since you can still filter sites no real functionality is removed but it should be more consistent to navigate.

> I couldn't dismiss it. Double tapping somewhere in the Reader view did nothing.

I'm seeing the same behavior as with any other popover, like the Share Sheet in Safari. I was able to exit using by tapping outside of the popover as well as with the the dismissal gesture:
> Two-finger scrub (move two fingers back and forth three times quickly, making a “z”)
##### from [Learn VoiceOver gestures on iPhone](https://support.apple.com/guide/iphone/learn-voiceover-gestures-iph3e2e2281/ios)

> when I tap once on a site/tag, then double tap off to close the menu, the Reader is filtered by that selection

I think that's expected. Again, testing against the Share Sheet popover on iPad I'm seeing the same behavior you described.

**Comment by Gio2018** [comment]
> (Or, sounds good?)
😀

**Pull request merged**
