### PR TITLE
Blogging Prompts: Add Core Data model and adjust service

### PR DESCRIPTION
**Pull request by dvdchr**
Refs #18375

So... it's a pretty big chunk of changes. But most of it is Core Data, I promise! 😆 I originally intended to split the PR between adding _just_ the Core Data model, and adding the changes to the `BloggingPromptsService` — but there's a naming conflict between the temporary model and the Core Data model so I decided to just fix it in one go.

A couple of notes about the changes:

- Considering the size of changes and the fact that this touches Core Data, I'm thinking to target this for 20.0. I'm just hoping that this won't turn into a gigantic conflict after the release branch is cut 😬 .
- Say goodbye to the temporary model. `BloggingPrompt` is now a Core Data model. 
  - ⚠️ Note: I've added a `siteID` field to `BloggingPrompt` since the user can access multiple sites — but there shouldn't be any impact on the UI side since this has been handled internally in `BloggingPromptsService`. Just make sure that you're always getting the prompts from the service, or remember to add `siteID` when fetching the model directly.
  - Added a convenience method `promptAttribution` that returns `BloggingPromptsAttribution`. 
- To remove the references to `examplePrompt`, I've replaced the calls with the `prompt` instance variable in `DashboardPromptCardCell`, and `CreateButtonCoordinator`.
- As for the changes on `BloggingPromptsService`, it now properly creates new objects and/or updates existing ones.
  - Additionally, I've added a convenience `localTodaysPrompt` method which synchronously fetches today's prompt from Core Data. I'm sure there's a use case for this somewhere. 
- Added some more unit tests.

### Unit tests ⚙️ 

Make sure that the unit tests are passing.

### Manual tests 👀 

- Enable the blogging prompts feature flag.
- Verify that the prompt contents are displayed correctly in the dashboard card, FAB, and the post draft (after tapping the Answer Prompt).

Description | Screenshot
--|--
Dashboard card | dashboard-card
Floating action button | create-post
Post draft | post-draft

## Regression Notes
1. Potential unintended areas of impact
N/A. Feature is not released yet.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A. Feature is not released yet.

3. What automated tests I added (or what prevented me from doing so)
Added unit tests for object mapping and date filtering.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dvdchr** [comment]
I'm pretty sure I've resolved the conflicts in https://github.com/wordpress-mobile/WordPress-iOS/pull/18607/commits/d621615d725b87f004d6f66a6280fa920dd8725d... 😅 . Giving it another go.

**Review by ScoutHarris — CHANGES_REQUESTED** [review]
I'm not sure how the tests are passing on the PR, but locally I'm getting failures on the dates like this:

Screen Shot 2022-05-13 at 12 48 51 PM

**Comment by dvdchr** [comment]
@ScoutHarris Ah, I see... I'm pretty sure this is a timezone issue. Since the dates under test are in UTC, calling `dateAndTimeComponents()` automatically converts the date to the machine's local timezone. The day component ended up moving 1 day back is most likely because your timezone is behind UTC. I should have used [`dateComponents(in timeZone: TimeZone, from date: Date)`](https://developer.apple.com/documentation/foundation/calendar/2293477-datecomponents) instead to extract the components so it ignores local timezone.

I'll post a fix soon! Thanks for noticing this. 🙇🏼 

---

UPDATE: Should be addressed in https://github.com/wordpress-mobile/WordPress-iOS/pull/18607/commits/c3ca0039bdb974bccaef36ce2ff9568c30ee4972

**Comment by ScoutHarris** [comment]
I saw one issue. I don't think it's related to this PR, but noting it here just in case. 

The dashboard card doesn't update with the latest prompt. The compact card does, as does the prompts list, but the dashboard card still displays the previous prompts. I haven't looked, but I _think_ it's related to Leandro's [explanation](https://github.com/wordpress-mobile/WordPress-iOS/pull/18548#issuecomment-1122732989) of why pull-to-refresh doesn't update the card. 

| prompt_cards | prompts_list |
|--------|-------|

**Review by ScoutHarris — APPROVED** [review]
> Considering the size of changes and the fact that this touches Core Data, I'm thinking to target this for 20.0.

I tend to agree. I don't see any PRs (at this time) that change the model, so should be ok until post-freeze. 🤞 

:shipit:  (eventually 😄 )

**Comment by dvdchr** [comment]
Thanks @ScoutHarris !

**Pull request merged**
