### PR TITLE
Integrate wpmediapicker 0.22

### LINKED ISSUE #7757: New Media Picker: Camera option in the media picker doesn't work from all album views
There are issues with the camera option in several places within the app, but I included them all in this issue since they all relate to the same underlying problem with the new media picker.

### Expected behavior

With the new media picker, when I am using the hybrid editor changing my site icon or Gravatar, I expect to see a camera option so I can take a photo or video from within the app. I expect to have that photo automatically added to the my post or be selected for the site icon/Gravatar, or at least be able to see that photo in the picker so I can select it.

### Actual behavior

The camera option in the media picker doesn't work from all album views:

- If I am in the Camera Roll album, after I take a photo/video I see the new photo appear in the Camera Roll, and it's selected so I can use it.
- If I am in the WordPress Media Library album, after I take a photo/video I see the new photo appear in the Media Library album automatically. If I select and add it from there, it is then uploaded and I can use it. If I cancel the process, the photo still appears in my media library in the app but it isn't actually uploaded. (Going to the Media section and selecting the photo results in errors because it isn't actually uploaded to the site's media library but it still appears there.)
- If I am in a different device album, after I take a photo/video nothing appears in my selected album. I have to go back and switch to the Camera Roll to find the new photo/video. This is especially confusing in the Gravatar flow, where the Selfie album is auto-selected but taking a selfie doesn't automatically show the new selfie in that album, so I have to go to the Camera Roll to find and select it as my new Gravatar.

### Steps to reproduce the behavior

**Gravatar flow:**

1. Go to the Me tab.
2. Tap on your Gravatar to change it.
3. You should be taken to the Selfie album on your device. Select the camera option at the top of the screen.
4. Take a selfie with the device camera and select "Use Photo" to use it.

Result: You are taken back to the Selfie album but the new photo doesn't appear.

**Media Library flow:**

1. In Me > App Settings choose "Visual" (the hybrid editor) as your editor.
2. Start a new post.
3. Select the add media button in the toolbar.
4. Choose "WordPress Media" from the Albums list.
5. Tap the camera icon at the top of the WordPress Media album.
6. Take a photo and select "Use Photo." Note that this photo now appears in the WordPress Media album.
7. Tap "Albums" to go back (don't add the photo to your post).
8. Tap "Cancel" to cancel adding media to your post, and then tap the X to close the editor.
9. Open your site's My Sites > Media section.
10. Note that the photo you just took is visible in your media library. Tap on it.

Result: You see the photo details as if it had been uploaded to your site's media library, but the options at the top of the screen (Cancel/Save) aren't the expected ones. Tapping "Cancel" doesn't do anything and tapping "Save" results in the error "Unable to save media item." If you check your media library from a browser you'll see that the photo is not uploaded there.

**Other device album flow:**

1. In Me > App Settings choose "Visual" (the hybrid editor) as your editor.
2. Start a new post.
3. Select the add media button in the toolbar.
4. Select an album other than "Camera Roll" from the list. (For example, the "Favorites" album.)
5. Tap the camera icon at the top of the WordPress Media album.
6. Take a photo and select "Use Photo." Note that the photo doesn't appear anywhere in your selected album.
7. Tap "Albums" to go back.
8. Select the "Camera Roll" album. Note that your photo appears here and you can now select it to add it to your post.

##### Tested on iPhone 6, iOS 10.3.3, WPiOS 8.4.0.20170828

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #7757 

Updates media to 0.21 and address the issues above
To test:

Check the tickets details for steps to test.

### CODE REVIEW

**Comment by bummytime** [comment]
@SergioEstevao was this PR supposed to include `pod 'WPMediaPicker', '0.21'` ?

**Comment by SergioEstevao** [comment]
@bummytime it looks I forgot to push some commits. It's done now.

**Comment by SergioEstevao** [comment]
Because of a crash on the version 0.21 of WPMediaPicker I updated this PR to update to version 0.22.

@frosty do you mind to have a look.

**Comment by frosty** [comment]
@elibud So I verified I can insert media fine with this version, and I fixed the compile error (CircleCI is happy now). There's one issue I found, but it was already existing on 8.4 (I'll write up a separate issue). Shall we merge?

**Comment by elibud** [comment]
@frosty yep lets do it, thanks a lot for taking care of this one

**Pull request merged**
