### PR TITLE
AztecPostViewController: Preventing UIViewControllerHierarchyInconsistency

### LINKED ISSUE #8995: Editor: App crashes when dismissing action sheet for a second time
### Expected behavior
The action sheet dismiss without crashing the app

### Actual behavior
crash

### Steps to reproduce the behavior

They are shown in the gif. The media picker needs to be present for this issue to happen.

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR fixes an ugly  crash in the Posts Editor

Fixes #8995
@etoledom sir, would you be game for a super fun review?

Thanks in advance!

### Scenario: More Options
1. Launch Aztec
2. Press the `+` button
3. Press the `...` button (navbar top right)
4. Press `Keep Editing`
5. Press the `...` navbar button, again
6. Verify the app doesn't crash!

### Scenario: Image Options
1. Open Aztec editor.
2. Add an image to the editor.
3. Press the + button on the input accessory view to show the media picker at the bottom.
4. Tap on the image added to the editor to show the image options.
5. Tap on Dismiss.
6. Repeat 4 and 5. Verify the app doesn't crash

### Scenario: (Even) More Media Options!
1. Open Aztec editor.
2. Tap on the body to activate the accessory input bar.
3. Press + button to open the media picker.
4. Press the ... button on the input accessory bar to show the options of Free Photo Library and Other Apps.
5. Choose Dismiss.

Verify the app doesn't break.

### Scenario: State Restoration
1. Launch Aztec
2. Send the app to Background (CMD + Shift + H in the simulator)
3. Click the **Stop** button
4. Click **Run**
5. Verify Aztec is onscreen (yay! state restoration worked!)
6. Go thru the **two scenarios above** and verify they work fine.

### CODE REVIEW

**Comment by jleandroperez** [comment]
@etoledom single (and general) solution implemented. Ready for another look, thanks god you caught the second scenario!!.

P.S: Testing Scenarios updated (covering State Restoration as well).

cc @jklausa thanks for the notes on the issue, you literally saved me a looot of debugger time!!

**Comment by etoledom** [comment]
I'm sorry! 
I should have noted that all those 3 ActionSheets should be tested from the beginning. 😔

**Comment by jleandroperez** [comment]
@etoledom effectively neutralized the old partial fix. All scenarios looking good now!

Thanks a lot for the super awesome review!!!

**Comment by jleandroperez** [comment]
Woooo thanks a lot for helping me out @etoledom !!!

**Pull request merged**
