### PR TITLE
Post Editor - Make heading style distinguishable from paragraph

### PR DESCRIPTION
**Pull request by pinarol**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/351

This PR updates the style of Heading block and makes it distinguishable from paragraph.

Aztec PR: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1127
mobile-gutenberg PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/525

aztec-bold

gutenberg-bold

**To Test**

**Prerequisites** 
- Remove pods folder and `run rake dependencies`
- Clean Xcode build folder

Repeat [Gutenberg Tests](https://github.com/wordpress-mobile/gutenberg-mobile/pull/525) for both Aztec and Gutenberg editors

**Additional Tests**

1. Dirty Flag:
Open a post, select a Heading text and tap B button
Tap close button
Check if Alert sheet is popped up asking if you want to save or discard changes
(For Aztec classes editor tapping B button also should activate the Update button on navigation bar)

2. Saving
Try Saving post after changing Bold attribute of some part of Header and paragraph blocks
Close the post
Reopen the post
Verify that changes are saved

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by pinarol** [comment]
Hey @iamthomasbishop 👋  You can request a new build from this PR's branch and start reviewing the style

**Comment by iamthomasbishop** [comment]
Changes look nice! I think the text-shadow might be a _tiny_ bit too strong, but it at least is better than no visual difference. Are we using straight css to apply this? If so, what are the values?

One other thing I noticed: When I try go to HTML Mode and change a header, from an `h2` to `h5` by editing the markup, when I switch back to Visual Mode, that change isn't visualized.

**Comment by iamthomasbishop** [comment]
> here is how shadow-x-offset is calculated with respect to the font size:

Ok, thanks for the explanation! Does that code you shared above only apply to _headings_, or _any text _with those fontSizes?

I do think we could pull back on the shadow slightly (~.1 less), but what we have now isn't terrible. Maybe we could try:

```
if fontSize >= 22 {
    return 0.72
} else if fontSize >= 20 && fontSize < 22 {
    return 0.68
} else if fontSize >= 18 && fontSize < 20 {
    return 0.65
} else if fontSize >= 16 && fontSize < 18 {
    return 0.62
} else {
    return 0.6
}
```

> I guess you did this on Gutenberg editor right? If so, it is because we don't support h5 in GB

That's correct. I just found it a little odd – but something we can address separately maybe.

**Comment by pinarol** [comment]
Hey @iamthomasbishop 👋  I've updated the values, this is ready to give another try.

**Pull request merged**
