### PR TITLE
Unescape About Me HTML entities

### PR DESCRIPTION
**Pull request by koke**
I'm only decoding the HTML entities, since I don't want to strip any content.

The new helpers are just a wrapper: Swift bridges `String` with `NSString`, but our custom NSString extensions don't get bridged automatically.

Needs Review: @oguzkocer

### CODE REVIEW

**Comment by oguzkocer** [comment]
I know this is not very likely, but if any of the other fields have &, it can _sometimes_ turn into `&amp;` as well. I think we should unescape all fields. Below are a couple screenshots from my tests. Note that when you change the field and go back to My Profile you won't see this immediately. Go back to Me screen wait a couple seconds and go back to My Profile in order to reproduce the issue. 

simulator screen shot dec 22 2015 15 02 23
simulator screen shot dec 22 2015 15 01 22
simulator screen shot dec 22 2015 14 55 17

**Comment by koke** [comment]
Interesting, I can only reproduce in Display Name:

screen shot 2015-12-22 at 17 05 53

I could argue that looking at the [documentation](https://developer.wordpress.com/docs/api/1.1/get/me/settings/), only `description` says it's HTML, and the other entities are a bug in the API.

**Comment by oguzkocer** [comment]
That makes sense, we should fix it in the API then. I've safe guarded it in Android just to make sure.

**Comment by oguzkocer** [comment]
We've reported the API bug and that doesn't need a client change. So, looks good :shipit:

**Pull request merged**
