### PR TITLE
Data: Organizes core data entity graph.

### PR DESCRIPTION
**Pull request by aerych**
As part of an exercise to review entity relationships I organized the our model's entity graph.  This PR contains the changes.  I figured we might save them for posterity. Maybe? Maybe not? 

To test:
Build the app. Confirm no unexpected issues or warnings when building and the app builds successfully. 
Select the data model and switch to the Style tab from the editor.  Confirm the tables are laid out in a readable graph rather than stacked one atop another.

Example:
Screen Shot 2020-05-21 at 1 42 53 PM

@leandroalonso would you be game to review this one?

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by aerych** [comment]
btw, @ScoutHarris, I just want to say the stats table relationships shown in the example above are a thing of beauty. ;)

**Comment by ScoutHarris** [comment]
> btw, @ScoutHarris, I just want to say the stats table relationships shown in the example above are a thing of beauty. ;)

Oh I wish I could take credit. 😄  We have @jklausa to thank for that. I knew he did a bang up job, but seeing it this way definitely drives it home.

**Comment by aerych** [comment]
> We have @jklausa to thank for that. I knew he did a bang up job, but seeing it this way definitely drives it home.

We know you're out there somewhere @jklausa. 😀  Kudos sir!

**Comment by jklausa** [comment]
:) Thanks y’all, I appreciate the nice words!

**Comment by leandroalonso** [comment]
@aerych thanks for this!

Now I can use the graph view to understand more about our relationships instead of changing back to tables afraid of what I just have seen. lol

**Comment by aerych** [comment]
Thanks @leandroalonso !

**Pull request merged**
