### PR TITLE
Nuking AFNetworking: Notifications Media Downloader

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR replaces AFNetworking with plain URLSession usage.

### To test:
1. You'll need two WordPress.com accounts: **A** and **B**
2. Log into **A** and post a comment into any of **B**'s posts
3. Log into **B** (on the  web) and edit the comment (via wp-admin). You can paste this snippet:
```
Test <img src="https://lanteanar.files.wordpress.com/2017/12/image.jpg">
```
4. Launch WPiOS in **B**'s account
5. Open Notifications List: find the new Notification

Verify the image shows up correctly!

cc @SergioEstevao 
Thanks in advance!!

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@jleandroperez didn't we want to start using AlamoFireImage for this cases?

**Comment by jleandroperez** [comment]
(Discussed on Slack, adding it here for historic purposes!). Detail with this one is that: the NotificationsMediaDownloader has a super custom API, meant to fit with the NotificationDetails comments.

AlamofireImage is probably worthy if we're dealing with setting images directly within a UIImageView, which is not this use case. On this one i believe we're better off using plain URLSession dataTasks!

**Comment by SergioEstevao** [comment]
@jleandroperez going back to this PR and the other one where you [implemented ImageDownloader](https://github.com/wordpress-mobile/WordPress-iOS/pull/9524) is there something that could be share between those two classes?

**Comment by jleandroperez** [comment]
@SergioEstevao i've slightly patched ImageDownloader, aaaand now the integration is possible!. 
Ready for another look sir!!

**Comment by jleandroperez** [comment]
Thank you sir!!

**Pull request merged**
