### PR TITLE
Notifications: fix readable media width and adapt separators for readable insets

### PR DESCRIPTION
**Pull request by kurzee**
Turns out, I was wrong in https://github.com/wordpress-mobile/WordPress-iOS/pull/6675#issuecomment-280771279

I simply wasn't following the correct `readableContentGuide` to calculate the `maxMediaEmbedWidth`. Now using the `tableView.readableContentGuide` and `ceil` value.

Also related, however, was that the separator insets used on block cells weren't use the readable insets for drawing. So that also added to the wide image appearing misaligned. I went ahead and fixed this in this same PR for easy review and comparison.

To test:
1. Follow the same steps in https://github.com/wordpress-mobile/WordPress-iOS/pull/6675
2. Also check that the separator above the action buttons is aligned with the left and right readable margins.

Needs review: @frosty can I bug you with another one of these? 😅 No rush.

### CODE REVIEW

**Comment by frosty** [comment]
Looks good to me, edges match up now :)

One question – do you think the image should adjust its width if the cell gets wider? (for example if you rotate to landscape)?

Otherwise, :shipit:

**Comment by kurzee** [comment]
>One question – do you think the image should adjust its width if the cell gets wider? (for example if you rotate to landscape)?

Yes... yes it should. Will fix that as well.

**Comment by kurzee** [comment]
>One question – do you think the image should adjust its width if the cell gets wider? (for example if you rotate to landscape)?

@frosty fixed! Needed to move the call for refreshing/reloading to animate along the `viewWillTransition` coordinator. Can you give this one more quick spin? Particularly on iPad with split-view.

**Comment by frosty** [comment]
@kurzee Works for me!

:shipit:

**Comment by kurzee** [comment]
Thanks for the testing @frosty!

**Pull request merged**
