### PR TITLE
Jetpack App: Disable new post shortcuts

### LINKED ISSUE #16209: Jetpack App (Basics): Disable posts shortcuts
## Description

Disable shortcuts for the Jetpack target
- New Photo Post
- New Post

### PR DESCRIPTION
**Pull request by momo-ozawa**
Resolves #16209 

## Description
This PR disables the New Post and New Photo Post shortcuts for the Jetpack app

WordPress | Jetpack
-- | --
 | 

## How to test:
1. Delete installed WordPress app
2. Build WordPress and login
2. Long press on WordPress app icon
3. ✅ App shortcuts should be displayed (Notifications, Stats, New Photo Post, New Post)
4. Delete installed Jetpack app
5. Build Jetpack and login
6. Long press on Jetpack app icon
7. ✅ Only the Notifications and Stats shortcuts should be displayed

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Test Jetpack and WordPress schemes

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by leandroalonso** [comment]
@momo-ozawa given the shortcuts work on the Jetpack app I wonder if we really should remove them. Wdyt?

**Comment by momo-ozawa** [comment]
@leandroalonso Updated the PR to only disable the new post/new photo post shorcuts 😄 

p1617476745047800/1617183838.042700-slack-C0180B5PRJ4

**Comment by momo-ozawa** [comment]
Stats shortcut bug fixed in a separate PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/16226

**Review by emilylaguna — APPROVED** [review]
LGTM! Tested using the steps.

All good to go once the conflicts are resolved.

**Pull request merged**
