### PR TITLE
Migrate fetching of Page Layouts call from WPiOS to WPKit

### PR DESCRIPTION
**Pull request by chipsnyder**
### Description
This is a simple refactoring to move the api calls `/wpcom/v2/sites/\(blogID)/block-layouts` and `/wpcom/v2/common-block-layouts` out of WPiOS and into WordPressKit. 

**Related PR:**
`WordPress-Kit:` https://github.com/wordpress-mobile/WordPressKit-iOS/pull/294

### Testing Details
📓 This is easiest to test with a fresh install so you know you aren't just seeing cached data in the app. 

<details>
<summary><strong>To disable or enable the development version of Modal Layout Picker</strong></summary>

- Open the app from the build that allows FeatureFlags such as a PR build or a local development build
    - By default, the modal layout picker will be disabled.
    - From the site page:
        - Click on your Gravatar.
        - Click on App Settings.
        - Click on Debug.
        - Toggle "Gutenberg Modal Layout Picker" to enable or disable the picker
            
</details>

When enabled, the Layout Picker should show when creating a new page from My Site and from the Page list.

- Navigating to the Modal Layout Picker
- Expect page layouts to be fetched and to load.

### PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by chipsnyder** [comment]
Hey @guarani 👋, After our DM chat the other day I was motivated to move these two endpoints to WordPressKit. No rush on this but if you have time I was hoping you could review it for me. 🙏

**Comment by guarani** [comment]
Just a quick comment before I review this (hopefully tomorrow).

I was able to get `NSManagedObject` subclasses to conform to `Codable`: https://github.com/wordpress-mobile/WordPress-iOS/pull/15139/files#diff-99b5ec4dc5a4d9ae723e0341af372bbe3acd319d72fbfc56625ed7f848ddb7ebR21-R24

Which alleviated the need for two models; one for Core Data and another for de-serialization. I'm unsure whether this would be possible if I'd implemented the endpoint in WordPressKit, since it doesn't know anything about CoreData AFAIK.

This isn't to say it's wrong to move this endpoint to WordPressKit, but I wanted share it in case it's useful.

**Comment by chipsnyder** [comment]
> I was able to get NSManagedObject subclasses to conform to Codable:

Oh cool! I'm glad you got that working. I do like that you don't need to have duplicate models.

Ultimately what motivated me to move the call was because it seems to be the more standard process to have the API calls in WPKit. But I still agree with the idea that if you don't have to duplicate the models it might not be worth the move.

**Review by guarani — APPROVED** [review]
Tested build 36638 and looking good! Approved WordPressKit PR here: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/294#pullrequestreview-516837465

**Pull request merged**
