### PR TITLE
Merging Release/5.8 into develop

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Notes:
- Data Model 41 was copied into Develop
- Develop's Data Model 41 is now 'Data Model 42'
- Reimplemented the Heavyweight Migration (former 40 to 41), into 41 to 42

#### Testing
1. Install `release/5.8` and log into your account
2. On top of it, install this branch (`origin/issue/merging-5_8-into-develop'`)

Make sure you don't get logged off, and that the Blog Settings work as expected.

Needs Review: @koke | @astralbodies 
Thanks in advance!

### CODE REVIEW

**Comment by astralbodies** [comment]
Reviewing this now, @jleandroperez

**Comment by astralbodies** [comment]
@jleandroperez Migration looks right - I'll work on manual testing now.

**Comment by koke** [comment]
Migration went fine and settings are there \o/ :shipit: on my side

**Comment by astralbodies** [comment]
Yup, :shipit:

**Comment by jleandroperez** [comment]
Thanks @astralbodies + @koke !!

**Pull request merged**
