### PR TITLE
Merge hotfix 17.7.1 into trunk

### PR DESCRIPTION
**Pull request by mokagio**
Includes #16877 by @emilylaguna.

Notice that I switched to a branch in the release toolkit and then reverted just so I could get the fix submitted quickly. Normally, I would have wanted to ship a new version of the toolkit and switch to it, but this is an hotfix so I prioritized speed.

The build has been approved for release and I started the rollout earlier today. This is ready to review and merge.

### CODE REVIEW

**Review by mokagio — COMMENTED** [review]
- [x] Patch version bump in `.xcconfig`
- [x] No strings or release notes localization changes – Hotfixes bypass localization to ship as soon as possible

**Comment by mokagio** [comment]
Ouch! I did it again, forgot the intermediate branch because the GitHub UI said it could merge without conflict. But there's a difference between being able to merge without conflict and the branch we want to merge being up to date with the base.

**Comment by oguzkocer** [comment]
> Ouch! I did it again, forgot the intermediate branch because the GitHub UI said it could merge without conflict. But there's a difference between being able to merge without conflict and the branch we want to merge being up to date with the base.

@mokagio What is the difference? As in, why does it matter for this PR to be up to date with the base for it to be reviewed and merged?

**Comment by mokagio** [comment]
It doesn't matter from the reviewing point of view, but it blocks the possibility to merge the PR, at least as far as I understand. This is the same thing that happened 

The PR branch needs to be up to date with trunk, but all these branches come from `develop`. To put them in sync with `trunk`, we'd need to merge `trunk` into them. Merging `trunk` into `release/17.7.1` would be inappropriate. Or maybe it isn't... we have the tag as the source of truth and the release branch gets deleted afterwards. Still, right now, while the PR into `release/17.8` hasn't been merged yet, that's definitely not appropriate.

🤔 maybe, instead of using the intermediate branch, I should just wait till the matching PR into `develop` has been merged next time.

Thanks for the food for thought @oguzkocer.

**Comment by oguzkocer** [comment]
@mokagio As I understand it, you're looking to guard against the potential merge conflict if the base branch moves. In this case - in theory - that should never happen because `trunk` should only be updated during a new release which should also update current `develop` and any other release branches with the same commits.

Furthermore, I understand creating an intermediate branch just for the peace of mind and not having to deal with potential merge conflicts, but I don't think the base branch should be merged until it's necessary. That's to say - in my opinion - "up to date with the base" shouldn't be a concern until there is a merge conflict.

For me that comes down to communication through commits. Having that merge commit tells me that there was a conflict to be resolved and I should look into whether that was done correctly while I review it. In this case, I like to re-create the conflict in a temporary branch and resolve it and check that it matches what the author did. Hope that clarifies my point of view!

**Comment by mokagio** [comment]
> "up to date with the base" shouldn't be a concern until there is a merge conflict.

That resonates. At the moment, we have a setting that enforces that requirement, for admin users, too.

Screen Shot 2021-07-20 at 3 20 51 pm

We'd need to disable that first. The rule is not active in `develop`. I also checked WordPress Android and WooCommerce iOS, just for a sample, and they don't have that requirement. I guess this was set as an experiment or even accidentally? What does the rest of @wordpress-mobile/owl-team think of the idea of removing the "Require branches to be up to date before merging" rule from this repo in `trunk`?

**Comment by mokagio** [comment]
> For me that comes down to communication through commits. Having that merge commit tells me that there was a conflict to be resolved and I should look into whether that was done correctly while I review it.

I had never though of that in those terms, but I really like the "communication through commits" idea. I try to write useful and informative commit messages, for example, in a merge I usually leave the list of files that had conflicts and add notes on the rationale behind the resolution I applied.

That a merge commit declares intent is totally in line with that. In that case, not having an intermediate branch is definitely clearer. 

Thank you for sharing 😄

**Comment by mokagio** [comment]
> What does the rest of @wordpress-mobile/owl-team think of the idea of removing the "Require branches to be up to date before merging" rule from this repo in `trunk`?

I haven't gotten a reply on this. I went ahead and disabled it to keep it consistent with other projects. Easy enough to revert this decision.

image

**Pull request closed without merging**
