### PR TITLE
Issues/5927 non latin tags

### LINKED ISSUE #5927: Reader: Adding a tag with non-Latin characters returns an error
### Expected behavior

I expect to be able to add tags in non-Latin languages such as Japanese and Arabic.

Example tags in the web reader:
https://wordpress.com/tag/%D8%B3%D9%84%D8%A7%D9%85
https://wordpress.com/tag/%E7%A7%81

### Actual behavior

Trying to follow a non-Latin tag such as `سلام` or `私` returns an error:

> Could Not Follow Tag
> unsupported URL

### Steps to reproduce the behavior

1. Open the Reader tab
2. In the menu, tap "Add a Tag"
3. Enter a tag with non-Latin characters (either all non-Latin characters or a mix)
4. Tap "Add Tag"
5. An alert message appears with the error "Could Not Follow Tag" and "unsupported URL"

### PR DESCRIPTION
**Pull request by aerych**
Fixes #5927 

To test:
Try following one of the tags mentioned in the issue. 
Confirm you can successfully add and remove the tag.
Additionally, try to follow the special character `%` as mentioned in @rachelmcr's comment in #5908.  Its a bit weird, but confirm that the behavior matches the web reader.

Needs review: @kurzee

### CODE REVIEW

**Comment by kurzee** [comment]
@aerych hmm, still seeing a "Could not follow tag"-"Operation could not be completed" error when leaving the text field empty, or with a space, following the steps in https://github.com/wordpress-mobile/WordPress-iOS/issues/5908

**Comment by kurzee** [comment]
Closing this one for now, I'll reopen this one with a new fix for the original issue, since Eric is out.

**Comment by kurzee** [comment]
Merging this one as the primary issue being the use of non-latin tags is resolved.

The other issue of errors on spaces, $, % and the like is a separate issue that can address in another way, more of a validation of the input.

**Comment by aerych** [comment]
@kurzee Thanks for the review and the merge

> The other issue of errors on spaces, $, % and the like is a separate issue that can address in another way, more of a validation of the input.

This PR was never intended to address that issue.  That issue was handled in #5929 and its changes were not included in this PRs branch.

**Pull request merged**
