### PR TITLE
Pressing enter in the verticals screen now performs an action.

### PR DESCRIPTION
**Pull request by diegoreymendez**
This is the first PR to fix: https://github.com/wordpress-mobile/WordPress-iOS/issues/12047

Pressing enter in the Site Verticals screen will now find attempt to submit the vertical selection with a perfect match.

enterInSiteVerticals

## Testing:

1. Go to the sites list.
2. Create a new WP.com site.
3. At the verticals selection screen type any input and press enter / tap return.
4. If you have a connection, the form should submit.  If you have no connection, nothing should happen.

Try combining pressing enter with tapping on a cell almost simultaneously - it shouldn't crash.

## Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by aerych** [comment]
@diegoreymendez 
 Is there a better text option for the button other than "return"?  Maybe "Next" since tapping it or pressing enter should move you to the next step?

**Comment by diegoreymendez** [comment]
@aerych - I though I had changed it to "Next" but I'll need to double check when I'm back from AFK... in the meanwhile and just to verify, have you seen this after running the demo or in the gif?

Bottom line: suggestion makes a ton of sense, and it was in my plans.  We'll need to review the design after this PR though as there's a "Next" button right above the keyboard too.

**Comment by diegoreymendez** [comment]
Thanks @aerych.  I deleted a comment I had posted since it was off... I'll review when back from AFK.

**Comment by diegoreymendez** [comment]
@aerych - The return button is now "Done".

I realize "Next" may feel like the obvious option here, but "Done" is currently more consistent with another PR I'm pushing for the next step (in which we have two fields and "Next" is used for moving to the next field.

**Comment by diegoreymendez** [comment]
I'm pushing since there's an approval (and so I can push another PR), but feel free to keep commenting @aerych and I'll address.

**Comment by aerych** [comment]
> The return button is now "Done".

Works for me!

> I'm pushing since there's an approval

Its all good sir! :)  Cheers!

**Pull request merged**
