### PR TITLE
Integrates the correct editor pod.

### PR DESCRIPTION
**Pull request by diegoreymendez**
The version of the editor pod for WPiOS v4.7.1 was incorrect. I just updated it to v0.3.1 to include our latest fixes.

This is urgent since we need to include it in the next internal for v4.7.1 for testing.

Whoever can first review this: @bummytime, @sendhil, @SergioEstevao

Thanks in advance!

### CODE REVIEW

**Comment by bummytime** [comment]
Hey @diegoreymendez, @sendhil made the decision to not include 0.3.1 in 4.7.1. So I'll let him decide if he wants it in there :smile: :hamster:

**Comment by diegoreymendez** [comment]
Hey @bummytime, thanks for the heads up.  I just talked with @sendhil and he mentioned we can include these changes for 4.7.1, since there's still going to be another internal release.

**Comment by bummytime** [comment]
Well, then :shipit: !

**Pull request merged**
