### PR TITLE
[Choose a Domain] Update search results to behave more like Android

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes** https://github.com/wordpress-mobile/WordPress-iOS/issues/15378
**Related PR:** 
    - `WordPressUI-iOS`: https://github.com/wordpress-mobile/WordPressUI-iOS/pull/79
    - `WordPressKit-iOS`: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/314
    - `WordPressAuthenticator-iOS`: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/542

### Search results have a match
1. Navigate to the Create WordPress.com site
    - My Sites > ➕ > Create WordPress.com site 
1. Choose a design or skip (this should be tested with each path to trigger both endpoints) 
1. Search for a Domain
1. **Expect** 
    - To have a maximum of 20 results displayed (Could be less depending on domain availability and your search term)
    - You should be able to scroll so the last row beyond the keyboard
    - The results should be sorted with exact matches first, then alphabetically after that. (Subdomains are sorted alphabetically)

### Search results don't have a match
1. Navigate to the Create WordPress.com site
    - My Sites > ➕ > Create WordPress.com site 
1. Choose a design or skip 
1. Search for a Domain
1. **Expect** 
    - To see a cell with `{your search term}.wordpress.com` and `This domain is unavailable`

## Screenshots:

Exact Match | No Match
--- | ---
<kbd><a href="https://user-images.githubusercontent.com/3384451/101957800-21215100-3bd0-11eb-90c3-8febb14bd77c.png"></a></kbd> | <kbd><a href="https://user-images.githubusercontent.com/3384451/101957932-634a9280-3bd0-11eb-8180-0935e04680d7.png"></a></kbd>

## Additional Context: 

This is a continuation of the work done in the [Home Page Picker Project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Home%20Page%20Picker) and specifically the [Round 2](https://github.com/issues?q=is%3Aissue+label%3A%22Project%3A+Home+Page+Picker+Round+2%22) set of requirements. 

## PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by chipsnyder** [comment]
Hey @kyleaparker and @iamthomasbishop, here's the PR for the Choose a Domain changes. When you get a chance I'd love to hear what you think.

**Comment by kyleaparker** [comment]
Thanks for the ping @chipsnyder! This is looking really good 😄 

I found a bug where if I delete all the text it seems to keep the last letter rather than going back to the empty state: 

Monosnap 2020-12-14 17-42-29

There also seems to be a bit of a delay populating the results and knowing if the domain is available/unavailable. At the same time the results jump around a bit. I could see people getting a little bit frustrated if they see the domain they like, they go to click on it, and the list suddenly changes. Can we wait until we have all the results before displaying them?

**Review by antonis — COMMENTED** [review]
Great work @chipsnyder 👍 
I tested on an iPhone SE 2020 with iOS 14.2 and an iPad Simulator with iOS 14.2. Everything seems to work as expected except the already reported issue by @kyleaparker 

> I found a bug where if I delete all the text it seems to keep the last letter rather than going back to the empty state:

Android cleans the results table on each input change. Aligning with this behaviour should also fix the above.

I also noticed a minor issue with the selection checkmark disappearing when result cells are redrawn.

<image width = "360" src="https://user-images.githubusercontent.com/304044/102085159-eeb96300-3e1e-11eb-96e8-a2089f37a15e.gif"/>

The code and the added test cases look consistent too me 🎉

**Comment by chipsnyder** [comment]
Thank you @kyleaparker and @antonis for pointing out these bugs 🙇 I'll take a look at them ASAP. 

>Can we wait until we have all the results before displaying them?

@kyleaparker We end up searching for nearly every typed character but then when the results come back we sort them then display them. But we throttle the network requests to prevent too many requests at once. I'll play around with other ways to do this though and see how it feels. I'll start with @antonis' suggestion to clear the results with each character.

**Comment by chipsnyder** [comment]
Hey @kyleaparker and @antonis I just put together a new build for us for the Choose a Domain screen in it:

1. I tackled the issue where the selected domain would appear deselected after scrolling.
1. Manually clearing the text by backspacing will also clear the results
1. I wait until the user stops typing for half a second before making the search to get results, (this appeared to be the same as Android).

Let me know what you think 😄

**Review by antonis — APPROVED** [review]
Hey @chipsnyder 👋 

Thank you for the changes 🙇 

> 1. I tackled the issue where the selected domain would appear deselected after scrolling.
> 2. Manually clearing the text by backspacing will also clear the results
> 3. I wait until the user stops typing for half a second before making the search to get results, (this appeared to be the same as Android).

The issues are fixed and the app behaves correctly IMO 👍 
The code changes LGTM 🎉

**Pull request merged**
