### PR TITLE
Update pods

### LINKED ISSUE #8609: Update outdated pods
```
- AFNetworking 3.1.0 -> 3.1.0 (latest version 3.2.0)
- Crashlytics 3.9.3 -> 3.9.3 (latest version 3.10.0)
- Fabric 1.7.2 -> 1.7.3 (latest version 1.7.3)
- HockeySDK 5.1.1 -> 5.1.1 (latest version 5.1.2)
- Starscream 3.0.3 -> 3.0.3 (latest version 3.0.4)
```

@jklausa can you take care of this? I can review :)

### PR DESCRIPTION
**Pull request by jklausa**
Updated pods and the version of Cocoapods we use to `1.4.0`.

Output of `pod outdated` is now:

```
The following pod updates are available:
- CocoaLumberjack 3.2.1 -> 3.2.1 (latest version 3.4.1)
- lottie-ios 1.5.1 -> 1.5.1 (latest version 2.5.0)
- UIDeviceIdentifier 0.5.0 -> 0.5.0 (latest version 1.1.1)
```

The AFNetworking update introduced some new warnings to the project, let me know if you want to keep it that way or roll it back?

screen shot 2018-02-20 at 18 30 51

Fixes #8609.

To test:
Run the app and make sure nothing obvious breaks. I clicked around the app, tried logging in with Google and everything seemed fine.

### CODE REVIEW

**Comment by elibud** [comment]
> The AFNetworking update introduced some new warnings to the project, let me know if you want to keep it that way or roll it back?

Nope we can't have new warning, it seems like we have conflicting declarations though? Mabye it's included in two different places and only one was updated?

**Comment by jklausa** [comment]
@elibud it's not "our" warning, it's from inside `AFNetworking`. 

Here: https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFNetworkReachabilityManager.h#L115
```
/**
 *  Initializes an instance of a network reachability manager
 *
 *  @return nil as this method is unavailable
 */
- (nullable instancetype)init NS_UNAVAILABLE;
```

They redefined `init` as `nullable`, because you're not supposed to create that object like that, but i conflicts with `-[NSObject init]`, which is marked as `nonnull`.

**Comment by elibud** [comment]
Oh that's not smart, lets hold off in updating that one. When doing releases is very hard to spot real warnings in the project otherwise. I'm sure they'll fix it soon.

**Comment by jklausa** [comment]
👍, rolling it back for now.

**Comment by jklausa** [comment]
@elibud Rolled back.

**Comment by jklausa** [comment]
@nheagy adding you as a reviewer since there were some issues with updating `GoogleSignIn`, and we're not sure if this should be at 4.1.2, or below 4.1 because of the popup mentioned in #7927

**Comment by diegoreymendez** [comment]
@jklausa - I created [a new pod update PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/8887) that's more up to date.  I'm closing this PR in favor of the new one.

**Pull request closed without merging**
