### PR TITLE
Wiring Native Followers Interface

### LINKED ISSUE #3349: Notifications: Header tap Handling
Whenever the user taps a notification header, we should proceed as follows:

```
1. if note.type = 'follow' => push native stats followers 
2. if meta.ids has 'commentId' => push comments view 
3. if meta.ids has 'postId' => push post 
4. else open note.url
```

### PR DESCRIPTION
**Pull request by jleandroperez**
Closes #3349

**Note:** 
This needs to be tested in the Notifications Testing bucket.

### CODE REVIEW

**Comment by jleandroperez** [comment]
@astralbodies last PR of the day, i promise!.

Thanks!

**Comment by astralbodies** [comment]
Is there a different API key for the notifications testing bucket?

**Comment by jleandroperez** [comment]
@astralbodies we use a different bucket. I'll poke you in PM with the details, thanks!

**Comment by astralbodies** [comment]
This works flawlessly - nice! Its good to see some of the work reused :smile: 

The only comment I have is that I don't know if its terribly intuitive to tap on the header to view all of the followers. I feel like if I were interacting with it, I'd expect the View All to be at the bottom of the list because I want to continue scrolling. Intuitively I don't know what to expect to happen when I tap on the site row in position 0.

code-wise and after testing it -> :shipit:

**Comment by jleandroperez** [comment]
Thank you @astralbodies !!. This is the way it's currently wired for (all of the) notifications. I'm /cc'ing our awesome UX expert, @drw158.

Dave, do you think we should tweak a little bit the Header so it's 10000% obvious that it's a tappable element?. Maybe a right ( i ) indicator?

**Comment by astralbodies** [comment]
The detail disclosure indicator isn't appropriate really - the standard disclosure indicator (right-facing chevron) works well to indicate it's tappable. I just don't know *why* its tappable as an inexperienced user.

**Comment by jleandroperez** [comment]
I think we had this conversation (long) ago with Dave. But if it's not immediately evident, maybe we should revisit that decision!

**Pull request merged**
