### PR TITLE
Issue/3708 clean up temporary video files

### LINKED ISSUE #3708: Cleaning of media files should also clean up videos and video thumbnails
Since we now have video files on the app we should also check for eventual temporary files created by uploads of video and the correspondent video thumbnails.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Closes #3708 

How To Test:

 * Using the simulator (iOS 8 or above)
 * Create a new post
 * Add a video to the post
 * Kill the app while the upload is happening
 * Check the simulator folder for the app, for a video file with extension .mov that represents the video you where uploading
 * Restart the app and after a while check to see if the video was deleted.

In case you don't have a video in your simulator just drag and drop a video file to the simulator screen. It will open safari to preview the video. Stop/Pause the video and then click the share button and select Save Video to save it to the Camera Roll of the simulator.

Nees Review: @diegoreymendez

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@SergioEstevao - Thanks for the testing path, it was a time saver.

This worked nicely for my .mov file, but didn't work for my mp4 file.  This got me thinking we should find a mechanism that doesn't require us to specify file extensions to know which files to delete (since it's prone to errors: there's no insurance the file extension is enough to know if the file has to be deleted).

I was wondering if we could us the `/tmp` directory for storing these videos instead.  Quoting from [Apple's docs](https://developer.apple.com/library/ios/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html):

```Use this directory to write temporary files that do not need to persist between launches of your app. Your app should remove files from this directory when they are no longer needed; however, the system may purge this directory when your app is not running.
The contents of this directory are not backed up by iTunes.```

**Comment by SergioEstevao** [comment]
These files are actually not temporary if all goes well they are the local
copy of the asset. This only happens if the app is killed during the upload
process and the media is not linked... Regarding the file type it's ok to
add the other, I think iOS only supports MP4 and MOV but I will double
check.

**Comment by diegoreymendez** [comment]
But we could improve this considerably if we instead:

1. **Had a specific media directory to store post media files:** so that we know what our media files are regardless of extension.
2. **Stored uploads in the /tmp directory until the upload succeeds:** and move them to our media folder from point 1 when the upload succeeds.

Right now we could be removing files stored for other purposes (even if no other feature is currently storing media files, we can't assume the files in that directory are post media files).

**Comment by SergioEstevao** [comment]
I agree with you @diegoreymendez , but I think that should be another PR, this is a just a quick fix for the pending videos.
I starting to implement the support for the Media Library again and I'm planning to change how and where we store media locally. 
One of them will be the place where we store the media and correspondent thumbnails, and it's something very similar to what you are proposing.

**Comment by diegoreymendez** [comment]
Sounds good to me Sergio. :shipit:

**Pull request merged**
