### PR TITLE
Fixes issue:  Reply comment button is unreadable in Spanish #3653

### PR DESCRIPTION
**Pull request by knutigro**
by resizing font to fit width.

- https://github.com/wordpress-mobile/WordPress-iOS/issues/3653

### CODE REVIEW

**Comment by koke** [comment]
screen shot 2015-05-20 at 23 49 50

That looks tiny, I'd rather use auto layout to shrink the reply field a bit

**Comment by knutigro** [comment]
@koke I was considering that approach at first but was a little afraid to resize stuff in the UI, since it feels like I am changing the design even more. Anyway, I think you are right, it will probably be better with autolayout. I will fix it.

**Comment by koke** [comment]
I actually tried to fix this myself when I reported it, but the tricky bit is that the "bezel view", that draws the rounded rectangle border of the text field, also draws the top 1px border of the reply view, so if you resize that, the top border doesn't reach the end.

**Comment by aerych** [comment]
> but the tricky bit is that the "bezel view", that draws the rounded rectangle border of the text field, also draws the top 1px border of the reply view, so if you resize that, the top border doesn't reach the end.

It sounding like we need to rebuild that view...

**Comment by jleandroperez** [comment]
Closing this one in favor of #4125. `ReplyBezelView` doesn't draw the top separator anymore :smile: 

@knutigro thank you for helping us out!!

**Pull request closed without merging**
