### PR TITLE
The post can't be saved now unless it has a title and content.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/441).

/cc @bummytime

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@aerych - So if you see the old code, you'll notice that I kept most of it in the same level (in the classes hierarchy) as before.  I think your observation about moving the code to `BasePost` is good, but I feel that change would be best implemented as a separate issue:

- Document the purpose of each class
- Move these methods down/up the hierarchy.
- Make sure every method and property being accessed by these methods are available at the appropriate level.

**Comment by diegoreymendez** [comment]
@aerych - The issue with spaced in the title and content fields should now be fixed with my latest commit.

**Comment by diegoreymendez** [comment]
@aerych - Just created [an issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/2991) for the `BasePost` vs `AbstractPost` thingie.

**Comment by aerych** [comment]
> So if you see the old code, you'll notice that I kept most of it in the same level (in the classes hierarchy) as before.

To me it looked like the modifications to `BasePost` consisted of three new methods and a method moved from `AbstractPost` into `BasePost`.  Why create a secondary PR to modify changes in this one?

**Comment by diegoreymendez** [comment]
@aerych - I read your message exactly the opposite way of what you meant (I interpreted you wanted to move the methods to base post).  I'll re-review it in a few mins and close the issue if it applies.

**Comment by aerych** [comment]
I just re-read it myself and I could have worded it a lot better!  Fwiw, I was trying to say that the methods in question don't really apply to ReaderPosts (which also inherits from BasePost) so maybe they would fit better in `AbstractPost`.

**Comment by diegoreymendez** [comment]
@aerych - This is ready for another look & test.  Please let me know if there's anything else.

**Comment by aerych** [comment]
Looks good @diegoreymendez :)  I say :shipit:

**Pull request merged**
