### PR TITLE
Reverts Plans removal

### PR DESCRIPTION
**Pull request by frosty**
Reversion of wordpress-mobile/WordPress-iOS#5471. 

I'll post another PR afterwards, knocking out the StoreKit-specific code.

Needs Review: @kwonye

### CODE REVIEW

**Comment by kwonye** [comment]
> I'll post another PR afterwards, knocking out the StoreKit-specific code.

Can we keep the StoreKit work in? I know it's paused right now, but we'll revisit it once plans on web becomes more stable. For this reason, I think we should keep it in.

**Comment by kwonye** [comment]
Works great, but since this is going back to develop, I'd like us to flesh out the final details. What is the text going to say when someone wants to get a new plan and where is that going to go?

**Comment by frosty** [comment]
@kwonye Yep, so I was planning on keeping the StoreKit code in there so that we can easily re-enable it in the future.

This PR is going into `develop`, but the feature is feature flagged to debug so I figured we could do a separate PR for the tweaks to the functionality. But it's such a small change I'm happy to add it into here. I'll push up some code. 👍

**Comment by frosty** [comment]
@kwonye: I've removed pricing and purchasing. Do you want to take a look at the latest commit?

It's mostly as simple as returning empty prices for the plans, which hides all of the UI for us. At the moment, I've just set a footer on the plans list screen that mentions where to buy. Do we need anything in the comparison view as well, or is this enough? I worry that if we push the website too much we might get rejected. Here's how it looks:

plans-1

**Comment by kwonye** [comment]
Looks great! :shipit:

**Comment by frosty** [comment]
Thanks @kwonye!

**Pull request merged**
