### PR TITLE
Gutenberg: Fetching RNAztecView from gutenberg-mobile

### PR DESCRIPTION
**Pull request by etoledom**
This PR updates the Podfile to load the RNAztecView from the `gutenberg-mobile` repo.

To test:

- Run `rake dependencies`
- Build and run the project. (might need to clean build folder or build with legacy build system)
- Check that it build without errors.
- Open the Gutenberg editor and check that it displays without errors.

### CODE REVIEW

**Comment by etoledom** [comment]
Ok, this is not working as expected.
I can reproduce this error locally after removing the `Pods` folder.
- First time I run `pod install`, it shows the error
- Second time I run `pod install`, it install the pods without errors 🤷‍♀️

As an alternative, I tested moving the `RNTAztecView.podspec` file to the root of `gutenberg-mobile` together with `Gutenberg.podspec` and it seems to work better.
In this way we also avoid messing up with the `.podspec.json`.

What do you think @koke ?

**Comment by etoledom** [comment]
I implemented that change as a proposal https://github.com/wordpress-mobile/gutenberg-mobile/pull/484

**Comment by diegoreymendez** [comment]
@etoledom - I'm a bit confused as to where to start reviewing.  Should I head over to `wordpress-mobile/gutenberg-mobile#484` first?

**Comment by etoledom** [comment]
Yes, sorry. I fixed the PR "on the fly" and I didn't added test steps.

- Let's first check if https://github.com/wordpress-mobile/gutenberg-mobile/pull/484 looks OK, then,
- If we merge that one, we update the Podfile on this PR to point to develop.

**Pull request merged**
