### PR TITLE
Retire Open Sans in favor of system fonts

### LINKED ISSUE #4895: Retire Open Sans in favor of system fonts.
We're about ready to make the change from Open Sans to system fonts for UI text in Calypso. Opening this issue to start thinking through what we'll need to change on iOS to match.

I think that everywhere we're using Open Sans, we should be able to simply use SF at the same size and weight. No change should be made to the text that's set in Merriweather, our serif typeface.

Ref: https://github.com/Automattic/wp-calypso/pull/3016

### PR DESCRIPTION
**Pull request by koke**
There was already a newer version of the Editor (1.1.4), was that OK to update?

Fixes #4895 
Cc: @mattmiklic 
Needs review: @SergioEstevao

### CODE REVIEW

**Comment by koke** [comment]
Vertical spacing on notification buttons looks a bit tight. @mattmiklic is this OK?

simulator screen shot 09 mar 2016 08 43 49

**Comment by SergioEstevao** [comment]
That editor version is still being tested for integration on the main repo. You should wait for that PR to be merged in instead of bumping here. Btw that version still doesn't remove open sans only the next one will do. That will be two weeks from now.

**Comment by koke** [comment]
This one? #4925

Let's wait until that's merged then

**Comment by koke** [comment]
Ready for review, that was quick :smile:

**Comment by mattmiklic** [comment]
> Vertical spacing on notification buttons looks a bit tight. @mattmiklic is this OK

Those could benefit from being moved down 2-4px.

**Comment by koke** [comment]
Added 2px of separation:

simulator screen shot 09 mar 2016 17 27 15

**Comment by mattmiklic** [comment]
Vertical spacing looks good! I'm just noticing now that Like and Spam look like the labels are not completely centered with the icons above them. It looks like the text in SF doesn't align quite the same as it did in Open Sans. I think both of those icons could benefit from shifting 2px to the left, if that's doable.

**Comment by SergioEstevao** [comment]
:shipit:

**Pull request merged**
