### PR TITLE
UGC: Add "Block this Site" button and hide blocked site's posts from the Reader's Following tab

### LINKED ISSUE #19981: Make the block site option available on posts of followed sites #17590
In order to make the block site option more prominent, we want to make it available both for followed and unfollowed sites. When a followed site is blocked it should also be unfollowed automatically.

Currently,  the "Block this Site" button appears only for Unfollowed Sites.

This task is to add the "Block this Site" option to the actions sheet on posts of followed sites.

| Followed Site | Unfollowed Site |
| - | - |
| Image | Image |

#### Tasks

- [x] Add "Block this Site" button and hide Blocked Site's posts from the "Following" tab in Reader.
- [x] Hide the Blocked Site and its Posts from the Search Results.

### PR DESCRIPTION
**Pull request by salimbraksa**
Fixes #19981

## Related PR
This PR is blocking the following:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/20053

## Description

Similar to unfollowed sites, this PR adds ability to block followed sites.

| Before | After |
| ------ | ------ |
|  | <video src="https://user-images.githubusercontent.com/9609223/217881379-a4a52836-9942-4c2c-896e-6531b46fc2d4.mp4"></video> |

## Test Instructions

**Prerequisites**

Please make sure to test this PR for both **wp.com sites** and **self-hosted sited**. You can discover sites to follow in the Reader Discover screen or you can follow these sites:
- **Self-Hosted Site**: https://www.tannr.com/
- **Dotcom Site**: https://apetcher.wordpress.com

**Case 1: Blocking sites from Reader Following screen**

1. Clean install WordPress app and log into your account.
2. Head to Reader screen > Following tab.
3. Find a post from a **Self-Hosted** site.
4. Tap ⠇button.
5. **Expect** "Block this site" button to be visible. The button's color should be red.
6. Tap "Block this site" button.
7. **Expect** all site posts to disappear immediately, then a notice should appear informing the user that the site is blocked.
8. Repeat 3-7 steps but with a dotcom site. 

**Case 2: Blocking sites from Reader Post screen**

1. Head to Reader screen > Following tab.
2. Tap the post title to head to Post Details screen.
3. Tap ⠇button. 
4. **Expect** "Block this site" button to be visible. The button's color should be red.
5. Tap "Block this site" button.
6. **Expect** the Post Details screen to dismiss after a few seconds and all sites posts to disappear.

## Regression Notes

1. Potential unintended areas of impact
"Blocking followed sites" is an additive feature so it shouldn't break existing behavior but it would be great to test "Block unfollowed sites" feature. You can find unfollowed sites in "Reader > Discover" tab.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Existing Unit Tests and Manual Tests.

3. What automated tests I added (or what prevented me from doing so)
None.

## PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ovitrif** [comment]
👋 @salimbraksa 

I've tested this and encountered two strange issues. At first I thought they were just a one-time fluke but after more testing I was able to repro them again.

When following the **test Case 1** I encountered this issues 2 times:

1. if I go fast enough to `Following` → `Following filter` after following the 2 sites they appear twice in the list.
2. Afterwards, if I try to block one of the sites, I get a small in-app notification saying `Unable to block site`.
   The app actually removes the posts and then they appear again, together with the small notification at the bottom. If I go to `Followed Sites` the site is no longer in the list.

| 1. Duplicated Followed Sites | 2. Unable to block site |
| - | - |
|  |  |

The other times I tested both test cases passed without issues.
I'm not sure if these issues are specific to this PR, but I couldn't repro them on the prod version 🤷 .

Not sure if you encountered them or know more about what could cause them.

---

When following the **test Case 2**, sometimes the `Block this site` button doesn't show. After restarting the app, it appears:
| Post of newly followed site | Same post after app restart |
| - | - |
|  | 

As I see the same thing happens with the existing `Report this post` button, so for me this is not blocking 👍

**Review by ovitrif — COMMENTED** [review]
@salimbraksa 👋 

Thank you for your work on this 🙇 

I have reviewed the PR and left a [comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/20023#issuecomment-1428129408) describing some issues I've encountered while testing.

I'm not 💯 the issues from **test case 1** are introduced in this PR but I couldn't repro them on `trunk`.

As for the issue from **test case 2** that wouldn't feel like a blocker to me seeing the same thing is already reproducing on `trunk` but would be nice to have it fixed 👍

**Comment by salimbraksa** [comment]
Thanks for testing @ovitrif, I'll investigate those issues and try to figure out whether they're caused by this PR or something else.

**Comment by ovitrif** [comment]
@salimbraksa I tried today again to reproduce the [1st bug](https://github.com/wordpress-mobile/WordPress-iOS/pull/20023#issuecomment-1428129408) (**test case 1**) on `trunk` and I could reproduce it.

<details>
<summary>Bug repro recording on <code>trunk</code></summary>

https://user-images.githubusercontent.com/4588074/218727333-0adc01eb-e5c1-4f36-a5c5-d4aa64eeb16f.mov

---
</details>

That confirms it's not an issue introduced with this PR 🎉 
Given the [2nd bug](https://github.com/wordpress-mobile/WordPress-iOS/pull/20023#issuecomment-1428129408) (**test case 2**) is also not specific to this PR, from my side the PR is ready for merge 👍 

Thanks for your work 🥇 !

**Review by ovitrif — APPROVED** [review]
@salimbraksa  As mentioned in [this comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/20023#issuecomment-1429600492) the issues I encountered yesterday are not introduced in this PR, so I'm approving it for merging 🎉 

:shipit:

**Pull request merged**
