### PR TITLE
Issue/7664 media settings design

### LINKED ISSUE #7644: Incorrect text when activating a theme
The alert displayed after activating a theme with no author (for example uploaded themes) is displaying an incorrect text:

simulator screen shot aug 1 2017 20 09 10

I originally thought this issue was affecting WP.com themes too but it isn't, so we will tackle it after https://github.com/wordpress-mobile/WordPress-iOS/issues/7469 is done.

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #7644 and #7707. There weren't a lot of issues here, just changing the slider for video resolution to be a tableview.

To test:
1. Change video resolution
2. Verify that changing the resolution saves the `MediaSettings().maxVideoSettings` value

simulator screen shot aug 21 2017 7 57 00 pm

simulator screen shot aug 21 2017 7 56 57 pm

### CODE REVIEW

**Comment by kwonye** [comment]
We should add analytics... I'll create a new issue for that.

**Comment by SergioEstevao** [comment]
@kwonye on the settings view isn't there way to show what the current video setting? do we need to go one screen down to find the current setting?

**Comment by kwonye** [comment]
@SergioEstevao yea that's one of the "downsides" I guess, but I think overall it looks cleaner so it's a trade off we're making.

**Comment by kwonye** [comment]
https://github.com/wordpress-mobile/WordPress-iOS/issues/7707

Analytics issue created. Will try to add to this PR

**Comment by kwonye** [comment]
@SergioEstevao this also now addresses the analytics added. Will update original PR information.

**Comment by SergioEstevao** [comment]
@kwonye what about something like this:

screen shot 2017-08-22 at 10 19 02

If you want I can push the code with the changes for this.

And if we are removing the slider we probably should remove this classes from the code: `VideoSizingRow` and `VideoSizeModel`

**Comment by iamthomasbishop** [comment]
@kwonye – @SergioEstevao nailed exactly what I was going to recommend (show the selected label on the initial view, then let the user go down a level to select a different option. 👍

**Comment by kwonye** [comment]
@SergioEstevao oh awesome, thanks so much for pushing that code change (just FYI, please always push any suggestions you'd like to make with me. Worst-case we can just reverse the commit.

> And if we are removing the slider we probably should remove this classes from the code: VideoSizingRow and VideoSizeModel

Good call, removed. Ready for your approval (and @iamthomasbishop's)

**Comment by SergioEstevao** [comment]
@kwonye it looks the unit tests are failing because of some analytics changes, do you want to double check that?

**Comment by kwonye** [comment]
@SergioEstevao thanks for finding that. All good now, ready for a final pass please!

**Comment by kwonye** [comment]
tyty @SergioEstevao

**Pull request merged**
