### PR TITLE
Updates for clean compile with Xcode 6.3/Swift 1.2

### LINKED ISSUE #3456: Allow user to browse and use blog's media library
Currently the post and page composer is only able to use images and media from the phone's local media library. The user should also be able to browse the images hosted on their blog's media library.

Feature should include the ability to:

- [ ] Browse media from blog's online library
- [ ] Insert media into a page or post using the composer
- [ ] Make media available for composing while network is not available
- [ ] Use XMLRPC API

### LINKED ISSUE #3514: Fix the project for Xcode 6.3/Swift 1.2
Lets fix all the broken things for Xcode 6.3 so we can upgrade and keep moving forward. :smile:

### PR DESCRIPTION
**Pull request by alexcurylo**
Fixes #3514.

Problems mainly with changes to Swift downcasts and Objective-C interop with String v. NSString. Also, override declarations of properties to add protocol conformance, as found in ContentView classes, now will complain if lacking an @dynamic implementation.

### CODE REVIEW

**Comment by sendhil** [comment]
Fixes #3456 ?

**Comment by alexcurylo** [comment]
Heh, got my trial project etched in my brain. I mean #3514 of course.

**Comment by sendhil** [comment]
Ahhh makes sense ;). Thanks for tackling this @alexcurylo, we appreciate it. That being said @nheagy already has a branch up and ready to go and I told him we'd merge it in once we sorted out some things with Xcode 6.3....

**Comment by alexcurylo** [comment]
OK thx!

**Pull request closed without merging**
