### PR TITLE
Updated Sign In screen icons.

### PR DESCRIPTION
**Pull request by mattmiklic**
Updates two icons to vector PDFs that I missed in #4655. These are visually identical to the current assets:

- icon-wp
- onepassword-wp-button

Also updates `icon-alert` to a Gridicon and vector PDF.

Before:
img_1004

After:
img_1005

### CODE REVIEW

**Comment by mattmiklic** [comment]
Whoops, did not mean to close this.

**Comment by hypest** [comment]
Totally unrelated to the PR per se but i'll just put this here: The `Sorry, we can't log you in` copy felt too direct for me. Almost like "..we *won't* let you in".
Maybe something like "Sorry, we failed to log you in" or something would sound a bit more mild and would feel that *we* are on the user's side :)

**Comment by mattmiklic** [comment]
> Totally unrelated to the PR per se but i'll just put this here: The Sorry, we can't log you in copy felt too direct for me. Almost like "..we won't let you in".

You're right; it's also a bit strange to say "we" -- the user may be trying to log in to their own self-hosted site, so who is the "we" in that instance? This would make for a good issue, I think.

**Comment by hypest** [comment]
Done: https://github.com/wordpress-mobile/WordPress-iOS/issues/4717

**Comment by jleandroperez** [comment]
Tested on both iPad / iPhone devices.

Looking great @mattmiklic. Sir, i love your style!

:shipit:

**Pull request merged**
