### PR TITLE
Some iOS 13 fixes!

### PR DESCRIPTION
**Pull request by frosty**
Refs #12211. This PR fixes some issues from 12211:

- Changes the window color to black to improve the appearance of the new style modal windows.
- Navigation bars in splitview detail controllers should now have correct styling. After these fixes I was seeing an issue on the iPad simulator where the status bar is incorrectly being colored `.darkContent`, but the iPhone simulators and my iPhone device are fine. If you could test on an iPad that'd be great.
- Fixes a crash when the notifications alert on first launch was dismissed.
- Fixes a crash when accessing the Notifications screen.

**To test:**

- Build and run (fresh install) with Xcode 11, iOS 13 SDK
- [ ] Check the login screen (which is still an incorrect type of modal) shows black behind it at the top
- Log in
- [ ] Say Yes to the notifications popup. Once it's been dismissed, ensure there's not a crash.
- [ ] On an iPad device or simulator, check that the detail view doesn't have a grey navigation bar and the title and buttons look correct.
- [ ] Tap on the Notifications tab and ensure there isn't a crash.
- [ ] Please also check the app still builds and runs correctly on iOS 12

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by jkmassel** [comment]
I'm bumping this to 13.0 as part of the code freeze. If we'd like to release it as part of 13.0, just merge it into `release/13.0`, and DM me – I'll be happy to cut a new beta build!

**Comment by frosty** [comment]
Thanks @nheagy!

**Comment by frosty** [comment]
@nheagy Forgot to ask – did you test on your device? How was the status bar colouring on an actual iPad?

**Comment by nheagy** [comment]
@frosty I only tested on iPad simulator, not device, but I just upgraded my device to b5, I can test for you.

**Comment by nheagy** [comment]
@frosty after testing on my iPad with beta 5 I noticed no problems with the navigation bar, tho the status bar was black-on-blue.

Also, the notification crash DID happen, despite seemingly fixed on simulator. I may look into that more.

**Pull request merged**
