### PR TITLE
[Modal Layout Picker] Cache the response of fetching the layout picker

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes**  https://github.com/wordpress-mobile/gutenberg-mobile/issues/2456

## To test:
<details>
<summary><strong>To disable or enable the development version of Modal Layout Picker</strong></summary>

- Open the app from the build that allows FeatureFlags such as a PR build or a local development build
    - By default, the modal layout picker will be disabled.
    - From the site page:
        - Click on your Gravatar.
        - Click on App Settings.
        - Click on Debug.
        - Toggle "Gutenberg Modal Layout Picker" to enable or disable the picker
            
</details>

When enabled, the Layout Picker should show when creating a new page from My Site and from the Page list.

### Browse Modal Layout Picker
1. Open the Modal Layout Picker 
    - Optionally scroll through to load a few preview images. 
1. Exit the Modal Layout Picker
1. Take your device offline
1. Return to Modal Layout Picker
**Expect** to see picker loaded with the same results previously viewed. 

### Create Page
1. After performing the steps of `Browse Modal Layout Picker`
1. Select a layout
1. Select "Create Page"
**Expect** to see the editor load with the populated data from the template

### Preview Template 
1. After performing the steps of `Browse Modal Layout Picker`
1. Select a layout
1. Select "Preview"
**Expect** to see the preview load with the cached data

### Create Page From Preview
1. After performing the steps of `Preview Template `
1. Select "Create Page"
**Expect** to see the editor load with the populated data from the template

## Additional Context: 
- I originally thought additional caching would be needed for images but from my testing, the existing cache is sufficient to retain the thumbnail images so no additional work was done there.
- This is a continuation of the work done in [Modal Layout Picker Project](https://github.com/wordpress-mobile/gutenberg-mobile/issues?q=is%3Aissue+is%3Aopen+%5BModal+Layout+Picker%5D) and will be followed up by other tickets as part of [Modal Layout Picker Project](https://github.com/wordpress-mobile/gutenberg-mobile/issues?q=is%3Aissue+is%3Aopen+%5BModal+Layout+Picker%5D)

## PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by chipsnyder** [comment]
Hey @etoledom @guarani, Wanted to check in and see if one of you might be able to help review this PR for me? It's one of the last ones I need to wrap up on Modal Layout Picker so would love to get this in soon. It also has some Core Data changes and would love to have this in to avoid any unwanted merge conflicts 😅 

If you're both busy though no worries I can ping someone else :)

**Comment by etoledom** [comment]
@chipsnyder - I'll check it out today. 
Not sure if I'll be able to finish the review today though, but by Monday for sure I'll have something to say :)

**Comment by guarani** [comment]
- [x] Browse Modal Layout Picker
- ⚠️ Create Page
    From the instructions, I assume this test is done while the device is still offline. While it works for the most part, the template I'd chosen has background images which didn't appear to have been cached. Maybe this is OK, can you please confirm?
- ⚠️ Preview Template
    I got a crash after opening clicking the FAB and creating a new page (I was about to test the "Preview Template" test after having completing the previous two tests — I can DM you the logs):
    <details>
    <summary>See screen recording</summary>
    Screen recording showing crash when opening page
    </details>
    The next time I tried this I didn't get a crash.
- [x] Create Page From Preview

**Review by guarani — COMMENTED** [review]
- [x] Browse Modal Layout Picker

- [ ] Create Page ⚠️
    From the instructions, I assume this test is done while the device is still offline. While it works for the most part, the template I'd chosen has background images which didn't appear to have been cached. Maybe this is OK, can you please confirm?

- [ ] Preview Template ⚠️
    I got a crash after opening clicking the FAB and creating a new page (I was about to test the "Preview Template" test after having completing the previous two tests — I can DM you the logs):
    <details>
    <summary>See screen recording</summary>
    Screen recording showing crash when opening page
    </details>
    The next time I tried this I didn't get a crash.

- [x] Create Page From Preview

**Comment by chipsnyder** [comment]
> Create Page ⚠️
From the instructions, I assume this test is done while the device is still offline. While it works for the most part, the template I'd chosen has background images which didn't appear to have been cached. Maybe this is OK, can you please confirm?

Yeah, I think this would be expected that those images aren't populated when offline. cc @iamthomasbishop just to get another opinion. I think for creating the new content not having those images immediately available is fine. For my use case, they were available if I moved the device back online and opened the post the images were there. So as long as that's the same for you as well then I think we're good to go.


> I got a crash after opening clicking the FAB and creating a new page (I was about to test the "Preview Template" test after having completing the previous two tests — I can DM you the logs):

I'll reach out to you now to get those longs. I would be interested in taking a look.

**Comment by guarani** [comment]
> For my use case, they were available if I moved the device back online and opened the post the images were there. So as long as that's the same for you as well then I think we're good to go.

Yep, it worked after bringing the device back online and opening the editor again.

**Review by guarani — APPROVED** [review]
After not being able to reproduce the crash above, I think we can write it off for now. 
Codewise it looks clean! 💯

**Comment by chipsnyder** [comment]
Since a release branch will be cut tomorrow I'll plan to merge this after that is cut.

Merging this now that the 15.9 code freeze branch has been cut

**Pull request merged**
