### PR TITLE
Fixing analytics for creating a new blog

### LINKED ISSUE #5785: Fix analytics for when a user creates a new site
### Expected behavior
Creating a new site triggers a "created new blog" event

### Actual behavior
Creating a new site triggers a "created new account" event

### Steps to reproduce the behavior
Create a new a blog from the "add a site" prompt.

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #5785 

Needs review: @astralbodies

### CODE REVIEW

**Comment by astralbodies** [comment]
For completeness lets also fire off this event when a site is created alongside a new account.

**Comment by kwonye** [comment]
@astralbodies done! Now time to do it on Android.

**Comment by kwonye** [comment]
@astralbodies done! Now time to do it on Android.

**Comment by astralbodies** [comment]
:shipit:

**Comment by sendhil** [comment]
So this busted our create account tracking...

**Comment by sendhil** [comment]
@astralbodies @kwonye :point_up:

**Comment by sendhil** [comment]
I'm an idiot, ignore the above comment. This was to fix a double count issue and when I searched for the create account event I forgot to search for the enum used in Swift.

**Pull request merged**
