### PR TITLE
Fix/8575 rtl layout

### LINKED ISSUE #8575: Proper Rirgt-to-Left layout support.
### Expected behavior
Support RTL layout properly in all sections of the app.

### Actual behavior
Many sections have some issues supporting RTL layout. Most of these problems are text alignment that should be quick/easy to fix.

The sections with problems I have found out so far are:

- [ ] Many text alignment of labels in the **Stats** section. PR #8576 
- [ ] **Reader** 'Manage' cell.
- [ ] **Contact Us** textfield placeholder.
- [ ] Warning text and **Contact Support** button placement on the 'Delete site' section.
- [ ] **Login** view element alignments.
- [ ] **Enter password** textfield alignment.
- [ ] **Create account** textfields alignment.
- [x] **Aztec Editor** formatter bar. [PR](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/904)

### Building with Xcode:

1. Edit Scheme
2. Options
3. Application Language
4. Arabic (or Right-to-Left Pseudolanguage)
5. Run the app
6. Create a post and check the bar

### On device:

1. Set the system language to Arabic
2. Run the app
4. Create a post and check the bar

### PR DESCRIPTION
**Pull request by etoledom**
Fixes #8575 

This first commit fixes the RTL layout of the **Stats** section.
It was completely done in IB so there is no code involved.

artboard

To test:

### Building with Xcode:

1. Edit Scheme
2. Options
3. Application Language
4. Arabic (or Right-to-Left Pseudolanguage)
5. Run the app
6. Create a post and check the bar

### On device:

1. Set the system language to Arabic
2. Run the app
4. Create a post and check the bar

### CODE REVIEW

**Comment by etoledom** [comment]
Fix crash when opening the stats area.

 The crash reason was: `attempt to delete section 1, but there are only 0 sections before the update` (StatsTableViewController:443) when trying to reload a specific section with animation.

It was solved by checking if the cell exists before reloading it.

This crash started happening after upgrading the `SiteStats.storyboard` to the latest Xcode version.

**Comment by etoledom** [comment]
@frosty thanks for the review!

Interesting; I see it displaying correctly on my device (iPhone 7, iOS 11) and in the iOS 10 simulator.



I'm pretty sure I'm sitting in the same commit.

Can you please check if you see the same issue in the Insight section? (it uses a different cell)
It also would be good to know how are you testing it to see if I can reproduce it.

**Comment by astralbodies** [comment]
Taking a look now!

**Comment by astralbodies** [comment]
There's one big downside to using the Storyboard in Stats and I regret using it because of this ... any time you make changes to the cells you have to make sure to copy and paste that cell into each of the tables that use it. Delete the old version and paste in the copy in that table. It's cumbersome but you'll see problems like this because the cell wasn't updated in the Insights table:

simulator screen shot - iphone 8 plus - 2018-02-09 at 09 30 18

**Comment by etoledom** [comment]
Right! The follower's table didn't have those changes yet. Thanks for pointing that out :)

I will push a new commit hoping it solves the remaining issues!

**Comment by etoledom** [comment]
@astralbodies The 'Followers' list should be fixed now. I also inspected all the scenes to make sure I didn't miss any other cell. 👍

**Pull request merged**
