### PR TITLE
[Jetpack plugin install prompt] Complete UI and tracking for installation prompt

### PR DESCRIPTION
**Pull request by staskus**
## Description

This pull request completes Phase 1 of Jetpack plugin install prompt project https://github.com/wordpress-mobile/WordPress-iOS/issues/19213

- Updating UI according to the new requirements
- Adding tracking

### Case 1:
1. Fresh install app and log in to self-hosted site without Jetpack
2. Install prompt appears
3. There's a title and description informing about Jetpack features
4. "Learn more" button opens the web site
5. "Install Jetpack" button opens installation flow
6.  "Continue without Jetpack" dismisses

### Case 2 - Tracking
1. Fresh install app and log in to self-hosted site without Jetpack
2. Install prompt appears
3. `Tracked: jetpack_install_prompt_shown <site_type: blog>` appears in console
4. Tap "Learn more"
5. `Tracked: jetpack_install_prompt_learn_more_tapped <site_type: blog>` appears in console
6. Tap "Install"
7. `Tracked: jetpack_install_prompt_install_tapped <site_type: blog>` appears in console
8. Come back and tap "Continue without Jetpack"
9. `Tracked: jetpack_install_prompt_dismiss_tapped <site_type: blog>` appears in console

## Regression Notes

1. Potential unintended areas of impact

Broken actions or accessibility

2. What I did to test those areas of impact (or what existing automated tests I relied on)

- Tested actions manually
- Tested accessibility using accessibility inspector, different screen sizes and different dynamic text size

8. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

#### Tracking

tracked events

### CODE REVIEW

**Review by sla8c — CHANGES_REQUESTED** [review]
@staskus I took a look and it's looking good so far.  One noticeable issue - this change doesn't work for Jetpack + Dark mode.  See screenshot
image

**Comment by staskus** [comment]
@sla8c 

Thank you for the review 🤝, good catch!

I made a change to support dark mode. 

https://user-images.githubusercontent.com/4062343/191737893-3f1cccd7-d337-474f-9a09-4f96faea136b.mp4

**Review by guarani — APPROVED** [review]
Nice work adapting this to the new design and adding tracks ✨

The code looks good and I run through the testing instructions and everything worked well. I also tested dark mode which @sla8c flagged earlier and it's fixed.

The only comment was on this Figma board: 7Xi0UHNwokIWen0cczwHti-fi-0%3A1 (I can't link to the specific comment since the link shorter doesn't seem to support Figma comments yet, see 152-gh-Automattic/tampermonkey-highlighter).
This is not a blocker since this PR is not being merged to `trunk`, but I was reminded of it on this PR and have pinged folks in that Figma comment thread for feedback.

**Comment by staskus** [comment]
> Nice work adapting this to the new design and adding tracks ✨
> 
> The code looks good and I run through the testing instructions and everything worked well. I also tested dark mode which @sla8c flagged earlier and it's fixed.
> 
> The only comment was on this Figma board: [7Xi0UHNwokIWen0cczwHti-fi-0%3A1](https://href.li/?https://www.figma.com/file/7Xi0UHNwokIWen0cczwHti/?node-id=0%3A1) (I can't link to the specific comment since the link shorter doesn't seem to support Figma comments yet, see 152-gh-Automattic/tampermonkey-highlighter). This is not a blocker since this PR is not being merged to `trunk`, but I was reminded of it on this PR and have pinged folks in that Figma comment thread for feedback.

Thanks 👍 Yes, I saw the comment. I agree that for now it's not worth waiting and texts could be changed later in case the feature is released.

**Pull request merged**
