### PR TITLE
Gutenberg: Update the tracker for unsupported blocks

### PR DESCRIPTION
**Pull request by etoledom**
This PR updates the interface implementation of the method that is used to keep track of unsupported blocks in the current post/page.

Prior to this PR, the JS side was sending a simple flag to signal the presence of unsupported blocks in the post. With the improved version of the JS side tracker, it will send the full list of unsupported block names. For now we're just checking if the list is empty or not, and then bump the same Analytics has_unsupported_blocks as before.

Ref:
WPAndroid PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10170
Gutenberg Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1199
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/16434

To test:
- Ensure that you have the block editor switch ON on Me -> App Settings
- Create a new post with a couple of paragraph and save it (as draft or publish)
- Open the saved post again
  - Check that the `editor_session_start` track event is registered with `has_unsupported_blocks: 0` property:

```
🔵 Tracked: editor_session_start <blog_type: wpcom, content_type: gutenberg, editor: gutenberg, has_unsupported_blocks: 0, post_type: post, session_id: A5877C9D-646A-4DBC-93B9-23778CAFDA84>
```
- Open the same post on web and add a few unsupported block (i.e: Gallery) and save.
- Refresh the post lists on mobile and open the edited post.
  - Check that the `editor_session_start` track event is registered with `has_unsupported_blocks: 1` property:
```
🔵 Tracked: editor_session_start <blog_type: wpcom, content_type: gutenberg, editor: gutenberg, has_unsupported_blocks: 1, post_type: post, session_id: 47A54BF2-A70F-466D-A76F-BBD32545AF71>
```

Note that this is a Bool value, so even if there are many unsupported blocks, `has_unsupported_blocks: 1` is expected.

### CODE REVIEW

**Comment by hypest** [comment]
As far as I understand, this PR will merge any recent gutenberg-mobile developments directly into the WPiOS develop, effectively bypassing the "editor code freeze" process. I wonder if we should instead target an "editor release" branch instead of develop directly.

**Comment by etoledom** [comment]
> As far as I understand, this PR will merge any recent gutenberg-mobile developments directly into the WPiOS develop, effectively bypassing the "editor code freeze" process.

@hypest - I'm not sure I follow? 🤔

The gutenberg-mobile v1.8 is ready on the `release/12.8` release branch for WPiOS.
And as far as I understand, gutenberg-mobile v1.9 code-freeze is not ready yet, and the changes coming in this PR are part of it?

In general, every time we need a JS Bundle update to solve errors on WPiOS we do so. It's just not a common thing.

The next editor code-freeze (v1.9) will bring an updated JS Bundle with the new gutenberg and gutenberg-mobile commits, plus a proper tag. But the update in this PR is needed to test the gutenberg bridge changes and test new gutenberg features until the code freeze is finished.

**Comment by hypest** [comment]
> And as far as I understand, gutenberg-mobile v1.9 code-freeze is not ready yet, and the changes coming in this PR are part of it?

That's the thing, the v1.9 is not cut yet and if we merge this PR it will be equivalent of directly merging all recent gutenberg-mobile changes into WPiOS without the "few days of testing" process of the editor code-freeze process.

> But the update in this PR is needed to test the gutenberg bridge changes and test new gutenberg features until the code freeze is finished.

I understand the need for this PR, no problem there. But, along with the bridge changes, every other recent gutenberg-mobile change will get merged too, right?

**Comment by etoledom** [comment]
> if we merge this PR it will be equivalent of directly merging all recent gutenberg-mobile changes into WPiOS without the "few days of testing" process of the editor code-freeze process.

Ok, I see the pain point!

I'll create a gutenberg release branch to merge this PR and we can use that branch for the code-freeze as well 👍

**Comment by etoledom** [comment]
Thank you for a fast review @frosty !

**Pull request merged**
