### PR TITLE
Reader: Ensures changes saved in the detail show in the list.

### LINKED ISSUE #4403: Reader: Likes made on full post view don't appear on return to list view
When you like a post on the full post view, that Like doesn't appear on the Reader's list view until you refresh the page. That can make it seem like the Like wasn't captured. I noticed this while testing, and another tester reported the same confusion.

Steps:
1. Open the Reader tab
2. Tap to view a full post
3. Tap the star at the bottom of the post to like it
4. Tap the back button to return to the Reader list view
Result: The like doesn't appear on the post's card, unless you pull down to refresh the list.

Screenshot of the like showing in the full post view:

Screenshot after tapping back to the list view, post doesn't show that I've liked it:

Tested on iPhone 6, iOS 9.1, WPiOS beta 5.7.0.20151102

### PR DESCRIPTION
**Pull request by aerych**
Closes #4403. 

To test, 
- Follow the steps outlined in the issue and confirm that likes made in the detail are reflected in the list. 
- While on the list, pull to refresh and confirm the refresh happens normally, no jank, or glitching. 

Needs Review: @alexcurylo

### CODE REVIEW

**Comment by alexcurylo** [comment]
Fix works as described, but it looks to me like that `NSManagedObjectContextDidSaveNotification` observer isn't getting removed anywhere. Am I overlooking something?

**Comment by aerych** [comment]
> Am I overlooking something

Doh!  No I spaced out and forgot to add a `deinit`. Good catch, fix on the way!

**Comment by aerych** [comment]
@alexcurylo Ready for round two!

**Comment by alexcurylo** [comment]
Looks good! :shipit:

**Comment by aerych** [comment]
Thanks Alex!

**Pull request merged**
