### PR TITLE
Integrate new media picker

### PR DESCRIPTION
**Pull request by SergioEstevao**
Replaces the CTAssetPickerController for the new MediaPicker-iOS
 
cc @bummytime @astralbodies, can you guys review and please have a good go on it on several devices with different media libraries sizes. Thanks in advance.

### CODE REVIEW

**Comment by bummytime** [comment]
Update from an offline Slack conversation with @SergioEstevao: looks like there is a small issue with unselecting images and videos that are captured within the picker.

**Comment by astralbodies** [comment]
I have a library of about 15 items on my iOS 7 device. I uploaded all 15 in a new post and while it was uploading, I uploaded the same 15 again. I did this about three times total and then suddenly I got an error `Failed to export media and message Cannot Save`. Once this happened canceling the upload didn't actually do anything and it was stuck on Uploading. Not sure if this is an iOS 7 issue specifically.

**Comment by bummytime** [comment]
I tested @astralbodies's scenario above (uploading the same set of images 3+ times)  on iOS 8.3 on my 6+. I did indeed see many of the same symptoms...laggy input, stuck on "uploading" even after cancelled, etc. However I did not ever see the `Failed to export media and message Cannot Save` error.

@SergioEstevao perhaps we need to put limit on how much the user can upload at one time?

**Comment by SergioEstevao** [comment]
@bummytime @astralbodies I can put a limit on the maximum simultaneous uploads. But I think this a separate issue from the new picker it should be happen before with the old picker.

**Comment by bummytime** [comment]
@SergioEstevao Fair enough, we can log it separately. @astralbodies beyond the multiple upload fail, were there any other issues you uncovered on iOS 7?

**Comment by astralbodies** [comment]
I didn't do a full suite of tests by any means - but this PR seemed okay otherwise with iOS 7.

**Comment by bummytime** [comment]
:shipit:

**Pull request merged**
