### PR TITLE
Notifications: 64 bit ID field

### LINKED ISSUE #4456: Notifications: Nuke id field
We've introduced the `Notification.id` field, initially, to silence a Simperium Warning (#2375).

Problem: the data type is set to Integer 32. In the past week we've exceeded the `2^31` range, and thus, this field is overflowing.

This is causing side effects to users that use both, iOS and Android, simultaneously. We need to remove the `id` field, and silence the warning in another way (perhaps a library patch, to be defined).

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:
This PR recreates #4481, which was merged against Release 5.7.1.

We had to revert #4481 (Ref. #4497) because Beta 5.8 was already shipped, and merging 5.7.1 back into 5.8 would log off (ALL) of our beta testers.

#### Scenario 1: Upgrade from 5.8
1. Install WPiOS 5.8
2. Log into your account
3. Install, on top of it, this branch
4. Make sure you don't get logged out, and the `Notifications` are still accessible

#### Scenario 2: Unit Test
1. Run `CoreDataMigrationTests.testMigrate40to41`
2. Make sure the unit test passes correctly

Needs Review: @sendhil
cc @astralbodies + @aerych (sorry guys, we had to revert the previous PR, and resubmit against 5.8)

Closes #4456

### CODE REVIEW

**Comment by koke** [comment]
I see no entry on `MIGRATIONS.md`

**Comment by jleandroperez** [comment]
Nice catch @koke! added, thanks!

**Comment by astralbodies** [comment]
:shipit:

**Comment by jleandroperez** [comment]
Thanks for the review Aaron!

**Pull request merged**
