### PR TITLE
Post list revamp

### LINKED ISSUE #11646: Post List Revamp Master Issue
This is a master issue to track the post list revamp on iOS.

# Changes

* View toggle to switch between card/list view
* Updated card designs

# Blueprint

post_list_blueprint

# Subtasks

- [x] Replace the "More" behavior to show options in an Action Sheet #11661
- [x] Update card designs and do not display author name when "Me" is selected https://github.com/wordpress-mobile/WordPress-iOS/pull/11705
- [x] Display "skeleton post card" when loading posts #11789
- [x] Adapt cards so it can be displayed in a compact way #11816
- [x] Change search to always happen in a list view #11830
- [x] Enable the list view option #11816
- [x] Improvements and polishes #11974
- [ ] Merge with `develop` and integrate

### PR DESCRIPTION
**Pull request by nheagy**
Fixes #11646

This PR will merge in all changes for the post list revamp 🎉

To test:
- Because this is the result of several previous PRs, you don't have to review the entire PR (that's the hope of breaking it up!) However, as a reviewer, you're welcome to comment on anything 😀 
- Ensure that the post list matches the mockups (see #11646)
- Also ensure that any features added to the post list recently (last 1-2 months) are still present, due to this being a long-lived feature branch 😀 

**Note:** This doesn't have the new colors, as they landed out-of-order. We should fix those in a separate PR.

Update release notes:
- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by yaelirub** [comment]
Hey @leandroalonso , @nheagy  while testing this I noticed that the 'expand cards' icon at the top right   is not visible, but is somewhat tappable (though hard to tap)
posts_list

**Comment by leandroalonso** [comment]
@yaelirub this definitely is not the expected experience. I will fix it — btw, the same problem is happening with the pages list, the fix will apply to both pages and posts.

**Comment by nheagy** [comment]
@yaelirub I've updated the branch to fix the missing icons, and the failing test. Ready for another look!

**Comment by nheagy** [comment]
Thanks @yaelirub!

**Comment by yaelirub** [comment]
@leandroalonso , @nheagy, I created this issue. The only one I could consistently reproduce. 
https://github.com/wordpress-mobile/WordPress-iOS/issues/12113

**Pull request merged**
