### PR TITLE
Aztec can now publish posts

### LINKED ISSUE #6553: Aztec: Wire up publishing a post
The Aztec editor needs to publish. Wire up it and also integrate with the state machine.

### PR DESCRIPTION
**Pull request by astralbodies**
Closes #6553 

# Summary
This PR wires up the publishing actions to the services to perform the actual actions. There are several things that are **TODOs for another PR**:
1. Removal of failed media from the post upon publish (after asking). #6635
2. Taking into account if a user can publish to the site or not (to implement "Submit for Review"). #6636
3. Dismissing of window is wonky - post-post is getting dismissed when it shouldn't be. #6637
4. Switching to post lists after publishing, if appropriate. (I think this is being handled by the editpost VC that handles post-post but I could be wrong.) #6637

# To test:
Make sure to test scenarios that include the following:
* Editing an existing post, creating a new post.
* Use the secondary publish button (publish now or save draft) from the action controller.
* Attempt to publish while media is uploading.
* Anything else you can think of to break crap.
* Test editing a New Post > Switching the Site > Saving as draft. Verify that the app doesn't get locked.

Needs review: @diegoreymendez, @jleandroperez, @SergioEstevao

### CODE REVIEW

**Comment by SergioEstevao** [comment]
When using the iPad on multitask mode the publish indicator is out of position.
screen shot 2017-02-10 at 10 23 52

**Comment by SergioEstevao** [comment]
Writing a post with an image, blocks/disables the Publish/Save button.

How to reproduce:

- Create one post
- Write a title
- On the main content just add an image
- See the Publish button getting disabled

screen shot 2017-02-10 at 10 33 05

**Comment by astralbodies** [comment]
@SergioEstevao 

> When using the iPad on multitask mode the publish indicator is out of position.
I'm using the same code for displaying the HUD in Aztec as we did in the hybrid editor. I'll open an issue to address later. #6651

> Writing a post with an image, blocks/disables the Publish/Save button.
Fixed! I moved the didFinish delegate call into `refreshMediaProgress()`.

> The app is crashing on the iPad when you you create a new post or edit a post do some changes and then press the X button.
I'll open another issue for this as I think I saw this happening with the hybrid editor too. #6652

**Comment by astralbodies** [comment]
Believe I resolved the iPad crash #6652 & the dismissal wonk #6637.

**Comment by jleandroperez** [comment]
@astralbodies sir, hope you don't mind! fixed a bug that was blocking the UI after saving a draft. Turns out, *EditPostViewController* (AKA the fellow that handles the PostPost screen) was retaining a reference to a `Post` object that was no longer valid.

(This is because, in the editors, whenever you switch a blog, we create a new Post entity / new revision).

Testing steps are: 

```
1. Edit a new post in Aztec
2. Switch the blog
3. Save as a draft

As a result, the screen *was getting blocked
```

I've also updated the main issue's description, with another (brief) test case.
Thanks!!

**Comment by astralbodies** [comment]
Opened up some bugs for issues discovered not directly associated with this PR or that shouldn't hold up this one getting merged. @jleandroperez and I tested this morning and it's good enough to get merged but I think significant testing is needed overall beyond just publishing.

**Pull request merged**
