### PR TITLE
Integrate gutenberg-mobile release 1.48.1

### PR DESCRIPTION
**Pull request by fluiddot**
## Description
This PR incorporates the 1.48.1 release of gutenberg-mobile.  
For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3237

Release Submission Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by jd-alexander — COMMENTED** [review]
LGTM 🚢 All expected behavior verified with smoke testing. Awaiting GB-mobile/GB CI confirmation before merge.

**Comment by fluiddot** [comment]
> Awaiting GB-mobile/GB CI confirmation before merge.

I've just [updated the Gutenberg reference](https://github.com/wordpress-mobile/WordPress-iOS/pull/16046/commits/0bf94bb46efda4db0b369efba73766ba5799dbe5), now it points to the `v1.48.1` tag so it's ready to be merged 🎊 .

**Comment by jd-alexander** [comment]
> > Awaiting GB-mobile/GB CI confirmation before merge.
> 
> I've just [updated the Gutenberg reference](https://github.com/wordpress-mobile/WordPress-iOS/pull/16046/commits/0bf94bb46efda4db0b369efba73766ba5799dbe5), now it points to the `v1.48.1` tag so it's ready to be merged 🎊 .

Thanks! Merging once CI passes.

**Review by jd-alexander — APPROVED** [review]
The tag has been updated with `v1.48.1` and CI passes. LGTM 🚢

**Pull request merged**
