### PR TITLE
Login with website address: Improve support for dynamic type

### PR DESCRIPTION
**Pull request by ctarda**
Implements part of #7640 

In this PR, improved support for Dynamic type when logging when website address:

Login with website address
Login with website address

To test:

1. Log out
2. Tap Log In in the first screen
3. Tap Log in by entering your site address
Change the text size (Settings > Display and brightness > Text Size)
As an alternative to 3, I added Text Size to my Control Centre (Settings > Control Centre > Customise Controls)

### CODE REVIEW

**Comment by etoledom** [comment]
It gets more complicated when showing the keyboard 😱

**Comment by nheagy** [comment]
What do you think about making all the blue buttons at the bottom of the login screens a UIButton subclass? Possibly even be the same one used for the text buttons on `LoginEmailViewController`.

**Comment by ctarda** [comment]
I just pushed another update. Following @nheagy 's suggestion, I made the blue button at the bottom a UIButton subclass that takes care of its own resizing.

**Comment by ctarda** [comment]
Closing. This is is included in PR #8908

**Pull request closed without merging**
