### PR TITLE
UL&S: Sign up: send magic link

### PR DESCRIPTION
**Pull request by mindgraffiti**
Ref. #14009 
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/355

This PR ports the "send magic link" code to the "Send Link by Email" button. Note that we are bypassing the old `SignupEmailViewController`, so this PR will crash on purpose if an invalid email address is used.

### To test:
1. Have the Auth PR checked out
2. In the Auth pod, modify the email address [found here](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/355/files#diff-70be8cd44c2d3e32bd0e29c2c874e981R26). You can use an email address with a plus modifier if you don't want to create a brand new email account (for example, `unknownuser+signuptesting@example.com`)
2. Set the podfile to local development: `pod 'WordPressAuthenticator', :path => '../WordPressAuthenticator-iOS'`
1. Enable the `unifiedSignup` feature flag
3. `rake dependencies`
4. Build and run
5. Sign up with WordPress.com > Sign up with Email. (Your entered email address should display.)
6. Tap the "Send Link by Email" button. Verify that you are navigated to an old "Magic Link sent!" VC. Verify you received a Magic Link email.

**iPhone 11 Pro, iOS 13.6 - Needs design review**
| Dark mode | Light mode |
| --- | --- |
| <a href="https://user-images.githubusercontent.com/1062444/89213260-6e3e4800-d58a-11ea-9e32-f67446158f29.png"></a> | <a href="https://user-images.githubusercontent.com/1062444/89213294-7a2a0a00-d58a-11ea-839c-a4ae62e6ca52.png"></a> |

**Example of navigation to the old UI**
<a href="https://user-images.githubusercontent.com/1062444/89212653-721d9a80-d589-11ea-972a-0524ea8e8db8.png"></a>

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mattmiklic — CHANGES_REQUESTED** [review]
Things generally look good here. There are a couple of things that would be nice to fix up but not crucial. Here's a zoomed-in side-by-side comparison of the mockup (left) and your screenshot (right):

- the `gridicons-user-circle` icon is 48pt in the mockup, but smaller in the screenshot. Note that the left edge of the circle itself should align with the "We'll email you…" text, which means the icon (which includes some whitespace) needs to be offset about 3pt to the left.
- There's about 44pt of space between the email address and the "We'll email you…" text in the mockup; only about 29pt in the screenshot. This doesn't have to be exactly 44pt but it would be nice to get it a little bit closer to the mockup.

Screen Shot 2020-08-03 at 2 20 14 PM

**Comment by mindgraffiti** [comment]
@mattmiklic thanks for the numbers, it helps a lot. How's this one look?

<a href="https://user-images.githubusercontent.com/1062444/89229579-49a49900-d5a7-11ea-828d-0afb23a30792.png"></a>

**Review by ScoutHarris — CHANGES_REQUESTED** [review]
Everything works as described. Just a request for the gravatar size.

(Sorry I put this on the wrong PR, so it's duplicated on the Auth PR. 🤦 )

**Review by diegoreymendez — APPROVED** [review]
This is working well on my end.

**Review by mattmiklic — APPROVED** [review]
This looks great now! 👍

**Review by ScoutHarris — APPROVED** [review]

**Comment by mindgraffiti** [comment]
Thank you for the reviews Matt, Diego, and Stephenie!

**Pull request merged**
