### PR TITLE
Merge release/12.6 into master

### PR DESCRIPTION
**Pull request by jkmassel**
Fixes #

To test:

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by jkmassel** [comment]
@jtreanor – is it odd that UI tests aren't running?

**Comment by jkmassel** [comment]
This now includes changes from `12.6.1`

**Comment by jtreanor** [comment]
@jkmassel Nope. UI tests don't run on every PR (yet). Did you make that status check required in the Github branch settings? In any case I have removed it now.

**Comment by jkmassel** [comment]
Not that I remember, but I can't say for certain that I didn't! 😅 

I'll check that next time first, thanks!

**Pull request merged**
