### PR TITLE
Merge finalized release 18.3 into `develop`

### PR DESCRIPTION
**Pull request by mokagio**
Notice the minor tweak to the _English US only_ release notes from #17247.

### CODE REVIEW

**Review by mokagio — COMMENTED** [review]
- [x] Fastlane  localized `release_notes.txt` updates
- [x] Localized `.strings` updates
- [x] Build number bump in version `.xcconfig` file
- [x] Plus diffs from the PRs that landed on the release branch since the last beta

**Comment by AliSoftware** [comment]
Warning: seems there is a very last minute fix to the release branch ~that was done~ coming soon (see build-and-ship in Slack)

> [From @startuptester]: @mokagio  there’s a fix coming to the WPiOS 18.3 frozen branch today from @diego. Sorry for the late fix, it’s my fault.

**Comment by loremattei** [comment]
Ah! You are great @AliSoftware! I came here to give @mokagio the heads up, but I see you already did it 🙌

**Comment by mokagio** [comment]
Thanks folks 😄

**Comment by mokagio** [comment]
@AliSoftware @loremattei Just a note to say that I have submitted a new build, 18.3.0.5, for review to include https://github.com/wordpress-mobile/WordPress-iOS/pull/17252 🚂

**Comment by mokagio** [comment]
As I tell my children "it's past your bedtime". I won't be waiting CI's result, but it was all green in [`2ce414a` (#17251)](https://github.com/wordpress-mobile/WordPress-iOS/pull/17251/commits/2ce414a616c3c3491ba2f2733f8168dc1d696a06) so we should be good.

**Comment by AliSoftware** [comment]
I just restarted the `unit-tests` job on Buildkite (it was failing with a "broken pipe" error, which is usually transient).

**Review by jkmassel — APPROVED** [review]

**Pull request merged**
