### PR TITLE
Post published while offline will now be published once back online.

### LINKED ISSUE #11420: Offline Support: Post / Page Published as Draft
## Description:

While creating a new post / page offline and publishing it, the post / page is queued but shows up as a draft. After successfully uploading it, it still stays as a draft.

### Steps To Reproduce

1. Go offline
2. Create a Post
3. Click on _Publish_ button in the Editor and publish 
4. When on the Post List, go online. 
5. Click on the post's _Retry_ button. 

## Decision
As the user intended to publish the post, retrying should also publish the post
To clarify, we should amend the error state to mention posting. Error message should say "Could not upload media. Post not published." Then its clear that retry relates to posting, not just media.
To make this work we need to differentiate the error state in publishing/saving/scheduling scenarios. 

1. User publishes and media upload error (use case in this issue)
Error Message: "Could not upload media. Post not published."
Action and behavior: Retry. Retrying publishes the post if media uploads successfully

2. User schedules and media upload error (scheduling rather than publishing)
Error Message: "Could not upload media. Post not scheduled."
Action and behavior: Retry. Retrying schedules the post if media uploads successfully

3. User saves and media upload error (user did not intend to publish)
Error Message: "Could not upload media."
Action and behavior: Retry. Retrying only retries uploading the media as the user has not changed the post state

## Related Issues

https://github.com/wordpress-mobile/WordPress-Android/issues/9933

### PR DESCRIPTION
**Pull request by diegoreymendez**
Title has it.

Fixes #11420 

## Testing:

1. Create a post while offline.
2. Tap "Publish".

Expected: Once you are back online make sure the post is published.

## Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by jklausa** [comment]
>IMPORTANT: let's wait to merge this until we decide what to do with offline publishing.

Is this referring to the call that @maxme is setting up or something else?

**Comment by diegoreymendez** [comment]
> Is this referring to the call that @maxme is setting up or something else?

Yes... I'll move this PR to draft and remove the reviewers for now.

**Comment by diegoreymendez** [comment]
Actually it seems I can't move it to draft, but I can add the "Not ready for review flag" at least.

**Comment by diegoreymendez** [comment]
This is ready for review @jklausa and @shiki

**Comment by shiki** [comment]
@diegoreymendez @osullivanchris This works! The post is automatically uploaded when online. 

I would like to confirm the flow here:

untitled@2x(1)

Like what I mentioned in https://github.com/wordpress-mobile/WordPress-iOS/pull/12178#issuecomment-514307641, the post does not stay in Drafts but is in the Published list. That contradicts the design described in #11425. Unlike https://github.com/wordpress-mobile/WordPress-iOS/pull/12178 however, I think this is an okay user experience and incrementally improves things as they are now. We can fix the Drafts list placement in a later PR. 

If you both agree, I can review this some more.

**Comment by diegoreymendez** [comment]
@shiki - I think it'd be best if we merged this PR into https://github.com/wordpress-mobile/WordPress-iOS/pull/12178.

This was we could test offline publishing as a full feature.

If you agree, I'll go ahead and merge this PR into the other one.

**Comment by shiki** [comment]
@diegoreymendez To be clear, do you mean:

1. Merge this branch into #12178 **without reviewing**.
2. Review #12178 instead.

**Comment by diegoreymendez** [comment]
@shiki - That's correct.  I don't think reviewing this individually makes much sense, and I feel it'd be best if this is reviewed as part of the larger PR so we can add relevant safeguards and checks.

**Comment by shiki** [comment]
Sounds good 👍

**Comment by diegoreymendez** [comment]
Closing this for now.

**Pull request closed without merging**
