### PR TITLE
Simperium Sunset Mark IV: Wiring Service Layer

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR Wires the new **NotificationsSyncService** in **NotificationsViewController**. We're adding three capabilities:

- Sync Newest Notifications
- Update Last Seen Time (reflected in the APN Badge Count)
- Mark Notifications as Read

`PushNotificationManager` was updated, so that it fires a `NotificationSyncService` sync event when needed. Push Notification handling has been also patched up, so that the associated Note gets displayed, whenever the user interacts with an APN event.

Ref #6086

### Scenario A: Upgrade
1. Install **develop** in your phone, and log into a dotcom account
2. Install this branch on top

Verify that you don't get logged off as soon as you run the app

### Scenario B: Account Change Sync'ing 
1. Fresh install the app
2. Wait for a second, and tap the Notifications Tab

Verify that Notification List is already populated, and the user doesn't get a blank screen (AKA the notifications should have sync'ed long ago, and not just on viewWillAppear event).

### Scenario C: Logout
1. Log into a dotcom account
2. Verify that the notifications do show up in the Notes tab
3. Logout, and log into a self hosted site
4. Verify that the Notifications tab is empty

### Scenario D: Badge
1. Launch the Push Notifications Server for develop build. (DM me if needed please!)
2. Log into the app, and send it to background (OR kill it)
3. Receive a Push Notification, and verify that the badge count is 1
4 Receive another Push Notification, and verify that the badge count is 2
5. Open the Notifications Tab, and send the app back to background
6. Verify that the Badge Count is not visible
7. Receive another Push Notification
8. Verify that the badge count is 1

The Badge Count is expected to indicate the number of unseen notes.

### Scenario E: Mark as Read
1. Log into a dotcom account
2. Pick an unread note, and tap on it
3. Hit back
4. Verify that the note is not marked as unread anymore
5. Verify on dotcom // another device, that the "Mark as Read" OP was propagated.

### Scenario F: Push Notification Interaction
1. Log into a dotcom account, and send the app to BG
2. Receive a Push Notification
3. Tap over the Note View (in iOS's Notification Center OR tap the badge, directly)
4. Verify that WPiOS gets launched, and the notification details for the associated note gets pushed

### Scenario G: Background Sync
1. Log into a dotcom account **using the iOS Simulator**
2. Send the app to BG
3. Trigger any event that would trigger a new notification (receive a like, comment, etc)
4. Verify that the following log shows up in the console:  `Running Notifications Background Fetch`
5. After a second (or so!) bring the app to foreground
6. Verify that the new notification is already available

### Scenario H: Foreground Sync
1. Log into a dotcom account **using the iOS Simulator**
2. Open the Notifications Tab
3. Trigger any event that would trigger a new notification (receive a like, comment, etc)
4. Verify that the notification shows up after a while (AKA as soon as the push note is sync'ed)

Needs review: @kwonye 
Sir, may i bug you with a review?

Thanks in advance!

### CODE REVIEW

**Comment by kwonye** [comment]
On initial NotificationsViewController loading we get this warning:
```
Warning: restoration class for view controller does not conform to UIViewControllerRestoration protocol: Class is WordPress.NotificationsViewController
```

**Comment by kwonye** [comment]
Receiving a notification does not refresh the list. Have to pull-to-refresh to actually show the new notifications.

**Comment by kwonye** [comment]
The notifications count does not match the amount of notifications I get (two notifications still show only 1 on the badge)

**Comment by jleandroperez** [comment]
@kwonye Nice catch on the State Restoration log. Cannot repro on my end, but will dig deeper. I've filed Issue #6155 for it.

Push Notifications will be dealt with in #6141 (Fetch new notes as soon as a Push Event comes thru).

I'll double check the Badge detail, not sure what might be going on there.

Thanks!!!

**Comment by jleandroperez** [comment]
@kwonye ready for another look sir. All of the test cases have been properly documented, please, lemme know if anything!

Thanks!!

**Comment by kwonye** [comment]
Works great! Once those tests are fixed, :shipit:

**Comment by jleandroperez** [comment]
@kwonye unit tests fixed, and Badge Behavior updated. I'll go ahead and merge this PR into the midway-branch, so that we can submit right away the **Master PR**!!

I'll make sure of adding a test scenario to cover that edge case.

**THANKS a lot sir!!!**

**Pull request merged**
