### PR TITLE
Feature/ios13 min build version

### PR DESCRIPTION
**Pull request by aerych**
See pbArwn-1ua-p2 for the background on this change.

This PR sets the app's minimum deployment target to iOS 13.0, and acts as the base branch for fixing deprecation warnings.

To test:
Smoke test the app and make sure there are no obvious regressions.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by yaelirub** [comment]
Thank you so much for starting this, @aerych.
I'm going to start with fixing UIKeyCommand init method deprecation.

**Comment by frosty** [comment]
I'll start with the `scrollIndicatorInsets` warnings.

**Comment by frosty** [comment]
Next, activity indicators!

**Comment by frosty** [comment]
Accidentally pushed my commit here instead of creating a new branch targetting this one, so I rolled it back. Will open a new PR, then work on activity indicators.

**Comment by leandroalonso** [comment]
Tomorrow I'll submit a fix to remove the deprecation warnings around `keyWindow`.

**Comment by aerych** [comment]
I'm going to sort out the warnings regarding the Scanner/NSScanner.  They're a bit weird. Some methods are flagged as depreciated only for Swift, not for ObjC, but I think I have a handle on it.

**Comment by emilylaguna** [comment]
I'll submit a fix soon for the `'init(forReadingWith:)' was deprecated in iOS 12.0: Use -initForReadingFromData:error: instead` warnings.

**Comment by aerych** [comment]
Gonna clean up the dimsBackgroundDuringPresentation and UIActivityIndicatorView warnings real quick.

**Comment by aerych** [comment]
Looking into warnings related to `statusBarFrame`, `showsSelectionIndicator`, and `statusBarOrientation`.
And I'll grabe the animation warnings while I'm at it.

**Comment by emilylaguna** [comment]
Update: I'm still working on fixing the archiving warnings. They're a bit more involved than I originally thought. Will have a PR soon.

**Comment by emilylaguna** [comment]
Since I took so long on the last one, I decided to knock out the `requestImageData` warnings as well.

**Review by bjtitus — APPROVED** [review]
✅ Compiles with Xcode 12.3
✅ Remaining warnings seem to be mostly benign (checked the BG App Refresh which [Apple says](https://developer.apple.com/videos/play/wwdc2019-707/?time=1170) does not change functionality on iOS)
✅ Runs - I checked iOS 14 device and simulator and iOS 13 simulator.

**Comment by aerych** [comment]
Thanks @bjtitus !

**Pull request merged**
