### PR TITLE
My Site Dashboard (Phase 2): Display quick start on site menu or dashboard

### PR DESCRIPTION
**Pull request by momo-ozawa**
Part of #17877 

## Description
- Extracted the new Quick Start designs into `QuickStartTourStateView` so that it can be reused on the site menu
- Updated Quick Start display logic so that it's only displayed in either the site menu or the dashboard

Site Menu | Dashboard
-- | --
 | 

## Note

- This PR is targeting the 19.5 milestone because we updated the Quick Start on the site menu to use the new designs 

### MSD feature flag enabled (To be released in MSD phase 2)

1. Enable MSD feature flag
2. Enable Quick Start via Me > App Settings > Debug > Enable Quick Start for site
3. ✅ Make sure Quick Start isn't displayed on the site menu
4. Go to the Home tab
5. ✅ Make sure Quick Start is displayed on the dashboard

### MSD feature flag disabled / regression testing (Targeting 19.5)

1. Disable MSD feature flag
2. Enable Quick Start via Me > App Settings > Debug > Enable Quick Start for site
3. ✅ Make sure Quick Start is displayed on the site menu
4. Go through all of the Quick Start tours
5. ✅ Make sure the waypoint spotlights show up as expected, and that the Quick Start cell updates to display the progress

https://user-images.githubusercontent.com/6711616/157028454-e713b58e-d19c-41fa-86b2-557ddecd6a3a.mp4

## Regression Notes
1. Potential unintended areas of impact
Quick Start tour progress when displayed in the site menu

7. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested manually (see video above)

8. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by leandroalonso — APPROVED** [review]
@momo-ozawa tested all steps and it works as described!

Just an important thing: we need to be able to decide if the tour should appear on the site menu or dashboard.

The reason is that our goal is to do AB testing. So the dashboard might be the default screen, or not. Thus we need to be flexible by deciding to show in one, or the other.

A `UserDefaults` should probably solve this issue. Instead of relying on the feature flag, we can set _where_ it should appear, and then it will appear in the specified place.

**Comment by momo-ozawa** [comment]
@leandroalonso 👋 


> Just an important thing: we need to be able to decide if the tour should appear on the site menu or dashboard.
> 
> The reason is that our goal is to do AB testing. So the dashboard might be the default screen, or not. Thus we need to be flexible by deciding to show in one, or the other.

Since I'm going AFK soon I added this as a subtask on the main issue. I'll address this in a separate PR.

**Comment by leandroalonso** [comment]
@momo-ozawa sure thing! Tks!

**Review by hassaanelgarem — APPROVED** [review]
Works as described 🚀 

Two things to note:
- I noticed that when the Quick Start is shown in the dashboard, there's no way now for the user to completely skip it. Are we planning on handling that?
- Right now when MSD is enabled and I enable Quick Start for a site, once I go to the site menu, a pop-up appears from the bottom prompting me to perform one of the steps. Since "Quick Start" in this case is only displayed in the dashboard, I think this might be a bit confusing for the user.

**Comment by momo-ozawa** [comment]
@hassaanelgarem 👋 

> I noticed that when the Quick Start is shown in the dashboard, there's no way now for the user to completely skip it. Are we planning on handling that?

I'm assuming by skip you mean an option to remove Quick Start? If so, then yes! It's listed as a subtask on the [main issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/17877): "Allow users to remove Quick Start card from dashboard"

> Right now when MSD is enabled and I enable Quick Start for a site, once I go to the site menu, a pop-up appears from the bottom prompting me to perform one of the steps. Since "Quick Start" in this case is only displayed in the dashboard, I think this might be a bit confusing for the user

Hmm! Interesting, added this as a subtask and will investigate in a different PR!

**Comment by brcavallaro** [comment]
Hi @momo-ozawa 👋

After testing this change, I noticed that when I do the logoff from my account, the progress I did with the **Quick Start** steps is not being maintained. This does not happen when I simply close the app and reopen it within the same user session. Do you know if this is expected behavior?

Thank you!

**Comment by leandroalonso** [comment]
@brcavallaro this is expected. Quick Start progress is saved locally, when the user logs out the database is wiped.

**Comment by brcavallaro** [comment]
Hey @leandroalonso 👋 Thanks for explaining that!

**Pull request merged**
