### PR TITLE
Display "ghost post card" when loading posts

### PR DESCRIPTION
**Pull request by leandroalonso**
Ref https://github.com/wordpress-mobile/WordPress-iOS/issues/11646

This PR shows a "ghost post card" when loading posts:

To test:
- Check if the ghost cells appear when loading fresh content
- All the previous error and messages showed by `NoResultsController` should remain the same
- Check it in iPad and with RtL screens

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks great @leandroalonso , thanks!

**Comment by leandroalonso** [comment]
@nheagy currently, in production, the loader of NoResultsController is also flashed when there's no content:



I deliberately added this behavior to override the previous loader. If I remove it, the behavior shown on the previous image will happen.

If we want no loader at all, this will need extra work on the `NoResultsViewController` and will affect all the other screens (Pages, Comments...).

What do you think @SylvesterWilmott?

**Comment by SylvesterWilmott** [comment]
>I deliberately added this behavior to override the previous loader. If I remove it, the behavior shown on the previous image will happen. If we want no loader at all, this will need extra work on the NoResultsViewController and will affect all the other screens (Pages, Comments...).

I think replacing the current loader is what is expected from this PR, if the flashing is part of a more fundamental issue it shouldn't be tackled here.

**Comment by ScoutHarris** [comment]
FWIW, I think this is related: https://github.com/wordpress-mobile/WordPress-iOS/issues/9993.

**Pull request merged**
