### PR TITLE
Navigation arrows for notifications detail

### LINKED ISSUE #6140: Notifications: up/down navigation arrows
Right now the mobile web has up/down arrows to go the the next/previous notification without having to go back to the notifications list. We're going to be adding that to the mobile apps.

img_0561

(note that Apple Mail has something similar) 

img_0768

### PR DESCRIPTION
**Pull request by koke**
Introduces buttons to navigate to next/previous note from the notifications detail.

simulator screen shot 6 feb 2017 12 08 04

Fixes #6140 

To test:

Go to a notification and navigate around. Some things to test:

- Buttons should be disabled when there are no next/previous notifications
- Notifications should be marked as read when you see them
- Getting a new notification while viewing the previously newest notification should update the navigation

@jleandroperez I'd love your opinion on the latest changes, but since you wrote most of this I'm asking @frosty to review it
cc @kwonye 
Needs review: @frosty

### CODE REVIEW

**Comment by frosty** [comment]
@koke @lantean Design question (perhaps let's pull in @mattmiklic too):

Do you think the notification navigation arrows should go vertically to match Calypso, rather than horizontally?) It feels like this would also make more more sense space vertically once we have a splitview in place, because the selection will be moving up and down the notifications list.

Calypso example:

img_6054

**Comment by koke** [comment]
> Do you think the notification navigation arrows should go vertically to match Calypso

I thought so initially, but then Mail uses `<` `>`, so I'm not sure what's the best approach.

> once we have a splitview in place

Also inspired by Mail, I think we should hide the arrows on a split view since you can see the list and select the notification you want.

**Comment by mattmiklic** [comment]
> I thought so initially, but then Mail uses < >, so I'm not sure what's the best approach.

I think it makes sense to match Calypso probably. But one nice thing about `<` and `>` is that it would make sense if we added the ability to horizontally swipe between notifications, as we have on Android. Don't know if that's planned or feasible but it would be a reason to go ahead with left/right instead of up/down now.

**Comment by koke** [comment]
Changed it to up/down, although it looks a bit odd to me:

simulator screen shot 7 feb 2017 08 28 05

**Comment by koke** [comment]
I'm going to merge this for now. If we want to go back to left/right it's a simple fix and can be another PR

**Comment by jleandroperez** [comment]
@koke Bravo!!! 😄

**Pull request merged**
