### PR TITLE
Issue/5849 Update Editor nav bar buttons

### LINKED ISSUE #5849: Re-do Editor Navbar Links
Right now the Nav Bar is a little crowded with the Preview button hangout up there along with the settings and the Post button.
image

Lets simplify it by getting rid of the Preview button and putting it as well as other options underneath an "..." button similar to:
image

### PR DESCRIPTION
**Pull request by frosty**
Fixes #5849. The nav bar in the editor now has its right bar button options under a 'more' menu (and an Edit button when appropriate). This makes things look way less cluttered. I also took the liberty of removing the Edit button tooltip, as it was a hack to position in the right place and it was kind of unnecessary (Tap Edit to Edit, huh?).

screen shot 2016-08-11 at 15 57 55

To test:

* Ensure that the More button behaves as you'd expect (on both Posts and Pages, when entering / exiting edit mode...) and shows the right options. 
* The Save / Update / Post button should appear next to the More button in edit mode, should be enabled when there are changes, and show the correct title.
* Ensure that each option in the menu works correctly.

Needs review: @aerych 
Would you do the honours? Thanks!

### CODE REVIEW

**Comment by frosty** [comment]
Forgot to cc @sendhil on this!

**Comment by aerych** [comment]
Code looks great @frosty :) 
There were a couple of things I noticed on the iPad.

Scenario 1: 
Tap on a post cell to view the detail.
Tap on the more menu. 
With the popover visible, tap on the Edit button. 
The expectation is the popover would dismiss (as it does tapping just about anywhere else on screen. However the popover remains visible and the post switches to edit mode.  The popover continues to show Preview and Share buttons rather than Preview and Option buttons.

Scenario 2:
Tap on a post cell to view the detail.
Tap on the more menu. 
With the popover visible, tap on the Back button. 
You're returned to the post list with the Popover still visible. (No crashes when tapping one the buttons tho!).

Scenario 3:
This one is super nitpicky but...
Tap on a post cell to view the detail.
Tap on the more menu. 
Note the position of the popover's arrow.
Tap the Share button in the popover. 
Note the position of the arrow for the Sharing popover.
I'd expect the two to match exactly.

**Comment by frosty** [comment]
@aerych Thanks for reviewing! I've fixed scenarios one and two – turns out that if a popover is presented from a bar button item then `UIPopoverPresentationController`, by default, will allow taps through to any sibling bar button items. To disable this, you need to set the presentation controller's `passthroughViews` array to nil – BUT, it doesn't work unless you do it after the popover has been displayed. Fun!

As for scenario 3... I've had a look, but I don't think there's a lot I can do here I'm afraid. Both are standard popovers, displayed from the same bar button item. 

Want to quickly double check my fixes for 1 and 2?

**Comment by aerych** [comment]
> BUT, it doesn't work unless you do it after the popover has been displayed. Fun

Hoops man... Apple loves its hoops.

:shipit: when ready! :)

**Comment by frosty** [comment]
Thanks @aerych!

**Pull request merged**
