### PR TITLE
Quick Start: Fix issue of displaying wrong data in quick start steps when the user creates a new site

### LINKED ISSUE #18019: Notices are glitching while being dismissed
### Expected behavior
Notices should be dismissed in a smooth manner. They should either fade out in place, or fade out while animating downwards out of the screen.

### Actual behavior
Notices glitch while being dismissed.

### Steps to reproduce the behavior
1. Enable quick start for a site
2. Go back to My Site
3. Tap Customize Your Site
4. Tap on a step and follow through
5. When done with a step, a notice for the next step will be automatically shown
6. Press Not now
7. Observe the notice being dismissed with a glitchy animation

https://user-images.githubusercontent.com/25306722/155451991-52f85fa5-aecb-4578-aa78-9bf869d4ae0e.MP4

**This is global to all notices not just quick start notices. Same occurs with notice in grow audience tips from stats**

https://user-images.githubusercontent.com/25306722/155452592-1e8de08d-bad5-46dd-b5ef-378aeb99d395.MP4

### LINKED ISSUE #18222: Quick Start: In first step of Quick Start, Site Title message at the bottom is showing the title of previous site
### Expected behavior
The toast at the bottom should show the current site title instead of the previous one.

### Actual behavior
The title of the previous site is shown in the toast message at the bottom when **Quick Start** flow is happening. Check the steps to reproduce and screenshot below.

| Wrong title is shown in **Quick Start** |
| --- |
| <div align="center"></div>  |

### Steps to reproduce the behavior
1. Create a new site
2. When asked for help to manage the new site, press `Show me around` button
3. In **Customize Your Site**, tap the option `Check your site title`
4. Check the title of the site in the message at the bottom of the screen

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Fixes #18222

## Root Cause
Quick start tours were all created on launch, which meant that the strings used were tailored for the blog at launch only. And not modified when the current blog changes.

https://user-images.githubusercontent.com/25306722/160860594-09b528cf-364f-474c-8ea0-667d2fe72f7c.mov

## Testing Instructions

1. Create a new site
2. When asked for help to manage the new site, press Show me around button
3. In Customize Your Site, tap the option Check your site title
4. Check the title of the site in the message at the bottom of the screen
5. It should be "Site Title" and not the title of the previous site.

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hassaanelgarem** [comment]
@mokagio This PR fixes an issue that was raised during the call for testing for `19.5`. We would like to include it in version `19.5` if possible.

Edit: as Leandro mentioned here https://github.com/wordpress-mobile/WordPress-iOS/pull/18244#issuecomment-1083259815, we no longer need this in 19.5, so you can ignore this message. Sorry for the ping!

**Comment by leandroalonso** [comment]
@hassaanelgarem I assume this issue has been there for quite some time, right? I think it's highly unusual that a user will create multiple sites and start the Quick Start for them. So given the proximity of the next release, I think we'll be safe to target `trunk` instead.

I know we talked about targeting `release/19.5` but I think this would be a better solution, sorry about the trouble! :(

**Comment by hassaanelgarem** [comment]
@leandroalonso 
> I assume this issue has been there for quite some time

Looks like it yeah.

I changed the PR to target trunk and the milestone to the next release 👍

**Comment by hassaanelgarem** [comment]
@brcavallaro FYI: this fixes #18222 👍

**Review by leandroalonso — APPROVED** [review]
Works as described! :shipit:

**Pull request merged**
