### PR TITLE
Use `replacePersistentStore` over `migratePersistentStore`

### PR DESCRIPTION
**Pull request by wargcm**
Ref to crash discussion: p1674061274711639-slack-C0180B5PRJ4

## Discussion

There have been performance issues on accounts which have a large number of blogs. On the account which had the issue, there was a memory warning. This is likely due to how `migratePersistentStore` works. The developer documentation on these two functions isn't great but according to a Core Data document, `migratePersistentStore` does the following:

1. Creates a temporary persistence stack.
2. Mounts the old and new stores.
3. Loads all objects from the old store.
4. Migrates the objects to the new store.
5. The objects are given temporary IDs, then assigned to the new store. The new store then saves the newly assigned objects (committing them to the external repository).
6. Informs other stacks that the object IDs have changed (from the old to the new stores), which keeps the stack running after a migration.
7. Unmounts the old store.
8. Returns the new store.

Ref: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/PersistentStoreFeatures.html#//apple_ref/doc/uid/TP40001075-CH23-SW1

Even though the function name `replacePersistentStore` implies that it is replacing something, it can be used to backup a database too. If the destination file does not exist, it will create it.

According to an Apple engineer, `replacePersistentStore` will attempt to do an APFS clone where possible. This greatly improves both the performance of the backup and the memory footprint.

Quote:
> Additionally you should almost never use NSPersistentStoreCoordinator's migratePersistentStore... method but instead use the newer replacePersistentStoreAtURL.. (you can replace emptiness to make a copy). The former loads the store into memory so you can do fairly radical things like write it out as a different store type. It pre-dates iOS. The latter will perform an APFS clone where possible.

Ref: https://developer.apple.com/forums/thread/651325

## Performance

> **Note**
> This was done on an iPhone SE 3rd generation phone with the **debug** build. Since it's debug, these aren't completely accurate but should give an idea of what we'll see.

**Using `migratePersistentStore` (current):**

**Using `replacePersistentStore` (new):**

## Testing

To test:
- Install WordPress and login
- Navigate to any of the Jetpack migration UI
- Initiate the migration
- Install Jetpack and launch
- Verify the database is successfully imported to Jetpack

## Regression Notes
1. Potential unintended areas of impact
WordPress to Jetpack migration flow

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dvdchr** [comment]
> According to an Apple engineer, replacePersistentStore will attempt to do an APFS clone where possible. This greatly improves both the performance of the backup and the memory footprint.

+1. Based on the recent Ask Apple session (ref: p1671177235749989-slack-C01CW1VMLAF), using `replacePersistentStore` is _strongly_ recommended over `migratePersistentStore`.

**Comment by mokagio** [comment]
Bumping from 22.2 to 22.3 because this is still a draft and I'll be starting the 22.2 code freeze tomorrow.

**Comment by mokagio** [comment]
> Bumping from 22.2 to 22.3 because this is still a draft and I'll be starting the 22.2 code freeze tomorrow.

Apologies. I got the wrong milestone last night 🤦‍♂️  I'll be working code freezing _22.1_ shortly, not 22.2.

I'll fix the milestone now.

**Comment by mokagio** [comment]
Moving to the 22.3 milestone because I'll start the 22.2 code freeze in ~14h and this is still a draft.

**Comment by mokagio** [comment]
Moving to the 22.4 milestone because I'll start the 22.3 code freeze in ~14h and this is still a draft.

**Review by dvdchr — APPROVED** [review]
@wargcm Should we go ahead and merge this? I think the changes look good for me.

**Comment by wargcm** [comment]
@dvdchr Sounds good! I'll update this to the latest `trunk` just in case and if everything looks good, I'll merge.

**Pull request merged**
