### PR TITLE
Always show searchbar in navbar.

### LINKED ISSUE #3764: Post/Pages: Use iPhone style search on iPad
Let the iPad and iPhone be consistent in how they present the search bar, favoring the approach taken in the iPhone.  [Background conversation](https://github.com/wordpress-mobile/WordPress-iOS/issues/3673#issuecomment-105312782).

### PR DESCRIPTION
**Pull request by aerych**
Removes obsolete code and IB assets.

Closes #3764 

Needs Review: @kwonye

### CODE REVIEW

**Comment by aerych** [comment]
Heya @kwonye, I wondered if you'd be game to review this once since you're doing some search wrangling of your own.

**Comment by kwonye** [comment]
@aerych on it! It'll be a great intro

**Comment by kwonye** [comment]
:+1: Looks great! 

Unrelated to your changes, but Travis failed with an error in the Widget dependency, so I kicked it off again.

Also has merge conflicts. Once both are resolved, :shipit:!

**Comment by aerych** [comment]
Thanks Will! Conflict resolved.
Travis is failing for pretty much every PR right now so I think we're safe assuming its issue is something separate.

**Pull request merged**
