### PR TITLE
Plans unavailable on simulator

### PR DESCRIPTION
**Pull request by koke**
Show a custom error if we try to load plans on the simulator.

To test: 

Go to the plans list from the simulator and check that the right error message is shown: "Plans are not available on the Simulator"

Also, unit tests should pass

Needs review: @frosty

### CODE REVIEW

**Comment by frosty** [comment]
Sorry to ask this now that you've already written the code, but I'm not sure why we should prevent viewing of plans on the simulator? It's fine to load StoreKit products on the simulator, so to me it makes sense to display them if we can. Should we not just disable purchasing of products (because that's not possible)?

**Comment by koke** [comment]
> It's fine to load StoreKit products on the simulator

Interesting. The reason I did this is because I was getting a `MissingProduct` error when fetching prices from StoreKit, until I realized I was testing on simulator so I switched to a device and it worked. I assumed none of StoreKit would work in the Simulator but I'll double check.

**Comment by frosty** [comment]
Well, I've been testing everything apart from purchases in the simulator up until now, and I've done so on other projects in the past too. I wonder why they weren't loading for you?

**Comment by koke** [comment]
Now it works. Maybe it was an issue with #5100. Closing this

**Pull request closed without merging**
