### PR TITLE
Check reachability, then present WP web view controller with admin url

### PR DESCRIPTION
**Pull request by jstart**

### CODE REVIEW

**Comment by aerych** [comment]
Heya @jstart.  We actually want to keep opening the admin externally.  In the past there was some confusion with the admin actually being a part of the app.   

I kind of like checking Reachability before taking the user out of the app.  That's a nice touch and would be nice to keep.

**Comment by jstart** [comment]
Reverted changes to use the internal web view controller, but kept reachability.

**Comment by aerych** [comment]
I'm a fan :)  Thanks @jstart!
@diegoreymendez, IIRC there was a planned pass through the app to improve the offline experience.  Would you take a peek also to make sure this is in-line anything planned?  If all is well I think we should :shipit:

**Comment by diegoreymendez** [comment]
@aerych - Nothing has been defined yet AFIK, so I'll check out this PR independently of what we may be changing for offline support.

**Comment by diegoreymendez** [comment]
@jstart - This is pretty straightforward.  Thanks for the PR. :+1:

**Pull request merged**
