### PR TITLE
Change WordPress / Jetpack launch screen

### LINKED ISSUE #19325: WPiOS - Update Launch Screen
# Description

Redesign the launch screen of the WordPress app and the Jetpack apps by replacing the existing resources

# Design

Screenshot 2022-09-20 at 12 38 37 PM

# Resources
Figma Design Page: `qk5s4q4mZsXknwhMWo2vIY/WordPress-->-Jetpack-Migration?node-id=3098%3A11890`
Internal discussion: `pbArwn-5dJ-p2#comment-6470`

### PR DESCRIPTION
**Pull request by salimbraksa**
Closes #19325

### Description
This PR updates WordPress and Jetpack launch screens to match the design in Figma qk5s4q4mZsXknwhMWo2vIY-fi-3098%3A11890

### Test Instructions:
Do the following for both WordPress and Jetpack apps:
1. Force close the app if it's already running.
2. Run the app. You should see the launch screen briefly.

| Target | iPhone | iPad |
| --- | --- | --- |
| **WordPress** |  |  |
| **Jetpack** |  |  |

### Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
None.

4. What automated tests I added (or what prevented me from doing so)
None.

### PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by twstokes — APPROVED** [review]
👋 @salimbraksa - this looks good to me! I just had two considerations that came to mind, but aren't blockers for the PR:

1. If we wanted to sync these changes up with the [feature flag](https://github.com/wordpress-mobile/WordPress-iOS/pull/19251) we could
2. The icon in the middle of the screen on iPad feels a bit small to me compared to the device's size. iPhone feels right.

Great work! 🚀

**Comment by ovitrif** [comment]
> * If we wanted to sync these changes up with the [feature flag](https://github.com/wordpress-mobile/WordPress-iOS/pull/19251) we could

Thank you for bringing this up @twstokes 🙇 

I'm rather undecided myself on this, I'd welcome what you suggest 😄
Perhaps we could use from @shaunandrews's feedback to get a clear view if this could get merged separate from the other project changes 😸, imho it's not that much related to the other changes.

**Comment by salimbraksa** [comment]
> 1. If we wanted to sync these changes up with the [feature flag](https://github.com/wordpress-mobile/WordPress-iOS/pull/19251)

I don't think the Launch Screen can be feature flagged. In fact, it's not even possible to set a custom class for the Launch Screen View Controller, if you try to do that, you get the following build error:

>Launch screens may not set custom classnames

https://developer.apple.com/documentation/xcode/specifying-your-apps-launch-screen/

CleanShot 2022-09-23 at 17 48 02@2x

**Comment by twstokes** [comment]
> I don't think the Launch Screen can be feature flagged. In fact, it's not even possible to set a custom class for the Launch Screen View Controller, if you try to do that, you get the following build error:

Good call @salimbraksa! Looks like that decides for us. 😄 

As an alternative we could wait to merge this PR until we're ready to default the feature flag to `true` (e.g. release the new landing screens).

**Comment by salimbraksa** [comment]
>The icon in the middle of the screen on iPad feels a bit small to me compared to the device's size. iPhone feels right. - @twstokes 

I've increased the icon's size to 100x100 for iPad-only. See the Before / After screenshots. Let me know what do you think @twstokes @ovitrif @shaunandrews.

|       | WordPress | Jetpack |
| --- | ----------- | -------- |
| **Before** |  |  |
| **After** | wpipad | jpipad |

**Comment by twstokes** [comment]
> I've increased the icon's size to 100x100 for iPad-only. See the Before / After screenshots. Let me know what do you think @twstokes @ovitrif @shaunandrews.

Thanks for the screenshots @salimbraksa! 50px felt too small on iPad, but 100px seems a little large. 😆 

So, I think we can keep it the way it is until you connect with @shaunandrews.

**Comment by shaunandrews** [comment]
> if this could get merged separate from the other project

I think it's safe to ship this on its own.

> I've increased the icon's size to 100x100 for iPad-only.

I actually like it better at the smaller 50px size; I don't know how to explain it, but the smaller size feels more subtle and dignified.

**Review by ovitrif — APPROVED** [review]
I've tested the changes myself and everything works as expected, great work @salimbraksa!

Thank you for implementing this change 🙇 

Considering @shaunandrews's feedback about shipping this separate from the project changes, I'd say from my side this PR is ready to merge!

@wordpress-mobile/manakin wdyt?

**Comment by antonis** [comment]
> Considering @shaunandrews's feedback about shipping this separate from the project changes, I'd say from my side this PR is ready to merge!

I would agree with that but for consistency lets wait for the Android implementation to ship both in the same release. Wdyt?

**Comment by ovitrif** [comment]
> > Considering @shaunandrews's feedback about shipping this separate from the project changes, I'd say from my side this PR is ready to merge!
> 
> I would agree with that but for consistency lets wait for the Android implementation to ship both in the same release. Wdyt?

Sounds good to me! Thank you for your feedback on this @antonis 🙇 
Let's go with this plan 👍

**Comment by antonis** [comment]
Hey @salimbraksa 👋 
We can now move forward with merging the new splash screens (internal ref `pbArwn-5dJ-p2#comment-6703`) when we have the time. Note that we should place the release note on the latest version (`20.1`) while resolving the conflict.

**Pull request merged**
