### PR TITLE
 Xcode 10.2 compatibility

### PR DESCRIPTION
**Pull request by jtreanor**
This fixes compatibility with Xcode 10.2 by updating Aztec, updating Zendesk and fixing the new Xcode warnings/errors.

Related pull requests and issues:

- CocoaPods update: https://github.com/wordpress-mobile/WordPress-iOS/pull/11442.
- WordPressAutenticator: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/67, https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/68, https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/70
- WordPressKit: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/140
- Aztec: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1167
- CircleCI Orb: https://github.com/wordpress-mobile/circleci-orbs/pull/21
- Zendesk SDK: https://github.com/zendesk/zendesk_sdk_ios/issues/480.
- WooCommerce: https://github.com/woocommerce/woocommerce-ios/pull/868

Still to do:

- [x] Fix remaining warnings and errors (there still Zendesk deprecations that I have not touched).
- [x] Fix crash on launch (`objc[8731]: Swift class extensions and categories on Swift classes are not allowed to have +load methods`). This is caused by https://github.com/facebook/react-native/issues/24139. To fix we will need to upgrade to RN 0.59.3.
- [x] Use release or beta versions of WordPressKit and WordPressAutenticator.
- [x] Fix the crashes caused by building Aztec on Xcode 10.2 (done in https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1167).

**Note:** Due to the Zendesk SDK update this breaks compatibility with Xcode 10.1. We should merge this very carefully with plenty of notice.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by jkmassel** [comment]
Looks like a `Podfile.lock` conflict has popped up in this one

**Comment by jkmassel** [comment]
This builds cleanly, which is great.

However, I'm seeing a few issues we probably want to address:

- React Native is missing nullability hints in Objective-C, which is causing compiler warnings
- WPMediaPickerViewController is missing nullability hints in Objective-C, which is causing a single compiler warning
- We need to upgrade ZenDesk to use the non-deprecated APIs in order to avoid compiler warnings.

Typically we don't accept a merge that still has these warnings, but it's also possible that our dependencies may not get to this right away.

WDYT?

**Comment by jkmassel** [comment]
Screen Shot 2019-04-11 at 11 48 33 AM

**Comment by jtreanor** [comment]
Thanks for taking a look, Jeremy! I completely agree that we should avoid introducing warnings.

There are two things happening here:

1. I should have been clearer but as I mentioned in the PR description, given that I do not have all the context and past experience of working with the Zendesk SDK, I was hesitant to migrate to the new API. My preference would be to open an issue for this when merged. Happy to discuss though.
2. We are experiencing an issue with CocoaPods + Xcode 10.2 where `inhibit_all_warnings!` is not working correctly for header files (https://github.com/CocoaPods/CocoaPods/issues/8219). I saw this but mistakingly thought it had been solved (they went away for me 🤷‍♂️).

I believe it should be possible to work around the CocoaPods warnings issue so I can definitely take a look at doing that. I think it may just be a wrong project setting (Its not happening for Woo).  Unfortunately, it won't be realistic to fix the actual RN warnings.

**Comment by jtreanor** [comment]
@jkmassel I have tried several things to suppress the nullability warnings, but so far nothing has worked. I also cannot reproduce the issue in any other project.

I have opened https://github.com/wordpress-mobile/MediaPicker-iOS/pull/320 to at least eliminate the warning we have control over.

**Comment by jkmassel** [comment]
Fair enough! Hopefully RN gets them fixed soon! :)

**Comment by jkmassel** [comment]
Per our discussion – even if we can't get the third-party warnings fixed just yet, I'm good to :shipit:

**Comment by jtreanor** [comment]
Resolved the conflicts with no other changes so I will go ahead with the merge.

I was still unable to suppress the warnings. I have opened a PR for React Native to fix them here: https://github.com/facebook/react-native/pull/24467.

**Pull request merged**
