### PR TITLE
Merge release 4.9 back into develop

### PR DESCRIPTION
**Pull request by aerych**
Merging `release/4.9` back into `develop`
The only conflicts were with the Podfile and Podfile.lock and were simple to resolve. Still, we might triple check all the things to be sure.

### CODE REVIEW

**Comment by aerych** [comment]
cc @sendhil & @diegoreymendez

**Comment by diegoreymendez** [comment]
@aerych - Considering:

- The merge reported no conflicts
- The commits were already reviewed in other PRs
- And the Travis build succeeded

I'd say :shipit: 

If it sounds good to you, I think that unless there's a conflict merging reviewed code we can go ahead and merge it automatically in the future.  Let me know your thoughts.

**Comment by aerych** [comment]
> I think that unless there's a conflict merging reviewed code we can go ahead and merge it automatically in the future.

I'd feel better having a second set of eyes when there are any conflicts, even if its just in the Podfile.

**Comment by diegoreymendez** [comment]
@aerych - My bad, I assumed there were no conflicts since the code merge was the last commit.

**Pull request merged**
