### PR TITLE
Reader: Maintain focus when pressing "Like" on a post with VoiceOver enabled

### LINKED ISSUE #22065: Reader: VoiceOver's focus jumps at beginning of article list when placing the first like on a post
### Expected behavior
when pressing the "Like" button on a post, VoiceOver's focus should remain on the "like" button. 

### Actual behavior
When pressing the "Like" button on an article and it's the first like the post gets, VoiceOver's focus jumps at the beginning of the posts list, making it difficult to proceed browsing the whole Reader. Involved post must be closed, it occurs in the main Reader window.

### Steps to reproduce the behavior
1. from JetPack app, go to Reader tab. VoiceOver must be active.
2. navigate the page sequentially until you find the "like" button, on a post without any other likes. Don't open the post.
3. place the first Like to the post, so that it will get "one like". 
4. VoiceOver's cursor will immediately jump to the very first article displayed on the feed.

### PR DESCRIPTION
**Pull request by twstokes**
Fixes #22065 by not removing any label views if they contain a `nil` `text` string.

| Before | After |
| - | - |
| <video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/8df0d3f3-f5cd-4f11-9b80-5009d22c1e2a" alt="Video recording of the VoiceOver bug" /> | <video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/4abb44b7-8bad-440d-b26e-1c077330585c" alt="Video recording of the VoiceOver fix" /> |

This may also resolve a visual artifact shown at the bottom of the cell when animating:

| Before | After |
| - | - |
| <video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/f6bae309-9e57-4cee-bd1a-43ec5e63285d" alt="Video recording of the visual artifact" /> | <video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/63c817d3-e0b2-424d-8dd4-8f3277f05c12" alt="Video recording showing no visual artifact" /> |

## Testing

1. Load Reader.
2. Enable VoiceOver.
3. Like a post with no likes.
4. **Expect:** Focus on the "Like" button is not lost and "1 Like" label appears.
5. Unlike the same post from step 3.
6. **Expect** Focus on the "Like" button  is not lost and the label from step 4 disappears.

- Test with VoiceOver off

## Regression Notes
1. Potential unintended areas of impact
    - Cards (cells) in Reader could render incorrectly due to missing text labels

2. What I did to test those areas of impact (or what existing automated tests I relied on)
    - I visually tested loading posts in Reader.
    - I tested Reader using VoiceOver.

3. What automated tests I added (or what prevented me from doing so)
    - None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [x] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by twstokes** [comment]
I attempted to just hide the view via [isHidden](https://developer.apple.com/documentation/uikit/uiview/1622585-ishidden) but that had the same effect as removing it.

**Review by dvdchr — APPROVED** [review]
Thank you for fixing this, @twstokes. Appreciate it! I've tested the changes and it works as expected. LGTM! :shipit: 

A quick confirmation about the base branch, though. I see that we are targeting the 23.9 milestone; do you mean to target the `release/23.9` branch?

**Comment by twstokes** [comment]
Thanks @dvdchr!

> do you mean to target the `release/23.9` branch?

Ah yes, good spot. I originally cut from `trunk` but want this to land on the beta, so I'll get it sorted.

**Comment by twstokes** [comment]
cc @mokagio if you wouldn't mind landing this in the next 23.9 beta due to its high priority. Thank you!

**Comment by twstokes** [comment]
One after-the-fact observation: 

This change adds a little more vertical spacing above the controls. I can bring it up with @osullivanchris to get thoughts, but in the meantime we can go ahead and ship the a11y fix. I actually don't mind the even top and bottom spacing.

image

**Comment by osullivanchris** [comment]
the spacing looks good @twstokes , I'm happy with the change 👍

**Pull request merged**
