### PR TITLE
Media picker update version

### PR DESCRIPTION
**Pull request by SergioEstevao**
This MediaPicker version update fixes the following bugs:

https://github.com/wordpress-mobile/MediaPicker-iOS/issues/85
https://github.com/wordpress-mobile/MediaPicker-iOS/issues/86
https://github.com/wordpress-mobile/MediaPicker-iOS/issues/73
https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/749 -> associated PR https://github.com/wordpress-mobile/MediaPicker-iOS/pull/91

and also improves the accessibility on the component:

https://github.com/wordpress-mobile/MediaPicker-iOS/pull/81

Needs Review: @astralbodies

### CODE REVIEW

**Comment by astralbodies** [comment]
@SergioEstevao - am I correct that none of the code changes listed above behind this new version of WPMediaPicker were peer reviewed?

**Comment by SergioEstevao** [comment]
@astralbodies you are. That is why I always ask someone to peer review the merge of a new version.

**Comment by astralbodies** [comment]
@SergioEstevao Okay I'll go back on those PRs and check them over. I found a weird rotation animation glitch with the popover but it might not be related to the underlying PRs.

**Comment by astralbodies** [comment]
So the only weird thing I'm seeing is the dismissal animation of the popover goes funky - the view inside resizes to something really small in the upper left corner during the fade out.
popover animation

**Comment by SergioEstevao** [comment]
Is this on device or simulator?

**Comment by astralbodies** [comment]
This is on the simulator - I'm not seeing the strangeness on the actual 6 Plus right now.

**Comment by astralbodies** [comment]
:shipit: for now - didn't do a deep deep dive into the code that changed in the other repo.

**Pull request merged**
