### PR TITLE
[Global Styles] Implement Global Styles endpoint

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes** https://github.com/wordpress-mobile/gutenberg-mobile/issues/3163
**Related PRs** 
- `WordPressKit` https://github.com/wordpress-mobile/WordPressKit-iOS/pull/394
- `Gutenberg-Mobile` https://github.com/wordpress-mobile/gutenberg-mobile/pull/3459
- `Gutenberg` https://github.com/WordPress/gutenberg/pull/30544

This change is dependent on: https://github.com/WordPress/gutenberg/pull/29969

## To test:
You can enable and disable the feature by:
1. Clicking your Avatar from the My Site Screen
2. Navigate to App Settings > Debug
3. Toggle "Global Style Settings" for the desired Setting

### Regression Tests:
These should be run on a site with "Global Style Settings" disabled or a site that doesn't have WordPress 5.8 installed:

- [x] Default Colors - Check that default colors still load - [steps](https://github.com/wordpress-mobile/test-cases/blob/gss-updates/test-cases/gutenberg/editor-theme.md#tc001) 
- [x] Default Gradients - Check that default gradients still load - [steps](https://github.com/wordpress-mobile/test-cases/blob/gss-updates/test-cases/gutenberg/editor-theme.md#tc002)
- [x] Custom Colors - Check that custom colors load in the editor - [steps](https://github.com/wordpress-mobile/test-cases/blob/gss-updates/test-cases/gutenberg/editor-theme.md#tc003)
- [x] Custom Gradients - Check that custom gradients load in the editor - [steps](https://github.com/wordpress-mobile/test-cases/blob/gss-updates/test-cases/gutenberg/editor-theme.md#tc004)
- [x] Offline Support - [steps](https://github.com/wordpress-mobile/test-cases/blob/gss-updates/test-cases/gutenberg/editor-theme.md#tc005)

### Tests:
These should be run on a site with "Global Style Settings" enabled and a site that has WordPress 5.8 installed:

- [x]  FSE Colors and Gradients - [steps](https://github.com/wordpress-mobile/test-cases/blob/gss-updates/test-cases/gutenberg/editor-theme.md#tc007)
- [x] Offline Support - [steps](https://github.com/wordpress-mobile/test-cases/blob/gss-updates/test-cases/gutenberg/editor-theme.md#tc008)

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

## PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by antonis — COMMENTED** [review]
Great work @chipsnyder 👍 
I started reviewing this and I've run into an issue with a missing gradient selector. I was able to reproduce this on Android too thus this seems unrelated with this PR.
The code changes LGTM but I've seized testing for now till we find out when this was introduced.

<details><summary>Screenshot</summary>

IMG_B1253007DCAD-1
</details>

**Comment by SiobhyB** [comment]
@chipsnyder, @antonis, do you have an idea when [the changes to GutenbergViewController](https://github.com/wordpress-mobile/WordPress-iOS/pull/16411/files#diff-beacfffc3f8a87edf94895da980a81e356f1b5aa7998f70791bc7baec9a11731) will be merged here? I'm looking to set [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/16427) as ready for review, but it's not currently building, which I believe is due to the changes from the merged Gutenberg PRs that this PR is connected to: 

Screenshot 2021-06-30 at 23 20 57

Thanks in advance!

**Comment by chipsnyder** [comment]
Hey @SiobhyB I'll work with @geriux to get this merged today since @antonis is AFK. Sorry about that delay and blocker.

**Review by geriux — APPROVED** [review]
LGTM! Ran some tests to check there are no regressions and is all good! Nice work!

**Pull request merged**
