### PR TITLE
Stories: iPad Support

### PR DESCRIPTION
**Pull request by bjtitus**
Adds iPad support for Stories.

#### Related PRs

Kanvas: https://github.com/tumblr/kanvas-ios/pull/112

## Changes

- Kanvas now supports iPad by fixing rotation and layout bugs.
- Removes to disable Stories for iPad (`EditorCreationError` and other related code)
- Changes the discard action sheet to an alert on iPad
- Uses `confirmButton` to display the prepublishing sheet as a popover.
- Changes the modal presentation style to `overFullScreen` so that it mirrors the iPhone presentation.
- Fixes a resizing bug in the Prepublishing sheet to allow for proper resizing based on the footer contents.

## Testing

- Verify that the "Story post" option is listed in the bottom sheet when tapping the FAB
- Create a Story
- Capture media from your device's camera. Ensure that rotation and capture functionality work as expected.
- Add media from your device's library. Ensure media is properly displayed in a 9:16 aspect ratio centered in the screen.
- Ensure that posting the content works as expected.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
👋 We're freezing 17.3 today, so this PR is being bumped to 17.4

**Review by danielebogo — APPROVED** [review]
Hey @bjtitus code looks good to me.

But I found some problem during the test. Not sure if its related to this PR though so I'm gonna approve it.
- On iPad/iPhone: If I select more than one image (or shoot more than 1) and I tap the arrow to post, the app crashes. (below the screenshot)
- On iPhone: if I select an image and then tap the arrow to post it, when I navigate back and I tap the + to add one more image, the camera doesn't work anymore and I can only import images from my camera roll
- On iPad: same scenario I described above, when I dismiss the popover to post, I can not add a new image because the + button is not enabled.

Screenshot 2021-05-04 at 15 50 24

**Comment by jkmassel** [comment]
👋 We're freezing `17.4` today, so this PR is being bumped to `17.5`

**Comment by jkmassel** [comment]
We're cutting `17.5` today, so this PR is being bumped to `17.6`

**Comment by mokagio** [comment]
@bjtitus I'm going to bump this to the next release because we'll be code freezing `17.7` today and this is still a draft.

If this cannot wait two weeks and it's important that this makes it into this release, let me know and we'll organize a new beta once ready. 👍 

Also, both this and #16583 have been sitting here for a while. Is there something I can do to help unstuck them? 🤔

**Comment by twstokes** [comment]
👋 I'm going to close this PR due to lack of activity, but please reopen if this was an error. Thank you.

**Pull request closed without merging**
