### PR TITLE
Remove Jetpack Signup feature flag

### PR DESCRIPTION
**Pull request by elibud**
**Fixes** #8949 

**To test:**

Check that in a production build Jetpack sign up is enabled.

Note: @nheagy while working on this I noticed two things:

- Social signup is not enabled from the Jetpack flow (I'm fine shipping a v1 without this)
- There's no option to update the username in this flow

Is there any particular reason for that or just that it's another step we haven't implemented yet?

### CODE REVIEW

**Comment by nheagy** [comment]
The epilogue is being hidden for the login flow with Jetpack, so I assumed the same for jetpack-via-signup. The mockup doesn't specify either way, so perhaps @mattmiklic could give some guidance?

**Comment by mattmiklic** [comment]
> The epilogue is being hidden for the login flow with Jetpack, so I assumed the same for jetpack-via-signup. 

I'm not sure if I have the terms right here, but:

- With my self-hosted site, if I go to Stats > Set up Jetpack > log in with my existing WordPress.com account, I do see the epilogue, which makes sense because when I connected that account I added a bunch more sites to the app.

- With my self-hosted site, if I go to Stats > Set up Jetpack > and then create a new WordPress.com account, I don't see the epilogue, because I've just created a new account for the site that was already connected to the app.

Make sense?

**Comment by elibud** [comment]
@mattmiklic @nheagy for sign up we need to display the epilogue so you can change your display name, does it make sense?

**Comment by folletto** [comment]
Yep: the "epilogue" in signup is not just an epilogue, but allows to change details — it's an epilogue in the sense that reviews all the details, and one can skip everything and move forward. :)

**Comment by elibud** [comment]
Thank you @mattmiklic and @folletto, and no, we don't need a design.

**Comment by elibud** [comment]
Closing this PR as it is too out of date, @nheagy will create a new one to enable Jetpack sign up.

**Pull request closed without merging**
