### PR TITLE
Change Gutenberg switch to only affect new posts

### PR DESCRIPTION
**Pull request by koke**
See https://github.com/wordpress-mobile/gutenberg-mobile/issues/565

To test:

* Open a post with blocks, it should open in Gutenberg regardless of opt-in
* Open a post without blocks, it should open in Aztec regardless of opt-in
* Create a new post, it should open in Gutenberg if the setting is on or Aztec if the setting is off

I've added a few unit tests to test that behavior as well.

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.
☝️ We'll add a single entry for all Gutenberg related changes https://github.com/wordpress-mobile/gutenberg-mobile/issues/584

cc @hypest

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Added the "Do not merge" flag for clarity, which can be removed once the conditions are given for it.

**Comment by diegoreymendez** [comment]
Thinking about it a bit more, that may be intentional since the switch is still only available internally?

Let me know.

**Comment by koke** [comment]
Oh, not intentional, good catch. I guess that alert needs to go now since it should only show when a gutenberg post is opened in Aztec, which shouldn't be possible anymore unless you "Switch to Classic" from Gutenberg. I'll change that

**Comment by hypest** [comment]
FWIW, removed it in the Android side of the work: https://github.com/wordpress-mobile/WordPress-Android/pull/9208

**Comment by koke** [comment]
Ready for another look

**Pull request merged**
