### PR TITLE
Quick Start V2: Fix notice bug

### PR DESCRIPTION
**Pull request by danielebogo**
Refs. #10860 

This PR fix a bug introduced changing the checklist presentation style. After the checklist is dismissed the notice doesn't appear correctly. It appears over the tab bar.

image

To fix it the selected tour starts after the checklist is definitely dismissed.

**To Test:**
• Open a qs checklist and select a tour
• The notice won't be displayed over the tab bar anymore

### CODE REVIEW

**Comment by danielebogo** [comment]
@nheagy thanks for the hint. I moved the `scroll(to:)` into the observer. I'm bit scared about it because I don't know who send that notification but it seems work fine.
Initially `scroll(to:)` was in the `viewDidAppear` (I only wrapped it with the block) but now I removed it. Let me know if I need to revert to its original state.

**Comment by danielebogo** [comment]
@nheagy I thought that the `scroll(to:)` should remain in the viewDidAppear for the V1. What do you think?

**Comment by nheagy** [comment]
`I thought that the `scroll(to:)` should remain in the viewDidAppear for the V1. What do you think?`

This is probably correct.

**Comment by danielebogo** [comment]
@nheagy Ok perfect! Let me fix it!

**Comment by danielebogo** [comment]
Awesome! Thanks @nheagy !

**Pull request merged**
