### PR TITLE
Time zone settings

### LINKED ISSUE #7831: Add missing Jetpack settings
We are missing some Jetpack settings in the app. We will work with @mattmiklic to get a design and determine which ones we should add and in the process we will probably add some Calypso ones too.

### PR DESCRIPTION
**Pull request by koke**
Support for changing the time zone in Settings for WordPress.com sites

ios-timezone-settings

To keep things simple, I'm only persisting in memory, and otherwise fetching from the network. If there's a memory warning, the store will reset its state and release the cached time zones.

Fixes #7831 

To test:

- Try to change the time zone in a WordPress.com site and a Jetpack site
- Verify that the change reflects in the web
- Verify that search works as expected

### CODE REVIEW

**Comment by elibud** [comment]
I tested on .com and Jetpack sites and it worked correctly. I'm not sure how you want to handle the rows, since Language and Timezone should be available for Jetpack sites.

**Comment by koke** [comment]
> Can we add a little label saying: Choose a city in your timezone or enter a manual offset. somewhere in the TimeZoneVC?

I'm not sure that's going to look right. We usually add explanations as a footer, but it's not going to be visible with such a long list.

> I was searching for Uruguay for a bit with no results

That's unfortunate, but similar to calypso/wp-admin, and the time zone list doesn't include the country. I'm not sure if that's often the case for you, but at this point I'm used to search for `Madrid` on any timezone list.

**Comment by koke** [comment]
> we are not displaying the NoResultsView when a search returns nothing

That's also how the language selector works. Having noResults there could be a nice touch, but I'm not sure it's needed if it's searching as you type.

**Comment by koke** [comment]
I just tested enabling language/timezone for Jetpack, and time zones work, but language is not persisted (wp-admin keeps showing English)

**Comment by elibud** [comment]
Oh well, lets just add Timezone then to JP sites. Let me know when that's done and I'll take another look, I'm fine with the other comments. Thanks

**Comment by koke** [comment]
Enabled for Jetpack sites as well, I had to move the rows around a little bit

**Comment by elibud** [comment]
Now I'm also seeing the setting for self-hosted sites 🤦‍♀️, adding these three lines on `Line 211` of `SiteSettingsViewController` seem to do the trick, what do you think?

```
    // Timezone is only available for WordPress.com and Jetpack sites
    if (![self.blog supports:BlogFeatureWPComRESTAPI]) {
        rowCount--;
    }
```

**Comment by koke** [comment]
Yes 🤦🏽‍♂️ That should do it

**Comment by elibud** [comment]
@koke leave it with me, I'll take care of it.

**Pull request merged**
