### PR TITLE
Update Aztec to version 1.7.0 and GB latest (1.7.0)

### PR DESCRIPTION
**Pull request by SergioEstevao**
To test:
 - Test copy paste from other apps and internally in GB
 - Test insertion and use of all blocks
 - Check focus issues
 - Check editing the Title of the post and press Enter

Note: still need to update the release notes, waiting for the final version GB-mobile to know what changed.

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
> Block validation Error on Quote block when starting typing on the second line.

This one looks bad, need to investigate more if there is a workaround for it.

**Comment by pinarol** [comment]
> This one looks bad, need to investigate more if there is a workaround for it.

was this solved @SergioEstevao ? I still see the validation error

**Comment by pinarol** [comment]
>was this solved @SergioEstevao ? I still see the validation error

Sorry for the wrong alarm, I don't see it anymore

**Comment by mkevins** [comment]
> The caret position remains at start after I paste. Happens only on empty blocks.
I'm observing the same on WordPress-Android.

**Comment by etoledom** [comment]
> Change detection works incorrectly, I see the "You have unsaved changes" action sheet even if I don't change anything:

@pinarol does your test post have an image with caption?

I only was able to reproduce it when I added an image with multi paragraph caption. Removing it the problem is gone.

There might be other instances that generate this issue too.

**Comment by pinarol** [comment]
@etoledom 👋  here's my post:

```
<!-- wp:paragraph -->
<p>Sdfaas</p>
<!-- /wp:paragraph -->

<!-- wp:video {"id":4482} -->
<figure class="wp-block-video"><video controls src="https://eritreocazzulati.files.wordpress.com/2019/06/20190611_151006.mp4"></video></figure>
<!-- /wp:video -->

<!-- wp:paragraph -->
<p>Asdf</p>
<!-- /wp:paragraph -->

<!-- wp:quote -->
<blockquote class="wp-block-quote"><p>asdasd asd asdf</p><cite>asdfsd sade asd<br />asdfdfs<br />asdf<br />asdfasd<br />High<br />Asdf<br />Asdf<br />Asdf</cite></blockquote>
<!-- /wp:quote -->

<!-- wp:quote -->
<blockquote class="wp-block-quote"><p></p></blockquote>
<!-- /wp:quote -->

<!-- wp:video {"id":1598} -->
<figure class="wp-block-video"><video controls src="https://videos.files.wordpress.com/4TucFubg/vid_20190603_122736-1_hd.mp4"></video></figure>
<!-- /wp:video -->

<!-- wp:video {"id":1490} -->
<figure class="wp-block-video"><video controls src="https://videos.files.wordpress.com/2WOwVmnA/ytzfjbuqce-1_hd.mp4"></video></figure>
<!-- /wp:video -->

<!-- wp:video {"id":1637} -->
<figure class="wp-block-video"><video controls src="https://videos.files.wordpress.com/XWdEP3Np/20190611_151006-1_hd.mp4"></video></figure>
<!-- /wp:video -->

<!-- wp:video -->
<figure class="wp-block-video"></figure>
<!-- /wp:video -->

<!-- wp:image {"id":1623} -->
<figure class="wp-block-image"><img src="https://pinpin.blog/wp-content/uploads/2019/06/Screen-Shot-2019-04-03-at-18.40.11.png" alt="" class="wp-image-1623"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":1592} -->
<figure class="wp-block-image"><img src="https://pinpin.blog/wp-content/uploads/2019/06/y2mate-1.com-nature_short_video_iqx4s3apkqm_240p_dvd.original.jpg" alt="" class="wp-image-1592"/></figure>
<!-- /wp:image -->

```
Very interesting thing happened: I removed the last block with {"id":1592} and updated the post, problem stopped occurring. When I add it back it started happening again. So I thought there's a problem related with that specific block, but after a few more publishes now I have the block {"id":1592} but I can't see the problem :( Maybe it is not directly related with the post content. Note: I sometimes edit this post from Android also.

**Comment by etoledom** [comment]
@pinarol thanks for sharing!

> Maybe it is not directly related with the post content.

Yeah that's also a possibility, or at least not related to a specific kind of content.

**Pull request merged**
