### PR TITLE
Languages naming refactor

### PR DESCRIPTION
**Pull request by koke**
I found the naming around the Language helpers way too ambiguous. Specially if we're already handling the different representations of languages between iOS and WordPress, if we have a `Language` type, it should be way more generic.

In this PR:

- I renamed `Languages` to `WordPressComLanguageDatabase`, which is closer to reality. This class is about WordPress.com supported languages.
- I renamed `Language` to `WordPressComLanguage`, as it's not a generic "language" but a representation of one in WordPress.com terms.
- I removed `sharedInstance`. Having a shared instance means that the list of languages is always in memory wether you need it or not. As languages are accessed very rarely, I'd rather load the database on demand.
- I make LanguageTagVariants a top level type. Even if it's currently private, it's not really related to WordPress.com, so it doesn't belong there. To be extra correct, this could be a generic method on `SequenceType` and I'm sure there's a name for that concept already, but I thought this was a good enough compromise.

I would have changed a few more things, but it felt like they were more a matter of style preferences. I think the current changes make the purpose of the types clearer and more semantically consistent.

Needs review: @jleandroperez

### CODE REVIEW

**Comment by jleandroperez** [comment]
Looking good @koke!

I initially picked `Languages` / `Language` since the actual class name (namespaced) is `Wordpress.Languages`

Plus `WordPressComLanguage`, namespaced, actually is `WordPress.WordPressComLanguageDatabase.WordPressComLanguage`, which feels a little bit too... verbose?. (Maybe) the nested class could be just called `Language`?

Nevertheless, that's just a personal style / taste, and doesn't affect functionality. So by all means, feel free to disregard.

:shipit: sir!

**Comment by koke** [comment]
I usually don't consider the WordPress prefix as it is rarely seen.

I agree that the full name of the language class is a bit verbose, and I didn't think of that. However, I think I'd rather keep the prefix and move it to be a top level class

**Comment by jleandroperez** [comment]
Since it's 100% a personal preference, absolutely your call on this one @koke.

**Comment by koke** [comment]
OK, I renamed `WordPressComLanguage` back to language. I went to move it to top level, but then it lost access to the `Keys` struct, so I'd have to further refactor it. I think it's good enough as it is for now.

**Pull request merged**
