### PR TITLE
Update project to recommended XCode 9 settings

### PR DESCRIPTION
**Pull request by elibud**
**Fixes** #7900 
Mostly by adding missing voids to comply with the strict prototype policy.

**To test:**
1. Clean + Build, check that there are no warnings other than: 
1.1 Convesion to Swift 4 is available.
1.2 Case is already handled by previous patterns; consider removing it (this one looks like a bug, @nheagy already looked into it, but if you want to double check is much appreciated)
1.3 Our old friend: Some object files have incompatible Objective-C category definitions....
2. Run the app, check that everything works as expected.

Needs review: @koke

### CODE REVIEW

**Comment by elibud** [comment]
@koke we still have warnings on the test target, but we can address those in another PR, I'm struggling to find a solution and I want this merged in version 8.6

**Comment by elibud** [comment]
BTW the warnings are not for our code, I've fixed those, they are for the included pods, related to the Cocoapods bug mentioned earlier

**Comment by koke** [comment]
When I build I'm also seeing:

```
WordPress/Classes/ViewRelated/Post/PostListFilterSettings.swift:88:14: warning: case is already handled by previous patterns; consider removing it
        case PostServiceTypePost as String:
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by koke** [comment]
I'm now seeing a lot of "This block declaration is not a prototype" warnings when running the tests, all about the Specta headers and TracksLogging.h.

**Comment by koke** [comment]
> Some object files have incompatible Objective-C category definitions

Just for reference, this [swift issue](https://bugs.swift.org/browse/SR-5415) has some interesting info. It might get resolved when switching to Swift 4, or hopefully a future Xcode version will give a better error to figure out what exactly is triggering it.

**Comment by elibud** [comment]
> I'm also seeing the Pods project asking to update to recommended settings.
This should be fixed once CocoaPods is updated, we can not fix it on our side since the project is regenerated on every `pod install`

The `Specta` issues I was not able to fix unfortunately, they should go away once `Specta` is updated.

**Comment by elibud** [comment]
@koke this is ready for another look, `Specta` and `Automattic-Tracks` updated 🎉

**Pull request merged**
