### PR TITLE
Swift 3: Staging

### PR DESCRIPTION
**Pull request by kurzee**
Staging PR as we bring in contributions, merge fixes, and other changes.

### CODE REVIEW

**Comment by kurzee** [comment]
Swift 3 doesn't seem to be a fan of `UserDefaults() as! KeyValueDatabase` and will crash the app on launch.

As seen in:
- `WordPress/Classes/Services/MediaSettings.swift`
- `WordPress/Classes/Services/EditorSettings.swift`
- `WordPress/Classes/Services/Store.swift`

@frosty can you take a look at the use of `KeyValueDatabase` and see if we can't fulfill the protocol cast without crashing on launch?

You can push commits here to the `swift-3` branch as needed.

**Comment by frosty** [comment]
@kurzee Looks like the line that added conformance to `NSUserDefaults` for the `KeyValueDatabase` protocol got removed in the migration. I've just added it back in and pushed a commit.

**Comment by kurzee** [comment]
@frosty another one for you 😄 

The init for an HTML styled attributed string is crashing on login with 2fa here: https://github.com/wordpress-mobile/WordPress-iOS/blob/swift-3/WordPress/Classes/Extensions/NSAttributedString+StyledHTML.swift#L22

Can you take a look and see if you can figure out what is going on?

```
2016-12-08 17:35:16:702 WordPress[57853:8139369] Error receiving OAuth2 token: Error Domain=WordPressComOAuthError Code=4 "Please enter the verification code generated by your Authenticator mobile application." UserInfo={NSLocalizedDescription=Please enter the verification code generated by your Authenticator mobile application.}
2016-12-08 17:35:16.715 WordPress[57853:8139369] -[_SwiftValue unsignedIntegerValue]: unrecognized selector sent to instance 0x618000054940
2016-12-08 17:35:16.742 WordPress[57853:8139369] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_SwiftValue unsignedIntegerValue]: unrecognized selector sent to instance 0x618000054940'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ecd334b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010e73b21e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ed42f34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010ec58c15 ___forwarding___ + 1013
	4   CoreFoundation                      0x000000010ec58798 _CF_forwarding_prep_0 + 120
	5   UIFoundation                        0x00000001111da953 -[NSHTMLReader _loadUsingWebKit] + 1329
	6   UIFoundation                        0x00000001111dbf15 -[NSHTMLReader attributedString] + 22
	7   UIFoundation                        0x000000011117245c _NSReadAttributedStringFromURLOrData + 5779
	8   UIFoundation                        0x0000000111170d35 -[NSAttributedString(NSAttributedStringUIFoundationAdditions) initWithData:options:documentAttributes:error:] + 115
	9   WordPress                           0x0000000105f034fd _TTOFCSo25NSMutableAttributedStringcfzT4dataV10Foundation4Data7optionsGVs10DictionarySSP__18documentAttributesGSqGVs33AutoreleasingUnsafeMutablePointerGSqCSo12NSDictionary____S_ + 173
	10  WordPress                           0x0000000105efcd34 _TFCSo25NSMutableAttributedStringCfzT4dataV10Foundation4Data7optionsGVs10DictionarySSP__18documentAttributesGSqGVs33AutoreleasingUnsafeMutablePointerGSqCSo12NSDictionary____S_ + 100
	11  WordPress                           0x0000000105f911a3 _TZFE9WordPressCSo18NSAttributedString24attributedStringWithHTMLfTSS10attributesGSqGVs10DictionaryOS_17HTMLAttributeTypeGS1_SSPs9AnyObject_____S0_ + 803
	12  WordPress                           0x000000010612d300 _TFC9WordPress23Signin2FAViewController27configureSendCodeButtonTextfT_T_ + 1120
	13  WordPress                           0x000000010612c0f8 _TFC9WordPress23Signin2FAViewController11viewDidLoadfT_T_ + 104
	14  WordPress                           0x000000010612c182 _TToFC9WordPress23Signin2FAViewController11viewDidLoadfT_T_ + 34
	15  UIKit                               0x0000000109adec99 -[UIViewController loadViewIfRequired] + 1258
	16  UIKit                               0x0000000109ae5102 -[UIViewController __viewWillAppear:] + 118
	17  UIKit                               0x0000000109b0ffbf -[UINavigationController _startCustomTransition:] + 1290
	18  UIKit                               0x0000000109b20c34 -[UINavigationController _startDeferredTransitionIfNeeded:] + 697
	19  UIKit                               0x0000000109b21dc7 -[UINavigationController __viewWillLayoutSubviews] + 58
	20  UIKit                               0x0000000109d18d6f -[UILayoutContainerView layoutSubviews] + 223
	21  UIKit                               0x0000000109a01f50 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1237
	22  QuartzCore                          0x00000001094d8cc4 -[CALayer layoutSublayers] + 146
	23  QuartzCore                          0x00000001094cc788 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
	24  QuartzCore                          0x00000001094cc606 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	25  QuartzCore                          0x000000010945a680 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 280
	26  QuartzCore                          0x0000000109487767 _ZN2CA11Transaction6commitEv + 475
	27  QuartzCore                          0x00000001094880d7 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 113
	28  CoreFoundation                      0x000000010ec77e17 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	29  CoreFoundation                      0x000000010ec77d87 __CFRunLoopDoObservers + 391
	30  CoreFoundation                      0x000000010ec5cb9e __CFRunLoopRun + 1198
	31  CoreFoundation                      0x000000010ec5c494 CFRunLoopRunSpecific + 420
	32  GraphicsServices                    0x0000000111751a6f GSEventRunModal + 161
	33  UIKit                               0x000000010993d964 UIApplicationMain + 159
	34  WordPress                           0x0000000105bed6ee main + 62
	35  libdyld.dylib                       0x000000010fc4f68d start + 1
	36  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by kurzee** [comment]
@frosty I think I fixed the issue for https://github.com/wordpress-mobile/WordPress-iOS/pull/6277#issuecomment-265890414 in https://github.com/wordpress-mobile/WordPress-iOS/pull/6277/commits/b38b4aebceca13866257888c2e8f9bd5f8635d8f, but it looks like we are losing the white text color styling on 2fa login. Can you take a look and see if perhaps something else is lost in the migration for `NSAttributedStrin+StyledHTML.swift`?

**Comment by frosty** [comment]
@kurzee I just pushed a fix for the HTML issue. The `colorHex` string that's used to populate the CSS styles for the attributed string was coming through as an optional (and being interpolated into the string as `Optional(#ffffff)`), so I've explicitly unwrapped it.

**Comment by kurzee** [comment]
>I just pushed a fix for the HTML issue.

@frosty thanks!

**Comment by kurzee** [comment]
Closing this staging PR to reopen as an actual merging PR. Thanks for all your help @frosty!

**Pull request closed without merging**
