### PR TITLE
Sync blog visibility to WordPress.com

### LINKED ISSUE #969: Sync hidden blog status with WordPress.com
From #715, let's sync blog visibility with WordPress.com once the API for it is in place.

Moving to a separate ticket since this will be punted to 3.9.1 or later

### PR DESCRIPTION
**Pull request by koke**
To verify it works, you can check your blogs list at
https://wordpress.com/sites

Or manage visibility at
https://dashboard.wordpress.com/wp-admin/index.php?page=my-blogs

Fixes #969 

Needs Review: @sendhil

### CODE REVIEW

**Comment by koke** [comment]
I wanted to add more UI to show/hide all and coalesce the network requests, but I'd rather keep the PR simple and work on that later.

**Comment by koke** [comment]
I got too excited about this but now I have some concerns. Since this isn't implemented in Calypso or Android, I'm worried that:
- On upgrade, any previously hidden blogs would reset
- When the user hides a blog in the app, it will hide on WordPress.com as well.

This last bit isn't obvious, and really hard to undo from the web side unless you know where to look for.

Maybe we should only sync this on internal betas until there UI is ready in other platforms.

**Comment by folletto** [comment]
> Maybe we should only sync this on internal betas until there UI is ready in other platforms.

Yeah, without a Calypso UI this is going to be even more challenging for users. I totally see the pain tho.

**Comment by sendhil** [comment]
@koke - I'm kind of nervous about integrating this right now with a internal build flag as i'm worried something might leak and without the appropriate UI in place it would make the experience bad for our users. Lets hold off on this until we have a Calypso UI in place?

**Comment by koke** [comment]
Closing this for now until there's a UI on the web side.

**Comment by sendhil** [comment]
@koke after chatting with @apeatling  a bit lets go ahead and merge this in for now.

**Comment by apeatling** [comment]
My thoughts summed up:

* Hiding a blog is a very explicit action, the user is going to know what they are doing in the app, and if they don't, they're going to change it back.
* It's annoying right now for people (agreed mostly a8cs) to have hidden sites on the web, and still see them all in the apps, it makes the apps feel behind.

**Comment by folletto** [comment]
:+1:

**Comment by koke** [comment]
> the user is going to know what they are doing in the app, and if they don't, they're going to change it back
If there still isn't a UI for this in calypso and they don't have their phone available it might be hard to do so. Granted, this is a feature for power users and they'll probably figure out a way.

Also, I thought we were moving away from hiding things towards giving more prominence to recently used or "favorite" sites (see calypso issue 8618)

**Comment by apeatling** [comment]
> If there still isn't a UI for this in calypso and they don't have their phone available it might be hard to do so. Granted, this is a feature for power users and they'll probably figure out a way.

That's possible, but seems unlikely. Still not enough of a chance to not do it and help everyone else.

**Comment by sendhil** [comment]
@koke - could you merge in the latest changes from develop so this could be merged in?

**Comment by koke** [comment]
Merged. It seems to still work fine, but it still needs review

**Comment by sendhil** [comment]
:shipit:

**Pull request merged**
