### PR TITLE
Switch over showing/fetching Streak data to new architecture

### PR DESCRIPTION
**Pull request by jklausa**
This was the last Insight that was using the old architecture/backend. Now all of them are powered by the new data layer :)

~Note: I noticed (present also in current implementation) problem with displaying the graph for sites with extremely heavy posting traffic (like our team P2, for example). I filed a [bug in WPKit](https://github.com/wordpress-mobile/WordPressKit-iOS/issues/104) and will fix it next week.~ fixed it upstream in WPKit already: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/107

To test:

Verify the app builds
Verify the data shown for Streaks in stats insights is the same as above

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @jklausa - looks like there's some data missing. This is from `develop` (looking at Hogwarts):

develop

This is your branch:
branch

Mar - June have no data, and July has partial.

Not sure where the problem lies, so I'll refrain from taking any action on the accompanying WPKit PR until you take a look.

**Comment by jklausa** [comment]
argh i didn't want to merge this yet

**Comment by jklausa** [comment]
my cat literally walked on my keyboard to do it, I _wish_ i were making it up...

**Comment by jklausa** [comment]
it's fine though, tests passed so it should be g2g :D

**Pull request merged**
