### PR TITLE
[Stats Refresh] Add Insights Followers card

### LINKED ISSUE #10668: [Stats Refresh] Add Insights Followers card
Add Insights Followers card.

- [ ] Fully expanded
- [ ] Tabbed view showing Followers/Email Followers
- [ ] No data (per tab)

Design:

followers

(8)

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #10668 

---
Notes: 
- The total followers is not abbreviated due to [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/10562) (Follower totals are currently only available in string format).
- `View more` shows a temporary alert.

---
To test:

- On a site with WP/Email followers, go to Stats > Insights.
  - Tip: Hogwarts and en.blog are good examples.
- Scroll to `Followers`.
- Verify:
  - The total count is shown on tabs with data.
  - `No data yet` is displayed on tabs with no data.
  - `View more` is shown if there are more than 6 followers.
  - If neither tab has data, the `FilterTabBar` is hidden.
    - Hack tip: to emulate this, in `SiteStatsInsightsViewModel:tabDataForFollowerType`, when it calls `TabData.init`, set `dataRows` to an empty array.

----
followers

---
no_followers

---
no_tab_data

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@SylvesterWilmott -

---
followers

---
no_followers

---
followers

---
followers_2

**Comment by SylvesterWilmott** [comment]
Looks good @ScoutHarris !

Can we make one minor change and that is: If no data exists in both tabs then hide the tabs

**Comment by ScoutHarris** [comment]
@jklausa - I'm marking this 'not ready for review' until I make the change @SylvesterWilmott requested.

**Comment by ScoutHarris** [comment]
@SylvesterWilmott - I've made the requested change. Now, if neither tab has data, the tab bar is hidden. I've updated the description and added a screenshot there.

@jklausa - ready for review sir!

**Comment by ScoutHarris** [comment]
@jklausa - you may notice on rotation the images disappear. It seems to be related to the issue where the hidden views appear on rotation. Ref https://github.com/wordpress-mobile/WordPress-iOS/issues/10707.

**Pull request merged**
