### PR TITLE
Use readable content in Revision diffs

### LINKED ISSUE #11999: Refine Revisions/History layout on tablet
### Currently

At the moment, I'm seeing a couple of issues with our Revision/History viewer layout: 

* The content container is full-width – should match the active editor
* The container doesn't have the same top-margin (when using GB)
* The previous/next arrows aren't vertically centered

I understand that some of these things are slightly different for Aztec vs. Gutenberg – ideally, the layout of the active editor for the post/page should be respected.

#### HTML mode (default view)

IMG_0492

#### Visual mode (default view)

IMG_0494

### Steps to reproduce the behavior

* Open a post/page with multiple revisions
* Tap on `•••` to open menu
* Tap on `History` to open History/Revisions viewer
* In History/Revisions viewer, tap `•••`, to switch between HTML/Visual modes

##### Tested on [device], iOS [version], WPiOS [version]

iPad Pro 10.5", iOS 13 beta 2, WPiOS 12.7 beta

// cc @nheagy @danielebogo and we should also cross-check Android tablet to see if these issues also exist there – Unfortunately, I don't have an Android tablet on me to test. cc'ing those who worked on the Android side – @theck13 @khaykov I think?

### PR DESCRIPTION
**Pull request by danielebogo**
Fixes #11999 

This PR fixes the layout used by the Revision diffs view, using a readable width when the device is an iPad. It also fixes the bottom navigation button alignment.

Simulator Screen Shot - iPad Air 2 - 2019-07-15 at 11 59 07

Simulator Screen Shot - iPad Air 2 - 2019-07-15 at 11 59 09

Simulator Screen Shot - iPad Air 2 - 2019-07-15 at 11 59 15

Simulator Screen Shot - iPad Air 2 - 2019-07-15 at 11 59 17

## To test:
• Open a _post/page_ with multiple revisions
• Tap on `•••` to open menu
• Tap on History to open _History/Revisions_ viewer
• In History/Revisions viewer, tap `•••`, to switch between _HTML/Visual_ modes

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
Looking pretty good – a couple of thoughts.

* The container looks a lot better – is it the same width as its "active" editor (Aztec or GB) container width? It looks a little wide, but hard to tell what the actual width is. Maybe I can snag a build of this to try it out live

This might be a side-issue, but wanted to document:

* I noticed the colors of the labels on the bottom bar (date, +/- count) are different. I'm guessing the +/- counts are using the new grays – if that's the case let's change the date label to the same gray color. Same thing for the divider I think – let's make that a neutral gray that's consistent with other dividers, if possible

**Comment by danielebogo** [comment]
> Is it correct that the bottom navigation arrows fade out when in visual mode?

@frosty yes we kept the same behaviour Android had.

> The container looks a lot better – is it the same width as its "active" editor (Aztec or GB) container width? It looks a little wide, but hard to tell what the actual width is. Maybe I can snag a build of this to try it out live

@iamthomasbishop yes the diff and preview views follow the system readable width, which is 672pt atm. The width it's defined by the system and It's the same property we use in the whole app to make the view readable with the iPad.

> I noticed the colors of the labels on the bottom bar (date, +/- count) are different. I'm guessing the +/- counts are using the new grays – if that's the case let's change the date label to the same gray color. Same thing for the divider I think – let's make that a neutral gray that's consistent with other dividers, if possible

Do you know more or less the shade you want to use? I can change those here

Just to confirm, the component used to render the HTML in Visual Mode is the Aztec text view.

**Comment by frosty** [comment]
@iamthomasbishop Note that the readable width may vary on different devices, even between different size of iPad (I think).

**Comment by iamthomasbishop** [comment]
> Do you know more or less the shade you want to use? I can change those here

@danielebogo I'm not sure – it's hard to know for sure as I'm not sure where that's being defined. I just noticed there is a difference and the date label looks like it's using an old shade.

> Note that the readable width may vary on different devices, even between different size of iPad (I think).

@frosty That makes sense. Thank you!

**Comment by jkmassel** [comment]
👋 I'm bumping this to `13.0` as part of the `12.9` code freeze. If you'd like it released as part of `12.9`, just merge it to `release/12.9` and DM me – I'll be happy to cut a new beta release!

**Comment by danielebogo** [comment]
@iamthomasbishop I modified the label and the stroke using the same _shade 40_

Screenshot 2019-07-16 at 09 05 58

**Pull request merged**
