### PR TITLE
ReaderPostCardCell.xib: Bigger action buttons

### LINKED ISSUE #9549: Bigger tap area for Menu button in the Reader Card
The tap area of the menu button in the Reader card is very small, making it difficult to tap it without opening the post.

screen shot 2018-06-07 at 8 54 32 pm

### PR DESCRIPTION
**Pull request by etoledom**
Fixes #9549 

This is a simple PR that increase the tap area of the action buttons in the reader card, without modifying the vertical visible layout.
This was possible by reducing spaces and margins to compensate for the larger action bar.

The menu button width was also increased trying to make it as close as possible to 44 points without making it too noticeable.

Now all buttons have a height of 44 points, that is the minimum recommended by Apple.
As a result, the menu button went from 24x24 to 34x44:

screen shot 2018-06-07 at 8 46 59 pm

**Old | New**
screen shot 2018-06-08 at 7 46 11 pm
**Diff comparison**
ea6854c25646d922242a8fae27f9e5aa 87mnnlodzvskrwvj3e6u2x01unknpqe1

To test:
- Go to the reader
- `Enjoy` how easer is now to tap the menu button.

cc @nozomimimi

### CODE REVIEW

**Comment by etoledom** [comment]
Updated with some comparison screenshots.

**Comment by frosty** [comment]
Still looks good to me! 👍

**Comment by iamthomasbishop** [comment]
Spacings in the `new` screenshot above look good at a glance, but I want to make sure that the tappable area of each action is ≥ 44x44 (if I'm reading correctly, the above are 34x44). The ones that have number labels can expand to be wider, but we can use 44pt as the minimum. It would look something like this:

screenshot 2018-06-11 09 14 48

**Comment by loremattei** [comment]
Hey! I moved the milestone to 10.4 since 10.3 has been cut. Please, feel free to move it back to 10.3 if it has to land there: just update it to target the release branch and ping me to update the build!

**Comment by etoledom** [comment]
@iamthomasbishop Agreed!

Now all the action buttons will have a minimum width of 44 points, and they will grow accordingly with the text.

I also made the images centered for when they have no text. They used to be aligned left.

screen shot 2018-06-18 at 11 34 53 am

And this is how it looks:
img_0044

**Comment by iamthomasbishop** [comment]
Looking better, one quick thing: The padding on the comments button above (w/ the number label) and star/like button look to have not enough padding on left/right - can we make sure each of the buttons (even those with labels) have 10pt padding on the sides? I think that'll help w/ the visual alignment.

screenshot 2018-06-18 11 53 33

**Comment by etoledom** [comment]
As requested, I increased the space in between action buttons when they have a visible title (for both numbers or action name)

screen shot 2018-06-19 at 10 42 17 am

img_3571

I noticed that with this change, there is not enough room on the thinest screen (iPhone 5/ 5S/ SE) to display correctly all the buttons with big numbers, so for that specific case, we decided to decrease the space in between buttons, but keeping the minimum size to 44x44.

img_0054

@iamthomasbishop Could you take another look please?

**Comment by iamthomasbishop** [comment]
Looking good. As we discussed in dm, the only issue I see is that the right-most button (`•••`) isn't aligned to the right edge of the contents above, but that sounds like more work, so we might want to address that separately.

**Pull request merged**
