### PR TITLE
[Home Page Picker] Adds template to the existing site creation analytics if a template was used

### PR DESCRIPTION
**Pull request by antonis**
Add's the template to the site creation analytics calls.

This is an alternative approach to https://github.com/wordpress-mobile/WordPress-iOS/pull/15377
adding the template information to the `site_created` event and the existing `enhanced_site_creation_success_*` event.

### Skip on site creation
1. Navigate to the Create WordPress.com site
    - My Sites > ➕ > Create WordPress.com site
1.  Select `Skip` on `Choose a Design`
1. Complete the flow
1. **Expect** to see the events
```
enhanced_site_creation_accessed <>
enhanced_site_creation_site_design_viewed <>
enhanced_site_creation_site_design_skipped <>
enhanced_site_creation_domains_accessed <>
enhanced_site_creation_domains_selected <chosen_domain: antonistest80.wordpress.com, search_term: antonistest80>
enhanced_site_creation_success_loading <>
site_created <>
enhanced_site_creation_preview_viewed <>
enhanced_site_creation_preview_loaded <>
enhanced_site_creation_preview_ok_button_tapped <>
```

### Select site design
1. Navigate to the Create WordPress.com site
    - My Sites > ➕ > Create WordPress.com site
1.  Select `Skip` on `Choose a Design`
1. Complete the flow
1. **Expect** to see the events
```
enhanced_site_creation_accessed <>
enhanced_site_creation_site_design_viewed <>
enhanced_site_creation_site_design_selected <template: alves>
enhanced_site_creation_domains_accessed <>
enhanced_site_creation_domains_selected <chosen_domain: antonistest79.wordpress.com, search_term: antonistest79>
enhanced_site_creation_success_loading <template: alves>
site_created <template: alves>
enhanced_site_creation_preview_viewed <template: alves>
enhanced_site_creation_preview_loaded <template: alves>
enhanced_site_creation_preview_ok_button_tapped <>
```

## Additional Context: 

This is a continuation of the work done in the [Home Page Picker Project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Home%20Page%20Picker). 

## PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by antonis** [comment]
I've left this PR based on @chipsnyder's PR https://github.com/wordpress-mobile/WordPress-iOS/pull/15377
to make it easier to track the additional changes.

**Review by mkevins — COMMENTED** [review]
The code looks good if we intend to go this route. :+1:

**Comment by mkevins** [comment]
The code looks correct to me, <s>but I have slightly different events for some reason, and I'm not sure why</s>. Here are the events I observed in each of the flows:

### Site created with a non-blog design

```
🔵 Tracked: enhanced_site_creation_accessed <>
🔵 Tracked: enhanced_site_creation_site_design_viewed <>
🔵 Tracked: enhanced_site_creation_site_design_selected <template: alves>
🔵 Tracked: enhanced_site_creation_domains_accessed <>
🔵 Tracked: enhanced_site_creation_domains_selected <chosen_domain: snaptest154041.wordpress.com, search_term: snaptest154041>
🔵 Tracked: enhanced_site_creation_success_loading <template: alves>
🔵 Tracked: site_created <>
🔵 Tracked: enhanced_site_creation_preview_viewed <template: alves>
🔵 Tracked: enhanced_site_creation_preview_loaded <template: alves>
🔵 Tracked: enhanced_site_creation_preview_ok_button_tapped <>
```

### Site created with a blog design

```
🔵 Tracked: enhanced_site_creation_accessed <>
🔵 Tracked: enhanced_site_creation_site_design_viewed <>
🔵 Tracked: enhanced_site_creation_site_design_selected <template: blog>
🔵 Tracked: enhanced_site_creation_domains_accessed <>
🔵 Tracked: enhanced_site_creation_domains_selected <chosen_domain: snapapp154042.wordpress.com, search_term: snaptest154042>
🔵 Tracked: enhanced_site_creation_success_loading <template: blog>
🔵 Tracked: site_created <>
🔵 Tracked: enhanced_site_creation_preview_viewed <template: blog>
🔵 Tracked: enhanced_site_creation_preview_loaded <template: blog>
🔵 Tracked: enhanced_site_creation_preview_ok_button_tapped <>
```

### Site created with design step skipped

```
🔵 Tracked: enhanced_site_creation_accessed <>
🔵 Tracked: enhanced_site_creation_site_design_viewed <>
🔵 Tracked: enhanced_site_creation_site_design_skipped <>
🔵 Tracked: enhanced_site_creation_domains_accessed <>
🔵 Tracked: enhanced_site_creation_domains_selected <chosen_domain: snaptest154043.wordpress.com, search_term: snaptest154043>
🔵 Tracked: enhanced_site_creation_success_loading <>
🔵 Tracked: site_created <>
🔵 Tracked: enhanced_site_creation_preview_viewed <>
🔵 Tracked: enhanced_site_creation_preview_loaded <>
🔵 Tracked: enhanced_site_creation_preview_ok_button_tapped <>
🔵 Tracked: quick_start_request_dialog_viewed <>
🔵 Tracked: quick_start_request_dialog_button_tapped <type: neutral>
```

<s>Note that the events that directly follow `site_created` are the `*_site_creation_preview_*` events instead of the `*_site_creation_success_preview_*` events, such as `enhanced_site_creation_success_preview_viewed` and `enhanced_site_creation_success_preview_loaded` as described in the related WordPress-Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/13489#issue-528677601.</s>

:man_facepalming: nvm, I just realized that these are in fact different from the preview events prior to site creation, which are:

```
🔵 Tracked: enhanced_site_creation_site_design_preview_viewed <template: blog>
🔵 Tracked: enhanced_site_creation_site_design_preview_loading <template: blog>
🔵 Tracked: enhanced_site_creation_site_design_preview_loaded <template: blog>
```

Looks like we are all good here. Nice work Antonis!

**Review by chipsnyder — APPROVED** [review]
This looks good to me. I think this is a better approach compared to https://github.com/wordpress-mobile/WordPress-iOS/pull/15377

**Comment by antonis** [comment]
As discussed I extended this PR by also adding the template information to the `site_created` event with 29da21924b48d7e3058f1fb7e7b06e5fe18de0c5

**Review by mkevins — APPROVED** [review]
Just tested again, and the site_created event now emits with the correct `template` too:

### Site created with a non-blog design

```
🔵 Tracked: enhanced_site_creation_accessed <>
🔵 Tracked: enhanced_site_creation_site_design_viewed <>
🔵 Tracked: enhanced_site_creation_site_design_selected <template: alves>
🔵 Tracked: enhanced_site_creation_domains_accessed <>
🔵 Tracked: enhanced_site_creation_domains_selected <chosen_domain: snaptest154045.wordpress.com, search_term: snaptest154045>
🔵 Tracked: enhanced_site_creation_success_loading <template: alves>
🔵 Tracked: site_created <template: alves>
🔵 Tracked: enhanced_site_creation_preview_viewed <template: alves>
🔵 Tracked: enhanced_site_creation_preview_loaded <template: alves>
🔵 Tracked: enhanced_site_creation_preview_ok_button_tapped <>
```

### Site created with a blog design

```
🔵 Tracked: enhanced_site_creation_accessed <>
🔵 Tracked: enhanced_site_creation_site_design_viewed <>
🔵 Tracked: enhanced_site_creation_site_design_selected <template: blog>
🔵 Tracked: enhanced_site_creation_domains_accessed <>
🔵 Tracked: enhanced_site_creation_domains_selected <chosen_domain: snaptest154047.art.blog, search_term: snaptest154047>
🔵 Tracked: enhanced_site_creation_success_loading <template: blog>
🔵 Tracked: site_created <template: blog>
🔵 Tracked: enhanced_site_creation_preview_viewed <template: blog>
🔵 Tracked: enhanced_site_creation_preview_viewed <template: blog>
🔵 Tracked: enhanced_site_creation_preview_loaded <template: blog>
```

### Site created with design step skipped

```
🔵 Tracked: enhanced_site_creation_accessed <>
🔵 Tracked: enhanced_site_creation_site_design_viewed <>
🔵 Tracked: enhanced_site_creation_site_design_skipped <>
🔵 Tracked: enhanced_site_creation_domains_accessed <>
🔵 Tracked: enhanced_site_creation_domains_selected <chosen_domain: snaptest154046.wordpress.com, search_term: snaptest154046>
🔵 Tracked: enhanced_site_creation_success_loading <>
🔵 Tracked: site_created <>
🔵 Tracked: enhanced_site_creation_preview_viewed <>
🔵 Tracked: enhanced_site_creation_preview_loaded <>
🔵 Tracked: enhanced_site_creation_preview_ok_button_tapped <>
```

LGTM! :+1:

**Pull request merged**
