### PR TITLE
Feature/9356 gif support in mediapicker preview

### LINKED ISSUE #9356: GIF image animation support Media Picker Preview
### Expected behavior

When picking images in the media picker, and the preview is opened (for a single image or in the carousel preview), all animated gif items should be animated.

### Actual behavior

All animated gif images are shown as static images:

media_picker_gifs

### PR DESCRIPTION
**Pull request by etoledom**
Fixes #9356 

This PR adds animated gifs to the media picker preview, both single image and carousel.
[Here is a video](https://cloudup.com/caR2f0LPnV3) demonstrating this feature.

This feature was added to the Media Picker in the Aztec editor, since is the one place where we use multiple selection, presenting them with the internal Media Picker preview controller and gifs could be present. If I'm missing another place with the same characteristic please let me know! :)

In the Aztec editor, this should work with all the pickers:
- WP Media Gallery Picker.
- Device Media Picker.
- Bottom Media Picker (where the keyboard usually is)

**Note:**
There are [changes in the MediaPicker-iOS](https://github.com/wordpress-mobile/MediaPicker-iOS/pull/300) project that needs to be merged before this.

### To test:

**Preparations**
1. Be sure to have Gifs in your WP Media Gallery.
2. Open Aztec editor.
3. Press `+` to add media items.

**WP Media Gallery Picker**
1. Select the `W` button to select assets from the WP Media Gallery.
2. Select one GIF.
3. Press on `Preview 1`.
4. **Check that the Gif is animating.**
5. Go back and select multiple items: Images, gifs, videos, etc.
6. **Check that all of them show as they should**.
7. Go back to the editor.

**Device Media Picker**
1. Repeat the previous steps but selecting the "on device" assets (The icon of the little image).
2. Go back to the editor.

**Bottom Media Picker**
1. Select a GIF in the bottom picker (where the keyboard usually is).
2. Tap and hold the asset to show the preview.
3. Check that it shows properly.
4. Go back and repeat selecting many items.
5. Check that everything shows correctly.

@bummytime Going back to you with the review 😁
Thank you!

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@etoledom the preview of GIF works fine for GIFs that come from the camera roll, but when I try to preview GIF from the WordPress Library it just show a black screen. 

You can scroll to other other items in the preview and if they are regular photos or videos they show ok, but the GIFs just show a black screen. Again this is only for GIF on the Wordpress Library.

**Comment by SergioEstevao** [comment]
I also found other problems with the GIF preview implementation I'm not sure if they are part of this PR, but here is a list:

 - If you select an animated GIF as the featured image of the post, then PostSetting screen is unable to display it, and then we also cannot remove it or change it after a GIF is set.
 - If you add/upload animated GIFs on the Media Library screen of the post, while they show perfectly, when you tap on them to Edit them the Media Details screen is unable to preview the animated GIF on the top of the screen.

**Comment by etoledom** [comment]
Thanks @SergioEstevao for checking this out!
I'm trying to reproduce the error and I might know what is happening, but not yet why.

While most of the gifs images on my WordPress Library work perfectly, I found one that is not working and behaves as you describe:

img_3575

That asset won't display in the picker, it won't display in the preview (showing the black screen) and also won't work with the post featured image (exactly as you described).

I also noticed that even in Calypso this won't display correctly:

screen shot 2018-06-20 at 9 09 41 am

screen shot 2018-06-20 at 9 10 18 am

But when I copy/paste the direct URL, the gif shows and it animates properly:
`https://mysitefortestingetoledom.files.wordpress.com/2018/05/t-rex.gif`
Gif

Could you please check that this is the same case for you? 
If it is, I think the problem is on the `Photon` API we use to resize the images.

Thank you!

**Comment by etoledom** [comment]
@SergioEstevao - I found another possible cause for this:

When a gif is uploaded from the device library, it will try to load the new media item from the local URL. With the new integration of `Photon`, it was trying to add the `Photon` parameters to the local URL and then it failed the loading.

Hopefully this last commits will fix that issue!

**Comment by SergioEstevao** [comment]
@etoledom this is working great now! I give it my approval functionality wise, I will let @bummytime check the code :).

**Pull request merged**
