### PR TITLE
Notification Likes list: show site row in user profile bottom sheet

### PR DESCRIPTION
**Pull request by ScoutHarris**
Ref #16244 

This adds a new Site cell and displays it in the Site section of the User Profile bottom sheet. It's showing stub values for now. Fetching and showing real site info will be in a future PR. The bottom sheet should render correctly on iPhone in portrait and landscape.

To test:
- Enable the `newLikeNotifications` feature.
- Run on an iPhone. (It will show on an iPad, just not in the right place.)
- Go to Notifications > Likes and tap a notification.
- Tap a user.
  - Verify a Site row is displayed in the Site section.
  - Verify the sheet is partial height in portrait.
  - Verify the sheet is full height in landscape.
- Disable the `newLikeNotifications` feature.
- Go to Notifications > Likes and tap a notification.
  - Verify tapping the user opens the user's site.

---
| light_port | dark_port |
|--------|-------|
| light_land | dark_land |

---

## Regression Notes
1. Potential unintended areas of impact
N/A. Feature is incomplete.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A. Feature is incomplete.

3. What automated tests I added (or what prevented me from doing so)
N/A. Feature is incomplete.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @mattmiklic . Could you take a look at the Site row please? Here's what I've used.

Site Icon: 
- 40 x 40

Site Name:
- `subhead` font
- `label` color

Site Url:
- `footnote` font
- `secondaryLabel` color

**Review by aerych — APPROVED** [review]
Howdy @ScoutHarris 👋 
Looking good :)  :shipit:  from me!

**Review by mattmiklic — APPROVED** [review]
Super, super close on the design. Just three small nits to pick, if you can:

- 1pt additional space between profile text and Site header
- Move Site Name up by 1pt
- 1pt additional space between Site Name and siteurl.wordpress.com.

That would look like this:
Screen Shot 2021-04-13 at 2 01 47 PM

Otherwise it's right on the money.

**Comment by ScoutHarris** [comment]
Thanks @mattmiklic ! Will do!

**Pull request merged**
