### PR TITLE
Update media editor version.

### LINKED ISSUE #4003: App crashes when selecting the media library on the media editor
This was reported on wordpress forum with this details:

> 1. WordPress is allowed access to Photos.
> 2. Shared Photo Streams are on
> 3. iCloud Photo Library is on
> 4. Connecting to a self-hosted site
> 
> When I tap the little photo icon in a post (trying to add a photo to a post), it displays the new controller and a progress indicator for a few seconds (usually about 15-20 seconds). It then crashes. I suspect it's loading data of some sort, and when that load is complete, whatever happens afterward crashes the app.
> 
> I have:
> 
> 1. Deleted the site and re-added the site.
> 2. Deleted and re-installed the app.
> 3. Tried toggling access to Photos.
> 
> I will attach a crash log in a bit but can't get to it currently. I am traveling, the WP iPad app is critical to my travel writing, as are my photos, and I can't attach them!
> 
> Thanks.

> It seems to be a memory issue. I will post the kill log below, but it's not a proper crash log as the "crash" is due to the process being killed by iOS/jetsam. The log may give some hints about where the memory exhaustion started though. Maybe too much, either from the network or the photo library, is being processed in one giant chunk. Obviously it's hard to say.

> The library is big, approximately 15,000 photos.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Closes #4003

How to test:

Get a device with a big media library: more than 5000 photos
Create or Edit a post
Click on the media icon
Check if the app doesn't crash and/or the total memory being used is not spiking. You can use the the debug session tab on Xcode.

Needs Review: @aerych

### CODE REVIEW

**Comment by aerych** [comment]
Everything looks good as far as I can see.  I don't have a device with anything close to 5000 photos (closer to 200 max) so I might not be able to perform the best test.  Should we ping someone else?

**Comment by SergioEstevao** [comment]
@aerych thanks for testing but I found some bugs from this change, so I will do some fixes to this and ping you and others to test it again.

**Comment by SergioEstevao** [comment]
@aerych, ready for another round of review.
@astralbodies, @sendhil, @diegoreymendez if any of you have a device media library with a lot of photos (5000 or more) I appreciate some tests using this branch.

**Comment by aerych** [comment]
Hi @SergioEstevao.  I took the branch for another spin and still couldn't reproduce the crash. 

I did notice a few other things but I'm not sure if they are relevant to this PR. I'll document here in case. 

- I noticed when I switch to the media library, the UI is responsive during the first sync of images. However, if I pull to refresh the UI is non responsive until the refresh is complete. 
- I never saw the media library show a final image count in the dropdown. It always said it was counting. 

To be super thorough I took the branch for a test drive in the profiler checking allocations and leaks.  I noticed that while memory never really spiked, there was a definite increase over time as I opened the media library, synced, scrolled, pulled to refresh, dismissed, etc. I eventually had >100megs in persistent memory and > 30megs of png assets, apparently just from interacting with the library.  It didn't decrease after closing the editor and returning to the blog list. 
Leaks shows something was going on in `WPAndDeviceMediaLibraryDataSource initWithPost:`.  Screen shots below: 
#### leaks
screen shot 2015-07-13 at 11 34 45 am

#### allocations after opening the media library a few times
screen shot 2015-07-13 at 11 35 08 am

#### after opening several more times. 
screen shot 2015-07-13 at 11 26 06 am


These things aside the PR accomplishes it task, so :shipit:  from me.

**Comment by SergioEstevao** [comment]
I incorrectly merged develop on this branch so I'm closing it and recreate it.

**Comment by SergioEstevao** [comment]
@aerych Thanks for the deep analysis! I add a look on the leak and I think I found the reason. Regarding the allocations of images I think some caching is going on for the downloads of images, I will double check it on another issue.

**Pull request closed without merging**
