### PR TITLE
Basic Background on Signup Header/Footer

### LINKED ISSUE #16073: Signup: gray background shouldn't appear behind grouped table header and footer.
On the account confirmation screen (epilogue), there is a gray background behind the Account Details header and password footer. These elements should not have a background color of their own (it should be white in light mode, black in dark mode).

IMG_4437
IMG_4438

This is in version 16.8.

### PR DESCRIPTION
**Pull request by illusaen**
Adds `.basicBackground` to signup's header and footer cells.

Fixes #16073

To test:
1. Sign up for new WordPress account.
2. Note that header and footer cells on confirmation page have background that match the rest of the page.
3. Switch to dark mode.
4. Confirm that same thing happens.

### Screenshots
| Before | After - Light | After - Dark
| - | - | - |
|  |  |  |

PR submission checklist:
- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mattmiklic — COMMENTED** [review]
Hi @illusaen -- this definitely looks better, thanks!

I noticed one thing; the Password hint text seems to be shifted over in the "after" screenshot, but only in light mode. I haven't had a chance to look at a build on my device yet, could you double-check that that's displaying correctly?

**Comment by illusaen** [comment]
> Hi @illusaen -- this definitely looks better, thanks!
> 
> I noticed one thing; the Password hint text seems to be shifted over in the "after" screenshot, but only in light mode. I haven't had a chance to look at a build on my device yet, could you double-check that that's displaying correctly?

Oh you're 100% right; I didn't even notice that. I'll take a look!

**Comment by jkmassel** [comment]
👋 We're cutting the `17.1` release today, so this PR's milestone will be updated to `17.2`!

**Comment by illusaen** [comment]
Closing this for now because other priorities rose up.

**Pull request closed without merging**
