### PR TITLE
More unit tests for our REST service classes.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Follow up to [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/3808).

This PR adds several tests for:
- AccountServiceRemoteREST.
- BlogServiceRemoteREST.
- PostServiceRemoteREST.

**How to test:**
- Run the unit tests and make sure the newly added tests all succeed (at the time of this writing there are a few unrelated broken tests coming from `develop` which are outside of the scope of this PR).

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Please review: @SergioEstevao, @sendhil, @astralbodies

**Comment by astralbodies** [comment]
I'm not entirely sure testing for the parameter asserts being thrown is useful. While I get why we're doing it, its not testing the logic of the underlying function. This is short circuiting production behavior for the sake of a something that only happens in debug and internal builds. 

I think if we're going to unit test a method we should be testing how it actually deals with the extraneous condition or make the solid conclusion that if it has a parameter assert we don't NEED to test for that condition. 

The problem I have with asserts being used for parameter sanity is that its not defined in our contract (the method declaration) that nil is acceptable. I guess this is where Swift comes in with optionals. But in any case if we're going to stick solid with unit testing principles we shouldn't be testing for something that only occurs when we're debugging. If the parameters are in fact required to the point where stuff is going to break BAD or be in an inconsistent state, we need to throw an exception that is always thrown.

**Comment by diegoreymendez** [comment]
The method documentation should definitely state what parameters can be nil and which ones can't be nil - so that's a very valid point.  I'll modify this PR to add notes for that.

But setting aside the lack of documentation, unit tests are also meant to test the preconditions for running a unit of code.  If we decided to ignore our pre-conditions we'd basically be ignoring half our test cases.

As a simple example: If someone broke an assertion by mistake that's something we'd surely want to know - even if we're lucky enough never to hit that case.  Removing these tests would offer us no gain, whereas it would definitely add some risk.

**Comment by astralbodies** [comment]
The problem is the precondition is conditional - so testing for it is tricky. If I decide to run the unit tests against the Release configuration (which they should be FWIW) the tests will fail.

**Comment by diegoreymendez** [comment]
Well, the preconditions per-se are not conditional logic-wise in release builds, what is conditional are the assertions checks (since the compiler removes them).

Do we run the unit tests against release builds?

If that's the case I wouldn't mind wrapping these tests up in `#ifdef DEBUG` - but I'd definitely keep them for debug runs.

**Comment by astralbodies** [comment]
Yeah I'm sorry the assertion checks are conditional is what I meant to say.  Been a long day :smile:.

I'm wondering if we can do something better like a custom assertion handler or something like it. 

I don't want to hold up this PR - this works for now. Something to consider for the future. If something is important enough for us to do parameter assertions we should probably throw and catch exceptions in code or make sure we're guarding against it properly in the flow.

**Comment by diegoreymendez** [comment]
Well I had never considered the unit-testing in release scenario so this has been productive for me.

Aaron, as a side note: I just noticed that the assertions being enabled is not dependent on the precompiler's `DEBUG` symbol but on `NS_BLOCK_ASSERTIONS`.  This means it'd also be possible to unit-test in release with assertions if necessary by either changing that setting momentarily or by creating a different configuration.

Whereas we want to do that or not is a different discussion though, heh.

**Comment by diegoreymendez** [comment]
A final note.  The cool thing about having these tests and assertions is that it suddenly becomes easier for us to know if a modification we make to the internal logic of a method also affects it's public interface in some way.  This means that refactoring code becomes easier, and that the developer that refactors code is more aware of what he's trully changing.  Makes sense?

**Comment by SergioEstevao** [comment]
Good to have more tests on the Rest API. :shipit:

**Comment by diegoreymendez** [comment]
@astralbodies - Just added documentation for the tested methods to clearly specify the preconditions for parameters.  Can you give it a look to see if that looks better?

I was also going to make changes to take into account the `release` vs `debug` differences we chatted about yesterday, but I think they'd add complexity to this PR and it'd be better if I treat that separately.  I'll probably go the route you suggested about a custom/intelligent assertion handler.

**Comment by jleandroperez** [comment]
Looks great Diego! :shipit:

**Comment by diegoreymendez** [comment]
All right, thanks.

**Pull request merged**
