### PR TITLE
Dashboard Cards: Track activity log events

### LINKED ISSUE #20451: Dashboard Cards: Implement Track events for the Activity Log card

### PR DESCRIPTION
**Pull request by momo-ozawa**
Closes #20451

## Description
Adds tracking for the activity log dashboard card

## How to test
1. Enable the activity log card remote feature flag via the debug menu
2. Switch to a site that has activity log enabled
3. Run and build the app
4. ✅ `my_site_dashboard_card_shown <blog_id: id, site_type: blog, type: activity_log>` is tracked
5. Tap on the card header
6. ✅ `activity_log_list_opened <tap_source: activity_card_header>` is tracked
7. Go back to the dashboard
8. Tap on an activity item
9. ✅ `my_site_dashboard_card_item_tapped <blog_id: id, site_type: blog, type: activity_log>` is tracked
10. Go back to the dashboard
11. Tap on the ellipsis button
13. ✅ `my_site_dashboard_contextual_menu_accessed <card: activity_log>` is tracked
14. Tap on the "All activity" button
15. ✅ `activity_log_list_opened <tap_source: activity_card_context_menu>` is tracked
16. Go back to the dashboard
17. Tap on the ellipsis button
18. Tap on the "Hide this" button
19. ✅ `my_site_dashboard_card_hide_tapped <card: activity_log>` is tracked

## Regression Notes
1. Potential unintended areas of impact
n/a

20. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a

21. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] VoiceOver.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] iPhone and iPad. 
- [x] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by hassaanelgarem — COMMENTED** [review]
Works as described!

However, I noticed a couple of actions that are not tracked.
- Tapping the card header to display the full activity list
- Tapping "Recent Activity" in the context menu

I think we can either add new events for them, or add a source property in the `activity_log_list_opened` event. What do you think?

**Comment by momo-ozawa** [comment]
> add a source property in the activity_log_list_opened event

@hassaanelgarem Good suggestion - fixed!

**Review by hassaanelgarem — APPROVED** [review]
I noticed that when we tap on an activity item from the card, an `activity_log_detail_opened` event is fired with the source being "unknown". I suggest changing this to something like `activity_card` or `dashboard`.

Other than that, all works as described 🚀

**Comment by momo-ozawa** [comment]
@hassaanelgarem Thanks for catching that! Fixed in 462487c

**Pull request merged**
