### PR TITLE
Media Picker: Prevent crash if no error is provided when picking media

### LINKED ISSUE #14958: EXC_BAD_ACCESS: delegate > emptyViewControllerForMediaPickerController: > mediaPickerController:handleError: > re...
**Sentry Url**: https://sentry.io/share/issue/44064e4cd9964f09a5ff497b6a90970f/
**User Count**: 643
**Count**: 1347
**First Release**: 15.5.0.3
**First Seen**: 2020-08-13T12:01:15Z
**Last Seen**: 2020-09-22T04:34:26Z
**24 Hours**: 81
**30 Days**: 1344
**LogID:** 7E14087A-C7D1-4093-BA54-E5EB92A62DDA

```
EXC_BAD_ACCESS: delegate > emptyViewControllerForMediaPickerController: > mediaPickerController:handleError: > re...
  File "MediaLibraryViewController.swift", line 600, in MediaLibraryViewController.mediaPickerController
  File "MediaLibraryViewController.swift", line 600, in MediaLibraryViewController.mediaPickerController
  File "<compiler-generated>", line null, in MediaLibraryViewController.mediaPickerController
  File "<compiler-generated>", line 599, in MediaLibraryViewController.mediaPickerController
  File "WPMediaPicker/Pod/Classes/WPNavigationMediaPickerViewController.m", line 221, in -[WPNavigationMediaPickerViewController mediaGroupPickerViewController:handleError:]
  File "WPMediaPicker/Pod/Classes/WPMediaGroupPickerViewController.m", line 88, in -[WPMediaGroupPickerViewController showError:]
  File "main.swift", line 7, in main
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by frosty**
Fixes #14958. Associated Media Picker PR: https://github.com/wordpress-mobile/MediaPicker-iOS/pull/360

**To test**

- Build on iOS 14
- Visit the Media Library, choose +, tap Choose From My Device, then Select More Photos (or Select Photos if this is the first time you've run the app). Ensure that no photos are selected and tap Done.
- The media picker should be displayed with no content, and the app should not crash.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by diegoreymendez — CHANGES_REQUESTED** [review]
@frosty - Feature works.

I found what I believe is an issue, that I'd consider addressing in this PR (please let me know if you feel otherwise):

Permissions to access my photos were requested at the (I believe) wrong time.  Right after tapping "+" but before I chose "From my device".  I think this can be confusing if you're planning to add images from other sources.

And some potential space for UX improvement (not necessary for this PR, just a thought):

If you select to only share some photos, it can be hard to figure out how to add more.  I realize this is an iOS thing, and not our fault... but maybe we can consider hints to let the user know how to add more local photos after they first selected a few?

hint

**Comment by diegoreymendez** [comment]
Hey @frosty - I just realised you're fixing a crasher there.  The issue I found is quite minor in comparison with a crasher, so I'm good with approving this if you want to move ahead and merge.  We can tackle what I found separately.  Can you let me know?

**Comment by frosty** [comment]
Thanks Diego! I agree with both of those issues – the first is a pre-existing issue that we should definitely adjust, and the second we should add if we can't adopt the new system picker (which doesn't need these new permissions). I noticed that Messenger does similar: image

**Comment by frosty** [comment]
Closed, favouring #15021

**Pull request closed without merging**
