### PR TITLE
Site Monitoring: Implement WebKit-based Metrics view

### PR DESCRIPTION
**Pull request by kean**
Reimplement Metrics view using `WebKitViewController`.

Out of all the `WKWebView` wrappers in the app, I found the `WebKitViewController` works best for our use case. There are also `WPWebViewController` and `BlazeViewController,` but the former missed `custom user agent`, and the latter is Blaze-specific, at least in the name.

To test:

- Uninstall the app or logout
- Log in and select an Atomic site
- Verify the Metrics are loading

**Note**: I noticed an (existing) performance [issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/22497) with web views – will investigate it later if time allows.

**Known Issues**: No dark mode or dynamic type support.

Simulator Screenshot - iPad (10th generation) - 2024-01-29 at 13 19 57

## Regression Notes
1. Potential unintended areas of impact: Site Monitoring
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual
3. What automated tests I added (or what prevented me from doing so): n/a

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by momo-ozawa — COMMENTED** [review]
When I force quit then reopen the app, I have to login again to see the metrics webview.

Also, feel free to delete WebView.swift, as it's no longer needed. Thanks for implementing WebKitView 🙇‍♀️

**Comment by kean** [comment]
> When I force quit then reopen the app, I have to login again to see the metrics webview.

Hmm, I couldn't reproduce it. Are there more steps? Are you sure you are not running using the proxy?

> Also, feel free to delete WebView.swift, as it's no longer needed. Thanks for implementing WebKitView 🙇‍♀️

Done.

**Review by momo-ozawa — APPROVED** [review]
Turned off the proxy - that was it!

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/269">24.2</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
