### PR TITLE
Fixed an issue introduced in a previous PR.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/3629).

How to test:
1. Run the app.
2. Go to Me / Help and check the logs are showing up.

/cc @astralbodies

### CODE REVIEW

**Comment by astralbodies** [comment]
@diegoreymendez probably want to remove this property from the class extension 

https://github.com/wordpress-mobile/WordPress-iOS/blob/issue/3629-broken-logger/WordPress/Classes/System/WordPressAppDelegate.m#L79

**Comment by diegoreymendez** [comment]
@astralbodies - It's actually intended: it's `readwrite` there so it can be instantiated by the class.  It's set to `readwrite` in the header so outside code can't modify it.

**Comment by astralbodies** [comment]
@diegoreymendez I obviously haven't had enough :coffee:. 

:shipit: :smile:

**Comment by diegoreymendez** [comment]
Thank you, Sir!

**Pull request merged**
