### PR TITLE
Create Modal Layout Picker Container for new Gutenberg pages and feature flag for development

### LINKED ISSUE #2419: [Modal Layout Picker] Create Modal window for Modal Layout Picker
### Is your feature request related to a problem? Please describe.
This task is part of the effort to rework the Starter Page Template Picker for new pages. This part of the initiative will focus on creating the base modal for the new Modal Layout Picker. Other tasks will then work off of the modal created in this task. It will also handle the feature flags to set up the build environments to enable the development and building of the new modal.

The goal will be to create a UI that looks something like:

| iOS | Android |
| --- | --- | 
| iOS-Container | Android-Container |

### Goals - Modal Container
+ When creating a new page, a modal should display with the following items:
    + Title
    + Subtitle
    + "Create Blank Page" Button
    + A button for dismissing the modal. 
    + These items should be styled for Light and Dark interfaces. 
+ Selecting the "Create Blank Page" button should create a new blank page.
+ Selecting the "X" (iOS) or Up button (Android) should dismiss the modal.
    + Android should validate the back button works as expected for dismissing the modal.
+ Swiping down on the modal should dismiss the modal. 

### Goals - Feature Flag
+ Selecting the Create page should only show this new modal when running:
    + iOS build configurations: `localDevelopment` and `a8cBranchTest`.
    + Android build configurations: `vanilla` and `jalapeno`.
+ Opening the editor **should not** show the existing STP picker if the modal **has** been shown
    + We can pass the feature flag to RN as part of capabilities ([iOS](https://github.com/WordPress/gutenberg/blob/7532a485b400f86638145b71f94f6f717e5add25/packages/react-native-bridge/ios/GutenbergBridgeDataSource.swift#L43), [Android](https://github.com/WordPress/gutenberg/blob/7532a485b400f86638145b71f94f6f717e5add25/packages/react-native-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java#L470))
    + The key to pass as part of the capabilities should be `modalLayoutPicker`. `true` would mean the app supports modal layout picker
+ Opening the editor **should** show the existing STP picker if the modal **has not** been shown

### Additional context
+ Creating a new page can happen from:
    + The FAB button on the bottom right of the site's home screen
    + The ➕ on the top right on the "Pages" screen in iOS or the FAB button on the "Pages" screen in Android

<details>
<summary>Blueprint Flow - iOS</summary>

</details>

<details>
<summary>Blueprint Flow - Android</summary>

</details>

### PR DESCRIPTION
**Pull request by chipsnyder**
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2419

Related PRs:
- `gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2478
- `gutenberg`: https://github.com/WordPress/gutenberg/pull/23872

## Description
Adds feature flags and a container view for creating a new modal layout 

## To test:
<details>
<summary>To disable or enable the development version of Modal Layout Picker</summary>

- Open the app from the build https://github.com/wordpress-mobile/WordPress-iOS/pull/14456#issuecomment-656759183 or a local development build
    - By default, the modal layout picker will be enabled.
    - From the site page:
        - Click on your Gravatar.
        - Click on App Settings.
        - Click on Debug.
        - Toggle "Gutenberg Modal Layout Picker" to enable or disable the picker
            <details>
            <summary>To toggle:</summary>
            
            </details>
</details>

- Steps to test the Gutenberg side of the modal layout picker toggle can be found in https://github.com/WordPress/gutenberg/pull/23872

### Classic Editor and Gutenberg Editor with Modal Layout Picker Disabled.
**Note:** Modal Layout Picker should be disabled and uneditable in any Release build
- Create a new page from My Site
    - Create a new page by clicking on the Floating Toolbar Button on the My Site Page then select "Site Page"
    - Expect to see the page editor without being prompted with the new modal layout picker
- Create a new page from Pages
    - Create a new page by clicking on the ➕ on the Pages screen
    - Expect to see the page editor without being prompted with the new modal layout picker

### Gutenberg Editor with Modal Layout Picker Enabled
- Create a new page from My Site
    - Create a new page by clicking on the Floating Toolbar Button on the My Site Page then select "Site Page"
    - Expect to see the modal layout picker container
    - Select "Create Blank Page"
    - Expect to see the page editor
- Create a new page from Pages.
    - Create a new page by clicking on the ➕ icon on the Pages screen.
    - Expect to see the modal layout picker container
    - Select "Create Blank Page"
    - Expect to see the page editor

### On the Modal Layout Picker
- Selecting the ✖️icon in the top right-hand corner should close the modal without creating a page.
- Swiping down around the "Grip" in the top middle of the modal should close the modal without creating a page.
    <details>
        <summary>Dismissing the modal</summary>
        
    </details>
- Scrolling up in the stubbed rows should collapse the header. Collapsing the header should:
    - Minimize the title
    - Hide the prompt
    - Leave space for adding the category bar in the future.
- Scrolling down in the stubbed rows should reset the header when reaching the top.
    <details>
    <summary>Continuing to scroll down after reaching the top should dismiss the modal</summary>
        
    </details>
- Toggle Dark mode and check the style seems consistent with other views

## Screenshots:
| Container | Collapsed Header | Dark Mode |
| --- | --- | --- |
|  |  |  |

## PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by chipsnyder** [comment]
Hey @iamthomasbishop 
When working on this I also took some time to work with the collapsable header. When adjusting how it collapses I was able to configure how it worked a bit by making it a "slower" scroll and by making it more "snappy." I kind of liked both but wanted to see your feelings. I created a debug toggle to allow you to play with each. When you get some time will you take a look and see if you prefer one or the other. 
<details>
<summary>Toggle "Snappy" collapse</summary >

</details>

I think on the "slower" scroll I would want it to set into fully open or fully collapsed at the end of the scroll but let me know.

Here are a few GIFs but I think it's hard to tell the difference with out "feeling" it.
| slow | snappy |
| --- | --- |
|  |  |

**Comment by iamthomasbishop** [comment]
Nice work @chipsnyder — really cool to see this in action. The header transition feels a bit awkward, both with the toggle on and off. I think I would expect that the header would scroll 1:1 with the page and then become fixed once the large title is near the top of the sheet.

Do we by any chance have access to the “standard” navigation bar transition that you see on most of Apple’s apps that have large titles, (a couple of examples: Apple Music, Notes, Mail)? If so, can we just follow that behavior?

**Comment by chipsnyder** [comment]
> The header transition feels a bit awkward, both with the toggle on and off.

Yeah, I agree they both could use some refinement to feel just right. 

> Do we by any chance have access to the “standard” navigation bar transition that you see on most of Apple’s apps that have large titles, (a couple of examples: Apple Music, Notes, Mail)? If so, can we just follow that behavior?

Their transition is built into the navigation bar, so if we used that directly, our title would be left-aligned, and the subtitle or "prompt" would be above the title. 

That can give me more of a direction to go in for the refinement. When in large title mode and scrolling up the standard behavior with the title is:
- The text scrolls "under" where the "collapsed" header would be. 
- After the text has scrolled away completely the smaller font title appears
- As soon as the text starts to appear again, the smaller font title disappears. 

For mimicking that behavior with a prompt text below the title (which Apple gets around by forcing it over the title), I feel like we would follow the same behavior by showing the smaller font title and then just scroll the subtitle off. 

Let me know if that doesn't sound like what you'd want but I can adjust my implementation to mirror this and make a new build for you to play with.

**Comment by iamthomasbishop** [comment]
> Their transition is built into the navigation bar, so if we used that directly, our title would be left-aligned

Ok, that makes sense about the navigation bar, and I can live with left-aligning the title label.

> the subtitle or "prompt" would be above the title.

Not quite sure what you mean by "above" here. Do you mean it'd be above the navigation bar on the z-index? Wouldn't the subtitle be on the main scrollable surface with the rest of the content? I think that's the behavior that you're referring to here 👇 , correct?

> For mimicking that behavior with a prompt text below the title (which Apple gets around by forcing it over the title), I feel like we would follow the same behavior by showing the smaller font title and then just scroll the subtitle off.

**Comment by chipsnyder** [comment]
>Not quite sure what you mean by "above" here. Do you mean it'd be above the navigation bar on the z-index?

We discussed this in another thread but wanted to capture it here in case others had the same question. I actually meant on the y-axis so using the native controls we'd have:

| Large title | Small title |
| --- | --- |
|  |  |

> Wouldn't the subtitle be on the main scrollable surface with the rest of the content?

The way it was in the build you originally played with I had everything in the scrollable area. I do think there is some room with the not "snappy" version to get more of that 1:1 scroll behavior you mention. 

I put together a build that has the native controls though so you can get a feel for that. With this approach though I cut out the "sticky" category bar because adding that in results in a need to handle the original question of "how do we want the scroll to feel." This build does have some UI work to do (like the separator bar on the navigation controller should probably be hidden in large title mode). Personally I think we can get a better transition by not using the native controls but I'll leave that up to what you think. 

Here's the updated build with the default UI components:
https://appcenter-filemanagement-distrib2ede6f06e.azureedge.net/e1b0452b-bd8d-43ba-b817-769a0120cd27/WordPress%20Alpha.ipa?sv=2019-02-02&sr=c&sig=llPOowJ2wFB9j4wlTRLfd%2FdovXsnvbCej9cE023OB5s%3D&se=2020-07-15T20%3A01%3A41Z&sp=r

**Comment by iamthomasbishop** [comment]
For transparency, as mentioned in DM here are some notes from a review I did over the weekend:

The layout is feeling a lot better already. I jotted down a few notes as I tested the build, but I think it’s getting pretty close.

## Navigation Bar

- The scroll pace when you initially start scrolling up seems a little jumpy — either faster than 1x or it is snapping too quickly. It seems to me like it’s related to the pacing, because if you try scrolling very incrementally, the collapse is gradual. ([video](https://cloudup.com/cWCWDKInHtI))
- Is it possible to override the default text-alignment of the navigation bar component? If so, let’s center that label. If it’s a pain, let’s leave it left-aligned and change the subtitle to also align left.

## Subtitle/Filter Toolbar

- There is an oddity when you are scrolled down the sheet a bit and quickly swipe down, the title bounces “over” the description ([video](https://cloudup.com/cG8XRGblnpj)). Is it possible to get the subtitle and filter bar to continue scrolling with the rest of the container in this case?
- If we can’t do that, the easiest way to solve this might be to give the Navigation Bar background a system material (Chrome?) so that when it does fly over the top of the description, the translucency allows the content below the title to shine through a little bit.
- Speaking of system materials, regardless of how we tackle the scrolling issues, we will also want to apply the same system material background to the filter bar, as well as the footer bar.

## Close Button

- Where is our “close” icon on the top right of the sheet coming from? The colors look right, but the “x” feels maybe slightly lighter than what I’m seeing on most system apps. ([comparison](https://cloudup.com/cyAVM3v8C1L): WP alpha vs. Pages, other system apps)

**Comment by chipsnyder** [comment]
Thanks again for the feedback on this @iamthomasbishop! I spent yesterday looking into these and here's what I have so far:

---- 

## Navigation Bar
>The scroll pace when you initially start scrolling up seems a little jumpy — either faster than 1x or it is snapping too quickly. It seems to me like it’s related to the pacing, because if you try scrolling very incrementally, the collapse is gradual. (video)

I did some testing on this and tracked down several different suggestions, and combinations from different threads ([[1]](https://stackoverflow.com/q/48039046/1350218), [[2]](https://stackoverflow.com/q/52171774/1350218), [[3]](https://stackoverflow.com/q/55919318/1350218), [[4]](https://stackoverflow.com/q/44448145/1350218), [[4]](https://stackoverflow.com/q/46703469/1350218), [[5]](https://developer.apple.com/forums/thread/86151)) unfortunately none of them seemed to work to remove the snappy feeling.

The one solution I could find with using Apple's transition was to switch the presentation from page sheet to full screen; doing this allowed the view to work as expected.  

| Page sheet | Full Screen |
| --- | --- |
|  |  |
> Is it possible to override the default text-alignment of the navigation bar component? If so, let’s center that label. If it’s a pain, let’s leave it left-aligned and change the subtitle to also align left.

We can "technically" do this by setting the [titlePositionAdjustment](https://developer.apple.com/documentation/uikit/uinavigationbarappearance/3198038-titlepositionadjustment), but this is more for making minor horizontal adjustments for font and not for centering the text. So I for maintainability, I would say we should just left-align the subtitle.

## Subtitle/Filter Toolbar
>There is an oddity when you are scrolled down the sheet a bit and quickly swipe down, the title bounces “over” the description (video). Is it possible to get the subtitle and filter bar to continue scrolling with the rest of the container in this case?

This bounce is something that's the result of not having the scrollable section (the subtitle and category bar) be a part of the navigation controller. I tried a couple of things like making the bar transparent and turning off the bounce on the scroll. Each of those solutions didn't solve it, nor is there a documented flow to prevent this.  

>Speaking of system materials, regardless of how we tackle the scrolling issues, we will also want to apply the same system material background to the filter bar, as well as the footer bar.

The footer bar does have the transparency on it right now, but it's hard to see with a white background of the cells. 

## Close Button
> Where is our “close” icon on the top right of the sheet coming from? The colors look right, but the “x” feels maybe slightly lighter than what I’m seeing on most system apps. (comparison: WP alpha vs. Pages, other system apps)

I'm currently using [cross-small](https://github.com/Automattic/gridicons/blob/master/pdf/gridicons-cross-small.pdf) from the GridIcons library. Since SF-Symbols are exposed in iOS 13, we could use that x-mark instead. The icon would just be a bit different on iOS 13 vs. iOS 12.  

---- 

## Overall thoughts

From those pieces of feedback, I think we would be able to solve those design issues if we went back to [Build: 31570](https://appcenter-filemanagement-distrib4ede6f06e.azureedge.net/b9f5c7d1-6cf0-4640-baf4-1d3df881ea01/WordPress%20Alpha.ipa?sv=2019-02-02&sr=c&sig=PBCEqnymWBek7YUILqhaA7MNAvIt1rCyRXDLBcBusoo%3D&se=2020-07-16T18%3A33%3A03Z&sp=r ) and tried to identify the areas where that feels off instead of investing the time in working around some of these bugs with page sheet and large title transitions. Because that way, we would have all of the control in the header instead of trying to manipulate Apple's navbar.

What are your thoughts?

**Comment by chipsnyder** [comment]
Closing this PR in favor of the approach in https://github.com/wordpress-mobile/WordPress-iOS/pull/14501

**Pull request closed without merging**
