### PR TITLE
Add defensive code for PostCategory save

### PR DESCRIPTION
**Pull request by kean**
I don't want to say that it fixes the issue https://github.com/wordpress-mobile/WordPress-iOS/issues/21138 entirely, but there was a recent spike in production in these crashes, and it adds some basic defensive and monitoring code.

The assumption is that it is a faulty plugin or misconfiguration on some sites that leads to invalid responses (more details in https://github.com/wordpress-mobile/WordPress-iOS/issues/23352#issuecomment-2165918514). The options in this scenario are limited. The app definitely can't simply crash. I think it's acceptable if it will still display the post but maybe fail to display some of the categories. I also focused on keeping the changes to the minimum since this PR targets the release branch.

## To test:

- Put breakpoint on line  `let category = PostCategory(context: context)`
- Open Post List in the app
- Open wp-admin and open one of the existing posts
- **Test 1**
  - Add a new category to a post (one with and one without a parent)
  - Refresh the post list in the app
  - ✅ Verify that the breakpoint was hit
  - Open Post Settings for the post
  - ✅ Verify that the new categories are displayed
- **Test 2**
  - Add an _existing_ category to the post
  - Refresh the post list in the app
  - ✅ Verify that the breakpoint was NOT hit
  - ✅ Verify that the category is displayed

Note: I tested it only on self-hosted sites, and I would appreciate a smoke-test on wp.com as well.

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/290">25.1 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR contains changes to <code>RELEASE-NOTES.txt</code>.<br />
Note that these changes won't affect the final version of the release notes as this version is in code freeze.<br />
Please, get in touch with a release manager if you want to update the final release notes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by staskus — APPROVED** [review]
Thanks for the fix and the explanation. It does make sense to guard against the crash, especially given the exact scenarios how it happens are unclear.

I tested both self-hosted and wpcom sites and the category update code is triggered when a new one is added on the web.

**Comment by kean** [comment]
I think it requires more investigation. There is clearly something that changes with XMLRPC that's triggering it, and we need to get to the bottom of this.

**Comment by kean** [comment]
I'm inclined to believe that this is an API issue because it happened before and It only happens for XMLRPC sites. I've tested many standard scenarios and was not able to reproduce it. I'm not fully satisfied with just adding the defensive code, but I can't sink any more time into it since it affects only a small subset of users.

**Pull request merged**
