### PR TITLE
Remove FeatureFlag.modernizeMedia and associated code

### PR DESCRIPTION
**Pull request by kean**
To test: 

- Verify that Site Media screens opens
- Verify that Site Media pickers in Gutenberg, Site Icon flow, and Feature Image flow allow you to select images from Site Media

I wish I could remove more, but Aztec and Story Editor use WPMediaPicker and I'm hoping we get to the point where both can be removed.

## Regression Notes
1. Potential unintended areas of impact: n/a (only removal)
2. What I did to test those areas of impact (or what existing automated tests I relied on): n/a
3. What automated tests I added (or what prevented me from doing so): n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x]  I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by crazytonyli — APPROVED** [review]
Nice work! Glad to see that many legacy code got removed.

**Comment by crazytonyli** [comment]
@kean I have found a bug in adding images. It's probably not related to this PR though.

1. Add a gallery block in Gutenburg editor.
2. Tap add media.
3. Select multiple images and then tap the **Cancel** button.

The selected images are added to the editor. But they should not be.

**Comment by kean** [comment]
> The selected images are added to the editor. But they should not be.

Nice catch, thanks! Yes, I can reproduce it in my branch. It looks like an issue in the new Site Media view controller. I'll open a PR with a fix targeting the 23.7 release branch.

**Comment by kean** [comment]
Fix https://github.com/wordpress-mobile/WordPress-iOS/pull/22041

**Pull request merged**
