### PR TITLE
Update site header UI 

### PR DESCRIPTION
**Pull request by yaelirub**
After updating the topic page header in #14525 , we are now giving the site header a fresh new look as well.

To test:
1. Go to reader 
2. Tap on a site name in a post card 
3. See the new site header

Before             |  After
:-------------------------:|:-------------------------:
  |  

### With a longer site description 
Screen Shot 2020-07-28 at 6 36 31 PM

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by yaelirub** [comment]
hey @mbshakti , I updated the site header like we talked about. 
Two things to notice: 
1. We had the followers count in the previous UI so I put it under the image but if you want to get rid of it, we can. 
2. In your designs, you limit the description to 3 lines and a "...more" text that I assume is meant to expend to the full description. I didn't have the time to work on that so the header will show the full description when initialized. I don't see it as a blocker for this PR approval but if you see it as a deal breaker, I'll add a task to tackle this later on.

**Comment by mbshakti** [comment]
Thanks @yaelirub! Agree that the "more" link isn't a blocker. 

Some nits:
- Can we make sure we are using the same background color for the blog header as the postcards? In light mode seems fine, but dark mode, it should match the postcard. I think it's using Elevated Primary color. 
- As discussed on slack, I updated the design to include the followers # below the follow button. [Figma link here](https://www.figma.com/file/pUAK0Ft8TxC1DyIbstP3MY/Untitled?node-id=0%3A1).

To @leandroalonso regarding your comment on the font sizes, do you mean it seems big just on iPad or generally?

**Comment by leandroalonso** [comment]
@mbshakti in general, for example:



The description text is bigger than the blog information on the post card, for example. Anyway, if you're ok with it I'm ok too. :)

**Comment by yaelirub** [comment]
Screen Shot 2020-07-29 at 11 26 30 AM

@mbshakti , @leandroalonso , updated according to code review and design updates

**Comment by mbshakti** [comment]
Thanks! Looking good! One visual design nit, but not blocking. I noticed that in the latest screenshot you shared there seems to be uneven spacing at the top and bottom of the blog header card, [for example here](https://drive.google.com/file/d/1FVt-AOKpTattUPWuh3h0tIGGcY_-9bWZ/view?usp=sharing). I didn't notice earlier because the header faded into the background. 

Regarding the blog description font size, thanks for clarifying @leandroalonso -- I know what you mean! Since this screen is dedicated to the blog, and I think the font size being slighter bigger on the header is nice because it makes it feel more prominent, and doesn't feel like just another card on the screen.

**Comment by yaelirub** [comment]
>to be uneven spacing at the top and bottom

Updated

**Pull request merged**
