### PR TITLE
Update SIWA button appearance

### LINKED ISSUE #13620: Update social login buttons appearance
Update social login buttons to be consistent.

From Zeplin:

social_buttons

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #13620 
Auth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/213

This uses the Auth changes to display the updated Login & Signup buttons, as described in the Auth PR.

To test:

---
- If logged in, log out.
- Select `Log in` and `Sign up`.
- Verify the three buttons all have the same appearance. (Button size, font, background color)

| Log In | Sign Up |
|--------|-------|
| login | signup |

---
- Toggle light/dark modes.
- Verify the colors update accordingly. Specifically:
  - In dark mode, the buttons and button view backgrounds are black.
  - The Apple logo updates.

| Log In | Sign Up |
|--------|-------|
| login_dark | signup_dark |

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mattmiklic** [comment]
Oh and one question, what color is being used for the button outline? I'm using the "White Fill - Gray Outline" style that's defined in the iOS design resources from Apple, so I'm not sure if it has a system color name. It's #BFBFBF, or rgb(191,191,191).

**Comment by ScoutHarris** [comment]
Hey @mattmiklic . I modified the logo sizes and positions, and updated the screenshots in the description. See what you think now.

**Comment by mattmiklic** [comment]
@ScoutHarris Sizing looks good now! it looks like the Apple logo should move down by about 1pt though. Sorry for the nitpick but hopefully that's easy to fix. :)

Screen Shot 2020-03-20 at 10 14 42 AM

**Comment by ScoutHarris** [comment]
Hey @mattmiklic . Thanks for being the eagle-eye! 😄 I think I got it! I've updated the screenshots in the description. Please take another gander when you have a chance.

**Comment by ScoutHarris** [comment]
Hey @mattmiklic . I'm going to go ahead and merge this so it goes in the next release. Of course I can make any follow-up changes you may have.

**Comment by mattmiklic** [comment]
@ScoutHarris Thanks for indulging me. 😄 It looks great after that fix.

**Pull request merged**
