### PR TITLE
Merge 27.1.0.2 into `trunk`

### PR DESCRIPTION
**Pull request by mokagio**
This beta was built for localization smoke testing. It does not include any fix.

- [x] Updates to the localization files (`.strings` and Fastlane metadata) automatically pulled for the new translations that have already been approved in GlotPress
- [x] Version update in `.xcconfig`
- [x] Diffs from the PRs that made it into this beta – N.A.

### CODE REVIEW

**Comment by mokagio** [comment]
Removed label to see if I can see an event for that in the Peril logs.

**Comment by mokagio** [comment]
🤔 Peril comment here, but I didn't see any info about it in the logs

image

The last log I see there is from today at 00:10:09 UTC, but we're at 00:54 UTC right now

image 

That makes me think the logs that are collected by Heroku are not the whole picture of what Peril is doing.

**Comment by AliSoftware** [comment]
> The last log I see there is from today at 00:10:09 UTC, but we're at 00:54 UTC right now

Don't we have 3 different heroku apps, one for each GitHub org we have? And the log screenshot you posted makes me think you checked `automattic-peril.herokuapp.com` while I'd expect the Peril instance triggered for this PR would be the one about `wordpress-mobile`? (I apparently lost my access to heroku so can't check by myself though)

**Comment by mokagio** [comment]
> Don't we have 3 different heroku apps

**Comment by mokagio** [comment]
I checked the logs _on the right app_, and confirmed the logs are viable. E.g. here's a log of the auto-merge change I made on this PR:

```
2023-02-16T23:20:17.905949+00:00 app[web.1]: info: [router] -- Received pull_request:
2023-02-16T23:20:17.906213+00:00 app[web.1]: info: pull_request.auto_merge_disabled on unknown skipped
```

I _assume_ it's on this PR just because of the timestamp and how unlikely it is that two people would disable auto-merge at the same time. However, I couldn't find a link to the PR in the logs.

_This is something we should keep in mind if implementing an alternative stack: make it easier to understand which events we received and processed._

**Comment by mokagio** [comment]
😞 I was hoping to test the `merge_queue` event by admin merging this. Unfortunately, admin merge bypasses _all_ branch protection requirements, which includes Merge Queue.

https://user-images.githubusercontent.com/1218433/219511297-072e76b9-ec12-4aa6-8830-9a69b77bf53e.mp4

I thought it appropriate to admin merge because Olivier's review raised an issue with my merge queue experiment, not the PR diff and this PR also has no code changes, only metadata.

**Pull request merged**
