### PR TITLE
Fixes Login Layout Inconsistency

### LINKED ISSUE #4013: Login + SignIn: Update Top Buttons Alignment
1. Test on an iPhone with at least one blog in the list.
2. In My Sites, tap to Add a Site
3. Notice the position of the cancel button in the sign in modal.
4. Tap the (?) button in the top right to open the support screen.

Notice the position of the Close button. There is a subtle position shift between the two screens, and the font on the login screen seems one size too small maybe?

Props to @aerych for spotting this (and actually writing the whole ticket, i'm just copy'ing and pasting his feedback on #4009).

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Scenario 1: Logged Off
1. Fresh Install WPiOS
2. Press the `Create Account` button
3. Tap over the top right button

Note that the `Close` button of the modal screen should be placed at the exact same position as the `Back` that shows up in the `Create Account` view.

#### Scenario 2: Logged In
1. Log into WPiOS
2. Tap over `My Site` > `Add Site`
3. Notice the position of the cancel button in the sign in modal.
4. Tap the (?) button in the top right to open the support screen.

The Navigation Buttons are expected to be displayed at the exact same position, so that it looks consistent.

I'm afraid that the NavigationBar Metrics are different for iPad / iPhone. Please, verify this PR in both devices.

Needs Review: @aerych  (I believe these changes look / feel okay Eric, thanks in advance!)

Fixes #4013

### CODE REVIEW

**Comment by jleandroperez** [comment]
#### iPhone Screenshots:

iphone

iphone 2

**Comment by jleandroperez** [comment]
#### iPad Screenshots:

ipad 2
ipad

**Comment by aerych** [comment]
Shiny! :shipit:

**Comment by jleandroperez** [comment]
Thank you @aerych !!

**Pull request merged**
