### PR TITLE
Issue/7891 crash on multiple thumb insert

### LINKED ISSUE #7891: Inserting multiple images on a post can make it crash.
### Expected behavior

When inserting multiple media objects (20 or more) from the device media library the application shouldn't crash.

### Actual behavior

The app gets too much memory pressure and crash.

### Steps to reproduce the behavior

- Running on a debug build (this is where the new Media code is active)
- Create a new post
- Tap on the media insert button
- Insert 20 or more images
- See the app crashing.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #7891 

This PR adds serial queues for the execution for the image resize operation while exporting PHAssets and other media resources.

This avoid multiple exports to be executed at the same time and cause issues with memory pressure.

To test:
 - Check the ticket above for details how to reproduce.

### CODE REVIEW

**Comment by frosty** [comment]
Just posting here for future reference, as we discussed in Slack I'm seeing this crash more slowly that `develop`, but still crash. Whereas memory usage on `develop` spikes up very quickly, this branch goes in peaks and troughs. I presume each memory spike coincides with an image being processed, but for some reason each time it spikes higher than the last. Here's the last snapshot I got before it crashed on me:

media-memory

**Comment by frosty** [comment]
Fwiw, I only seem to get these graphs on Aztec. Hybrid seems okay. I just tested ~3 times on each editor, and got consistent results.

**Comment by SergioEstevao** [comment]
@bummytime do you mind give it a look to see what happens in your devices?

**Comment by bummytime** [comment]
@SergioEstevao yep!

**Comment by bummytime** [comment]
@SergioEstevao Just like @frosty mentioned, I am seeing slower crash on this branch than `develop`. However I do see that memory usage is way lower than what he captured above ☝️ : 

screen shot 2017-10-03 at 5 33 24 pm

Memory use oscillated between 30MB and ~110MB as each image was processed, but eventually crashed. I tested this 3 times with similar results.

_Tested on an iPhone 5 (10.3.3) with 20 on-device photos._

**Comment by frosty** [comment]
@bummytime Can I check, which editor were you using? I seemed to see different performance on Aztec vs Hybrid.

**Comment by bummytime** [comment]
@frosty I was using Aztec.

**Pull request merged**
