### PR TITLE
[Home Page Picker] Update the design of the “Choose a Domain” screen 

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2722

## To test:
📓 This doesn't include the [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/15303) to enable HPP by default so you'll still need to toggle the feature on if not already enabled
<details>
<summary><strong>To disable or enable the development version of Home Page Picker</strong></summary>

- Open the app from the build that allows FeatureFlags such as a PR build or a local development build
    - By default, the modal layout picker will be disabled.
    - From the site page:
        - Click on your Gravatar.
        - Click on App Settings.
        - Click on Debug.
        - Toggle "Site Creation: Home Page Picker" to enable or disable the picker
        - <kdb><a href="https://user-images.githubusercontent.com/3384451/97343011-5f032980-185d-11eb-9030-06c17f732fec.gif"></a></kdb>

</details>

When enabled, the first step of the Site Creation flow will be replaced with the Home Page Picker flow.

### Initial loading and Navigation
1. Navigate to the Create WordPress.com site
    - My Sites > ➕ > Create WordPress.com site > Select a site design or skip on the Choose a design page
1. **Expect** 
    - The back button to say "Design"
        - This is a change from the initial setting because "Choose Design" was too long that it ended up being shortened to "Back" by the system. 
    - The cursor to be on the "Search Domains" text field
    - The title to be updated to "Choose a domain"
    - The prompt to be updated to "This is where people will find you on the internet."
    - You should be able to scroll the header away (before searching) 

### Searching for a Domain
1. Navigate to the "Choose a Domain" Screen
1. Enter some text into the search box
1. **Expect** To see some results for a valid search term
    - 📓 The results for this screen uses the default quantity as set by the server which appears to be 5. I didn't change this here but totally think this could be a good enhancement in a follow-up PR.
1. Select the ✖️ in the search field
1. **Expect** 
    - To see the results clear and return to a blank space under the bar
    - The header should maintain its state (open or collapsed)
1. Enter some text into the search box again
1. **Expect** 
    - To see the results return
    - The header should maintain its state (open or collapsed)
1. Select a domain
1. **Expect** 
    - The keyboard to dismiss 
    - The "Create Site" button to appear
1. Select the search box to enter a new option
1. **Expect** 
    - The keyboard to appear 
    - The "Create Site" button to disappear

### Create Site
1. Navigate to the "Choose a Domain" Screen
1. Search for a domain 
1. Select a domain 
1. Select "Create Site" 
1. **Expect** To have a site created that matches your selected Domain and Design

### Searching for a Domain - No Results
1. Navigate to the "Choose a Domain" Screen
1. Search for a domain that won't return any results (I had luck with `google` and single letters but this seemed server-dependent)
1. **Expect** To see a label appear that says "No available addresses matching your search"

### Searching for a Domain - No Network
1. Navigate to the "Choose a Domain" Screen
1. Disengage your network connection
1. Search for a domain
1. **Expect** To see a cell added wit No connection and Retry
1. Repair your network connection
1. Select the cell 
1. **Expect** To see the search retry

### Analytics
📓 While testing this I noticed that if you navigate away and back to any of the site creation screens then the analytics for views don't fire again. This is consistent with the production versions of these screens though so I didn't change it. 

1. Navigate to the "Choose a Domain" Screen
1. **Expect** to see `enhanced_site_creation_domains_accessed` fire
1. Search for a domain
1. Select a domain
1. Select "Create Site"
1. **Expect** to see `enhanced_site_creation_domains_selected ` fire with `chosen_domain` populated with your selected domain and `search_term` populated with the term you searched with.

## Screenshots:
Initial Load | Search Results | Selected | Scrolled | No Results | No Network
--- | --- | --- | --- | --- | ---
<kdb><a href="https://user-images.githubusercontent.com/3384451/99574296-30342b00-29a5-11eb-961f-3fc875548938.png"></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/99574363-4b9f3600-29a5-11eb-951f-a90e974c2f7f.png"></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/99574404-5f4a9c80-29a5-11eb-9314-87e09fd81d36.png"></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/99574492-78534d80-29a5-11eb-9335-644eff21e696.png"></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/99574567-8e610e00-29a5-11eb-971e-d1684088fd11.png"></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/99574614-9faa1a80-29a5-11eb-96e4-3f8b25a57094.png"></a></kdb>

## Additional Context: 

This is a continuation of the work done in the [Home Page Picker Project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Home%20Page%20Picker) and is part of the [Round 2 requirements](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Home%20Page%20Picker%20Round%202). 

## PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by chipsnyder** [comment]
@kyleaparker @iamthomasbishop Here's the UI changes for the Choose a Domain screen. I decided to go forward using the same collapsing header of the other screen. I felt like just making the font and UI changes resulted in a weird feel. I did try and preserve some of the existing behaviors though. When you get a chance I'd love to get your thoughts.

**Comment by iamthomasbishop** [comment]
@chipsnyder I will reserve final judgement until I can get my hands on a test build, but based on these screenshots, it's looking pretty sharp! The only thing that looks off to me is the spacing between navigation bar and the large title — feels a little cramped. Can't remember off the top of my head what we're using on the other sheets (I _think_ 24?) and it might be too much spacing, but I think adding 8-16pts here might be sufficient.

image

**Comment by chipsnyder** [comment]
Thanks @iamthomasbishop!
Yeah looks like the CI build failed. I'll dive into that tomorrow. 

As for the spacing there it's actually the exact same on all instances. I'm using a reusable control where we can only modify the title and prompt for that spacing.

**Comment by iamthomasbishop** [comment]
> As for the spacing there it's actually the exact same on all instances. I'm using a reusable control where we can only modify the title and prompt for that spacing.

Ah, fair enough! Perhaps if the spacing is that tight across all instances, we should increase it a tad?

**Comment by chipsnyder** [comment]
Yup that's easy enough. I'll add a bit of space to the build once it's working and we can tweak it across the board as needed.

**Comment by chipsnyder** [comment]
Sorry about that build failure @iamthomasbishop and @kyleaparker. A new one with that top spacing is available now.

**Review by antonis — APPROVED** [review]
The code LGTM and the App behaves as expected 🎉 
Nice work Chip 👍

**Comment by chipsnyder** [comment]
Hey @kyleaparker, @SylvesterWilmott, @iamthomasbishop I added that extra spacing mentioned here: https://github.com/wordpress-mobile/WordPress-iOS/pull/15324#issuecomment-730293640 

To give you all a more comprehensive look I'm going to merge this branch and https://github.com/wordpress-mobile/WordPress-iOS/pull/15349 This will allow us to provide a more comprehensive build to a call for testing. I'll ping you all there once the build is avaialble

**Pull request merged**
