### PR TITLE
Site Tags search: add 'no tags matching your search' view.

### LINKED ISSUE #10143: Site Tags search: add 'no tags matching your search' view.
Site Tags search: add 'no tags matching your search' view.

Current:
tags_search_current

Design:
tags_search_design

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #10143 

To test:
- On a site with tags, go to site > settings > Tags.
- Enter an invalid search term.
- Verify the label appears, and is static at the top of the view.

**NOTE**: There is a pre-existing issue with the search bar not displaying correctly on the iPad (https://github.com/wordpress-mobile/WordPress-iOS/issues/10145).

iPhone portrait:
iphone_port

iPhone landscape:
iphone_land

iPad portrait:
ipad_port

iPad landscape:
ipad_land

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @jklausa . Please hold off on reviewing this for a bit. I think I found an issue. I'll ping you again when it's ready. Thanks!

**Comment by ScoutHarris** [comment]
OK well that didn't take as long as I thought. Good to go @jklausa . Sorry for the spam!

**Comment by SylvesterWilmott** [comment]
Looking good! Do we have the same max-width on these as in [#10129](https://github.com/wordpress-mobile/WordPress-iOS/pull/10129#issuecomment-421130247)

**Comment by ScoutHarris** [comment]
Hey @SylvesterWilmott . The max width is now 360. I fudged a multi-line label so you can see it wrap. Thoughts?

iPhone portrait:
iphone_port

iPhone landscape:
iphone_land

iPad portrait:
ipad_port

iPad landscape:
ipad_land

**Comment by SylvesterWilmott** [comment]
Looks good @ScoutHarris !

**Pull request merged**
