### PR TITLE
Fix/17344 - Close account error messages

### PR DESCRIPTION
**Pull request by nikola-milicevic**
Fixes [#17344](https://github.com/wordpress-mobile/WordPress-iOS/issues/17344)

This PR adds more specific localized error message for different error types that can be encountered while trying to close the user account.

## Test closing account with active subscription:
1. Make sure logged in user has an active subscription
2. Go to **My Site > Profile > Account Settings > Close account**
3. Enter the username when prompted
3. Closing account should fail with the following error message:

Screenshot 2021-10-21 at 15 11 21

## Test closing account with atomic site
1. Make sure logged in user has an atomic site, or is added as an admin to one
2. Go to **My Site > Profile > Account Settings > Close account**
3. The following error message should be displayed:

Screenshot 2021-10-21 at 15 14 07

## Regression Notes
1. Potential unintended areas of impact
n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a

3. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by momo-ozawa — APPROVED** [review]
Works as described! Thanks @nikola-milicevic 🙌  

One important thing though, I remembered the **Changes to the strings during the beta testing** section in p77Llu-bLz-p2. This document is a bit old though, so I'm not sure what the current protocol is. (cc: @leandroalonso @mokagio) 

I asked in Slack because I wasn't sure: p1634826656003100-slack-CC7L49W13

**Comment by momo-ozawa** [comment]
@nikola-milicevic 👋 
I'll be merging this into `release/18.5` once CI completes, since it's EOD for you... and also because I wanted to make sure @mokagio has a chance to make a new beta with these changes + merge `release/18.5` into `develop` before EOW.

Special thanks to @AliSoftware for helping to update the strings for localization! 🙇‍♀️

**Comment by mokagio** [comment]
@momo-ozawa  @nikola-milicevic  this has been bundled as part of [18.5 beta 3 (18.5.0.3)](https://github.com/wordpress-mobile/WordPress-iOS/pull/17346).

Thanks for your work 🙌

**Comment by nikola-milicevic** [comment]
@momo-ozawa @AliSoftware @mokagio Thanks! 🎉

**Pull request merged**
