### PR TITLE
Gutenberg: update to v1.27.0

### PR DESCRIPTION
**Pull request by mkevins**
## Related PRs

gutenberg-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2186
WordPress-Android: https://github.com/wordpress-mobile/WordPress-Android/pull/11756

To test:

**Bug fix**

- [x] Issue/1966 Disable whitespace collapse in Aztec https://github.com/wordpress-mobile/gutenberg-mobile/pull/2127
- [x] Revert "Add prop to force fullscreen preview for videos. (#20436)" https://github.com/wordpress-mobile/gutenberg-mobile/pull/2173
- [x] Block list - Autoscroll to text components within InnerBlocks https://github.com/wordpress-mobile/gutenberg-mobile/pull/2171
- [x] Issue/1851 insert captions https://github.com/wordpress-mobile/gutenberg-mobile/pull/2156
- [x] [FIX] Cover block background when there's a video is totally black https://github.com/wordpress-mobile/gutenberg-mobile/pull/2146
- [x]  Correct colors usage in Button https://github.com/wordpress-mobile/gutenberg-mobile/issues/2155
- [x] Correct slider step value https://github.com/wordpress-mobile/gutenberg-mobile/issues/2119
- [x] Refactor: Fixed position of `FloatingToolbar` on the bottom of the screen https://github.com/wordpress-mobile/gutenberg-mobile/issues/2118

**New feature & Improvement**

- [x] Update Aztec-Android for alignment handling https://github.com/wordpress-mobile/gutenberg-mobile/pull/2006 [Android **only**]
- [x] ~Video block - don't force full screen on iOS https://github.com/wordpress-mobile/gutenberg-mobile/pull/1952~ This was reverted
- [x] Adjust RangeControl to add the stepper control and allow type selection https://github.com/wordpress-mobile/gutenberg-mobile/pull/2125
- [x] Cover block - enable upload options in production https://github.com/wordpress-mobile/gutenberg-mobile/issues/2174
- [x] Cover block uploads failure UI https://github.com/wordpress-mobile/gutenberg-mobile/issues/2150
- [x] Add Buttons block https://github.com/wordpress-mobile/gutenberg-mobile/issues/1933

**Note:** including this to ensure we don't see the block in production yet:
- [x] Contact Info jetpack native blocks behind DEV flag https://github.com/wordpress-mobile/gutenberg-mobile/issues/1934

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by geriux** [comment]
### Writing flow sanity check

- [ ] Undo-redo [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/undo-redo.md)
- [ ] Copy-paste [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/copy-paste.md)
- [ ] Splitting blocks [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md)
- [ ] Multiline components [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/multiline-components.md)
- [ ] Formatting on rich-text based components [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/rich-text-formatting.md)
- [ ] Block insertion [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/block-insertion.md)

**Comment by geriux** [comment]
Related PRs and Writing flow sanity check tests ✅

**Comment by mkevins** [comment]
### Cover-1

- [ ] Cover - Add image background from WordPress Media library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)
- [ ] Cover - Change Minimum height in pixels - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc002)
- [ ] Cover - Change Background Opacity - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc009)
- [ ] Cover - Image focal point is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc003)
- [ ] Cover - Custom color is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc004)

**Comment by lukewalczak** [comment]
@mkevins I was not able to reproduce that problem, however, I was checking it on the simulator using release branch, because looks like `.ipa` expired.

Steps I went through:

1. Open a post
2. Add `Group` block
3. Add `Paragraph` into `Group` block
4. Type `Test`
5. Open a preview - check if the paragraph is displayed correctly
6. Add `Buttons` into `Group` block
7. Type `Test`
8. Open a preview - check if the button is displayed correctly
9. Add another `Buttons` into `Group` block
10. Type `Test`
11. Open a preview - check if the button is displayed correctly

Output:

Kapture 2020-04-29 at 10 04 21

**Comment by mkevins** [comment]
Thanks for testing!

**Comment by mkevins** [comment]
> @mkevins I was not able to reproduce that problem, however, I was checking it on the simulator using release branch, because looks like `.ipa` expired.
> 

Thanks for attempting to reproduce this @lukewalczak ! I have confirmed this bug does not require the group block. Also, I have confirmed that it does not appear to be related with button(s) block, which is where I originally encountered the issue while testing. This may be an issue with preview. I have now encountered this with the following steps:

1. Add a new post
2. Repeat the following 3 times:
   1. Add a paragraph with some text
   2. View preview (obvserve the new paragraph is display in the preview)
   3. Switch back to editing

On the third edit, I observed that the preview content was "stale". I'll open an issue for this.

**Pull request merged**
