### PR TITLE
Notifications: cell bottom padding constraint @ 999.

### PR DESCRIPTION
**Pull request by kurzee**
Resolves constraint conflict warnings when loading the Notifications cells; auto layout not
liking the height constraint versus the bottom constraint, together. Simply setting the bottom constraint to priority to `999` fixes the constraint conflict, and is ideal.

To test:

1. Launch the app, check that no warnings appear.
2. Give the Notifications tab a few good scrolls, rotations, push/pop, make sure all of the cells layout as expected.
3. Reader seems to have it's own warnings going on, might need to pop to root on the Reader tab before testing to avoid those warnings.
4. Test again on iPad.

Needs review: @elibud can you give it a whirl?

cc @astralbodies

### CODE REVIEW

**Comment by kurzee** [comment]
>No dice, I'm still getting the warning on IPad.

@elibud hmm, I'm having a hard time reproducing this, can you try this one more time? Perhaps there was an issues updating the simulator, or there is a particular notification with another edge case.

**Comment by elibud** [comment]
It's still there :( Lets see if this gif helps you reproduce it:

stupidautolayout

**Comment by kurzee** [comment]
@elibud ready for another look at your leisure!

**Comment by kurzee** [comment]
Thanks @elibud!

**Comment by astralbodies** [comment]
Nice work @elibud & @kurzee 😄

**Pull request merged**
