### PR TITLE
removed forced try & unwrap

### PR DESCRIPTION
**Pull request by entunidotdeb**
Fixes #
Safety checks: removed forced try & forced unwrap to avoid crash

### CODE REVIEW

**Comment by mokagio** [comment]
@entunidotdeb just a note to say I "took over" your work in #19167 to 1) run all the CI checks on it (which don't run on external contributor PRs) and 2) add some additional tweaks.

I cherry picked your commit, so once merged you should appear in the list of contributors.

Also, once #19167 merges this PR should automatically be marked as merged, too.

Thank you so much for your help!

**Comment by entunidotdeb** [comment]
@mokagio  thank you so much for informing. Just to confirm here, are CI checks supposed to run automatically on contributor's PR ? 
Happy to help more :)

**Comment by mokagio** [comment]
>  Just to confirm here, are CI checks supposed to run automatically on contributor's PR ?

Not the full CI suite. For example, this PR has 2 successful checks:

image

But a maintainer PR has 20:

image

**Comment by crazytonyli** [comment]
Ops, sorry, I didn't realize there was an open PR targeting my PR branch. But luckily Gio's PR got me covered. 😸

**Pull request closed without merging**
