### PR TITLE
Issue/7878 fix blog picker with long titles

### LINKED ISSUE #7878: Long site/url interfering with action buttons in Editor
### Expected behavior
If I had a long site title or URL (in the case of an empty site title), I would expect to still see the publish button in portrait mode in the Editor.

### Actual behavior
The Publish button is either not available or overrun with text.

### Steps to reproduce the behavior
1. Set a long site title (I used "This is a long site title I mean who would write something...")
2. Open the editor

Neither the "X" to exit the editor or the Publish action are available:

screen shot 2017-09-29 at 10 30 54

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #7878 

So in iOS 11 the code for UINavigationBar navigationItem looks it was changed and we now see overlap of titles over the other buttons on the navigation bar.

In order to solve this I moved the blog selector button to the titleView of the navigation bar. This look to solve the overlapping issues, but it changes the design of this screens. Now we have the blog picker on the centre of the navigation bar if there is a site.

screen shot 2017-10-10 at 14 42 23
screen shot 2017-10-10 at 14 43 00
screen shot 2017-10-10 at 14 43 30

To test:
 - Open the app
 - Select a blog with a long title
 - Create a Post
 - Check with the different orientations to see if title is not overlapping other buttons on the navigation bar.
 - Test on phones and tablets on different orientations and multitask modes. Also test in iOS10 and iOS11.

Needs review: @folletto do you mind to have a look to see if design wise this is ok.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
@SergioEstevao Is there any reason we can't keep the site picker on the left side, other than because that's where the title is by default? I ask because the current layout is left, and there's a good chance this pattern will stay in the next evolution of the editor (site picker left, in some form).

**Comment by frosty** [comment]
Just checked this out and ran it on my device (iPhone 7), and I'm seeing the blog title overlapping the publish button:

img_8937

**Comment by SergioEstevao** [comment]
@iamthomasbishop I will love to keep  it, but Apple is not making it easy for us to do it.

I couldn't find a way to keep on the left has before and not overlap anything.

**Comment by SergioEstevao** [comment]
@frosty if you rotate and rotate back is it still overlapping?

**Comment by bummytime** [comment]
@SergioEstevao I am seeing the blog selector overlap as well on the iPhone X in portrait:

screen shot 2017-10-10 at 4 50 54 pm
screen shot 2017-10-10 at 4 51 17 pm

Rotating and rotating back does not seem to help.

**Comment by SergioEstevao** [comment]
@bummytime and @frosty fixed some spacing issues, give it another look please.

**Comment by frosty** [comment]
Still seeing this behaviour:

editor-bar

**Comment by bummytime** [comment]
@SergioEstevao It is looking better:

napkin 49 10-11-17 8 23 25 am

I know it's outside the scope of what this PR is fixing, but man, that nav bar is cramped! It would be awesome to redesign it a little bit.

**Comment by bummytime** [comment]
(Maybe @folletto has some insight here)

**Comment by iamthomasbishop** [comment]
@bummytime it is super cramped. Redesign is incoming soon ;)

**Comment by SergioEstevao** [comment]
@frosty @bummytime do we go forward like this until we get a new design?

**Comment by folletto** [comment]
> I know it's outside the scope of what this PR is fixing, but man, that nav bar is cramped! It would be awesome to redesign it a little bit.

What @iamthomasbishop said. He's on it ;)

**Comment by bummytime** [comment]
@SergioEstevao Yeps! I think this PR address the core problem in #7878 — it works on iOS 10/11. :shipit: 

Nice work!

**Comment by frosty** [comment]
Let me run again, as my screenshot looks a little different to @bummytime's. I'll check if there's any difference.

**Comment by SergioEstevao** [comment]
Thanks for all feedback, me and @frosty found an alternative solution that keeps the current layout structure. Closing this PR in favour of this: #7952

**Pull request closed without merging**
