### PR TITLE
Gutenberg: update to v1.26.0

### PR DESCRIPTION
**Pull request by pinarol**
gutenberg-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2153
WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/11647

To test:

**Bug fix**

- [x] Fix: remove extra padding for post title and first `Paragraph` block  https://github.com/wordpress-mobile/gutenberg-mobile/pull/2095
- [x] Layout Template Modal & Button block - Orientation fixes https://github.com/wordpress-mobile/gutenberg-mobile/pull/2086
- [x] Fix: prevent ripple effect on slider cell in BottomSheet and disable it completely on iOS https://github.com/wordpress-mobile/gutenberg-mobile/pull/2023
- [x] Correct slider step value https://github.com/wordpress-mobile/gutenberg-mobile/pull/2119
- [x] Fix typography breakage in master https://github.com/wordpress-mobile/gutenberg-mobile/pull/2149
- [x] Align plus icon for the iOS Stepper control https://github.com/wordpress-mobile/gutenberg-mobile/pull/2116

**New feature & Improvement**

- [x] New: Column block - https://github.com/wordpress-mobile/gutenberg-mobile/pull/1661
- [x] New: Blogger template - https://github.com/wordpress-mobile/gutenberg-mobile/pull/2114
- [x] Layout Picker - Keyboard visibility improvements https://github.com/wordpress-mobile/gutenberg-mobile/pull/2123

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pinarol** [comment]
Writing flow sanity check:

- [ ] Undo-redo [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/undo-redo.md)
- [ ] Copy-paste [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/copy-paste.md)
- [ ] Splitting blocks [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md)
- [ ] Multiline components [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/multiline-components.md)
- [ ] Formatting on rich-text based components [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/rich-text-formatting.md)
- [ ] Block insertion [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/block-insertion.md)

**Comment by pinarol** [comment]
I completed the tests, could only find [1 bug](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2154), which doesn't look like a blocker. But I appreciate an extra eye on writing flow. @etoledom Thanks!

**Comment by etoledom** [comment]
Writing flow tests from https://github.com/wordpress-mobile/WordPress-iOS/pull/13878#issuecomment-612992309 ✅ 

Changes tests:

* ✅ Block editor: Disable ripple effect in all BottomSheet's controls.
* ✅ Block editor: New block: Columns
* ✅ Block editor: New starter page template: Blog
* ✅ Block editor: Make Starter Page Template picker buttons visible only when the screen height is enough
* ✅ Block editor: Fix a bug which caused to show URL settings modal randomly when changing the device orientation multiple times during the time Starter Page Template Preview is open (I didn't have much background on this one but didn't noticed anything estrange following the provided steps).

**Note**: I noticed something strange on the `Latest Posts` settings bottom sheets:
At first it wasn't scrolling to show the last control, then I notice that it won't scroll if I happen to tap. over the Section Title (Post meta settings or Sorting and filtering).

Other settings doesn't have so many sections so it's not so noticeable, but on this one took me a bit to make it scroll and to realice what was happening.

This happens on the previously released version too, not a regression from this one.

**Comment by pinarol** [comment]
Thank you @etoledom !

> At first it wasn't scrolling to show the last control, then I notice that it won't scroll if I happen to tap. over the Section Title (Post meta settings or Sorting and filtering).

Interesting finding. Could you open an issue and add to Mobile Gutenpages board? Don't think this is a blocker but definitely worth investigating.

**Comment by etoledom** [comment]
> Could you open an issue and add to Mobile Gutenpages board?

https://github.com/wordpress-mobile/gutenberg-mobile/issues/2160 👍

**Pull request merged**
