### PR TITLE
Minor Spelling Corrections

### PR DESCRIPTION
**Pull request by garrett-eclipse**
Fixed spelling of wordpress within the site address placeholder

### CODE REVIEW

**Comment by michelleweber** [comment]
What/where is the full text? I can't know which is correct without context. Thanks!

**Comment by nheagy** [comment]
Hi @garrett-eclipse, thanks for the PR!

I know these are really simple changes, but a description would be much appreciated—and will make your contributions more obvious 😉

The use of "any time" is intentional, fwiw. But the `wordress.com` clearly isn't, ha! If you reduce to the PR to just that commit and add a description, I'll happily merge it in.

Thanks! ✅

**Comment by michelleweber** [comment]
(To weigh on on the grammar -- both "anytime" and "any time" are correct in the phrase in question, and "any time" was chosen there because of how it reads/the feel it gives the sentence.)

**Comment by garrett-eclipse** [comment]
Sorry @nheagy I've reverted the two anytime commits and added a description.
Thanks @michelleweber for the grammar check, was just following my Grammarly autochecker on that one.
Should be good to go now
Thanks

**Comment by garrett-eclipse** [comment]
Thanks @nheagy I'll take a look when I have some personal dev time. All the best

**Pull request merged**
