### PR TITLE
Add push notification media support

### PR DESCRIPTION
**Pull request by emilylaguna**
### Description
This is a continuation of the gif/media support PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/17981

This PR adds rich media support to notifications, and a

This also disables the NotificationContentExtension and switches to the system rendering of the content which prevents some empty display issues and clipping issues: 
- https://github.com/wordpress-mobile/WordPress-iOS/issues/15495

### Screenshots
| Notification | Long Press view |
|:---:|:---:|
|IMG_3151|IMG_3152|

### To test:
**Note: Push notifications need to be tested on a real device**
**Note: You will need 2 accounts to receive the comment notifications.**

You should also apply this to a sandbox: D75182-code

### With media
1. Go to a test blog that has blocks enabled for comments (P2 sites work well) with your second account (the one that isn't logged into the app)
2. Reply to a comment and add an image block with some text
3. Upload a static image (not a gif)
4. Receive the notification in the app
5. Verify you see the media preview on the notification itself
6. Long press on the notification 
7. Verify you see the comment content with the image
8. Repeat the steps with a gif, and verify the gif animates in the preview

### Other notifications
Correct meaning, it looks the same as it does on the current release version of WordPress (19.2).

It's easiest to use the push notification debug on MC.

1. Send yourself notifications that include media and do not (ie: comments without media, likes, achievements, miletones)

### Regression Notes
1. Potential unintended areas of impact
TBD

4. What I did to test those areas of impact (or what existing automated tests I relied on)
TBD

5. What automated tests I added (or what prevented me from doing so)
TBD

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by frosty — COMMENTED** [review]
Finally got everything working to get this tested! Thanks for your help getting it set up.

So code-wise I think this all looks good. Notifications in Notifications center also look good and I think as expected, however I did notice some cases where text is visible in the notification which gets replaced by the image when viewing it in the app. I'm not sure if this is intentional or not? For example:

|   |   |
|---|---|
| B298B164-EC1C-4780-BC20-C92E4F301AB1_1_105_c | F7F06740-63DB-4CF3-B903-CC671F478B80_1_105_c |

I also have an issue where the static images aren't loading in the app (but I can see where they should appear) – I think this is likely due to my proxying setup though

|   |   |
|---|---|
| 90945B5B-0B33-417F-9D6B-9F689E1A6DE8_1_201_a | E8316D2A-44E2-4686-9ACD-6134E50FA48E_1_201_a |

My final query would be whether we want to remove the remaining WordPressNotificationContentExtension files in this PR, or separately.

**Review by momo-ozawa — COMMENTED** [review]
@emilylaguna 

I noticed that the block order matters for static image blocks.

If your comment block order is [image block, paragraph block], then there's no media preview on the notification. However, if the order is [paragraph block, image block], then you can see the media preview.

For gif blocks, the order doesn't seem to matter -- I was able to see the media preview either way.

**Comment by emilylaguna** [comment]
> If your comment block order is [image block, paragraph block], then there's no media preview on the notification. However, if the order is [paragraph block, image block], then you can see the media preview.

Hmm. I'm not able to reproduce that on my end. When you get a chance, can you send me a comment with this issue on this post? pdJdvN-P-p2

**Comment by emilylaguna** [comment]
@frosty 

> I did notice some cases where text is visible in the notification which gets replaced by the image when viewing it in the app. I'm not sure if this is intentional or not? For example:

It looks like that's the alt text for the image that is appearing in the comment. I may make a server change to remove that. 

> I also have an issue where the static images aren't loading in the app (but I can see where they should appear) – I think this is likely due to my proxying setup though

Not able to reproduce that on my end, I wonder if it could be a permissions issue since you're not a member of the blog? 



> My final query would be whether we want to remove the remaining WordPressNotificationContentExtension files in this PR, or separately.

I was thinking of doing it separately once we know we no longer want to use it.

**Comment by emilylaguna** [comment]
@momo-ozawa Thanks for sending that over, this is how it came through for me:

**Comment by momo-ozawa** [comment]
@emilylaguna Hmm! Maybe it's my device? I'm testing on an iPhone SE.

first block == image block | first block != image block
-- | --
 | 
 |

**Review by momo-ozawa — APPROVED** [review]
Tested again w after D75182-code was deployed, works as described!

**Pull request merged**
