### PR TITLE
Update media picker version.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Update new media picker version with the ImageCacheManager. This should solve the non-retina iPad crashes

Needs Review: @sendhil

### CODE REVIEW

**Comment by sendhil** [comment]
@SergioEstevao when I logout I get a bunch of errors like this:
```
2015-09-08 16:45:33:018 WordPress[62788:607] Error removing media files:Error Domain=NSCocoaErrorDomain Code=4 "The operation couldn’t be completed. (Cocoa error 4.)" UserInfo=0x7feaf533fff0 {NSFilePath=/Users/sendhil/Library/Developer/CoreSimulator/Devices/1E7F6834-8E23-4D0E-A732-9B3C3BACC855/data/Containers/Data/Application/0D357F5E-D846-40A3-A573-9806D2B967C3/Documents/Media/20140429-001808-1088745-thumbnail.jpg, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x7feaf0d158e0 "The operation couldn’t be completed. No such file or directory"}
```

**Comment by SergioEstevao** [comment]
I don't think this error messages are related to the change I did. This log message comes from a cleanup code that we have in the MediaService class ```cleanUnusedMediaFileFromTmpDir```. 
It tries to find any media files that are  and not being used by the blog and deleted them this as nothing to do with the media picker. That said we should create a different issue to investigate what is going on there.

**Comment by sendhil** [comment]
Ahh your right, just verified that the error is in `release/5.6` as well. Just update the branch and we can merge this in.

**Comment by SergioEstevao** [comment]
Close will redo it from scratch to avoid strange merge on podfile.

**Pull request closed without merging**
