### PR TITLE
Recent Sites

### LINKED ISSUE #6217: Site Picker: Sort recently used sites to the top of the site list
In Calypso web, if you have 15 or more sites, there is a "recent sites" group that appears at the top of the site picker (see https://github.com/Automattic/wp-calypso/pull/2742) to keep you from having to scroll every time to find recently used sites.

This shows your most recently used sites at the top of your site list, with other sites shown alphabetically beneath it:

screen shot 2016-11-21 at 4 16 37 pm

We could do the same in the app, showing the three most recently used sites at the top of the site list. Currently, we show the primary site at the top of the list with other sites listed alphabetically beneath that:

h/t Ryan for [raising this issue](https://test.wordpress.com/2016/11/10/session-notes-back-buttons-hidden-sites-touch-image-flow-notifications-site-switching-flow-keyboard-flow-media-section-desktop-first/).

##### Tested on iPhone 6, iOS 10.1.1, WPiOS 6.7.0.20161115

### PR DESCRIPTION
**Pull request by koke**
Keep the 3 most recently used sites at the top of the blog list and blog selector.

recent-sites

## Decisions

When I started, I had a few unanswered questions, so here are my notes:

- Do we want a minimum number of sites before we show recent sites?
- Do recent sites get removed from the rest of the list?
- Do we want to separate the two sections visually? How?

I think recent sites starts being useful whenever you have more than "a page" of blogs: if all your blogs fit in the screen, it's probably best to keep that order. That's roughly about 6 sites on an iPhone SE. We could also use 4 as the threshold, to match when we start showing search. Note that this threshold should count *visible* sites.

I'd rather keep the recent sites also in the "all sites" section, but that might lead to odd UI scenarios where you'd see the same site twice on the screen. It might be best to start by filtering those out, which would also match what Calypso does.

As for the separator, it seems we could have sections with no title and a height of 1px to show a subtle distinction, but that'd need design review. It doesn't look too bad with a 2px gap. @mattmiklic thoughts?

## Design

Instead of adding more (duplicate) logic to both view controllers, I extracted all of it to a `BlogListDataSource` object, which uses a few distinct "mappers" to generate the expected results.

I'd probably extract the cell configuration to a custom cell that just takes a `Blog`, but this PR was already big enough, and that's not related to recent sites anyway.

I still want to add documentation to `BlogListDataSource` on Monday, but the rest should be ready for review.

Fixes #6217 

I feel like I changed a lot of code here but it was hard to do it more incrementally, so I'm asking for some extra eyes on this one.
Needs review: @aerych @frosty

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@koke did you considerer to have two sections on the list? one on the top that say Recent and the another with the full list?

Calypso add a separator between them but no section name...

**Comment by aerych** [comment]
I'll echo @SergioEstevao.  Without grouping into sections (I'd be a fan of a section title btw) it could just look like the list was out of order.  Maybe we could at least include a separator?  Thoughts?

**Comment by aerych** [comment]
I took a quick first pass and noticed that the list does not update to show recent blogs during the first launch after install (when there are still no recent blogs).  On subsequent launches the list does update as expected.

**Comment by aerych** [comment]
Tested a bit more and it seems pretty solid I'll follow up with a code review Monday. 

One thing, I'm not sure how necessary a recent section is when there are only a few visible blogs. Currently there must be five blogs added before the the recent section grouping but that seems like too few, especially when its not necessary to scroll the list.  Perhaps we could increase this a bit?

**Comment by koke** [comment]
I did consider section titles, but I couldn't figure out the right title. Sure "Recent Sites" might suit the first section, but what to call the second? "All sites" is not accurate, and rest/other doesn't feel right. It looks like when the feature was introduced in calypso, it had "Recent Sites"/"Sites" as the section titles but those were eventually removed. I finally went for the choice that was closer to the current calypso, but I'd love @mattmiklic and @mtias thoughts on this one.

**Comment by mtias** [comment]
> It looks like when the feature was introduced in calypso, it had "Recent Sites"/"Sites" as the section titles

Indeed, I went through the same train of thought you did, and this seemed the best:

image

But in practice it was just adding vertical weight unnecessarily. I remember @m asked me to just remove the headings at the time.

> Do we want a minimum number of sites before we show recent sites?

We do have a threshold in Calypso. It's defined here: https://github.com/Automattic/wp-calypso/blob/master/client/components/site-selector/index.jsx#L439

We only show recent sites if you have more than 11 non-hidden sites.

> Do recent sites get removed from the rest of the list?

In Calypso, yes. The duplicated sites was very odd.

**Comment by koke** [comment]
About the threshold, on an iPhone SE (the shortest screen), only 5 sites are fully visible without scrolling, so 5 could be the new threshold. I used 4 since it's the same threshold we use to show the search bar, but we could bump that one as well.

**Comment by aerych** [comment]
> About the threshold, on an iPhone SE (the shortest screen), only 6 sites are fully visible without scrolling, so 6 could be the new threshold

Could this be calculated at run time based on the optimal size of the screen.  Six is might still be too few for an iPad.

**Comment by frosty** [comment]
I should've requested changes instead of approving, but I can't seem to change it after the fact...

**Comment by mattmiklic** [comment]
> We only show recent sites if you have more than 11 non-hidden sites.
> Could this be calculated at run time based on the optimal size of the screen. Six might still be too few for an iPad.

I think we could make things fairly simple and use the same threshold as Calypso, >11 sites. That makes the behavior more consistent between web and apps, and solves the problem of there not being enough sites in the list on larger screens to make the separation make sense.

> But in practice it was just adding vertical weight unnecessarily.

This seems like a good enough reason to try it without the headers. If we find that people need an explanation, we can add them.

I like the 2px separator -- I think 1px would be subtle enough that the division might not be clear. We can always try different treatments later but I think this is a good place to start

**Comment by koke** [comment]
> I'm not sure I like the name Table, but I don't have any better suggestion.

I'm not either. It seemed like a good idea at first, but I might just drop the `typealias`

**Comment by koke** [comment]
Pushed a few changes:

* Drop Table typealias and rename table to sections
* Limit recent sites on display instead of storage
* Moved related constants inside WPBlogTableViewCell
* Remove "count" helpers
* Turn recent site threshold up to eleven! :metal:

This should address all the feedback except the "recommended section not appearing during the lifetime of the first instance" that I haven't been able to reproduce. @aerych do you mind testing that again?

**Comment by aerych** [comment]
> do you mind testing that again?

Re-tested and... I can't reproduce now 😞, not even from a clean install. 🤷‍♂️ 

That being the case, :shipit:

**Pull request merged**
