### PR TITLE
[SIWA] Show Apple credentials request.

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes # n/a 
WPAuth PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/115

This uses the WPAuth changes in the above PR to show the Apple ID credentials request.

To test:
Run the app in Xcode 11.
- Log out if necessary.
- Select Log In > Continue with Apple.
- The 'Sign In with Apple' process is presented until valid credentials are entered or 'Cancel' is selected.
- Since account creation is not yet implemented, for now the user's email and full name will be logged in the console. Ex:
```
Apple Authenticator credentials: Optional("useremail@gmail.com"), Optional(givenName: First familyName: Last )
```

siwa_flow

Run the app in Xcode 10. Verify the app runs and does not show the 'Continue with Apple' login button.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@mattmiklic - just fyi - that darker background in the SIWA flow is Apple's doing. And I don't see that there's any way to change it.

Also, if you'd like a video of this just let me know and I can DM it to you. I didn't add one here as it clearly shows credentials.

**Comment by mattmiklic** [comment]
Hey @ScoutHarris this is looking pretty good. Two notes:

- The "Or log in by entering your site address" subheadline should be 15pt by default, but it looks like it's 11pt right now.
- Re: the darker background in the SIWA flow, I'm wondering if we're displaying Apple's scrim on top of the scrim we add in the step where you choose a login option? I think that screen would work fine without a scrim, and then Apple could display their own for their flow without it becoming too dark.

**Comment by ScoutHarris** [comment]
Hey @mattmiklic .

> The "Or log in by entering your site address" subheadline should be 15pt by default, but it looks like it's 11pt right now.

Woops. Fixed.

> Re: the darker background in the SIWA flow, I'm wondering if we're displaying Apple's scrim on top of the scrim we add in the step where you choose a login option? I think that screen would work fine without a scrim, and then Apple could display their own for their flow without it becoming too dark.

The login button view is dismissed, which includes our scrim.  Then the `ASAuthorizationController` is displayed.

siwa_view

**Comment by mattmiklic** [comment]
> The login button view is dismissed, which includes our scrim. Then the ASAuthorizationController is displayed.

Ok got it, thanks! Let's roll with that then. Text link looks good now. 👍

**Comment by ScoutHarris** [comment]
Thanks @mattmiklic !

@astralbodies ready for a review when you have a mo! Thanks!

**Pull request merged**
