### PR TITLE
Nukes BlogSettings Helpers

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:
As part of the #4382 Data Layer groundwork, we've introduced a new entity called `BlogSettings`. Several `Blog` fields have been moved over to this new entity.

In order to minimize the main PR footprint, we've added several helpers that relay the appropriate `setting.property`. The purpose of this change is to remove those helpers, and update the related code.

#### Scenario 1: Geotagging
1. Tap over `My Sites` and pick a dotcom site
2. Select the `Settings` row
3. Toggle the Geotagging field
4. Press the `New Post` button
5. Make sure that the same blog as selected in (1) is also picked
6. Press over the Top Right Settings button

Verify that the Geotagging preferences are respected.

#### Scenario 2: Default Category / Post Format
1. Tap over `My Sites` and pick a dotcom site
2. Select the `Settings` row
3. Edit the Default Category / Post Format preferences
4. Press the `New Post` button
5. Make sure that the same blog as selected in (1) is also picked
6. Press over the Top Right Settings button

Verify that both values, `Category` and `Post Format` are correctly loaded.

#### Scenario 3: Blog Name + Tagline + Privacy
1. Tap over `My Sites` and pick a dotcom site
2. Select the `Settings` row
3. Edit the Blog's Name + Tagline + Privacy settings

Verify that the new Name and Tagline values are effectively saved at WordPress.com

Needs Review: @astralbodies 
Thanks Aaron!

### CODE REVIEW

**Comment by astralbodies** [comment]
Conflicts here, @jleandroperez - can you merge in develop? :smile:

**Comment by jleandroperez** [comment]
@astralbodies all conflicts gone. Ready for a check, thank you sir!

**Comment by astralbodies** [comment]
:shipit: - Maybe revert the changes to the Today Widget storyboard?

**Comment by jleandroperez** [comment]
Storyboard changes reverted! thanks for the review Aaron!

**Pull request merged**
