### PR TITLE
Fix Aztec editor constraints and scrolling issues

### PR DESCRIPTION
**Pull request by SergioEstevao**
This PR ports the changes made on this Aztec PR https://github.com/wordpress-mobile/AztecEditor-iOS/pull/940 to the main app.

This fixes a lot of constraints warning and some scrolling issues we where seeing.

To test:
 - Open the Aztec editor with a big post
 - Scroll up and down on it and see if everything is work ok.
 - Check on phones and tablets on the multiple multitasks mode.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Ping @frosty since you reported some issues with insets recently.

**Comment by frosty** [comment]
I'm still seeing the issue I was seeing here, but perhaps it's not directly related. I can open a separate issue. Essentially the steps to reproduce are:

* Start a new post
* Add multiple lines of text (can just be one word per line) so that the post scrolls
* Add a list – it can be at the bottom or further up
* Notice you now can't scroll to the end of the post

**Comment by SergioEstevao** [comment]
@frosty please open another issue I will check it. Thanks!

**Comment by frosty** [comment]
@SergioEstevao Done! I noticed it affected the Aztec example too, so I created the issue over there: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/946

**Pull request merged**
