### PR TITLE
[Home Page Picker] Enable Home Page Picker feature

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2727

## To test:
This enables the Home Page Picker for the enhanced site design selection. The old flow can still be tested for comparison reasons by toggling the feature off.
<details>
<summary><strong>To disable or enable the development version of Home Page Picker</strong></summary>

- Open the app from the build that allows FeatureFlags such as a PR build or a local development build
    - By default, the modal layout picker will be disabled.
    - From the site page:
        - Click on your Gravatar.
        - Click on App Settings.
        - Click on Debug.
        - Toggle "Site Creation: Home Page Picker" to enable or disable the picker
        - <kdb><a href="https://user-images.githubusercontent.com/3384451/97343011-5f032980-185d-11eb-9030-06c17f732fec.gif"></a></kdb>

</details>

## To Test
From a clean install:
1. Log in 
1. Navigate to the Create WordPress.com site
    - My Sites > ➕ > Create WordPress.com site
1. **Expect** To be presented with the Choose a design screen instead of the site Segment selection 

### Create a Site - Selecting a design
<details>
<summary>Steps</summary>

1. Navigate to the Create WordPress.com site
    - My Sites > ➕ > Create WordPress.com site
1.  **Expect** 
    - To see the analytics event `enhanced_site_creation_site_design_viewed`
    - To see a single placeholder while the network request to fetch the available design is processing
        - 📓 You may not see this if you're on a fast network
    - To see placeholders populate for each site design 
    - To see thumbnail images load as their network request finishes
1. Scroll to the bottom of the list
1.  **Expect** 
    - To see the header collapse as you scroll down
    - To see placeholders for thumbnails that weren't on the screen during the initial load.
        - 📓 You may not see the thumbnail placeholders if you're on a fast network and if they were cached on the server
1. Scroll to the top of the list
1.  **Expect** 
    - To see the header expand as you reach the top
    - Thumbnails should not be fetched from the server again unless your device purged the cache (low memory devices)
1. Select a layout
1.  **Expect** 
    - To see the footer slide in from the bottom
    - To see a border and checkmark animate in place on the selected design. 
1. Select Choose
1.  **Expect** 
    - To see the analytics event `enhanced_site_creation_site_design_selected` with the property `template` populated with the selected layout's slug
1. Search for a domain
    - Selecting [Cassel](https://s0.wp.com/mshots/v1/public-api.wordpress.com/rest/v1/template/demo/mayland/casselstartermobile.wordpress.com/%3Flanguage%3Den?vpw=1200&vph=1600&w=400&h=534) or [Bowen](https://s0.wp.com/mshots/v1/public-api.wordpress.com/rest/v1/template/demo/coutoire/bowenstartermobile.wordpress.com/%3Flanguage%3Den?vpw=1200&vph=1600&w=400&h=534) should include `.blog` subdomains all others (at the time of writing this) should not. 
1. Select a Domain
1. Select Create Site
1.  **Expect** 
    - To see a temporary screen as the site is being created
    - To see the site confirmation screen.

</details>

### Create a Site - Skip button
<details>
<summary>Steps</summary>

1. Navigate to the Create WordPress.com site
    - My Sites > ➕ > Create WordPress.com site
1.  **Expect** 
    - To see the analytics event `enhanced_site_creation_site_design_viewed`
    - To see a single placeholder while the network request to fetch the available design is processing
        - 📓 You may not see this if you're on a fast network
    - To see placeholders populate for each site design 
    - To see thumbnail images load as their network request finishes
1. Select `Skip` in the top right-hand corner
1. Scroll to the top of the list
1.  **Expect** 
    - To see the analytics event `enhanced_site_creation_site_design_skipped`
1. Search for a domain
    - This should not include `.blog` subdomains
1. Select a Domain
1. Select Create Site
1.  **Expect** 
    - To see a temporary screen as the site is being created
    - To see the site confirmation screen.
    - This should create a site based on the [default](https://s0.wp.com/mshots/v1/public-api.wordpress.com/rest/v1/template/demo/hever/defaultstartermobile.wordpress.com/%3Flanguage%3Den?vpw=1200&vph=1600&w=400&h=534) layout

</details>

### Preview then Create a Site
<details>
<summary>Steps</summary>

1. Preform `Create a Site - Selecting a design` 1-8
1. Select Preview
1.  **Expect** 
    - A new modal to appear stacked on top of the current one
    - A progress bar should appear and begin progressing
    - To see the event `enhanced_site_creation_site_design_preview_viewed` fire with the parameter `template` populated with the selected design's `slug`
    - To see the event `enhanced_site_creation_site_design_preview_loading`
    - To see the event `enhanced_site_creation_site_design_preview_loaded`
        - If there is a network error: **Expect** to see the event `enhanced_site_creation_error_shown` fire with the parameter `error_info` with a description of the error
    - On a successful load the preview should be populated with a demo site
        - If there is a network error: you should see the error screen but should be able to tap "Choose" still
1. Select Choose
1. **Expect** to see the preview modal dismiss and for the Choose a Domain screen to be "pushed" on to the navigation flow. 
1. Continue `Create a Site - Selecting a design` at step 10 `Expect ...`

</details>

### Error Scenario
<details>
<summary>Steps</summary>

1. Using an account that is logged in
1. Disconnect your device from a network connection
1. Navigate to the Create WordPress.com site
    - My Sites > ➕ > Create WordPress.com site
1.  **Expect**
    - To see the analytics event `enhanced_site_creation_error_shown` with `error_info` populated with a description of the error that occurred.
    - To see the error screen in the screenshots below
1. Repair your network connection
1. Either:
    - Tap `Retry` and expect to be able to complete `Create a Site - Selecting a design`
    - Tap `Skip` and expect to be able to complete `Create a Site - Skip button`

</details>

## Screenshots:

<details>
<summary>Choose a design</summary>

Expanded | Collapsed | Selected | Network Error
--- | --- | --- | ---
<kdb><a href="https://user-images.githubusercontent.com/3384451/99829543-6b139b80-2b2a-11eb-846d-3bf8cb59b52c.png"></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/99829675-972f1c80-2b2a-11eb-88a4-0e8bd8a2ebb6.png"></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/99829883-e5442000-2b2a-11eb-8921-4a1a1b2f5de0.png"></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/99830972-71a31280-2b2c-11eb-97f3-ae2f7f8e4233.png"></a></kdb>

</details>

<details>
<summary>Preview</summary>

<kdb><a href="https://user-images.githubusercontent.com/3384451/99829946-fa20b380-2b2a-11eb-988f-1ff0f0f11c8e.png"></a></kdb>

</details>

<details>
<summary>Choose a Domain</summary>

Expanded | No Options | Results | Selected | Network Error
--- | --- | --- | --- | ---
<kdb><a href="https://user-images.githubusercontent.com/3384451/99830228-68fe0c80-2b2b-11eb-96c4-e6bb0f7ecc3d.png"></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/99830667-03f6e680-2b2c-11eb-96fe-69998f240ca5.png"></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/99830712-1709b680-2b2c-11eb-964a-30f9dab6588e.png"></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/99830782-31439480-2b2c-11eb-91cf-c20981d744d5.png"></a></kdb> | <kdb><a href="https://user-images.githubusercontent.com/3384451/99830850-45879180-2b2c-11eb-866a-c1d544792286.png"></a></kdb>

</details>

## Additional Context: 

This is a continuation of the work done in the [Home Page Picker Project](https://github.com/wordpress-mobile/gutenberg-mobile/labels/Project%3A%20Home%20Page%20Picker). 

## PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by antonis — APPROVED** [review]
LGTM @Chip :tada:

**Comment by mkevins** [comment]
I've re-tested all the flows described, and everything is working as expected. I've also verified the events in the debugger and in the live view, and all events are emitted correctly.

Two issues I observed are described here: https://github.com/wordpress-mobile/WordPress-Android/pull/13409#issuecomment-729425368 which were also present in the iOS app.

Nice work Chip! :+1:

**Comment by chipsnyder** [comment]
> Two issues I observed are described here: wordpress-mobile/WordPress-Android#13409 (comment) which were also present in the iOS app.

Thanks for testing and confirming @mkevins. I agree with what @antonis' [analysis](https://github.com/wordpress-mobile/WordPress-Android/pull/13409#issuecomment-729653778), this is probably something we can help triage to fix on the backend. I'll do some more investigating as well on the iOS side.

**Comment by chipsnyder** [comment]
@kyleaparker @SylvesterWilmott @iamthomasbishop I merged the other changes as mentioned in https://github.com/wordpress-mobile/WordPress-iOS/pull/15324#issuecomment-731246542 and updated this branch with those changes. That way we can start a call for testing and you have a more comprehensive build to look at. 

Build `38175` just finished so when you get a chance to take a look and if you have any final feedback let me know and I'll start working on it :)

**Comment by chipsnyder** [comment]
Running through some test cases on different devices this is a running list of issues I'm encountering. I'll branch these off into fixes soon:
(all devices are simulators unless noted)

----
(Edit) The following issue(s) are being addressed in https://github.com/wordpress-mobile/WordPress-iOS/pull/15360
<details>
<summary>Choose a Domain screen - Header unexpectantly expands when search results change</summary>

**Noticed on:** 
- iPad Air 11.4

**Steps**
1. Navigate to Choose a Domain
1. Search for results

Notice the header will sometimes expand
<kdb><a href="https://user-images.githubusercontent.com/3384451/99837456-9bad0280-2b35-11eb-9a9f-7dd8bf56af12.png"></a></kdb>

</details>

**Comment by kyleaparker** [comment]
Thanks for the ping @chipsnyder! This is looking really great 🎉 I have reviewed the build and have a couple of comments: 
- On a slow connection the homepage images load in one by one. Do we have a skeleton loading state we can use to fade the images in once they're available? I think this would help the loading state feel a bit smoother. 
- I'd mentioned this in a previous PR but I think it would be useful to add the _Skip_ option to the domains screen
- On the _Choose a Domain_ screen, the "Search Domains" placeholder text looks too small, what size are we using for that?
- I think we should change the wording of the sub-text on the _Choose a Design_ screen from "**Pick your favorite homepage layout. You can customize or change it later**." to "**Pick your favorite homepage layout. You can edit and customize it later.**" At least until we know which approach we are going to take on switching homepage layouts. cc @iamthomasbishop I'd like to hear your thoughts on changing the wording here.

**Comment by chipsnyder** [comment]
Thank you, @kyleaparker, for your review 😃 

> On a slow connection the homepage images load in one by one. Do we have a skeleton loading state we can use to fade the images in once they're available? I think this would help the loading state feel a bit smoother.

I see what you mean. Having a more uniform loading might help make the experience more smooth. I came up with a few scenarios while thinking about this that I fear might lead to worse overall behavior and add complexity. Let me know your thoughts on it. If you feel like there is enough value to smoothing out that load then we can continue to investigate and I'll create a GH issue to track that work.

- During development, we saw some issues with the server where an image would fail to generate. We would want to decide how we want to handle this and how long we'd want to "hold up" the other images from displaying while waiting for one that's lagging behind. In some cases, we saw the image take upwards of 10 seconds to generate from the time the request began. (1). I'm worried this introduces a risk of completely breaking the feature if a server error happens, or make the feature seem overly sluggish. 
- We also want to think about how many images we want to try and download at a time. If we attempt to download all of them we could overwhelm the device's ability to process all of the requests. This could end up in the images being downloaded even slower and cause the user to sit and wait patiently which I fear might be frustrating. By batching the requests we could end up in a situation where if the total is separated into three batches then it could be upwards of 30 secs before the user sees anything. (2)
- One way we might be able to achieve this goal is to throttle the updates so that you only see images load in every `#` seconds. So if we say you see an update every 2 seconds then that might help. On iOS, the containers that display the design thumbnails are reused so we would want to consider conditions where an image downloaded but then the image scrolled off-screen and changed to a different design. I think this adds enough complexity where I would be hesitant to include it here.  

(1) Once the image is generated we cache it and it's available so only a very small number of users will ever experience this lag for an image. Hopefully, this lag will be mostly internal team members as were testing and verifying a new site design. 
(2) The way the code works today is we ask for the images that are on the screen and display them once they load there currently isn't a relationship from one to the other to throttle the updates. If a layout is scrolled offscreen then we stop waiting and will try and load the next set. 

> I'd mentioned this in a previous PR but I think it would be useful to add the Skip option to the domains screen

I think we still need more research before we charge forward with this. I went ahead and created an issue to track this though and added my initial research. https://github.com/wordpress-mobile/gutenberg-mobile/issues/2828 

We were able to get some of the V2 items work for the code cut off but I feel like this is something that won't make it until next release. Let me know if you feel like it's a higher priority though. 

> On the Choose a Domain screen, the "Search Domains" placeholder text looks too small, what size are we using for that?

I reused the same search control from the other flow for this which had it set to a style defined in the style guide as the default search bar text attributes. Which seems to translate to the [system's preferred size of footnote](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/) so if have the default accessibility font size set this would translate to 13 points. 

Searching through the code this looks like this is used for other search bars as well so let me know if you'd like to see some other options and explore making this a one-off case I'm happy to take some screenshots of some other cases. If I get time today I'll come back through and post those in another comment. 


> I think we should change the wording of the sub-text on the Choose a Design screen from ...

Given our other discussions, I think think this is a good idea. I'll go ahead and make this change in the bug fix branch.

**Comment by kyleaparker** [comment]
>I see what you mean. Having a more uniform loading might help make the experience more smooth. I came up with a few scenarios while thinking about this that I fear might lead to worse overall behavior and add complexity. Let me know your thoughts on it. If you feel like there is enough value to smoothing out that load then we can continue to investigate and I'll create a GH issue to track that work.

Ahh yes I see how this could cause more potential problems. I think this is another one we can leave as is for V1 and possibly investigate other options for V2. 

>I think we still need more research before we charge forward with this. I went ahead and created an issue to track this though and added my initial research. wordpress-mobile/gutenberg-mobile#2828

Sounds good, I don't think there is any rush on this so investigating it during V2 works for me

>Searching through the code this looks like this is used for other search bars as well so let me know if you'd like to see some other options and explore making this a one-off case I'm happy to take some screenshots of some other cases. If I get time today I'll come back through and post those in another comment.

It seems small to me, but if we are using it throughout the app let's keep it as is for now

>Given our other discussions, I think think this is a good idea. I'll go ahead and make this change in the bug fix branch.

Thank you!

**Review by Tug — APPROVED** [review]
LGTM 👍

**Pull request merged**
