### PR TITLE
Adds display name to Me tab

### LINKED ISSUE #3971: Add display name to Me tab
Both WordPress.com and Android show the display name below the avatar. Let's do it on iOS as well

screen shot 2015-07-03 at 12 56 40
screenshot_2015-07-03-12-56-56

### PR DESCRIPTION
**Pull request by koke**
Save the account's display name and show it in the Me tab, for consistency with Android and WordPress.com

me-tab-add-display-name

@MichaelArestad does this look good? The vertical spacing feels a bit off to me

Fixes #3971 

Needs Review: @MichaelArestad @oguzkocer

### CODE REVIEW

**Comment by koke** [comment]
If I remove the margin between the display name and the username, it looks slightly better

me-display-name-v2

**Comment by oguzkocer** [comment]
Code looks good :shipit:

**Comment by MichaelArestad** [comment]
I would reduce the space between the display name and username slightly. I would also increase the space above the gravatar to optically match the space below the username.

**Comment by koke** [comment]
@MichaelArestad something like this?

ios simulator screen shot 08 jul 2015 19 54 08

**Comment by MichaelArestad** [comment]
Yep! LGTM!

**Comment by koke** [comment]
@SergioEstevao I merged develop and re-added the `displayName` attribute to the data model, can you take a look just to be safe?

**Comment by SergioEstevao** [comment]
:shipit:

**Pull request merged**
