### PR TITLE
Updated editor pod to latest

### PR DESCRIPTION
**Pull request by bummytime**
Fixes https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/65

/cc @diegoreymendez

### CODE REVIEW

**Comment by bummytime** [comment]
@sendhil Would you mind taking a peek at this one?

**Comment by sendhil** [comment]
@bummytime  this looks fine but would you mind taking a look at this one - https://github.com/wordpress-mobile/WordPress-iOS/pull/3038 and merging it in if it looks ok before you merge this one in?

**Comment by sendhil** [comment]
@bummytime eek - looks like this one won't merge as a result of #3038... mind updating it or just re-submitting it?

**Comment by bummytime** [comment]
Closing this for now.

**Pull request closed without merging**
