### PR TITLE
Implementing WordPressAuthentication.framework 

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR implements WordPressAuthentication.framework:

- Moves over all of the Authentication-Y classes.
- Adds several missing imports.
- Exposes few internal types that are being used by the main app.

### Notes:
The following IB were relying on components that are now part of the Authentication framework (ie. **NUXButton** / **SearchTableVIewCell**. 

We've patched them so that such components are now picked up from the right bundle (`WordPressAuthenticator`). I'm adding this for documentation purposes: not happy with the change, but works _for now_:

```
TextWithAccessoryButtonCell.xib
SignupEpilogueCell.xib
JetpackLoginViewController.xib
SignupEpilogue.storyboard
SiteCreation.storyboard
NoResults.storyboard
```

---

@nheagy @ScoutHarris @frosty @bummytime: Ladies and gentlemen, this PR is officially UP for review. 

Since the Test Cases are HUGE i suggest we split them (maybe we can coordinate over Slack?).
We'll merge on three Squirrels :shipit:. Suggestions / observations are always more than welcome.

Thank you all!!!

cc @astralbodies @elibud @aerych 

---

### Scenario(s): WordPress.com Login
- Log into a WordPress.com Account with Username + Password + 2FA Token (Manually Type it!)
- Log into a WordPress.com Account with Username + Password + 2FA Token (Get the SMS!)
- Log into a WordPress.com Account with Username + Password
- Log into a WordPress.com Account with Magic Link
- Log into a WordPress.com Account with Google!
- Log into a WordPress.com Account with 1Password Integration
- Log into a WordPress.com Account, by pressing `enter your site address`, and entering a WordPress.com URL + Username + Password

Please, for each scenario, verify that the Epilogue shows up correctly, and that your blogs are properly sync'ed.

---

### Scenario: WordPress.org Login
1. Fresh Install
2. Log into a WordPress.org Site

Please verify that the Epilogue shows up correctly, and that your blog shows up in `My Sites`.

---

### Scenario: Jetpack Login
1. Log into a WordPress.org Site (that's connected to a dotcom account!)
2. Press `My Sites` > `Stats`
3. Log into the associated WordPress.com Account

Please, verify that the WordPress.com account is properly connected.

---

### Scenario: WordPress.com Signup
1. Signup for a new account using Email + Password
2. Signup for a new account using Google

---

### Scenario: Site Creation
1. Log into an account that has no Sites
2. Press the `My Sites` tab
3. Press over `Add New Site`
4. Press over `Create WordPress.com site`

Please: review the whole Site Creation flow!

### CODE REVIEW

**Comment by bummytime** [comment]
> Scenario: WordPress.org Login

- [X] Fresh Install
- [X] Log into a WordPress.org Site
- [X] Epilogue shows up correctly
- [X] blog shows up in My Sites

.org sites (no JP) seems to be working great @jleandroperez

**Comment by bummytime** [comment]
> Scenario(s): WordPress.com Login

- [X] Log into a WordPress.com Account with Username + Password + 2FA Token (Manually Type it!)
- [X] Log into a WordPress.com Account with Username + Password + 2FA Token (Get the SMS!)
- [X] Log into a WordPress.com Account with Username + Password
- [X] Log into a WordPress.com Account with Magic Link
- [X] Log into a WordPress.com Account with Google!
- [X] Log into a WordPress.com Account with 1Password Integration
- [X] Log into a WordPress.com Account, by pressing enter your site address, and entering a WordPress.com URL + Username + Password

Looking good on .com for me!

### (Tested on both 10.3 and 11 devices)

**Comment by jleandroperez** [comment]
@bummytime thanks SOOOO MUCH for your time!!!

**Comment by bummytime** [comment]
> Scenario: Jetpack Login

- [X] Log into a WordPress.org Site (that's connected to a dotcom account!); Press My Sites > Stats; Log into the associated WordPress.com Account

JP-connected .org works across devices

**Comment by bummytime** [comment]
> Scenario: WordPress.com Signup

- [x] Signup for a new account using Email + Password
- [x] Signup for a new account using Google

Signup tested well for me!

**Comment by bummytime** [comment]
> Scenario: Site Creation

- [x] Log into an account that has no Sites
- [x] Press the My Sites tab
- [x] Press over Add New Site
- [x] Press over Create WordPress.com site
- [x] Please: review the whole Site Creation flow!

I smoke tested this as well as I could and found no issues.

**Comment by jleandroperez** [comment]
@bummytime BEST friday EVER ❤️ . Thank you!!!

**Comment by frosty** [comment]
Working my way through the list...

**Scenario: WordPress.org Login:**

- [x] Fresh Install
- [x] Log into a WordPress.org Site

**Scenario: Jetpack Login:**

- [x] Log into a WordPress.org Site (that's connected to a dotcom account!)
Press My Sites > Stats
- [x] Log into the associated WordPress.com Account

Looking good!

**Comment by frosty** [comment]
**Scenario: WordPress.com Signup:**

- [x] Signup for a new account using Email + Password
- [x] Signup for a new account using Google

**Scenario: Site Creation:**

- [x] Log into an account that has no Sites
- [x] Press the My Sites tab
- [x] Press over Add New Site
- [x] Press over Create WordPress.com site

**Comment by jleandroperez** [comment]
@frosty @bummytime @nheagy Thanks **A LOT** for your time + help!!!. `Podfile.lock` conflict solved. Merging whenever Buddybuild turns green!!

🔥

**Pull request merged**
