### PR TITLE
Issues/3612 reader featured attachment fix

### LINKED ISSUE #3612: Attached image not in a gallery is used as a featured image
When you have an attached image which is not inserted a post, it shows up as a featured image on the iOS app. This seems to happen only when other images are added to the post as a gallery.

Steps to reproduce:
1. Upload 3 images.
2. Create a gallery with 2 of the images, leaving the last uploaded image.
3. Publish the post.
4. View the post on your Reader feed. The last image which in not included in the post will show up as a featured image.

### PR DESCRIPTION
**Pull request by aerych**
Fixes #3612 

To test:
#### Scenario 1
- Follow the updated steps in the issue to create a post with only text content, but with an image attachment.  Do this on a blog you follow in the reader.  Bonus: confirm the attachment via the REST API console.
- View your Following feed in the reader.  Confirm the post appears and the attachment does not appear as a featured image in either the Reader's post list or post detail. 

#### Scenario 2
- On a blog you follow, create a new post and upload an image to the post. 
- Edit the image so it is a thumbnail. Make sure its width is around 100px to ensure it would normally be ignored as a featured image.
- View your following feed in the reader.  Confirm the post appears and the attachment is shown as a featured image in the post list.

Needs review: @kurzee would you kindly?

### CODE REVIEW

**Comment by kurzee** [comment]
@aerych for scenario 1, I followed the steps to attach a post without inserting it. The attachment, as confirmed in the console, does indeed still show as a featured image in the Reader card for this post: https://testkurzee.wordpress.com/2017/01/25/post-with-attachment-no-insertion/

**Comment by kurzee** [comment]
For scenario 2: everything checks out. However, for this post: https://testkurzee.wordpress.com/2017/01/25/post-with-smaller-edited-thumbnail/ the Reader card displays the featured image in the app while the web does not.

**Comment by kurzee** [comment]
Looks like the test `testFeaturedImageFromDictionary` is failing in `ReaderPostServiceRemoteTests`.

**Comment by aerych** [comment]
> for scenario 1

In the rest console I see that the image appears in the featured_media field.
screen shot 2017-01-25 at 3 13 20 pm

Maybe try posting via wp-admin instead of Calypso

**Comment by kurzee** [comment]
>Maybe try posting via wp-admin instead of Calypso

FWIW, I posted that one via the app. But I'll try with both Calypso and wp-admin.

**Comment by aerych** [comment]
> FWIW, I posted that one via the app

Oh interesting.  TIL images posted via the app show up as featured media.

**Comment by aerych** [comment]
> the Reader card displays the featured image in the app while the web does not

This is fine. Calypso doesn't consider attachments when selecting an image to feature (but maybe it should!).   We still consider a card with an image to be better than a card without one.

**Comment by kurzee** [comment]
This post, posted via Calypso, shows a featured image in the app for both the card and detail, while the web does not: https://testkurzee.wordpress.com/2017/01/25/post-with-inserted-then-deleted-media/

This post, posted via wp-admin, shows no featured image in neither the app nor web: https://testkurzee.wordpress.com/2017/01/25/wp-admin-post-inserted-media-and-then-deleted/

**Comment by kurzee** [comment]
My impression, if I had inserted media and then deleted it from the post content, I would definitely want it to _never_ show up in any way for a post. Maybe I have this backwards?

**Comment by aerych** [comment]
> Looks like the test testFeaturedImageFromDictionary is failing

Doh!  I overlooked that test.  Fixing

**Comment by aerych** [comment]
> My impression, if I had inserted media and then deleted it from the post content, I would definitely want it to never show up in any way for a post. Maybe I have this backwards?

No, I think that's correct.  The featured_media behavior is something I wasn't aware of.  Let's patch that while we're at it.

**Comment by aerych** [comment]
@kurzee Okay, test fixed and I've added a check to ensure featured_media exists in the post content as well.  Retested on your sample posts and everything seems to be the way we want. 
Ready for another peek at your leisure sir.

**Comment by aerych** [comment]
Thank ya @kurzee !!

**Pull request merged**
