### PR TITLE
Tapping post shows editor in preview mode.

### LINKED ISSUE #3899: Post/Pages: tapping on a post should open the post in view-mode.
Right now the app considers a tap in the post's body as an edit request.  Tapping on a post in the posts list should open the post in view-mode (read-only mode) instead.

### PR DESCRIPTION
**Pull request by aerych**
Closes #3899 

To test:
Open the post list and tap a post. 
The editor should be in preview mode. 
Return to the list and tap the Edit button in one of the post cards.
The editor should open in edit mode. 

Needs Review: @diegoreymendez

### CODE REVIEW

**Comment by diegoreymendez** [comment]
:shipit:

**Comment by aerych** [comment]
Thanks Diego!

**Comment by sendhil** [comment]
@diegoreymendez @aerych for this the behavior on the web is to do the tap to edit... perhaps we should return to that to be consistent?

**Comment by diegoreymendez** [comment]
@sendhil - Well... we could do that, but then I'd suggest removing the edit button (since it wouldn't be needed) and the read-only editor mode (since it wouldn't be used / accessible).

My opinion is that we could really do without the read-only mode in this section of the app, since it's not the reader.  I'd involve the editor designers into this discussion though - maybe in a separate issue

Thoughts?

**Pull request merged**
