### PR TITLE
Reader: better voiceover support in cells

### PR DESCRIPTION
**Pull request by ctarda**
Implements the second part of #8667 

- I have maintained the button with the author name, blog title and published date as an independent control, because its action (browsing all the posts from that blog) is different than the action when tapping the cell (browsing the selected post in detail)
- I have still kept the `Accessible` interface around, but it seems unnecessary. I would still like to keep it around while I work on some other voiceover-related tickets, to decide if it actually helps or just adds unnecessary clutter.

img_2544
img_2545
img_2546

To test:
- Navigate to Reader
- Activate Voiceover
- Tap a cell.

Expected behaviour: voiceover should be able to identify the following:
- Autor+blog title+ published date as a single control
- Post body
- Visit button
- Share button
- Like button
- Comments button
- More button

### CODE REVIEW

**Comment by etoledom** [comment]
Looking good!
In overal the VoiceOver experience is already a lot better than before.

Just a couple of small details about some VoiceOver texts:

- The text in the cell header I think its missing the Author's name, and the fact that it is related with the post content bellow it. If I test it closing my eyes is difficult to figure out that they are related. I would change it to something like: 
-`Post by $user_name, from $blog_name` or
-`From $blog_name by  $user_name`

- Related to that button, when you tap on it to open the Blog's posts list, it uses the same cells but the behavior of that header button changes to open the actual post. It would be good that the hint also reflect that change.

- The like button reflect a state. We could be more explicit about it, so the user doesn't need to wait for the hint to know the state of the button. (An example in the Twitter like button or many of the stateful buttons in Spotify)

- The visit button, I would highlight that the post will be opened in a web view. The experience there is completely different for a VoiceOver user than opening the post natively.

- An idea regarding the previous point, maybe is also good to point out that by double tapping in the post, it can be opened to get the full text.

**Comment by ctarda** [comment]
Thanks for the comments, @etoledom 😉 

I have pushed a few commits that I believe address all of them. One thing to have in mind is that I tried to follow Apple's suggestions when it comes to labels and hints: [Crafting Useful Labels and Hints](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/iPhoneAccessibility/Making_Application_Accessible/Making_Application_Accessible.html#//apple_ref/doc/uid/TP40008785-CH102-SW6)

Also, I have temporarily marked a button in `ReaderDetailViewController` as not available for VoiceOver. I will add a ticket to improve VoiceOver support in that specific View Controller.

**Comment by etoledom** [comment]
Great! All the changes look good!

I found this last small button without labeling. I'm not sure if it's better to label it or to hide it (for VoiceOver). If we label it, it might be good to check its tap area since it seems to be too small for a proper VoiceOver experience (also for tapping in general).

artboard

**Comment by ctarda** [comment]
I completely missed this cell was used in more than one list 😊  I have added support for it, but I didn't do anything abut the size I think it might be worth discussing if the icon should be bigger.

**Comment by ctarda** [comment]
^ @etoledom

**Comment by etoledom** [comment]
Great!

**Pull request merged**
