### PR TITLE
Logout: Let's be friendly!

### LINKED ISSUE #3164: Add a message informing the user they will lose any local drafts on sign out

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR implements an improved Logout Text:

- Whenever there are local changes, not persisted in the backend, the Logout Confirmation will read `You have changes to %d posts that haven’t been uploaded to your site. Logging out now will delete those changes. Log out anyway?`
- Whenever there are no local changes, the text will just say `Log out of WordPress?`

This one goes to our friend @sendhil, who filed the issue 3 years + nearly 5 months ago. If you ever get this ping, **WE MISS YOU AROUND!!!**

Closes #3164 

@ScoutHarris may i bug you with a hopefully fun review?. Thanks in advance!!

### Scenario: No Local Changes
1. Log into WPiOS
2. Press the `+` button
3. Type anything! (Title or Body)
4. Dismiss the editor
5. Wait a few seconds, so that the post is sync'ed with our backend
6. Press `Me` > `Logout`

Verify that the text reads `Log out of WordPress?`. 

### Scenario: Local Changes
1. Log into WPiOS
2. Turn off the device's WiFi
3. Press the `+` button
4. Type anything! (Title or Body)
5. Dismiss the editor
6. Press `Me` > `Logout`

Verify that the confirmation alert reads as follows:

```
You have changes to %d posts that haven’t been uploaded to your site. Logging out now will delete those changes. Log out anyway?
```

### CODE REVIEW

**Comment by nheagy** [comment]
@jleandroperez can you attach a screenshot of the new alerts?

**Comment by jleandroperez** [comment]
@nheagy sure!. Ain't this cute? Thanks for checking this out!!

simulator screen shot - iphone se - 2018-06-21 at 16 29 15

simulator screen shot - iphone se - 2018-06-21 at 16 29 02

**Comment by jleandroperez** [comment]
@ScoutHarris good catch!! would something like this work well?. (Plurals would look as before!).

Thanks in advance!

simulator screen shot - iphone se - 2018-06-22 at 15 02 44

**Comment by jleandroperez** [comment]
@ScoutHarris yyyyeah i kinda did that on purpose!!! but since the idea didn't really fly far away, i've patched the string to look as suggested (thanks for the feedback!!!)

Ready for one laaast check, thanks a lot!!!

**Comment by ScoutHarris** [comment]
Thank you @jleandroperez ! It looks great! :shipit:

**Comment by jleandroperez** [comment]
Thanks a lot @ScoutHarris !!!

**Pull request merged**
