### PR TITLE
Make code signing options for debug mode generic.

### PR DESCRIPTION
**Pull request by SergioEstevao**
This options should make easier for all developers to build the project in Debug mode.
Instead of hard coding Automatic profiles we should use the generic iOS Developer identity and the Automatic profile option.

Needs Review: @astralbodies

### CODE REVIEW

**Comment by astralbodies** [comment]
I don't think this is going to work as we do need to specifically pull the proper profile to ensure the Today extension, keychain groups, etc are all in place. I'll verify it later this week.

**Comment by SergioEstevao** [comment]
@astralbodies I tried it on my laptop and it worked, but maybe I'm missing something.

**Comment by astralbodies** [comment]
I pushed a small update with the new App Store and Internal distribution profiles. FWIW the `Distribution` build configuration should match `Release`. In fact, we could probably just get rid of `Distribution` as we do not use it anywhere.

**Comment by astralbodies** [comment]
As far as I can tell this change does work - I want to say there used to be some condition where it wouldn't work right. We may have cleaned up the dev profiles enough where this isn't a problem matching the right profile any more. Lets go with this for now and if we run into any problems its not a big change to go back. :+1: :shipit:

**Pull request merged**
