### PR TITLE
Allow the Pages list to listen to Core Data changes

### PR DESCRIPTION
**Pull request by dvdchr**
Refs #16370

This fixes the issue where the Pages list doesn't refresh after making changes (e.g. adding a new page). As mentioned in https://github.com/wordpress-mobile/WordPress-iOS/issues/20647#issuecomment-1603357554, this was a legacy part of the codebase where the view controller is configured to not listen to Core Data changes.

This PR simply removes that line, so the view controller now subscribes to Core Data changes. The `listensForContentChanges` property defaults to true if the table handler has a delegate: 

https://github.com/wordpress-mobile/WordPress-iOS/blob/ddb7cd7bc436170f6814d9e9d4f77417153e4309/WordPress/Classes/Utility/WPTableViewHandler.m#L55-L58

## To Test

1. Go to My Sites > Pages.
2. Go to the Draft section.
3. Create a new page.
4. Save the page as a draft.
5. 🔎 Verify that the new draft appears on the list.

## Regression Notes
1. Potential unintended areas of impact
Core Data traffic for this screen will increase with this change.

6. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the changes.

7. What automated tests I added (or what prevented me from doing so)
N/A.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

N/A, this doesn't introduce any UI changes.

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by wargcm — COMMENTED** [review]
I'm not seeing the new page appear until I pull to refresh.

https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/e8f6553d-3f23-4ce6-9620-c10305938e31

**Comment by dvdchr** [comment]
I'm converting this back to a draft. After looking at this further, it seems there's something wrong with the table view handler setup. When `listensForContentChanges` is enabled, the filter tabs stop working after creating a new draft Page.

For example, if you were in the Draft tab and created a new Page from there, all the other tabs will show contents for the Drafts tab. I'll need more time to look into this.

Interestingly, I've found that `PageListViewController` didn't get its `viewWillAppear` or `viewDidAppear` methods called.  Even though `listensForContentChanges` is set to `false`, `PageListViewController` has set up some refresh calls in the `viewWillAppear`; but since this method is not called after returning from the editor, the view is not updated.

**Comment by mokagio** [comment]
Bumping to 23.3 because I'll be starting the 23.2 code freeze soon and this is still a draft.

**Comment by mokagio** [comment]
Bumping from [23.3](https://github.com/wordpress-mobile/WordPress-iOS/milestone/257) to [23.4](https://github.com/wordpress-mobile/WordPress-iOS/milestone/258) because I'm about to start the code freeze and this is a draft.

**Comment by dvdchr** [comment]
Thank you, @mokagio. I will remove the milestone for now until there's more capacity to pick this up.

**Comment by dvdchr** [comment]
Closing this in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/20647#issuecomment-1800842489.

**Pull request closed without merging**
