### PR TITLE
Improve Dynamic Type accessibility for Posts list

### PR DESCRIPTION
**Pull request by ctarda**
Implements part of #8909 (Posts List only)

Before:
simulator screen shot - iphone 8 - 2018-03-19 at 16 13 54

After:
simulator screen shot - iphone 8 - 2018-03-19 at 16 20 46

I have touched the FilterTabBar, so, @frosty I'd appreciate if you could take a look as well.

I think we should rewrite parts of `PostCardTableViewCell` to base the UI implementation on a set of nested stack views, but I also think that might be out of the scope of this story. If that's not the case, I would be happy to spend more time on this 😊 

To test:
1. Navigate to posts list
2. Change font size

### CODE REVIEW

**Comment by ctarda** [comment]
@etoledom I will play with it again, but there is code that makes that header of a fixed height, and to be honest, I am really scared to touch it, because the only way I see to make that header grow vertically is by redoing the whole cell's layout. I'll give it another try though 😄

**Comment by ctarda** [comment]
I just pushed another update, thanks for the nudge in the right direction, @etoledom ! 🤗

**Comment by etoledom** [comment]
The header is looking great! 🎉

@frosty 
>I also noticed (not a big issue, and perhaps it's okay to leave it), that in some situations, the bottom of the body label gets cut off.

I'm not sure that small detail is worth the trouble. As @ctarda said, it's probably a good idea to remake this cells using stack views in the future, and we will avoid that issue and other couple of very small details.

I think its ✅ to :shipit: .

@SylvesterWilmott any comment about the font size in the FilterBar?

**Comment by frosty** [comment]
@etoledom I agree with your comment - although it's probably not even worth remaking this cell at this stage, as I think there's a plan to completely update the design of the posts list anyway. :)

**Pull request merged**
