### PR TITLE
Tenor GIF picker for Gutenberg editor

### PR DESCRIPTION
**Pull request by ngoctr**
This added Tenor Picker support for Gutenberg editor as part of #13803.

# Testing
**First steps**
1. Register your Tenor developer API here: https://tenor.com/gifapi
2. Check out this branch
3. Put your API Key into `.configure-files/wpcom_app_credentials` (TENOR_API_KEY line)
4. Run `rake dependencies`
5. Build and run

**Verify Tenor support in Gutenberg Editor**
1. Go to Site -> Posts
2. Tap any Post to edit it, if you are using Classic (Aztec) Editor, you will need to switch to Block Editor.
3. Tap the + button at the bottom left corner
image
4. Choose an _Image_ or _Gallery_ block
image
5. Tap *ADD IMAGE* button to activate the media picker
image
6. Choose *Free GIF Library*
7. Search and select the GIF(s) you want to insert, then tap **Add** button at the bottom right corner
image
8. Verify the selected GIF(s) have been added into the Post

There are other flows in the Block Editor also involved the Tenor Picker that you should also make tests:

- Replace an image: 
image
- Media & Text block:
image

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes. **(Will be in a separate PR)**
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary. **(Will be in a separate PR)**

### CODE REVIEW

**Comment by ngoctr** [comment]
@ScoutHarris I noticed the same issue with Stock Photos too, it's not just happened only with GIFs.

**Comment by ScoutHarris** [comment]
> I noticed the same issue with Stock Photos too, it's not just happened only with GIFs.

Aaaahh. Would you mind creating an issue in the [gutenburg repo](https://github.com/wordpress-mobile/gutenberg-mobile) (if one doesn't already exist) and we'll reference that here.

**Comment by ngoctr** [comment]
> > I noticed the same issue with Stock Photos too, it's not just happened only with GIFs.
> 
> Aaaahh. Would you mind creating an issue in the [gutenburg repo](https://github.com/wordpress-mobile/gutenberg-mobile) (if one doesn't already exist) and we'll reference that here.

Sure, I will do that. If I do update the Post before previewing, then everything is working ;-)

**Comment by ScoutHarris** [comment]
> If I do update the Post before previewing, then everything is working

Well you know very well people are _not_ that patient. How do you think I found it? 😆

**Comment by ngoctr** [comment]
> > If I do update the Post before previewing, then everything is working
> 
> Well you know very well people are _not_ that patient. How do you think I found it? 😆

Haha, I see 😃 Thanks @ScoutHarris for approving this.

**Pull request merged**
