### PR TITLE
rake dependencies: Check if Podfile matches Podfile.lock

### PR DESCRIPTION
**Pull request by jtreanor**
Currently, if you run `rake dependencies` after making changes to the `Podfile`, nothing happens. This is because `bundle exec pod check` only checks if `Podfile.lock` and `Pods/Manifest.lock` match.

This PR updates `rake dependencies` to also check if the checksum in `Podfile.lock` matches the `Podfile` (Thanks @koke for the idea!).

The downside is that `rake dependencies` isn't as fast if you have no changes. I think its a trade off worth making.

I'll open a PR for https://github.com/square/cocoapods-check to see if they will accept a change so we don't need to do this.

To test:

- Make any change to `Podfile`
- Run `rake dependencies`

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by jtreanor** [comment]
I have opened a PR for `cocoapods-check` here: https://github.com/square/cocoapods-check/pull/11

**Comment by koke** [comment]
I think `dependencies` is still running automatically on the `post-merge` and `post-checkout` hooks, so it might add a good amount of friction there

**Comment by jtreanor** [comment]
@koke Oh, I didn't realise those were there. Do you think are the hooks still useful?

I think we can either remove the hooks or live with this issue (hopefully it will be fixed in `cocoapods-check`).

**Comment by koke** [comment]
I don't do much development here lately, but it's one of the things I've been missing on gutenberg-mobile. To me it was very useful to be able to check out a PR and not even have to think about whether I had to run pod install or not.

Adding that check to `cocoapods-check` is probably better but meanwhile we can also have it in the Rakefile. Like this, but with proper error handling 😉 

https://gist.github.com/koke/ea8ae5251193fbec4a45bf5b09bf419e

**Comment by jtreanor** [comment]
This is now updated to use your suggested implementation alongside `pod check`. This feels like it gives the best of both worlds.

**Pull request merged**
