### PR TITLE
Quick Start: remove duplicated line in release notes

### PR DESCRIPTION
**Pull request by momo-ozawa**
## Description
- Removes a duplicated note in the release notes (Thanks @tiagomar for the heads up 🙏 )

## Regression Notes
1. Potential unintended areas of impact
n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a

3. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by momo-ozawa** [comment]
> This PR contains changes to RELEASE_NOTES.txt.
Note that these changes won't affect the final version of the release notes as this version is in code freeze.
Please, get in touch with a release manager if you want to update the final release notes.

Hey @mokagio! 👋 
No major changes to the release notes -- just wanted to get rid of a duplicated line.

**Review by tiagomar — APPROVED** [review]
Looks good to me! =)
:shipit:

**Comment by mokagio** [comment]
Good catch @momo-ozawa @tiagomar 👏 

I forgot to update this file when doing 4ec2364eca 🤦‍♂️

**Comment by mokagio** [comment]
Safe to merge 👍

**Pull request merged**
