### PR TITLE
WordPressAuthenticator: pass the new style parameter for spinner color when NUXButton is disabled

### LINKED ISSUE #2716: Log In: some colors are off in dark mode
- [x] The spinner color makes it not visible at all in dark mode; it's visible in light mode (this is new in release 4.9, potentially due to color changes in `AuthenticationManager` in this PR https://github.com/woocommerce/woocommerce-ios/pull/2644

example 1 | example 1
-- | --
Simulator Screen Shot - iPhone 11 Pro - 2020-08-26 at 15 47 43 | Simulator Screen Shot - iPhone 11 Pro - 2020-08-26 at 15 41 19

~~- [ ] The colors of the site address after entering site address look odd (this is pre-existing)~~ (update: this screen is no longer shown in the new UL&S)

### PR DESCRIPTION
**Pull request by jaclync**
Fixes https://github.com/woocommerce/woocommerce-ios/issues/2716
WordPressAuthenticator PR: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/562

- [x] ⚠️ Update pod to release version after https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/562 is merged ⚠️ 

## Changes

This PR set the new style parameter `WordPressAuthenticatorStyle.disabledButtonActivityIndicatorColor` to the same value as before (`WordPressAuthenticatorStyle.secondaryTitleColor`).

## To test

- Run `bundle exec pod install --repo-update`
- Launch the app in logged out state, or log out from the app
- Tap "Continue with WordPress.com"
- Enter an email
- Tap "Continue" --> the spinner color should look the same as before
- Go back to the prologue screen
- Tap "Enter your existing site address"
- Enter a site address
- Tap "Continue" --> the spinner color should look the same as before

## Example screenshots

(No changes are expected!)

\ | before | after
-- | -- | --
log in with email | Simulator Screen Shot - iPhone 8 Plus - 2021-01-14 at 17 06 36 | Simulator Screen Shot - iPhone 8 Plus - 2021-01-14 at 17 31 07
log in with site address | Simulator Screen Shot - iPhone 8 Plus - 2021-01-14 at 17 07 07 | Simulator Screen Shot - iPhone 8 Plus - 2021-01-14 at 17 31 18

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ScoutHarris — APPROVED** [review]
Hey @jaclync . I assumed this was ready for review since the Auth PR was. Tested fine. Thanks for updated WPiOS!

:shipit:

**Comment by jaclync** [comment]
Hey @ScoutHarris thanks for reviewing this one as well! I updated the pod to release version in https://github.com/wordpress-mobile/WordPress-iOS/pull/15639/commits/8fca76928f8fae335d88b37f8f44abeeb82cbb3c and tested again. Do you think it's good to merge this PR now?

**Comment by ScoutHarris** [comment]
Aw. Sadly you now have a conflict. 😆 But otherwise yea. This branch picked up `1.34.0-beta.1` so once you do the resolution dance, feel free to merge!

**Comment by jaclync** [comment]
Haha that happens, taking advantage of the quiet time now. Fixed the merge conflicts in https://github.com/wordpress-mobile/WordPress-iOS/pull/15639/commits/2c10103f267018c3a49c72e2558ef3865f8920ad, merging now!

**Pull request merged**
