### PR TITLE
Merge Release/12.9 into Release/13.0

### PR DESCRIPTION
**Pull request by loremattei**
This PR merges the latest fixes in 12.9.1 into 13.0, since the fixes in #12270 don't seem to be in 13.0 yet.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by jklausa** [comment]
hm, mine changes should have been pulled in already via this: https://github.com/wordpress-mobile/WordPress-iOS/pull/12271

**Comment by loremattei** [comment]
You are right. They seem to be there. Did you cherry-pick them from a branch to another (GitHub UI sometimes does weird things with cherry-picked commits... the actual merge is good though)?

**Comment by jklausa** [comment]
Yeah, I cherry-picked them off of develop, i think

**Comment by loremattei** [comment]
Ok, cool. It seems it's the same for Frosty's changes. I checked and they're already in `release/13.0` with a different commit hash. 
I'm just closing this PR so.

**Pull request closed without merging**
