### PR TITLE
Fix exit animation of notices

### LINKED ISSUE #18019: Notices are glitching while being dismissed
### Expected behavior
Notices should be dismissed in a smooth manner. They should either fade out in place, or fade out while animating downwards out of the screen.

### Actual behavior
Notices glitch while being dismissed.

### Steps to reproduce the behavior
1. Enable quick start for a site
2. Go back to My Site
3. Tap Customize Your Site
4. Tap on a step and follow through
5. When done with a step, a notice for the next step will be automatically shown
6. Press Not now
7. Observe the notice being dismissed with a glitchy animation

https://user-images.githubusercontent.com/25306722/155451991-52f85fa5-aecb-4578-aa78-9bf869d4ae0e.MP4

**This is global to all notices not just quick start notices. Same occurs with notice in grow audience tips from stats**

https://user-images.githubusercontent.com/25306722/155452592-1e8de08d-bad5-46dd-b5ef-378aeb99d395.MP4

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Fixes #18019

## Description
- Fixed issue that caused the change in vertical position of notices to not be animate on dismissal 7604a49983e712ca4024d2caebeef2b392d50e49
- Modified the dismissal animation to move the whole notice off-screen instead of moving it to the bottom of the screen.

Normal Animation Speed

https://user-images.githubusercontent.com/25306722/159398891-c9d13c93-962d-4257-8506-be3727be60a4.mp4

Slowed down Animation Speed

https://user-images.githubusercontent.com/25306722/159398962-0747b6b8-8ce4-4384-a82b-19bdc2933b39.mp4

## Testing Instructions
1. Enable quick start for a site
2. Go back to My Site
3. Tap Customize Your Site
4. Tap on a step and follow-through
5. Observe the animation of replacing a notice with a new notice; it should be smooth. 
6. When done with a step, a notice for the next step will be automatically shown
7. Press Not now
8. Observe the notice being dismissed with a smooth animation

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hassaanelgarem** [comment]
@osullivanchris I based the current implementation on the animation you shared [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/18019#issuecomment-1061704941). However, I didn't apply all the exact properties cause I found these were already defined before. 

Mainly what's different is:
- Speed of transition: 1 second instead of 0.3
- Delay before disappearing: 5 seconds instead of 3
- Distance moved up and down: This depends on the height of the notice and is not constant. But it moves down till it's no longer visible. And moves up till it's right above the tab bar.

Let me know what you think!

**Review by momo-ozawa — APPROVED** [review]
Works as described! Looks great ✨

**Comment by osullivanchris** [comment]
@hassaanelgarem thanks for all the details! I was just defining in absence of existing definitions. The values you have shared sound fine. The outcome looks really good anyway, much smoother. 

I noticed a couple details that felt a bit clunky. They're more about transitions between steps, than the animation, so might be out of scope here.

- For the homepage task, when I started from the dashboard, the delay after I tap 'Site menu' feels slightly too long. Maybe this applies whenever the user gets 'Tap site menu' first. I haven't checked.
- On the reader task, on the last step when I tap search, the way the notice disappears behind the keyboard feels a bit off

**Comment by hassaanelgarem** [comment]
> For the homepage task, when I started from the dashboard, the delay after I tap 'Site menu' feels slightly too long. Maybe this applies whenever the user gets 'Tap site menu' first.

@osullivanchris This indeed applies whenever "Tap site menu" step is performed. We deliberately add this delay to fix a different issue. Without this delay, or if we even decrease it a bit, the next step behaves weirdly. @momo-ozawa Can speak more about this and how easy it would be to fix it. But I'm guessing it won't be an easy fix.

> On the reader task, on the last step when I tap search, the way the notice disappears behind the keyboard feels a bit off.

It does feel off. I will create another issue to track this and will try to address this in a future PR 👍

**Comment by momo-ozawa** [comment]
> We deliberately add this delay to fix a different issue. Without this delay, or if we even decrease it a bit, the next step behaves weirdly. @momo-ozawa Can speak more about this and how easy it would be to fix it. But I'm guessing it won't be an easy fix.

@osullivanchris 👋 

Yep, as @hassaanelgarem mentioned this delay is a workaround to prevent the waypoint from flashing several times after landing on the site menu, if the Quick Start tour was triggered from the dashboard. Previously I was using .5 seconds but that wasn't enough of a delay, so I bumped it up to 1 second.

The delay is necessary because we need the site menu to finish reloading before we scroll / display a waypoint on a menu item to prevent the flashing issue. Unfortunately I don't think there's a simple fix for this since it'll require us to re-work the reloading logic for the site menu.

Linking [this comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/18015#issuecomment-1050782591) for more context

**Comment by osullivanchris** [comment]
@hassaanelgarem @momo-ozawa 
thanks for the explanation re; the 1 second delay. Its not a deal breaker for me. Sounds like you had enough trouble to get this working, and its already really good. So we can park that request 😄 

Glad if we can do something on reader, search, thanks @hassaanelgarem !

**Pull request merged**
