### PR TITLE
Use credentials tool to copy/decrypt credentials intead of referencing the secrets repo path

### PR DESCRIPTION
**Pull request by jtreanor**
Currently, our credentials generation references the `~/.mobile-secrets` path directly. This is a problem for cases where the secrets repo doesn't exist (such as CI).

This is an update to use our existing credentials tool to copy/decrypt the relevant files within the repo. This will allow CI to decrypt these files if needed. It also simplifies the setup for third party contributors (no need to create a `~/.mobile-secrets` directory).

To test:

1. Run `rake dependencies`.
2. Confirm that `wpcom_alpha_app_credentials`, `wpcom_app_credentials` and `wpcom_internal_app_credentials` are present in the `WordPress/Credentials` directory.
3. Open the workspace in Xcode and build & run the app. Confirm WP.com login still works.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
This doesn't work for me – I _think_ it's a me problem – I suspect I don't have the decryption keys? 

The error I'm seeing is:

```
TypeError: [!] no implicit conversion of nil into String
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/bundler/gems/release-toolkit-b57127b313fd/lib/fastlane/plugin/wpmreleasetoolkit/helper/encryption_helper.rb:32:in `key='
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/bundler/gems/release-toolkit-b57127b313fd/lib/fastlane/plugin/wpmreleasetoolkit/helper/encryption_helper.rb:32:in `decrypt'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/bundler/gems/release-toolkit-b57127b313fd/lib/fastlane/plugin/wpmreleasetoolkit/models/file_reference.rb:16:in `source_contents'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/bundler/gems/release-toolkit-b57127b313fd/lib/fastlane/plugin/wpmreleasetoolkit/models/file_reference.rb:43:in `apply'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/bundler/gems/release-toolkit-b57127b313fd/lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb:53:in `apply_file'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/bundler/gems/release-toolkit-b57127b313fd/lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb:17:in `block (2 levels) in run'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/bundler/gems/release-toolkit-b57127b313fd/lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb:16:in `each'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/bundler/gems/release-toolkit-b57127b313fd/lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb:16:in `block in run'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/bundler/gems/release-toolkit-b57127b313fd/lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb:36:in `prepare_repository'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/bundler/gems/release-toolkit-b57127b313fd/lib/fastlane/plugin/wpmreleasetoolkit/actions/configure/configure_apply_action.rb:14:in `run'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/one_off.rb:42:in `run'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/one_off.rb:22:in `execute'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/gems/fastlane-2.127.2/bin/fastlane:23:in `<top (required)>'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/bin/fastlane:23:in `load'
  /Users/jeremymassel/Projects/WordPress-iOS/vendor/bundle/ruby/2.5.0/bin/fastlane:23:in `<top (required)>'
```

If you agree, perhaps we could improve the error messaging for this case? 😅

**Comment by jtreanor** [comment]
Hmm, that’s odd. I think it’s because your local secrets repo is out of date, but that shouldn’t matter since it should check it out as part of applying. I’ll check out what’s happening.

Definitely agree the error message is bad also!

**Comment by jkmassel** [comment]
Ah, I think you're correct! I manually pulled in the latest in my mobile secrets repo, and it now it works! I think there was an issue because my secrets repo couldn't be fast-forwarded. Probably a rare issue 🤷‍♂️

**Comment by jtreanor** [comment]
I'll do some testing to make sure that is the case. If so, we should still have a better error message.

**Comment by jkmassel** [comment]
Update:

1) `rake dependencies` works fine
2) Build the app works fine
3) For some reason I get the "The required `client_id` parameter is missing" message – seems like maybe something is up with the configuration? I can't see why based on the code, and I'm having a hard time tracking it down. I can confirm that it works fine in `develop`, so something in this branch is acting strangely. I'm kind of wondering if we ought to just store complete configuration files in the secret store rather than a file that we then parse and overwrite? If this were just a simple copy it'd reduce the potential for weird issues at the same time. Given that we're reworking all of this stuff now, it might be a good time to do it?

**Comment by jtreanor** [comment]
Thanks @jkmassel! It turns out there was a problem with the paths I had specified to the copied credentials files. It's fixed now.

> I'm kind of wondering if we ought to just store complete configuration files in the secret store rather than a file that we then parse and overwrite? If this were just a simple copy it'd reduce the potential for weird issues at the same time. Given that we're reworking all of this stuff now, it might be a good time to do it?

In my opinion, the advantage of config files like we have now is that they are easy to edit and get started with for external contributors. I'm not against looking at changing this, but given this PR is just moving things along I would suggest doing an overhall of how the system works would fit better in a separate change.

**Pull request merged**
