### PR TITLE
Remove "View Web Version" in stats; also kill WPChromelessWVC

### LINKED ISSUE #3331: Nuke duplicate UIWebView wrappers
We've got several class'es that wrap up UIWebView:

- [x] WPWebAppViewController
- [x] WPWebBridge
- [x] WPChromelessWebViewController

Let's analyze if it's possible to have a single tool to do the job. And if possible, proceed to cleanup the duplicated code.

/cc @aerych =D

### LINKED ISSUE #4550: Remove View Web Stats functionality
Related: https://github.com/wordpress-mobile/WordPressCom-Analytics-iOS/issues/48
Related: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/pull/359

Update the stats pod once https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/pull/359 is merged. Also if the analytics pod is ready for updating, then update it as well to remove the unneeded enum for viewing web stats.

### PR DESCRIPTION
**Pull request by astralbodies**
Closes #4550 
Closes #3331 

This PR:
1. Updates to Stats pod 0.6.0 which removed the "View Web Version" row in the stats period-based stats (Days, Weeks, Months, Years).
2. Updated the stats delegate to remove the optional protocol for opening web stats.
3. Axed the `WPChromelessWebViewController` class and switched over to `WPWebViewController`.

Testing:

Tap rows in stats that normally load in a browser - tags, clicks, referrers. Ensure the page loads.

Needs Review: @jleandroperez

### CODE REVIEW

**Comment by astralbodies** [comment]
cc: @daniloercoli

**Comment by jleandroperez** [comment]
Looking great @astralbodies! Few notes:

- You'll love this one: since `WPChromelessWebViewController` is dead, can we also kill `WPWebView` here?
- Are the rows [in the 'Authors' row](https://cloudup.com/csUDy2Q1Hxr) expected to push a webview?
- You also addressed #3331, so props to you sir!

Thanks!

**Comment by astralbodies** [comment]
@jleandroperez forgot to push my commit last week - removed `WPWebView`. Can you take another look?

**Comment by jleandroperez** [comment]
@astralbodies :shipit: once the conflict is fixed!

**Comment by jleandroperez** [comment]
@astralbodies what an *AWESOME* PR, thanks for the cleanup!

**Pull request merged**
