### PR TITLE
Pull in 4.6.1 changes to 4.7

### PR DESCRIPTION
**Pull request by sendhil**

### CODE REVIEW

**Comment by aerych** [comment]
Hi @sendhil.  I can build and run just fine and no obvious breakage with the merge. :shipit:

**Comment by SergioEstevao** [comment]
This merge somehow in the end missed this important update:

https://github.com/wordpress-mobile/WordPress-iOS/commit/61be18a0b627677f10fa5071eefd1832592d12f9

**Comment by sendhil** [comment]
@SergioEstevao - just submit a PR to `release/4.7` to fix it. I think i saw the changes but generally default to the later branch when it comes to Podfile conflicts.

**Comment by sendhil** [comment]
@SergioEstevao ignore my comment above, I was processing old email ;).

**Pull request merged**
