### PR TITLE
[Dark Mode] Fix colors in rich notifications

### PR DESCRIPTION
**Pull request by danielebogo**
Refs. #12320 

This PR fixes the colors used in the rich notifications title and body.
**Title** -> `.text`
**Body** -> `. textSubtle`
dark-mode-rich-notifications

## To test:
- Run this branch with iOS 13
- Generate a push notification from another account
- Expand the notification to see its content
- Switch between light/dark style to verify the colors are ok
- Run it with iOS 12 and verify everything works as always

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
I'll leave this for @jtreanor to 👍 as how is now the release manager for WPiOS , but it looks like this PR needs changes to `Podfile.lock` committed – you can fix this by running `bundle exec pod install` in the repo, then committing the changes! :)

**Comment by danielebogo** [comment]
Hey @jkmassel the `Podfile.lock` changed because I run `bundle exec pod install` (aka `bepi` in my commit 😁). Do I need to update the branch and /or run it again? Or run another command?

**Comment by jkmassel** [comment]
Hmm good question! I see that the hash for ZenDesk has changed – perhaps try running it again and see if anything changes? It's possible that they updated something again and that's causing the issue? 🤔 

If running it again doesn't change the `.lock` file, perhaps try just getting rid of that change?

**Comment by danielebogo** [comment]
@jkmassel ok that's strange! I run `bepi` again and it always generated a new hash.
I removed then the commit (removing the `.lock` change) and pushed.
I tried (just for curiosity) to run again `bepi`and it didn't change anything!

**Comment by mattmiklic** [comment]
Colors look good. 👍

**Pull request merged**
