### PR TITLE
Quick Start: New visuals for Quick Start Modal

### LINKED ISSUE #18552: Quick Start: New visuals for checklist modal
## Description

Visual changes to the Quick Start checklist modal.

Design ref: pbArwn-4wS-p2

## Tasks

- [ ] Update Quick Start checklist modal 
    - [x] Remove success screen and completed list (#18649)
    - [ ] Update to new designs for both New Site / Existing Site (#18711)
    - [ ] Grey out completed task (#18711)

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Closes #18552 

## Description
This PR revamps the quick start modal

_PS: This PR is based on #18688 because it depends on the same newly added illustration._

\ | Light Mode | Dark Mode
-|-|-
Know the app tour |app-light|app-dark
Customize tour |customize-light|customize-dark
Grow tour |grow-light|grow-dark

## Testing Instructions

_Please test the following using both quick start types and on light and dark modes_
1. Enable quick start
2. Tap on the quick start card
3. Make sure the modal is presented and matches the design
4. Tap any task
5. Make sure the modal is dismissed and the task is started
6. Finish the task
7. Open the modal again
8. Make sure the completed task matches the design

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hassaanelgarem** [comment]
@osullivanchris Right now, we show the same illustration in the modal for all tours. What do you think of using the existing illustrations for the old two tours? These illustrations were displayed in the modal when all tasks were completed. This is how it could look:
Get to know tour | Customize tour | Grow tour 
-|-|-
app-light|customize-suggestion-light|grow-suggestion-light

---

Another thing, I want to double-check that for a completed task, there shouldn't be a change of style for the description label. This is how it behaves right now:
Not completed | Completed 
-|-
customize-light|Simulator Screen Shot - iPhone 13 Pro - 2022-05-24 at 03 00 26

**Review by osullivanchris — APPROVED** [review]
Wow awesome work @hassaanelgarem , looks really spot on already. Two tiny details

- In 'Grow You Audience' the blue background is changing to a different colour in dark mode. I'm thinking this is probably because we globally use the blue colours a lot, and there's some attribute applied globally to flip it in dark mode. I think it looks a bit off, because it has a different tone to the other colours. Is it too hacky to just keep the colour same in both modes for this case?
- The 'X' to close the dialog is slightly smaller than the one I referenced in 'About WordPress'

I'll keep playing around with it but for now everything is looking great to me otherwise. 

Oh yeah re; the 'Grow Your Audience' and 'Customize your Site' illustrations I'm in two minds:
- Good point that we have existing illustrations, but they feel dated, and we're trying to move away from that style.
- I could get our illustrator to make new ones. But I'm unsure we'll be keeping two separate lists long term, so I didn't think it was a great use of her time 🤔

**Review by momo-ozawa — APPROVED** [review]
Looks amazing, @hassaanelgarem!

Just a quick q for @osullivanchris. This is how it looks on iPad -- what do you think of the white space at the bottom?

Simulator Screen Shot - iPad Air (4th generation) - 2022-05-24 at 12 20 11 | Simulator Screen Shot - iPad Air (4th generation) - 2022-05-24 at 12 20 14
-- | --

**Comment by osullivanchris** [comment]
> Just a quick q for @osullivanchris. This is how it looks on iPad -- what do you think of the white space at the bottom?

aha. I hadn't seen iPad (have trouble installing builds on mine). Thanks for sharing @momo-ozawa 

Yeah ideally it would be nice to reduce the bottom padding on portrait. But I don't know if its a dynamic height component or fixed-height? On landscape it looks fine.

In my mock I had added additional left and right padding to the content as well. I had 96pt left and right.

Screenshot 2022-05-24 at 12 44 38

**Comment by hassaanelgarem** [comment]
@osullivanchris 

> In 'Grow You Audience' the blue background is changing to a different colour in dark mode

Nice catch! Turns out the Blue and JetpackGreen shades have different definitions for light and dark modes. But that was easy to fix without affecting the rest of the app 👍 

> The 'X' to close the dialog is slightly smaller than the one I referenced in 'About WordPress'

I was following the sizes on zeplin. But now I matched the sizes to the 'X' button on the About screen 👍 

> In my mock I had added additional left and right padding to the content as well. I had 96pt left and right.

Fixed 👍 

Customize Light | Customize Dark | iPad Spacing
-|-|-
updated-light|updated-dark|updated-ipad

---

> Yeah ideally it would be nice to reduce the bottom padding on portrait.

Right now the height is static. I'll look into making it dynamic and if it's doable I'll address this in a different PR.

---
Regarding the illustrations suggestion, I agree that they do seem dated. However, do we actually have plans for ditching the old lists? I think they add good value for new users. @leandroalonso What do you think?

**Comment by osullivanchris** [comment]
All sounds good, thanks @hassaanelgarem !

> Right now the height is static. I'll look into making it dynamic and if it's doable I'll address this in a different PR.

Not a big issue. If its an easy fix. Is it a native component rule that its static? If so maybe we shouldn't mess with it. If its our own, tweak away.

> Regarding the illustrations suggestion, I agree that they do seem dated. However, do we actually have plans for ditching the old lists? I think they add good value for new users. @leandroalonso What do you think?

Oh yeah I'm sure we'll continue to have Quick Start. I just think it could become one list like we're doing for existing users. Then if its one list, 1 illustration and more general title like we have here for existing users will make sense too.

**Comment by hassaanelgarem** [comment]
@osullivanchris 
> I just think it could become one list like we're doing for existing users.

Aah okay, gotcha! I thought you meant 1 list for new & existing users, my bad 🙈 

> Then if its one list, 1 illustration and more general title like we have here for existing users will make sense too.

Yeah, I think it makes sense to wait for that instead of creating two illustrations and then throwing one (or both) 👍

**Pull request merged**
