### PR TITLE
Integrating WordpressAuthenticator

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
- Linking the new [WordPressAuthenticator framework](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS) (Mapped via cocoapods).
- Nukes **WordPressAuthenticator** folder
- Disables Bitcode for: [WordPress, ShareExt, DraftAction, TodayWidget]. Reason: **GoogleSignIn-Repacked** wasn't built without bitcode, which forces the entire chain not to use bitcode. We'll revisit as soon as GoogleSignIn is officially updated with Bitcode support.
- **NUXButtonViewController** is now being programatically  instantiated from the Signup Epilogue (AND) Site Creation flow. Since it's the second time we need to patch this (turns out cocoapods changes the dependencies Bundle Identifiers...), i'm implementing a more robust solution.

@nheagy @ScoutHarris @bummytime ladies and gentlemen... may i bug you all with a superhugesuperimportant PR?

**NOTE** that this PR actually maps to a [This WordPressAuthenticator PR](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/1) that does not modify behavior, but fixes few things here and there. We should test the whole thing with this integration, actually.

Apologies about the "child PR" size. No new code there: it's mostly about LICENSE + missing assets!.

---

### Scenario(s): WordPress.com Login
- Log into a WordPress.com Account with Username + Password + 2FA Token (Manually Type it!)
- Log into a WordPress.com Account with Username + Password + 2FA Token (Get the SMS!)
- Log into a WordPress.com Account with Username + Password
- Log into a WordPress.com Account with Magic Link
- Log into a WordPress.com Account with Google!
- Log into a WordPress.com Account with 1Password Integration
- Log into a WordPress.com Account, by pressing `enter your site address`, and entering a WordPress.com URL + Username + Password

Please, for each scenario, verify that the Epilogue shows up correctly, and that your blogs are properly sync'ed.

---

### Scenario: WordPress.org Login
1. Fresh Install
2. Log into a WordPress.org Site

Please verify that the Epilogue shows up correctly, and that your blog shows up in `My Sites`.

---

### Scenario: Jetpack Login
1. Log into a WordPress.org Site (that's connected to a dotcom account!)
2. Press `My Sites` > `Stats`
3. Log into the associated WordPress.com Account

Please, verify that the WordPress.com account is properly connected.

---

### Scenario: WordPress.com Signup
1. Signup for a new account using Email + Password
2. Signup for a new account using Google

---

### Scenario: Site Creation
1. Attempt to create a new Site
2. Verify that the Domains Picker correctly displays the ButtonViewController at the bottom of the screen
3. Proceed until you reach the epilogue (Contragulations UI). Verify that the bottom buttons show up correctly

### CODE REVIEW

**Comment by loremattei** [comment]
Moved the milestone to 10.3 since this didn't make the 10.2 cut. Please, feel free to move it back and to let it target the release branch if it has to land in 10.2.

**Comment by jleandroperez** [comment]
Ping @nheagy @bummytime @ScoutHarris

**Comment by bummytime** [comment]
Sorry @jleandroperez, this fell off my radar. I will get to this...promise. 😄

**Comment by jleandroperez** [comment]
No worries at all @bummytime !!! not blocked or anything!!

😄

**Comment by a8cbuddybuild** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR has more than 500 lines of code changing. Consider splitting into smaller PRs if possible.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jleandroperez** [comment]
Signup issue solved. Background:

- **NUXButtonViewController** lives within the WordPressAuthenticator, but is used in few spots within WordPress iOS
- Cocoapods does not respect the Bundle Identifiers specified by the actual dependencies, and proceeds to change `com.automattic.WordPressAuthenticator` with `org.cocoapods.WordPressAuthenticator`.
- Since i'm not happy about it, and it's literally the second time we have issues with this, i've implemented a (hopefully) robust solution, which simply instantiates the NUXButtonViewController programatically, and injects it into a placeholder canvas.

Ready for another round, thanks in advance!!

**Comment by ScoutHarris** [comment]
@jleandroperez signup works now! 🎉  All looks good to me.

**Comment by jleandroperez** [comment]
@ScoutHarris @beaucollins thank you both **A LOOOT** for verifying this one. 

@nheagy i'm honestly **terrified** about getting this PR out of sync again. (Forgive me about not waiting a bit longer sir!!), i'd be more than happy to fix anything that might come up. Thank you as well!!

**Comment by jleandroperez** [comment]
Thanks Nate!!

**Pull request merged**
