### PR TITLE
[Xcode 12] Update Core Data transformers to use NSSecureUnarchiveFromData

### LINKED ISSUE #15167: [Xcode 12] Fix Core Data transformer warnings
When building on Xcode 12, there are many of these warnings:

```
warning: XYZ is using a nil or insecure value transformer. Please switch to NSSecureUnarchiveFromDataTransformerName or a custom NSValueTransformer subclass of NSSecureUnarchiveFromDataTransformer
```

- [ ] AbstractPost.revisions
- [ ] Blog.capabilities
- [ ] Blog.options
- [ ] Blog.postFormats
- [ ] BlogSettings.commentsBlacklistKeys
- [ ] BlogSettings.commentsModerationKeys
- [ ] BlogSettings.jetpackLoginWhiteListedIPAddresses
- [ ] Media.error
- [ ] MenuItem.classes
- [ ] Notification.body
- [ ] Notification.header
- [ ] Notification.meta
- [ ] Notification.subject
- [ ] Post.disabledPublicizeConnections
- [ ] Post.geolocation
- [ ] Theme.tags

### PR DESCRIPTION
**Pull request by frosty**
Fixes #15167.

This PR makes some changes to remove the `is using a nil or insecure value transformer` warnings when building with Xcode 12.

- Updates all Transformable Core Data properties that use 'top level' classes to specify the `NSSecureUnarchiveFromData` transformer. This only exists on iOS 12+, so this will generate console warnings on iOS 11. However, if the class isn't found, I'm pretty certain that the system will just fallback to the default behaviour.
- Adds custom value transformers for the two Transformables that don't use top level classes – one is our own Coordinate class, and the other is NSError (which does conform to NSSecureCoding).

**To test**

- Note: I should probably add a unit test to verify the migration before we merge this
- Install a build that uses the 102 version of the data model
- In that build, create a post and in Post Settings assign it a location
- Also, begin uploading some media in the Media library and cause it to error - the easiest way is to disable your internet connection during the upload
- Background the app to ensure everything is saved
- Install a build from this branch, and ensure there are no Core Data errors logged on startup
- Ensure that your post and its location are still correct
- Visit the media library, tap on one of your failed media items and check the error message is shown as the title of the alert controller that appears.

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Gio2018 — APPROVED** [review]
The test cases passed. I saw core data warnings in the console when I first run this branch, but those were likely related to the model pre-migration. When re-run, the warnings were gone.

**Comment by jkmassel** [comment]
👋 Howdy! We are freezing `16.2` today, so this PR is being pushed to `16.3`. If you need it to be part of the `16.2` release, please merge it to the `release/16.2` branch, then DM me – I'll be happy to cut a new beta release!

**Comment by frosty** [comment]
Just posting an update that I'm currently trying to track down the origin of a crash on iOS 12 reported by @shiki, which is why this PR hasn't progressed any further.

**Comment by jkmassel** [comment]
👋 Hey there! We are freezing `16.3` today, so this PR is being bumped to `16.4`. If you need it to be part of the `16.3` release, please merge it to the `release/16.3` branch and send me a DM – I'll be happy to cut a new beta release!

**Comment by frosty** [comment]
Develop xcmodel version has changed, so closing this PR – new PR incoming.

**Pull request closed without merging**
