### PR TITLE
My Site Dashboard: Fix truncated title on next post card

### LINKED ISSUE #18266: My Site Dahboard: Next post card title is truncated on smaller screen devices
### Expected behavior

Dahboard card title to be displayed fully on small screens and not truncated. 

### Actual behavior

"Create your next post" card title is truncated on small screen devices (iPhone 8)

### Steps to reproduce the behavior

1. Install the app on iPhone 8
2. Choose a site that has published posts, and has no drafts or scheduled posts.
3. Open the dashboard
4. Observe the truncated card title.

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Fixes #18266

## Description
Enabled auto shrinking for the title label in the next post view card.

## Testing Instructions

1. Install the app on a small screen device (iPhone 8)
2. Choose a site that has published posts, and has no drafts or scheduled posts.
3. Open the dashboard
4. Make sure the title "Create your next post" is not truncated.

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by momo-ozawa — APPROVED** [review]
🚀

**Comment by leandroalonso** [comment]
@hassaanelgarem we should probably target the release branch with this one. :)

**Comment by hassaanelgarem** [comment]
@leandroalonso Updated the target branch ✅

**Comment by hassaanelgarem** [comment]
@mokagio We would like to include this small fix in `19.6` 🙏

**Comment by mokagio** [comment]
> @mokagio We would like to include this one as well in 19.6 🙏

Sure. The base branch being `release/19.6` and the PR having the 19.6 milestone is all we need. I'm going to take over merging this so we can ship a beta that includes it ASAP.

**Comment by mokagio** [comment]
@hassaanelgarem  this has been bundled as part of [19.6 beta 1 (19.6.0.1)](https://github.com/wordpress-mobile/WordPress-iOS/pull/18293).

Thanks for your work 🙌

**Pull request merged**
