### PR TITLE
Comments: Show a spinner when refreshing comment lists.

### LINKED ISSUE #16480: Spinner needed for loading comments filters
### Expected behavior
Indication of something loading when switching between filters, especially when switching from ones with no results to ones with results

### Actual behavior

https://user-images.githubusercontent.com/66104034/117908386-8ec3cd00-b295-11eb-93c5-37fb370fc84c.mp4

### PR DESCRIPTION
**Pull request by aerych**
Closes #16480
This PR causes the CommentsViewController's tableView's refreshControl to become visible as the list is refreshed when switching filters. 
Example:
filter-spinner

To test:
View the comments list.  Tap between different filters.  Confirm a spinner is shown while the list is loading. Confirm the animation is smooth and not jarring. 

@ScoutHarris Game for another? 

## Regression Notes
1. Potential unintended areas of impact
n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a

3. What automated tests I added (or what prevented me from doing so)
n/a
PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @aerych .

I noticed a couple oddities. Can we do anything to make it better?

1) When going from a filter with no results to another filter with no results, the NRV jumps and flashes.


https://user-images.githubusercontent.com/1816888/118721553-40a84f80-b7e8-11eb-8f34-be6013b7132a.mov

2) When going from a filter with no results to another filter with results, the spinner doesn't show. I'm assuming because the NRV is on top of the table, covering the spinner.

https://user-images.githubusercontent.com/1816888/118721712-70efee00-b7e8-11eb-9a36-a11f10b7bd8d.mov

**Comment by aerych** [comment]
Well spotted. I missed them both cases while testing in the simulator. There _should_ be something we can do to improve. I'll dig into it.

**Comment by aerych** [comment]
Hola @ScoutHarris  👋  I guess this one is ready for another look.  There is still an intermittant, quick, jump with the no results view that I haven't been able to nail down. It seems to have something to do with the tableView's contentOffset being adjusted while showing the refreshControl and the tableView not liking new subviews being added.   The jump doesn't happen all the time so maybe it works for now.  It's an improvement from before at any rate.  Lemme know what you think.  We can always punt this one to later if we need.

**Review by ScoutHarris — APPROVED** [review]
This looks much better! ⭐ 

> There is still an intermittant, quick, jump with the no results view that I haven't been able to nail down.

It took a few tries, but I spotted it. I think it's minor enough to let it be. I'm not sure I even would have noticed if I hadn't been looking for it. 🤷 

Anywho, I call it good.

:shipit:

**Comment by aerych** [comment]
Thank you!!!

**Pull request merged**
