### PR TITLE
Remove .nativePhotoPicker feature flag

### PR DESCRIPTION
**Pull request by kean**
Remove `.nativePhotoPicker` feature flag and the associated code.

## To test:

Requires smoke tests. Please, follow the main steps from the following PRs:

- https://github.com/wordpress-mobile/WordPress-iOS/pull/21391
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21388
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21370
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21360

## Regression Notes
1. Potential unintended areas of impact: Media Picker
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual
3. What automated tests I added (or what prevented me from doing so): n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by momo-ozawa — COMMENTED** [review]
Hey @kean, when I try to update my site icon, some times it doesn't update to the new photo. You see the spinner over the old icon, then the spinner goes away. If you pull to refresh, it shows the new photo.

I'm not sure if the device version matters here - I can reproduce this pretty consistently on my iPhone 14 Pro on iOS 16.6.1. I can't seem to reproduce this on the simulator (iPhone 15 Pro, iOS 17)

**Comment by kean** [comment]
@momo-ozawa , I opened a bug https://github.com/wordpress-mobile/WordPress-iOS/issues/21735. It doesn't seem to be related to the changes from this PR.

**Review by momo-ozawa — APPROVED** [review]
LGTM! Can you add release notes for this? Thanks! 🙇‍♀️

**Comment by kean** [comment]
> Can you add release notes for this? Thanks! 🙇‍♀️

Done, thank you.

**Pull request merged**
