### PR TITLE
[Gutenberg] Hotfix 1.15.2

### PR DESCRIPTION
**Pull request by etoledom**
PR to merge hotfix v1.15.2 into `release/13.5`

`gutenberg-mobile` PR: https://github.com/WordPress/gutenberg/pull/18128

**To test:**

- Upload media (Image, Video, Media&Text Blocks).
- Copy images from Photos app into gutenberg editor.
- Block inserter layout should be correct after device rotation. (https://github.com/wordpress-mobile/gutenberg-mobile/pull/1495)
- Added left right borders to inner blocks (https://github.com/wordpress-mobile/gutenberg-mobile/pull/1496)
- Removed alignment options from Media & Text until they are fixed (https://github.com/wordpress-mobile/gutenberg-mobile/pull/1500)

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by etoledom** [comment]
Tested the last commit and overall looks good to me ✅ 

Somehow I managed to save a post with a media&text image local URL, but I wasn't able to reproduce this issue consistently.

The validation issue (from https://github.com/wordpress-mobile/gutenberg-mobile/issues/1509) is completely gone and video uploads work just fine 🎉

**Comment by koke** [comment]
We already discussed this one, but making a note here:

* Insert a media-text block
* Choose to have the media on the right
* Select an image and publish before it finishes uploading
* The post is published with a local image URL and a local media ID

Interestingly enough, there is no validation error.

**Comment by koke** [comment]
Not sure if I reported this before, but when you create a new post and insert a media-text block, the keyboard is set to lowercase instead of capitalizing the text.

IMG_43EC293B38BB-1

Also, the `Content…` placeholder is not showing translated, even though we have a translation for it.

**Comment by koke** [comment]
I also noticed that our media upload process create intermediate undo steps, so after uploading an image on the image or media-text blocks, you can "undo" to get back to the local file or even the thumbnail. Switching to HTML and back would trigger a new upload (sometimes it happened right away).

undo-media-upload

It doesn't look like a new bug, as I can see the same in 13.5 (TestFlight)

**Comment by koke** [comment]
Testing on iPhone 8 iOS 12.4.1 with Display Zoom enabled, the toggle for opening links in new tab is cropped:

IMG_38E40960D0AC-1

**Comment by etoledom** [comment]
Thank you @koke for the detailed review!
Let's be sure to create the appropriate tickets for these issues 👍

**Pull request merged**
