### PR TITLE
Jetpack Focus: Remove footnote in new users overlay

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Ref: p1676550754200889-slack-C04564QS0V7

## Description
This PR fixes an issue with the New Users Overlay where “Switching is free and only takes a minute” was being displayed twice.

## Testing Instructions

Test on both iPhone and iPad:

1. Run the app
2. Open the debug menu and enable the "Jetpack Features Removal Phase For New Users" flag
3. Close & re-open the app
4. An overlay should appear
5. Make sure the footnote "Switching is free and only takes a minute" is not displayed and only the subtitle is displayed.

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mokagio — COMMENTED** [review]
I tried testing this PR on the Simulator, but didn't know how to trigger the new user flow. I mean, I'm sure one can trigger it by creating a new account, but I didn't go to such length...

I'm about to start the 21.8 code freeze and this PR won't make it into the first beta. @hassaanelgarem if you want to land this in 21.8, please updated the branch to `relaese/21.8`, otherwise, could you please update the milestone to 21.9. Thanks!

**Review by momo-ozawa — APPROVED** [review]
Works as described!


@mokagio I think you may have been testing on the JP app instead of the WP app - the overlay only shows up on the WP app.

**Comment by mokagio** [comment]
@momo-ozawa 

> I think you may have been testing on the JP app instead of the WP app - the overlay only shows up on the WP app.

I _did_ start with the Jetpack app, yes 😳 But then I realized that it didn't make sense to see a "try Jetpack" view from Jetpack and rerun on WordPress.

The test I did was on the Simulator, logged in with an existing account created via Google SignIn. I run the app then killed it from Xcode and relaunched it manually from the Sim. 🤷‍♂️

**Comment by hassaanelgarem** [comment]
@mokagio Sorry I was AFK this past week.
I updated the base branch to `release/21.8`. It would be great to include this in the next beta.


> The test I did was on the Simulator, logged in with an existing account created via Google SignIn. I run the app then killed it from Xcode and relaunched it manually from the Sim.

To see the overlay, you need to manually enable the "Jetpack Features Removal Phase For New Users" feature flag or test using the new user test account (pcdRpT-1Fn-p2).

**Comment by mokagio** [comment]
> To see the overlay, you need to manually enable the "Jetpack Features Removal Phase For New Users" feature flag or test using the new user test account ( pcdRpT-1Fn-p2 ).

I'm pretty sure that's what I did but I clearly must have missed something at some point. I think this has been enough scrutiny from other folks and I won't try to reproduce.

**Comment by mokagio** [comment]
> I updated the base branch to release/21.8. It would be great to include this in the next beta.

There should be one out shortly

**Pull request merged**
