### PR TITLE
Merge finalized release 23.3 

### PR DESCRIPTION
**Pull request by mokagio**
- [x] Fastlane  localized `release_notes.txt` updates
- [x] Localized `.strings` updates
- [x] Build number bump in version `.xcconfig` file
- [x] Plus diffs from the PRs that landed on the release branch since the last beta

Changes that made it into this latest build:

- https://github.com/wordpress-mobile/WordPress-iOS/pull/21622, @kean @momo-ozawa 
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21629 @momo-ozawa @kean @salimbraksa 

Plus, https://github.com/wordpress-mobile/WordPress-iOS/pull/21623 but that's not user facing.

### CODE REVIEW

**Comment by oguzkocer** [comment]
It looks like there is a merge conflict, so we'll need to create a new PR. @mokagio Let me know if you'd like me to take care of that. I'd also be happy to cover the rest of your release tasks for today if you'd like.

**Comment by momo-ozawa** [comment]
Hey @oguzkocer, @mokagio 

Just wanted to note that these two PRs were merged into `release/23.3` as well, but aren't included in this PR
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21648
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21630

Flagged this in Slack (p1695996189821279/1695891466.316049-slack-CC7L49W13), but posting here for visibility 🙇‍♀️

**Comment by oguzkocer** [comment]
@momo-ozawa It looks like they are in the PR - they are just not listed in the PR description. You can see both 965f6ef7169770eca692100955133a9552300c0f & f06f8cc9e5fdf23120faf9dff4d06d1946bff2ee in the commit list. I imagine @mokagio missed listing these in the PR description because the commit messages are too long and the PR number doesn't show up in the commit list unless you go into the commit. I'd have missed it as well.

Also worth noting that since this PR is merging `release/23.3` branch and the PRs you mentioned were merged to this branch, it's not really possible for the PRs not to be there. There are some odd cases where the GitHub might not list them, but if the branches match, it'll be there.

There are cases the commits might be missed when we create the intermediate branches such as `merge/23.3-final-to-trunk` - so, it's still good to be vigilant and worth bringing up any concerns. Thank you for that!

**Comment by mokagio** [comment]
@oguzkocer @momo-ozawa 

> There are cases the commits might be missed when we create the intermediate branches such as merge/23.3-final-to-trunk - so, it's still good to be vigilant and worth bringing up any concerns. Thank you for that!

I second that. Thanks @momo-ozawa and sorry for the confusion.

Thanks for pointing out the conflicts @oguzkocer. I'll push a merge branch shortly.

**Pull request closed without merging**
