### PR TITLE
Newly created posts can now switch the parent VC's filter to be shown.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes [this issue](https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/769).

Basically when a post is created or edited in the new editor, and saved, the parent list makes sure that the post is visible by changing the filtering as necessary (ie: published, draft, pending, etc).

**Test 1:**
1. Launch the app
2. Open the list of posts for a blog
3. Set the filtering to "Published"
4. Create a new post
5. Set it to save as "Draft" in the optinons
6. Save the draft
7. The parent VC's filtering should be changed to "Drafts".

Variations of this test can be performed by changing the status.

**Test 2:**
1. Launch the app
2. Open the list of posts for a blog
3. Set the filtering to "Published"
4. Edit an existing post
5. Change it to "Draft" in the optinons
6. Save the draft
7. The parent VC's filtering should be changed to "Drafts".

Variations of this test can be performed by changing the status.

/cc @SergioEstevao for review.

### CODE REVIEW

**Comment by kurzee** [comment]
@diegoreymendez heads up, I just merged https://github.com/wordpress-mobile/WordPress-iOS/pull/4840 which will create build issues for this PR.

**Comment by diegoreymendez** [comment]
@kurzee - Thank you.  I'll merge the latest from develop to bring your changes in.

**Comment by kurzee** [comment]
@diegoreymendez took a quick look, just need to use `availablePostListFilters` instead of `postListFilters` now on `[self.postListFilters enumerateObjectsUsingBlock:`.

**Comment by diegoreymendez** [comment]
I took the opportunity to improve this PR a bit:

- Added documentation for `setFilterWithPostStatus:`
- Removed an unused variable.
- Merged the lates from `develop` as suggested by @kurzee.
- Modified `filterThatDisplaysPostsWithStatus:` to rely on `indexOfFilterThatDisplaysPostsWithStatus:`.

**Comment by diegoreymendez** [comment]
@kurzee - As discussed privately with @kurzee, since he's doing parallel work on some of this code, I'm reassigning the PR to him.

**Comment by kurzee** [comment]
@diegoreymendez code looks good, testing variations of the above tests pass. Just need the PR labels and milestone set and we're good to :shipit:

**Comment by diegoreymendez** [comment]
Ty @kurzee !

**Pull request merged**
