### PR TITLE
Post Settings: Remove ability to set post location

### LINKED ISSUE #16234: Post Settings > Location: remove deprecated feature
As feature does nothing and no longer exists on Android, please remove Post Setting > Location feature.

### PR DESCRIPTION
**Pull request by momo-ozawa**
Fixes #16234

## Description

This PR removes the Location feature under Post Settings.

Geotagging posts (setting their location) [is no longer supported on the web](https://wordpress.com/support/replacing-the-older-wordpress-com-editor-with-the-wordpress-block-editor/) and was [removed from WPAndroid](https://github.com/wordpress-mobile/WordPress-Android/pull/13378) about six months ago.

Before | After
-- | --
Simulator Screen Shot - iPhone 12 Pro - 2021-08-18 at 17 46 51 | Simulator Screen Shot - iPhone 12 Pro - 2021-08-18 at 17 54 31

## To test

1. Install an older version of the app, without the changes from this PR
2. Check out this branch, then run and install the app
3. ✅ Should run as normal -- this means that the lightweight Core Data migration is working as expected
4. Open **Post Settings** on a post or page
5. ✅  Notice that the option to **set the location** is no longer there

## Regression Notes
1. Potential unintended areas of impact
Post Settings

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I built and ran the post settings screen

3. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by momo-ozawa** [comment]
Hi @twstokes 👋 
I'm tagging you for a review, since it looks like you did some stuff on PostSettings fairly recently 🙇‍♀️

**Comment by twstokes** [comment]
Hey @momo-ozawa! 👋 Correct! Those commits were from my trial, so if it would provide extra assurance to add someone a little more seasoned on this project to the review I totally understand.

The changes look great to me, but I did have one question:

Is it outside of the scope of this PR to remove the [`geolocation` property here](https://github.com/wordpress-mobile/WordPress-iOS/blob/task/16234-deprecate-location-post-setting/WordPress/Classes/Models/Post%2BCoreDataProperties.swift#L8)? I also see there are latitude and longitude properties. Changing these may also affect the Core Data model.

If it's best to leave that alone for the sake of this PR's goal, I'll approve the PR. Thanks!

**Review by twstokes — COMMENTED** [review]
Hey @momo-ozawa! 👋 Correct! Those commits were from my trial, so if it would provide extra assurance to add someone a little more seasoned on this project to the review I totally understand.

The changes look great to me, but I did have one question:

Is it outside of the scope of this PR to remove the [`geolocation` property here](https://github.com/wordpress-mobile/WordPress-iOS/blob/task/16234-deprecate-location-post-setting/WordPress/Classes/Models/Post%2BCoreDataProperties.swift#L8)? I also see there are latitude and longitude properties. Changing these may also affect the Core Data model.

If it's best to leave that alone for the sake of this PR's goal, I'll approve the PR. Thanks!

**Comment by momo-ozawa** [comment]
@twstokes Thanks for the review! 🙏 

> Is it outside of the scope of this PR to remove the geolocation property here? I also see there are latitude and longitude properties. Changing these may also affect the Core Data model.

Great catch. I've removed the `geolocation`, `latitudeID`, and `longitudeID` properties. @leandroalonso has offered to take another look, so I'm gonna pass on the review to him.

**Comment by twstokes** [comment]
Sounds great @momo-ozawa!

**Review by leandroalonso — APPROVED** [review]
:shipit:

**Pull request merged**
