### PR TITLE
Kanvas update with 9:16 export fixes

### LINKED ISSUE #62: Text isn't positioned properly in export images
In some cases the text isn't properly positioned in the exported media.

Need to investigate this and find out when and why this is happening.

<a href="https://user-images.githubusercontent.com/3250/103923117-f2fd3700-50d1-11eb-86a5-3efc4f0dc8c7.png"></a> <a href="https://user-images.githubusercontent.com/3250/103923285-293ab680-50d2-11eb-87b3-b4b295acb68c.png"></a>

pbMoDN-1Hv-p2#comment-3573

### PR DESCRIPTION
**Pull request by bjtitus**
Fixes https://github.com/tumblr/kanvas-ios/issues/62

### Related PRs

https://github.com/tumblr/kanvas-ios/pull/114

## Testing

* Create a Story post
* Add landscape and portrait media
* Add text to the media
* Ensure that the media posted uploaded to the site is roughly 9:16. (about 0.5625 when dividing the width by the height)
* Ensure text is positioned as expected

## Regression Notes
1. Potential unintended areas of impact

Anything related to Story media export.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Tested posting stories with a variety of media sizes and types.

3. What automated tests I added (or what prevented me from doing so)

Unfortunately, the OpenGL rendering will not work in the simulator so we cannot test this.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
We're cutting `17.5` today, so this PR is being bumped to `17.6`

**Comment by mokagio** [comment]
Bumping this to 17.7 as part of the open PRs walkthrough before starting the 17.6 code freeze because it's still a draft. 

Thank you for working on this 🙇

**Comment by mokagio** [comment]
@bjtitus I'm going to bump this to the next release because we'll be code freezing `17.7` today and this is still a draft.

If this cannot wait two weeks and it's important that this makes it into this release, let me know and we'll organize a new beta once ready. 👍 

Also, both this and #16031 have been sitting here for a while. Is there something I can do to help unstuck them? 🤔

**Comment by mokagio** [comment]
Pushing this PR to the next milestone, 17.9, because I'm running the code-freeze today and this is still a draft.

**Comment by mokagio** [comment]
Pushing this PR to the next milestone, 18.0, because I'm running the code-freeze today and this is still a draft.

**Comment by mokagio** [comment]
Pushing this PR to the next milestone, 18.1, because I'm running the code-freeze today and this is still a draft.

**Comment by mokagio** [comment]
Pushing this PR to the next milestone, 18.2, because I'm running the code-freeze today and this is still a draft.

**Comment by mokagio** [comment]
Pushing this PR to the next milestone, 18.3, because I'm running the code-freeze today and this is still a draft.

**Comment by mokagio** [comment]
Pushing this PR to the next milestone, 18.4, because I'm running the code-freeze today and this is still a draft.

**Comment by mokagio** [comment]
Pushing this PR to the next milestone, 18.5, because I'm running the code-freeze today and this is still a draft.

**Comment by mokagio** [comment]
Pushing this PR to the next milestone, 18.6, because I'm running the code-freeze today and this is still a draft.

**Comment by twstokes** [comment]
👋 I'm going to close this PR due to lack of activity, but please reopen if this was an error. Thank you.

**Pull request closed without merging**
