### PR TITLE
Update Media Library Data Source

### PR DESCRIPTION
**Pull request by SergioEstevao**
Update the media library data source to use a NSFetchedResultsController.
This allows improved changed notification and also allow to show media immediately instead of waiting for the server sync.

To test:
 - Create a new post
 - Tap on add media
 - Select the media library
 - If it's the first access it should sync from the server and then show the results
 - If not the first access it should show results immediately and eventually update from server results.
 - On the media library you also need to test the adding a new image using the camera. 

Needs review: @frosty

### CODE REVIEW

**Comment by frosty** [comment]
:shipit:

**Comment by astralbodies** [comment]
@SergioEstevao If this isn't a bug fix release I'm hesitant to pull it into 6.4.

**Comment by SergioEstevao** [comment]
@astralbodies this PR beside the performance improvements also fixes a issue with selection on the media library after a photo capture.

**Comment by astralbodies** [comment]
@SergioEstevao If you're confident the change is well tested then I'm cool with merging 😄

**Pull request merged**
