### PR TITLE
Jetpack Focus: Reschedule local WordPress notifications after reenabling notifications

### PR DESCRIPTION
**Pull request by staskus**
Part of #19619

## Description

Reschedule:
- Weekly Roundup notifications
- Blogging Reminders

after reenabing local notifications

## Solution:

1. For `Weekly Roundup`:  Reschedule background tasks using `backgroundTasksCoordinator.scheduleTask`. If the tasks are already scheduled they are not scheduled again
2. For `Blogging Reminders`: Fetch `schedules` and `times` for each blog and reschedule notifications `BloggingRemindersScheduler`

### Additional change

Moving `UNNotificationCenter` away from `JetpackNotificationMigrationService` to it could be used as a singleton in all the places and wouldn't keep the state. Otherwise, if we reenable notifications and quickly dismiss notification settings screen, `JetpackNotificationMigrationService` gets deinitialized and reminders might not be rescheduled. 

### Case 1 Blogging reminder:
1. Open the WordPress app
2. Enable "Jetpack prevent duplicate WP notifications" feature flag (App Settings -> Debug)
4. Notification Settings -> Select Site -> Push Notifications -> Set blogging reminders for near future
5. Come back to Notification Settings
6. Toggle "Allow Notifications" to off
7. Toggle "Allow Notifications" to on
8. Wait for Blogging Reminders
9. Blogging Reminder notifications should appear

### Case 2 weekly roundup:
1. Open the WordPress app
2. Enable "Jetpack prevent duplicate WP notifications" feature flag  (App Settings -> Debug)
3. Schedule Weekly Roundup notification for the future  (App Settings -> Debug)
4. Go to Notification Settings
5. Toggle "Allow Notifications" to off
6. Toggle "Allow Notifications" to on
7. Background the app
8. Wait for Weekly Roundup notification
10. Weekly Roundup notification (in practice it takes at least couple of minutes to appear)

## Regression Notes

1. Potential unintended areas of impact

- Breaking already built duplicate notification prevention functionality
- Setting duplicate notifications

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing

3. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
Thanks for this PR, @staskus! As we discussed today, I prioritized https://github.com/wordpress-mobile/WordPress-iOS/pull/19616#pullrequestreview-1190707077 so wasn't able to get to this one today. Will be back ASAP to review it if no one beats me to it.

**Review by guarani — COMMENTED** [review]
- ✅ Case 1 Blogging reminder: The blogging reminders got rescheduled after I reactivated push notifications

- ⚠️ Case 2 weekly roundup: I'm having trouble with this one. When I set the Weekly Roundup to fire "immediately" and then quickly toggle push notifications, the Weekly Roundup doesn't appear. It seems like this option to fire immediately gives me about 10s to toggle notifications, which should be just enough time to toggle notifications and background the app.
I tried the "Schedule in 10 sec / 5 min" option but I'm not seeing the notification there after waiting over 5 minutes. This seems unrelated to this PR because I don't get the notification even if I don't toggle the push notification switch.
I need to check if this works on `trunk` but would appreciate any pointers you might have. I did test on an A8c blog and enabled the "Include A8c P2s" option.

**Comment by staskus** [comment]
> * Case 2 weekly roundup:

@guarani, yes this one is really hard to judge. It does appear randomly after some time and it's unclear how much time to wait. For me, the weekly roundup did arrive in a couple of minutes after disabling/re-enabling.

I also tested code-wise, making sure that the task is actually scheduled after toggling disable notifications.

**Comment by guarani** [comment]
> ### Case 2 weekly roundup:
> 1. Open the WordPress app
> 2. Enable "Jetpack prevent duplicate WP notifications" feature flag  (App Settings -> Debug)
> 3. Schedule Weekly Roundup notification for the future  (App Settings -> Debug)
> 4. Go to Notification Settings
> 5. Toggle "Allow Notifications" to off
> 6. Toggle "Allow Notifications" to on
> 7. Background the app
> 8. Wait for Weekly Roundup notification
> 9. Weekly Roundup notification (in practice it takes at least couple of minutes to appear)

I was having trouble receiving these notifications but found how to get them to fire:
1. Enable [the `weeklyRoundupStaticNotification` feature flag](https://github.com/wordpress-mobile/WordPress-iOS/blob/6a57f7c848e9393b6eba6036232f973ba5fdb003/WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift#L75-L77)
2. (Optional) Reduce the `staticNotificationDelay` delay in this code:

https://github.com/wordpress-mobile/WordPress-iOS/blob/6a57f7c848e9393b6eba6036232f973ba5fdb003/WordPress/Classes/ViewRelated/Developer/WeeklyRoundupDebugScreen.swift#L91

**Comment by guarani** [comment]
I don't get the Weekly Roundup notification after I turn the `Jetpack Migration prevent duplicate WordPress app notifications when Jetpack is installed` switch on 🤔. I haven't even toggled the Push Notification switch in Notifications Settings.

I'm testing using the static notifications as mentioned in my previous comment. I know these are not enabled in production, it's the dynamic notifications that are shown. That means I should only test the dynamic notifications.

(AFAIK static notifications are a single notification that prompts the user to open the app to look at stats. The dynamic notifications are multiple notifications, one for each site, displaying view, like, and comment counts.)

**Review by guarani — APPROVED** [review]
@staskus and I figured out how to verify that Weekly Roundup notifications behave correctly in accordance with the state of the Allow Notifications switch. This requires building the app from Xcode instead of testing the above installable builds. Here are the scenarios we tested:

### Notification fires in the default scenario
1. Clean install the WordPress app and grant push notifications permission
2. Pause app execution <sup>1</sup>
3. Run the command to force the launch of any background tasks <sup>2</sup>
4. Continue execution and verify that a Weekly Roundup notification is received

### Notification doesn't fire if push notifications are disabled
1. Clean install the WordPress app and grant push notifications permission
2. Enable the feature flag <sup>3</sup>
3. Open the Notifications Settings screen, turn off Push Notifications, and close the screen
4. Pause app execution <sup>1</sup>
5. Run the command to force the launch of any background tasks<sup>2</sup>
6. Continue execution and verify that a Weekly Roundup notification is **not** received

### Notification does fire if push notifications are re-enabled
1. Clean install the WordPress app and grant push notifications permission
2. Enable the feature flag <sup>3</sup>
3. Open the Notifications Settings screen, turn off Push Notifications, and close the screen
4. Open the Notifications Settings screen, turn on Push Notifications, and close the screen
5. Pause app execution <sup>1</sup>
6. Run the command to force the launch of any background tasks<sup>2</sup>
7. Continue execution and verify that a Weekly Roundup notification is received

---

<sup>1</sup> For example, put a breakpoint in `viewDidAppear` of `NotificationSettingsViewController` (it needs to be after App Delegate finishes) and hit the breakpoint OR just pause app execution in Xcode
<sup>2</sup> In the Xcode debugger, run the command to [force the launch of any background tasks](https://developer.apple.com/documentation/backgroundtasks/starting_and_terminating_tasks_during_development):
```
e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"org.wordpress.bgtask.weeklyroundup.processing"]
```
<sup>3</sup> Enable the `Jetpack Migration prevent duplicate WordPress app notifications when Jetpack is installed` feature flag

---

We noticed one minor issue that will be fixed in a follow-up PR:
```
Main Thread Checker: UI API called on a background thread: -[UIApplication isRegisteredForRemoteNotifications]
PID: 47247, TID: 3764239, Thread name: (none), Queue name: com.apple.BGTaskScheduler (org.wordpress.bgtask.weeklyroundup.processing), QoS: 9
```

**Pull request merged**
