### PR TITLE
Release 9.2.1.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Merges all of the 9.2.1 changes into `develop`.

### CODE REVIEW

**Comment by elibud** [comment]
@diegoreymendez I think we may not want to do this, since we've already started the 9.3 release process. Instead what we could do is:

1. Merge 9.2.1 into master
2. Update Aztec Beta 18 with the fix 
3. Update WPiOS to use Aztec Beta 18 v2 on 9.3
4. Merge 9.3 into develop

What do you think? Also, I don't get why this is not showing changes on develop.

**Comment by diegoreymendez** [comment]
It's not showing changes because the only change in 9.2.1 was Aztec being changed to Beta 17.1 and since `develop` already had Beta 18, `develop` prevailed in all cases.

This merge is good because if anyone branched 9.2.1 for any reason, the conflicts I resolved above would not affect their merge-back.  It may not affect us now but I think it's still a good practice to always merge back branches (thus avoiding possible conflicts later on).

**Comment by diegoreymendez** [comment]
As for Beta 18 needing the fix, that is correct and I'll update it separately (since it's not related to this specific PR).

**Comment by diegoreymendez** [comment]
PS: I'm checking why there are failing tests too.

**Comment by diegoreymendez** [comment]
Relaunching BB since tests are not failing locally.

**Pull request merged**
