### PR TITLE
Stats Traffic: Integrate Bar Chart and Today Card within Traffic tab

### LINKED ISSUE #22530: Stats Traffic: Integrate a new Bar Chart and Today Card within Traffic tab
Parent: https://github.com/wordpress-mobile/jetpack-issue-repo/issues/1
Continuation of: https://github.com/wordpress-mobile/WordPress-iOS/issues/22392, https://github.com/wordpress-mobile/WordPress-iOS/issues/22459

- Business logic (view model updates)
- Tests

### PR DESCRIPTION
**Pull request by staskus**
Fixes #22530

Integrated Bar Chart and Today Card within the Traffic tab:

1. Updated `StatsPeriodStore` to fetch the required data for the Today card and Bar Chart card. 
2. Made slight improvements to `StatsPeriodStore` to avoid unnecessary updates and incorrectly placed caching calls
3. Made `StatsPeriodStore` mockable for View Model tests
4. Mapped Store data to table view model data for Today card and Bar Chart card
5. Limiting bar chart bars data within a given period (week, month, year)
6. Removed comparison label based on agreement p1708009222647489-slack-C06BR07TJHK
7. Added tests

### Today Card
1. Change `trafficTableViewController.selectedPeriod = selectedPeriod` to `.day` in `SiteStatsDashboardViewController`
2. Enable Stats Traffic feature flag
3. Confirm Today card is displayed with the correct data
4. Try going back and forward through the dates, confirm correct data is loaded and caching is working when coming back through already seen dates

## Bar Chart
1. Change `trafficTableViewController.selectedPeriod = selectedPeriod` to `.week`, `.month`,`.year` in `SiteStatsDashboardViewController`
2. Enable Stats Traffic feature flag
3. Confirm Bar chart card is displayed with the correct data
5. Try going back and forward through the dates, confirm correct data is loaded and caching is working when coming back through already seen dates

## Regression Notes
1. Potential unintended areas of impact

Affecting existing Days/Weeks/Months/Years tabs

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual tests

3. What automated tests I added (or what prevented me from doing so)

Unit tests for view model

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by guarani** [comment]
Here are my comments from testing (will do a code review separately):

#### Day view (Today card)

This looks great, and the counts match the web.

#### Week view

##### Date range
The date range matches the date range used on the most recent bar of WP.com's Weeks bar chart (Feb 19-25). However, the bars shown in the app are for Feb 18-19 (it starts one day too early). Also, I expected to see empty slots for future days up until Feb 25, but instead, the two bars shown are stretched to fill the empty slots. Please let me know if this was discussed somewhere, as I might have missed it.

<details>
<summary>See screenshot</summary>

</details>


##### The bar chart shows no views on the first load
The chart showed zero views the first time I loaded a high-traffic site. The label on the top-left side of the chart shows the correct View count (2,324). Pull-to-refresh is a workaround. I saw this most consistently on a clean install and a high-traffic site.


<details>
<summary>See screenshot</summary>

</details>

#### Month view

While the Week view uses Mon-Sun (Feb 19-25 as the current week), the Month view uses Sun-Sat (Feb 18-24). This might be fixed by integrating the date picker (which is on me), so I'm just sharing it here in case it needs attention. 

<details>
<summary>See screenshot</summary>

</details>


Here I see empty slots for future weeks of the month as expected (in contrast with the Week view, which didn't do this).
#### Year view
The counts on the app match those on WP.com.

--- 

That's all! 🙇

**Comment by staskus** [comment]
Thanks for review, @guarani !

> The date range matches the date range used on the most recent bar of WP.com's Weeks bar chart (Feb 19-25). However, the bars shown in the app are for Feb 18-19 (it starts one day too early). Also, I expected to see empty slots for future days up until Feb 25, but instead, the two bars shown are stretched to fill the empty slots. Please let me know if this was discussed somewhere, as I might have missed it.

Yes, this is wrong. The chart should be for Feb 19-25 and show empty slots. This is exactly what `boundChartData` method was supposed to achieve but it looks like it's not working in all the cases. Given it starts one day too early there's something wrong with calls to the store & dates.

I tried to reproduce it with the same time-zone and date as you had in the screenshot but it works for me. I'll dig deeper!

image


> The chart showed zero views the first time I loaded a high-traffic site. The label on the top-left side of the chart shows the correct View count (2,324). Pull-to-refresh is a workaround. I saw this most consistently on a clean install and a high-traffic site.

I'll check that out! High-traffic sites are working poorly for me as well but we noticed that before. There's a chance that a call to fetch view count succeeds while a call to fetch chart bar count fails. I need to think about what to do better UX-wise in case something like this happens.

> While the Week view uses Mon-Sun (Feb 19-25 as the current week), the Month view uses Sun-Sat (Feb 18-24). This might be fixed by integrating the date picker (which is on me), so I'm just sharing it here in case it needs attention.

🤔 This is what API returns and groups automatically when we ask for monthly data in weekly units. 

I think that combining this issue with the problem of displaying weekly data for Feb 18, but not Feb 19-25, points to something being wrong with the way I handle dates. Also, for me, the same site shows the correct data ranges:

image

My first thought is to make sure that all the dates are normalized to the site's timezone.

**Comment by staskus** [comment]
#### Date range

This is the only one that I couldn't reproduce at all. I may need help.

#### While the Week view uses Mon-Sun (Feb 19-25 as the current week), the Month view uses Sun-Sat (Feb 18-24)

I think it's related to your locale calendar having a different start of the week than Monday. I made changes to use the `iso8601` calendar within ViewModel which has a Monday-Sunday week range. The same is done within other Stats date helpers. However, I'm still trying to figure out the difference between using `iso8601 calendar` (StatsDataHelper. calendar) and `iso8601 calendar with site timezone set` (StatsDataHelper.calendarForSite), since both are used within Stats calculations. 

#### The bar chart shows no views on the first load

I reproduced a similar issue while simulating your time zone and Sunday being the first day of the week, so it could be also related to dates as well. Although in such instances pull-to-refresh doesn't solve the problem.

**Comment by guarani** [comment]
Thanks @staskus! I re-tested and things look fixed. I'll need to confirm with more testing later today:

Before pulling in the latest changes:
- The Week view is showing 18-20 now and still no empty slots
- The issue with the bar chart not loading is reproducible for me on the team P2 (low traffic). It seemed to resolve after a while, so I wonder if the endpoint is responding slowly. I need to try again to see what exactly happened.
- The Month view is still using the incorrect week range (18-24)

After pulling in the latest changes:
- The Week view is now showing the correct range (19-25) and empty slots 
- I couldn't reproduce the issue with the bar chart not loading, but only tested once so far
- The Month view now shows the correct date range (19-25)

**Review by guarani — APPROVED** [review]
I ran through the test plan again and found no issues 🎉

Previously viewed periods are loaded immediately, but the date picker still shows its ghost cells and it looks like data is re-fetched (even if it's not used). I think this is out-of-scope here, but just leaving it here for reference. 

And thanks for adding the tests, they look great.

**Comment by staskus** [comment]
Thanks again for reviewing and testing!

> Previously viewed periods are loaded immediately, but the date picker still shows its ghost cells and it looks like data is re-fetched (even if it's not used). I think this is out-of-scope here, but just leaving it here for reference.

Yes, I decided not to include more changes in this PR. I created a task on the board, I can make such improvements once we finish with the planned work.

**Pull request merged**
