### PR TITLE
Corrects typo in Menus

### LINKED ISSUE #5833: Typo in WordPress/Classes/ViewRelated/Menus/MenusViewController.m
### Expected behavior
use the word **please** instead of **pealse**, please.

### Actual behavior
uses the word **pealse**

### Steps to reproduce the behavior
Umm …

##### Tested on [device], iOS [version], WPiOS [version]
Nope. Found it during translation on translate.wordpress.org.

### PR DESCRIPTION
**Pull request by pixolin**
Fixes #5833 

To test:

Needs review: @

### CODE REVIEW

**Comment by astralbodies** [comment]
@sendhil @kurzee Do we want this aimed at 6.4? Can't remember which release menus is enabled on.

**Comment by pixolin** [comment]
Hm, I was so happy to finally find a place to add my bug ticket, but may have picked the wrong branch. The error occurs in the version currently in development and shown at https://translate.wordpress.org/locale/de/default/apps/ios. Sorry for the confusion.

**Comment by astralbodies** [comment]
Actually @pixolin can you open a new PR against `release/6.4` and also only commit the text change eliminating the whitespace fixes. Although the extra whitespace is strange 😄

**Comment by kurzee** [comment]
@astralbodies Menus is indeed on 6.4 😎

**Comment by kurzee** [comment]
Not sure why this whitespace is here and why our linter didn't catch it, 🤔, @pixolin if you'd like to also create a PR for the whitespace cleanup that would be super handy! Otherwise, I'll fix it up a bit later in a separate PR.

**Comment by pixolin** [comment]
Um, OK, you got me. I have no clue, why my Atom editor added the white space nor what I would need to do now. I actually just wanted to make you aware of a tiny, little, not so important typo in a single word, which I found while translating.

**Comment by kurzee** [comment]
@pixolin no prob! The whitespace is actually already present in the code, Atom just cleaned it up for us in your commit!

We'll rebuild this PR off of 6.4 and cherry-pick your commit.

Thanks!

**Pull request closed without merging**
