### PR TITLE
Issue/3271 add support for animated gifs on post list

### LINKED ISSUE #3271: Have a look at FLAnimatedImage for animated gif support
Link:  http://engineering.flipboard.com/2014/05/animated-gif/ 

Props @blowery for the tip

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #3271 #2752 

This PR add supported for animated GIF on post list by using the FLAnimatedImage library from Flipboard

To test:
 - Open the app
 - Create a new post
 - Add image to it that is an animated GIF, and set it has featured image, or only add one image to the post
 - Post it
 - Check on the post list that  the animated GIF shows correctly and plays correctly.
 - Try add multiple ones and see if they work correctly and there is no performance or memory issues.

Needs review: @aerych

### CODE REVIEW

**Comment by koke** [comment]
I'm wondering if we should revisit https://github.com/wordpress-mobile/WordPress-Shared-iOS/pull/93
I don't like that we're duplicating the image fetching and caching code when the only thing different is turning the data into an image object, and using one type of view or another.

**Comment by SergioEstevao** [comment]
@koke I agree with you that when I was doing this, I felt that we really need to have all this caching, request duplication/merging join together in a single place. I will not put it on WordPress-Shared, prefer to have class on the main repo.

My ideas for this for this was to create a main class for doing requests, cache results and merge multiple class to the same url. On top of that we could create extensions that handle UIImage, FLAnimatedImage, or another type. Even on top of that we could create extensions to connect to views if needed. 
But all this should be tackled in a different PR.

**Comment by runytry1** [comment]
Thanks you all for the support 

- [http://connectedinvestors.com/myaccount ]

**Comment by sendhil** [comment]
Have we tested this with really large GIFs? I seem to recall sometime back having the occasional out of memory crash when the GIFs got too large.

**Comment by SergioEstevao** [comment]
@sendhil good observation, I will grab a big GIF from the internet and give it a test.

**Comment by aerych** [comment]
Hola @SergioEstevao 
Things are looking good so far.  Code looks fine to me, everything runs well in the simulator, and we're not redlining anything in instruments as far as I can tell, even when the list is full of large and long playing gifs.  I want to test the branch on my iPhone 5 but buddybuild is being slow to send me an install link.  I'll follow up later after I (hopefully) get the email.

**Comment by aerych** [comment]
@runytry1, we appreciate your enthusiasm ,but only team members should be approving pull requests.

**Comment by aerych** [comment]
@SergioEstevao Testing on an iPhone 5 went well. However I did notice that images get stretched in landscape orientation.
simulator screen shot sep 29 2016 8 14 00 pm
I think this branch is probably good to go after that's sorted.  Nice work yo!

**Comment by SergioEstevao** [comment]
@aerych do you prefer to have it centered like this:
aspect fit:
screen shot 2016-09-30 at 14 36 03

or with aspect fill like this:
screen shot 2016-09-30 at 14 45 36

**Comment by aerych** [comment]
@SergioEstevao probably aspect fill, to be consistent with the post card image view.

**Comment by SergioEstevao** [comment]
@aerych ready for another look.

**Comment by aerych** [comment]
Looks great on the iPad and iPhone in both landscape and portrait orientations. 
:shipit: !!!

**Pull request merged**
