### PR TITLE
Issue/new domain suggestion parameter

### PR DESCRIPTION
**Pull request by kwonye**
## Description

Addresses #11366

To test: Go through the new site creation flow and verify the domain suggestions returned include .blog subdomains for a blog site. Verify also that for all other site types, only wordpress.com subdomain domains are returned.

Note: we must keep the old call of `getDomainSuggestions()` with `DomainSuggestionType` as there are other users of the `DomainsService` and `DomainsServiceRemote`.

### CODE REVIEW

**Comment by kwonye** [comment]
Linked with https://github.com/wordpress-mobile/WordPressKit-iOS/pull/137

**Comment by diegoreymendez** [comment]
I'm removing myself as reviewer, and taking over this PR as its new owner.

Also adding @stevebaranski as the new reviewer since he's worked on this code before.

**Comment by diegoreymendez** [comment]
Note: before merging, I'll do a new release of WordPressKit and update the `Podfile` in this PR.

**Comment by diegoreymendez** [comment]
Also updated the description to remove the podfile indications, since there' no need to change anything right now for testing.

**Comment by diegoreymendez** [comment]
I've re-targetted this to `develop` since at this point it no longer makes sense to release this in 12.1.

**Comment by diegoreymendez** [comment]
Once https://github.com/wordpress-mobile/WordPressKit-iOS/pull/137 is approved, can you review this PR?  Thanks!

**Comment by diegoreymendez** [comment]
@ctarda - Ready for review.

**Comment by diegoreymendez** [comment]
Thanks @ctarda !

**Pull request merged**
