### PR TITLE
Changing text types to match design.

### LINKED ISSUE #6946: Delete Site: Support dynamic type
The Delete Site screen currently doesn't support dynamic type. We should update it to support dynamic type sizes and adapt the layout as necessary. The designs list the dynamic type font types we should use:

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #6946 

To test: Verify text types match the design on the issue.

Needs Review: @frosty

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Moving to 9.1 since it missed 9.0's deadline.

**Comment by frosty** [comment]
Thanks @diegoreymendez!

**Comment by ScoutHarris** [comment]
@frosty - I didn't notice the button squishing - thank you! Should be fixed.

**Comment by mattmiklic** [comment]
Looks good for the most part; though the text is getting truncated when I choose the largest (non-accessibility) text size on iPhone X.

img_22cd94808cff-1

**Comment by ScoutHarris** [comment]
Hey @mattmiklic . The truncating should be fixed now. I believe I enabled installable builds for this, but if you have trouble let me know.

**Comment by ScoutHarris** [comment]
@frosty  - when you get a chance, please give this another look. All known issues have been fixed. Thanks!!

**Pull request merged**
