### PR TITLE
Issue/8020 xmlrpc api background uploads

### LINKED ISSUE #8020: Allow WordPressXMLRPCAPI to do background uploads

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #8020 

Updates the XMLRPC Api to be able to use background uploads. In order to be able to do background uploads the class was refactored to use Alamofire.

To test:
 - Start the app
 - Connect to a XMLRPC site
 - Test the several parts of the app, Post, Media, Comments, Site Settings and see if works correctly
 - Test the same with an XMLRPC site with basic auth.

### CODE REVIEW

**Comment by bummytime** [comment]
Nice work @SergioEstevao. So, I am in the middle of testing this now on both basic auth and no-auth .org sites. It is hard to quantify exactly, but everything in the app that requires a network connection seems to be a little "off". Examples of this include:

* When uploading media in Aztec, the spinner/upload never completes
* Cell images in the post list never appear (or take a really long time)
* When viewing the item detail screen in the media library, the app locks up

...and a few other things. I am not sure if you have seen similar behavior or not but I wanted to mention it early.

**Comment by bummytime** [comment]
@SergioEstevao those last two commits seemed to have fixed the issues. During testing I discovered #8053 and #8052, but these are unrelated to this PR.

Tested on .org site (no auth):
✅ New post (with device media uploaded & media lib inserted from picker)
✅ Edit post
✅ Post List
✅ Post Options (including Featured Image)
✅ Media Library - add media
✅ Media Library - delete media
✅ Comments
✅ Site Settings

Tested on .org site (basic auth):
✅ New post (with device media uploaded & media lib inserted from picker)
❌ Edit post — More or less worked but there were some issues. When opening a post with media the image placeholder in Aztec never updated:

screen shot 2017-10-25 at 12 52 11 pmscreen shot 2017-10-25 at 12 51 58 pm

❌ Post List — Refreshing worked, but "featured" image in post list cell did not display:

screen shot 2017-10-25 at 12 49 50 pm

❌ Post Options — More or less worked, but was unable to set featured image:

screen shot 2017-10-25 at 12 57 45 pm

✅ Media Library - add media
✅ Media Library - delete media
✅ Comments
✅ Site Settings

**Comment by bummytime** [comment]
@frosty, maybe you could put some 👀 on this PR too to make sure I am not missing anything.

**Comment by bummytime** [comment]
@SergioEstevao regarding the missing post list cell images and missing image placeholders above — this may be an existing issue with basic auth sites. I just tested `develop` and saw similar things happen. Let me know your thoughts.

**Comment by bummytime** [comment]
Discussed in slack: all of the ❌ from above are separate issues and logged in #8054. Soooo  beyond that, the code looks square and unit tests are 💚.  I will say :shipit: from me nice work @SergioEstevao

**Comment by frosty** [comment]
@bummytime I agree for a change like this it'd be good to get a second set of eyes on it, particularly as it's introducing some big changes and a new pod. 👍 I'll see if I have time today, or we can ask someone else to take a look.

**Pull request merged**
