### PR TITLE
Fixes Namespaces Collisions

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes Issue #2239 (Reference: #2238)

/cc @bummytime  + @astralbodies (**Thanks!!**)

### CODE REVIEW

**Comment by bummytime** [comment]
@jleandroperez Reviewed and tested. The migration seems to work without issue as well. So, a :shipit: from me, but you should prolly wait for @astralbodies stamp of approval.

**Comment by astralbodies** [comment]
This looks good @jleandroperez - I appreciate you refactored all of the uses of the term Category. That will definitely help with clarity later down the right.

Cough  `WPAccount`  Cough

**Comment by astralbodies** [comment]
:shipit:

**Comment by diegoreymendez** [comment]
@jleandroperez - Do you think you can move the files `WordPress/Classes/Networking/CategoryServiceRemoteREST.h` and `WordPress/Classes/Networking/CategoryServiceRemoteXMLRPC.h` instead of deleting / re-creating them?

This is pretty minor but I believe it's possible to do so in order to help git maintain the file's history.

**Comment by jleandroperez** [comment]
@diegoreymendez (As spoke via Slack), as far as i know, there is no way to undo that change. Not without reverting the rename commits (or redoing the PR).

Since it's just the headers, let's go for it. 

Thank you all!

**Pull request merged**
