### PR TITLE
[Analytics] Refactor the code that bumps blog_id

### LINKED ISSUE #4538: Refactor the code that Tracks blog/site ID
Refactor any changes with the use WPAppAnalyticsKeyBlogID. Ref: https://github.com/wordpress-mobile/WordPress-iOS/pull/4537#issuecomment-161130814
It would be nice to not have to check for nil any time we want to pass in an ID. Perhaps there is a helper method that can be created to pass in a default value?

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix  #4538

@astralbodies - remember to test this with self-hosted test sites.

### CODE REVIEW

**Comment by kurzee** [comment]
@daniloercoli that looks much nicer 😃

**Comment by kurzee** [comment]
@daniloercoli FYI, just in case no one catches it, this is currently crashing. This is setting a value in an immutable `NSDictionary` with `[properties setValue:blogID forKey:WPAppAnalyticsKeyBlogID]` within the method `+ (void)track:(WPAnalyticsStat)stat withProperties:(NSDictionary *)properties withBlogID:(NSNumber*)blogID`. The `NSDictionary` will need to be an `NSMutableDictionary`, if it isn't already and then ideally used with `setObject:` instead of `setValue:`.

**Comment by astralbodies** [comment]
Just thinking ahead - maybe we should make the method signature something like:

`[WPAppAnalytics track:WPAnalyticsStatSignedInToJetpack withBlog:blog];`

That way the logic for checking for nil blogID is totally self-contained within the method and a developer using it doesn't have to worry in the back of their head if they're sending a nil or if the method can take a nil blogID. 

I'd also suggest removing every call to `WPAnalytics` and replacing it with a new method on `WPAppAnalytics` with a matching method signature. That way we're consistently tracking events through the same mechanism across the board. Then the `track:withBlog:` and `track:withProperties:withBlog:` methods can be convenience calls to `track:withProperties:`.

**Comment by astralbodies** [comment]
Looks great @daniloercoli! 

:shipit:

**Pull request merged**
