### PR TITLE
Allow 2FA codes to have spaces

### PR DESCRIPTION
**Pull request by nheagy**
We should be slightly more permissive for the formatting of 2FA codes by allowing white space.

This updates our support to match https://github.com/Automattic/wp-calypso/pull/23176

To test:
- ensure normal 2FA codes still work
- ensure typing in a 2FA code with or without a space (such as `123 456`) works
- ensure pasting codes with/without white space works
- ensure that really wrong codes still don't work eg `12as56`; `password`; `😂`

Also tagging @diegoreymendez for release management.

### CODE REVIEW

**Comment by nheagy** [comment]
@ScoutHarris gratuitous build errors replaced, paste-on-resume functionality restored.

Your turn!

**Comment by nheagy** [comment]
Thanks @ScoutHarris!

**Comment by nheagy** [comment]
Thanks @ScoutHarris!

**Comment by stephanethomas** [comment]
@nheagy: does it mean we can send formatted codes again now (i.e. merge D11117-code and https://github.com/Automattic/wp-calypso/pull/23176)?

**Comment by nheagy** [comment]
@stephanethomas sadly, `9.7` isn't yet available on the App Store. We can coordinate the rollout (with @diegoreymendez) but I'm guessing we won't want to change back for a few weeks _after_ the 9.7 release, to be sure that most people have upgraded.

**Pull request merged**
