### PR TITLE
Update Jetpack App Store keywords to include WordPress

### PR DESCRIPTION
**Pull request by staskus**
Context: p1715982219773889-slack-C072SR2B86Q

### CODE REVIEW

**Review by guarani — APPROVED** [review]
Makes sense, thanks @staskus!

**Comment by guarani** [comment]
Should we add this to the beta instead?

**Comment by kean** [comment]
They don't? Great catch!

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR contains changes to <code>RELEASE-NOTES.txt</code>.<br />
Note that these changes won't affect the final version of the release notes as this version is in code freeze.<br />
Please, get in touch with a release manager if you want to update the final release notes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/289">24.9 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by guarani** [comment]
I added `wordpress` to the other locales. I assume the localization process will still be triggered for 25.0, but translators will see that `wordpress` is already included in each locale and do nothing. 

If we only modify the default locale, I think this change won't reach non-English locale users, which would be a missed opportunity IMO.

Again, if we target `trunk` instead of the release branch, we would miss the opportunity to change these keywords sonner since 25.0 will be released publicly in three more weeks.


Notes:
- I used `WordPress` or `wordpress` depending on each locale. Some used capitals while others didn't. 
- I removed spaces from keyword lists since they're not needed
- The order of the keywords doesn't matter

**Comment by guarani** [comment]
Looping in @salimbraksa as release wrangler: we've updated the Jetpack app's keywords to include `WordPress` since, surprisingly, it wasn't there. Having it lets us reach more people searching for WordPress, which should lead to more downloads. 

I'm not sure if/how this change will affect the release process, but I can't see any issues yet. Feel free to reach out in p1715982219773889-slack-C072SR2B86Q if you have questions 🙇

**Comment by guarani** [comment]
👋 @kean, could you give this a review please? Asking so we can land this today since we're in the 2nd week of the beta.

**Review by kean — APPROVED** [review]

**Pull request merged**
