### PR TITLE
Replace occurrences of 'sign in' with 'log in'

### PR DESCRIPTION
**Pull request by nheagy**
Replaces occurrences of "Sign in" with "Log in" so as to be consistent with wp-admin, WordPress.com, and mobile FAQ.

login signin examples

To test:

- Primarily, the login/NUX screens should now say "Log in". 
- The 3D touch shortcut when logged out should say "Log in"
- There are also a few user-facing errors that mention "sign in".

What do you think about this, @mattmiklic ?

Needs review: @aerych

### CODE REVIEW

**Comment by aerych** [comment]
Ahh... the never ending question: "log in" or "sign in" :D 
Let's get @mattmiklic's thoughts for sure, esp. since he was involved in the design of the iOS sign in flow.

**Comment by mattmiklic** [comment]
Consistency FTW. 👍 

My rule of thumb that labels in the apps should match labels in Calypso, if the actions or features do the asme thing. I'm not sure why I didn't catch this when I did my previous pass on the login form, but I agree that this is a good change to make.

**Comment by aerych** [comment]
Looks like `WordPress/WordPress.xcodeproj/project.pbxproj` has some cocoapod related changes included.  I'm not sure what those could be for.  Any thoughts on those changes @nheagy ?  If its not necessarily related to the log in / sign in change maybe it could be discarded from this PR?

**Comment by rachelmcr** [comment]
Just a quick note that I opened a matching Android issue to suggest the same change there. When possible, it's really helpful to make terminology changes like this on both platforms at once. It makes it easier for us to keep our FAQs up to date (since we can use one FAQ for both platforms) and makes it easier for Happiness Engineers to use the right terminology with users.

**Comment by nheagy** [comment]
@aerych I removed the cocoapod-related changes. Thanks for catching that 😀

**Comment by aerych** [comment]
:shipit: :)

**Pull request merged**
