### PR TITLE
Update Helpshift to 6.1.0

### PR DESCRIPTION
**Pull request by koke**
Originally a branch for Xcode fixes, after merging the cocoapods update and the latest aztec changes, the only errors remaining was updating Helpshift to 6.1.

App builds. Unit tests are passing. UI Tests are throwing some inconsistency errors, but I have to investigate more.

Related: #7343

### CODE REVIEW

**Comment by elibud** [comment]
@koke can you check if the `CocoaLumberjack.swift` file needs updating? Thanks

**Comment by koke** [comment]
Looking at the diff, I only see whitespace changes with our `CocoaLumberjack.swift` version

**Comment by elibud** [comment]
Excellent! I'll take this one for a spin later today, thanks for checking.

**Comment by elibud** [comment]
👏 All good, tested submitting a ticket, all tags were present, the FAQ also worked as expected. Linking this https://github.com/wordpress-mobile/WordPress-iOS/pull/7773 as a reminder for both of us, the last one to merge should check that it still works as expected.
:shipit:

**Comment by koke** [comment]
Tested that #7773 still works after merging develop back in.

**Pull request merged**
