### PR TITLE
Images: Fixes an issue with image layout after rotation.

### LINKED ISSUE #10099: WPImageViewController has broken layout on rotation
Edit: This isn't just limited to gifs, and happens for any images viewed full screen.

When previewing gifs in `WPImageViewController`, the image doesn't remain fixed to the centre of the view if you rotate the device:

This affects the new Giphy integration, as well as simply previewing gifs that are already present in your media library.

**To reproduce**

Either:

* Upload a gif to the site via your computer
* Open the Media Library for a site
* Find the gif you uploaded, and tap to view its details
* Tap the gif preview to view it full screen
* Rotate the device

Or

* Open the Media Library for a site
* Tap +
* Choose Giphy
* Tap one or more gifs to preview
* Tap Preview in the bottom toolbar
* Rotate the device

Tested on iPhone X (device) and iPhone 8 (simulator), iOS 11.4 and iOS 12, WPiOS 10.8

### PR DESCRIPTION
**Pull request by aerych**
Fixes #10099 
Refs #13757 (fixes?)

The call to `centerImage` was happening before final layout was determined, and was thus using stale geometry. Animating the change along side the transition seems to fix the issue.

To test:
With an iPhone (or iPhone simulator) preview an image either in the Reader or via the Media feature (they both use the WPImageViewController). 
Switch between portrait and landscape orientation.  Confirm the image is correctly positioned.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

@frosty could I trouble you for a review?

### CODE REVIEW

**Review by frosty — APPROVED** [review]
Thank you for fixing this! I can confirm that images are rotating correctly for me.

Should we add this as a bug fix note to the release notes?

**Comment by aerych** [comment]
> Should we add this as a bug fix note to the release notes?

Sure thing.  How does that look?

**Review by frosty — APPROVED** [review]
Looks good to me! :shipit:

**Comment by aerych** [comment]
Thanks @frosty !!

**Pull request merged**
