### PR TITLE
Hide partner themes from theme browser

### LINKED ISSUE #21932: Partner themes should not be listed on mobile
### Expected behavior
Partners themes should not be listed on mobile because they need to be subscribed to before activating them, and we currently do not support subscribing to them. 
The same issue was addressed on Android by using `theme_type` field from the themes endpoint response: https://github.com/wordpress-mobile/WordPress-Android/pull/19497

### Actual behavior
Partner themes are displayed on the themes screen, and attempting to activate them results in an error message.

https://github.com/wordpress-mobile/WordPress-iOS/assets/2471769/0922e687-1b4d-466d-ba33-97edf54bd50c

### Steps to reproduce the behavior
1. Launch the JP app.
2. Login with a site that you own and have a business plan.
3. From the My Site tab, tap the "More" button on the shortcut list.
4. Tap Themes.
5. Search for partner themes, such as "Scentina" or "Kereta".
6. Observe that the partner theme is included in the list.

##### Tested on iPhone 15 Pro Simulator, iOS 17.0, Jetpack iOS 23.6

### PR DESCRIPTION
**Pull request by guarani**
The Jetpack app should hide all partner themes because they require a separate purchase. Paid non-partner themes will still be shown because the app shows a helpful message when users attempt to active them: "Please upgrade your plan to access this theme". 

> [!IMPORTANT] 
> AT sites aren't showing paid themes due to a separate issue, see https://github.com/wordpress-mobile/WordPress-iOS/pull/22812#issuecomment-1995140378)

When a user tried to activate a partner theme, the unhelpful message, "The specified theme could was not found" was shown. Instead of updating the message, this PR matches Android's behavior in https://github.com/wordpress-mobile/WordPress-Android/pull/19497 by hiding partner themes.

Related: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/750

Fixes #21932

#### Partner themes are hidden
1. On WP.com, locate a Partner theme at `https://wordpress.com/themes/partner/{your site}.wordpress.com`
2. In the JP app, open My Site > More > Themes 
3. Verify that the partner theme is not there

#### Free themes are visible
1. On WP.com, locate a Free theme at `https://wordpress.com/themes/free/{your site}.wordpress.com`
2. In the JP app, open My Site > More > Themes 
3. Verify that the Free theme is there

#### Purchased partner themes are visible
1. On WP.com, locate a Partner theme at `https://wordpress.com/themes/partner/{your site}.wordpress.com`
2. Install it on your site (likely needs a Creator plan)
3. In the JP app, locate the site, and open My Site > More > Themes 
4. Verify that the purchased partner theme is shown at the top of the list

#### Other scenarios
- A self-hosted site without Jetpack won't show the themes screen at all 
- A Jetpack-connected self-hosted site should show WP.com themes (and possibly .org themes)

## Regression Notes
1. Potential unintended areas of impact: Theme screen
2. What I did to test those areas of impact (or what existing automated tests I relied on): Manual testing
3. What automated tests I added (or what prevented me from doing so): I think it might be worth adding tests but didn't investigate further than to look at `ThemeServiceTests`

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist: 
- [x] WordPress.com sites and self-hosted Jetpack sites

### CODE REVIEW

**Review by staskus — APPROVED** [review]
Thanks for the fix! 

The original issue was about _Partner themes should not be listed on mobile_ (https://github.com/wordpress-mobile/WordPress-iOS/issues/21932) which is now working well, therefore I am approving the PR.

However, I noticed that for other cases WP.com behaves differently from the app. I suppose not as much attention was paid for Themes purchasing on the app so these cases are not fully handled:

✅ Starter themes are hidden:
Both Starter and Premium themes are hidden. However, they are also hidden for sites with a Creator plan that have these themes included. I think we should include them if possible for sites that can install these themes.
✅ Partner themes are hidden
✅ Free themes are visible
❌ Purchased paid themes are visible:
I chose Cakely theme which requires to Upgrade the plan to activate. After I purchased the plan and activated the theme, it still wasn’t visible on Themes page on the app. Is there another way to purchase a theme?
✅ A self-hosted site without Jetpack won't show the themes screen at all
✅ A Jetpack-connected self-hosted site should show WP.com themes 
❌ (and possibly .org themes):
Only [WP.com](http://wp.com/) themes are shown. For example, “Hello Elementor” theme is visible on wp-admin but cannot be found on the app. However, it’s a bit confusing. If I visit the “Appearance - Themes” through [WP.com](http://wp.com/) for Jetpack-connected site, then I need to upgrade to install “Hello Elementor”. If I visit “Appearance - Themes” through self-hosted WP-admin, then I can install “Hello Elementor” theme. Also, after I install “Hello Elementor”, it is shown as “Current Theme” in themes but I cannot find it when searching.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by guarani** [comment]
> ✅ Starter themes are hidden:
> Both Starter and Premium themes are hidden. However, they are also hidden for sites with a Creator plan that have these themes included. I think we should include them if possible for sites that can install these themes.

Good catch! This was possible before this PR, so I'll restore this. It used to show a helpful message, "Please upgrade your plan to access this theme," (see https://a8c.slack.com/archives/C0180B5PRJ4/p1709752911304329?thread_ts=1709748614.878359&cid=C0180B5PRJ4) when the user tries to activate a non-partner theme they don't have a plan for. For partner themes, the error message is not helpful, "The specified theme could was not found", so this is something I want to address.

<details>
<summary>I couldn't find a good way to show only paid themes the user has access to</summary>

I looked at two options for showing only the themes the user can access on their plan:
- Get the user's plan from https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/ and fetch only themes compatible with that plan e.g. `/themes?tier=personal`. The challenge here is that the site endpoint returns `personal-bundle-monthly` while the theme endpoint expects `personal`, and I don't think mapping them in the app would be robust.
- Get the user's current theme, find its plan (which is of the correct format, e.g. `personal`), and request themes for that plan. This should work, but might slow down the screen's loading time, because the app would need first to fetch the current theme and then fetch the available themes that are compatible with the current theme's plan (right now the app makes these requests independently of one another). It'll also require updating the `Theme` Core Data entity (a migration) to include the theme tier. 

Neither seemed great, so I stopped here. 

</details>

So I'm going to hide partner themes using `theme_tier == managed-external`, like Android did. It's the simplest solution to address the issue this PR is trying to fix. 

> ❌ Purchased paid themes are visible:
> I chose Cakely theme which requires to Upgrade the plan to activate. After I purchased the plan and activated the theme, it still wasn’t visible on Themes page on the app. Is there another way to purchase a theme?

I'll just reply here even though it's no longer relevant: Yesterday, I purchased a Creator plan on WP.com and set my theme to Feeling Good, which showed up at the top of the list of themes under Current Theme.

❌ (and possibly .org themes): 

That's odd, I'll test this with the new changes and see if I can understand how it works. 

---

I'll let you know when this is ready for a re-review since I've made significant changes since you reviewed.

**Comment by guarani** [comment]
#### Partner themes are hidden
✅ I checked that the Kereta partner theme is not visible in the app

#### Free themes are visible
✅ I checked that the Alter free theme is visible in the app

#### Purchased partner themes are visible
✅ I purchased a partner theme (see instructions here p1695056335721129/1695055562.563419-slack-C029JEQRVRT) and checked it's shown first in the list of themes.

#### A Jetpack-connected self-hosted site should show WP.com themes (and possibly .org themes)

On WP.com's Appearance > Themes, I saw the Upgrade pill on the Hello Elementor theme, but could still click through and activate the theme. I could also activate it on the site's wp-admin. 

On the JP app, I don't see Hello Elementor, so that does seem like an inconsistency that could be fixed separately. 


--- 

This is ready for another review 🙇

**Review by staskus — APPROVED** [review]
✅ Partner themes are hidden
✅ Free themes are visible
✅ Purchased partner themes are visible
It worked well now I purchased SolarOne theme with a Creator plan using instructions and it showed up on the Jetpack app Theme page.
❌ Premium themes are visible
They are still not visible to me but they are also not visible on the trunk. I have a Creator plan and Explorer/Starter themes are available on the web but not the app. 

I also tested with an Explorer plan but Explorer themes do not show up for me on the app. For example, the Cakely theme you shared here p1709752911304329/1709748614.878359-slack-C0180B5PRJ4 doesn't show up for me both on trunk and on your branch. Any ideas what could be the case?

**Comment by guarani** [comment]
I reproduced this by installing a plugin on my site after buying the ~~plugin~~ plan (to make the site AT). Now, I can't see premium themes either. Without the plugin, despite having the Creator plan, the app does not support custom themes:

https://github.com/wordpress-mobile/WordPress-iOS/blob/549ace59b386cffab28e9f9b6d57d14d88340b02/WordPress/Classes/Services/ThemeService.m#L166

and calls the `v1.2/sites/171152168/themes` endpoint.

With the plugin, the app supports custom themes and calls a different endpoint: `/v1.2/themes` and requests only free themes:

https://github.com/wordpress-mobile/WordPress-iOS/blob/549ace59b386cffab28e9f9b6d57d14d88340b02/WordPress/Classes/Services/ThemeService.m#L168

To include paid themes, the app has to support `BlogFeaturePremiumThemes`, but that requires a Jetpack Professional plan:

https://github.com/wordpress-mobile/WordPress-iOS/blob/549ace59b386cffab28e9f9b6d57d14d88340b02/WordPress/Classes/Models/Blog.m#L578-L580

This logic is outdated (see p1710190776075689/1710183825.709389-slack-C0CMN0V97), so this should be fixed in another PR. 

I'm reasonably confident this is the issue you caught, so I'll go ahead and start merging these PRs. Thanks @staskus!

**Comment by staskus** [comment]
@guarani, thanks for explaining!

> This logic is outdated (see p1710190776075689/1710183825.709389-slack-C0CMN0V97), so this should be fixed in another PR.

Yes, it all sounds super outdated. I feel Themes is one of the features we could consider removing altogether if we're not supporting it properly.

**Pull request merged**
