### PR TITLE
Fix issue where viewing search result user details automatically pops back

### PR DESCRIPTION
**Pull request by crazytonyli**
> [!Note]
> This PR is built on top of https://github.com/wordpress-mobile/WordPress-iOS/pull/23855.

To reproduce the issue:

1. Go to users list
2. Tap the search bar and search
3. Tap a user in the search result.

The app should stay on user details view, but it goes back to the users list almost immediately after entering the user details screen.

The root cause is the users list is refreshed (due to a full users list is assigned to `sortedUsers`) when tapping a user details. The fix here is, only displaying search result when in search mode.

## Regression Notes
1. Potential unintended areas of impact

5. What I did to test those areas of impact (or what existing automated tests I relied on)

6. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by crazytonyli** [comment]
The issue will be addressed in a separate PR using a different approach.

**Comment by kean** [comment]
Hey, is it ready for review? The PR is marked as draft and has conflicts.

**Comment by crazytonyli** [comment]
I'll close this PR since the issue has been fixed in a different way.

**Pull request closed without merging**
