### PR TITLE
My Site Dashboard: Posts Cards improvements

### PR DESCRIPTION
**Pull request by leandroalonso**
Part of #17875

This PR adds some improvements to the posts card feature (and the MSD as a whole) such as:

* Only refreshing a card if new data comes from the API
* Reuse existing post lists being presented for performance reasons
* Fix a bug when syncing/showing posts
* Do not sync posts if not needed

#### PostsCardViewController and Instruments

Given `PostsCardViewController` are now dequeued and reused, there must be a maximum of 2 `PostsCardViewController` at the same time, doesn't matter how many site switches you perform.

1. Open Instrument > Allocations
2. Run WordPress
3. Start recording
4. Add `PostsCardViewController` in the filter
5. Make sure there will never be more than 2 `PostsCardViewController`

#### Syncing posts correctly

1. Open a site with drafts (or scheduled) and tap Dashboard
2. Go to web and create a new draft (or schedule) post for this blog
3. On the app, tap "Site menu" and "Dashboard" again
4. The post your created should appear

#### Switching between "Site menu" and Dashboard

1. Open the dashboard for a site
2. Go to site menu
3. Go back to dashboard
4. The cell should not be updated (you can put a breakpoint on `DashboardPostsCardCell.configure`

## Regression Notes
1. Potential unintended areas of impact
n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a

3. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by momo-ozawa — COMMENTED** [review]
@leandroalonso Testing instructions work as described. I found an issue for offline dashboard behavior. For sites that are supposed to display the no posts / next post cell, the cell isn't displayed correctly.

1. Go to the dashboard
2. Turn off wi-fi
2. Switch to a site that should display no posts or next post
3. Notice that the cell content isn't displayed

 | 
-- | --

**Comment by leandroalonso** [comment]
@momo-ozawa fixed!

To reproduce that easily (and check the fix), I recommend installing the Network Link Conditioner and using the 100% Loss profile.

**Comment by momo-ozawa** [comment]
@leandroalonso I'm seeing a different issue -- The wrong card is shown when switching from a site to No Posts -> Next Post while offline. Below are steps to reproduce this issue.




1. Run app (no need for a fresh install)
2. While on the Site Menu tab, select a site with no posts
3. Turn on Network Link Conditioner and use the 100% loss profile 
4. Switch to the Home tab
5. Wait until the loading icon disappears
6. While on the Home tab, switch to a site that should show the next post card
7. 👀 Notice that the "Create your first post" card is shown
8. Turn off Network Link Conditioner
9. Switch to the Site Menu tab then switch back to the Home tab
10. 👀 Notice that the "Create your first post" card is shown
11. Force quit the app and reopen it again
12. Switch to the Home tab
13. 👀 Notice that this time, the correct card is displayed ("Create your next post")

**Comment by leandroalonso** [comment]
@momo-ozawa good catch!

Since there are a few PRs opened right now (all depending on this one), what do you think about merging this one, and then I can tackle this issue on a separate PR? This way we can merge the pending PRs.

(already added as a task in #17875)

**Comment by momo-ozawa** [comment]
@leandroalonso Agreed!

**Review by momo-ozawa — APPROVED** [review]

**Pull request merged**
