### PR TITLE
Rich Text: Filter new lines.

### PR DESCRIPTION
**Pull request by aerych**
This PR fixes an issue where new lines ( `\n` ) would cause doubled paragraph spacing when combined with P tags, and additional bullet points when combined with LI tags when converting an HTML formatted string to an NSAttributedString.

To test:
Wait until the refreshed comments are merged to develop.
The easiest practical test is to create a comment with a list and add an extra carriage return between the list items.  This is easiest to do with the web-editor in a O2/P2 theme.
Confirm the bug by viewing the issue in the refreshed comments UI.
Confirm the fix by switching to this branch and viewing the comment again. 

Confirm the updated test passes.

Needs review: @kurzee

### CODE REVIEW

**Comment by aerych** [comment]
Updated for the comments refresh and Swift 3.  Ready at your leisure @kurzee :)

**Comment by kurzee** [comment]
Found this one while testing, related to comments in general, separate from this change: https://github.com/wordpress-mobile/WordPress-iOS/issues/6344

**Comment by kurzee** [comment]
BuddyBuild might need to rebuild without cache.

**Comment by aerych** [comment]
> whether or not we should filter out any of the other newline/return characters

I got to thinking about this.  Since our content is HTML new line characters should be ignored, except for when they are inside a pre tag. In that case we would want to preserve them, so this filter is a bit too greedy. Let me see what I can do to tweak it a bit for that special case.

**Comment by aerych** [comment]
@kurzee I've updated things to preserve new lines inside pre tags.  Another look for paranoia?

**Comment by kurzee** [comment]
Looks like there is a `<pre>` issue, separate from this change: https://github.com/wordpress-mobile/WordPress-iOS/issues/6346

**Comment by kurzee** [comment]
@aerych great catch with allowing new lines in pre tags! Tested it out, works as expected, code looks good. Just the separate issue above, unrelated to this change.

:shipit:

**Comment by aerych** [comment]
Thanks as always @kurzee !!! :)

**Pull request merged**
