### PR TITLE
Jetpack Focus: New users phase menu card and overlay display logic

### LINKED ISSUE #19453: Jetpack Focus: Display Jetpack overlay for new users on login
## Description

This should only be displayed once. And only for new users.

Ref: pe7hp4-4k-p2
Design Ref: qk5s4q4mZsXknwhMWo2vIY-fi

## Tasks
- Update overlay content
- Track events

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Closes #19453

## Description
This PR adds the menu card for new users. It also tweaks when the remote feature flags are updated. Instead of updating them after login is complete, we update it them during login, so they are always ready post-login. 

### Screenshots

| Light Mode | Dark Mode |
| - | - |
|light|Simulator Screen Shot - iPhone 14 Pro - 2023-01-12 at 01 26 27|

## Pre-testing Instructions
- To disable the learn more button:
    - Go to `JetpackFullscreenOverlayGeneralViewModel.swift` line 183
    - Replace this line with `return nil`
    - This won't be needed in production since the learn more button will be disabled remotely by then
- To enable the new users phase on login (Not needed if using the [test account](https://github.com/wordpress-mobile/WordPress-iOS/pull/19894#issuecomment-1379622320))
    - Go to `FeatureFlag.swift` line 130
    - Replace this line with `return true`
    - Go to `FeatureFlag.swift` line 150
    - Replace this line with `return "dummy_key"`

## Testing Instructions

1. Fresh install the app
2. Log in
3. Choose any blog
4. You should eventually land on My Site
5. Make sure the overlay is displayed
6. Dismiss the overlay
7. Make sure the card is displayed and matches the design

## Regression Notes
1. Potential unintended areas of impact
Sign-in and sign-up flows

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested manually.

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hassaanelgarem** [comment]
@enejb is working on adding a test account with the new users flag enabled. It would be great to test this PR using that test account when created, to make sure the feature flags are refreshed correctly during login.

**Review by momo-ozawa — COMMENTED** [review]
@hassaanelgarem 

Are we meant to be showing the "Learn more at jetpack.com" button in the overlay? I thought we were hiding this link for the new user overlay?

Screenshot 2023-01-12 at 17 28 40

**Comment by hassaanelgarem** [comment]
@momo-ozawa I'm not entirely sure. I started this slack thread (p1673545326946679-slack-C04564QS0V7) to gain some clarity on this.

**Comment by hassaanelgarem** [comment]
@momo-ozawa I've applied the outcome of the slack thread in #19907 because it touches both new users and self-hosted phases.

**Review by momo-ozawa — APPROVED** [review]

**Pull request merged**
