### PR TITLE
Issues/3888 model cleanup

### LINKED ISSUE #3888: Define defaults property values in the model, vs initializer methods
The Post service's `initializeDraft:` method assigns starting values for several properties.  It seems like it would make more sense to do this in the model by assigning default values to these properties. 

Update `AbstractPost` and assign the following properties their default values:
- `remoteStatus`:  2 (`AbstractPostRemoteStatusLocal`)
- `status`: publish (`PostStatusPublish`)
- `metaPublishImmediately` : 1 (`YES`)
- `metaIsLocal` : 1 (`YES`) 

Remove the hack setting date_created_gmt to nil added in #3887

### PR DESCRIPTION
**Pull request by aerych**
Closes #3888 
This PR updates the default values for new post and pages. Status is defaulted to publish and metaPublishImmedately is defaulted to true.  This let us remove some initialization for new drafts from the PostService and keeps defaults in the model. 
Tests were added for checking default properties are correctly assigned and that changes to either the date_created_gmt and remoteStatus are properly reflected in the meta properties used for sorting. 

@astralbodies would you do the review honors? Also @diegoreymendez as this affects the the post models and by extension touches the Editor. 

Needs Review: @astralbodies, @diegoreymendez

### CODE REVIEW

**Comment by astralbodies** [comment]
You could potentially just add these changes to model 33 since it hasn't been released to any internal testers or contained in a release branch. It might be easier to keep this as a separate model version since 32 > 33 was a heavy migration.

:shipit: from me for the model. If you feel inclined to merge the changes into model 32, let me know and I'll review again.

**Comment by aerych** [comment]
> You could potentially just add these changes to model 33 since it hasn't been released to any internal testers

I am a fan of not adding more revisions than necessary.  ;)

**Comment by aerych** [comment]
@astralbodies I'm gonna change up a few things and we'll re-target this one for 5.5

**Comment by diegoreymendez** [comment]
@aerych - This is working great for me.  Let me know when it's ready for 5.5.

**Comment by aerych** [comment]
Closing in favor of #3979

**Pull request closed without merging**
