### PR TITLE
Adding in tracking for when photos are added

### PR DESCRIPTION
**Pull request by sendhil**
We weren't tracking when photos were added to the editors in Mixpanel. This PR fixes that.

cc @bummytime @diegoreymendez @meremagee

### CODE REVIEW

**Comment by bummytime** [comment]
Word! :shipit:

**Comment by diegoreymendez** [comment]
:shipit:

**Comment by sendhil** [comment]
We're probably going to want to cherry pick this into 4.7.1 so we can do some good before/afters with the new editor.

**Comment by diegoreymendez** [comment]
@sendhil - Sounds good... want to try that yourself or do you prefer me to do it?  Either way would be ok.

**Pull request merged**
