### PR TITLE
Issue/4471: Remove "Private" privacy setting for Jetpack sites

### LINKED ISSUE #4471: Blog Settings: Privacy settings do not match available options for Jetpack connected blogs.
Site settings shows the Privacy option for Jetpack connected blogs and the available options are public, hidden, and private.  The "private" setting is only respected by wpcom hosted blogs and choosing this option on a Jetpack connected blog appears to have the same effect as choosing public. 

Probably only Public and Hidden options should be displayed.

### PR DESCRIPTION
**Pull request by frosty**
Fixes #4471. The "Private" privacy setting is only supported by wpcom sites, so I've removed this setting if a site is self-hosted. I've also tidied up `SiteSettingsViewController` a little by moving some code into the existing `BlogSiteVisibilityHelper`, which I've also added unit tests to.

### To Test

1. Sign into a wpcom account with a connected Jetpack blog.
2. Select the site in the Sites list, and choose Settings (under Configure).
3. Select Privacy (under General).
4. Ensure that only the Public and Hidden options are available, and that their hint text is correct.

Also ensure that:

- For a non-Jetpack self-hosted site, the Privacy option isn't available at all (I haven't touched this, but it's worth verifying).
- Unit tests pass.

Needs review: @SergioEstevao

### CODE REVIEW

**Comment by astralbodies** [comment]
@frosty Can you bring this branch current?
@SergioEstevao Are you able to review this soon?

**Comment by frosty** [comment]
Done! :)

**Comment by SergioEstevao** [comment]
Can we move the class ```BlogSiteVisibilityHelper``` to be near the ViewController? the Utility folder doesn't look a good place to have this class in.

**Comment by SergioEstevao** [comment]
After moving the utility class feel free to :shipit: @frosty

**Comment by astralbodies** [comment]
`BlogSiteVisibilityHelper` really isn't about the UI layer of the app though IIRC.

**Comment by SergioEstevao** [comment]
It's helping deciding string to show in the UI. 

BTW that is why I don't like the ```Utility``` folders they ends up to being a sink where we put everything.. that is hard to find a category :)

**Comment by frosty** [comment]
Okay, so `BlogSiteVisibilityHelper` was also being used from within the `Blog` class. I've extracted this method out into `BlogSiteVisibilityHelper` so that there are now no usages of `BlogSiteVisibilityHelper` outside of `SiteSettingsViewController`. Now that this is the case, I've moved the files as @SergioEstevao requested.

@SergioEstevao Would you mind quickly reviewing the new changes, as I did a little more than just move the files? Thanks!

**Comment by SergioEstevao** [comment]
@frosty I see that you move the class inside the group on Xcode, did you moved the file in the file system also?

**Comment by frosty** [comment]
I have now – sorry, missed that!

**Comment by SergioEstevao** [comment]
:shipit:

**Pull request merged**
