### PR TITLE
Update to cocoa pods 1.3.1

### PR DESCRIPTION
**Pull request by SergioEstevao**
This PR updates the cocoapod version to 1.3.1

To test:
 - Try to build the app from scratch using the version 1.3.1 
 - Run the app on simulator and device
 - Try to make an archive and check if all is good.

### CODE REVIEW

**Comment by elibud** [comment]
@koke do you remember what was stopping us from updating to Cocoapods 1.3.1 so I can double check that's not an issue on this PR? Thx

**Comment by koke** [comment]
@elibud sorry, I have zero memory of that 🤦‍♂️

**Comment by SergioEstevao** [comment]
@elibud it's building and running ok for me, could you try to build the archive for a release just to see if it works ok?

**Comment by SergioEstevao** [comment]
@elibud 

1. I had a look on the project after `pod deintegrate` and the scripts changes look mainly moving of scripts up and down the file, but no real change on the scripts.
2. Just update it
3. On Xcode 9 we get build errors because one of our pods CocoaLumberJack will need to be update to a later version that conforms to some more stricter compiler rules.

**Comment by elibud** [comment]
Since it doesn't work on XCode 9 I don't think we can update then, but you can try updating CocoaLumberJack first and then see what happens.

**Comment by SergioEstevao** [comment]
@elibud I update CocoaLumberjack and now it build fine on Xcode 9.

**Comment by elibud** [comment]
That's great @SergioEstevao :) I'm adding @astralbodies and @koke as reviewers. 
@koke was planning on looking into our issues with XCode 9 and I think this upgrade might be relevant to that. 
@astralbodies might remember what I don't, which is why we couldn't upgrade to 1.3.1 before.
I'll take another look a this later today and will mark is as approved from my side.

**Comment by koke** [comment]
Pushed d77485a to also update the bundled cocoapods version, so `rake dependencies` does the right thing

**Comment by elibud** [comment]
Lets go ahead and merge this one @SergioEstevao, now that we've decided to skip one release we'll have time to sort things out if something is amiss.

**Pull request merged**
