### PR TITLE
Extract delete user confirmation sheet into its own view

### PR DESCRIPTION
**Pull request by crazytonyli**
> [!Note]
> This PR is built on top of https://github.com/wordpress-mobile/WordPress-iOS/pull/23834.

Nothing too interesting really. Just moving a ViewBuilder function to a View type.

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/303">25.6</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by kean — APPROVED** [review]

**Comment by kean** [comment]
The current form look a bit off.

Screenshot 2024-11-20 at 8 55 21 AM

Id suggest the following changes (not necessarily in the scope of this PR):

- Shorter title for the field and remove `:`
- Push list of users in the navigation stack + use the same design and maybe even code to render the post list
- Smaller spacing for the header

Screenshot 2024-11-20 at 8 37 07 AM


```swift
        Form {
            Section {
                NavigationLink {
                    EmptyView()
                } label: {
                    HStack {
                        Text("Selected User")
                        Spacer()
                        Text("username2")
                            .foregroundStyle(.secondary)
                    }

                }
            } header: {
                Text("Select the user to attribute the content of the site to")
                    .font(.body)
                    .textCase(nil)
                    .foregroundStyle(.primary)
                    .padding(.bottom, 8)
            }
        }
```

**Comment by crazytonyli** [comment]
@kean Thanks for the suggestion. I have update the UI to also include a short helper message.

**Comment by crazytonyli** [comment]
⬆️ Rebased without code changes.

**Pull request merged**
