### PR TITLE
WordPressCom API Cleanup

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:
- Push Token Registration / De-registration has been moved over to *NotificationsService*
- WordPressComApi cleanup =)

Note: This cleanup is just one piece, of a much bigger refactor (Reference: #4069).

#### Scenario 1: Registration
1. Fresh install WPiOS
2. Log into your account and enable Push Notifications

Verify that the PN's are effectively received.

#### Scenario 2: Un-registration
1. Right after testing Scenario 1, logout from your account

Verify that PN's are not received anymore.

Needs Review: @astralbodies 
Thanks Aaron!

### CODE REVIEW

**Comment by astralbodies** [comment]
Code looks good - still need to test the functionality

**Comment by astralbodies** [comment]
Reviewing functionality now.

**Comment by astralbodies** [comment]
Looks solid @jleandroperez  - :shipit:

**Comment by jleandroperez** [comment]
Thank you @astralbodies !!

**Pull request merged**
