### PR TITLE
Notifications: enable mark all as read button

### LINKED ISSUE #17135: Feature Request: Mark all notifications as read
Requested in 4280910-zd-woothemes from a Jetpack iOS app user:

> It would be nice to mark all notifications as read

I agree that it would be nice to have an option to mark all notifications as read, especially when we have old and outdated notifications.

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #17135

This enables the Notifications nav bar button to mark all notifications as read.

To test:
- Go to Notifications.
- Verify a checkmark icon now appears in the nav bar to the left of the settings button.
- For filters that do not have unread notifications, the checkmark is disabled.
- For filters that do have unread notifications, the checkmark is enabled.
- Tip: if you don't have any unread notifications, swipe right on a notification row to mark it unread.

| read | unread |
|--------|-------|

- On a filter that has unread notifications, tap the checkmark button.
- On the alert:
  - Verify `Cancel` cancels the action.
  - Verify `OK` marks notifications in that filter as read, and the nav bar button is disabled.

| comment_confirmation | like_confirmation |
|--------|-------|

- Verify notifications in other filters are not.
- Note that, since the button applies to the selected filter, `All` and `Unread` will mark all unread notifications as read (thus affecting the other filters).

## Regression Notes
1. Potential unintended areas of impact
It's possible marking a single notification as read/unread could be affected.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Verified marking a single notification as read/unread still works as expected. And there are existing tests that passed.

3. What automated tests I added (or what prevented me from doing so)
Tests were added to WPKit.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
You can test the <strong>Jetpack</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/jetpack-installable-builds/'>here</a> with build number: <code>pr17840-ea7a1b9</code>. IPA is available <a href='https://appcenter-filemanagement-distrib2ede6f06e.azureedge.net/40c23264-00bf-487e-aaaf-fe66c2ddfeca/Jetpack%20Alpha.ipa?sv=2019-02-02&sr=c&sig=Q43XXJvN8WoOJy7oxY3ZAgTB0uovyyyBg2YaGNt4tGQ%3D&se=2022-01-29T21%3A51%3A58Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

**Comment by jkmassel** [comment]
You can test the <strong>WordPress</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/WPiOS-One-Offs/'>here</a> with build number: <code>pr17840-ea7a1b9</code>. IPA is available <a href='https://appcenter-filemanagement-distrib3ede6f06e.azureedge.net/b0603e96-6e44-4c12-b812-0b1875db4e2a/WordPress%20Alpha.ipa?sv=2019-02-02&sr=c&sig=MYreGfdE2xU3RWHaiGGffybmmrMzcz3bIT3nTp1QjCo%3D&se=2022-01-29T21%3A53%3A44Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

**Review by frosty — APPROVED** [review]
Tested with the various filter views as well as All, and worked as described 👍

**Comment by ScoutHarris** [comment]
Thanks @frosty !

**Pull request merged**
