### PR TITLE
iOS 16 Lock Screen Widgets: Today Views Widget

### PR DESCRIPTION
**Pull request by staskus**
Note: 
- All the work is done by @tzef, 
- Feature Flag Disabled (will be enabled once the feature is decided to be released)
- All the PRs merged into this branch are reviewed

## Description
This is the PR to merge the feature branch into the trunk. All commits are simply merging sub PR into this branch without introducing any new changes. All sub PR have been reviewed and are listed below for reference.

1. https://github.com/wordpress-mobile/WordPress-iOS/pull/20309
2. https://github.com/wordpress-mobile/WordPress-iOS/pull/20312
3. https://github.com/wordpress-mobile/WordPress-iOS/pull/20353
4. https://github.com/wordpress-mobile/WordPress-iOS/pull/20371
5. https://github.com/wordpress-mobile/WordPress-iOS/pull/20317
6. https://github.com/wordpress-mobile/WordPress-iOS/pull/20368
7. https://github.com/wordpress-mobile/WordPress-iOS/pull/20399
8. https://github.com/wordpress-mobile/WordPress-iOS/pull/20405
9. https://github.com/wordpress-mobile/WordPress-iOS/pull/20422
10. https://github.com/wordpress-mobile/WordPress-iOS/pull/20427

### Feature flag protect
Given `lockScreenWidget` feature flag disabled, note that this needs to be programmatically changed. It can't be overwritten in the app setting because the widget list updates along with the app installation.
1. Long press the lock screen to turn on editor mode
2. The Jetpack application shouldn't be in the selection page

**Enable `lockScreenWidget` feature flag the following testings**
### Only for Jetpack
1. Build WordPress target
2. Long press the lock screen to turn on editor mode
3. The WordPress application shouldn't be in the selection page

**Build `Jetpack` target for the following testings**
### Widget Selection (Fresh install or Logged out)
1. The Jetpack application should be in the selection page
2. The widget data should display placeholder data (My WordPress Site with 649 views today)

### Add to the lock screen
1. Tap the widget in the selction page
2. The widget should be added to the rectangular place (below the time)

### Logged-Out status
1. The widget content should be `LocalizableStrings.unconfiguredViewJetpackTodayTitle` ("Log in to Jetpack to see today's stats.") as the same as home screen today widget

### Redirection for unconfigured status
1. Tap the widget
2. The Jetpack app should open

### No-Sites status
1. Log in with the account without any websites
2. The widget should change the content to `LocalizableStrings.noSiteViewTodayTitle` ("Create or add a site to see today's stats.") as the same as home screen today widget

### Site-Selected status
1. Switch to the account with at least one website
2. The widget should change to success layout with stats data of the default website

### Widget Selection (Logged in)
1. Go to widget selection add one more widget
2. The widget data should display the stats of the default website instead of placeholder

### Switch Website
Given the logged-in account with more than one website
1. Tap widget in lock screen when editor mode
2. Select another website
3. The widget should be in rendering mode when fetching data
4. The widget should display the corresponding views in today

### Redirection for success status
1. Tap the widget
2. The app should open and redirect to the Stats/Days for the widget-selected website.

### Widget updated when stats data updated
Can temporarly change the `LockScreenSingleStatView` `Text(viewModel.title)` to `Text(viewModel.updatedTime.mediumStringWithTime())` for easy verification of the update.
1. Tap the widget redirect to the insights page to trigger the API refresh
2. The widget in lock screen should update when the new data date compared to widget data date is larger than one minute
3. The another widget with different selected website shouldn't update

### Widget autorefreshed per 30 mins
Changing system time is not working from my test, and the laptop can't be in sleep mode.
1. Wait for 30 mins (The mechanism is not very accurate, minutes of delay is acceptable)
2. The widget should be updated automatically

## Regression Notes
1. Potential unintended areas of impact
Home Screen Widgets

2. What I did to test those areas of impact (or what existing automated tests I relied on)
- Existing Widgets
Add today, this week, and all time widgets to the home screen, all won't be impacted after app updated
- Adding Widgets
After app updated, still able to add today, this week, and all time widgets to the home screen
- Shouldn't be impacted by lock screen widget feature flag
No matter if `lockScreenWidget` is enabled or disabled, the above two test cases should't be impacted

3. What automated tests I added (or what prevented me from doing so)
- `WidgetsViewModelMapperTests` test the view model is correctly converted from the stats data.
- `WidgetDataReaderTests` test the widget status is correctly converted based on the account and website status.
- `WidgetUrlSourceTests` test the widget URL is correct, and the source can be mapped to the right deep link source type for event tracking.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by staskus** [comment]
## Note for reviewers:

This is the work done by @tzef.  I'm creating the PR due to limited permissions.  All the PRs that went into this branch are already reviewed. 

- This is the whole functionality for Today Views widget (see description). 
- For now the feature flag is disabled, although in my opinion this could be the candidate for a release without additional functionality

**Review by sla8c — APPROVED** [review]
All test instructions worked for me.  @staskus I noticed that the test `Jetpack Build for Testing` still says `expected` and has not passed.

**Comment by guarani** [comment]
👋 @staskus, does this need a review?

**Comment by staskus** [comment]
> 👋 @staskus, does this need a review?

@guarani, thanks for checking.

Not now. Every single part of it is already reviewed. I will think if it makes sense to merge it now. It's under the disabled feature flag.

Regarding finishing the project. There's a lot of valuable functionality implemented, it could be a small project to add the missing pieces and release it.

**Comment by guarani** [comment]
Thanks @staskus! Let me know if I can help with anything.

**Comment by staskus** [comment]
I retested and merged with trunk. This PR is safe to merge since it has a feature flag disabled. 

| No site | Site | Logged out |
|--------------|--------------|--------------|
| Simulator Screenshot - iPhone 14 - 2023-09-04 at 12 54 26 | Simulator Screenshot - iPhone 14 - 2023-09-04 at 12 14 50 | Simulator Screenshot - iPhone 14 - 2023-09-04 at 12 12 13 |

**Comment by staskus** [comment]
@guarani, I want to merge this PR but it looks like this PR requires another review, although this is already approved. Could you review it?

This functionality is behind the feature flag. I want to merge it, and build upon it to include a few more configurations before releasing.

**Review by guarani — APPROVED** [review]
Hey @staskus, if I understand correctly, I can approve this without reviewing it because it's already been reviewed. Is that correct?

I'm leaving an approval, but if you'd like me to review it (go through the code, test it, etc.) before merging, I'd be happy to do that/

**Comment by staskus** [comment]
@guarani thanks! Yes, I think it's appropriate. It's all been reviewed and approved. You can test it once the feature flag will be enabled.

**Pull request merged**
