### PR TITLE
Update localization strings and scripts to use UTF-8 encoding

### PR DESCRIPTION
**Pull request by jtreanor**
This updates all string files to UTF-8 and changes our scripts to read and write strings files in UTF-8.

Note: `update-translations.rb` will just download whatever encoding it gets so we should go ahead with the GotPress change to UTF-8 also.

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/10192

To test:
- `./Scripts/localize.py` runs correctly.
- `./Scripts/update-translations.rb` runs correctly (although for now its still downloading in UTF-16LE)

### CODE REVIEW

**Comment by elibud** [comment]
cc: @akirk

**Comment by elibud** [comment]
If we merge this before changing GlotPress will things break?

**Comment by akirk** [comment]
GlotPress expects UTF-16LE and also outputs it, this was a deliberate decision (see pxLjZ-QT-p2 and p1537479214000100-slack-i18n), not sure if we can just change this in GlotPress–I don't know if other people also use this format.

Would it be possible to convert to and from UTF-16LE when talking to GlotPress?

**Comment by jtreanor** [comment]
Should have been clearer about this. Yes, this will not work correctly until GlotPress is updated.

Not sure how to link to it here but there is a P2 discussion with a pending change to GlotPress to do this. It triggered these changes.

If GlotPress isn’t changing, perhaps we should do this either.

Yes, it would be possible to translate to and from UTF-16LE for GlotPress. We could do this as a stopgap to allow compatibility.

**Comment by jtreanor** [comment]
Quick update here:

There was some confusion on my part about the difference between translate.wordpress.com and translate.wordpress.org. Only the former has moved to UTF-8 but WP-iOS uses translate.wordpress.org.

GlotPress-WP has already been updated to use UTF-8 (see https://github.com/GlotPress/GlotPress-WP/issues/957), but the new code is not yet on translate.wordpress.org. Once it deployed, we can make these changes.

I will leave this PR open until there is clarity on if the change will be made to translate.wordpress.org soon. If it will not happen soon, I'll close this and we can pick it back up when the code is deployed.

> Would it be possible to convert to and from UTF-16LE when talking to GlotPress?

After a closer look, this will not be possible. Since GlotPress fetches the strings from the repo directly they must be in UTF-16LE until the above code is deployed.

**Comment by jtreanor** [comment]
I'm closing this as there is no indication that the UTF-8 change will be made to GlotPress very soon. We can revisit this once it changes.

**Pull request closed without merging**
