### PR TITLE
What's New: Add chrome material background to the "Continue" button

### LINKED ISSUE #14720: Add system material background behind the Continue button in What's New
Following up discussions in  #14698, a system material background should be added behind the `Continue` button in the What's New page.

Here is how it should look like:
<p align=center>
Screen Shot 2020-08-21 at 1 52 59 PM
</p>

### PR DESCRIPTION
**Pull request by Gio2018**
Fixes #14720

Adds a chrome material background to the view containing the "Continue" button, and moves the table view behind that view to emphasize the blur effect (see example screenshots below):

**Note:** 
- **I added a few more fake announcements to emphasize the scrolling. These will all go away once the real data come in.**

Chrome Light | Chrome Dark
--- | ---
chrome light | chrome dark

To test:

- Go to Me/App Settings/What's New in Wordpress
- Make sure that the background of the view containing the "Continue" button matches the designs in #14720 and the sample screens above, and that the subtle blur effect is visible.
- Try different devices/simulators and orientations, and make sure that the views look right.

PR submission checklist:

- [x] ~~I have considered adding unit tests where possible.~~ Future PR
- [x] ~~I have considered adding accessibility improvements for my changes.~~ Future PR
- [x] ~~I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.~~ Not released.

### CODE REVIEW

**Comment by jkmassel** [comment]
We're cutting the `15.6` release today, so this PR is being bumped to `15.7`. If it needs to land in the `15.6` release, please merge it to the `release/15.6` branch, and DM me so that I can release a new beta build.

Thanks!

**Comment by Gio2018** [comment]
> We're cutting the `15.6` release today, so this PR is being bumped to `15.7`. If it needs to land in the `15.6` release, please merge it to the `release/15.6` branch, and DM me so that I can release a new beta build.
> 
> Thanks!

Sorry about that @jkmassel ! I meant to choose 15.7 but obviously made a mistake, thanks for fixing it!!

**Comment by Gio2018** [comment]
@osullivanchris @frosty moving this to draft as there's a couple of things that I need to fix before it's ready

**Comment by Gio2018** [comment]
> @osullivanchris @frosty moving this to draft as there's a couple of things that I need to fix before it's ready

It's now ready for review, thank you!!

**Review by osullivanchris — APPROVED** [review]
Looks good 😃

**Review by frosty — APPROVED** [review]
Looks great! :)

**Pull request merged**
