### PR TITLE
Merge 12.8 into develop

### PR DESCRIPTION
**Pull request by jkmassel**
Merges the recent 12.8 changes into `develop`. 

@diegoreymendez – I had to resolve conflicts with your code, feel free to take a look if have any concerns :) 

@ScoutHarris – I just added you as an FYI! :)

### CODE REVIEW

**Comment by jtreanor** [comment]
There seems to be a bunch of failing tests. I have re-run them to see if its flakiness.

**Comment by diegoreymendez** [comment]
@jkmassel - Apologies for that!  I'll check this PR now... I think it may make sense, when pushing a PR to a frozen branch, to also ask the person (me) afterwards to cherry pick their commits into `develop`.  Thoughts?

I don't think it's desirable for the release manager (or p9 in general) to solve these conflicts.

**Comment by diegoreymendez** [comment]
@jtreanor - The tests are failing locally as well... I'm trying to figure out what's up.

**Comment by jkmassel** [comment]
Closing this one down – we replaced it with https://github.com/wordpress-mobile/WordPress-iOS/pull/12115 due to some merge issues.

**Pull request closed without merging**
