### PR TITLE
Update ZenDesk to 3.0.2

### PR DESCRIPTION
**Pull request by jkmassel**
This PR updates ZenDesk to 3.0.2. Release notes for it can be found here: https://github.com/zendesk/zendesk_sdk_ios/releases/tag/3.0.2.

To test:
It's just a bug fix release, but we should thoroughly test any ZD functionality as part of this to ensure regressions haven't happened.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Ref #12701.

**Comment by ScoutHarris** [comment]
Hey @jkmassel this has no reviewers. What that an oversight - is it ready for review?

**Comment by jkmassel** [comment]
@ScoutHarris – it is ready for review!

Because there are no code changes, @designsimply was going to do hand-testing on it to ensure nothing is borked. If you would like to test as well, that would be super. :)

If you want to 👍 it once everyone is collectively convinced it's ok, that works for me!!

**Comment by ScoutHarris** [comment]
Hey @jkmassel .

I think @designsimply is poking at it, but it works fine for me.

**Comment by ScoutHarris** [comment]
Hey @jkmassel . I hate to be a pest, but can this be merged?

**Comment by ScoutHarris** [comment]
@designsimply I have a fix for #12779 pending (#12836) once this is merged.

**Comment by jkmassel** [comment]
Sorry about the wait @ScoutHarris – merged!

**Comment by ScoutHarris** [comment]
Thanks @jkmassel !

**Pull request merged**
