### PR TITLE
Adding Blog capabilities

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:
This is required by #5175. We need to track a Blog's Capabilities, in order to Enable / Disable the UI accordingly.

We're simply adding a `Capabilities` field to the Blog Entity (Transformable).

Needs Review: @astralbodies 
Thanks in advance Aaron!

cc @bummytime

### CODE REVIEW

**Comment by jleandroperez** [comment]
P.s: Sorry about the typo in `#d6b183c`'s description =(

**Comment by astralbodies** [comment]
@jleandroperez Pain will follow shortly.

**Comment by jleandroperez** [comment]
@astralbodies i thought Pain never... left.

Mwah ha ha

**Comment by astralbodies** [comment]
:shipit:

**Comment by jleandroperez** [comment]
Thanks sir!

**Pull request merged**
