### PR TITLE
[VoiceOver] Reader Detail: Hide “Attachment. PNG. File” dictation

### PR DESCRIPTION
**Pull request by shiki**
Refs #12866. 

This hides the dictated “Attachment. PNG. File“ message.

## Findings

The dictation was caused by the `ReaderPlaceholderAttachment`. The message gets dictated even for images. 

## Solution

For the life of me, I could not hide it from VoiceOver using `isAccessibilityElement`. I ended up using an empty `accessibilityLabel` instead. 

In addition, I also made the `CachedAnimatedImageView` used in `WPRichTextImage` accessible so when a user hovers over it, VoiceOver would announce that it's an image rather than be silent. 

## Testing

1. Turn VoiceOver on.
1. In Reader, navigate to a post with an image.
2. Hover over the first paragraph. Confirm that VoiceOver doesn't say ”Attachment. PNG. File” anymore and just proceeds to dictate the paragraph's content. 
4. Hover over an image. Confirm that VoiceOver will announce that it's an image.

Please also watch for regressions, particularly the one fixed by #12351. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

**Comment by shiki** [comment]
@aerych Can I bother you with this one? 🙂

**Comment by paskalem** [comment]
😄of course you can

**Comment by aerych** [comment]
@paskalem :( This sort of comment isn't very helpful.   It could be taken as you're answering for someone else, and its doesn't add any value to the thread.  It feels more like a random drive-by comment. 

We get very excited when new contributors take an interest in the project, and we'd like to be welcoming. If you've taken a real interest in WordPress for iOS, maybe have a quick peek at our [code of conduct](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/CODE-OF-CONDUCT.md), and our guide to [contributions](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/CONTRIBUTING.md).  :)

**Comment by shiki** [comment]
Thank you, Eric! 🙏

**Pull request merged**
