### PR TITLE
Notifications + Swift Mk 6: Application State Events

### PR DESCRIPTION
**Pull request by jleandroperez**
#### Details:
This PR adds no new functionality. We'll gradually migrate all of the Notifications-Y code over to Swift.
Once it's ready, we'll address code improvements / technical debt.

Reference #5613

--

#### Scenario A: Notifications List were Visible
1. Log into a dotcom account
2. Open the Notifications tab
3. Send the app to Background
4. Receive a new notification (like any of your own comments, that should do the trick)
5. Bring the app to Foreground

As a result, the badge should get immediately reset. Please, send the app to background, and receive a new notification. Verify that the badge count is correct (1).

#### Scenario A: Notifications List were Not Visible
1. Log into a dotcom account
2. Open the reader
3. Send the app to Background
4. Receive a new notification (like any of your own comments, that should do the trick)
5. Bring the app to Foreground
6. Send the app back to Background

Please, verify that the badge didn't get cleared out. Receive a new notification, and verify that the badge count is correct.

#### Scenario C: Logout
1. Log into a dotcom account
2. Open the Reader
3. Receive a new notification
4. Without opening the Notifications tab, logout from the app

Please, verify that the Badge got effectively cleared out.

Needs review: @kwonye 
Will, may i bother you with a (hopefully brief) review?

Thanks in advance!!

### CODE REVIEW

**Comment by kwonye** [comment]
@jleandroperez can you merge develop into this please? It's running into

` Exception occurred restoring state [<BlogListViewController 0x12692ea60> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key searchWrapperView.`

I'm guessing because of the UISearchController merge

**Comment by kwonye** [comment]
> fatal error: unexpectedly found nil while unwrapping an Optional value

in `NotificationsViewController+Extentions` line 331

Foregrounding app after receiving notification.

**Comment by jleandroperez** [comment]
@will crash fixed already in #5778, since it wasn't introduced here.

(Sorry about the issue!)

**Comment by will** [comment]
I'm glad when any crash is fixed, but I've never used wordpress

**Comment by jleandroperez** [comment]
@will LOOOL SORRY MAN!!! wrong will!!! have a terrific weekend sir, you made me laugh, quite violently. 

:hug:

**Comment by kwonye** [comment]
> crash fixed already in #5778, since it wasn't introduced here.

Can you go ahead and merge that branch/cherry-pick that commit into this PR please? Checked out that PR and it looks fine, but I don't feel merging this PR with a known crash.

**Comment by jleandroperez** [comment]
@kwonye crash fix merged in. Ready for another peek!

Thanks!

**Comment by kwonye** [comment]
When signing out, running into this crash

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NotificationsViewController handleDefaultAccountChangedNote:]: unrecognized selector sent to instance 0x14096cae0'`

**Comment by kwonye** [comment]
@jleandroperez trying something new: instead of waiting for you to make the appropriate fix, I just went ahead and did it and set up a PR against this branch. I've tested against #5783 and once that is merged, this PR is ready to :shipit:

**Comment by jleandroperez** [comment]
Thanks **a lot** for reviewing this one sir!!

**Pull request merged**
