### PR TITLE
Update Gravatar to 3.0.0

### PR DESCRIPTION
**Pull request by pinarol**
Fixes #

To test:

Me > My Profile > Update Profile Photo

## Regression Notes
1. Potential unintended areas of impact

Avatars URLs. In fact, nothing has changed about Avatar URLs but let's just be extra careful for unexpected regressions.

3. What I did to test those areas of impact (or what existing automated tests I relied on)

Smoke test avatars throughout the app.

4. What automated tests I added (or what prevented me from doing so)
1 unit test added. 1 updated.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [x] WordPress.com sites and self-hosted Jetpack sites.
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] VoiceOver.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] iPhone and iPad. 
- [x] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>Modules/Package.swift</code> was changed without updating its corresponding <code>Package.resolved</code>. Please resolve the Swift packages in Xcode.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pinarol** [comment]
@dangermattic

**Comment by pinarol** [comment]
About the [dangermattic warning](https://github.com/wordpress-mobile/WordPress-iOS/pull/23701#issuecomment-2437339455). I ran `swift package resolve` under `/Modules`. However, `Modules/Package.swift` is in `.gitignore` so not sure how to address that at the moment. 🤔 I will ask around. .

Edit: It turns out this is a false positive and the check will be removed.

**Comment by pinarol** [comment]
This is ready to review.

**Review by etoledom — APPROVED** [review]
Looks good! 🎉

**Pull request merged**
