### PR TITLE
Update My Sites icons to gridicons

### PR DESCRIPTION
**Pull request by mattmiklic**
Replaces the existing menu icon assets with new ones using gridicons. The new assets are PDFs, so the scale-specific PNG assets have been removed. The default blavatar has also been updated to use a gridicon.

Before (left) and after (right):
comparison

### CODE REVIEW

**Comment by mattmiklic** [comment]
One small issue I noticed while working on this: the first three icons (view site, WP admin, stats) are all perfectly sharp. All other icons are very slightly blurry. This is not related to the new assets; the same blurriness is present in the current icons. Is it possible that these icons are sitting on a subpixel, causing the blurriness? 

You can see it in this zoomed-in version of the Posts icon, both the current (left) and new (right) icons -- which are perfectly sharp in the original assets.

zoom

**Comment by koke** [comment]
One little trick: on the Simulator, you can check `Debug > Color Misaligned Images` and get this:

simulator screen shot 18 dec 2015 07 05 25

So it looks like those sections are on fractional pixels.

Coincidentally enough, I think we have `WPTableViewSectionHeaderFooterView` to blame. Our custom section headers/footers have to calculate their height, and they don't round up. I checked on this view, and the header height is `46.70361328125`. Add a simple `round()` to it, and you get this

simulator screen shot 18 dec 2015 07 10 10

I'm currently working on another branch to completely remove `WPTableViewSectionHeaderFooterView`, which I believe would fix this.

**Comment by mattmiklic** [comment]
> One little trick: on the Simulator, you can check Debug > Color Misaligned Images and get this:

> I'm currently working on another branch to completely remove WPTableViewSectionHeaderFooterView, which I believe would fix this.

Cool, thank you @koke! That's really useful to know.

Since you're working on a fix in another branch anyway, no need to worry about it here.

**Comment by jasmussen** [comment]
Looks like a pretty amazing upgrade to me!I don't have any serious concerns about this at all.

**Comment by shaunandrews** [comment]
Nice. More in line with the web. :+1:

**Comment by mattmiklic** [comment]
I think design-wise, this is ready to go as soon as someone can review the code.

**Comment by koke** [comment]
Looks good :shipit:

**Pull request merged**
