### PR TITLE
Reader: Removes obsolete code.

### PR DESCRIPTION
**Pull request by aerych**
Refs #4033 

Cleans up deprecated/obsolete code from the old Reader post list and post detail. 

Needs review @jleandroperez

### CODE REVIEW

**Comment by SergioEstevao** [comment]
Hi @aerych good job on this clean up! Do you know if you we still need this class? WPWebVideoViewController? or this is non related to the reader?

**Comment by jleandroperez** [comment]
Beautiful PR @aerych!!

:shipit:

**Comment by aerych** [comment]
> WPWebVideoViewController? or this is non related to the reader?

Hi @SergioEstevao!  Good catch.  I didn't notice this one and it looks like its been orphaned for a while.  I'll do a follow up PR to take care of it.

**Comment by aerych** [comment]
Thanks @jleandroperez !

**Pull request merged**
