### PR TITLE
Remove activity logs after logging out

### LINKED ISSUE #19913: Activity logs should be cleared
### Expected behavior
Activity Logs should be removed after logging out.

### Actual behavior
After logging out, activity logs aren't being removed. Internal discussion: p1673653812673169-slack-C011BKNU1V5

### Steps to reproduce the behavior
1. Launch the app and log in.
2. Use the app for a while.
3. Log out and log in with a different account.
4. Open Me screen by tapping your profile icon on the top of the screen.
5. Tap "Help & Support"
6. Tap "Activity Logs".
7. Look inside your saved logs and notice your logs from your logged out account is visible.

##### Tested on iPhone 14 Pro Simulator, iOS 16.2, WPiOS 21.5

### PR DESCRIPTION
**Pull request by staskus**
Fixes #19913

## Description

We do not delete activity logs when logging out.

Handling 2 cases:
- Logging out of WP.com site
- Removing self-hosted site

### Case 1: WP.com accounts:
1. Launch the app and log in.
2. Use the app for a while.
3. Log out and log in with a different account.
4. Open Me screen by tapping your profile icon on the top of the screen.
5. Tap "Help & Support"
6. Tap "Activity Logs".
7. Look inside your saved logs and confirm your logs from your logged-out account are **not visible**

### Case 2: Self-hosted site
1. Launch the app and log in to a self-hosted site with no .com account
2. Use the app for a while.
3. "Remove site" and log in with a different account
4. Open Me screen by tapping your profile icon on the top of the screen.
5. Tap "Help & Support"
6. Tap "Activity Logs".
7. Look inside your saved logs and confirm your logs from your remoted self-hosted site are **not visible**

### Case 3: Multiple sites, removing self-hosted site when more sites are available
1. Launch the app and log in
2. Add self-hosted site
3. Use the app for a while.
4. Remove self-hosted site, the app switches to another account
5. Open Me screen by tapping your profile icon on the top of the screen.
6. Tap "Help & Support"
7. Tap "Activity Logs".
8. Look inside your saved logs and confirm that logs **are visible**

## Regression Notes

1. Potential unintended areas of impact

Disrupting logout or site removal flows

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manually testing that account logout and site removal process continue working smoothly. Inspecting activity logs.

4. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by sla8c — APPROVED** [review]
@staskus LGTM and nice refactor + encapsulation into functions!  👍

**Comment by irfano** [comment]
All tests passed. ✅
Do we keep removed site logs in case 3 on purpose? I think we can remove them if it's easy to filter logs related to the removed site.

**Review by irfano — APPROVED** [review]
All tests passed. ✅
Do we keep removed site logs in case 3 on purpose? I think we can remove them if it's easy to filter logs related to the removed site.

**Comment by staskus** [comment]
> Do we keep removed site logs in case 3 on purpose? I think we can remove them if it's easy to filter logs related to the removed site.

@irfano thanks for testing! Not on purpose. We don't filter these activity logs by blogs, so if we switch between sites, we will have one set of logs. `Case 3` was to make sure that all logs are not deleted by accident only when one site is removed but account remains logged in.

**Pull request merged**
