### PR TITLE
When thumbnail is available make overlay transparent.

### LINKED ISSUE #8343: Media cells: Show thumbnail behind progress view when thumbnail becomes available

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #8343 

To test:
 - Start the app
 - Open a media library of a blog
 - Add new media using the async option
 - Check if thumbnail of media shows when upload starts.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@frosty updated the code, please have a look.

**Comment by SergioEstevao** [comment]
@bummytime can you have a look on this?

**Comment by bummytime** [comment]
On it @SergioEstevao!

**Comment by bummytime** [comment]
@frosty, get back on vacation!

**Pull request merged**
